foundryvtt/pf2e

- src/styles/actor/tabs/_actions.scss
Expanded actions with short names relative to the longest non breaking text in their description (usually content-links, which have `white-space: nowrap` applied) would see their first grid column grow larger as the character sheet was made narrower. This could be seen with Bon Mot at the default character sheet size, for example.
`1fr` is greedier than `auto` when allocating remaining space and prevents this behavior.
Before:
After:
> Ensure action icon grid column not grow larger than needed

- packs/rage-of-elements-bestiary/vegetable-lamb.json
- packs/spells/falling-stars.json
In my recent games I noticed that two items had data issues.
Vegetable Lamb now has correct Strikes.
Falling Stars variants now should work correctly for all variants, not just Airburst.
> Data updates for Vegetable Lamb and Falling Stars

- src/module/actor/character/feats.ts
Simple enough: the ancestry featgroup didn't account for the `hb_` prepended string for homebrew ancestries (and heritages), so when you tried to filter for those using the magnifying glass icons next to the ancestry feat slots, you'd get shown all ancestries' feats. 
Used the same logic as the class featgroup uses, then lifted out the now-common logic.
An alternate option would have been to modify either the slug or the filling up of `sameAs`, but neither felt like safe options. 
The previous logic would have worked if the homebrew ancestry / versatile heritage slugs started with `hb_`, but this isn't communicated anywhere, and honestly should not be expected considering no other feat or feature would need it.
So I think this is the most reasonable approach to fixing the issue.
> Fix ancestry featgroup not being able to filter for homebrew ancestries

- src/module/item/abstract-effect/data.ts
- src/module/item/affliction/data.ts
- src/module/item/affliction/document.ts
- src/scripts/handlebars.ts
- src/styles/item/_affliction-sheet.scss
- static/templates/items/affliction-details.hbs
- static/templates/items/affliction-sidebar.hbs
I am very tempted on making initial stage always 0 and then clamping to 1 during data preparation if there's no onset, to save us the extra checks. Let me know if that sounds like a better idea than what I did.
> Enforce min stage for unowned afflictions and add onset stage

- build/lib/compendium-pack.ts
Saves the folder data as `kingmaker-features_folders.json`
> Include embedded compendium folder definitions in `json-assets.zip`

- src/module/actor/conditions.ts
- src/module/item/base/document.ts
- src/module/rules/rule-element/ae-like.ts
- src/module/rules/rule-element/base.ts
- src/module/rules/rule-element/choice-set/rule-element.ts
- src/module/rules/rule-element/grant-item/rule-element.ts
- src/module/rules/rule-element/item-alteration/rule-element.ts
- src/module/rules/rule-element/roll-option.ts
This will have the effect of them waiting to run until after choice sets are resolved.
> Move AE-like/roll-option processing during item pre-creation to own method

- src/module/item/weapon/data.ts
- src/module/item/weapon/document.ts
- src/module/rules/rule-element/strike.ts
This also removes the hands-free predicate from Strike REs using the "fist" shorthand. Will follow up with a UI update that is wise to it.
> Mark some unarmed attacks as "grasping appendages"

- src/module/apps/compendium-browser/loader.ts
~~This is more of a workaround than a fix. The problem is that hazards and npcs live in the same packs but need different index fields and indexing npcs with added hazard fields would brick the bestiary tab checks.~~
~~This change ensures that either the hazard or the bestiary tab can be openeded first and the other one will still get fresh index data.~~
Closes #10928
> Remove superfluous `PackLoader#loadedPacks` cache

- static/templates/items/sheet.hbs
I could have tweaked a bunch of styles to no longer rely on editor/editor-content, but having variant description match the html of non-variants is probably better in the long run.
> Fix display of variant spell descriptions

- packs/classfeatures/amulet.json
- packs/classfeatures/bell.json
- packs/classfeatures/chalice.json
- packs/classfeatures/first-implement-and-esoterica.json
- packs/classfeatures/implement-adept.json
- packs/classfeatures/implement-paragon.json
- packs/classfeatures/lantern.json
- packs/classfeatures/mirror.json
- packs/classfeatures/regalia.json
- packs/classfeatures/second-adept.json
- packs/classfeatures/second-implement.json
- packs/classfeatures/third-implement.json
- packs/classfeatures/tome.json
- packs/classfeatures/wand.json
- packs/classfeatures/weapon.json
- src/module/rules/rule-element/choice-set/rule-element.ts
As the title says.
Replaces the hardcoded ChoiceSet lists in every implement-related class feature with `other-tags` based ChoiceSet filters and ItemAlterations.
All implements now have the `thaumaturge-implement` other tag. Second and Third Implement by default will not pick the already picked implements because class features by default get a `maxTakeable` of 1. 
Adept implements get the `thaumaturge-implement-adept` other tag, and Second Adept checks for its (non-)presence.
Paragon implements get the `thaumaturge-implement-paragon` other tag.
`adept:XYZ` and `paragon:XYZ` rollOptions are thrown out as literally nothing checks for them (but could _theoretically_ be readded if I add a `RollOption` RE to every implement that forces it to add the relevant rollOption when it has the …
> Allow Thaumaturge Implements to accept homebrew

- build/run-migration.ts
- packs/actions/devise-a-stratagem.json
- packs/feat-effects/effect-devise-a-stratagem.json
- packs/feats/athletic-strategist.json
- packs/feats/shared-stratagem.json
- packs/feats/takedown-expert.json
- packs/iconics/quinn-level-1.json
- packs/iconics/quinn-level-5.json
- packs/paizo-pregens/oraka.json
- src/module/migration/migrations/879-devise-a-stratagem-and-friends.ts
- src/module/migration/migrations/index.ts
- src/module/migration/runner/base.ts
- static/lang/re-en.json
This also removes the totm toggle, which doesn't really work alongside a token mark
> Migrate Devise a Stratagem and related feats to use token mark

- src/module/actor/character/elemental-blast.ts
- src/module/item/spell/document.ts
- src/module/system/damage/dialog.ts
- src/module/system/damage/formula.ts
- src/module/system/damage/helpers.ts
- src/module/system/damage/types.ts
- src/module/system/damage/weapon.ts
- src/module/system/text-editor.ts
There's still a few weapon vs not-weapon seams, but at least they're all in one place now for the clobbering later.
> Include damage dice overrides and criticals in dialog

- src/module/item/melee/data.ts
- src/module/item/melee/document.ts
- src/module/item/weapon/document.ts
- src/module/rules/rule-element/adjust-strike.ts
- src/module/system/damage/weapon.ts
Closes #7496
Warning to data contributors: this will actually add damage if the property rune provides it, so such runes generally aren't appropriate for NPCs.
> Add support for property-rune strike adjustments on melee items

- packs/blood-lords-bestiary/facetbound-cascader.json
- static/lang/re-en.json
If accepted, "Effect: Energy Ward" can be added to the migration/deletion list.
> Update Facetbound Cascader's Energy Ward from effect to RollOptions with suboptions

- src/module/item/physical/runes.ts
- src/module/system/damage/damage.ts
- src/styles/_tags.scss
This is to address the relatively common confusion over why vitality damage is being rolled against non-undead (or nothing).
Also move note that goes along with ghost touch rune to special tag:
> Conditionally roll vitality damage from property runes

- packs/spell-effects/spell-effect-weapon-surge-major-striking.json
- packs/spell-effects/spell-effect-weapon-surge.json
Can't make it expire on use since the basic one also adds damage.
Closes https://github.com/foundryvtt/pf2e/issues/11036
> Set Weapon Surge effect duration to 1 round

- src/module/item/spell/sheet.ts
- src/scripts/handlebars.ts
- static/templates/items/spell-overlay.hbs
This fixes the issue where creating an area for a heightened spell where the base spell doesn't have an area would be impossible to edit or remove.
> Fix creating and editing spell area for fixed heightening

- package-lock.json
- package.json
- packs/feat-effects/effect-aura-junction-fire.json
- src/module/actor/base.ts
This replaces "actor:uuid:*" with "actor:signature:*"
> Use a V5 UUID hash digest of Foundry UUIDs for roll options

- static/templates/items/armor-details.hbs
Also moves Hardness to before HP, as that's the ordering it displays in the books.
> Fix shield hardness label in armor sheet

- src/module/item/melee/document.ts
- src/module/system/damage/weapon.ts
> Fix NPC damage formula creation when precision/splash occurs first

- src/module/system/damage/helpers.ts
- src/module/system/damage/weapon.ts
Reverts foundryvtt/pf2e#11108. Superceded by https://github.com/foundryvtt/pf2e/pull/11118
> Revert "Fix fatal override when base damage type is overwritten"

- static/lang/en.json
- static/templates/actors/character/partials/sidebar.hbs
- static/templates/actors/npc/partials/sidebar.hbs
This fixes NPC shield stat labels, which broke sometime between 5.7.4 and 5.8.0 when the old localized text was removed.
For the moment I've pointed the text to the newer `PF2E.Actor.Character.Shield` and `PF2E.Item.Physical` strings since they're already there rather than adding `Shield` to `PF2E.Actor.NPC` and having duplicates there. I suspect it's best to have one place outside of Character and NPC for these shield specific strings but wasn't quite sure where, so let me know what/where is preferred.
Before: 
After:
> Fix NPC shield labels

- packs/equipment-effects/effect-disarm-success.json
- static/lang/action-en.json
Update the text for the success outcome to reflect the text in Player Core, and slightly refined the rule elements on the effect for the success outcome.
> Add remaster changes to disarm action macro

- src/module/item/armor/data.ts
- src/module/item/consumable/data.ts
- src/module/item/consumable/sheet.ts
- src/module/item/container/data.ts
- src/module/item/equipment/data.ts
- src/module/item/melee/document.ts
- src/module/item/physical/data.ts
- src/module/item/physical/document.ts
- src/module/item/weapon/data.ts
- src/module/system/damage/formula.ts
- src/module/system/text-editor.ts
- src/styles/item/_index.scss
- static/lang/en.json
- static/templates/items/action-details.hbs
- static/templates/items/consumable-details.hbs
> Add support for including material damage effects in consumable inline rolls

- src/module/actor/creature/spell-preparation-sheet.ts
- src/scripts/register-templates.ts
- src/styles/actor/_spell-collection.scss
- static/templates/actors/character/tabs/spellcasting.hbs
- static/templates/actors/npc/tabs/spells.hbs
- static/templates/actors/partials/spell-collection.hbs
- static/templates/actors/spell-preparation-sheet.hbs
Also addressed a minor issue involving resize behavior and extra whitespace in the spell preparation sheet caused by the lack of a casting button.
> Remove spell components from actor sheets

- src/module/item/spell/document.ts
The localized string was set as `data-save-type` on the save button:
> Fix `saveType` value in `SpellPF2e#getChatData`

- packs/spell-effects/spell-effect-weapon-surge.json
- packs/spells/weapon-surge.json
If accepted, the effect "Spell Effect: Weapon Surge (Major Striking)" can be added to the migrate/remove list.
> Update effect for Weapon Surge

- packs/spell-effects/spell-effect-sweet-dream.json
- packs/spells/sweet-dream.json
- static/lang/re-en.json
If accepted, "Spell Effect: Sweet Dream (Glamour)", "Spell Effect: Sweet Dream (Insight)", "Spell Effect: Sweet Dream (Voyaging)" can be added to the migrate/delete list
> Add unified effect for Sweet Dream and update

- packs/spells/rangers-bramble.json
Closes https://github.com/foundryvtt/pf2e/issues/11196
> Fix defense for Ranger's Bramble and auto-heighten damage link

- src/module/system/action-macros/athletics/long-jump.ts
- static/lang/action-en.json
Update the text with the default difficulty class to reflect the text in Player Core, and assign the default difficulty class for the action macro when no other DC is provided.
> Add remaster changes to long jump action macro

- src/module/system/action-macros/athletics/high-jump.ts
- static/lang/action-en.json
Update the outcome text to reflect the text in Player Core, and assign the default difficulty class for the action macro when no other DC is provided.
> Add remaster changes to high jump action macro

- src/module/actor/character/attribute-builder.ts
- src/module/actor/character/data.ts
- src/module/actor/character/document.ts
- static/template.json
This will fix the BB iconics in the premium module from ending up in manual mode.
> Change `CharacterPF2e#abilities` to `null` when using boosts

- packs/feats/lions-fury.json
- packs/npc-gallery/veteran-reclaimer.json
Needed as "PF2E.Item.Weapon.CriticalSpecialization.knife" has been removed
> Update critical specialization of Lion's Fury and Veteran Reclaimer

- src/module/rules/rule-element/item-alteration/alteration.ts
If using either `frequency-max` or `frequency-per` in ItemAlteration (or GrantItem's `alterations`), it will set a default if the item has no frequency before doing the alteration.
The default is simply the, well, default from `activateActionSheetListeners`.
I found that that one also hard-coded `"day"` as the `per` value rather than referring to `CONFIG.PF2E.frequencies.day`. I tried doing it with the `CONFIG` frequency values, but then it'd complain about mismatched types, string vs `FrequencyInterval`, so I went with `"day"` since there was an example of it already in the code -- and it's exactly what I want to replicate anyways.
I don't think this has an in-system example, this is a purely self-serving PR.
> Allow frequency ItemAlterations (`max` and `per`) to alter items without a frequency

- src/module/item/armor/document.ts
- src/module/item/weapon/document.ts
As the title says.
Decided to *only* modify the rollOptions and not the logic before it so anything that depended on an actual `null` value in-code or in modules need not change.
This rollOption change is just an additional value that didn't exist before, and `group:null` should be "unnatural" enough to not fuck anything over for modules and the like.
> Add `none` group to rollOptions for weapons and armour without groups

- src/module/apps/compendium-browser/index.ts
- static/templates/actors/character/tabs/spellcasting.hbs
- static/templates/actors/partials/spell-collection.hbs
Focus spells (non-cantrip) were adding both Spell and Focus category, which was causing issues. Similarly, Ritual was being added twice.
Not sure if this is the 100% best way to fix it but it works for me ™️
> Fix opening spellbook from focus and ritual entries

- src/module/apps/compendium-browser/tabs/spell.ts
Without this when searching while you have 1 or more categories selected categories would be undefined, causing an exception to be raised.
> Add categories to spell tab storeFields so search works with category filter

- packs/equipment-effects/effect-batsbreath-cane.json
It did not work properly when applied before this fix.
> Rename Hearing to Echolocation in Batsbreath Cane Effect

- src/module/system/settings/homebrew/data.ts
- src/module/system/settings/homebrew/helpers.ts
- src/module/system/settings/homebrew/menu.ts
It was previously allowed for world settings, this extends it to modules.
> Allow null categories in module custom damage

- packs/actions/shed-spirit.json
- packs/actions/stitching-strike.json
Closes https://github.com/foundryvtt/pf2e/issues/11451
Using max() so that the base damage hover text works as expected.
> Update damage links in Shed Spirit and Stitching Strike to autolevel

- src/module/system/settings/homebrew/menu.ts
- types/foundry/common/primitives/set.d.ts
Technically a bugfix, though the bug has already been fixed. This is mostly future proofing to avoid the bug resurfacing again at a later date.
> Cleanup custom damage versatile traits (and restrict deletion to damage types only)

- src/module/system/settings/homebrew/menu.ts
Tagify takes care of this, and it turns out the form can't be submitted if there are pre-existing reserved terms
> Remove calls to `HTMLInputElement#setCustomValidity`

- packs/feats/channeling-block.json
- packs/feats/lasting-armament.json
- packs/feats/restorative-channel.json
- packs/feats/spellshape-channel.json
Fixes https://github.com/foundryvtt/pf2e/issues/11530
Updates Lasting Armament, Restorative Channel, and Spellshape Channel to Remaster.
> Correct Channeling Block level and Mark Others as Remastered

- packs/feats/snarecrafter-dedication.json
Change the maximum craftable item level from the default to the actor level instead of using the default to 1 for the CraftingEntry rule element.
> Fix maximum craftable item level for snarecrafter dedication

- packs/feats/witchs-armaments.json
Witches Armaments was not adding the selected strike to the players character sheets because the predicate specified "witchs-armament" instead of "witchs-armaments"
> Fix Witches Armaments not adding the selected strike to character sheet

- packs/classfeatures/antipaladin.json
- packs/classfeatures/champions-code.json
- packs/classfeatures/desecrator.json
- packs/classfeatures/liberator.json
- packs/classfeatures/paladin.json
- packs/classfeatures/redeemer.json
- packs/classfeatures/tyrant.json
Adds a predicate to check which variant of the Champion is selected and only add the Tenets of Evil or Tenets of Good based on that selection.
> Update REs on Champion's Code to not Add both Holy and Unholy when selecting a Deity that adds both

- packs/classfeatures/antipaladin.json
- packs/classfeatures/desecrator.json
- packs/classfeatures/liberator.json
- packs/classfeatures/paladin.json
- packs/classfeatures/redeemer.json
- packs/classfeatures/tyrant.json
- static/lang/re-en.json
Paladin needs the general toggle for retributive strike since some feats key off making one, it will just be inert until they get a feat like shining oath or the divine smite feature.
> Improve automation for granting champion reactions

- src/module/actor/character/elemental-blast.ts
Added the melee-attack-roll and ranged-attack-roll domains will require a migration, so roll option only for now.
Closes https://github.com/foundryvtt/pf2e/issues/10722
> Add melee/ranged and damage type to elemental blast roll options

- src/module/migration/migrations/882-spell-data-reorganization.ts
- static/templates/chat/spell-card.hbs
the recent migration (12 days ago) did not migrate the code itself to use the new name
> Fix spell counteraction property reference in template file

- src/module/rules/rule-element/item-alteration/alteration.ts
> Reinclude AC bonus from potency rune following override-mode item alterations

- src/module/item/class/document.ts
This is to allow for one class feature to be informed by another despite coming later if sorted alphabetically or by presence of choice sets.
> Only sort class-granted class features by level

- src/module/migration/migrations/881-no-hb-prefix.ts
Anyone with broken IWR homebrew types should run `game.pf2e.system.remigrate({ from: 0.881, to: 0.881 })`
> Add homebrew IWR to Migration 881

- packs/classfeatures/animal-instinct.json
This affects case-sensitive file systems
Closes https://github.com/foundryvtt/pf2e/issues/11697
> Fix capitalization on Animal Instinct tongue image name

- src/module/actor/party/document.ts
The BBEG travelling with the party to kill a bigger BBEG is unfortunately too common a story trope, and the GM might not have updated the alliance, so I test for "has friendly" first.
> Set party alliance based on contained members

- src/module/actor/army/document.ts
- src/module/actor/base.ts
- src/module/item/base/document.ts
- src/module/item/helpers.ts
- static/lang/kingmaker-en.json
This has impact on the core embedded item creation workflow, so this will need eyes on it. Technically the item helpers type is incorrect, though it was never really correct.
> Block invalid tactic types from armies

- static/templates/actors/character/tabs/general.hbs
nearly the easiest pull request of your life. This changes the icon from a plus to a magnifying glass, which is consistent with behavior throughout the rest of the character sheet
> Use magnifying glass icon consistently

- packs/spell-effects/spell-effect-untamed-shift.json
The _untamed shift_ spell was no longer allowing two (or three) options to be selected if the spell was cast at a heightened level. This patch fixes that to restore the intended functionality.
> Fix Untamed Shift effect heightening

- src/module/rules/rule-element/battle-form/rule-element.ts
Also avoid purging synthetic strikes with `battleForm` flag
> Fix preparation of range data in BattleForm RE strikes

- static/lang/en.json
This was just a minor error that was missed during the item bulk refactor: the modified localisation strings don't have the nested `Bulk` level.
> Fix recently adjusted container bulk localisation strings

- src/module/actor/army/data.ts
- src/module/actor/army/document.ts
- src/module/actor/army/sheet.ts
- src/styles/actor/army/_index.scss
- static/lang/kingmaker-en.json
- static/template.json
- static/templates/actors/army/sheet.hbs
Armies often only have one type of strike and need to purchase the other one.
> Make army strikes optional

- src/module/item/consumable/data.ts
- src/module/item/consumable/document.ts
- static/templates/actors/partials/item-summary.hbs
The button in item summary only shows "Use" now, which is consistent with using consumables via chat.
The template's default formula value is "" but some entries in our database have a formula of null. Given all of this is going to need tweaking anyways (and I don't see what coerces "" to null), I widened the type to handle the possible error from clicking use on items such as Cold Iron Blanch.
I'm tempted on removing the use button from item summaries outright though, but I guess they can be useful for like healing potions...
> Fix consumable summary use localization regression, and only show button if there's no formula

- src/module/chat-message/helpers.ts
- static/lang/en.json
- static/templates/chat/damage/adjustment-dialog.hbs
1. Remove initial value from damage/healing adjustment dialog (leaving placeholder)
2. Alter title of damage/healing adjustment dialog depending on damage vs healing
The first change is needed because otherwise a user that immediately starts typing after the dialog opens up will get an extra 0 appended to the end - meaning they'll deal 10 times as much extra damage (or healing).
Before:
After:
> Improve damage/healing adjustment dialog

- packs/feat-effects/effect-kaiju-form.json
- packs/feats/heart-of-the-kaiju.json
- packs/spell-effects/spell-effect-monstrosity-form-kaiju.json
Wasn't sure if it should be a feat effect or a spell effect since access is granted by a feat, but the effect is applied via the Untamed Form spell.
~~Ultimately went with feat effect, since it's the primary source.~~
Now a spell effect to group with the other Monstrosity Forms.
Closes https://github.com/foundryvtt/pf2e/issues/11904
> Add effect for Heart of the Kaiju

- packs/feats/brutal-bully.json
- packs/feats/overpowering-charge.json
Closes https://github.com/foundryvtt/pf2e/issues/11982
> Fix inline roll for Brutal Bully and Overpowering Charge and emit note on critical success

- packs/deities/lamashtu.json
Corrects Lamashtu’s Level 1 Cleric Spell to Spider Sting, and updates her Anathema and Edicts according to changes made in PC1.
Closes [#11516](https://github.com/foundryvtt/pf2e/issues/11516).
> Update Lamashtu for Remaster

- src/module/actor/character/document.ts
- Don't show raise-a-shield action if the effect is present at all
- Revert back to previous `canWield2H` check except still show button for wielding shields with two hands
> Reduce number of auxiliary actions appearing on PC sheet

- src/module/actor/character/attribute-builder.ts
Lines were deleted in an old refactor.
> Fix regression in ancestry flaws tooltip

- src/module/canvas/layer/template.ts
Adds the `passive: false` option to the wheel listener and uses an `AbortController` to avoid using `removeEventListeners` with options.
Warning for reference:
> Handle template preview wheel listeners warning

- src/styles/_globals.scss
- src/styles/actor/_index.scss
- src/styles/item/_header.scss
- src/styles/item/_index.scss
- src/styles/item/_nav.scss
This is to make it easier for them to override general styling
Also:
- Move item-sheet nav styling to own file
- Move global font-family and h1-h6 overrides to individual sheets
> Import item-type-specific scss files after main item-sheet styling

- src/styles/item/_header.scss
before (hide armor shown for comparison)
after (hide armor shown for comparison)
> Reduce vertical separation in item sheets with action glyph

- src/module/migration/migrations/828-prune-invalid-traits.ts
Now that module-provided homebrew traits are stored without the "hb_" prefix, migration 828 suddenly considers them invalid and prunes them. This would only affect modules with compendium content that hasn't been migrated since then.
> Adjust migration 828 to skip "hb_" traits

- packs/spells/puff-of-poison.json
Per the official Secrets of Magic [errata](https://paizo.com/pathfinder/remaster/faq)
> Page 124: In the puff of poison spell, replace "poison damage equal to your spellcasting modifier and 2 persistent poison damage" with "1d8 poison damage and 2 persistent poison damage".
> Update Puff of Poison with Remaster errata

- packs/outlaws-of-alkenstar-bestiary/trapjaw-tangle.json
got a report to the Outlaws of Alkenstar premium module, fixing it here
> Fix the Athletics modifier RE on Trip and Tangle

- src/module/item/base/document.ts
For the use case of batch calling this method on many items, where a summary is being provided. not having several tens of notifications to click through is a better user experience.
> Allow suppression of ui notifications in refreshFromCompendium

- src/module/actor/sheet/item-summary-renderer.ts
The await is necessary so foundry's built in "restore scroll y" feature runs after the item summaries are opened.
> Fix regression restoring scroll positions after re-render

- packs/kingmaker-bestiary/_folders.json
- packs/kingmaker-bestiary/armies/basic-cavalry.json
- packs/kingmaker-bestiary/armies/basic-infantry.json
- packs/kingmaker-bestiary/armies/basic-siege-engines.json
- packs/kingmaker-bestiary/armies/basic-skirmishers.json
- packs/kingmaker-bestiary/armies/catspaw-marauders.json
- packs/kingmaker-bestiary/armies/drelev-irregulars.json
- packs/kingmaker-bestiary/armies/first-world-army.json
- packs/kingmaker-bestiary/armies/narlmarch-hunters.json
- packs/kingmaker-bestiary/armies/pitax-horde.json
- packs/kingmaker-bestiary/armies/pitax-war-machines.json
- packs/kingmaker-bestiary/armies/pitaxian-raiders.json
- packs/kingmaker-bestiary/armies/tatzlford-town-guard.json
- packs/kingmaker-bestiary/armies/troll-marauders.json
- packs/kingmaker-bestiary/armies/tusker-riders.json
- packs/kingmaker-bestiary/armies/wyvern-flight.json
- src/module/item/base/document.ts
- src/module/item/campaign-feature/document.ts
Some limitations are discussed here:
https://github.com/foundryvtt/pf2e/issues/12161
Most notably this does not include the appendix actors yet, only the ones that are used in the adventure itself
> Add actors to the Kingmaker compendium to represent armies

- packs/bestiary-effects/effect-stoke-the-fervent.json
- packs/extinction-curse-bestiary/urdefhan-high-tormentor.json
- packs/pathfinder-bestiary-2/urdefhan-tormentor.json
- packs/pfs-season-4-bestiary/urdefhan-high-tormentor-pfs-4-11.json
Renamed "Effect: Stoke the Fervent - High Tormentor" to "Effect: Stoke the Fervent (High Tormentor)" so that auto-labeling works without changing the slug.
> Add effect for Stoke the Fervent

- src/module/item/ability/document.ts
- src/module/item/melee/document.ts
- src/module/item/spell/document.ts
- src/module/item/weapon/document.ts
(during data preparation, not from compendium data)
> Filter out inactive homebrew/legacy traits from certain item types

- src/module/encounter/document.ts
When an encounter hasn't started yet, rolling initiative causes the current turn to be set to that combatant. This will ensure that turn remains null when rolling initiative before combat starts.
> Not setting the turn value if an encounter hasn't started yet

- src/module/system/text-editor.ts
- src/styles/mixins/_typography.scss
I would super appreciate some testing to make sure I didn't break any existing localizations, though roll notes and attack of opportunity seem to be working fine in this respect.
> Fix invalid spacing in journals created with prosemirror

- src/module/system/text-editor.ts
Using updated Stupefied, and opened from the Compendium.
Before:
After:
> Allow check DCs to resolve for an item with no actor

- packs/feats/vengeful-spirit-deck.json
Also added spellshape trait since source lists it as metamagic
Closes https://github.com/foundryvtt/pf2e/issues/12283
> Fix action cost of Vengeful Spirit Deck and autolevel damage links

- src/module/system/action-macros/athletics/force-open.ts
- src/module/system/action-macros/index.ts
- static/lang/action-en.json
Update the outcome text to reflect the text in Player Core. Also convert it to an action object and add the remaster description.
> Add remaster changes to force open action macro

- src/module/system/action-macros/athletics/climb.ts
- src/module/system/action-macros/index.ts
- static/lang/action-en.json
Update the outcome text to reflect the text in Player Core. Also convert it to an action object and add the remaster description.
> Add remaster changes to climb action macro

- src/module/system/action-macros/athletics/swim.ts
- src/module/system/action-macros/index.ts
- static/lang/action-en.json
Update the outcome text to reflect the text in Player Core. Also convert it to an action object and add the remaster description.
> Add remaster changes to swim action macro

- packs/campaign-effects/effect-tiger-form.json
The land speed of the Tiger Form effect (from Fists of the Ruby Phoenix) was set to 40 feet, probably a copy-paste error from the Boar Form effect from the same module. It should actually be 30 feet according to the module (both the initial printing and the hardcover compilation).
> Fix land speed of Tiger Form effect

- packs/equipment-effects/effect-fury-cocktail-greater.json
- packs/equipment-effects/effect-fury-cocktail-lesser.json
- packs/equipment-effects/effect-fury-cocktail-moderate.json
Noticed in production - missed a level in the localization.
> Fix label path for Fury Cocktail

- packs/feat-effects/effect-oceans-balm.json
- packs/feats/oceans-balm.json
Adds an effect for Ocean's Balm. 
The healing is still from the feat, but the effect allows the correct fire resistance value and duration to be tracked. 
This does not track the timed healing immunity.
> Add Effect for Ocean's Balm

- build/lib/extractor.ts
- build/run-migration.ts
- src/module/item/armor/data.ts
- src/module/item/base/document.ts
- src/module/item/book/data.ts
- src/module/item/equipment/data.ts
- src/module/item/physical/document.ts
- src/module/item/shield/data.ts
- src/module/item/spell/document.ts
- src/module/item/weapon/data.ts
- src/module/item/weapon/document.ts
- src/module/migration/runner/base.ts
- src/module/migration/runner/index.ts
- static/template.json
- tests/mocks/actor.ts
- tests/module/migration.test.ts
Starting with just their inert presence for easier review
> Build out basic structure for doubly-embedded items

- packs/feats/advanced-runic-mind-smithing.json
- packs/feats/runic-mind-smithing.json
Removes the axiomatic and anarchic runes from Advanced feat and changes disrupting to vitalizing in the base feat.
> Change Runic Mindsmith feats to the remaster runes

- packs/other-effects/effect-aid.json
Since Aid is a reaction triggered for a single, specific roll, I figure it makes sense for it to be removed after the roll.
> Add removeAfterRoll to Aid effect

- packs/feats/syu-tak-nwas-deadly-hair.json
Reported on discord.
Also adds the missing Grapple trait the feat provides.
> Fix Deadly Hair Feat to apply to Living Hair

- src/scripts/ui/inline-roll-links.ts
This is a very rarely used feature so I'm fine not including an angle property in `@Template` and telling people to use the older HTML style.
> Allow for user defined cone angles in HTML inline templates

- src/module/actor/base.ts
- src/module/item/physical/document.ts
- src/module/rules/rule-element/item-alteration/rule-element.ts
This prevents issues from occuring where a physical item's `_preUpdate` method rejects an update to hit points after testing against a clone because the clone does not have the new item carrying HP-altering the rule element.
> Skip clamping hit points when item alterations make updates

- packs/classfeatures/animal-order.json
- packs/classfeatures/flame-order.json
- packs/classfeatures/leaf-order.json
- packs/classfeatures/stone-order.json
- packs/classfeatures/storm-order.json
- packs/classfeatures/untamed-order.json
- packs/classfeatures/wave-order.json
There is no grant on the order for dedication taken as part of the druid dedication, but order explorer allows *only* the feat and no other items from the dedication. This fixes the rule elements for each order to allow order explorer to grant the feat even if only a druid dedication is present.
Closes #9825.
> Allow order explorer to grant order feat automatically for dedication

- packs/feats/multishot-stance.json
Multishot Stance's prerequisite changed from Triple Shot to Double Shot in Player Core 1.
> Fix Multishot Stance's prerequisite feat

- src/module/system/action-macros/diplomacy/make-an-impression.ts
- src/module/system/action-macros/index.ts
- static/lang/action-en.json
Convert it to an action object and add the remaster description.
> Add remaster changes to make an impression action macro

- src/module/system/action-macros/deception/create-a-diversion.ts
- src/module/system/action-macros/index.ts
- static/lang/action-en.json
Convert it to an action object and add the remaster description.
> Add remaster changes to create a diversion action macro

- src/module/system/action-macros/helpers.ts
- static/templates/actors/actions/base/chat-message-content.hbs
- static/templates/actors/actions/simple/chat-message-flavor.hbs
> Align header of action chat cards to consistently show action glyph in the same place

- packs/book-of-the-dead-bestiary/llorona.json
- packs/pfs-season-3-bestiary/wailing-ghost.json
Closes #12523
Scanned and found Wailing Ghost had the same issue, so fixed as well in this PR.
> Fix Llorona's Wail to use @Template

- src/module/rules/rule-element/flat-modifier.ts
This prevents empty array from getting cleared out by the form's clearing behavior. FlatModifier's without a selector property now complain about selector cannot be undefined instead of "must have at least 1".
> Restore converting selector to array for fresh flat modifier forms

- packs/feats/basic-witchcraft.json
Closes #12539
I tested it and Witch Dedication appears to already provide a correct familiar ability count.
> Change Basic Witchcraft to provide 3 familiar abilities per PC1

- packs/book-of-the-dead-bestiary/siabrae.json
Closes #12543
Confirmed Earth Glide and Miasma were missing from the abilities block per the Book of the Dead. Also provided the correct DC for Miasma.
> Add two missing abilities to Siabrae NPC

- src/module/item/spellcasting-entry/trick.ts
- src/module/system/statistic/data.ts
- src/module/system/statistic/statistic.ts
Also make creation of untrained bonus wise to PwoL setting
> Remove usage of "untrained-level" rank in `Statistic`

- src/styles/actor/character/_sidebar.scss
- static/templates/actors/character/partials/sidebar.hbs
Make certain sidebar modifiers clickable instead of using a button.
> Make modifiers in sidebar clickable to open up tooltip

- packs/feats/accursed-clay-fist.json
- packs/feats/golem-grafter-dedication.json
- packs/feats/iron-lung.json
- packs/feats/legs-of-stone.json
- packs/feats/quicken-heartbeat.json
Touches up the Golem Grafter Dedication feat chain and adds REs where needed.
> Add REs to Golem Grafter Archetype feats

- src/module/actor/base.ts
Now that users may wish to enable vision for NPCs via the token defaults setting, it should still be prevented for hazards so they don't get unusable vision.
> Disable sight for hazards on actor creation

- packs/spell-effects/spell-effect-amplifying-touch.json
> In the Amplifying Touch feat, replace "deals 1 additional good damage on all their Strikes" with "deals 1 additional spirit damage on all their Strikes". Add the following sentence at the end of the feat's description, "In addition, all their Strikes are holy until the end of their next turn."
Per the remaster compatibility errata. 
I tested and adding a weapon-trait of Holy seems to work with any Strike. Not 100% if that's the correct way to do that though.
> Add Holy and correct duration to Amplifying Touch Effect

- packs/spells/litany-of-depravity.json
> Page 228: In the litany of depravity focus spell, replace the Targets line "1 good creature" with "1 creature that isn't unholy" and replace "weakness 7 to evil" with "weakness 7 to unholy".
> Change Litany of Depravity's target per the remaster errata

- src/module/actor/character/sheet.ts
- src/module/actor/sheet/base.ts
- src/styles/actor/character/_character.scss
- static/templates/actors/character/tabs/character.hbs
The simpler tag styling languages had in the screenshot is not an available global tag styling, and I'll have to come up with a name and perhaps a tweak, since those were actually meant for the party sheet. The one in this current PR uses the normal tags. I'll think on all that later.
> Update PC languages, speed, and traits styling

- src/module/actor/actions/base.ts
- static/lang/action-en.json
Change `BaseAction#getDefaultVariant` from being asynchronous to being synchronous since the asynchronicity was not necessary and future synchronous use cases are anticipated.
> Refactor getDefaultVariant method on BaseAction to be synchronous

- src/module/actor/actions/base.ts
- src/module/actor/actions/types.ts
- src/module/system/action-macros/acrobatics/balance.ts
- src/module/system/action-macros/acrobatics/maneuver-in-flight.ts
- src/module/system/action-macros/acrobatics/squeeze.ts
- src/module/system/action-macros/athletics/climb.ts
- src/module/system/action-macros/athletics/force-open.ts
- src/module/system/action-macros/athletics/swim.ts
- src/module/system/action-macros/diplomacy/gather-information.ts
- src/module/system/action-macros/exploration/sense-direction.ts
- src/module/system/action-macros/exploration/track.ts
- src/module/system/action-macros/general/decipher-writing.ts
- src/module/system/action-macros/general/subsist.ts
- src/module/system/action-macros/performance/perform.ts
- src/scripts/config/index.ts
- static/lang/action-en.json
- static/templates/actors/actions/base/chat-message-content.hbs
Include refactored data for all the actions currently existing in the system as action objects.
> Extract action sample tasks as separate data field

- packs/classfeatures/bravery.json
Not sure "success" needs to be in there because the RE upgrades to Critical Success automatically, but left it in just in case.
> Add outcomes to the bravery note RE

- packs/classfeatures/lesson-of-bargains.json
- packs/classfeatures/lesson-of-calamity.json
- packs/classfeatures/lesson-of-death.json
- packs/classfeatures/lesson-of-dreams.json
- packs/classfeatures/lesson-of-elements.json
- packs/classfeatures/lesson-of-favors.json
- packs/classfeatures/lesson-of-life.json
- packs/classfeatures/lesson-of-mischief.json
- packs/classfeatures/lesson-of-protection.json
- packs/classfeatures/lesson-of-renewal.json
- packs/classfeatures/lesson-of-shadow.json
- packs/classfeatures/lesson-of-snow.json
- packs/classfeatures/lesson-of-the-frozen-queen.json
- packs/classfeatures/lesson-of-vengeance.json
- packs/feats/basic-lesson.json
- packs/feats/greater-lesson.json
- packs/feats/major-lesson.json
Not *necessarily* needed for the Witches+ Remaster module, I could just duplicate the Basic / Greater / Major Lesson feats, but this is probably "more proper" this way.
> Update witch lessons to use otherTags

- packs/classes/barbarian.json
- packs/classfeatures/heightened-senses.json
- packs/feat-effects/effect-scouts-warning.json
- packs/iconics/amiri-level-1.json
- packs/iconics/amiri-level-3.json
- packs/iconics/amiri-level-5.json
- packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
- packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
- packs/paizo-pregens/popcorn-level-4.json
- packs/paizo-pregens/popcorn.json
> Update effect for Scout's Warning to removeAfterRoll

- packs/feats/cut-from-the-air.json
Also remove selfEffect as it's handled by the feat's RollOption
> Brush up automation for Cut from the Air

- packs/classfeatures/ruffian.json
> When you gain light armor expertise, you also gain expert proficiency in medium armor, and when you gain light armor mastery, you also gain master proficiency in medium armor.
The wording is identical in Core Rulebook / Player Core 1, so I guess it's just a long standing data bug.
Works on my local install and I can't think of any feats that would 'break' the logic, but would definitely appreciate someone else having a look!
> Fix Ruffian Rogue armor proficiency

- src/module/actor/spellcasting.ts
- src/module/chat-message/document.ts
- src/module/item/spell/document.ts
- src/module/item/spellcasting-entry/trick.ts
loadVariant() might need to be repurposed into a more general cloning method that never returns null.
Closes https://github.com/foundryvtt/pf2e/issues/12538
> Fix spellcasting entry assignment for scroll/wand spells

- packs/feats/weapon-proficiency.json
Closes #12674
Weapon Prof in the remaster can be taken repeatedly, so made sure that was reflected as well.
> Update Weapon Proficiency Feat for the remaster

- packs/heritages/hillock-halfling.json
- packs/heritages/jinxed-halfling.json
- packs/heritages/nomadic-halfling.json
- packs/heritages/twilight-halfling.json
- packs/heritages/wildwood-halfling.json
took the chance to fix publication data from the rest of Player Core halfling heritages too
> Add level to Hilllock Halfling's healing received from Treat Wounds

- src/module/item/abc/data.ts
- src/module/item/ability/data.ts
- src/module/item/affliction/data.ts
- src/module/item/ancestry/data.ts
- src/module/item/armor/data.ts
- src/module/item/background/data.ts
- src/module/item/base/data/system.ts
- src/module/item/book/data.ts
- src/module/item/campaign-feature/data.ts
- src/module/item/class/data.ts
- src/module/item/condition/data.ts
- src/module/item/consumable/data.ts
- src/module/item/container/data.ts
- src/module/item/deity/data.ts
- src/module/item/effect/data.ts
- src/module/item/equipment/data.ts
- src/module/item/feat/data.ts
- src/module/item/heritage/data.ts
- src/module/item/kit/data.ts
- src/module/item/lore.ts
- src/module/item/melee/data.ts
- src/module/item/physical/data.ts
- src/module/item/shield/data.ts
- src/module/item/spell/data.ts
- src/module/item/spellcasting-entry/data.ts
- src/module/item/weapon/data.ts
- src/module/migration/migrations/742-rm-class-ability-boost-levels.ts
- src/module/migration/migrations/767-convert-voluntary-flaws.ts
- src/module/rules/rule-element/item-alteration/alteration.ts
- src/module/rules/rule-element/item-alteration/schemas.ts
An alternative to previously requested "item notes". This has a large types update, so I just added the alteration validator and data structure for it. Will follow up with rest of implementation if/when this PR is merged.
> Add `description` item alteration

- src/module/item/physical/document.ts
- src/scripts/config/traits.ts
From rudimentary testing, rule elements don't trigger on items that are invested but not in the right usage status, which I believe is what we want.
> Relax equipped check for invested non-worn items

- packs/spell-effects/spell-effect-ki-form.json
Closes #12745
I've opted to replace it with spirit damage, going off Ki Strike [here](https://github.com/foundryvtt/pf2e/pull/11375). Let me know if I should just remove it instead.
> Replace Ki Form's lawful damage with spirit

- packs/classes/ranger.json
> Fix level of Ranger's Perception Legend feature

- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
Specifically when a language has been both manually and automatically added
> Fix cases of erroneous PC language slot calculations

- packs/spell-effects/spell-effect-ghostly-weapon.json
- packs/spells/ghostly-weapon.json
Also add magical trait to weapon.
Closes https://github.com/foundryvtt/pf2e/issues/12825
> Fix Ghostly Weapon to apply only to selected weapon

- src/styles/packs/_tab.scss
Also slightly reduces padding and removes unnecessary margin from rarity tags in compendium browser to keep within 2em height.
Before:
After
Could also set `aspect-ratio: 1/1;` and `object-fit: contain;` on the image itself if keeping a uniform height across all rows is desired, though some images will be hard to see.
> Fix overlapping images in compendium browser

- static/templates/items/ancestry-sidebar.hbs
Fixes #12835 
option had old value `lowLightVision` and would throw the following error.
After:
> Fix outdated ancestry sheet low-light-vision value

- src/util/misc.ts
Fix expand/collapse item descriptions on mobile by adding a 500ms delay to drag-n-drop sort
> Add 500ms delay for Drag-n-Drop sort for touch

- static/templates/actors/character/tabs/proficiencies.hbs
- static/templates/actors/character/tabs/spellcasting.hbs
Some buttons on character sheet were missing `type="button"`. This caused a click event on them to be triggered via implicit submission if enter was pressed on the keyboard while within one of a sheet's text inputs.
> Prevent erroneous triggering of sheet handlers

- src/module/actor/hazard/sheet.ts
- src/module/actor/sheet/base.ts
- src/styles/actor/hazard/_header.scss
- static/templates/actors/hazard/partials/header.hbs
- static/templates/actors/hazard/partials/sidebar.hbs
- static/templates/actors/hazard/sheet.hbs
Includes updating base sheet class's `data-property` handler to accommodate nullable numeric values
> Kill the jquery in hazard sheet

- packs/spell-effects/spell-effect-everlight.json
- packs/spells/everlight.json
While Everlight doesn't technically affect a creature, this will handle the common use-case.
> Add spell effect for Everlight

- packs/feats/cauldron.json
- static/lang/re-en.json
Closes #11595
RAW the feat doesn't seem to limit the level of the item, so I didn't include that in the RE. It also seems like the follow up feat [Double, Double](https://app.demiplane.com/nexus/pathfinder2e/feats/double-double-rm) isn't possible to implement right now, unless I'm missing something.
> Add Witch's Cauldron Crafting Entry

- src/styles/item/_index.scss
- static/templates/items/spell-details.hbs
> Fix sustained/basic save spell toggle sizing

- src/styles/_globals.scss
Most visible scenario is chat message headings:
Another scenario is NPC actions.
> Prevent action glyphs from inheriting bold styling

- src/styles/item/_sidebar.scss
- src/styles/item/_spell-sheet.scss
- static/templates/items/action-details.hbs
- static/templates/items/campaign-feature-sidebar.hbs
- static/templates/items/feat-sidebar.hbs
- static/templates/items/heritage-sidebar.hbs
Fixed heightening still needs better separation of ranks but its a start.
Also fixes positioning of death note checkbox.
> Tweak spacing in item sidebar and spell heightening

- src/styles/actor/_index.scss
- src/styles/actor/_spell-collection.scss
Closes #13012
Restores `z-index: 0` removed in #12936, long text still works.
> Restore heightened signature spell background color

- src/module/actor/actions/single-check.ts
Providing just a number for a check DC is such a common use-case that it warrants direct support, instead of having to wrap it up in an object. The original syntax, as well as a `DCSlug`, is still a valid value.
**Before**
```js
game.pf2e.actions.get("climb").use({ difficultyClass: { value: 31 } });
```
**After**
```js
game.pf2e.actions.get("climb").use({ difficultyClass: 31 });
```
> Add support for providing a numeric difficulty class parameter on action use

- packs/pathfinder-bestiary/wraith.json
As per [AoN](https://2e.aonprd.com/Monsters.aspx?ID=417), [pf2etools](https://pf2etools.com/bestiary/wraith-b1.html), and my own copy of the Bestiary.
> Fix Wraith having Aklo instead of Necril

- packs/classfeatures/impulses.json
- packs/feats/base-kinesis.json
Closes #13066
Also makes the Base Kinesis grant the corresponding impulse action.
> Fix Kineticist Dedication wrongly granting Base Kinesis

- packs/agents-of-edgewatch-bestiary/teraphant.json
Teraphant actually has **e**motion sense, not motion sense.
> Fix Teraphant senses

- packs/feats/mountain-skin.json
Closes #12980
The feat already granted medium and heavy armor proficiency over on the details tab's proficiencies. This adds upgrading with respect to light armor proficiency.
> Add scaling to Mountain Skin's armor proficiency

- packs/age-of-ashes-bestiary/xotani-the-firebleeder.json
- packs/blood-lords-bestiary/vampire-taviah.json
- packs/gatewalkers-bestiary/protosoul.json
- packs/rage-of-elements-bestiary/blustering-gale.json
- packs/season-of-ghosts-bestiary/stone-spider.json
- Moved blindsight from details to sences for Xotani The Firebleeder
- Moved thoughtsense from details to sences for Vampire Taviah
- Moved thoughtsense from details to sences for Protosoul
- Moved Darkvision from details to sences for Blustering Gale
- Moved Darkvision from details to sences for Stone Spider
> Fix sense details for several NPCs

- packs/pfs-season-5-bestiary/giant-er-mouse.json
- packs/pfs-season-5-bestiary/giant-mouse.json
- packs/pfs-season-5-bestiary/weak-giant-er-mouse.json
- packs/pfs-season-5-bestiary/weak-giant-mouse.json
I assume defensive is correct, as I don't have the PDF.
```
Warning in Weak Giant Mouse: Ability item "Skittish" has no category defined!
Warning in Weak Giant-er Mouse: Ability item "Skittish" has no category defined!
Warning in Giant Mouse: Ability item "Skittish" has no category defined!
Warning in Giant-er Mouse: Ability item "Skittish" has no category defined!
```
> Update Skittish to be defensive

- packs/classfeatures/battledancer.json
- packs/classfeatures/braggart.json
- packs/classfeatures/fencer.json
- packs/classfeatures/gymnast.json
- packs/classfeatures/panache.json
- packs/classfeatures/wit.json
- packs/feat-effects/effect-panache.json
- packs/feats/derring-do.json
Makes things a bit cleaner, and hopefully easier for 3PP to add their own swashbuckler styles. I left feats out of this due to the way Panache and Derring-Do are worded:
Panache says
> gain a +1 circumstance bonus to checks to Tumble Through or to take any actions that give you panache due to your style
Derring-Do says
> you can roll twice and use the higher result on checks to which the circumstance bonus for having panache applies (Tumble Through and any skill actions listed in your swashbuckler's style).
Which implies that different ways to gain Panache (such as Leading Dance, One For All, and Disarming Flair) do not qualify for these benefits. For the sake of convenience, I think they're better off with their own Note for gaining Panache, if we add any. Thoughts?
> Set roll option for Swashbuckler's Panache-granting actions

- packs/familiar-abilities/greater-resistance.json
- packs/familiar-abilities/major-resistance.json
- packs/familiar-abilities/resistance.json
The rule elements for the base `Resistance` ability are a bit clunky but it gets the job done and allows for the upgrades from the other two abilities.
Happy for some tips if there's a more succinct way to do the same though.
> Add automation for the Resistance group of Familiar Abilities

- src/styles/actor/_spell-collection.scss
The border remaining blue kinda looks deceptively like a lingering selection highlight IMO.
> Remove colored border on disabled `Cast` buttons in spellcasting entries

- src/module/system/text-editor.ts
- src/scripts/hooks/init.ts
- src/styles/_globals.scss
- static/lang/en.json
Add support for inline slash-style syntax, specifically `/act`, for actions.
Also give priority to the action objects instead of the old action functions when using both the old HTML syntax and the new slash syntax.
`[[/act administer-first-aid variant=stop-bleeding dc=25]]`
`[[/act escape statistic=acrobatics dc=fortitude]]`
`[[/act grapple]]`
~~Depends on https://github.com/foundryvtt/pf2e/pull/13043 and https://github.com/foundryvtt/pf2e/pull/13047~~
> Add support for inline /act syntax for using actions

- src/module/item/spell/document.ts
- src/module/item/spell/helpers.ts
- src/module/item/spell/sheet.ts
- src/styles/actor/_spell-collection.scss
- src/styles/actor/_spell-preparation.scss
- static/templates/actors/partials/spell-collection.hbs
- static/templates/actors/spell-preparation-sheet.hbs
Closes https://github.com/foundryvtt/pf2e/issues/12910
Big cast buttons still work in Russian, though the solution is a little cursed. We can introduce localization specific CSS variables instead if you prefer. Another solution is to make it part of the range cell, and right align the cast button.
> Add defense column to spells tab

- src/module/actor/actions/single-check.ts
- src/module/actor/actions/types.ts
- src/module/system/action-macros/types.ts
The proposed change allows calling `action.use({target:token})` or `action.use({target:token.action})` and use the passed value instead of picking the first user target.
When called with an actor, the assumption is that the caller doesn't care about a specific token.
The intended use case is to call this from a macro or a module and utilize the system action checks and modifiers.
> Add `target` property to SimpleRollActionCheck options that accepts Token or Actor

- src/module/system/text-editor.ts
The statistic is still shown if a custom statistic is provided as a parameter.
> Do not show default statistic for inline actions

- src/module/actor/actions/base.ts
getDefaultVariant() is not async, and defaults to "toActionVariant()" anyways.
> Simplify action toMessage() and use() methods

- packs/backgrounds/bookish-providence.json
- packs/backgrounds/chosen-one.json
- packs/backgrounds/free-spirit.json
- packs/backgrounds/genie-blessed.json
- packs/backgrounds/hammered-by-fate.json
- packs/backgrounds/keys-to-destiny.json
- packs/backgrounds/pathfinder-recruiter.json
- packs/backgrounds/runner.json
- packs/backgrounds/shielded-fortune.json
- packs/backgrounds/sun-dancer.json
- packs/backgrounds/thrill-seeker.json
- packs/backgrounds/unremarkable.json
- packs/backgrounds/writ-in-the-stars.json
A pass over Backgrounds to grant the appropriate feats and actions, along with adding missing links to Feats in the text.
> Add GrantItem REs and Feat links in some Backgrounds

- packs/spell-effects/spell-effect-shillelagh.json
- static/lang/re-en.json
Made the predicate more specific, localised the labels, and made the bonus damage die a Damage Dice rule element instead of a Striking one, since the spell doesn't technically mention the weapon becoming Greater Striking.
> Brush up Shillelagh's spell effect

- packs/feats/visual-fidelity.json
Didn't include low-light vision since darkvision supercedes it in the system, but if there's a good reason to include it anyway I'm happy to do so
> Add darkvision subfeature to Visual Fidelity

- packs/feat-effects/effect-curse-of-outpouring-life.json
- static/lang/re-en.json
Testing out the waters, first time using this new feature of Item Alteration
> Append healing note to spells under moderate Curse of Outpouring Life

- packs/feat-effects/effect-overdrive-ally-shared-overdrive.json
- packs/feat-effects/effect-overdrive-ally.json
- packs/feats/overdrive-ally.json
- packs/feats/shared-overdrive.json
Since it seems there's no way currently to get roll options from the item's origin, I set up a flag in Overdrive Ally that could tell the effect what Overdrive degree of success the inventor has. The alternative is a Choice Set, but this seemed cleaner.
It doesn't look like there's console noise if the flag is missing (which would be the case for inventors with an old copy of the feat), but even then if they want to have the effect handy, it's likely they will get a new overdrive ally copy. If this isn't ok I'm happy to go with a Choice Set instead though.
> Automate Overdrive Ally

- src/styles/actor/_spell-collection.scss
Spells with really brief descriptions weren't pushing the summary card to match the normal width.
Example of the issue before fix:
> Use full width in spell collection summary expando

- packs/actions/confident-finisher.json
- packs/classfeatures/precise-strike.json
- packs/feats/bleeding-finisher.json
- packs/feats/finishing-precision.json
- static/lang/re-en.json
I also use the very same flag to automate Bleeding Finisher, which supports multiclass swashbucklers as well.  ~~I tried to do the same with Confident Finisher but quickly ran into the roadblock of inline precision damage...~~
Were this to be accepted I suppose it'd require to migrate existing swashbucklers for them to have the relevant flag?
> Store Swashbuckler's Precise Strike value in a flag

- packs/feat-effects/effect-curse-of-outpouring-life.json
- static/lang/re-en.json
For some reason `parent:badge:value` does not work correctly as a predicate for an individual line, but `oracular-curse:stage`, which denotes the same thing in this context, does.
> Append note to spells under major Curse of Outpouring Life

- packs/outlaws-of-alkenstar-bestiary/vivielle-ramslay.json
Closes #9156
The core difference as noted in the issue was the missing Clairaudience spell, which has been added.
> Add Vivielle Ramslay to Outlaws of Alkenstar Bestiary

- packs/equipment/pernicious-spore-bomb-greater.json
- packs/equipment/pernicious-spore-bomb-lesser.json
- packs/equipment/pernicious-spore-bomb-major.json
- packs/equipment/pernicious-spore-bomb-moderate.json
- static/lang/re-en.json
Removes the unnecessary current Notes and adds the special Terrain-specific note to the _attack roll_ instead of damage, so it can show on Failure as well.
Closes #2128
> Add Failure Note to Pernicious Spore Bomb

- packs/equipment/black-hole-armor.json
- packs/feats/megaton-strike.json
- src/module/migration/migrations/916-new-pc-toys.ts
Also switched `value` for `diceNumber` on the rule elements, as the dice were not being added
> Restrict Megaton Strike to specified Strikes

- src/module/actor/creature/document.ts
- src/module/item/spellcasting-entry/document.ts
When an actor can cast spells it currently gets a roll option named "self:caster" (or "target:caster", etc. depending on context).
Extend this with "self:caster:divine", etc. for whatever tradition(s) the actor has.  "self:caster" is still there if any traditions are known.
Like the existing isSpellcaster() check, the tradition doesn't count unless it actually has spells.
The motiviation is to be able to add automation for things like Divine Disharmony, which triggers on, amongst other things, "...  creature with divine spells." Or Robe of the Archmagi, which "benefit only characters who can cast arcane spells."
> Add roll options for spellcasting traditions

- packs/kingmaker-bestiary/black-smilodon.json
Closes #9023
Set to the same rarity as Smilodons.
> Fix Black Smilodon rarity in Kingmaker

- packs/menace-under-otari-bestiary/animated-armor-bb.json
- packs/menace-under-otari-bestiary/gargoyle-bb.json
- packs/menace-under-otari-bestiary/ghost-commoner-bb.json
- packs/menace-under-otari-bestiary/ghoul-bb.json
- packs/menace-under-otari-bestiary/hell-hound-bb.json
- packs/menace-under-otari-bestiary/shadow-bb.json
- packs/menace-under-otari-bestiary/skeletal-giant-bb.json
- packs/menace-under-otari-bestiary/skeleton-guard-bb.json
- packs/menace-under-otari-bestiary/zombie-shambler-bb.json
- packs/pathfinder-bestiary/zombie-brute.json
- packs/pathfinder-bestiary/zombie-shambler.json
Even without a remaster to the BB, we can infer some changes from recent publications which can (hopefully uncontroversially) be retroactively applied to the BB creatures and allow them to be used with less friction in the latest system versions. These include things like the removal of alignment (previously applied by system update) and (in this PR) some changes to the way that immunities and resistances are listed for undead creatures. 
This PR adds bleed & void immunity to undead creatures, updates the Hellhound's languages, and similar small tweaks.
One of the changes was less clear-cut- adding the Slowed condition to the zombie shambler. I think this is harmless and just makes the system a bit easier to learn, but I've included it in a separate commit so that it can be excluded …
> Make minor updates to BB data entry for compatibility with Remaster

- src/styles/legacy/_chat.scss
- static/templates/items/partials/spell-description-prepend.hbs
Following on from the change in #13140 this adds the `Defense [...]` label to the prepended spell descriptions.
I need input on which display we prefer though: inline or separate line to `Duration`. I prefer inline but it does mean that some spell chat cards have to wrap the Duration value if it's wordy. The current PR is the _inline_ implementation.
Comparisons:
I also experimented with displaying a "fully complete" defense label for niche cases that have _both_ an AC and stat defense like Disintegrate but I'm not convinced it's worth the mess to implement 🤷 
Here's what one iteration looked like (note slightly fatter spell slot row):
IMO it does look nice in the spell cards but not in the new Defense column, however I'm not convinced it's worth all the janky code changes vs the current …
> Add Defense to spell description headers

- src/module/actor/character/document.ts
When the modifier for a resilient rune is created, the adjustments weren't also extracted and added to it.  The result is that AdjustModifier REs can't change the resilient bonus.
This extracts the adjustments, in the same way as, e.g., the Bulwark trait.  Items like Robe of the Archmagi that only supply their resilient benefit if the owner has certain traits can be automated using an AdjustModifier RE.
> Allow AdjustModifier REs to affect resilient rune modifier

- packs/feats/defensive-armaments.json
Handling of the parry bonus is a bit jank right now, so this doesn't build on top of it.
Partially addresses #13408
> Add RE to handle part of Defensive Armaments

- packs/feats/divine-disharmony.json
Rule for the +2 circumstance bonus to the divine disharmony action, when the target meets certain conditions.
While the text of the feat mentions GM arbitration in determining the nature of the target's faith or lack thereof, it also lists several specific traits.  The RE tests only for the extact traits listed in the text.
> Add rule for Divine Disharmony bonus

- build/extract-packs.ts
It doesn't accept the options.json path as an argument anymore.
But it doesn't produce any error if one tries, so it's easy to think it's working.
> Remove out of date example froms extractPacks

- src/module/actor/creature/document.ts
Armor speed penalty is implemented in character and checks the derivedFromLand property.
> Fix armor speed penalty applying twice to derived from land speeds

- src/styles/actor/_nav.scss
This should be a more reliable way of maintaining the centered, evenly spread sub-nav links now that we have a Kingdom sheet with more sub-nav links than the player sheet and party sheet.
> Fix styling regression in Kingdom sheet sub-nav header

- packs/feats/mystery-conduit.json
which in turn will post the appropriate curse advancement to chat.
> Add cursebound trait to spells cast with Mystery Conduit on

- packs/classfeatures/kinetic-aura.json
- static/lang/re-en.json
~~Feat description alterations are not posted to chat currently, so I suppose I'm drafting this until that's resolved.~~
> Append aura shut off reminder note to overflow impulses

- packs/spell-effects/spell-effect-animal-feature-claws.json
- packs/spell-effects/spell-effect-animal-feature-jaws.json
- packs/spell-effects/spell-effect-dragon-claws.json
- packs/spell-effects/spell-effect-gluttons-jaw.json
- packs/spell-effects/spell-effect-mantle-of-the-frozen-heart-icy-claws.json
- packs/spell-effects/spell-effect-mantle-of-the-magma-heart-fiery-grasp.json
- packs/spell-effects/spell-effect-mantle-of-the-unwavering-heart.json
- packs/spell-effects/spell-effect-moon-frenzy.json
- packs/spell-effects/spell-effect-shifting-form.json
- packs/spell-effects/spell-effect-untamed-shift.json
Morph states "Any Strikes specifically granted by a morph effect are magical."
So I added the magical trait to all Strike REs on Morph spell effects.
> Add Magical Trait to Strikes granted by Morph spell effects

- packs/spells/lifes-flowing-river.json
It's not a basic saving throw, and the language doesn't indicate that the damage is doubled or halved.
By my interpretation that means a +1 heightened Critical Failure should do 9d6 mental rather than 10d6.
> Remove damage partial from Life's Flowing River and add inline damage links

- src/module/actor/party/kingdom/model.ts
Kinda closes https://github.com/foundryvtt/pf2e/issues/13490 making it possible to do stuff like the following for an extra boost
```json
{"key":"ActiveEffectLike","mode":"add","path":"system.campaign.abilities.loyalty.value","value":"ternary(gte(@kingdom.abilities.loyalty.value, 18),1,2)"}
```
> Move kingdom mod computation to a later step

- src/module/system/damage/iwr.ts
Previously, a critical success would always generate a <critImmuneTotal> value as it would not check whether critImmunity was applied. This change adds the critImmunity check to the calculation for critImmuneTotal, therefore not later halving precision damage by assuming that crit immunity was already applied.
> Correct precision damage getting halved by critical success

- src/module/actor/sheet/popups/identify-popup.ts
- src/module/item/identification.ts
Fall back to using a recall knowledge action for appraising non-magical and non-alchemical items.
> Fix identification of mystified mundane items

- packs/classfeatures/first-doctrine-warpriest.json
While technically wrong on some deities we can't grant based on the category without a larger rewrite of deity items and the feat will simply do nothing on deities that don't qualify anyways.
> Grant Deadly Simplicity with Warpriest's First Doctrine

- packs/feats/dueling-parry-fighter.json
- packs/feats/slam-down.json
- packs/feats/sneak-adept.json
- packs/feats/tactical-reflexes.json
Partially addresses #13527
- Green Empathy is a duplicate of the new Plant Empathy, which Druids can get for free at level 1. It's even already listed in the Remaster Changes journal entry as being a rename. But then Green Empathy is also a prerequisite for Green Tongue. Nuke both?
- Battle Assessment is sheer chaos; it's no wonder that it didn't make it to PC1. That said, I suppose GMs can continue to indulge it if they want to.
> Update publication data of some PC1 class feats

- src/module/actor/base.ts
- src/module/chat-message/data.ts
- src/module/item/abstract-effect/data.ts
- src/module/item/abstract-effect/document.ts
- src/module/item/effect/document.ts
- src/module/item/spell/document.ts
- src/scripts/system/dragstart-handler.ts
> Make available roll options of effect origins' originating items

- packs/strength-of-thousands-bestiary/unshadowed-haibram.json
The text states: 
> Haibram imbues a weapon he's holding with the power of the wind until the start of his next turn. The wind's power allows Haibram to swing and hurl the weapon with great force, causing the weapon to deal an additional 2d10 damage. 
This fixes the extra damage to match.
> Fix 'wind touch' damage in Unshadowed Haibram

- packs/classfeatures/conscious-mind.json
- packs/classfeatures/psi-cantrips-and-amps.json
Also throw in spell otherTag of "amped"
> Move general amp-related REs to Psi Cantrips and Amps class feature

- types/foundry/client/application/sidebar/sidebar.d.ts
- types/foundry/client/core/hooks.d.ts
- types/foundry/client/pixi/board.d.ts
Add once Hook for I18nInit
Add ui.sidebar.activeTab getter
Add Canvas.prototype._onDragSelect
> Fill in miscellaneous type gaps

- packs/feats/bestial-manifestation.json
Also add icons to ChoiceSet and use higher-res image for hoof
Closes https://github.com/foundryvtt/pf2e/issues/13617
> Fix missing versatile piercing for Bestial Manifestation claw attack

- src/module/system/text-editor.ts
This will allow the PFS modules to implement Influence Statblocks without excessive duplication, but I'm sure there could be other uses.
I've checked to make sure that the Journal and Chat are not affected by this in any way.
> Remove redundant retrieval of actor in `getCheckDC` inline roll links helper

- src/module/actor/character/document.ts
- src/module/actor/creature/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/13629. This is the earliest possible for base spellcasting to be set up in the pipeline (used to be in derived data).
> Fix rank of base spellcasting proficiency and innate spells

- src/module/apps/compendium-browser/tabs/spell.ts
The helper was being called with sluggified action costs and failing. An alternative fix is to modify `getActionGlyph(..)` to support sluggified input but I'm not convinced we need that.
Before v After:
> Fix variable-cost action glyphs in Spell Compendium

- packs/kingmaker-bestiary/armies/basic-skirmishers.json
Skirmishers are a level 5 army not 15 (typo I think)
> Fix skirmisher army level

- static/templates/actors/npc/partials/sidebar.hbs
Vampire Squid before:
After:
Kasesh (Stone) before:
After:
> Fix disabled appearance of NPC resistances header

- src/module/actor/loot/sheet.ts
- src/module/actor/sheet/base.ts
- src/module/actor/sheet/data-types.ts
- src/styles/actor/loot/_index.scss
- static/templates/actors/loot/inventory.hbs
- static/templates/actors/partials/inventory.hbs
- static/templates/actors/partials/item-line.hbs
GM view
Player View
Coins in containers are purposefully not hidden as it would cause strange behavior if the container itself as sold (and if it also sold what was inside the container, which it should.....)
> Hide merchant coins and empty loot sections from players

- src/module/actor/item-transfer.ts
- src/styles/ui/sidebar/chat/_action.scss
- static/templates/chat/action/content.hbs
Closes #13680
Inserts the item link for all of the valid A -> B item transfer chat messages.
The default item link styling was way too chunky without word wrap so I experimented with a simple underline instead. It still maintains all the clicky, hover etc effects:
> Add item links to item transfer chat messages

- packs/feats/mummy-dedication.json
Applying the Mummy Dedication to a character triggers a wall of warnings in the console regarding an ignored RuleElement and fails to trigger the ChoiceSet prompt.
Simply moving the ChoiceSet up the list of REs resolves the issue and allows the ChoiceSet to trigger.
> Fix Mummy Dedication ChoiceSet activating

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
When target:self is defined in the @Checks params, set the target for any defense evaluation to the origin of the Check.
> Add targetOwner option to @Check syntax

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
- src/util/dom.ts
check the value of targetOwner is "true" - it's a string when read from the dataset.
> Fix not-targetOwner roll links

- src/module/actor/creature/document.ts
This label was missed when the actor base speed labels were refactored.
Noticed while doing some Familiar Sheet work 👀
> Fix broken non-land Base Speed tooltip labels in creature documents

- src/module/actor/familiar/sheet.ts
- static/templates/actors/familiar/sheet.hbs
Previously the `masters` array would be empty for non-Owner users and not show the Master's name.
This also lets us simplify the messy template code that I just added for handling the Limited sheet view since the familiar Master, if set, will always be available in the `<select>` (I had confirmed it was an existing bug while working on the Limited sheet).
> Fix display of Master name in Familiar sheet when User is an `Observer`

- packs/feats/basic-synergy.json
> Due to your tenuous link, you can't gain or use tandem actions.
> Remove Tandem feats from Basic Synergy options

- packs/classfeatures/the-oscillating-wave.json
- packs/feat-effects/effect-psi-strikes.json
- packs/feats/psi-burst.json
- packs/feats/violent-unleash.json
- static/lang/re-en.json
Also add rule elements to conditionally change damage type of psi strikes
> Move leveled force damage to main `@Damage` links in Psi Burst and Violent Unleash

- src/module/chat-message/roll-inspector.ts
- src/styles/tooltip/_index.scss
- src/styles/ui/sidebar/chat/_roll-inspector.scss
- static/templates/chat/roll-inspector.hbs
If you can think of a good data property to replace the html query selector with for the hover, I'd appreciate it.
> Show tooltip for modifier/dice roll options in inspector

- src/styles/actor/familiar/_index.scss
The padding was placed on the header which pushed down the title bar. Moving it to the form fixes this.
Before
After
> Fix padding on familiar sheet headers

- src/styles/actor/character/_proficiencies.scss
- static/templates/actors/character/tabs/proficiencies.hbs
Seems it went over well, so I'm confident enough to do it in the proficiencies tab as well
> Use underline modifiers convention for character proficiencies tab

- packs/agents-of-edgewatch-bestiary/grabble-forden.json
This allows inline damage links to also be overridden.
> Update Grabble Forden's Poison Conversion to use DamageAlteration

- packs/equipment/robe-of-the-archmagi-greater.json
- packs/equipment/robe-of-the-archmagi.json
This automates most of the effects of a non-arcane caster wearing a Robe of the Archmagi (regular or plus-sized).
A Stupefied 2 condition is imposed.
The saving throw bonus is disabled.
The AC and the resilient item bonuses are supressed.  They'll appear on the character sheet with the normal +2 value, but be grayed out and not applied.
The good/neutral/evil alignment of the robe, and the robe's color, isn't part of the item.  So none of the effects consider that.
> Finish Robe of the Archmagi automation

- packs/feat-effects/effect-smite-evil.json
- packs/feat-effects/effect-smite-good.json
- packs/feats/smite-good.json
Follow up to #13867, updates the effects of Smite Evil and Good to remaster and makes Smite Good a self effect.
I tried thinking of a clever way to combine the Flat Modifiers, but not sure if it's possible to get the weapon's proficiency in a Flat Modifier resolvable format? Chime in if you got one!
> Update Champion Smite effects to remaster errata

- packs/spells/heros-defiance.json
- packs/spells/life-siphon.json
- packs/spells/soothing-spring.json
- packs/spells/wholeness-of-body.json
I assumed that spells with the vitality trait did vitality healing
> Fix damage type of Hero's Defiance, Life Siphon, Soothing Spring, and Wholeness of Body

- packs/abomination-vaults-bestiary/deep-end-sarglagon.json
- packs/agents-of-edgewatch-bestiary/avarek.json
- packs/agents-of-edgewatch-bestiary/minchgorm.json
- packs/agents-of-edgewatch-bestiary/tiderunner-aquamancer.json
- packs/feats/smite-evil.json
- packs/kingmaker-bestiary/false-priestess.json
- packs/night-of-the-gray-death-bestiary/riekanoy.json
- packs/pathfinder-bestiary-2/adult-brine-dragon-spellcaster.json
- packs/pathfinder-bestiary-2/adult-brine-dragon.json
- packs/pathfinder-bestiary-2/ancient-brine-dragon-spellcaster.json
- packs/pathfinder-bestiary-2/ancient-brine-dragon.json
- packs/pathfinder-bestiary-2/sarglagon.json
- packs/pathfinder-bestiary-2/water-yai.json
- packs/pathfinder-bestiary-3/danava-titan.json
- packs/pathfinder-bestiary-3/storm-hag.json
- packs/pathfinder-bestiary-3/tidehawk.json
- packs/pathfinder-bestiary/marid.json
- packs/quest-for-the-frozen-flame-bestiary/jesseri-the-hailstorm.json
- packs/rage-of-elements-bestiary/faydhaan-shuyookh.json
- packs/season-of-ghosts-bestiary/heh-shan-bao.json
- packs/season-of-ghosts-bestiary/iogaka.json
- packs/spells/hydraulic-torrent.json
- packs/stolen-fate-bestiary/markish-aghayarea.json
- packs/strength-of-thousands-bestiary/grouloop.json
- packs/strength-of-thousands-bestiary/ssumzili.json
Manually replace copies for Minchgorm, Ancient Brine Dragon, Ancient Brine Dragon (Spellcaster), and Water Yai.
> Refresh copies of Hydraulic Torrent

- packs/feat-effects/effect-channeling-block.json
- packs/feat-effects/effect-deitys-protection.json
- packs/feat-effects/effect-prayer-touched-weapon.json
- packs/feat-effects/effect-premonition-of-clarity.json
- packs/feat-effects/effect-raise-symbol.json
- packs/feat-effects/effect-restorative-strike.json
- packs/feats/channeling-block.json
- packs/feats/dance-of-intercession.json
- packs/feats/deitys-protection.json
- packs/feats/panic-the-dead.json
- packs/feats/premonition-of-clarity.json
- packs/feats/raise-symbol.json
- packs/feats/sap-life.json
- packs/feats/shared-clarity.json
- static/lang/re-en.json
- Add note to Panic the Dead.
- Grant Raise a Shield effect along with Raise Symbol when shield is a religious symbol.
- Remove manipulate trait from 1-action heal when using Restorative Strike and add Note rule element.
- Automate Channeling Block.
- Append Deity's Protection effect to cleric domain spells.
- Make Premonition of Clarity a self-applied effect.
- Add note rule element to Shared Clarity
- Adjust degree of success of Dance of Intercessions' performance check based on remaining uses.
And a couple of very minor things: Fix typo in Sap Life's description, Add description to Prayer-Touched Weapon's effect
> Brush up Cleric feats

- src/global.ts
- src/module/system/check/check.ts
- src/module/system/settings/metagame.ts
- src/scripts/set-game-pf2e.ts
- static/lang/en.json
Closes #9544, closes #2262
Toggling this alters the default roll type for Secret actions to Public. It doesn't remove the trait from the roll.
> Add Metagame Setting to ignore the Secret Trait on Checks

- src/module/actor/base.ts
This prevents a break in Battlezoo dragons if you add the Empowered Size feat before the Ancestry itself. In theory Automatons could trigger the same issue with their own equivalent "get big feat" and the CreatureSize RE in the ancestry itself.
> Ensure ABC items are processed first

- packs/blood-lords-bestiary/vice-chancellor-vikroti-stroh.json
- packs/spells/final-sacrifice.json
Cannot use alteration REs and predicate off target, since non-attack spells don't have target RollOptions.
> Add cold damage overlay to Final Sacrifice

- packs/classfeatures/fifth-doctrine.json
- packs/classfeatures/final-doctrine.json
- packs/classfeatures/fourth-doctrine.json
- packs/classfeatures/second-doctrine.json
- packs/classfeatures/third-doctrine.json
As title. The data is already all there in the subclasses, but only the first doctrine used them.
> Fix Cleric Doctrines granting features based on predication rather than flags

- src/module/actor/creature/data.ts
- src/module/actor/sheet/base.ts
- src/module/rules/rule-element/creature-size.ts
This prevents dropped longswords becoming Huge on Medium actors enlarged to Large.
Closes https://github.com/foundryvtt/pf2e/issues/2840
> Handle resized actors when dropping from compendium

- packs/equipment/clan-pistol.json
- packs/outlaws-of-alkenstar-bestiary/corrupt-shieldmarshal-clan-pistol.json
Immolation Clan Pistol is correctly bulk 1.
Closes https://github.com/foundryvtt/pf2e/issues/13997
> FIx bulk of Clan Pistol

- packs/iconics/ezren-level-1.json
- packs/spells/caustic-blast.json
Persistent damage was incorrectly set to increase starting from the second rank.
Maybe it would be convenient to have something like `@item.heightening` - a read-only property that essentially evaluated to `@item.rank - @item.baseRank`.
> Correct Caustic Blast persistent damage

- src/module/actor/actions/types.ts
- src/module/item/consumable/document.ts
- src/module/item/physical/document.ts
- src/module/rules/index.ts
- src/module/rules/rule-element/base.ts
- src/module/rules/rule-element/data.ts
- src/module/rules/rule-element/effect-spinoff/rule-element.ts
- src/module/rules/rule-element/effect-spinoff/spinoff.ts
- static/lang/re-en.json
No UI exposure yet: just the RE itself and populating `PhysicalItemPF2e#effectSpinoffs`
> Add foundational framework for effect spinoff rule elements

- src/module/apps/compendium-browser/tabs/action.ts
- src/module/apps/compendium-browser/tabs/bestiary.ts
- src/module/apps/compendium-browser/tabs/campaign-feature.ts
- src/module/apps/compendium-browser/tabs/equipment.ts
- src/module/apps/compendium-browser/tabs/feat.ts
- src/module/apps/compendium-browser/tabs/hazard.ts
- src/module/apps/compendium-browser/tabs/spell.ts
The system is still constructing the compendium pack entries `uuid` manually in `CompendiumBrowserTab#loadData`, this PR will switch to using the one "now" provided by foundry directly which also will make them have the v11 format.
> Use `CompendiumIndexData.uuid` instead of constructing it manually in `CompendiumBrowserTab#loadData`

- packs/feats/advanced-warden.json
- packs/feats/initiate-warden.json
- packs/feats/masterful-warden.json
- packs/feats/peerless-warden.json
Since they say "or another you have access to", I don't believe we should limit the takable count to the spells in Player Core.
Closes https://github.com/foundryvtt/pf2e/issues/14056
> Set warden spell feats to be takable an unlimited number of times

- packs/equipment-effects/effect-bronze-bull-pendant.json
- packs/equipment/bronze-bull-pendant.json
- packs/rollable-tables/2nd-level-consumables.json
Remove extraneous Trigger text
Make effect removeAfterRoll
Closes https://github.com/foundryvtt/pf2e/issues/14082
> Refresh Bronze Bull Pendant

- src/module/apps/compendium-browser/tabs/action.ts
- src/module/apps/compendium-browser/tabs/bestiary.ts
- src/module/apps/compendium-browser/tabs/campaign-feature.ts
- src/module/apps/compendium-browser/tabs/equipment.ts
- src/module/apps/compendium-browser/tabs/feat.ts
- src/module/apps/compendium-browser/tabs/hazard.ts
- src/module/apps/compendium-browser/tabs/spell.ts
Babele adds the `originalName` property when a compendium index entry was translated.
Closes #14068
> Support Babele's `originalName` property in compendium browser search

- src/module/apps/compendium-browser/tabs/base.ts
- src/module/apps/sidebar/compendium-directory.ts
> Add fallback for browsers lacking `Intl.Segmenter`

- src/module/system/statistic/statistic.ts
This fixes a regression that prevented Kingdom sheet rolls.
Fixes #14162
> Add `party` as a valid roller in `StatisticCheck.roll()`

- src/styles/actor/character/_sidebar.scss
- static/lang/re-en.json
This increases the width of the Max HP label from `5em` to `6em`.
The reason for this change is due to (Brazilian Portuguese) localization not fitting into the box and requiring custom CSS styling to fix it.
> Update Character Sidebar's Shield Max HP label's width

- src/module/actor/npc/types.ts
- static/templates/actors/npc/partials/sidebar.hbs
- static/templates/actors/npc/simple-sheet.hbs
> Fix NPC sheet initiative only showing perception

- src/module/system/schema-data-fields.ts
This causes thrown exceptions in strict mode if any key or value in RecordField has unresolved errors. This causes https://github.com/foundryvtt/pf2e/pull/13927 to behave correctly, *but* it is an incredibly fundamental change that may have repercussions to rule elements.
> Set RecordField as unresolved if anything was unresolved

- packs/feats/parallel-breakthrough.json
> Hide disabled damage dice and modifiers in Parallel Breakthrough

- packs/classfeatures/the-silent-whisper.json
- packs/feats/parallel-breakthrough.json
and add Message's missing heightened amp entry on the relevant Item Alterations.
> Exclude alternate amps from Parallel Breakthrough

- static/templates/actors/party/regions/exploration.hbs
Hexploration's Travel Speed was using the old loc string for Feet.
> Fix Party's Hexploration Speed missing localization

- packs/classfeatures/air-gate.json
- packs/classfeatures/earth-gate.json
- packs/classfeatures/metal-gate.json
- packs/classfeatures/water-gate.json
- packs/classfeatures/wood-gate.json
```
In addition, you gain an impulse junction, a benefit that
occurs when you use an impulse of the chosen element
that takes 2 actions or more.
```
Currently, when an elemental blast attack misses, there is no roll note shown for the impulse junction effect.
After this PR:
> Show impulse junction note on elemental blast attack roll instead of damage roll

- packs/feat-effects/effect-animate-net.json
- packs/feat-effects/effect-shining-arms.json
- packs/feats/animate-net.json
- packs/feats/lingering-flames.json
- packs/feats/shining-arms.json
- static/lang/re-en.json
- Add effect for Animate Net.
- Add effect for Shining Arms.
- Replace instance of level with rank in Choking Smoke's localization key.
- Replace Lingering Flames' persistent damage flat modifier with an inline roll, since the persistent damage only occurs on a failure and critical failure.
- Fix Siphoning Touch's name in localization file.
Also fix some Alchemical Bomb notes scarily written in the first person.
> Brush up some Spell Trickster automation

- packs/classfeatures/catharsis-emotion-love.json
- packs/equipment/kinburis-sandals-of-bounding.json
- packs/feats/dragonslayer-oath.json
- packs/feats/esoteric-oath.json
- packs/feats/fiendsbane-oath.json
- packs/feats/intimidating-prowess.json
- packs/feats/ravenings-desperation.json
- packs/feats/shining-oath.json
- packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
- packs/kingmaker-bestiary/valerie-level-9.json
Shouldn't be a need to check for empty string as empty slug auto-nulls on item card update. #14212
> Add slugs to FlatModifier REs targeted by AdjustModifier REs

- src/module/actor/familiar/document.ts
- src/module/actor/party/document.ts
- src/scripts/hooks/ready.ts
Closes https://github.com/foundryvtt/pf2e/issues/10778
In better detail (the title is bad and I gave up coming up with a better one):
* Fixes familiars in the actor sidebar being level 0 by re-rendering after re-preparation
* Fixes certain errors that occur if the party was created after the members (there was an old issue that comes to mind, though I can't find it now)
> Fix familiar level 0 in world actors and party errors based off initialization order

- packs/iconics/daji-level-3.json
- packs/iconics/daji-level-5.json
- packs/iconics/droogami-level-3.json
- packs/iconics/droogami-level-5.json
- packs/iconics/ezren-level-3.json
- packs/iconics/ezren-level-5.json
- packs/iconics/feiya-level-3.json
- packs/iconics/feiya-level-5.json
- packs/iconics/harsk-level-3.json
- packs/iconics/harsk-level-5.json
- packs/iconics/jirelle-level-1.json
- packs/iconics/jirelle-level-5.json
- packs/iconics/kyra-level-1.json
- packs/iconics/kyra-level-3.json
- packs/iconics/kyra-level-5.json
- packs/iconics/lem-level-3.json
- packs/iconics/lem-level-5.json
- packs/iconics/lini-level-3.json
- packs/iconics/lini-level-5.json
- packs/iconics/merisiel-level-3.json
- packs/iconics/merisiel-level-5.json
- packs/iconics/valeros-level-1.json
- packs/iconics/valeros-level-3.json
- packs/iconics/valeros-level-5.json
Clarifying a couple issues with Alex:
Level 5 Ezren in the PDF doesn't have his Wayfinder, and Hand of the Apprentice is only doing 1d4+4 damage, even though his weapon is a +1 striking staff (I don't think this will matter, since the system uses the damage roll from the weapon). Level 5 Lini has a typo on the first page with the ancestry feats; animal elocutionist should be gnome obsession. Additionally, she's untrained in crafting, yet is hauling around a repair toolkit.
> Update and Add Level 3 and 5 Iconics from *Player Core*

- packs/age-of-ashes-bestiary/saggorak-poltergeist.json
- packs/fists-of-the-ruby-phoenix-bestiary/watchtower-poltergeist.json
- packs/pathfinder-bestiary/poltergeist.json
- packs/pfs-season-3-bestiary/poltergeist-holy-hand.json
Use RollOption with suboptions for damage type
Use DamageAlteration to automate Telekinetic Storm inline damage type
Use proper selectors
Fix Saggorak and Watchtower Poltergeists' Telekinetic Storm extra damage
> Update Poltergeist Telekinetic Object and Telekinetic Storm

- src/module/rules/rule-element/grant-item/rule-element.ts
This is more of an internal bugfix, and I don't know if anything trips this in the wild.
If you create this:
Before:
After:
> Preserve creation order in nested grants

- static/templates/dice/damage-roll.hbs
> Fix parentheses sometimes appearing in private damage rolls

- src/module/actor/character/sheet.ts
Older versions of Chrome still in use out in the wild lack the method
> Replace usage of `Array#toReversed` with `Array#reverse` on copy

- src/module/actor/party/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/14308
Moving items to the party created a clone of the party, which triggered the bug.
> Fix leak when updating party stash

- src/module/system/rolls.ts
Looking at the "consumeAmmo" AttackRollParams, I noticed a likely typo in DamageRollParams's Omit type.
> Fix "consumAmmo" in an Omit type

- src/module/actor/sheet/item-summary-renderer.ts
- src/module/item/helpers.ts
- src/styles/actor/_item-summary.scss
- static/templates/actors/partials/item-summary.hbs
I'm surprised it wasn't in item summaries in the first place. Screenshot includes a AV spoilers.
> Also show GM Notes in item summaries

- packs/ancestryfeatures/draconic-exemplar.json
- packs/feats/dragons-breath.json
- static/lang/re-en.json
also add the appropriate trait to the Kobold Breath action and fix a typo in Dragon's Breath inline damage.
> Add description alteration for Dragons Breath

- src/module/actor/roll-context/base.ts
Closes https://github.com/foundryvtt/pf2e/issues/14380
Feel free to handle it a different way if this isn't correct. From my limited testing "hit the dirt" works again
> Include item options in target context clones

- src/module/actor/modifiers.ts
This is the true cause behind https://github.com/foundryvtt/pf2e/issues/14394. Rule isn't enumerable and must be copied separately.
I don't understand why there is a mergeObject without arguments though. It was introduced in https://github.com/CarlosFdez/pf2e/commit/1f9ae8ea0e2244936453f6d8f7297c1d7eee2c2a . I kept it in just in case but my guess is that it should probably be removed.
> Fix predicating parent roll options in modifier clones

- packs/feats/settlement-scholastics.json
- packs/pathfinder-monster-core/shining-child.json
- packs/season-of-ghosts-bestiary/heh-shan-bao.json
- packs/spell-effects/spell-effect-glimpse-weakness.json
- packs/spells/winters-breath.json
- Add language slot to Settlement Scholastics (Closes #14402)
- Add missing spell to Monster Core's Shining Child (Partially addresses #14358, as the other missing spell doesn't exist)
- Correct DC and spell attack of Season of Ghosts NPC (Closes #14410)
- Add missing ritual data to Winters Breath (Closes #14416)
- Correct Glimpse Weakness' effect's amp heightening (Closes #14421)
> Correct Glimpse Weakness scaling and fix other data errors

- packs/feat-effects/effect-alloy-flesh-and-steel.json
- packs/feats/alloy-flesh-and-steel.json
Removes the unautomated aspects of ferrous forms from the description, and added the additional die for metal spells.
> Tweak Ferrous Form and add effect for alloy flesh and steel

- src/scripts/macros/check-prompt/prompt.ts
- static/templates/gm/check-prompt.hbs
splitting PR from #14450 to include only default level feature request
Potentially Closes #11664 
- I did not like the idea of extra clicks to prefill the default value, so I went with the most common occurrence to use the party level as the default value automatically rather than have to push an extra button to do so.  I believe this will be a better user experience than a separate level button. 
- I think this can close the request, but that depends if you see value in the request for the option to have a button(s) for levels of creatures and hazards on the scene. Practically speaking I am not sure why you would be using a level based DC from Creature's/Hazards rather than the party level.
> Set default level in party check level-based DC's to average party level.

- src/module/item/deity/sheet.ts
Closes https://github.com/foundryvtt/pf2e/issues/14456. This error wasn't just for localization though, it was incorrectly setting deity skills to short form.
> Fix deity skill getting set to invalid values

- static/system.json
diagonals 4 sets it to 1/2/1 (internally referred as CONST.GRID_DIAGONALS.ALTERNATING_1)
> Set grid manifest settings to the new v12 format

- packs/classfeatures/fury-instinct.json
```You resist physical weapon damage, but not physical damage from other sources (such as unarmed attacks).```
Unarmed attacks are exception
> Fix logic of Fury Instinct Raging Resistance

- static/templates/actors/character/tabs/pfs.hbs
- static/templates/actors/familiar/sheet.hbs
- static/templates/actors/hazard/partials/header.hbs
- static/templates/actors/npc/partials/header.hbs
- static/templates/actors/npc/simple-sheet.hbs
- static/templates/items/action-sidebar.hbs
- static/templates/items/ancestry-sidebar.hbs
- static/templates/items/armor-details.hbs
- static/templates/items/physical-sidebar.hbs
- static/templates/items/rules-panel.hbs
- static/templates/items/sheet.hbs
- static/templates/items/weapon-details.hbs
It doesn't seem possible to directly convert all of them. The ones that are arrays (Proficiency ranks for example) require an Object.entries() first (see https://github.com/foundryvtt/foundryvtt/issues/10691). The ones that have additional non-blank option entries cannot be converted, and neither can those that have hardcoded select options or labels generated at render time.
There are more that can be converted now though rather than just these.
> Begin converting deprecated select handlebars helper to selectOptions

- packs/feats/keen-follower.json
- packs/other-effects/effect-follow-the-expert.json
This will add the larger bonus when following an Expert or Master.
To get the necessary information, the Follow The Expert effect makes the ChoiceSets copy to actor flags.  The proficiency is also a roll option.
The proficiency roll option is used so the Keen Follower modifier can be disabled when it shouldn't apply, i.e. when following a trained or legendary "expert".
I also tried as an AdjustModifier, but without a relabel there's no clear indication the feat is working.  And with a relabel, the localized skill name is removed from the modifier, e.g. "Follow The Expert (Arcana)" would become "Keenly Follow The Expert".
> Automate Keen Follower feat

- src/module/item/base/sheet/rule-element-form/aura.ts
The color picker elements are not working correctly so the rule element data gets bricked when the form is used until the next core version. But this fixes a type error introduced by #14497
> Fix aura RE form error

- roll-grammar.peggy
- src/module/actor/base.ts
- src/module/actor/party/kingdom/model.ts
- src/module/apps/sidebar/chat-log.ts
- src/module/item/effect/document.ts
- src/module/rules/rule-element/fast-healing.ts
- src/module/scene/token-document/document.ts
- src/module/system/action-macros/crafting/repair.ts
- src/module/system/check/check.ts
- src/module/system/check/roll.ts
- src/module/system/damage/damage.ts
- src/module/system/damage/helpers.ts
- src/module/system/damage/roll.ts
- src/module/system/damage/terms.ts
- src/module/system/text-editor.ts
- src/scripts/dice.ts
- src/scripts/macros/encouraging-words.ts
- src/scripts/macros/treat-wounds.ts
- types/foundry/client/game.d.ts
- types/foundry/client/roll-term/base.d.ts
- types/foundry/client/roll-term/function-term.d.ts
- types/foundry/client/roll.d.ts
- types/foundry/common/packages/base-system.d.ts
I've slipped in a minor change to fix an error with default token settings but they are still broken on the foundry side until the next release anyway.
> Fix parsing damage rolls with `MathTerms` and remove deprecated `async` option for roll evaluation

- src/module/active-effect.ts
- src/module/actor/base.ts
- src/module/actor/creature/document.ts
- src/module/actor/token-effect.ts
- src/module/canvas/status-effects.ts
- src/module/encounter/combatant.ts
- src/module/scene/token-document/document.ts
- types/foundry/client/config.d.ts
- types/foundry/client/data/documents/actor.d.ts
- types/foundry/client/pixi/placeables/token.d.ts
- types/foundry/common/documents/active-effect.d.ts
- types/foundry/common/documents/token.d.ts
Allows the creation of active effects that carry the "dead" status only. This could be relaxed to allow all statuses registered in `CONFIG.statusEffects` as long as the `overlay` flag is set.
A positive side effect of this change should be that modules that rely on `actor.statuses.has("dead")` should work out of the box now.
> Fix status effect icons

- src/module/system/damage/damage.ts
- src/module/system/damage/dialog.ts
Closes #14439
This sets the initial roll mode of Damage Rolls from undefined to the current user default. Undefined was falling back on the current user default anyway but displaying as Public Roll, leading to assumptions from users.
~~Also changes the secret rollMode handling a bit in damage.ts to compensate for undefined no longer being the default pass-through.~~
> Fix damage dialog rollmode display

- src/module/canvas/status-effects.ts
- src/styles/ui/_token-hud.scss
> Fix status effect title bar and base image opacity in token HUD

- packs/abomination-vaults-bestiary/dread-wisp.json
- packs/abomination-vaults-bestiary/dune-candle.json
- packs/abomination-vaults-bestiary/groetan-candle.json
- packs/abomination-vaults-bestiary/sacuishu.json
- packs/abomination-vaults-bestiary/spellvoid.json
- packs/abomination-vaults-bestiary/will-o-the-deep.json
- packs/agents-of-edgewatch-bestiary/gloaming-will-o-wisp.json
- packs/kingmaker-bestiary/ancient-wisp.json
- packs/kingmaker-bestiary/spirit-of-stisshak.json
- packs/pathfinder-bestiary/will-o-wisp.json
- packs/pathfinder-monster-core/will-o-wisp.json
- packs/pfs-season-2-bestiary/urkhas-3-4.json
- packs/pfs-season-2-bestiary/urkhas-5-6.json
All of these monsters have conditions under which they become temporarily Hidden instead of Invisible (such as Feed on Fear). Their light is also too bright in my opinion, so I toned them down, but I'm open to leaving it alone if people disagree.
> Add suboption for Hidden to wisp's Go Dark

- static/lang/re-en.json
I think this might reduce some of the confusion regarding this prop, but let me know if I'm wrong.
It will add new confusion about what constitutes a "phase", but that's better than a false assurance that priority is the end-all-be-all.
> Make priority tooltip a tiny bit clearer

- packs/pathfinder-bestiary/sewer-ooze.json
- packs/pathfinder-monster-core/sewer-ooze.json
- packs/pfs-season-5-bestiary/commodore-sticky-fingers.json
- packs/pfs-season-5-bestiary/elite-commodore-sticky-fingers.json
- packs/pfs-season-5-bestiary/elite-grig-pfs-q18.json
- packs/pfs-season-5-bestiary/elite-lively-commodore-sticky-fingers.json
- packs/pfs-season-5-bestiary/elite-sewer-ooze-pfs-q18.json
- packs/pfs-season-5-bestiary/elite-sprite-pfs-q18.json
- packs/pfs-season-5-bestiary/lively-commodore-sticky-fingers.json
- packs/pfs-season-5-bestiary/sprite-pfs-q18.json
- packs/pfs-season-5-bestiary/weak-sewer-ooze-pfs-q18.json
Paizo did a bad job on these ones. Incorrect stealth modifier on Pixie from either monster core or bestiary. Incorrect perception modifier on every elite and weak template *except* the grig, where they got the save incorrect.
Fixed the sewer ooze stealth modifiers for being in a sewer from +2 to +3 (text was correct, only the RE was wrong)
> Add quest 18 npcs

- src/module/system/damage/formula.ts
> True means the dice are added to critical without doubling; false means the dice are never added to critical damage; omitted means add to normal damage and double on critical damage.
The image shows: true, false, null
> Fix `DamageDice` with critical set to `false` being included in critical damage

- src/module/system/damage/formula.ts
> Revert "Fix `DamageDice` with critical set to `false` being included in critical damage"

- packs/feat-effects/effect-guided-by-the-stars.json
Currently, the "Guided by the Stars" effect immediately becomes "Expired" when applied to a character and de-activates, making it impossible to use even when the game is paused.
I believe this change will cause it to persist until it is triggered (at which point `removeAfterRoll: true` should remove it?), allowing it to be applied to the next save or skill check as intended.
This is my first contribution to this community, so please let me know if I've misunderstood the way durations work, or if my PR is in some way off!
> Fix duration of Guided by the Stars effect

- packs/actions/recall-under-pressure.json
- packs/equipment-effects/effect-deck-of-destiny.json
- packs/feat-effects/effect-recall-under-pressure.json
Also fix bonus type for Effect: Recall Under Pressure
Make Effect: Recall Under Pressure a self effect
Closes https://github.com/foundryvtt/pf2e/issues/14555
> Fix ChoiceSet labels for Effect: Deck of Destiny and Effect: Recall Under Pressure

- src/styles/actor/_spell-collection.scss
- src/styles/actor/_spell-preparation.scss
- src/styles/item/_feat-sheet.scss
- src/styles/item/_sidebar.scss
Closes https://github.com/foundryvtt/pf2e/issues/14572
> Fix centering for wrapped text in prerequisites and spellcasting

- packs/classfeatures/the-distant-grasp.json
- packs/classfeatures/the-infinite-eye.json
- packs/classfeatures/the-oscillating-wave.json
- packs/classfeatures/the-silent-whisper.json
- packs/classfeatures/the-tangible-dream.json
- packs/classfeatures/the-unbound-step.json
Reverting #14344, closes #14476
Now the original implementation works as intended thanks to #14579.
> Restore surface cantrips for Psi Development archetype psychics

- src/module/chat-message/listeners/cards.ts
At a later date I wish to move inline roll registration to TextEditor#activateListeners(), which should improve performance very slightly and remove these bugs from happening.
> Process user visibility and register inline roll links for expanded descriptions

- src/module/system/damage/damage.ts
- src/module/system/text-editor.ts
Previously it was using the actor name as the flavor text if there was no item associated with it. But the title of the chat message is already the actor name.
Closes https://github.com/foundryvtt/pf2e/issues/14562
> Avoid always revealing actor name for inline rolls of hazard routines

- src/module/system/text-editor.ts
Closes https://github.com/foundryvtt/pf2e/issues/14403
Mostly supercedes https://github.com/foundryvtt/pf2e/pull/14506. That said, this one doesn't handle area damage nor fix the typo.
> Propagate real inline damage traits like holy to item:trait:X options to support IWR

- src/module/canvas/token/object.ts
Closes https://github.com/foundryvtt/pf2e/issues/14587
This stopped working a year ago when the ally check changed. The ally check change is correct (it was changed for the purposes of auras, but you can't be your own ally in pf2e) but flanking code wasn't changed in response.
> Allow duplicates of a linked actor to flank amongst themselves

- packs/classfeatures/the-oscillating-wave.json
Closes #14623
also adds hideIfDisabled to it and other damage dice rule elements for a cleaner damage dialog
> Add missing amp damage for Redistribute Potential

- src/module/actor/creature/document.ts
Also secretly changes the bump to innate to only work if its for an entry for regular spellcasting.
It might be worth incorporating a "base" prop to BaseSpellcastingEntry which marks what proficiency it is based on. Then we can simplify the logic of this and a whole bunch of others.
> Set spellcasting proficiency to trained if at least one entry exists

- src/module/canvas/helpers.ts
- src/module/canvas/layer/template.ts
- src/module/canvas/measured-template.ts
- types/foundry/client/pixi/layers/base/placeables-layer.d.ts
It doesn't fix the templates center-point not snapping properly (which is apparently on purpose for smoother behavior), but it does fix the highlight when placed at a corner for a circle template created directly from canvas controls. It also restores mid edge placements for cones going in a lateral direction.
> Fix highlighting for cone and custom circle templates

- src/module/apps/sidebar/compendium-directory.ts
After looking at https://github.com/foundryvtt/pf2e/pull/14121 and the recent https://github.com/foundryvtt/pf2e/pull/14603, I've tried to extend former solution to the sidebar search. This provided the desired result with no apparent side effects in an non-localized world
> Extend sidebar compendium search to support Babele originalName

- src/scripts/hooks/index.ts
- src/scripts/hooks/ready.ts
- src/scripts/hooks/render-settings-config.ts
- static/lang/en.json
- types/foundry/client/core/hooks.d.ts
We handle the grid ourselves, so letting users configure these would lead to confusion
> Lock configuration of certain core grid settings

- packs/journals/hero-point-deck.json
- packs/other-effects/effect-ancestral-might.json
- packs/other-effects/effect-aura-of-protection.json
- packs/other-effects/effect-called-foe.json
- packs/other-effects/effect-catch-your-breath.json
- packs/other-effects/effect-class-might.json
- packs/other-effects/effect-critical-moment.json
- packs/other-effects/effect-daring-attempt.json
- packs/other-effects/effect-desperate-swing.json
- packs/other-effects/effect-endure-the-onslaught.json
- packs/other-effects/effect-fluid-motion.json
- packs/other-effects/effect-impossible-shot.json
- packs/other-effects/effect-rage-and-fury.json
- packs/other-effects/effect-spark-of-courage.json
- packs/other-effects/effect-strike-true.json
- static/lang/re-en.json
~~I had to make an assumption on the Endure the Onslaught effect by assuming the user of the card and the receiver are the same level, which will be true in 99% of cases, but still noted it in the effect's description.~~
Used origin in Endure the Onslaught and Catch your Breath as suggested by Simon instead. The usual places you'll be dragging this from shouldn't have origin data as far as I know, but it will fall back on the actor's data anyway, so I figured no harm in using it here, in case modules find ways of having the actor post the effect (like Idle's Toolbelt module).
> Add Hero Point Deck effects

- src/module/item/spell/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/14657
> Fix spell heighten rank for npcs above level 20

- src/module/scene/sheet.ts
- src/module/system/settings/automation.ts
- static/templates/scene/sheet-partials.hbs
This issue also exists in v11. requiresReload does not work for any of our split off settings menus, but even then the canvas refresh didn't work because token detection modes weren't reset.
Also sneakily fixes `World Default (undefined)` for v12. I haven't dug into why selectOptions was doing that when localizing though.
> Rerender token vision when RBV setting is changed

- src/module/scene/helpers.ts
- src/module/scene/token-document/document.ts
- src/module/scene/token-document/sheet.ts
Also stealthily changes more maxR fallbacks to null (since null is now infinity)
> Show prepared values instead of source in token config when RBV is enabled

- packs/spell-effects/effect-hand-of-the-apprentice.json
- packs/spell-effects/spell-effect-hand-of-the-apprentice.json
- packs/spells/hand-of-the-apprentice.json
Improve Hand of the Apprentice automation.
Added a spell effect that toggles the attribute modifier to intelligence and adds the critical specialization effect to the selected weapon
> Add effect for Hand of the Apprentice

- packs/backgrounds/mechanical-symbiosis.json
- static/lang/re-en.json
Added a choice set for all skills other than Arcana, added a toggleable roll option for the +1 circumstance bonus to said skill, and added notes with linked Stunned x conditions for failure and crit failure of checks for selected skill.
> Add automation for the Mechanical Symbiosis background

- src/module/system/prosemirror-menu.ts
A piece of https://github.com/foundryvtt/pf2e/pull/14709 I think we can go ahead with right now.
> (In3luki) Avoid prosemirror detecting inline header as h4

- packs/age-of-ashes-bestiary/ilgreth.json
- packs/age-of-ashes-bestiary/mengkare.json
- packs/fists-of-the-ruby-phoenix-bestiary/mafika-ayuwari.json
- packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
- packs/pathfinder-bestiary-2/bastion-archon.json
- packs/pathfinder-bestiary-2/lerritan.json
- packs/pathfinder-bestiary-3/elysian-titan.json
- packs/pathfinder-bestiary-3/hesperid-queen.json
- packs/pathfinder-bestiary-3/thanatotic-titan.json
- packs/pathfinder-bestiary/pit-fiend.json
- packs/stolen-fate-bestiary/obcisidaemon.json
- packs/strength-of-thousands-bestiary/unshadowed-haibram.json
Edited all instances of Meteor Swarm in the bestiary to include the fire damage and a 40-foot burst.
Closes #14721
> Fix NPC copies of Meteor Swarm

- src/styles/actor/character/_biography.scss
Teeny below notice thing yoinked from the v12 work. The rest of the bio fixes assume prosemirror though, so we can leave that for v12.
> Fix character biography h3 styling bleeding into content

- src/module/actor/base.ts
- src/module/item/base/document.ts
- src/scripts/config/index.ts
After evaluation and testing this is not actually something we can support, especially not at this time.
To summarize, ActorPF2e and ItemPF2e have too much behavior baked into them, and we rely on a document hierarchy instead of a system data model hierarchy. We could enable some use cases if we skip all lifetime methods (like prepareBaseData) for sub-types. Early returning if its a module subtype could work but is not the ideal solution. We could make ANOTHER actor base class, this time even more barebones, but this will require extensive system changes for what is effectively a maybe.
I would prefer to re-evaluate once we have system data models and can move some of our lifecycle methods to those system data models.
> Block the existance of item and actor module sub-types

- types/foundry/common/constants.d.ts
- types/foundry/common/data/data.d.ts
- types/foundry/common/data/fields.d.ts
- types/foundry/common/documents/region.d.ts
> Make it possible to get mapped source/model types from `TypedSchemaField`

- packs/spells/awaken-portal.json
Since https://github.com/foundryvtt/pf2e/pull/14050 might not make it before V12, I at least want to fix the error I made back in https://github.com/foundryvtt/pf2e/pull/14043 so that V11 users are not stuck with an invalid Awaken Portal spell state.
> Fix invalid secondary casters in Awaken Portal ritual

- src/module/item/helpers.ts
- Convert description overrides
- Prevent Foundry content links from being treated as markdown links
> Fix pair of issues with markdown conversion

- packs/equipment-effects/effect-aeon-stone-pink-rhomboid.json
- packs/equipment/aeon-stone-pink-rhomboid.json
Having the RE on the item itself doesn't work.
> Add effect for Aeon Stone (Pink Rhomboid)

- src/module/item/base/sheet/sheet.ts
- src/styles/item/_rules.scss
- static/lang/en.json
- static/templates/items/roll-options.hbs
- static/templates/items/rules-panel.hbs
Requires V12 first due to locked tooltip bugfixes.
> Add button to show item roll options in item sheet

- src/styles/actor/character/_spellcasting.scss
> Fix button wrapping in prepared spellcasting entry with long statistic names

- src/module/actor/character/feats.ts
This makes the advanced archetype feats possible to implement. One possibility is https://github.com/foundryvtt/pf2e/pull/14636 but I had another idea floating around that also requires this change.
Technically a bugfix but not worth announcing until the feature is complete.
> Set level taken when adding a feat

- packs/feats/thaumaturges-investiture.json
Closes #14687
Checks for the partial boost that decimalizes the attribute.
> Fix Thaumaturges Investment for partial boosts

- packs/feats/irezoko-tattoo.json
- packs/feats/steady-spellcasting.json
- packs/feats/twin-psyche.json
Closes #14863
Irezoko Tattoo is strangely written - it's listed with all the spellcasting class traits but it only actually gains a class trait when taken. I left the trait list off the feat, but added an alteration for it to gain the trait of the class that takes it.
Steady Spellcasting was reprinted in Player Core 1 under each spellcasting class in there, but because it was printed identical, it should still have the class traits from its previous Legacy printings, so I added Psychic.
> Add Psychic to feats and add trait RE to Irezoko Tattoo feat

- build/lib/compendium-pack.ts
- static/system.json
- types/foundry/common/data/fields.d.ts
This will prevent unnecessary server migrations due to a lack `_stats` (specifically the `coreVersion` field)
> Stamp actors and items with partial `_stats` data on build

- src/module/item/spell/document.ts
rollDamage will automatically try to heighten the spell if it's not a variant, but doesn't pass on the mapIncreases option when it does that.
> Pass mapIncreases when rollDamage heightens the spell

- packs/backgrounds/mortuarium-survivor.json
- packs/spells/carrion-mire.json
- packs/spells/osseous-cage.json
- src/module/actor/familiar/document.ts
- src/module/apps/hotbar.ts
- src/module/item/class/sheet.ts
- src/module/system/settings/homebrew/helpers.ts
- src/module/system/tag-selector/index.ts
- src/module/system/text-editor.ts
- src/scripts/config/index.ts
- src/scripts/macros/hotbar.ts
Also removes unused macro code, and runs the migration again to catch new data entries. The skill list in class sheet data wasn't actually in use..
> Remove CONFIG.PF2E.skills

- packs/seven-dooms-for-sandpoint-bestiary/statue-of-alaznist.json
checked with the PDF, and the rule Elements are set up for the correct value.
> Fix AC value in Construct Armor description for Statue of Alaznist

- src/styles/actor/character/_attack-popout.scss
The attack list shouldn't show the "1.", "2.", etc. in the `<OL>` of strikes.  The character sheet has list-style set to none for ol in general, but the attack-popout doesn't match the same css selector.
While the margin settings mostly cut it off, you can see a bit of the digit poking out on the edge of the window.
> Hide ordered list number in attack-popout

- build/lib/extractor.ts
- src/module/actor/sheet/base.ts
- src/module/item/melee/data.ts
- src/module/item/melee/document.ts
- src/module/item/melee/sheet.ts
- src/module/item/weapon/document.ts
- src/module/migration/migrations/885-convert-alignment-damage.ts
- src/scripts/hooks/init.ts
Note to self: remove unused fields in a `DataModel` migration
> Convert melee items to use `TypeDataModel`-based system data

- src/module/rules/rule-element/roll-option/rule-element.ts
The previous algorithm attempted to match rules to sources on both index and sourceindex, but the index of the rule was its position in the filtered results. This meant that a bug could occur if there were rule elements above the RollOption.
The new algorithm works by iterating on the rules we're trying to search for instead, and then pulling the source based on the source index. We then check if its a RollOption RE just in case.
> Make retrieving mergeable roll options to toggle more consistent

- packs/rusthenge-bestiary/rusted-door.json
Fix action type of Inflict Rust Creep
Move Rust Creep description to passive ability
Fix rarity and traits
Closes https://github.com/foundryvtt/pf2e/issues/14942
> Brush up Rusted Door

- packs/classfeatures/air-gate.json
- packs/classfeatures/earth-gate.json
- packs/classfeatures/metal-gate.json
- packs/classfeatures/water-gate.json
- packs/classfeatures/wood-gate.json
Now that we have action cost roll options in feats, it seems like this is a better place for these to be in.
> Move impulse junction notes to feat description alterations

- packs/ancestries/awakened-animal.json
- packs/heritages/awakened-animal/swimming-animal.json
We've had some people run into the trap of using a versatile heritage with awakened animal. This still leaves a gap in the awakened shark duskwalker niche, but that's a smaller gap than we have now so 🤷
> Fix automation of Awakened Animal and Swimming Animal heritage

- src/module/item/container/document.ts
- static/templates/items/backpack-details.hbs
Addresses: https://github.com/foundryvtt/pf2e/issues/14073
The page for containers shows reduced bulk even if the container is non-stowing.  The definition of a non-stowing container within the system is a "not real" container such as a belt, where the items are functionally "worn" as opposed to "stowed".
The FVTT PF2e system does not allow non-stowing containers to reduce bulk, so the form element is confusing.  This causes them to be hidden, so the user has greater clarity that these numbers will not apply.  The stowing container checkbox is moved upwards as the relevance of the maximum and ignored bulk elements is subordinate to the existence of the stowing field.
https://github.com/foundryvtt/pf2e/assets/22515/6083e8f7-a7c3-40a4-b388-33c183d160da
> Sheets for non-stowing container show should not show form elements for reducing bulk

- src/module/actor/character/sheet.ts
- src/module/actor/sheet/base.ts
Whether an item is actually equipped/invested depends on whether its stowed or not, but the *display* of said elements were based on whether it was in a container or not. This makes the latter match the former.
> Show invested icon within non-stowing containers

- src/module/apps/compendium-browser/tabs/base.ts
- static/lang/en.json
The goal is less to actually stop them, and more to sanity check a full table export. But even 1000 results takes forever to animate in a roll table. A animation that scales in speed would be appreciated for core.
> Prevent table creation and addition with result sizes that are too large

- types/foundry/common/constants.d.ts
- types/foundry/common/documents/table-result.d.ts
The compendium browser was already using CONST.TABLE_RESULT_TYPES.COMPENDIUM so only the types needed to change.
> Update table result type to v12 definition

- packs/season-of-ghosts-bestiary/shisagishin.json
I added Grab to the melee strike.
Closes #15042
> Update Shisagishin to add Grab to its melee attack

- packs/pathfinder-monster-core/iron-warden.json
- static/lang/re-en.json
The "spells that cause rust" portion isn't functional, but at least it will show in the sheet.
Closes https://github.com/foundryvtt/pf2e/issues/15035
> Add custom resistance exception for Iron Warden

- packs/pathfinder-monster-core/fire-giant.json
Fix the Flame attack to reflect the Monster Core attack parameters.
Closes #15040
> correct Fire Giant's (Monster Core) Flame Attack

- src/module/system/damage/dialog.ts
- src/module/system/damage/helpers.ts
- static/lang/en.json
Closes https://github.com/foundryvtt/pf2e/issues/13701
> Show damage type override label in dialog

- src/scripts/hooks/ready.ts
- src/scripts/hooks/render-settings-config.ts
Turns out we don't use this setting for calculating anything anyways, only movement.
We can't unrestrict the other two unless we're happy with weird burst shapes. If people are ok with it, I can also flip that switch once I do the refactoring to eventually allow it.
> Unrestrict grid diagonals setting

- types/foundry/client/data/documents/macro.d.ts
While actor and token are the only ones listed explicitly in the Macro.execute() docs, the code can accept any additional properties and they will be placed into the scope the macro executes in.  There's code in executeScript() that serves no purpose other than allow this to be possible, so it's clearly intended.
This can be used to pass an event to the macro other than the global one or to pass arbitrary parameters.
> Type for Macro.execute() can accept additional properties for scope

- src/module/item/physical/document.ts
- src/module/item/weapon/document.ts
Closes #14971
`prepareSiblingData`, etc. often need to run from doubly-embedded items: call them from the same method of their parents
> Call subitems' secondary data preparation methods

- src/styles/_globals.scss
The line height property was actually something we added and removing it gets us closer to core's styling. The reduced padding is unnecessary and I can roll that back but it makes the text more readable I hope with that in play as well. The way premium modules actually fix this is by applying font-size: 0.9em instead, which we can try instead of adjusting padding if you want.
Before:
After: 
Its more obvious what's going on if you check the second line on the before. The 4th line wasn't impacted because we never applied the line height to inline roll links.
> Fix inconsistent line heights with inline links and content links

- src/module/system/settings/homebrew/data.ts
i.e. any traits you add to feats now propagate to effect traits. 
**Without this PR, #15099 has little to no purpose in regards to homebrew Kineticist Gates.**
Replaces #15083
> Add effectTraits to featTraits propagations

- build/run-migration.ts
- src/global.ts
- src/module/item/base/sheet/sheet.ts
- src/module/migration/migrations/931-expand-re-permissions.ts
- src/module/migration/migrations/index.ts
- src/module/migration/runner/base.ts
- src/module/system/settings/index.ts
- static/lang/en.json
Closes #14203
Allows setting a minimum role for Rule Elements UI access. Choices are Game Master/Assistant GM, Trusted Player, and Player.
> Update Rule Elements UI setting to manage access by user role

- src/module/item/physical/document.ts
Feel free to close if this seems overkill, but I wanted to give it a shot while the muse struck.
This isn't necessary to fix the reported bug. It does fix it on its own, and could maybe lead to the removal of the other guard if we so choose though.
> Guard item.container against cycles

- src/module/system/settings/world-clock.ts
I don't like the setting localization config options but unfortunately the world clock still makes heavy use of them.
> Fix synchronize darkness for current scene default option when changing the world default

- src/module/item/physical/runes.ts
Greater Rooting rune had a Note for success, but the rune only has an effect on Critical Success, and the localization string for the Note text doesn't actually exist.
> Remove rule for success note from Greater Rooting rune

- packs/spells/unimpeded-stride.json
I'm splitting https://github.com/foundryvtt/pf2e/pull/14976 PR into several smaller-sized and logically contained PRs for easier review.
There are bestiary creatures that use legacy version of this spell that still use spell level instead of rank. Namely, those are
- Fallen Champion from Book of the dead
- Ordwi from Rusthenge
I did not change them here but tell me if you want me to.
> Replace level with rank in Unimpeded Stride description

- src/module/canvas/token/object.ts
V12 is mostly in line with how we preferred it in V11
> Remove workaround of upstream token border coloration

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
This fixes the "is from document sheet" check returning true even for chat messages, and uses the item uuid field for all item resolution, which means that now it also works in tooltips. There are already checks for saving throws in the inline check listener.
> Fix regression with chat message inline saves and fix resolution in party exploration

- src/module/actor/helpers.ts
- src/module/rules/rule-element/choice-set/rule-element.ts
Closes https://github.com/foundryvtt/pf2e/issues/14789
While a getter that does this would be fine to have on the actor, I'm not sure on its signature yet. Better to keep it a method for now. An alternative is to rely on https://github.com/foundryvtt/pf2e/pull/15175 but `[...actor.items, ...actor.inventory.subitems]` might not be as intuitive.
> Include sub items in choice sets

- packs/feats/parallel-breakthrough.json
Closes #15028
Allows psychic archetypes to amp their chosen cantrip
> Remove class predicate from Parallel Breakthrough

- packs/equipment/dragonslayers-shield.json
Removed Dragonhide table reference to OGL - it was never part of the item description.
See #15170 for reference.
> Remove Dragonhide table from Dragonslayer's Shield description

- packs/feats/explosive-arrival.json
- static/lang/re-en.json
This would proc a note on Summon spells if a Wizard PC has the Explosive Arrival Feat.
Note - damage does not scale from the note.
> Add ItemAlteration rule element to Explosive Arrival

- packs/book-of-the-dead-bestiary/queen-sluagh.json
- packs/pathfinder-bestiary-3/pakalchi.json
- packs/pathfinder-monster-core/gongorinan.json
- packs/tian-xia-world-guide-bestiary/aso-berang.json
There's two other creatures with 0 but they have whyzo going on for their spells and no specified DC, and it's not worth chasing it down.
> Fix several creatures with missing spellcasting DCs

- src/module/actor/creature/document.ts
- src/scripts/ui/inline-roll-links.ts
- static/lang/en.json
This bug is actually quite old. A below mention new feature is that actor.getStatistic() now resolves "best casting entry for tradition" rather than handling it in the inline check code.
Enable hide whitespace to reduce the diff.
> Show error instead of silently failing when rolling inline checks for invalid actors

- src/module/actor/actions/base.ts
Fixes an edge case introduced by https://github.com/foundryvtt/pf2e/pull/13198
> Fix sending description to chat for actions with variants when no variant is specified

- src/module/system/statistic/statistic.ts
It seems we're going with the "add stuff in ActionsCheck to show alternative labels" without putting it in config so that's what we're doing.
Eventually we need to remove the generic messages from the slug key'd super collection.
> Use specific skill check localizations for check dialogs and messages

- packs/feat-effects/effect-combat-premonition.json
- packs/feat-effects/effect-guide-the-timeline.json
- packs/feat-effects/effect-turn-back-the-clock.json
- packs/feats/chronoskimmer-dedication.json
- packs/feats/combat-premonition.json
- packs/feats/guide-the-timeline.json
- packs/feats/turn-back-the-clock.json
- static/lang/re-en.json
- Add suboptions for Chronoskimmer Dedication's stabilize and destabilize timestream
- Add effects for Combat Premonition, Guide the Timeline and Turn Back the Clock
> Brush up automation for Chronoskimmer archetype

- package-lock.json
- package.json
Add a node 20 dependency to the package.json to avoid issues in regards to parsing dice ([18-19 said to be broken by Tikael](https://discord.com/channels/880968862240239708/880969304365994034/1253736595056496680), and node 21 also broke my local build process.)
> Add engines: node to package.json

- src/module/actor/base.ts
- src/module/actor/data/base.ts
- src/module/scene/token-document/document.ts
This enables a Shield's HP to be edited on the Token Attribute bar, just like HP.
> Token Attribute: Allow editing Shield HP

- src/module/rules/rule-element/damage-alteration/rule-element.ts
This allows DamageAlteration to support selectors like:
```
"selectors": [
"{item|id}-inline-damage"
]
```
Cribbed from /src/module/rules/rule-element/damage-dice.ts:59
> Allow DamageAlteration REs to have resolvable selectors

- packs/classfeatures/attack-refiner.json
- packs/classfeatures/automated-impediments.json
- packs/classfeatures/deadly-strike.json
- packs/classfeatures/enhanced-damage.json
- packs/classfeatures/extensible-weapon.json
- packs/classfeatures/heavy-construction.json
- packs/classfeatures/impossible-alloy.json
- packs/classfeatures/incredible-resistance.json
- packs/classfeatures/momentum-retainer.json
- packs/classfeatures/multisensory-mask.json
- packs/classfeatures/omnirange-stabilizers.json
- packs/classfeatures/perfect-fortification.json
- packs/classfeatures/physical-protections.json
- packs/classfeatures/rune-capacity.json
- packs/classfeatures/tangle-line.json
Class Features granted by Revolutionary Innovation are not in the system. This is a first step to add these and then build towards adding automation.
> Add class features for Revolutionary Innovation

- src/module/actor/actions/single-check.ts
- src/module/actor/types.ts
- src/module/actor/values.ts
This is only used by action macros and its a bit confusing to understand what its being used for there. Please review @nikolaj-a when you get the chance, since I don't know how to actually test this.
> Use the values of other objects at runtime for determining valid dc slugs

- src/styles/actor/loot/_index.scss
- static/templates/actors/loot/sheet.hbs
Tag styling has changed a bit, which broke the layout. Loot shouldn't be using tag styling for this anyways.
> Fix regression with loot sheet type

- packs/feats/spellshot-dedication.json
Closes #15231
Conjure Bullet is not referenced anywhere else in the system. Let me know if you want me to delete the action while I'm at it, too.
> Remove Conjure Bullet grant from Spellshot Dedication

- packs/equipment/choker-of-elocution-greater.json
- packs/equipment/choker-of-elocution.json
Also, removed plural languages from the base item craft requirements as it refers to the Greater version
Also, please check if the wording in the Greater version would be better as "This platinum choker bears characters from alphabets of three languages". It's kind of editorializing, but the Greater item has no distinct description in the source anyway.
> Fix Choker of Elocution (Greater) craft requirements

- packs/pfs-season-5-bestiary/fey-table-hound.json
- packs/pfs-season-5-bestiary/weak-leaf-leshy-q19.json
I didn't do the 3-4 variants for leaf leshy and elite leaf leshy because the inline save DC is an obvious editing error. 
The weak template didn't apply because of the level 0 being undefined issue (didn't adjust HP or inline DCs on template application)
> Add Quest 19 NPCs

- src/module/actor/familiar/sheet.ts
- src/module/actor/npc/sheet.ts
- src/module/actor/sheet/data-types.ts
- src/styles/actor/_red-action-boxes.scss
- static/templates/actors/npc/partials/action.hbs
Updates action.hbs, _red-action-boxes.scss, data-types.ts familiar/sheets.ts and npc/sheets.ts to prepare frequency data for use in the .hbs file and updates the template to include it on the sheet. 
the .tracking class in _red-action-boxes.scss appeared to be unused. With only the npc, familiar and hazard sheets importing the .scss file and none using the class. Thus I've updated the css to produce visually consistent results. 
Additional the interface AbilityViewData appeared to only be imported for the familiar and npc so it should have limited/no downstream effects.
> Add Action Frequency Tracking to Familiar and NPC sheets

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
Adds `itemUuid` data attribute to `@Template` tags and adds `item.getOriginData()` results to templates created from inline buttons.
Example: `@Template` tag from Blazing Wave kineticist feat. Includes Fireball spell for comparison.
| Before | After |
| :-----: | :----: |
| ![image](https://github.com/foundryvtt/pf2e/assets/32039708/f244a94f-0d03-4a10-ba34-c3730e422b0e) | ![chrome_yvI9kHcZya](https://github.com/foundryvtt/pf2e/assets/32039708/90ff28c9-396e-4a91-b925-6bd0d7f32c6d) |
> More consistent origin flags on templates

- packs/one-shot-bestiary/grazing-deer.json
Two small adjustments to match the module text: "THe" -> "The" and "NPCs" -> "PCs"
> Fix typos in Grazing Deer hazard

- packs/actions/claw-stance.json
- packs/actions/talon-stance.json
- packs/feats/clawdancer-dedication.json
- Created two actions for Claw Stance and Talon Stance that grant their respective stances.
- Added grant item rule element to Clawdancer dedication to grant the above.
> add grant item to Clawdancer dedication

- src/module/chat-message/document.ts
As far as I know, they only print red in the console, but better not print that at all.
> Fix regression from chat messages referring to compendium items

- src/module/actor/character/sheet.ts
- src/module/actor/data/base.ts
- src/styles/actor/_index.scss
- static/lang/en.json
- static/templates/actors/character/partials/strike.hbs
- static/templates/actors/character/tabs/actions.hbs
Show Unready Strikes hasn't worked for a long time, so its been removed.
> Add toggle to hide strikes from stowed weapons

- packs/equipment/marvelous-medicines-greater.json
- packs/equipment/marvelous-medicines.json
added `"requiresEquipped": false` to enable use of bonus when not held.
Closes #13907
> Allow Marvelous Medicines to be used when not held

- packs/pathfinder-bestiary-2/sceaduinar.json
Closes https://github.com/foundryvtt/pf2e/issues/15405
> Fix Sceaduinar's spell list and give it void healing

- packs/feats/breath-control.json
- packs/feats/experienced-professional.json
- packs/feats/fast-recovery.json
- packs/feats/lengthy-diversion.json
- packs/feats/oddity-identification.json
- packs/feats/schooled-in-secrets.json
- packs/feats/streetwise.json
- packs/feats/student-of-the-canon.json
- packs/feats/subtle-theft.json
- packs/feats/terrain-stalker.json
- static/lang/re-en.json
- Remove unnecessary note from Breath Control
- Localise and narrow down Experienced Professional and Fast Recovery notes
- Add note on critically successful Create a Diversion action to Lengthy Diversion
- Add alternative skill action macros to Schooled in Secrets and Streetwise
- Replace unlocalised notes in Student of the Canon with predicated Adjust Degree of Success rule elements
- Add compendium links to Subtle Theft and Terrain Stalker
> Brush up some Player Core general feats

- src/styles/actor/character/_actions.scss
- src/styles/actor/tabs/_actions.scss
- static/templates/actors/character/partials/elemental-blast.hbs
- static/templates/actors/character/partials/strike.hbs
I recommend hiding whitespace for this diff.
> Remove gap between name and buttons for unready strikes

- packs/equipment/silver-salve.json
From "instead of its normal precious material" to "instead of its normal material", and usage to "held in two hands"
> Correct usage and description of Silver Salve

- src/styles/actor/_index.scss
- static/lang/en.json
- static/templates/actors/character/tabs/actions.hbs
Feel free to close if you think its not an improvement. I was worried that the previous button didn't properly communicate what it was.
> Change styling of stowed strikes toggle

- packs/heritages/versatile-heritages/aiuvarin.json
- packs/heritages/versatile-heritages/aphorite.json
- packs/heritages/versatile-heritages/beastkin.json
- packs/heritages/versatile-heritages/changeling.json
- packs/heritages/versatile-heritages/dromaar.json
- packs/heritages/versatile-heritages/reflection.json
- packs/heritages/versatile-heritages/suli.json
Removes duplicate traits already included in item from RE.
> remove duplicate traits from Versatile heritages

- src/module/canvas/measured-template.ts
- src/module/canvas/token/aura/util.ts
- types/foundry/client/data/documents/client-document.d.ts
Inconsequential for our purposes, but some modules benefit from the data being present.
> Include point sources in `testCollision` calls lacking them

- packs/feat-effects/effect-raise-symbol.json
- packs/feats/raise-symbol.json
Emblazon Armament was unified in https://github.com/foundryvtt/pf2e/pull/14748
> Update Raise Symbol to handle unified Emblazon Armament

- packs/feats/intense-implement.json
Works just like the 1st and 2nd adept feats to select an owned implement feature that does not yet have the adept tag.
This works fine with the Thaum EV module, which picks up the adept tag just as it does with the other feats that add it.
> Add implement choiceset rules to Intense Implement feat

- src/styles/actor/character/_actions.scss
- src/styles/actor/tabs/_actions.scss
- static/templates/actors/character/partials/elemental-blast.hbs
- static/templates/actors/character/partials/strike.hbs
Also simplifies the HTML a bit and reduces vertical space expenditure when wrapping occurs.
> Fix regression with character strike name not wrapping

- static/lang/en.json
I caught this one while checking on an issue. This was a miss on my part.
As it turns out, changing the whole container breaks the labels on the drop-down menu in the Property Runes section. 
Will see about possibly updating this with proper guidance once we get over the PC2 rush
> undo breaking changes in en.json

- packs/actions/activate-resonant-reflection.json
- packs/campaign-effects/resonant-reflection-reflection-of-life.json
- packs/campaign-effects/resonant-reflection-reflection-of-light.json
- packs/campaign-effects/resonant-reflection-reflection-of-stone.json
- packs/campaign-effects/resonant-reflection-reflection-of-storm.json
- packs/campaign-effects/resonant-reflection-reflection-of-water.json
- static/lang/re-en.json
- Created `Activate Resonant Reflection` action.
- Added Item Alteration RE to the corresponding Resonant Reflection items to add the effect description and traits to the  `Activate Resonant Reflection` action.
- Added Grant Item RE to the above items.
- Localized the descriptions in re-en.json.
> Add action to Resonant Reflection Campaign items.

- src/module/rules/rule-element/item-alteration/alteration.ts
- src/module/rules/rule-element/item-alteration/schemas.ts
Closes #13910 
Uses Math.trunc() to ensure Hardness is always an integer and abides by the round down rule.
> Allow ItemAlteration Hardness to use non-integer alteration values

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
```
[[/act demoralise roll-options=some:other:option traits=bravado]]
```
Or using the `options` alias:
```
[[/act demoralise options=some:other:option traits=bravado]]
```
> Add traits and roll-options parameters to /act inline links

- packs/spell-effects/spell-effect-lucky-number.json
Lucky Number needs to be associated with a 1d20 roll, so this sets the Effect to Formula to roll the d20 for the player when the effect is attached.
> Add Formula roll to Lucky Number Spell Effect

- src/module/rules/rule-element/damage-alteration/alteration.ts
The title is the patch note version. The developer deets is that override dice use the properties at the base level as a pseudo-predicate to match to what entry to override. If an alteration hits one of them, the match will no longer succeed.
> Prevent damage alterations from disabling override dice

- src/module/rules/rule-element/strike.ts
Fixes these warnings:
```
pf2e.mjs:1580 PF2e System | Strike rules element on item Cloud Form (Compendium.pf2e.lost-omens-tian-xia-world-guide.Actor.9jvXTVcMNTx3kGfU.Item.5J06Ku4CI2tpvzEV) failed to validate: Unrecognized weapon group: null
pf2e.mjs:1580 PF2e System | Strike rules element on item Change Shape (Compendium.pf2e.lost-omens-tian-xia-world-guide.Actor.zrx1qjf1WbSYllvz.Item.DFXZDYeKTRu6SKvv) failed to validate: Unrecognized weapon group: null
pf2e.mjs:1580 PF2e System | Strike rules element on item Phantom Flames (Compendium.pf2e.lost-omens-tian-xia-world-guide.Actor.zrx1qjf1WbSYllvz.Item.EuFSoclL9h9ZYg1y) failed to validate: Unrecognized weapon group: null
pf2e.mjs:1580 PF2e System | Strike rules element on item Torch …
```
> Allow Strike REs to have a null weapon group

- packs/feats/artokuss-fire.json
Artokus's Fire has a RollOption with the domain of `attack-roll` but the Note and DamageDice predicated on that are both on damage rolls.
> Fix domain on Artokus's Fire RollOption

- src/module/system/action-macros/basic/escape.ts
The find best unarmed attack modifier code doesn't work if the best is less than zero.  This can easily happen when MAP -10 is used.
> Fix Escape not picking unarmed attacks with negative modifiers

- src/module/canvas/layer/template.ts
- src/module/scene/document.ts
- src/scripts/hooks/canvas-ready.ts
`BaseGrid` now has boolean getters for each type
> Remove `ScenePF2e#hasHexGrid` getter

- src/module/canvas/layer/template.ts
- add grid type check to `MeasuredTemplatePF2e` `snappingMode` function
- use appropriate `GRID_SNAPPING_MODES` for templates on hex grids
- use `snappingMode` on hex grids instead of using default implementation
- [BREAKING] remove `hasHexGrid` from `ScenePF2e` as `isHexagonal` serves the same purpose
> Adjust Hex Grid Logic for MeasuredTemplatePF2e

- src/module/actor/modifiers.ts
- src/module/item/physical/runes.ts
- src/module/item/weapon/document.ts
- src/module/item/weapon/values.ts
- src/module/system/damage/weapon.ts
- static/lang/en.json
Surprisingly, this is the first rune (at least among those with system support) that deals an additional flat amount of damage.
Closes #15617
> Add support for Shockwave rune

- src/module/actor/modifiers.ts
- src/module/item/melee/document.ts
- src/module/rules/rule-element/damage-alteration/alteration.ts
- src/module/system/damage/weapon.ts
A worthy refactor will be to process such damage as `ModifierPF2e`/`DamageDicePF2e` throughout
> Add support for damage alterations of base weapon damage

- packs/equipment/dancing-scarf.json
Fixing a typo I noticed today.
The Performance bonus for the base Dancing Scarf is only +1, not +2. (+2 comes in at the Greater level.)
The modifier is already configured correctly, but the description text is confusing as it uses the wrong value.
https://2e.aonprd.com/Equipment.aspx?ID=3074
> Fix Performance bonus for Dancing Scarf

- packs/ancestries/kobold.json
- Kobolds no longer have Draconic Exemplar as an ancestry feature
- Kobolds have Sakvroth instead of Draconic as a base language
- Draconic, Empyrean, and Fey were added to their additional language list
> Update Kobold Ancestry for PC2

- packs/classfeatures/furious-footfalls.json
- packs/feats/breath-of-the-dragon-dragonblood.json
also fix Furious Footfalls not having a slug on its Adjust Modifier
Closes #15689
Closes #15692
> Add action cost to Breath of the Dragon dragonblood feat

- packs/actions/destructive-vengeance.json
- packs/actions/flash-of-grandeur.json
- packs/actions/glimpse-of-redemption.json
- packs/actions/iron-command.json
- packs/actions/liberating-step.json
- packs/actions/retributive-strike.json
- packs/actions/selfish-shield.json
- packs/classfeatures/exalted-reaction.json
- packs/classfeatures/relentless-reaction.json
- packs/feat-effects/effect-champions-extra-damage.json
- packs/feat-effects/effect-selfish-shield.json
- packs/feats/dragonslayer-oath.json
- packs/feats/esoteric-oath.json
- packs/feats/fiendsbane-oath.json
- packs/feats/gruesome-strike.json
- packs/feats/instrument-of-slaughter.json
- packs/feats/instrument-of-zeal.json
- packs/feats/shining-oath.json
- static/lang/re-en.json
- Remove unnecessary toggles on champion reactions, except on Retributive Strike, whose toggle is predicated on features that make use of it.
- Add effect for the extra spirit damage that Desecration, Iniquity and Obedience get, and implement Gruesome Strike and Implement of Slaughter through it.
- Turn erronously added Iniquity cause Notes into Item Alterations in Exalted Reaction and Relentless Reaction
> Brush up Champion reactions implementation

- packs/classfeatures/deity-champion.json
per the PFS clarification https://paizo.com/pathfindersociety/characteroptions
> Allow Champion's Aura to be granted to archetype champions

- src/styles/actor/character/_sidebar.scss
- static/templates/actors/character/sheet.hbs
The inline height attribute was vertically stretching it a few pixels; current width is preserved.
Before:
After:
> Fix dimensions of pathfinder logo on PC sheet

- src/module/canvas/layer/template.ts
The above `isSquare` check means that this code will no longer be called and I hate to see dead code stick around.
> Remove Unreachable Hex Check

- packs/feats/breath-of-the-dragon-dragonblood.json
- packs/feats/draconic-resistance.json
- packs/feats/formidable-breath.json
- packs/feats/lingering-breath.json
- packs/heritages/versatile-heritages/dragonblood.json
- static/lang/re-en.json
Every current option only has cones, but should be future-proofed if line options are ever added, as Breath of the Dragon implies. Same with Draconic Resistance, no dragon offers piercing or slashing damage, but should work if they're ever added.
Draconic Exemplar must be chosen at character creation in this implementation, as we don't have a great way to implement the delay that the book allows.
Partially addressess #15726
> Automate dragonblood's Draconic Exemplar feats

- packs/feats/widen-spell.json
Using the shiny shiny new area size Item Alteration. Figured we can lose the description addendum now that it's actually automated.
> Automate Widen Spell

- packs/equipment-effects/effect-sulfur-bomb.json
- packs/equipment/sulfur-bomb-greater.json
- packs/equipment/sulfur-bomb-lesser.json
- packs/equipment/sulfur-bomb-major.json
- packs/equipment/sulfur-bomb-moderate.json
- packs/sky-kings-tomb-bestiary/ashrin.json
- static/lang/re-en.json
I believe it's clear enough that the effect is meant to be on the successful, but not critically successful hit, but I'm open to suggestions on renaming it something else. Like `Sulfur Bomb (Success)` or `Sulfur Bomb (Hit)` perhaps
Closes #15752
> Rename Sulfur Bomb effect

- packs/classfeatures/tempest.json
Not sure if spell attack rolls are supposed to have the ranged attack roll selector, but here's a workaround for now if it is.
> Fix ranged attack penalty on Tempest curse

- static/templates/chat/check-modifiers-dialog.hbs
- static/templates/chat/damage/damage-modifier-dialog.hbs
Refactor for check, surface level bugfix for damage. All computations check "enabled", but the dialog was checking "ignored". This makes them both check the same properties.
> Fix damage dialog toggles not reflecting correct state

- packs/spell-effects/spell-effect-courageous-anthem.json
Should only show now when the roll is enabled.
Closes #15794
> update Courageous Anthem effect to hide Discordant Voice damage dice

- packs/classfeatures/offensive-boost.json
- packs/feat-effects/effect-offensive-boost.json
- packs/feats/persistent-boost.json
- static/lang/re-en.json
Closes #14704
Since construct and inventor use an effect for their particular cases, I used that for their persistent boost automation.
> Automate Persistent Boost

- packs/feats/advanced-weapon-training.json
- packs/feats/scars-of-steel.json
- packs/feats/untamed-form.json
One gap in this is that it doesn't work in conjunction with fighter weapon mastery, etc that use MartialProficiency to create subgroups of weapons, but better to have a 90% solution than a 0% solution.
Closes #7605
> Automate Advanced Weapon Training

- packs/feats/herbalist-dedication.json
Changed Herbalist Dedication batch size to 1 in order to better match PC2 while we wait for the Alchemist UI update
> Update Herbalist Dedication batch size to match PC2

- packs/classfeatures/bloodline-aberrant.json
- packs/classfeatures/bloodline-angelic.json
- packs/classfeatures/bloodline-demonic.json
- packs/classfeatures/bloodline-diabolic.json
- packs/classfeatures/bloodline-draconic.json
- packs/classfeatures/bloodline-elemental.json
- packs/classfeatures/bloodline-fey.json
- packs/classfeatures/bloodline-genie.json
- packs/classfeatures/bloodline-hag.json
- packs/classfeatures/bloodline-harrow.json
- packs/classfeatures/bloodline-imperial.json
- packs/classfeatures/bloodline-nymph.json
- packs/classfeatures/bloodline-phoenix.json
- packs/classfeatures/bloodline-psychopomp.json
- packs/classfeatures/bloodline-shadow.json
- packs/classfeatures/bloodline-undead.json
- packs/classfeatures/bloodline-wyrmblessed.json
- packs/classfeatures/strategic-strike.json
- packs/feat-effects/effect-blood-sovereignty.json
- packs/feats/blood-rising.json
- packs/feats/blood-sovereignty.json
- packs/feats/crossblooded-evolution.json
- packs/feats/explosion-of-power.json
- packs/feats/propelling-sorcery.json
- packs/feats/reflect-harm.json
- packs/feats/tap-into-blood.json
- packs/feats/terraforming-trickery.json
- static/lang/re-en.json
This is a lot. I recommend building and playing around with this, but the idea is using other-tags Item Alteration to tag which spells should get Blood Magic, that way additional Blood Magic can be added to the appropriate spells.
- Blood Sovereignty and Blood Ascendancy will make a Second Blood Magic toggle appear, which will add a second blood magic to a spell or to the Blood Rising feat respectively.
- Crossblooded Evolution adds a tag to the Bloodline class feature in order for it to only grant the Blood Magic effects, but none of the skills, tradition, and most importantly, the blood magic spell list, which is exclusive to what you receive at character creation. 
- Third-parties should be able to build their own bloodlines and blood magic feats following the format here, and they …
> Automate Player Core 2 Sorcerer Blood Magic Feats

- packs/classfeatures/blessed-armament.json
- packs/classfeatures/blessed-shield.json
- packs/classfeatures/blessed-swiftness.json
- packs/classfeatures/blessing-of-the-devoted.json
- packs/feats/expand-aura.json
Allows 3rd party blessings to show in the Choice Set
Closes #15893
Also increase the priority on Expand Aura, as its toggle was not working due to depending on the Champion's Aura roll option
> Use tag-based Choice Set for Blessing of the Devoted

- src/module/canvas/ruler.ts
Adds support for "Hexagonal Columns - Odd" to RulerPF2e grid-snapping mode.
> RulerPF2e - Fix Hexagonal Snapping

- packs/equipment-effects/effect-choker-arm-mutagen-greater.json
- packs/equipment-effects/effect-choker-arm-mutagen-lesser.json
- packs/equipment-effects/effect-choker-arm-mutagen-major.json
- packs/equipment-effects/effect-choker-arm-mutagen-moderate.json
Added the afterDerived phase to the mutagen effects so that it combines with size increases from spells and effects instead of being ignored.
Fixes #15316
> Choker-Arm Mutagen fix to account for size changes

- packs/classfeatures/mighty-rage.json
Added a simple toggle for Mighty Rage which doubles the rage damage which satisfies the requirement of mighty rage. 
Fixes #15777
> Add toggle to the Mighty Rage feature

- packs/classfeatures/ancestors.json
- packs/classfeatures/battle.json
- packs/classfeatures/bones.json
- packs/classfeatures/cosmos.json
- packs/classfeatures/curse-of-ancestral-meddling.json
- packs/classfeatures/curse-of-engulfing-flames.json
- packs/classfeatures/curse-of-inclement-headwinds.json
- packs/classfeatures/curse-of-outpouring-life.json
- packs/classfeatures/curse-of-the-living-death.json
- packs/classfeatures/curse-of-the-mortal-warrior.json
- packs/classfeatures/curse-of-the-skys-call.json
- packs/classfeatures/curse-of-torrential-knowledge.json
- packs/classfeatures/flames.json
- packs/classfeatures/life.json
- packs/classfeatures/lore.json
- packs/classfeatures/tempest.json
Before
After
Perhaps how I should've entered them to begin with, this allows them to be sent to chat nicely formatted and compact, and gives a more accurate picture on where the penalties come from on tooltips and roll breakdowns.
> Add oracle curses as class features

- packs/spells/inner-radiance-torrent.json
Without this, it is missing a `origin:item:cast:actions` roll option. The 2 round version can be predicated on by excluding the 2 and 3-action ones.
> Add 2 Action version to Inner Radiance Torrent

- packs/feats/diverse-lore.json
The text of the feat clearly states it only applies to recall knowledge checks.
This also helps the RK macro in workbench identify this modifier as relating to recall-knowledge.
> Add action:recall-knowledge to diverse-lore FlatModifier predicate

- src/module/system/settings/homebrew/languages.ts
- static/templates/system/settings/homebrew.hbs
The render in the languages update method was eating the update to the languages itself as well, and since updateObject always leads to a re-render it was unnecessary.
> Fix updating homebrew languages

- packs/classfeatures/bloodline-aberrant.json
- packs/classfeatures/bloodline-angelic.json
- packs/classfeatures/bloodline-demonic.json
- packs/classfeatures/bloodline-diabolic.json
- packs/classfeatures/bloodline-draconic.json
- packs/classfeatures/bloodline-elemental.json
- packs/classfeatures/bloodline-fey.json
- packs/classfeatures/bloodline-genie.json
- packs/classfeatures/bloodline-hag.json
- packs/classfeatures/bloodline-harrow.json
- packs/classfeatures/bloodline-imperial.json
- packs/classfeatures/bloodline-nymph.json
- packs/classfeatures/bloodline-phoenix.json
- packs/classfeatures/bloodline-psychopomp.json
- packs/classfeatures/bloodline-shadow.json
- packs/classfeatures/bloodline-undead.json
- packs/classfeatures/bloodline-wyrmblessed.json
The archetype wasn't actually getting blood magic, but they were seeing a useless suboption.
> Limit bloodline blood magic suboption to sorcerer class

- packs/feat-effects/effect-oracular-warning-initiative.json
This avoids needing to resolve the origin's cursebound value, which may not be there if the user is not following the exact rules (cursebound value increases before the action's effects take place if you weren't already cursebound).
> Use AdjustModifier on Oracular Warning initiative effect

- src/module/actor/party/document.ts
- src/module/encounter/combatant.ts
- types/foundry/client/data/documents/combatant.d.ts
- Don't add members that are already being added
- Don't add members lacking placed tokens
- Perform addition as part of current operation
> Fix edge cases when adding party to encounter

- src/module/system/text-editor.ts
When I refactored it, I didn't notice that all was only omitted from flat checks.
Closes https://github.com/foundryvtt/pf2e/issues/15990
> Fix elite/weak affecting flat checks

- packs/feats/deadly-aspect.json
- split the one Adjust Strike into three to account for separate definitions.
Closes #16008
> update Deadly Aspect rule elements to now work

- packs/feats/iruxi-armaments.json
- added slugs. labels and images for the tail and fang strikes.
- added a flag to the Roll Option.
- changed how many times the feat can be taken.
> update rule elements on Iruxi Armaments feat

- packs/classfeatures/lesson-of-bargains.json
- packs/classfeatures/lesson-of-calamity.json
- packs/classfeatures/lesson-of-decay.json
- packs/classfeatures/lesson-of-favors.json
- packs/classfeatures/lesson-of-the-flock.json
- packs/classfeatures/lesson-of-the-frozen-queen.json
- packs/classfeatures/lesson-of-the-shark.json
- Also added icons to the three lessons added in Howl of the Wild.
Closes #16030
> correct book sources for certain Witch lesson feats

- packs/heritages/tripkee/thickskin-tripkee.json
Heritage HP was set to 20, changed it to 8 as intended.
Closes #16046
> Fix hp for thickskin tripkee heritage

- src/module/system/damage/weapon.ts
processBaseDamage() wasn't getting passed the roll options and was using the domains (also a string[]) as if they were the roll options when it applied alterations.
> Fix DamageAlteration predicates for base damage

- packs/equipment-effects/effect-bestial-mutagen-greater.json
- packs/equipment-effects/effect-bestial-mutagen-lesser.json
- packs/equipment-effects/effect-bestial-mutagen-major.json
- packs/equipment-effects/effect-bestial-mutagen-moderate.json
- packs/feats/mutant-physique.json
By moving the damage dice upgrades to the Mutant Physique feat, as well as its intimidation bonus and the resistance to physical damage from Juggernaut Mutagen.
Closes #16090
> Fix Bestial Mutagen Strikes

- static/system.json
Necessary for referencing `game.compendiumArt`
> Bump minimum core version to 12.328

- packs/classfeatures/explode.json
- packs/feat-effects/effect-unstable-check-failure.json
- Change the Item Alteration RE predicate only to proc when the failure effect is not on the actor.
- Changed the duration of the Unstable Check Failure Effect to Unlimited, as it's supposed to persist until action is taken per the rules.
> brush up Inventor Unstable Check rule element and effect

- src/module/actor/npc/types.ts
- src/module/item/base/sheet/sheet.ts
- src/module/item/spell/sheet.ts
- src/module/sheet/helpers.ts
- src/module/system/html-elements/tagify-tags.ts
- static/templates/items/partials/other-tags.hbs
The otherTags property name was already taken by armor and consumable which wants different data entirely.
> Do not persist other tags added via item alterations

- src/styles/_tags.scss
For the purpose of the red attack tag in a strike becoming blue in starfinder.
> Refer to trait color in default red tag styling

- static/templates/actors/character/tabs/character.hbs
Certain elements like the character sheet and chat messages override padding to zero. Chat messages lost out due to specificity. 
A better solution is to remove the padding from the global styling but its not safe to do that during a patch release.
> Remove tag_alt from character sheet trait tags

- src/module/system/statistic/statistic.ts
- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
- static/lang/en.json
> Allow "roller role" (target/origin status) of inline check rolls to be overridden

- packs/feats/advanced-domain.json
- packs/feats/domain-initiate.json
- packs/feats/expanded-domain-initiate.json
Soul Warden Dedication counts the number of Soul Warden feats towards the radius of the light it emits, but some of the Cleric feats like Domain Initiate, Expanded Domain Initiate, and Advanced Domain Initiate are also accessible to Soul Wardens. These now count towards the total feat count for the archetype.
Closes https://github.com/foundryvtt/pf2e/issues/16164
> Count Domain Initiate Cleric feats toward Soul Warden feat count

- packs/equipment-effects/effect-storm-breath.json
- packs/equipment/storm-breath.json
- packs/extinction-curse-bestiary/abberton-ruffian.json
also update a Bottle from some Extinction Curse ruffians. Both of these had the Serum of Sex Shift icon, presumably from way before it was replaced with TangleLion's icon.
> Update Storm Breath icon to use core icon

- packs/ancestries/human.json
update source to Pathfinder Player Core, license to ORC and remaster to true. Closes  #16219
> update Human ancestry publication source to remaster

- packs/spell-effects/spell-effect-hand-of-the-apprentice.json
- packs/spells/hand-of-the-apprentice.json
- Added a choice set and roll option to get the spellcasting attribute used in the spellcasting entry.
- Added additional Flat Modifiers for the charisma and wisdom that only proc on the corresponding roll option
> Brush up Hand of the Apprentice wizard focus spell

- packs/quest-for-the-frozen-flame-bestiary/azi.json
Also refresh copies of False Life (False Vitality)
They were inadvertently removed by https://github.com/foundryvtt/pf2e/pull/16234
> Fix missing spell sourceIds for Azi

- static/templates/actors/character/attribute-builder.hbs
Just a little issue with `PF2E.Background` leading to no localization key.
> Fix background label in the attribute boosts menu

- packs/feats/champion-dedication.json
- packs/feats/sentinel-dedication.json
- Update the RE to bring them up to match those in the Armor Proficiency General Feat and account for someone taking both dedications.
Closes #16296
> Update Sentinel and Champion Dedication armor proficiency Rule Elements

- packs/feat-effects/effect-fey-blood-magic.json
- packs/feats/winter-sleet.json
- packs/rage-of-elements-bestiary/living-magma.json
- packs/sky-kings-tomb-bestiary/giant-leech.json
Except the Kingmaker ones because I know nothing about them. Also fix description of the Fey Blood Magic effect.
> Use `rollerRole` on remaining `resolve()` inline checks

- src/module/item/base/document.ts
- src/module/item/campaign-feature/document.ts
- src/module/item/feat/document.ts
Adds _buildEmbedHTML to ItemPF2e so that `@Embed` can be used to reference the description (and prerequisites if present) stored in the item directly.
This will simplify the maintenance of the Archetypes journal (as well as anywhere else that text is duplicated from Items into Journal entries.
For example, in the Acrobat page of the Archetypes journal, the first feat reference would be replaced by:
```
<H2> @UUID[Compendium.pf2e.feats-srd.Item.aFygWxgSv82WyCsl]{Acrobat Dedication} Feat 2
<p> @Embed[Compendium.pf2e.feats-srd.Item.aFygWxgSv82WyCsl inline]
```
whereas **Dodge Away** would require an additional new parameter to prevent the HR being added immediately after the prerequisites (since a HR is added in the body of the feat description):
```
<H2> …
```
> Allow `@Embed` of Items

- packs/feats/fortuitous-shift.json
- Removed the label as overriding description to the DC as it is displaying incorrectly/weirdly.
- Added the suggested RE per the linked issue (let me know if you want me to drop this).
Closes #16384
> Brush up Fortuitous Shift

- packs/feats/pitborn.json
- src/module/rules/rule-element/choice-set/prompt.ts
Closes https://github.com/foundryvtt/pf2e/issues/16339. Sneakily also fixes pitborn
> Fix choice set homebrew item dropzone for button lists

- src/module/chat-message/document.ts
- types/foundry/client-esm/canvas/module.d.ts
- types/foundry/client-esm/canvas/tokens/module.ts
- types/foundry/client-esm/canvas/tokens/ring-config.d.ts
- types/foundry/client/config.d.ts
The type additions are incomplete, and were originally added to observe the grid fit mode. That setting is no longer observed, but there's no real reason to omit the typings I did include.
> Scale up dynamic tokens in chat messages

- packs/feats/champion-dedication.json
- packs/feats/sentinel-dedication.json
As noted by @websterguy. This should resolve the issue.
> Update Champion and Sentinel dedication to account for armor expertise class feature

- packs/kingmaker-bestiary/black-tear-cutthroat.json
The actor only had the ranged version of the strike. I checked the stat block and they should have a melee version as well.
> Update Black Tear Cutthroat actor Dagger strikes

- packs/feat-effects/effect-unleash-psyche.json
and limit its damage bonus to a spontenous occult spellcasting entry, or psychic cantrips
> Move unleash psyche's toggle to spellcasting tab

- packs/ancestryfeatures/animal-attack.json
- packs/feats/tooth-and-claw.json
as discussed in the Discord, using `"fist": true` instead of creating a fist Strike from scratch suffices
> Prevent Awakened Animal's fist Strike from overriding other Strikes

- packs/spells/wild-winds-stance.json
remove wrong link in Wild Wind Stances (Kingmaker)
> Fix incorrect link in Wild Winds Stance

- src/module/actor/character/document.ts
- src/module/system/rolls.ts
The consumeAmmo logic wraps an existing caller supplied attack roll callback.  Unlike a RollParameter callback, which has only the Roll as an argument, an attack roll callback is a CheckRollCallback, which has four parameters.  The consumeAmmo wrapper would only pass along the first of these.
Since the wrapper doesn't care about any of the arguments, use the rest argument syntax to pass along whatever argument(s) the callback was called with.  This way the code can work with any callback.
The callback also can be async, so await it, otherwise it won't finish before the code in CheckPF2e.roll() that awaits the callback continues.
> Also await on user provided callbacks for weapons that consume ammo

- src/module/actor/modifiers.ts
- src/module/system/statistic/base.ts
Addresses https://github.com/foundryvtt/pf2e/issues/16405 but does not close it.
A modifier's enabled state persists in all clones of that modifiers even when retested. Changing this behavior by resetting enabled state when retesting is risky, however testing modifiers before applying stack resolution rules is much safer and fixes this and potentially other unreported issues. For example, if slugs collide now, the enabled one will always win out properly.
Could be worth waiting on if we're at the cusp of the release. This looks like an old bug.
> Avoid disabled modifiers suppressing enabled ones

- packs/feats/athletic-strategist.json
The skill actions are not checking for item roll options, so this predicate is never met. Alternatively, we could use a toggle in lieu of checking for what type of weapon is being used, if any. Closes #16405
~~This partially addresses #16405, but there seems to be a separate bug with FlatModifier which is wrongly suppressing the original attribute modifier, despite the predicate being false. Left more details on the discord.~~ Bug was fixed by #16415
> Remove weapon predicates from Athletic Strategist

- packs/feats/acrobatic-performer.json
The perform action demands a variant be used, and dance seemed like the closest one.
Closes #16487
> Add inline acrobatics action and circumstance bonus to Acrobatic Performer

- src/module/apps/sidebar/encounter-tracker.ts
This PR aims to improve performance when updating the encounter tracker. The current problem is that `refreshTargetDisplay` forces a style recalculation each time it is executed, which is at least once per combatant per turn or whenever the status effects for any combatants change.
The cause for this repeated recalculation is that the combatants title is updated in a loop in `activateListeners` (modify) to add the user targets indicator. In the same loop, `refreshTargetDisplay` is then called to modify the newly created target indicator element, which first has to be found in the dom for this combatant (query). This combination leads to forced style recalculations, which can be quite expensive.
In the above case, just the `activateListeners` phase took over 100ms to complete, in a very …
> Reduce layout thrashing in activateListeners phase of encounter tracker update

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/crafting.ts
- src/module/actor/character/crafting/index.ts
- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
- src/module/rules/helpers.ts
- src/module/rules/rule-element/crafting-entry.ts
This is a split of multiple refactors from an inprogress branch, in a more finalized state. To go into more detail, this is what changes:
* Scope several crafting functions in Character to actor.crafting.
* Lazily cache the list of known actor formulas instead of receiving each time 
* Add CraftingAbility#getSheetData() and pass that instead of CraftingAbility itself. Also remove the sheet data only formula getter. 
* Construct crafting abilities during data preparation instead of during sheet rendering. The sheet based functions that required the formulas to be preloaded have been converted to async.
* When updating the list of prepared formulas, updates all rule elements with the same selector instead of only the parent item. This makes it so we no longer need to pass the parent item, …
> Split certain crafting functions and defer use of async

- packs/feats/werecreature-dedication.json
@DocSchlock contributed this automation originally in the form of an effect (#14854). In order for it to work with the Change Shape refactor, I moved it to the Werecreature Dedication feat and modified predicates accordingly.
Closes #16497
> Move Werecreature Dedication automation from effect to feat

- packs/ancestryfeatures/horns-sarangay.json
- packs/classfeatures/animal-instinct.json
- packs/equipment-effects/effect-bestial-mutagen-greater.json
- packs/equipment-effects/effect-bestial-mutagen-lesser.json
- packs/equipment-effects/effect-bestial-mutagen-major.json
- packs/equipment-effects/effect-bestial-mutagen-moderate.json
- packs/equipment/berserkers-cloak-greater.json
- packs/equipment/berserkers-cloak.json
- packs/feat-effects/effect-kishin-rage.json
- packs/feats/crown-of-bone.json
- packs/feats/mutant-physique.json
- packs/feats/oni-weapon-familiarity.json
- packs/heritages/versatile-heritages/hungerseed.json
Closes #16479
Also move away from using Roll Options to tag RE-generated Strikes when needed, and instead use tag Item Alteration
> Restrict Mutant Physique's effets to Bestial Mutagen Strikes only

- packs/pathfinder-monster-core/banshee.json
Monster Core page 37. Doesn't say anything about a changed save, unchanged from Bestiary 1. Must have snuck in via copy&paste.
> Fix save type of Banshee's Wail

- packs/classfeatures/weapon-expertise.json
> Enable Martial Weapon expertise for Swashbuckler in Weapon Expertise class feature

- packs/feats/deadly-grace.json
- packs/feats/diamond-fists.json
Regarding priorities, I figured it makes more sense to push back the trait-adding Item Alterations, and keep the tagging Item Alterations at the default 120, otherwise it will not be there in time for other Item Alterations possibly adding the trait it's checking for, and incorrectly leaving the unarmed attack/weapon untagged. I have gone back and done the same thing for Deadly Grace.
Please let me know if I'm missing something there.
> Implement dice upgrade for Diamond Fists

- packs/feats/fortuitous-shift.json
Closes #16577
This is an error in the book, but seems clear enough that we can fix?
> Fix description of Fortuitous Shift

- src/module/encounter/combatant.ts
Closes #16101
Adding party to initiative bypasses the normal actor check, so I implemented a small actor trait check in the party swap method.
> Add check to Party swap method to avoid non-initiative actors

- packs/feat-effects/effect-divine-health.json
I'm not 100% sure about this one, because people in the champion's aura get that +1, but the champion himself gets +2.
> Fix divine health modifier

- packs/feat-effects/effect-divine-health.json
I commented on #16581, but I guess I should've closed it. This effect is meant to have only a +1, since it's the bonus that allies receive through the champion's aura. The champion's +2 is on the feat itself.
> Revert 'Fix divine health modifier'

- packs/spell-effects/spell-effect-enduring-might.json
Closes #11392
Increasing the duration slightly so the resistance doesn't instantly expire if used on the user's own turn. We already rely on manually removing the effect for things like Champion's Resistance, better to keep it functional imo.
> Increase duration of Enduring Might spell effect

- packs/feats/crossbow-crack-shot.json
also fix weapon group selectors. The AdjustModifier on the backstabber damage is not working due to some bug in retrieving the weapon damage dice, it seems. I'll try to confirm that, but that's unrelated to this particular fix.
Closes #14769 though the general limitation of AdjustModifier remains.
> Make Crossbow Crackshot's additional precision damage untyped and add increased backstabber damage

- src/module/actor/familiar/data.ts
- src/styles/actor/familiar/_index.scss
- static/templates/actors/familiar/sheet.hbs
Closes #16175
No toggle:
toggle:
> Add Toggle support to Familiars

- src/module/item/spellcasting-entry/trick.ts
Because the Trick Magic Item spell entry checks  `game.pf2e.settings.variants.pwol` to see if it should add the character's level, and `game.pf2e.settings.variants.pwol` is an object, it is always truthy and the level isn't added
> Fix untrained bonus in Trick Magic Item

- packs/feats/godless-healing.json
- packs/feats/tengu-weapon-familiarity.json
- packs/iconics/korakai-level-1.json
- packs/iconics/korakai-level-3.json
- packs/iconics/korakai-level-5.json
Priority on the ActiveEffectLike had to be lowered to before the MartialProficiency rule elements. It had the wrong slug on its predicate as well. Refreshed the Korakais' copy of the feat, as well as their focus spells since they still had the cursebound trait. Made sure to keep their sourceId.
Also pushed Godless Healing, which keeps nagging at me on extraction to strip that label.
> Fix warnings on Tengu Weapon Familiarity

- packs/spell-effects/spell-effect-charged-javelin-attacker.json
- packs/spell-effects/spell-effect-charged-javelin.json
- packs/spells/charged-javelin.json
`item:material:metal` is not an actual roll option, but it will show the bonus in the roll dialog for users to toggle on when targeting the creature with the effect
> Add spell effect for Charged Javelin

- src/module/apps/compendium-browser/index.ts
- static/lang/en.json
- static/templates/compendium-browser/settings/pack-settings.hbs
Closes #15555
Issue was the campaignFeature sources were getting permanently set to load = false.
I noticed there was no pack settings to toggle it, so I added it and it fixed the issue.
> Fix issue with permanently hidden Campaign Features in Comp Browser

- src/module/actor/base.ts
This PR aims to improve the performance of the actors `getRollOptions` function.
Performance is quite difficult to measure in the best of times, but from my profiling, this change alone means the function only takes about 60% the time to execute.
Absolute terms are even more complicated as they depend on even more variables, but in my test world this shaves off about 17ms when changing turns in the encounter tracker. This function is also a hot path when adding effects or manipulating actors in other ways. 
previous function:
with `Object.keys`
The reason `Object.keys` is faster in this case is due to the fact that no additional arrays have to be created for the [key, value] pair.
> Improve actor getRollOptions performance

- src/module/actor/familiar/sheet.ts
- src/module/actor/npc/sheet.ts
- src/module/actor/npc/types.ts
- src/module/actor/sheet/data-types.ts
- static/templates/actors/army/sheet.hbs
- static/templates/actors/familiar/sheet.hbs
- static/templates/actors/npc/partials/action.hbs
- static/templates/actors/npc/partials/attack.hbs
It entails a change to the view data to match character more closely, meaning it also required a refactor for all existing sheets. Posting abilities to chat and editing still works on npc, character, and familiar sheets. Vehicles remain broken for entirely unrelated reasons involving sheet handlers which I'll handle separately.
> Fix updating frequency of NPC abilities

- packs/other-effects/effect-aid.json
Aid is triggered by an attack roll or skill check. Also changed the value to a number.
> Apply aid bonus to attack rolls and skill checks only

- packs/feat-effects/effect-starlit-transformation.json
The action specifies a bonus to damage rolls, not attack rolls
> Remove attack bonus from Starlit Transformation effect

- packs/pathfinder-monster-core/frost-giant.json
Per Monster Core page 166, Frost Giants have Reactive Strike.
> Add Reactive Strike to Frost Giant from Monster Core

- packs/classfeatures/bloodline-aberrant.json
- packs/classfeatures/bloodline-angelic.json
- packs/classfeatures/bloodline-demonic.json
- packs/classfeatures/bloodline-diabolic.json
- packs/classfeatures/bloodline-draconic.json
- packs/classfeatures/bloodline-elemental.json
- packs/classfeatures/bloodline-fey.json
- packs/classfeatures/bloodline-genie.json
- packs/classfeatures/bloodline-hag.json
- packs/classfeatures/bloodline-harrow.json
- packs/classfeatures/bloodline-imperial.json
- packs/classfeatures/bloodline-nymph.json
- packs/classfeatures/bloodline-phoenix.json
- packs/classfeatures/bloodline-psychopomp.json
- packs/classfeatures/bloodline-shadow.json
- packs/classfeatures/bloodline-undead.json
- packs/classfeatures/bloodline-wyrmblessed.json
- packs/feats/blood-sovereignty.json
- packs/feats/crossblooded-evolution.json
- packs/feats/explosion-of-power.json
- packs/feats/propelling-sorcery.json
- packs/feats/reflect-harm.json
- packs/feats/terraforming-trickery.json
Added dividers, used Blood Magic as a label and the specific Blood Magic's name as the title for consistency
also
- Pushed back priorities of blood magic feats' description alterations to ensure they're after spells are tagged as blood magic
- Remove unnecessary tag from Crossblooded Evolution, and replace parent tag predicate on bloodlines with granter slug one.
> Improve Blood Magic description alteration's formatting

- src/module/actor/roll-context/base.ts
I am not certain why we are typechecking distance, but I'm not about to change that.
> Always include origin and target distance roll option

- src/scripts/config/damage.ts
- src/scripts/config/index.ts
For ChoiceSets that let you pick any energy damage, so they can be shortened to `config: energyDamageTypes`. Physical is just added for symmetry.
> Add energy and physical damage types to pf2econfig

- src/module/system/damage/formula.ts
Closes https://github.com/foundryvtt/pf2e/issues/16669.
It'll still show as enabled in the damage dialog, but it won't affect the outcome. I can't think of a good solution for that right now other than making a redundant check in the dialog itself for "invalid" modifiers.
I'll try a refactor that filters enabled much much sooner next cycle.
> Only allow bonuses to apply to enabled instances

- packs/feats/monastic-weaponry.json
Add critical specialization to monk weapons if you have expert strikes, addresses #16687
> Update Monastic Weaponry by adding critical specialization to monk weapons

- packs/classfeatures/deity-champion.json
- Remove `class:champion` from the holy/unholy strike predicates
> Brush up Deity (Champion) class feature

- packs/feats/scouts-charge.json
Per the feat's description, this variant of Feint uses stealth
> Update Scout's Charge to use variant Feint action

- src/module/item/base/sheet/sheet.ts
The ?? null changed to || null which broke 0, but ?? isn't correct for NaN regardless.
> Fix regression with editing the first rule element

- packs/equipment/backfire-mantle-greater.json
- packs/equipment/backfire-mantle.json
It looks like splash resistance is not currently supported, even as a custom resistance.
> Automate Backfire Mantle bonus to saves

- packs/shadows-at-sundown-bestiary/paradox-engine.json
* Swapped the DC and skill arguments so their order is correct
* Gave it the same name as the disable Society check because as written either Thassilon Lore or Society can be used to "Work out the puzzle"
> Fix inline checks for Paradox Engine

- build/lib/compendium-pack.ts
- build/lib/extractor.ts
This doesn't fix the items that are missing a compendium source, not convert the ones that are using flags to use compendium source.
> Conserve compendium source for embedded items when extracting

- build/lib/compendium-pack.ts
- build/run-migration.ts
- packs/curtain-call-bestiary/delaraius-solzakarr.json
Fixes slug being set for embedded migrated items, as well converting source ids on extract when source ids as a whole are not converted.
> Fix some extract and migrate regressions and delaraius's wand 

- packs/equipment/elixir-of-life-lesser.json
- packs/equipment/elixir-of-life-major.json
- packs/equipment/elixir-of-life-minor.json
- packs/equipment/elixir-of-life-moderate.json
- packs/equipment/elixir-of-life-true.json
Updated the descriptions of the various Elixir of Life descriptions so they are more uniform - @Damage[(10d6+27)[healing]]{10d6+27 Hit Points} => @Damage[(10d6+27)[healing]] Hit Points - this matches healing potions formatting.
> Update Elixir of Life descriptions

- src/module/rules/rule-element/item-alteration/alteration.ts
Closes https://github.com/foundryvtt/pf2e/issues/16730
> Fix ItemAlteration removing the wrong trait if it does not exist

- src/module/actor/initiative.ts
- src/module/apps/sidebar/chat-log.ts
- src/module/encounter/document.ts
This allows you to set the initiative statistic for a combatant when setting there initiative. By default it uses whatever statistic their initiative is set on the actor and defaults to perception. This is a problem when setting the initiative via a chat message because it doesn't set the statistic to whatever they actually rolled, so if they rolled stealth and set that as their initiative it sets their combatant's initiative statistic to whatever is set on the actor. The same applies to `ActorInitiative` where it doesn't base along the base statistic so it ends up doing the same default.
Lastly there is a fail safe built in that requires the string being passed in to be a core skill or perception, if it's not it defaults to the old behaviour.
Fixes #16821
> Identify the correct statistic when using a pre-existing roll for initiative

- packs/adventure-specific-actions/holy-light.json
- packs/bestiary-family-ability-glossary/lich-steal-soul.json
- packs/blood-lords-bestiary/unstable-fiendflame-cage.json
They caused warnings when the sheets were opened.
Also fix damage for Unstable Fiendflame Cage's routine.
> Remove some invalid traits

- packs/spell-effects/spell-effect-envenom-companion.json
- static/lang/re-en.json
Text from spell
```
A creature that is damaged by this poison must attempt a Fortitude save
```
Old & New message
> Add Note for Envenom Companion

- packs/bestiary-effects/effect-filth-wave.json
PCs can reduce the penalty by 5 ft. for each action they spend. This is to help with that.
> Add labeled badge to Sewer Ooze's Filth Wave effect

- packs/feat-effects/effect-curse-of-ancestral-meddling.json
Fixed the `selector` key of one `AdjustModifier` rule element. 
`"selector":["skill-check","perception"` became `this.selectors = "skill-check, perception"`.
> Fix selectors of Curse of Ancestral Meddling

- packs/spell-effects/spell-effect-fire-shield.json
- Change the RE to once again use the toggle as "Fake Shields" do not read/interpret incoming damage
> Restore Fire Shield's Rules Elements to function properly

- src/module/actor/character/sheet.ts
- src/module/actor/familiar/sheet.ts
- src/module/actor/npc/sheet.ts
- src/module/actor/sheet/base.ts
- src/module/actor/sheet/data-types.ts
- src/module/actor/sheet/helpers.ts
- src/module/actor/vehicle/sheet.ts
- src/module/chat-message/helpers.ts
- src/scripts/macros/hotbar.ts
- static/templates/actors/npc/partials/action.hbs
- static/templates/actors/partials/action.hbs
This adds a use button to every action with a frequency, though since collapsed preview messages are expressly codified as "self-effect" chat messages even down to the message type, these messages do not show a collapsed preview at this time. It also does not prevent using the ability once there are no uses remaining, though I will definitely do that once we have regeneration for per round and per turn abilities.
> Reduce remaining action uses when clicking the use button

- src/module/actor/character/document.ts
This is already handled by `CharacterPF2e#prepareMartialProficiencies`.
Closes #16510, supersedes #16879
> Remove duplicate "same-as" processing of linked martial proficiencies

- packs/feats/monstrous-peacemaker.json
Before it was just default on for all rolls from the skills tab, since they don't get target info.
> Brush up rule elements on Monstrous Peacemaker

- src/module/actor/base.ts
- src/module/actor/spellcasting.ts
- src/module/actor/types.ts
- src/module/encounter/combatant.ts
- src/module/encounter/document.ts
- src/scripts/macros/rest-for-the-night.ts
There is a very strange bug where the self effect image disappears until next re-render if the ability got updated. It seems to be an issue with the fallback uuid sync fallback, so I'll leave that to shark to figure out as he's more familiar with that side of things.
Merging this or the special resource branch will necessitate updating the other. That's fine by me though.
> Recharge turn and round abilities as the encounter changes turns

- src/module/actor/base.ts
- src/module/actor/character/data.ts
- src/module/actor/character/sheet.ts
- src/module/actor/creature/data.ts
- src/module/actor/creature/document.ts
- src/module/actor/creature/sheet.ts
- src/module/actor/helpers.ts
- src/module/actor/sheet/base.ts
- src/module/actor/spellcasting.ts
- src/module/actor/types.ts
- src/module/rules/index.ts
- src/module/rules/rule-element/special-resource.ts
- src/module/rules/synthetics.ts
- src/module/scene/token-document/document.ts
- src/scripts/macros/rest-for-the-night.ts
- src/styles/actor/character/_sidebar.scss
- static/lang/en.json
- static/lang/re-en.json
- static/templates/actors/character/partials/header.hbs
- static/templates/actors/character/partials/sidebar.hbs
- static/templates/actors/character/tabs/spellcasting.hbs
While it is functional, it is still a work in progress, and will need to be run through a bit of rigor to be as good as it can be. The physical item binding, while *generally* functional, is untested and will be completed during the crafting rework. Token bar updates work though, as does updating the max via AELike rule elements.
These bits of functionality are missing or spotty:
1) Slugs are hyphen cased, and included in system.resources as is. This becomes awkward when you have `system.resources.heroPoints` and `system.resources.vitality-network`. We could make them bactrian in system.resources and kebab in synthetics.resources, which is a bit weird to me, but perhaps its fine to others?
2) They aren't shown for npcs yet. I'd like to get them shiny in character first.
3) It assumes full …
> Initial implementation of SpecialResource rule element

- src/global.ts
- src/module/actor/army/document.ts
- src/module/actor/character/document.ts
- src/module/actor/character/feats/collection.ts
- src/module/actor/character/feats/group.ts
- src/module/actor/character/feats/index.ts
- src/module/actor/character/feats/types.ts
- src/module/actor/character/sheet.ts
- src/module/actor/party/kingdom/model.ts
- src/module/actor/party/kingdom/sheet.ts
- src/module/item/campaign-feature/document.ts
- src/module/item/class/document.ts
- src/module/item/feat/document.ts
There is only one actual change here. FeatGroupOptions split into FeatGroupData and options. Level is used by kingmaker to pass in the level of the kingdom instead of the actor's level, but it was not part of the actual structural metadata. That is not the sort of data we'd want to store in the campaign feat settings when we finally make a UI for it, so I split it off.
> Organize character feat collection classes and interfaces

- src/module/system/text-editor.ts
This ensure that the DC is displayed correctly in `[[\act ...]]` blocks so that the DC isn't shown to players if the metagame option is not ticked.
Fixes #16932
> In `/act` ensure DC has correct metagame visibility

- packs/fists-of-the-ruby-phoenix-bestiary/ghost-monk.json
- packs/fists-of-the-ruby-phoenix-bestiary/ji-yook-level-9.json
- packs/fists-of-the-ruby-phoenix-bestiary/kannitri.json
- packs/fists-of-the-ruby-phoenix-bestiary/old-man-statue.json
- packs/fists-of-the-ruby-phoenix-bestiary/takatorra-level-9.json
- packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-9.json
Some Chapter 1, Book 1 NPCs were missing correct vision types from the book. The higher level versions are already correct.
> Fix vision on some FOTRP NPCs

- packs/classfeatures/debilitating-strike.json
Predicates are same as for Note
> Improve automation of bloody debilitation

- packs/equipment-effects/effect-antidote.json
- packs/equipment-effects/effect-antiplague.json
- packs/equipment-effects/effect-blood-booster.json
- packs/equipment-effects/effect-bombers-eye-elixir.json
- packs/equipment-effects/effect-elixir-of-life.json
- packs/equipment-effects/effect-healers-gel.json
- packs/equipment-effects/effect-life-shot.json
- packs/equipment-effects/effect-mudrock-snare.json
- packs/equipment/elixir-of-life-moderate.json
- static/lang/re-en.json
This approach would allow us to skip having to add all these names to the localization file. The changes aren't live yet, so should be fine to remove too.
I'm not 100% sold on `elixir-of-life:elixir-of-life-variety` as a roll option, but I can't think of any alternatives.
> Use UUID-based Choice Set for condensed equipment effects

- packs/paizo-pregens/kangir.json
- packs/paizo-pregens/yacob.json
- packs/paizo-pregens/zeah.json
This is meant to fix some discrepancies between the Foundry pregens and the PDF:
https://paizo.s3.us-west-2.amazonaws.com/PZOPF1004E+Mark+of+the+Mantis+Pregens.pdf
- Kangir's armor is supposed to have a +1
- Yacob has 100 ft of rope, rather than just 50
- Zeah is expert in Society and Stealth (Foundry pregen shows only trained)
- Zeah also has a Sunrod, like Yacob
> Fix Mark of the Mantis Pregens

- src/module/rules/rule-element/choice-set/rule-element.ts
This would be useful for exemplar weapon ikons, which let you pick weapons with specific damage types
> Add damage type as index field for item-filter choice sets

- src/module/actor/helpers.ts
- src/module/canvas/ruler.ts
- src/module/scene/document.ts
- src/module/scene/token-document/document.ts
- src/scripts/hooks/canvas-ready.ts
- src/scripts/hooks/ready.ts
Region behaviors (environment and environmentFeature) were always being processed, even when the behavior was not active.
This PR updates the filter searches to only consider region behaviors which are active (`behavior.active`).
> Ignore disabled region behaviors when determining effect on actors

- src/module/item/weapon/trait-toggles.ts
Closes https://github.com/foundryvtt/pf2e/issues/16982.
I was tempted on leveraging createBatchRuleElementUpdate() to tag every strike with the same slug across every item but I stopped myself. It might create a bit more stability to trait toggle behavior but I doubt it'll be necessary.
> Fix trait toggles on strikes overriden within the same item

- packs/feat-effects/stance-twisting-petal-stance.json
Updated the description, set the strike RE  `replaceAll` to false, and changed the perception bonus to proc on perception-dc.
Closes #17007
> Brush up `Twisting Petal Stance` effect(stance)

- src/module/actor/data/iwr.ts
Double Vs check was being treated as an "and" instead of an "or". Change the predicate test into "or".
> fix "double vs" resistance requiring all entries to be true

- src/styles/_fonts.scss
Throwing darts at the Firefox bug
> Add redundant registration of action-glyph font

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
When a `/act` with a secret roll is made, the display would include a space (or dot) before the action link, and would display "()" at the end of the string to players.
> Improve display of /act in chat for secret rolls

- packs/equipment-effects/effect-diplomats-badge.json
Unconditional +1 from the item was being hidden by the conditional +2 from the activated effect due to duplicate slug. Giving effect unique label based on the activation action name so +1 can still apply.
> fix issue with Diplomat's Badge bonus being hidden while having Effect

- packs/feats/energized-spark.json
Made the suboptions based on the damage instead of traits since I don't think we can automate adding the traits right now, due to not having context on whether a feat is "damaging". Plus, it means we only need one Damage Alteration.
Weapon dice and modifiers pending system enhancements.
> Automate Energized Spark's inline damage alteration

- src/global.ts
- src/module/actor/character/data.ts
- src/module/actor/character/document.ts
- src/module/actor/character/feats/collection.ts
- src/module/actor/character/feats/group.ts
- src/module/actor/character/feats/types.ts
- src/module/actor/character/sheet.ts
- src/module/actor/party/kingdom/model.ts
- src/module/item/class/document.ts
- src/module/system/settings/menu.ts
- src/module/system/settings/variant-rules.ts
- src/scripts/set-game-pf2e.ts
- src/styles/actor/character/_feats.scss
- static/lang/en.json
- static/templates/actors/character/partials/feat-slot.hbs
- static/templates/actors/character/tabs/feats.hbs
- static/templates/system/settings/variant-rules.hbs
This includes the variant introduced in a separate pdf. I put them in homebrew settings under campaign, but I'm almost tempted to put it under variant rules instead. Not sure.
This PR introduces the ability for a group to have a separate configurable limit in the feat header. So far the only other official use I can think of where it'd be handy is strength of thousands.
> Add support for mythic feat slots

- packs/classfeatures/bands-of-imprisonment.json
- packs/classfeatures/fetching-bangles.json
- packs/classfeatures/horn-of-plenty.json
- packs/classfeatures/pelt-of-the-beast.json
- packs/classfeatures/skybearers-belt.json
- packs/classfeatures/thousand-league-sandals.json
- packs/classfeatures/victors-wreath.json
also prevent premade physical worn ikons from having the corresponding class feature redundantly embedded
> Fix Embed UUID on Thousand League Sandals

- src/module/actor/creature/document.ts
- src/module/actor/creature/sheet.ts
- src/module/rules/rule-element/special-resource.ts
I'm unsure about this and am only trying it out. It trades our current set of problems for a new set of problems.
One annoyance is that a feat that consumes a resource will use kebab case, and then will check using dromedary. So for example, if a feat consumes hero points, the slug will be `hero-points` and it will check `system.resources.heroPoints`.
> Internally represent special resources using dromedary

- packs/classfeatures/gleaming-blade.json
- packs/classfeatures/hands-of-the-wildling.json
- packs/classfeatures/titans-breaker.json
- packs/feats/vow-of-mortal-defiance.json
- static/lang/re-en.json
Instead of having the user choose a specific unarmed Strike, they can use the toggle to say they're using whatever unarmed attack qualifies as an ikon.
Also closes #17100 while I'm at it
> Use toggle to tag unarmed attack as a weapon ikon

- packs/actions/fracture-mountains.json
The action makes the modifier go from its original 2 per weapon damage die to 4 per weapon damage die
> Fix Fracture Mountain's immanence damage adjustment

- static/lang/en.json
This attempts to resolve make alternate mythic progression easier to understand, and also hopefully proficiency without level's modifier adjustments.
> Make mythic variant rule hint more descriptive

- packs/feats/energized-spark.json
Forgot this, which made the inactive roll options throw warnings
> Make Energized Spark's suboptions mergeable

- static/templates/actors/character/tabs/pfs.hbs
Change template file to look at `document.pfsBoons` instead of `actor.pfsBoons`, matching the way divine intercessions are accessed shows the boons
> fix issue with PFS boons not displaying on character sheet

- packs/feats/quick-climb.json
- packs/feats/quick-swim.json
- static/lang/re-en.json
Using brackets for the value made it so the armor penalties applied as if the character didn't meet the strength requirement. Perhaps the bracket resolving before that is taken into account? Either way, predicating the BaseSpeed rule element instead resolves the issue and is the better way to do it.
Closes #17199
> Localize Quick Climb and Quick Swim notes and update the latter's value

- packs/classfeatures/barrows-edge.json
- packs/classfeatures/the-distant-grasp.json
- packs/classfeatures/the-oscillating-wave.json
- packs/classfeatures/the-silent-whisper.json
- packs/classfeatures/the-tangible-dream.json
- packs/classfeatures/the-unbound-step.json
and add `hideIfDisabled` to DamageDice rule elements to clean up the dialog
> Update conscious mind Damage Dice overrides to Damage Alteration

- packs/feat-effects/effect-unleash-psyche.json
Rather than cantrips with the psychic trait, which missed non-psychic-exclusive cantrips like Telekinetic Projectile
Closes #17203
> Predicate Unleash Psyche's bonus on `psi-cantrip` tag

- packs/rollable-tables/1st-level-consumables.json
- packs/rollable-tables/1st-level-permanent-items.json
Update 1st-Level Consumable Items and 1st-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
* Common = 6
* Uncommon = 3
* Rare = 1
> Update 1st-level rollable tables

- packs/rollable-tables/2nd-level-consumables.json
- packs/rollable-tables/2nd-level-permanent-items.json
Update 2nd-Level Consumable Items and 2nd-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
* Common = 6
* Uncommon = 3
* Rare = 1
> Update 2nd-level rollable tables

- packs/rollable-tables/3rd-level-consumables.json
- packs/rollable-tables/3rd-level-permanent-items.json
Update 3rd-Level Consumable Items and 3rd-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
* Common = 6
* Uncommon = 3
* Rare = 1
> Update 3rd-level rollable tables

- packs/feat-effects/effect-game-hunter-critical-failure.json
- packs/feat-effects/effect-game-hunter-failure.json
- packs/feat-effects/effect-game-hunter-target.json
- packs/feats/game-hunter-dedication.json
- static/lang/re-en.json
```When you succeed at a Strike against your hunted prey while it's Off-Guard, it must attempt a Fortitude save against your class DC. On a failure, the prey's Speeds are each reduced by 10 feet for 1 round; on a critical failure, the duration of this effect is 1 minute. The prey is then temporarily immune to this effect for 10 minutes.```
> Add Game Hunter (Target) effect

- packs/rollable-tables/4th-level-consumables-items.json
- packs/rollable-tables/4th-level-permanent-items.json
Update 4th-Level Consumable Items and 4th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
* Common = 6
* Uncommon = 3
* Rare = 1
> Update 4th-level rollable tables

- packs/rollable-tables/6th-level-consumables-items.json
- packs/rollable-tables/6th-level-permanent-items.json
Update 6th-Level Consumable Items and 6th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
* Common = 6
* Uncommon = 3
* Rare = 1
> Update 6th-level rollable tables

- packs/pathfinder-monster-core/animated-armor.json
"Animated Armor" does not have any immunities listed in it's "Monster Core" JSON file.
I added the immunities according to the "Monster Core".
> Fix immunities of Animated Armor

- packs/rollable-tables/7th-level-consumables-items.json
- packs/rollable-tables/7th-level-permanent-items.json
Update 7th-Level Consumable Items and 7th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
- Common = 6
- Uncommon = 3
- Rare = 1
> Update 7th-level rollable tables

- packs/backgrounds/farmhand.json
- packs/spell-effects/spell-effect-enlarge.json
Also clean up the Enlarge spell effect
Closes #17212
> Fix Assurance grant of Farmhand background

- packs/actions/mark-for-death.json
- packs/classfeatures/avenger.json
- packs/classfeatures/ruffian.json
- packs/classfeatures/sneak-attack.json
- packs/feats/shadow-sneak-attack.json
- packs/feats/sly-striker.json
Sneak Attack now gives its default weapons the `sneak-attack` tag and predicates its damage on that tag. Avenger and Ruffian tag their own weapons, thus qualifying them for Sneak Attack. Switched to tag-based predicate on Sly Striker as well.
Closes #17160
> Refactor Sneak Attack to be tag-based and add missing Avenger features

- packs/howl-of-the-wild-bestiary/mocking-chorus.json
- packs/howl-of-the-wild-bestiary/prismhydra.json
- packs/howl-of-the-wild-bestiary/sunscale-serpent.json
- packs/howl-of-the-wild-bestiary/tyrafdir.json
- packs/howl-of-the-wild-bestiary/wereshark.json
- packs/quest-for-the-frozen-flame-bestiary/desiak.json
Some NPCs had Reactive Strike/AoO abilities that used the descriptions of PC's RS/AoO.
Replaced them with the ability from Bestiary Glossary.
> Replace some NPCs Reactive Strike action with the one from the Bestiary Ability Glossary

- src/module/actor/character/document.ts
- src/module/actor/character/feats/collection.ts
The rerolll prompt checks if you have hero points before showing the option. This removes hero points from the pc. Even if the value is still in the data, the clamp will set it to zero during data preparation.
> Fix reroll using a hero point erroneously displaying for a mythic character

- build/lib/extractor.ts
- packs/iconics/nahoa-level-1.json
- packs/iconics/nahoa-level-3.json
- packs/iconics/nahoa-level-5.json
- packs/iconics/samo-level-1.json
- packs/iconics/samo-level-3.json
- packs/iconics/samo-level-5.json
We might need @SpartanCPA to make fallback tokens but they shouldn't look weird on the canvas anymore.
> Preserve token ring on extraction and fix Nahoa and Samo tokens

- src/module/canvas/token/aura/util.ts
Instead of testing each aura square against each source point of the aura, compute the full clockwise sweep polygons for the collisionType to reduce edge intersection tests in core foundry methods. 
Rendering the full polygon is a little wasteful for very small aura shapes, but greatly improves performance for large auras.
In my testing on a scene with 1099 wall segments, only auras with a radius of 15ft or smaller were faster to render with the current method. I'd argue though that these aura sizes could already be rendered "fast enough".  
As for performance numbers, on my system the aura drawing times improved in the following ways in the above mentioned test scene:
90ft: 195ms -> 21ms
60ft: 78ms -> 16ms
30ft: 18ms -> 12ms
15ft: 6ms -> 12ms
I know the system does not specifically cater …
> Improve aura rendering performance

- packs/feats/advanced-alchemy.json
- packs/feats/advanced-herbalism.json
- packs/feats/cauldron.json
- packs/feats/double-double.json
- packs/feats/herbalist-dedication.json
- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/sheet.ts
- src/module/item/feat/document.ts
- src/module/rules/rule-element/crafting-ability.ts
- src/module/rules/rule-element/special-resource.ts
- static/lang/en.json
- static/lang/re-en.json
- static/templates/actors/character/tabs/crafting.hbs
The following occured refactor wise:
1) Crafting Ability now injects initial data during the active effects phase, so that AELike no longer needs to target the beforeDerived phase.
2) Crafting abilities with the same slug merge. The AELikes I added could have more CraftingAbility RE's, but I don't know if we want to incentivize that for abilities without craftable items.
3) Prepared items now support batch sizes. Each prepared item crafts the batch size in the craftable entry, and falls back to the batch size of the entire ability.
4) Items now have a timesTaken getter. The current implementation is inefficient if the getter gets used often. I'll refactor if we start using it a bunch.
This does not update every source of advanced alchemy. I am not touching alchemist class personally until …
> Implement remaster styled advanced alchemy and Double, Double

- packs/feats/armor-proficiency.json
- packs/feats/champion-dedication.json
Closes #17285
No need to check if Heavy Armor is untrained, as there is no higher tier of armor than itself to accidentally grant. This way the Choice Set isn't skipped if a character is already trained in Heavy Armor, which can happen in cases where the feat is automatically granted as seen in the linked issue.
Also did the same for Champion Dedication and fixed heavy armor being pre-selected for it.
> Adjust Armor Proficiency Choice Set to not be ignored

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/crafting.ts
- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
- src/module/actor/creature/document.ts
- src/module/rules/rule-element/crafting-ability.ts
- static/lang/en.json
- static/templates/actors/character/tabs/crafting.hbs
There is some temporary hackery for rerouting the infused reagents resource. We can kill that later once the data is migrated.
> Add resource consumption support to daily prep crafting

- packs/rollable-tables/8th-level-consumables-items.json
- packs/rollable-tables/8th-level-permanent-items.json
Update 8th-Level Consumable Items and 8th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
- Common = 6
- Uncommon = 3
- Rare = 1
> Update 8th-level rollable tables

- packs/rollable-tables/9th-level-consumables-items.json
- packs/rollable-tables/9th-level-permanent-items.json
Update 9th-Level Consumable Items and 9th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
- Common = 6
- Uncommon = 3
- Rare = 1
> Update 9th-level rollable tables

- packs/rollable-tables/10th-level-consumables-items.json
- packs/rollable-tables/10th-level-permanent-items.json
Update 10th-Level Consumable Items and 10th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
- Common = 6
- Uncommon = 3
- Rare = 1
> Update 10th-level rollable tables

- packs/rollable-tables/11th-level-consumables-items.json
- packs/rollable-tables/11th-level-permanent-items.json
Update 11th-Level Consumable Items and 11th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 11th-level rollable tables

- packs/rollable-tables/12th-level-consumables-items.json
- packs/rollable-tables/12th-level-permanent-items.json
Update 12th-Level Consumable Items and 12th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 12th-level rollable tables

- packs/rollable-tables/13th-level-consumables-items.json
- packs/rollable-tables/13th-level-permanent-items.json
Update 13th-Level Consumable Items and 13th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 13th-level rollable tables

- packs/rollable-tables/14th-level-consumables-items.json
- packs/rollable-tables/14th-level-permanent-items.json
Update 14th-Level Consumable Items and 14th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 14th-level rollable tables

- packs/rollable-tables/15th-level-consumables-items.json
- packs/rollable-tables/15th-level-permanent-items.json
Update 15th-Level Consumable Items and 15th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 15th-level rollable tables

- packs/rollable-tables/16th-level-consumables-items.json
- packs/rollable-tables/16th-level-permanent-items.json
Update 16th-Level Consumable Items and 16th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 16th-level rollable tables

- packs/rollable-tables/17th-level-consumables-items.json
- packs/rollable-tables/17th-level-permanent-items.json
Update 17th-Level Consumable Items and 17th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 17th-level rollable tables

- packs/rollable-tables/18th-level-consumables.json
- packs/rollable-tables/18th-level-permanent-items.json
Update 18th-Level Consumable Items and 18th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 18th-level rollable tables

- packs/rollable-tables/19th-level-consumables-items.json
- packs/rollable-tables/19th-level-permanent-items.json
Update 19th-Level Consumable Items and 19th-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 19th-level rollable tables

- packs/rollable-tables/20th-level-consumable-items.json
- packs/rollable-tables/20th-level-permanent-items.json
Update 20-Level Consumable Items and 20-Level Permanent Items tables with remaster changes, consolidating the treasure tables from the GM Core and Player Core 2 books, preserving the item order found in those tables. Weight is based on rarity:
Common = 6
Uncommon = 3
Rare = 1
> Update 20-level rollable tables

- packs/equipment/composer-staff-greater.json
> Fix greater composer staff item bonus to performance

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/sheet.ts
- src/module/rules/rule-element/crafting-ability.ts
While there is a specific exclusion for snares, this isn't a change in functionality. Snares aren't really a thing you have in your inventory in any sort of complete form.
This bug has likely existed for years.
> Create item when using the craft item button on a prepared entry

- src/module/actor/character/crafting/crafting.ts
- static/lang/en.json
Fixes special resource items being deleted by daily crafting, brings back the message complete notification, and does not craft items that are set to expended.
These are either irrelevant or too inconsequential for the changelog
> Fix regressions and other issues in daily crafting

- src/module/actor/base.ts
- src/module/rules/rule-element/special-resource.ts
The level overrides are applied when first creating the item and when resting for the night
> Add level override support to special resource

- packs/spells/awaken-entropy.json
Added a vanilla variant for the void damage in addition to the force damage variant.
Closes #17441
> Update Awaken Entropy spell variants

- src/module/rules/rule-element/battle-form/rule-element.ts
At the moment, the property BattleForm: true in Strike REs has no effect on BattleForm REs. By adding the condition to the filter, individual Strike REs can also be used in BattleForms, instead of the "all or nothing" of ownUnarmed.
> Include Strike REs with battleForm: true to battle forms

- src/module/data.ts
This is the only instance where it's importing something from the Foundry types using a relative path, every where else it's import via `types/foundry/*`. Doesn't really change much but it was bugging me since I had to write a special rule for this one instance.
> Remove relative path to Foundry types

- packs/spell-effects/spell-effect-blink-charge.json
- packs/spells/blink-charge.json
- static/lang/re-en.json
Not completely on board with the Notes as they'd be missing spell context, but maybe it's an acceptable level of inaccuracy.
> Add spell effect for Blink Charge

- packs/iconics/ezren-level-1.json
- packs/iconics/ezren-level-3.json
- packs/iconics/ezren-level-5.json
- packs/iconics/lem-level-1.json
- packs/iconics/lem-level-3.json
- packs/iconics/lem-level-5.json
- packs/iconics/lini-level-3.json
- packs/iconics/lini-level-5.json
- packs/iconics/seelah-level-1.json
- packs/iconics/seoni-level-1.json
- packs/iconics/seoni-level-3.json
- packs/iconics/seoni-level-5.json
Note - Seoni still has Bespell Weapon; Bespell Strikes replaced that feat. I replaced it here but if you want to keep Bespell Weapon until Paizo issues a correction, let me know.
> Refresh Spellshape feats and Class Features for PC1/PC2 spellcaster iconics

- packs/heritages/versatile-heritages/aiuvarin.json
- packs/heritages/versatile-heritages/dromaar.json
As of Player Core, these are versatile heritages available to any ancestry (although most of them are human lorewise!)
> Update Aiuvarin and Droomar to be versatile heritages

- src/module/actor/character/sheet.ts
- src/module/actor/character/tab-manager.ts
- src/module/actor/hazard/sheet.ts
- src/module/actor/npc/sheet.ts
- src/module/actor/party/kingdom/sheet.ts
- src/module/actor/party/sheet.ts
- src/module/actor/sheet/base.ts
- src/module/actor/sheet/popups/iwr-editor.ts
- src/module/apps/compendium-browser/index.ts
- src/module/apps/pick-a-thing-prompt.ts
- src/module/apps/sidebar/chat-log.ts
- src/module/apps/sidebar/encounter-tracker.ts
- src/module/item/base/sheet/rule-element-form/actor-traits.ts
- src/module/item/base/sheet/rule-element-form/aura.ts
- src/module/item/base/sheet/rule-element-form/base.ts
- src/module/item/base/sheet/rule-element-form/fast-healing.ts
- src/module/item/base/sheet/rule-element-form/roll-note.ts
- src/module/item/base/sheet/sheet.ts
- src/module/item/campaign-feature/sheet.ts
- src/module/item/deity/sheet.ts
- src/module/item/feat/sheet.ts
- src/module/item/spell/sheet.ts
- src/module/scene/sheet.ts
- src/module/system/settings/homebrew/languages.ts
- src/module/system/settings/homebrew/menu.ts
- src/scripts/macros/check-prompt/prompt.ts
This PR fixes memory leaks in character/npc/hazard/party/kingdom/item sheets and various other places.
Any application currently using `Sortable`, `tooltipster` or `Tagify` is currently leaking memory (some references + the entire detached application dom tree) because these utilities register global event handlers or other global references that survive the application elements being detached from the DOM.
The solution to this to use the respective `destroy` methods these libraries provide. Either `.destroy()` on the `Sortable` or `Tagify` instances or `$(element).tooltipster('destroy')` for tooltipster.
This is done by keeping references to the active instances and destroying and nulling them when the application is closed, new event handlers are registered or rule element forms are not …
> fix memory leaks due to retained tagify, sortable or tooltipster instances

- build/uuid-redirects.json
Geist in Seven Dooms for Sandpoint does not need a redirect to Monster Core.  These are different actors.
> Remove extraneous UUID redirect for Adventure actor

- packs/other-effects/effect-ancestral-might.json
- packs/other-effects/effect-aura-of-protection.json
- packs/other-effects/effect-called-foe.json
- packs/other-effects/effect-catch-your-breath.json
- packs/other-effects/effect-class-might.json
- packs/other-effects/effect-critical-moment.json
- packs/other-effects/effect-daring-attempt.json
- packs/other-effects/effect-desperate-swing.json
- packs/other-effects/effect-endure-the-onslaught.json
- packs/other-effects/effect-fluid-motion.json
- packs/other-effects/effect-impossible-shot.json
- packs/other-effects/effect-rage-and-fury.json
- packs/other-effects/effect-spark-of-courage.json
- packs/other-effects/effect-strike-true.json
- static/lang/re-en.json
You choose among any of the possible key attributes for your class, so arbitrary choice is the best we can do.
Also clean up all the other Hero Point Deck effects.
> Allow Class Might effect to select any attribute

- packs/actions/quick-tempered.json
- packs/feat-effects/effect-rage-temporary-hit-points-immunity.json
The description looked real weird (see below). The feat has both a self-applied effect and a roll Note on initiative. This keeps both implementations happy.
> Move Quick-Tempered effects to its Note

- packs/feats/blast-resistance.json
- packs/feats/tide-hardened.json
- static/lang/re-en.json
It used to be the same as Undine's Tide Hardened.
Added both to re-en.json
Also, I'm not sure that this Blast Resistance RE even works properly. Is there anything that even uses `condition:deafened` as a roll option? Maybe it's better to remove this part of the predicate, so that the note still pops up at times?
> Replace Blast Resistance Note RE with DoS adjustment, Remove Tide Hardened Note RE

- packs/equipment/greatpick.json
Greatpick price was incorrectly listed as 2 gp instead of 1 gp.
> Correct Greatpick price

- packs/equipment-effects/effect-eye-of-the-unseen-greater.json
- packs/equipment-effects/effect-eye-of-the-unseen.json
- packs/equipment/eye-of-the-unseen-greater.json
- packs/equipment/eye-of-the-unseen.json
Turns out the RE was already in the item - nobody bothered to remove the links to the effects.
> Remove effects from Eye of the Unseen

- packs/crown-of-the-kobold-king-bestiary/dark-talon-kobold.json
- packs/crown-of-the-kobold-king-bestiary/kieragan-skross.json
- packs/equipment/hellknight-half-plate.json
- packs/feats/advanced-order-training.json
- packs/feats/gaze-of-veracity.json
So that the name matches the dedication name.
They are also called signifiers in Hellknight Half Plate description, but that's in flavor, so I didn't make a change there. Should I do that as well?
Also, fixed a typo and a minor formatting error in CotKK bestiary.
> Rename Hellknight Signifier to Signifer in feat prerequisites

- packs/classfeatures/debilitating-strike.json
This needs to be reworked eventually, but it'll require a migration
> Hide disabled Bloody Debilitation dice in Debilitating Strike feature

- packs/equipment/pilgrims-token.json
Item from the feat is a wooden religious symbol, so its price should be 1 sp instead of 2 sp.
> Correct Pilgrim's Token price

- src/module/rules/rule-element/battle-form/rule-element.ts
Fixes #17563 
When comparing a battle form's static bonus to a character's unarmed attack bonus to choose which was higher, Foundry did not consider modifiers. This change grabs the applicable modifiers (status/circumstance bonuses, and penalties) and applies them in the comparison before setting the generated Strike's modifiers.
This will result in a slight (but acceptable) change in functionality. If a character's unarmed attack modifier is higher than the battle form's modifier, their modifiers will always be used, no matter what penalties are applied. This should work in reverse too (with bonuses and a lower unarmed attack modifier). **The total modifier won't change**, but the calculation will, since previously, the calculation would switch to the battle form's modifier once the …
> Add applicable modifiers to battle form unarmed modifier comparison

- src/styles/actor/_item-transfer-dialog.scss
6ch fits 5 characters. Padding seems to be about 1 character wide.
> Allow more characters to fit in transfer dialog quantity field

- src/module/actor/character/sheet.ts
- src/styles/actor/character/_crafting.scss
- static/lang/en.json
- static/templates/actors/character/tabs/crafting.hbs
I wanted to move the free crafting from the fake trait toggles, as it only applied to known formulas and looked confusing separated visually where it was. I also wanted to get rid of another old style header.
> Update styling of known formulas

- src/module/item/consumable/types.ts
- src/scripts/config/traits.ts
- static/lang/en.json
This would be useful to build the investigator's Quick Tincture and Wandering Chef's Quick Alchemy Crafting Ability rule elements.
> Add alchemical tool and alchemical food consumable tags

- packs/classfeatures/amulet.json
- packs/classfeatures/bell.json
- packs/classfeatures/chalice.json
- packs/classfeatures/lantern.json
- packs/classfeatures/mirror.json
- packs/classfeatures/regalia.json
- packs/classfeatures/tome.json
- packs/classfeatures/wand.json
- packs/classfeatures/weapon.json
- packs/equipment/amulet-implement.json
- packs/equipment/bell-implement.json
- packs/equipment/chalice-implement.json
- packs/equipment/lantern-implement.json
- packs/equipment/mirror-implement.json
- packs/equipment/regalia-implement.json
- packs/equipment/tome-implement.json
- packs/equipment/wand-implement.json
- static/lang/re-en.json
Either grant a generic implement item, or tag an existing item as an implement. No automation yet, but the plan is to add suboptions to denote which implement is being held, and leverage that for automation from there.
Tagging @mysurvive, your input would be appreciated here! Trying to take some stuff off your plate.
> Add basic support for physical implement items for Thaumaturge

- src/module/actor/base.ts
- src/module/chat-message/data.ts
> Show selectors when inspecting damage taken messages

- src/module/apps/sidebar/chat-log.ts
- src/module/chat-message/listeners/damage-taken.ts
Tooltipster usage outside application windows will be skipped pending their purgation
> Remove destroyable management from chat messages

- src/module/actor/roll-context/base.ts
Closes https://github.com/foundryvtt/pf2e/issues/12521
I would feel more comfortable having this merged if some people volunteer for extensive QA.
> Receive statistics from cloned actors for non-strikes

- static/templates/actors/character/tabs/crafting.hbs
This prevent the form to be submitted when pressing `enter` in any input field on the sheet.
> Fix `Craft` button being a submit button

- src/scripts/macros/hotbar.ts
Someone wanted to be able to invoke the use button externally. I considered action.use() and feat.use(), but given how we are against adding api I figured that at the very least expanding an existing function would be within reason.
UUIDs allow us to invoke the item of a specific actor. TBH I suspect for linked actors the macro creation should probably use the uuid anyways, but that's probably assumptive.
> Support uuid when using rollItemMacro()

- src/util/destroyables.ts
I really do like the Idea of using Mutation Observer for the otherwise errorprone task of cleanup up the `tooltipster`, `Sortable` and `Tagify` instances. I wish I had thought of that when authoring my PR.
However, I have identified some issues with the current implementation that this PR aims to address:
1. **Tooltipster cleanup timing**
Tooltipster instances normally to be destroyed **before** their associated DOM elements are removed. Tooltipster relies on jQuery’s .data attribute to store references to its instances, and these attributes are cleared when elements are removed via jQuery. If the destroy method is called after this happens, Tooltipster logs warnings or even throws errors.
Additionally, the instance itself is not automatically destroyed, and it retains a reference to the …
> Fix memory leaks and failed cleanups in destroyables Mutation Observer

- packs/actions/skill-actions/disarm.json
- packs/other-effects/effect-disarm-bonus.json
- packs/other-effects/effect-disarm-success.json
- static/lang/action-en.json
- static/lang/re-en.json
Also moved the effects to `other-effects` rather than `equipment-effects`. I didn't redirect since it was only linked in `action-en.json`, but I can add a redirect if deemed necessary.
> Add Ephemeral Effect for Disarm's bonus to further attempts

- packs/actions/implements-interruption.json
- packs/classfeatures/bell.json
- packs/classfeatures/chalice.json
- packs/classfeatures/implements-empowerment.json
- packs/classfeatures/mirror.json
- packs/classfeatures/wand.json
- packs/classfeatures/weapon.json
- packs/feats/thaumaturge-dedication.json
- static/lang/re-en.json
This would supersede #16265 and #14678
The predicated `GrantItem` does require an actor update after the Implement Initiate feat has been taken, the same way Champion does, which isn't ideal. It might be good to consider if such an update could be triggered upon a feat being taken, or something along those lines. (Made an issue for it here #17698)
also disable Implement's Empowerment if no implement is being held, and deleted some unused localization keys. Some might be added back later as needed, but nothing is using them right now.
> Grant implement with Thaumaturge Dedication and add Note for Weapon Implement Adept

- src/module/apps/hotbar.ts
Use UUID for item macros created from linked actors.
> Roll item macros for linked actors even if another actor is selected

- packs/feats/diverse-mystery.json
Might need to look into a way of excluding spells from your own mystery, but not sure what the best way to go about that would be.
> Allow 3rd rank revelation spells to be chosen for Diverse Mystery

- packs/classfeatures/bomber.json
The acid, fire, electricity and cold trait are based on the damage type of the item. When the Bomber alchemist class feature changes the damage type of versatile vials it should also alter the damage trait of the item.
> Alter versatile vial traits with bomber class feature

- packs/feats/scuttle-up.json
- packs/feats/skilled-climber.json
fixed kashrishi's scuttle-up and skilled climber feats to use selector, rather than type. Also made skilled climber change climb speed to movement speed when scuttle up is taken.
> Fix Kashrishi climbing feats

- packs/classfeatures/mirror.json
- packs/classfeatures/second-adept.json
- packs/feat-effects/effect-instructive-strike.json
- packs/feats/cursed-effigy.json
- packs/feats/implements-flight.json
- packs/feats/instructive-strike.json
- packs/feats/intense-implement.json
- packs/feats/seven-part-link.json
- packs/feats/shared-warding.json
- packs/feats/thaumaturges-investiture.json
- packs/feats/thaumaturgic-ritualist.json
- packs/feats/ubiquitous-weakness.json
Also
- Fix wrong Adept Benefit being linked in Mirror class feature
- Change Second Adept's Choice Set item flag to `secondAdept`
- Automate Intense Implement
- Use ternary over brackets in Thaumaturge's Investiture
- Add compendium links to various feat descriptions
> Add effect for Instructive Strike and automate Implement's Flight

- packs/feats/wild-witchs-armaments.json
- static/lang/re-en.json
Also, corrects a typo in the localization and updated iron teeth note to match errata.
> Add localized notes to Wild Witch's Armaments feat

- packs/classfeatures/adept-benefit-bell.json
- packs/classfeatures/adept-benefit-mirror.json
- packs/classfeatures/paragon-benefit-bell.json
- packs/classfeatures/paragon-benefit-mirror.json
- packs/feat-effects/effect-chalice-adept-benefit-self.json
- packs/feat-effects/effect-drink-from-the-chalice.json
- static/lang/re-en.json
Also have the Chalice Adept Benefit's effect add a description addendum to Drink from the Chalice to make it clearer to the user
> Add adept and paragon benefits description addenda to Ring Bell and Mirror's Reflection

- src/styles/ui/sidebar/chat/_index.scss
The portrait itself still handles click events, but the image which overflows intentionally no longer blocks
> Fix chat token images blocking saves posted to chat

- src/module/actor/character/sheet.ts
- src/styles/actor/character/_crafting.scss
- static/templates/actors/character/tabs/crafting.hbs
This removes the ability for spontaneous crafting that is independent of activations. There is a point of disconnect where quick alchemy done via the crafting tab is slightly different than quick alchemy done via the actions tab. I would prefer gather data first, as its easier to add features than remove as far as perception goes.
I have a suspicion that the `use` button being how you craft with quick alchemy won't be that intuitive. If so, duplicating crafting actions in the actions tab to the crafting tab may help teach that its related and also allow better UX in certain out of combat scenarios.  However this is different from the current implementation that allows you to quick craft items even without being associated with an action.
The future has a few different approaches:
1) Leave …
> Remove spontaneous quick craft button from crafting tab

- packs/classfeatures/first-implement-and-esoterica.json
- packs/classfeatures/implement-adept.json
- src/module/item/base/data/system.ts
- src/module/item/base/document.ts
- src/module/rules/rule-element/base.ts
- src/module/rules/rule-element/grant-item/rule-element.ts
There are 3 different bugfixes here, but as each one is useless on its own, I submitted them altogether
1) Move the AELike initializing adeptChoices and paragonChoices earlier. AELikes and Grant items resolve immediately during preCreate and ignore priority.
2) While granter flags are set in source data to be saved, AELikes referring to them were initially incorrect. We assign to the item during data preparation so that those AELikes function appropriately.
3) item updates performed in preCreate() immediately trigger actor data preparation and caused us to lose all temporary changes applied during preCreate. This was the real reason the array did not exist in the adept choice.
> Fix corruption in grant item data when jumping multiple levels

- packs/feats/elaborate-talisman-esoterica.json
- packs/feats/gadget-specialist.json
- packs/feats/plentiful-snares.json
- packs/feats/snare-genius.json
- packs/feats/snare-specialist.json
- packs/feats/snarecrafter-dedication.json
- packs/feats/ubiquitous-snares.json
The snare feats (Snarecrafter Dedication, Snare Genius and Snare Specialist) were sharing a slug (what used to be a selector), which combined their slots into one. Unlike alchemy archetypes, this doesn't seem to be supported by the rules, so I've separated them into their own Crafting Abilities.
> Update Snare feats and Gadget Specialist crafting abilities

- src/module/actor/character/crafting/ability.ts
People were trying to do this in order to use quick vial, and understandably it was not working as expected
> Prevent recursively creating a resource by expending that same resource

- src/module/item/container/document.ts
- src/module/item/physical/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/17807
An alternative idea if we want to keep held items separate is to allow stacking held items if the quantity of any of them is 0, and to auto-delete if reduced to 0 and a stack exists, but that's significantly more complicated to solve and I don't think it ended up being worth it after all.
> Allow held items to stack with other held items

- packs/equipment/ka-stone.json
- static/lang/re-en.json
> Correct Ka Stone localization path and string

- src/module/rules/rule-element/roll-option/rule-element.ts
This fixes kineticist when jumping from levels 4 to 9 and doing 2 back to back gate junctions on the same element.
The cause of the bug is `this.option = this.#resolveOption()` called directly in the constructor on line 30, snapshotting the value. Subsequent calls to #resolveOption() don't actually do anything on master.
I'm ok with trying a different approach where we store `#initialOption` in the rule element if you prefer that.
> Fix RollOption option injected with flags introduced later in data preparation

- packs/actions/furious-strike.json
- packs/feat-effects/effect-core-cannon.json
- packs/feats/brilliant-crafter.json
- packs/feats/brutal-finish.json
- packs/feats/core-cannon.json
- packs/feats/grievous-blow.json
- packs/feats/skeletal-resistance.json
- packs/feats/soul-warden-dedication.json
- packs/heritages/ghoran/ancient-ash.json
- packs/spell-effects/spell-effect-soothing-words.json
- static/lang/re-en.json
Also move more brackets to other formulas.
Core Cannon has its Strike inside the feat itself, predicated on a roll option in the effect. I'm not 100% sure why it's set up that way, but I'm open to changing it if someone sees the need to do so.
> Add Note to Grievous Blow and Brutal Finish, and potency rune bonus to Core Cannon effect

- packs/classfeatures/implement-adept.json
- packs/classfeatures/implement-paragon.json
- packs/classfeatures/second-adept.json
- packs/feats/intense-implement.json
These are not being used by anything anymore after the restructuring of the class.
> Remove unused adept and paragon implement tags

- packs/npc-gallery/prisoner.json
- packs/pfs-season-1-bestiary/1-12/hungry-blade-apprentice.json
- packs/pfs-season-1-bestiary/1-12/hungry-blade-recruit.json
- packs/pfs-season-4-bestiary/4-12/witchs-wing.json
- packs/pfs-season-5-bestiary/5-03/krosovahn-mendesil-7-8.json
- packs/pfs-season-5-bestiary/5-03/krosovahn-mendesil.json
- packs/pfs-season-6-bestiary/6-00/sharkskin.json
- static/lang/re-en.json
Also removes the roll options from older actors as these are not in use
> Update `You're next` to use `/act` syntax on select NPC actors

- static/lang/en.json
Before:
After:
"TraitGnoll" text was changed with 215b740d1da7.
> Update gnoll trait description to reference kholo

- packs/feat-effects/effect-extra-alchemy.json
Closes #17893
I was sure I had accounted for this, but clearly I didn't. My bad!
> Update Extra Alchemy's rule element to execute after Advanced Alchemy slot upgrades

- packs/equipment/armored-coat.json
LO: KoL p. 86: "All the gear, armor, shields, and weapons in this section are uncommon, and Knights of Lastwall have access to all of them."
> Fix rarity for Armored Coat

- packs/campaign-effects/pathfinder-society/effect-grand-finale.json
- packs/campaign-effects/pathfinder-society/effect-light-in-the-dark.json
- packs/campaign-effects/pathfinder-society/effect-nexian-researcher.json
- packs/campaign-effects/pathfinder-society/effect-practiced-medic.json
- packs/campaign-effects/pathfinder-society/effect-tarnbreaker-champions.json
- packs/campaign-effects/pathfinder-society/effect-technological-defence.json
- packs/pathfinder-society-boons/adversary-lore.json
- packs/pathfinder-society-boons/menace-under-otari.json
- packs/pathfinder-society-boons/practiced-medic.json
- packs/pathfinder-society-boons/s1-00-nexian-researcher.json
- packs/pathfinder-society-boons/s1-04-touched-by-the-storm.json
- packs/pathfinder-society-boons/s1-10-tarnbreaker-champions.json
- packs/pathfinder-society-boons/s1-18-light-in-the-dark.json
- packs/pathfinder-society-boons/s1-18-narsens-web.json
- packs/pathfinder-society-boons/s1-25-grand-finale.json
- packs/pathfinder-society-boons/s1-q08-numerian-archaeologist.json
- packs/pathfinder-society-boons/steady-hand.json
- static/lang/re-en.json
Note - Please merge #17839 first before merging this one. Thanks!
> Add automation and effects to additional Pathfinder Society Boons

- src/module/rules/rule-element/roll-option/rule-element.ts
Closes #17015
Closes #17857
Closes #17932
If a new suboption is selected, all related `RollOptions` are updated. However, `#resolveSuboptions` is used to select the affected rules, which first filters out duplicates. This can result in individual `RuleElements` not being passed and therefore not being updated. During subsequent processing, these `RuleElements` then overwrite the new selection with the old value.
This PR adds a separate method `#resolveSuboptionRules` to find all `RollOptions` of the same family, replacing `#resolveSuboptions` in the update process.
> Fix update mechanic on RollOptions with merged suboptions

- packs/feats/quick-recovery.json
> Correct level for the Quick Recovery Yaoguai ancestry feat

- packs/equipment/versatile-vial.json
Versatile Vials have a bug in automation that incorrectly applies item bonus to attack rolls from 4th level upgrade to lower level versions. As far as I can understand, the issue is in automation that scales them with actor level, the main problem lying in automation defaulting to +1 bonus for Versatile Vials below 12th level.
> Fix Versatile Vials having item bonus to attack rolls before level 4

- src/module/item/base/document.ts
- src/module/rules/rule-element/special-resource.ts
The [...item] change stops precreates from running twice. The special resource change makes it a bit smarter when multiple of the same special resource is added simultaneously.
> Fix versatile vials being created twice when alchemist is added

- src/module/actor/character/apps/formula-picker/app.svelte
- src/module/actor/character/apps/formula-picker/app.ts
- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/sheet.ts
- src/module/chat-message/helpers.ts
- src/module/sheet/components/hover-icon-button.svelte
- static/lang/en.json
Versatile Vial is only there due to a twisted experiment. Nobody should be adding it themselves. The goal is to make snarecrafter easier to use.
> Add support for changing prepared quantities from the formula picker

- src/module/actor/creature/document.ts
- src/module/actor/creature/sheet.ts
- src/module/actor/spellcasting.ts
- src/module/apps/compendium-browser/browser.ts
- src/module/item/spell/document.ts
- src/module/item/spellcasting-entry/collection.ts
- src/module/item/spellcasting-entry/item-spellcasting.ts
- src/module/item/spellcasting-entry/rituals.ts
- src/module/item/spellcasting-entry/trick.ts
- src/module/item/spellcasting-entry/types.ts
Adding these getters to each new spellcasting type is silliness. The ones that can return true still exist because they're easy to keep around, but they're on the chopping block.
> Remove most category getters from non-document spellcasting entries

- src/module/rules/helpers.ts
- src/module/rules/rule-element/choice-set/rule-element.ts
- src/module/rules/rule-element/roll-option/data.ts
- src/module/rules/rule-element/roll-option/rule-element.ts
Created to purify some frankly scary thaumaturge related rule elements
```json
{
"key": "RollOption",
"option": "super-skill",
"toggleable": true,
"phase": "beforeDerived",
"suboptions": {
"config": "skills",
"predicate": [
{
"gt": [
"skill:{choice|value}:rank",
0
]
}
]
}
}
```
> Support suboptions from config in roll option rule element

- src/module/item/base/data/system.ts
- src/module/item/helpers.ts
- src/module/rules/rule-element/item-alteration/rule-element.ts
Around 10ms improvement in preparing high level sorcerers with a few metamagic and bloodline feats.
> Lazy load description alterations

- src/module/item/base/document.ts
- src/module/item/base/sheet/sheet.ts
- src/module/item/consumable/document.ts
- src/module/item/helpers.ts
- src/module/item/spell/document.ts
- src/module/item/spell/sheet.ts
- src/module/item/weapon/document.ts
- src/module/rules/rule-element/item-alteration/rule-element.ts
- src/module/rules/rule-element/strike.ts
Closes https://github.com/foundryvtt/pf2e/issues/18018. Applies to both real spells and fake spells such as signature spells. I copied over some of the refactors of the staff PR regarding descriptions so that it works a bit more smoothly.
> Fix multiplying addendum notes on spells

- src/module/rules/rule-element/item-alteration/rule-element.ts
This is a very minor speedup on actors that have a few strikes and a lot of alterations of any kind. In the best case it removes around 3-4ms, but its simple and easy.
> Skip item alteration roll option fetching if it doesn't match any items

- src/module/item/weapon/sheet.ts
- static/templates/items/weapon-details.hbs
Closes https://github.com/foundryvtt/pf2e/issues/18025
> Avoid saving temporary modifications to weapon striking runes when editing the weapon

- packs/equipment/chromatic-jellyfish-oil-moderate.json
Moderate Chromatic Jellyfish Oil was set to Level 11; the actual level is 14 (see https://2e.aonprd.com/Equipment.aspx?ID=1959 )
I opened a previous Issue about this, #18047 .
> Fix level of Moderate Chromatic Jellyfish Oil

- packs/feats/hideous-ululation.json
Disturbing Defense says "You gain resistance to precision damage equal to 2 + your number of class feats from the oozemorph archetype" and Hideous Ululation is not a class feat, it's a skill feat.
> Remove rule element from Hideous Ululation

- packs/spells/spray-of-stars.json
Spray Of Stars deals 2d4 fire, not 1d4. It dealt 1d4 in legacy
> Fix damage of Spray of Stars

- .prettierrc.json
- src/module/actor/character/apps/abc-picker/app.svelte
Svelte collapses whitespace by default, so the setting is unnecessary and only leads to ugly html
> Disable whitespace sensitivity for svelte files

- src/module/rules/rule-element/item-alteration/alteration.ts
- src/module/rules/rule-element/item-alteration/schemas.ts
Sort of fixes #18054, #18032 and #16714?
While looking for DamageAlteration info, I noticed that in #18032, Shark mentioned that increasing the damage of weapons should be done in ItemAlteration. I suspect he meant damage faces, but I was curious if you could really do base weapon damage dice number increases that way, and turns out, yeah?
Additionally, I think having the base weapon damage dice number increased for weapons in ItemAlteration makes more sense than having it in DamageAlteration. This solution also "fixes" the problem that Gravity Weapon and the like have, where by referring to `@weapon.system.damage.dice`, they don't benefit from DamageAlteration increases.
> Extend ItemAlteration to be able to change base damage dice number

- src/module/system/statistic/statistic.ts
- src/styles/actor/vehicle/_sidebar.scss
- static/templates/actors/vehicle/sidebar.hbs
Closes https://github.com/foundryvtt/pf2e/issues/18063.
Is there a reason we don't return true in the else case?
> Fix rolling vehicle fortitude saves

- src/module/system/statistic/statistic.ts
It seems the code we're removing predates the origin/target options. Currently if an NPC ability includes an inline perception check that is posted to chat, the origin is the roller and not the NPC. This conflicted with item.actor, creating two sets of origin options.
After this, it should only post the roller's options as the origin by default.
This bug looks ancient though, I wonder why now.
> Prevent having two sets of origin options for non-saves

- src/module/item/base/document.ts
For an otherwise bare bones swashbuckler with 6 finisher options, it speeds up adjusting the toggle's selected suboption from 212ms to 27ms. Larger actors will lead to larger gulfs (which I've witnessed sometimes approach seconds).
You can test on a swashie with the sheet closed by selecting the token and running
`foundry.utils.benchmark(() => _token.actor.toggleRollOption("all", "finisher", null, true, _token.actor.synthetics.toggles.all.finisher.suboptions.find((s) => !s.selected).value), 50)`
> Improve performance of mergeable sub options

- packs/feat-effects/effect-monster-warden.json
Closes #18079
Separate the FlatModifier RE on the `Effect: Monster Warden` to only provide a +1 to attacks.
> Correct monster warden circumstance bonus

- src/module/actor/sheet/item-summary-renderer.ts
Addresses the issue https://github.com/foundryvtt/pf2e/issues/18086
Removes the default self-applied effect link label and lets the enricher generate one.
> Remove explicit label from self-applied effect item link to facilitate localization in the item's summary

- src/module/rules/rule-element/roll-option/rule-element.ts
Currently in live, the processing occurs per merge entry but only the first one actually applies (due to the early return). So the others are superfluous.
> Avoid duplicate processing in mergeable roll options by returning earlier

- src/module/actor/inventory/bulk.ts
- src/module/item/container/document.ts
This check also exists in PhysicalItemPF2e#bulk, but was inconsistent in its application. Closes https://github.com/foundryvtt/pf2e/issues/18089.
> Fix stacks of items being bulk adjusted on vehicle actors

- packs/classfeatures/animal-instinct.json
> Remove level 7 reach increment for Deer antler and Frog tongue from Animal Instinct class feature

- packs/feats/empiricists-eye.json
and remove auditory trait from Point Out if it's on the actor's sheet
> Add missing prerequisite to Empiricist's Eye

- packs/equipment/reinforced-chassis.json
This is the new language of Reinforced Chassis
> Your body is designed to be particularly resilient. Your chassis is made from reinforced armor plating that grants a +3 item bonus to AC with a Dexterity cap of +1. If you are at least 5th level, the item bonus increases to +4 and at 10th level it increases to +5. You can never wear other armor or remove your chassis; however, you still don't become fatigued from sleeping. You can etch armor runes onto your chassis.
Since it doesn't specify it being any category of armor, and the runes are etched into the chassis specifically (as opposed to onto explorer's clothing in Scaly Hide), I think this might be the best way to go about it. The Reinforced Chassis feat includes the scaling for this armor.
> Update Reinforced Chassis physical armor to be unarmored

- packs/spells/trade-death-for-life.json
Trade Death for Life hex cantrip is incorrectly stated to have casting time of 2 actions instead of 1.
> Fix incorrect casting time on Trade Death for Life

- packs/equipment/black-powder-dose.json
- packs/feats/munitions-crafter.json
Closes #18251
For the sake of completion I suppose. Also shorten `Black Powder (Dose or Round)` to `Black Powder (Dose)`, since rounds have weapon-specific items.
> Include "Black Powder (Dose)" in Munitions Crafter's Crafting Ability

- packs/classfeatures/ashes.json
Added a class predicate to the Grant Item rule element that confers Whispers of Weakness to prevent incorrectly giving this class feat to characters who pick up the ashes mystery via the oracle dedication archetype feat.
> Add class predicate to Oracle Ashes mystery

- packs/classfeatures/time.json
Added a class predicate to the Grant Item rule element that confers Oracular Warning to prevent incorrectly giving the class feat to characters who pick up the time mystery via the oracle dedication archetype feat.
> Add class predicate to Oracle Time mystery

- packs/outlaws-of-alkenstar-bestiary/dewey-daystar.json
In all the other entities, in the spell dc fields (value, dc, mod) the values are written as int. This is the only case in which they are written as string.
> Fix spell dc data of Dewey Daystar

- packs/agents-of-edgewatch-bestiary/baatamidar.json
- packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
- packs/agents-of-edgewatch-bestiary/blunes-illusory-toady.json
- packs/agents-of-edgewatch-bestiary/camarach.json
- packs/agents-of-edgewatch-bestiary/daemonic-infector.json
- packs/agents-of-edgewatch-bestiary/daemonic-rumormonger.json
- packs/agents-of-edgewatch-bestiary/daemonic-skinner.json
- packs/agents-of-edgewatch-bestiary/ghaele-of-kharnas.json
- packs/agents-of-edgewatch-bestiary/hundun-chaos-mage.json
- packs/agents-of-edgewatch-bestiary/overdrive-imentesh.json
- packs/agents-of-edgewatch-bestiary/sordesdaemon.json
- packs/agents-of-edgewatch-bestiary/ulressia-the-blessed.json
- packs/agents-of-edgewatch-bestiary/veksciralenix.json
- packs/outlaws-of-alkenstar-bestiary/follower-of-shumfallow.json
- packs/pfs-season-2-bestiary/2-16/burned-out-efreet.json
- packs/pfs-season-2-bestiary/2-16/corvius-vayn-5-6.json
- packs/pfs-season-2-bestiary/2-16/perizia-5-6.json
- packs/pfs-season-2-bestiary/2-16/planar-nixie.json
- packs/pfs-season-2-bestiary/2-18/vermlek-centaur-3-4.json
I've noticed that most of the creatures (NPC/Monsters) have their spell casting entry set as a int value (since the value is always numerical). I've changed every creature that had a string dc value to int to be more coherent with the rest of the data.
> Convert 'dc' field string values to integers

- packs/spells/prismatic-spray.json
Removed the saving throw inlines for the spell variants as the inlines would go for the highest values, not those from the origin spellcasting.
Closes #18246
> Add inline damage rolls and variants to Prismatic Spray

- src/module/actor/base.ts
- src/module/rules/rule-element/special-resource.ts
- src/module/system/schema-data-fields.ts
We can add more complex rules once we have a better workflow for start of turn events.
> Add support for disabling special resource renewal

- packs/classfeatures/flame-order.json
- packs/classfeatures/stone-order.json
- packs/classfeatures/wave-order.json
- packs/equipment/necklace-of-knives.json
Updated the RE so it correctly interacts with Deadly simplicity and the description so it has a link to the dagger item.
Updated the descriptions of orders; Flame, Stone, Wave so they match up with the other orders style.
This closes issue #18285
> Update Necklace of Knives and Druidic orders

- src/module/canvas/token/aura/renderer.ts
- src/module/canvas/token/object.ts
Continues to show for regular hidden
> Hide aura texture when token is GM hidden

- src/module/item/physical/coins.ts
Instead of using hardcoded currency denominations, output localized names.
Also, when parsing item value, tries to convert it from localized name to English before parsing values
Example output (An item with value of 1 cp, 2 sp, 3 gp, 4 pp)
On item sheet (input visually truncated, but accepts both localized strings and English strings)
> Add translation to item currency values and parsing

- packs/spell-effects/spell-effect-shields-of-the-spirit.json
Update spell-effect-shields-of-the-spirit.json
Added GrantItem Rule Element to the Shields of the Spirit spell effect that applies "Effect: Raise a Shield"
> Add GrantItem RE for Raise a Shield to Shields of the Spirit spell effect

- packs/actions/pursue-a-lead.json
- packs/feats/detectives-readiness.json
Should handle https://github.com/foundryvtt/pf2e/issues/17939 (at least the original issue). The Defensive Stratagem part might not be easily doable with REs.
- - -
Moves part of the RE responsible for the Pursue a Lead bonus for saving throws from Pursue a Lead action into Detective's Readiness.
Reasons: In the current implementation, investigators get an optional bonus to saving throws even without a feat, which is labeled Pursue a Lead. This might be confusing to players, especially if they don't intend to ever take Detective's Readiness.
Updated behavior: Shows the bonus when the character has the feat. This bonus is labeled Detective's Readiness, as expected.
Since the RE has slug property "pursue-a-lead", it still gets improved by Investigator Expertise.
> Move Detective Readiness modifier RE into its feat

- src/module/recall-knowledge.ts
- src/scripts/config/traits.ts
- static/lang/en.json
Closes https://github.com/foundryvtt/pf2e/issues/18458
Also adds the Shade trait, which isn't in use yet, but has been claimed by Player Core.
> Add creature identification skills for dream, shade, and time

- packs/spell-effects/spell-effect-shields-of-the-spirit.json
Also added `"granter": "detach"` to not lower shield, in case the effect is removed prematurely, or some ability that increases the duration of raise shield is introduced.
> Remove Shields of the Spirit effect if shield is no longer raised

- packs/feats/armored-stealth.json
The second rule is needed to cap the resolved penalty to `0`. Otherwise, an actor with `master` stealth and studded leather armor, will make the penalty `-1 + 2 = +1`!
Note that the item is still not 100% supported with this change, as it doesn't check for proficiency. You could potentially account for this in the `value` calculation, but it really should be a `predicate` since the existing rule also needs to be disabled when not proficient. I tried with a `{"not":"defense:{actor|wornArmor.system.category}:rank:0"}` predicate, which technically works, but it throws an error when no armor is worn.
> Add rules to handle Armored Stealth penalty adjustment

- packs/spore-war-bestiary/book-1-whispers-in-the-dirt/fungal-flytrap.json
This variant Giant Flytrap doesn't have Improved Grab
> Remove Improved Grab from Fungal Flytrap's Focused Assault

- packs/feats/kholo-weapon-familiarity.json
Also, there seems to be a "kholo" trait description in the translation data. Not sure if that's vestigial or the gnoll trait was actually meant to be renamed to kholo, as opposed to just having a different display value.
https://github.com/foundryvtt/pf2e/blob/376d59d743108cd77a3f44acf761b23c54a94e00/src/scripts/config/traits.ts#L1352
> Fix Kholo Weapon Familiarity

- packs/equipment/assassins-bracers-type-i.json
- packs/equipment/assassins-bracers-type-ii.json
- packs/equipment/assassins-bracers-type-iii.json
- packs/equipment/bands-of-force-greater.json
- packs/equipment/bands-of-force-major.json
- packs/equipment/bands-of-force.json
Closes #18479
and remove `bracers-of-armor` slug from Assassin's Bracers, which are seemingly the result of copy pasting rule elements from the Bands of Force.
> Update Bands of Force's Flat Modifier slug

- packs/pathfinder-npc-core/ancestry-npcs/catfolk/catfolk-name-collector.json
- packs/pathfinder-npc-core/ancestry-npcs/elf/forlorn-artist.json
- packs/pathfinder-npc-core/ancestry-npcs/halfling/halfling-yarnspinner.json
- packs/pathfinder-npc-core/official/watchmage-squadron.json
- packs/pathfinder-npc-core/scholar/departmental-chair.json
Added missing Spell Statistics (Spell DC/Attack) to the following NPC Core actors:
Forlorn Artist
Catfolk Name Collector
Halfling Yarnspinner
Watchmage Squadron
Departmental Chair
> Add missing spell statistics to additional NPC Core Actors

- packs/spells/far-flung-fetch.json
Fixed the passage "...one of your open hand..." to "...one of your open hands..." as corroborated by [Demiplane's page for the spell](https://app.demiplane.com/nexus/pathfinder2e/spells/far-flung-fetch-rm).
> Fix minor typo in Far-Flung Fetch

- src/module/item/spell/document.ts
This bug mostly affected the editor, but it can cause incorrect data to stick around.
Closes https://github.com/foundryvtt/pf2e/issues/18514
> Fix spell variants always fixed heightening when cast without a rank

- packs/feat-effects/effect-watchful-gaze.json
- packs/feats/ancestry/goloma/watchful-gaze.json
- packs/feats/archetype/chronoskimmer/superimpose-time-duplicates.json
To prevent players from thinking they should drag the glossary item to themselves
> Remove player facing links to All-Around Vision glossary item

- packs/classfeatures/elemental-magic.json
- packs/classfeatures/flexible-spell-preparation.json
- packs/classfeatures/wellspring-magic.json
I did another round of testing and noticed that I needed to fine-tune the filters for Elemental Magic and Flexible Spell Preparation.
Did not add Summoner and Psychic to the options for Wellspring Magic. Summoner has no grant choices for their subclasses and Psychic has two choices. Will leave those out for the moment.
> Implement Wellspring Magic grant as class archetype choice and add brush up Elemental Magic and Flexible Spell Preparation choice grants

- packs/classfeatures/deity-champion.json
Remove the page reference from the description and reduce the number of rules needed to do the same thing
> Clean up Champion deity rule elements

- packs/classfeatures/horn-of-plenty.json
and add link to elixir of life in the description.
It seems the elixirs, which are alchemical items, are hardcoded to receive the infused trait when created via daily prep crafting, so that makes this implementation slightly innacurate.
> Implement Horn of Plenty's daily crafting

- packs/feats/archetype/vigilante/stunning-appearance.json
Adds the Stunning Appearance Information to Startling Appearance if the former feat is taken.
> Add Stunning Appearance Note automation for Startling Appearance (Vigilante)

- packs/equipment/reinforced-chassis.json
Closes #18612
I guess we could get away with not even having the physical item now, but it's still useful for property runes
> Remove check and speed penalty, and strength requirement from Reinforced Chassis

- packs/feat-effects/effect-oath-of-the-defender.json
We do have an open issue (#17428) about the resistance only applying to the highest instance of damage, which isn't doable yet.
> Add increased Oath of the Defender's champion's resistance

- src/module/item/spell/document.ts
This probably broke when I was refactoring this to support other kinds of prepends/appends.
> Show spell traditions in description for unowned actors

- packs/conditions/deafened.json
- packs/conditions/encumbered.json
- packs/conditions/grabbed.json
- packs/conditions/restrained.json
- packs/conditions/sickened.json
- static/lang/en.json
- static/lang/re-en.json
Few points of interest
- Deafened
- `item:trait:auditory` doesn't necessarily represent all skill checks involving sound and involve other senses, but seems preferable to adding a toggle on the character sheet, and instead allowing it to be enabled in the roll dialog.
- All spells are affected by deafened's description alteration. That is based on the rules stating "being unable to speak prevents spellcasting for most casters", and that "all speech has the auditory trait". I know this is a bit of a hot topic of discussion, so let me know if we'd rather not have the note in that case.
- Sickened
- Added a DC-less fortitude save to its description.
- Included alchemical foods as items that are affected by its Item Alteration aside from potions and elixirs. Hopefully it's a reasonable enough …
> Add reminder notes to deafened, grabbed, restrained and sickened conditions

- src/module/actor/character/apps/abc-picker/app.ts
The `pf2e-animal-companions` clause is insufficient when it comes to any other 3rd party eidolons. This should hopefully take care of it.
> Exclude eidolons from ABC Picker

- src/module/system/text-editor.ts
This should preserve backwards compatibility. `@Check[deception|traits:fire|overrideTraits]` and `@Check[deception|traits:fire|overrideTraits:true]` should be equivalent to `@Check[deception|overrideTraits:fire]`.
We can either go this route, or attempt to transition/migrate to overriding by default and using `@Check[deception|addTraits:fire]` to add new ones instead. Regardless of what we do, we should make https://github.com/foundryvtt/pf2e/pull/18422 behave accordingly.
> Allow inline roll overrideTraits to be a list of traits itself

- packs/classfeatures/dragon-instinct.json
Currently the ItemAlteration RE breaks due to chromatic/metallic not being real traits.
Alternatively if this interpretation is not something the system wants to use, we should change the table to say N/A instead of Arcane.
> Change Dragon Instinct pre-remaster dragons to arcane tradition

- packs/deities/other-gods/sivanah.json
I reverted this to `delirium`, but this needs a migration.
Closes #18697
> Correct Sivanah's primary domain selection

- src/module/item/physical/runes.ts
The localization key already existed, the note just wasn't added yet
> Add missing bow group note for Grievous rune

- src/module/chat-message/listeners/cards.ts
- src/module/item/base/document.ts
- src/module/item/base/sheet/sheet.ts
- src/module/item/helpers.ts
- src/module/item/spell/document.ts
- src/styles/legacy/_chat.scss
- src/styles/ui/sidebar/chat/_index.scss
In the process of removing our dependency of the description getter, I saw a use case where we might want the full description.
> Support description item alteration addendums in expandable self effect actions

- packs/classfeatures/explode.json
- packs/feats/archetype/inventor/inventor-dedication.json
> Extend Unstable note to actions that have the `unstable` trait and add notes RE to Inventor dedication

- src/module/actor/creature/sheet.ts
- src/module/item/spellcasting-entry/collection.ts
- src/module/item/spellcasting-entry/document.ts
I asked idle and these functions aren't used in his module. I suspect the next release will be a patch release since no major changes are occurring nor are in the docket.
> Refactor spell unprepare to be done by preparing a null spell

- src/module/actor/sheet/base.ts
Reproduces core foundry functionality for our non-submit form inputs (see FormApplication#_render()). This should make https://github.com/foundryvtt/pf2e/pull/18531 work a bit better.
This will not be needed for svelte sheets at least.
> Preserve input focus in data-property and data-resource fields in re-render

- src/module/actor/roll-context/base.ts
- src/module/rules/rule-element/token-mark/rule-element.ts
- src/module/rules/synthetics.ts
Closes https://github.com/foundryvtt/pf2e/issues/18807. While the original issue is a feature request, token marks disabling the automation of other token marks smells more like a bug.
> Support multiple token marks instead of overriding them

- packs/equipment/grasp-of-droskar.json
> Remove `free hand` trait from Grasp of Droskar weapon

- src/module/item/weapon/sheet.ts
- src/styles/_colors.scss
- src/styles/actor/_index.scss
- src/styles/actor/army/_index.scss
- src/styles/actor/npc/_index.scss
- src/styles/actor/party/kingdom/_index.scss
- src/styles/actor/vehicle/_index.scss
- src/styles/item/_index.scss
- static/templates/items/weapon-details.hbs
Closes https://github.com/foundryvtt/pf2e/issues/18587
I also did some UI/UX stuff to make the adjusted colors behave more predictably with select, and made it themeable.
There is only one bug remaining: if you set it to empty input, the sheet will not re-render since there were no changes. This bug is a general problem with all of our handlebars sheets though, so I'm not really planning on fixing it here.
> Avoid persisting automated weapon property runes when closing the item sheet

- src/module/apps/effects-panel.ts
- src/scripts/hooks/canvas-ready.ts
- src/styles/_colors.scss
- src/styles/_globals.scss
- src/styles/system/_effects-panel.scss
- static/templates/system/effects/panel.hbs
Since Foundry V13 reduces borders by quite a bit, the current effects panel stands out. I changed it and themed the tooltips. Addendums have not been handled since item alterations are currently non-functional.
Also supports light mode interface
> Update Effects Panel to AppV2 and fix inline rolls styling

- packs/campaign-effects/season-of-ghosts/effect-blessed-coins.json
- packs/campaign-effects/season-of-ghosts/effect-spirit-power-passion.json
Didn't add a predicate to subsequent skill choices, as TSTNW p. 25 doesn't preclude it: "... there’s no advantage to using multiple blessed coins from the same shrine or from deities who share the same divine skill.
> Add effect for Blessed Coins

- static/lang/en.json
- static/templates/actors/npc/partials/sidebar.hbs
> Fix missing localized string for NPC Shield Max HP

- src/scripts/hooks/ready.ts
With V13 compatibility update, those are now split into "babele.dataLoaded" (first hook call) and "babele.ready" (second hook call).
> Remove babele double-hook

- src/styles/system/_effects-panel.scss
The hr size in v12 is very small, but in v13 its currently taller than even a single icon.
After tweak:
> Reduce divider size in effects panel

- packs/equipment/tengu-feather-fan.json
- packs/feats/ancestry/tengu/tengu-feather-fan.json
- packs/feats/ancestry/tengu/thunder-gods-fan.json
- packs/feats/ancestry/tengu/wind-gods-fan.json
- static/lang/re-en.json
- Updated item to one-hand-held usage per PFS Clarification.
- Updated item text and publication source to Pathfinder Player Core 2
- Added item alteration REs to add the respective class or spell DCs
> Update Tengu Fan Item usage, description text, publication source and add automation to feats.

- packs/feat-effects/effect-legendary-monster.json
- packs/feat-effects/effect-unleash-yaoguai-might.json
- packs/feats/ancestry/yaoguai/legendary-monster.json
- packs/feats/ancestry/yaoguai/unleash-yaoguai-might.json
- static/lang/re-en.json
Turns out there were effects in the system, but neither was added to their respective feats. Things I did:
- Localize any instances of spell effects, such as Enlarge and Fly, to now use dedicated RE to do these effects.
- I added "change-shape:yaoguai" as a predicate for all effects (per the ability description, these effects can only happen in Yaoguai form).
- Added a Choice Set to Legendary Monster (can only have one benefit active) with RollOptions so they can better integrate with the Unleash Yaoguai Might effect.
- Added Localized text.
- Added a toggle and Item Alteration Description to add flavor text to Change Shape when either ability is used.
- Changed the icons on both effects.
> Set up automation for `Unleash Yaoguai Might` and `Legendary Monster`

- src/module/actor/character/apps/formula-picker/app.svelte
- src/module/actor/character/apps/formula-picker/app.ts
- src/styles/_globals.scss
Before
After
There was a misalignment issue in the traits during dev, but when I went back to master it seems to have not occured, so it might be inconsistent sub-pixel rendering related (the height of the element was 17.5)
> Fix formula picker styling

- src/module/item/abstract-effect/data.ts
- src/module/item/affliction/data.ts
- src/module/item/armor/document.ts
- src/module/item/physical/data.ts
- src/module/system/text-editor.ts
Expired is only ever set programmatically, not persisted, so it shouldn't be part of the abstract effect source data.
> Fix affliction errors and import more types

- packs/spell-effects/spell-effect-ki-cutting-sight.json
- packs/spells/focus/ki-cutting-sight.json
Used a RollOption rather than a TokenMark as save spells (such as Qi Blast) don't include target data.
Closes https://github.com/foundryvtt/pf2e/issues/18962
> Add monk to trait to Ki Cutting Sight and add effect

- src/styles/actor/npc/_sidebar.scss
- static/templates/actors/npc/partials/sidebar.hbs
Color are still a bit off but I'd rather not mess with colors outside of the V13 branch if possible
> Fix display of NPC Shield health when 3 digits long

- packs/feats/class/alchemist/mutant-physique.json
Priority needs to be set after the tag is added to the strike so the tag is found by the predicate
> Fix Mutant Physique Deadly D10 ItemAlteration

- packs/spells/2nd-rank/blood-vendetta.json
> Remove `Concentrate` trait from Blood Vendetta spell

- src/styles/_colors.scss
- src/styles/ui/sidebar/chat/_check.scss
Closes https://github.com/foundryvtt/pf2e/issues/19134
The core `.dice-roll .dice-total.success` style is being overwrtten by the core `.chat-message h4` style due to the layer system. I suspect foundry is more likely to remove the style than to fix it given core doesn't seem to actually use and 5e no longer uses it.
> Fix regression with crit and crit fail result color

- packs/feat-effects/effect-furnace-form.json
- static/lang/re-en.json
Furnace Form feat (https://2e.aonprd.com/Feats.aspx?ID=4247) states:
```
You gain the benefits of the fiery body spell (except the ability to cast ignition) until the end of your next turn
```
However, in the actual effect, there is no mention of return damage, which combined with the fact the feat is just refering to the fiery body and not actually listing the effects itself can create a confusion what actually should be applied.
This PR fixes this issue by introducing automation for return damage.
> Add automation for return damage to Furnace form

- packs/feats/ancestry/android/internal-respirator.json
- packs/feats/ancestry/kashrishi/mental-sustenance.json
- packs/feats/ancestry/versatile-heritages/sylph/inner-breath.json
- packs/feats/general/breath-control.json
- packs/heritages/awakened-animal/swimming-animal.json
- packs/other-effects/effect-remaining-air.json
Made the Remaining Air effect max badge counter into an AE Like that gets upgraded by various feats like Breath Control.
Remade PR to rebase my fork and remove unnecessary extra merge commits
> Modify hold breath Air Remaining Effect duration to be upgradeable by feats

- packs/feat-effects/stance-ghosts-in-the-storm.json
- packs/feat-effects/stance-kindle-inner-flames.json
- packs/feat-effects/stance-orchards-endurance.json
- packs/feat-effects/stance-sea-glass-guardians.json
- packs/feat-effects/stance-shattershields.json
- packs/feat-effects/stance-thermal-nimbus.json
- static/templates/items/rules/aura.hbs
Closes https://github.com/foundryvtt/pf2e/issues/19176
Its exclusion from the form made it tricky for the layman to fix.
> Remove kineticist trait from stance auras and show invalid traits in form
