packs/classfeatures/extreme-curse.json

Automatically add/increase Doomed condition at extreme curse stage

---

packs/classfeatures/deific-weapon.json
packs/classfeatures/devotion-spells.json
packs/iconics/seelah-level-1.json
packs/iconics/seelah-level-5.json
packs/paizo-pregens/jadren-tagar.json
packs/spells/lay-on-hands.json

Fix reference to "Vs. Undead" spell effect in text of Lay on Hands

---

packs/agents-of-edgewatch-bestiary/avsheros-the-betrayer.json
packs/agents-of-edgewatch-bestiary/ghaele-of-kharnas.json
packs/pathfinder-bestiary-2/monadic-deva.json
packs/pathfinder-bestiary-2/planetar.json
packs/pathfinder-bestiary-2/solar.json
packs/pathfinder-bestiary-3/zuishin.json
packs/pathfinder-bestiary/astral-deva.json
packs/pathfinder-bestiary/ghaele.json
packs/pathfinder-bestiary/shield-archon.json

Also removed duplicate "Holy Greatsword" strike from Planetar

Add automation for NPC holy and unholy runes

---

packs/classfeatures/impulses.json

Add label for fire impulse junction upgrade

---

src/module/actor/character/elemental-blast.ts
src/module/item/spell/document.ts
src/module/system/damage/weapon.ts
src/module/system/text-editor.ts

Initial development effort was In3luki, I just helped get it to the finish line.

Make damage modifiers dialog visible in release worlds

---

src/module/actor/character/document.ts
src/module/item/physical/runes.ts
src/module/system/check/check.ts
src/module/system/damage/damage.ts
static/lang/en.json

Automate Keen rune

---

packs/bestiary-family-ability-glossary/ravener-vicious-criticals.json
packs/blood-lords-bestiary/urbulinex.json
packs/classfeatures/keen-flair.json
packs/feats/piercing-critical.json
packs/feats/savage-critical.json
packs/pathfinder-bestiary-2/ravener-husk.json
packs/pathfinder-bestiary-2/ravener.json

Automate Keen-rune-like abilities on PC options and creature abilities

---

src/styles/actor/character/_actions.scss

Somewhat gray names of unready strikes on PC sheet

---

src/module/item/spell/sheet.ts
src/styles/item/_index.scss
src/styles/item/_spell-sheet.scss
static/templates/items/spell-details.hbs
static/templates/items/spell-overlay.hbs

Cantrip/Counteract weren't right aligned, and formula rows in spell heighten layers had broken styling. Also kill some of the Jquery.

Fix some spell sheet errors and update to fieldset

---

packs/npc-gallery/demonologist.json
packs/pathfinder-bestiary-3/brimorak.json
packs/pfs-season-2-bestiary/firestorm-brimorak.json

Also make Demonologist's Breach the Abyss roll blind

Add automation for Brimorak's Flaming Weapon

---

src/module/item/spell/sheet.ts
static/templates/items/spell-overlay.hbs

Remove spell sheet overlay collection path property and fix regressions

---

src/module/apps/compendium-browser/index.ts
src/styles/_tags.scss

No functional change just better UI:

Add "not" button to Compendium Browser filter tags

---

CHANGELOG.md
static/templates/actors/hazard/partials/sidebar.hbs

Fix regression in hazard initiative rolling

---

src/module/actor/character/data.ts
src/module/actor/character/document.ts
static/templates/actors/character/partials/strike.hbs

Remove checking of hands available for free-hand weapons

---

src/module/rules/rule-element/iwr/base.ts

Resolve injected properties in custom IWR definitions

---

src/module/actor/base.ts
src/module/system/settings/index.ts
src/scripts/config/index.ts
static/lang/en.json
static/templates/sidebar/encounter-tracker/config.hbs

- Massive damage
- Death effects
- Becoming a fine powder

Automate damage-based instant death

---

src/module/system/check/dialog.ts
src/module/system/damage/dialog.ts
src/styles/ui/_roll-modifiers-dialog.scss
static/lang/en.json
static/templates/chat/check-modifiers-dialog.hbs
static/templates/chat/damage/damage-modifier-dialog.hbs

Move always show dialog toggle from the header to the dialog body

---

src/styles/actor/_coinage.scss
src/styles/actor/_index.scss
src/styles/actor/_nav.scss
src/styles/actor/vehicle/_index.scss
static/templates/actors/character/sheet.hbs
static/templates/actors/vehicle/sheet.hbs
static/templates/actors/vehicle/tabs/inventory.hbs

Also update some tab icons to be consistent with PC sheet

Display total bulk in vehicle sheet inventory

---

src/module/actor/sheet/popups/manage-attack-proficiencies.ts

Restore removability of custom attack proficiencies

---

packs/equipment/candlecap.json

Add icon to Candlecap

---

src/module/actor/base.ts

Fix condition increasing when no value is passed

---

src/module/actor/base.ts

There's no rule stating how to calculate massive damage under the variant, but this seems like the best RAI for it.

Include max stamina when determining whether massive damage is taken

---

src/module/item/base/sheet/base.ts

Show secret text in item descriptions to GMs

---

packs/equipment/scarlet-queen.json
packs/equipment/songbirds-brush.json

Also fix light radius on Scarlet Queen and fix formatting

Add TokenLight to Songbird's Brush

---

packs/spells/purple-worm-sting.json

Fix Purple Worm Sting damage

---

packs/feats/ongoing-strategy.json
src/module/migration/migrations/879-devise-a-stratagem-and-friends.ts

Fix predicate in Ongoing Strategy feat

---

src/module/system/damage/formula.ts

The true fix for the Fatal Bug. We can revert the other fix after this.

Prevent side-effects for damage modifiers and dice

---

packs/equipment-effects/effect-silver-crescent-greater.json
packs/equipment-effects/effect-silver-crescent-lesser.json
packs/equipment-effects/effect-silver-crescent-moderate.json
packs/equipment/silver-crescent-greater.json
packs/equipment/silver-crescent-lesser.json
packs/equipment/silver-crescent-moderate.json

Also fix Secondary Effect action cost and add silver to damage traits

Add effects for Silver Crescent

---

packs/kingmaker-bestiary/the-first-faithful.json

Also reorder Worm Jaws damage partials
Closes https://github.com/foundryvtt/pf2e/issues/11133

Fix physical resistance exception for The First Faithful

---

src/module/item/spell/data.ts
src/module/item/spell/document.ts
static/lang/en.json
static/templates/chat/spell-card.hbs

This was originally done for the purpose of displaying in the spell list, but I think for now I'm going to abstrain from doing that as a feature. So I stripped it out from the current ongoing work as its own thing.

Refactor spell area labels

---

src/module/actor/sheet/item-summary-renderer.ts
static/templates/actors/partials/item-summary.hbs

Add button to place template in spell item summary

---

static/system.json

Also expand system title to "Pathfinder Second Edition" (Paizo's preferred unabbreviated spelling)

Bump verified core compatibility version to 11.315

---

packs/spells/wronged-monks-wrath.json

Closes https://github.com/foundryvtt/pf2e/issues/11157

Fix single action damage for Wronged Monk's Wrath

---

packs/action-macros/reposition-athletics.json
src/module/system/action-macros/athletics/reposition.ts
src/module/system/action-macros/index.ts
static/lang/action-en.json

Add Reposition action implementation, action item, and action macro

---

src/scripts/config/traits.ts
static/lang/kingmaker-en.json

The removed traits are army save types.

Add kingmaker army type trait descriptions

---

src/global.ts
src/module/actor/character/feats.ts
src/module/item/class/document.ts
src/module/migration/migrations/880-split-show-dialogs-setting.ts
src/module/system/settings/variant-rules.ts
static/lang/en.json
static/templates/system/last-stop-message.hbs
static/templates/system/settings/variant-rules.hbs

Also remove "last stop before remaster" message

Drop dual class and ancestry paragon variants

---

src/module/actor/base.ts
src/module/actor/creature/sheet.ts
src/module/item/base/document.ts
src/module/item/kit/sheet.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/collection.ts
src/module/item/spellcasting-entry/document.ts
types/foundry/common/abstract/document.d.ts

Account for `Document#update` returning `undefined`

---

src/module/item/consumable/spell-consumables.ts
src/module/item/consumable/types.ts
src/scripts/config/traits.ts

Include all traits in scrolls/wands generated from spells

---

src/module/migration/migrations/882-spell-data-reorganization.ts

Retested on unmigrated compendium JSON

Reduce type coercion in migration 882

---

packs/agents-of-edgewatch-bestiary/clockwork-chopper.json
packs/agents-of-edgewatch-bestiary/mr-snips.json
packs/agents-of-edgewatch-bestiary/pulping-golem.json
packs/spells/cinder-swarm.json

Issues to be solved: 
https://github.com/foundryvtt/pf2e/issues/11171 - Cinder Swarm data error
https://github.com/foundryvtt/pf2e/issues/10838 - Errors in Agents of Edgewatch Monsters

Remove incorrect elite adjustments from compendium NPCs

---

packs/spells/final-sacrifice.json

Issue:
https://github.com/foundryvtt/pf2e/issues/10684

Add 20ft emanation to Final Sacrifice

---

packs/hazards/poisonous-mold.json

Add Floating Spores to Poisonous Mold

---

packs/equipment-effects/effect-alloy-orb-exquisite-high-grade.json
packs/equipment-effects/effect-alloy-orb-exquisite-standard-grade.json
packs/equipment-effects/effect-alloy-orb-high-grade.json
packs/equipment-effects/effect-alloy-orb-low-grade.json
packs/equipment-effects/effect-alloy-orb-standard-grade.json
packs/equipment/alloy-orb-exquisite-high-grade.json
packs/equipment/alloy-orb-exquisite-standard-grade.json
packs/equipment/alloy-orb-high-grade.json
packs/equipment/alloy-orb-low-grade.json
packs/equipment/alloy-orb-standard-grade.json
src/scripts/config/index.ts
static/lang/en.json

Also add Affixed to a Metal Weapon usage

Add effects for Alloy Orb

---

static/lang/action-en.json

Update the text to reflect the text in Player Core, and add links to the High Jump and Long Jump actions.

Add remaster changes to leap action implementation

---

packs/classfeatures/antipaladin.json
packs/classfeatures/champions-code.json
packs/classfeatures/desecrator.json
packs/classfeatures/liberator.json
packs/classfeatures/paladin.json
packs/classfeatures/redeemer.json
packs/classfeatures/the-tenets-of-evil.json
packs/classfeatures/the-tenets-of-good.json
packs/classfeatures/tyrant.json
packs/iconics/seelah-level-1.json
packs/iconics/seelah-level-5.json
static/lang/re-en.json

(and refresh the Seelahs again)

Update text of champion tenets and causes

---

src/module/scene/token-document/document.ts
types/foundry/client/data/documents/token-document.d.ts

Fix default token config with stamina variant

---

packs/spells/wave-of-despair.json

Closes https://github.com/foundryvtt/pf2e/issues/11204

Fix heightened area for Wave of Despair

---

packs/spells/shifting-sand.json

Closes https://github.com/foundryvtt/pf2e/issues/11194

Fix defense for Shifting Sand

---

packs/spells/swamp-of-sloth.json

Closes https://github.com/foundryvtt/pf2e/issues/11175

Fix defense for Swamp of Sloth

---

src/module/item/consumable/spell-consumables.ts

Originally added with https://github.com/foundryvtt/pf2e/pull/6522

Do not emphasize spell link when creating consumable from spell

---

src/module/system/text-editor.ts

...and don't do heightening checks on unowned items.

Handle inline damage rolls that fail to resolve

---

src/module/system/text-editor.ts

Resolves https://github.com/foundryvtt/pf2e/issues/10571

Support dragdrop of inline @Damage persistent damage

---

src/module/actor/base.ts

Add support for using token marks on origins

---

src/module/actor/creature/document.ts

Add the holy/unholy trait to sanctified actions/spells

---

packs/deities/atheism.json

Insert joke dunking on dawkins here.

Fix typo in atheism

---

packs/spell-effects/spell-effect-spirit-sense.json
packs/spells/spirit-sense.json

Issue:
https://github.com/foundryvtt/pf2e/issues/10951

Create Spirit Sense Spell Effect

---

packs/equipment-effects/effect-skinstitch-salve.json

Issue: https://github.com/foundryvtt/pf2e/issues/10788

Fix missing RE on Skinstich Salve.

---

packs/backgrounds/feral-child.json

Issue: https://github.com/foundryvtt/pf2e/issues/10924

Add missing RE to Feral Child

---

packs/spells/confront-selves.json

Issue: https://github.com/foundryvtt/pf2e/issues/11172

Change save from Confront Selves to Basic

---

static/templates/actors/actions/base/chat-message-content.hbs
static/templates/actors/actions/simple/chat-message-flavor.hbs
static/templates/actors/character/partials/strike.hbs

Fix tooltips in strike summaries and action macro cards

---

src/module/actor/modifiers.ts
src/module/chat-message/data.ts
src/module/chat-message/roll-inspector.ts
src/module/system/damage/damage.ts
static/lang/en.json
static/templates/chat/roll-inspector.hbs

Fix roll inspector attempting to localize dice as modifiers

---

packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
packs/kingmaker-bestiary/ekundayo-level-1.json
packs/kingmaker-bestiary/ekundayo-level-6.json
packs/kingmaker-bestiary/jubilost-level-1.json
packs/kingmaker-bestiary/jubilost-level-8.json
packs/kingmaker-bestiary/linzi-level-1.json
packs/kingmaker-bestiary/linzi-level-7.json
packs/kingmaker-bestiary/nok-nok-level-1.json
packs/kingmaker-bestiary/nok-nok-level-5.json
packs/kingmaker-bestiary/tristian-level-1.json
packs/kingmaker-bestiary/tristian-level-10.json
packs/kingmaker-bestiary/valerie-level-1.json
packs/kingmaker-bestiary/valerie-level-9.json

Add publication titles to all Kingmaker actors

---

packs/classfeatures/antipaladin.json
packs/classfeatures/deity-and-cause.json
packs/classfeatures/desecrator.json
packs/classfeatures/liberator.json
packs/classfeatures/paladin.json
packs/classfeatures/redeemer.json
packs/classfeatures/the-tenets-of-evil.json
packs/classfeatures/the-tenets-of-good.json
packs/classfeatures/tyrant.json
packs/feats/champion-dedication.json
static/lang/re-en.json

Have Champion Dedication grant Deity & Cause and Champion's Code

---

src/module/actor/creature/sheet.ts
src/module/actor/creature/spell-preparation-sheet.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/loader.ts
src/module/apps/compendium-browser/tabs/action.ts
src/module/apps/compendium-browser/tabs/base.ts
src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/campaign-feature.ts
src/module/apps/compendium-browser/tabs/data.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/compendium-browser/tabs/feat.ts
src/module/apps/compendium-browser/tabs/hazard.ts
src/module/apps/compendium-browser/tabs/spell.ts
src/styles/packs/_tab.scss
src/util/misc.ts
static/lang/en.json
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/partials/spell-collection.hbs
static/templates/actors/spell-preparation-sheet.hbs
static/templates/compendium-browser/partials/spell.hbs

Fix several spell browser regressions from data refactor

---

src/module/system/settings/homebrew/menu.ts
src/scripts/hooks/i18n-init.ts
src/scripts/hooks/index.ts
src/scripts/hooks/init.ts
static/lang/en.json

Automatically create versatile weapon traits from homebrew damage types

---

src/module/item/spell/document.ts
src/module/migration/migrations/887-redirect-spell-links.ts
types/foundry/common/documents/journal-entry-page.d.ts

Also prevent an error in migration 887

Move error suppression of pre-migration spell data to better location

---

packs/classfeatures/rogue-resilience.json

Update Rogue Resilience to upgrade Fortitude instead of Reflex

---

packs/classfeatures/anathema-druid.json

Add Atone ritual link in Druid Anathema description

---

packs/spell-effects/spell-effect-untamed-shape.json

Fix Untamed Shape precidate

---

packs/equipment/staff-of-the-dead-greater.json
packs/equipment/staff-of-the-dead-major.json
packs/equipment/staff-of-the-dead.json

Thanks to qwertthewert on Discord for report.

Remove identify bonus from Staff of the Dead

---

packs/classfeatures/fourth-gates-threshold.json
packs/classfeatures/gates-threshold.json
packs/classfeatures/kinetic-gate.json
packs/classfeatures/second-gates-threshold.json
packs/classfeatures/third-gates-threshold.json
src/module/migration/migrations/892-choice-re-adjust-name-value.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

#11242 changed `adjustName` to a `StrictBooleanField`

Migrate non-boolean `adjustName` values in choice set REs

---

packs/feats/untamed-form.json

Fix Untamed Form feat

---

packs/spells/holy-light.json
packs/spells/moonlight-ray.json

Add Holy trait to Holy Light and Moonlight Ray spells

---

packs/spells/mindlink.json

Closes https://github.com/foundryvtt/pf2e/issues/11475

Add arcane to Mindlink traditions

---

packs/spells/clear-mind.json

Closes https://github.com/foundryvtt/pf2e/issues/11471

Fix traits for Clear Mind

---

packs/feats/initiate-warden.json

Closes https://github.com/foundryvtt/pf2e/issues/11483

Fix Initiate Warden's link to Heal Companion

---

packs/feats/elven-weapon-familiarity.json

Add links to weapon names in Elven Weapon Familiarity feat

---

packs/feat-effects/stance-everstand-stance.json

Fixes https://github.com/foundryvtt/pf2e/issues/11528

Fix RE on Everstand Stance Effect to Increase Hardness

---

packs/feat-effects/effect-restorative-strike.json
packs/feats/elven-weapon-familiarity.json
packs/feats/restorative-strike.json

Also remove extra space from Elven Weapon Familiarity

Add effect for Restorative Strike

---

packs/feats/communal-crafting.json

Closes https://github.com/foundryvtt/pf2e/issues/11527

Add Communal Crafting feat

---

packs/actions/reposition.json

Closes https://github.com/foundryvtt/pf2e/issues/11552

Add attack trait to Reposition

---

packs/feats/unusual-treatment.json

Closes https://github.com/foundryvtt/pf2e/issues/11556

Add Unusual Treatment feat

---

packs/equipment/indestructible-shield.json

Closes https://github.com/foundryvtt/pf2e/issues/11567

Fix hardness and HP of Indestructible Shield

---

packs/feats/additional-lore.json

Fixes https://github.com/foundryvtt/pf2e/issues/11571.

Allow Additional Lore to be Selected Multiple Times

---

packs/feat-effects/effect-raise-symbol.json
packs/feats/raise-symbol.json

Closes https://github.com/foundryvtt/pf2e/issues/11499

Add effect for Raise Symbol

---

src/module/chat-message/data.ts
src/module/chat-message/document.ts
src/module/item/spell/document.ts
static/templates/chat/spell-card.hbs

Fix rolling damage from spell consumables

---

packs/heritages/skilled-heritage.json
packs/iconics/ezren-level-1.json
packs/iconics/ezren-level-3.json
packs/iconics/ezren-level-5.json

Also update Cooperative Nature feat, use identical core icon for Skilled Heritage

Apply Ezren's Skilled Heritage increase to crafting

---

src/module/system/action-macros/performance/perform.ts

Set default opposing statistic in Perform action to will

---

packs/feats/swaggering-initiative.json

Closes https://github.com/foundryvtt/pf2e/issues/11014

Add toggle to Swaggering Initiative

---

packs/spells/charm.json
packs/spells/invisibility.json
packs/spells/subconscious-suggestion.json

Closes https://github.com/foundryvtt/pf2e/issues/11609

Add subtle trait to Charm, Invisibility, and Subconscious Suggestion

---

packs/paizo-pregens/kangir.json

Was the only use of "domain": "speed" in the system

Refresh Kangir's Unburdened Iron

---

packs/classfeatures/deity.json
packs/feats/cleric-dedication.json
packs/npc-gallery/antipaladin.json

Have Cleric Dedication grant Deity class feature

---

packs/feats/words-of-unraveling.json

Closes https://github.com/foundryvtt/pf2e/issues/11612

Fix level of Words of Unraveling

---

packs/iconics/ezren-level-1.json

Change Ezren's Skilled Heritage Skill to Society

---

packs/feats/elemental-shape.json

Closes https://github.com/foundryvtt/pf2e/issues/11639

Fix Elemental Shape to use new unified Spell Effect: Elemental Form

---

packs/familiar-abilities/familiar-of-balanced-luck.json
packs/familiar-abilities/familiar-of-flowing-script.json
packs/familiar-abilities/familiar-of-freezing-rime.json
packs/familiar-abilities/familiar-of-keen-senses.json
packs/familiar-abilities/familiar-of-ongoing-misery.json
packs/familiar-abilities/familiar-of-restored-spirit.json
packs/familiar-abilities/familiar-of-stalking-night.json

Closes https://github.com/foundryvtt/pf2e/issues/11449

Add Witch Patron Familiar Abilities

---

packs/feats/blade-brake.json

Closes https://github.com/foundryvtt/pf2e/issues/11643

Change Blade Brake to a Reaction

---

build/run-migration.ts
packs/feat-effects/effect-curse-of-outpouring-life.json
packs/feats/harming-hands.json
packs/feats/healing-hands.json
packs/feats/unusual-treatment.json
packs/iconics/kyra-level-3.json
packs/iconics/kyra-level-5.json
packs/kingmaker-bestiary/tristian-level-10.json
packs/paizo-pregens/eteleon.json
packs/paizo-pregens/lavanna-saltspray.json
src/module/item/spell/document.ts
src/module/migration/migrations/896-healing-domains.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

Also adjust some compendium REs to utilize it

Include a "healing" domain for healing spells

---

packs/classes/wizard.json
packs/classfeatures/school-of-unified-magical-theory.json
static/lang/re-en.json

Localize prompt in Unified Magical Theory choice set

---

packs/actions/destructive-vengeance.json
packs/actions/iron-command.json
packs/actions/selfish-shield.json

Closes https://github.com/foundryvtt/pf2e/issues/11656

Fix unholy champion reaction damage and include auto-heightening damage links

---

packs/feats/inventor.json

Update Inventor Feat to PC1

---

src/module/actor/data/iwr.ts

Adjust magical IWR to inspect action traits in addition to item traits

---

src/module/item/heritage/document.ts

Prevent granted heritages from overriding PCs' main heritages 

---

src/module/item/armor/sheet.ts
static/templates/items/weapon-sidebar.hbs

Also remove extra inclusion of `CONFIG.PF2E.bulkTypes` in `ArmorSheetPF2e`

Remove "equipped bulk" from weapon sheet

---

packs/classfeatures/untamed-order.json

Closes https://github.com/foundryvtt/pf2e/issues/11724

Fix predicate for Untamed Order granting intimidation

---

packs/stolen-fate-bestiary/speaker-of-svaryr.json

Closes https://github.com/foundryvtt/pf2e/issues/11726

Fix Speaker Of Svaryr's regeneration and fix attack traits

---

packs/classfeatures/rogue-resilience.json

Fix Rogue Resilience note selector

---

src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/module/actor/army/values.ts
src/module/actor/party/kingdom/sheet.ts
src/module/actor/vehicle/sheet.ts
src/module/sheet/helpers.ts
src/scripts/handlebars.ts
src/scripts/register-sheets.ts
src/styles/actor/_index.scss
src/styles/actor/army/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/army/gear-card.hbs
static/templates/actors/army/sheet.hbs

Adapted from Cora's old army sheet code. The empty space in the localization marks the old localization keys I haven't adapted to our naming convention yet.

Start on army sheet

---

packs/equipment/aeon-stone-envisioning.json
packs/equipment/aeon-stone-pearlescent-pyramid.json
packs/equipment/aeon-stone-peering.json
packs/equipment/aeon-stone-preserving.json
packs/equipment/aeon-stone-smoothing.json
packs/equipment/aeon-stone-sprouting.json

Also remove unnecessary definition predicate and clean up description
Closes https://github.com/foundryvtt/pf2e/issues/11708

Fix usage of and bulk of some aeon stones

---

packs/actions/refocus.json

update text of refocus action to remaster text

Update Refocus action text to remaster

---

packs/bestiary-effects/effect-challenge-foe.json
packs/pathfinder-bestiary-3/einherji.json
packs/stolen-fate-bestiary/svaryr-soldier.json
static/lang/en.json

Also improve automation for Einherji's Jotun Slayer
Closes https://github.com/foundryvtt/pf2e/issues/11727

Add automation for Challenge Foe

---

packs/equipment/jeweled-dawnsilver-crown.json
packs/rollable-tables/major-art-object.json

Closes https://github.com/foundryvtt/pf2e/issues/11751

Update name of Jeweled dawnsilver crown

---

packs/feats/forager.json
static/lang/re-en.json

Closes https://github.com/foundryvtt/pf2e/issues/11740

Add degree of success automation to Forager and localize note

---

src/module/canvas/measured-template.ts

[burst-snap.webm](https://github.com/foundryvtt/pf2e/assets/41452412/40dc5a4d-935e-40a5-b3a3-f8d9f9e7e642)

Snap burst templates to grid intersections

---

packs/equipment/duskwood-violin-by-a-legend.json
packs/rollable-tables/major-art-object.json

Closes https://github.com/foundryvtt/pf2e/issues/11754

Update name of Duskwood violin by a legend

---

build/run-migration.ts
src/module/item/class/data.ts
src/module/item/class/document.ts
src/module/migration/migrations/900-class-spellcasting-proficiency.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/ae-like.ts
src/scripts/config/traits.ts
src/styles/item/_abc-sheet.scss
src/styles/item/_index.scss
static/lang/en.json
static/template.json
static/templates/actors/character/attribute-builder.hbs
static/templates/actors/character/sheet.hbs
static/templates/items/class-details.hbs
static/templates/items/sheet.hbs

Also spruce up class sheet with fieldsets

Add property to class items to indicate initial spellcasting proficiency

---

packs/equipment/morphing-weapon.json
src/module/item/physical/usage.ts
src/scripts/config/index.ts
static/lang/en.json

Closes https://github.com/foundryvtt/pf2e/issues/11765

Update Usage of Morphing Weapon

---

packs/kingmaker-features/army-conditions/concealed.json
packs/kingmaker-features/army-conditions/fortified.json
packs/kingmaker-features/army-conditions/mired.json
packs/kingmaker-features/army-conditions/outflanked.json
packs/kingmaker-features/army-conditions/routed.json
packs/kingmaker-features/army-conditions/shaken.json
packs/kingmaker-features/army-conditions/weary.json
packs/kingmaker-features/army-tactics/hold-the-line.json
src/module/actor/army/data.ts
src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/module/rules/rule-element/base.ts
src/module/sheet/helpers.ts
src/styles/actor/army/_index.scss
src/styles/journal.scss
static/lang/kingmaker-en.json
static/template.json
static/templates/actors/army/sheet.hbs

Also adds a better = higher/lower param to the adjustment class helper

Add basic army rule element support and fix minor bugs

---

src/module/item/base/sheet/rule-element-form/base.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/crit-spec.ts
src/module/rules/rule-element/flat-modifier.ts
src/module/rules/rule-element/multiple-attack-penalty.ts
src/module/rules/rule-element/substitute-roll.ts
src/module/rules/rule-element/temp-hp.ts
src/module/rules/rule-element/token-effect-icon.ts
src/module/rules/rule-element/token-light.ts
src/module/system/schema-data-fields.ts

Also tweak error language in some REs to be in the data model validation failure style

Convert late-occurring RE validation failures to `DataModel` failures

---

packs/feats/channel-smite.json

removed in Player Core reprint

Remove channel smite prerequisite

---

packs/equipment/charm-of-resistance-greater.json
packs/equipment/charm-of-resistance-major.json
packs/equipment/charm-of-resistance.json
src/module/rules/rule-element/choice-set/data.ts
src/module/rules/rule-element/choice-set/rule-element.ts
static/lang/re-en.json

Add support for format strings in ChoiceSet name adjustments

---

src/module/actor/base.ts
src/module/actor/character/data.ts
src/module/actor/character/sheet.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/rituals.ts
src/module/item/spellcasting-entry/trick.ts
src/module/item/spellcasting-entry/types.ts
src/module/migration/migrations/900-class-spellcasting-proficiency.ts
src/styles/actor/character/_proficiencies.scss
src/styles/actor/character/_proficiency-ranks.scss
static/lang/en.json
static/templates/actors/character/partials/proficiencylevels-dropdown.hbs
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/character/tabs/proficiencies.hbs
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/items/class-details.hbs

Also move display of spellcasting rank in proficiencies tab to own subsection

Update spellcasting entries to change proficiency ranks

---

src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/battle-form/types.ts

Allow BattleForm RE strikes to be predicated

---

src/module/actor/army/data.ts
src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/styles/actor/army/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/army/sheet.hbs

Still not done yet but visibly its starting to shape up at least

Support army potency updates and fix ac/scouting adjustments

---

packs/classfeatures/third-doctrine-warpriest.json

Upgrade martial proficiency to expert in Warpriest's Third Doctrine

---

src/module/rules/rule-element/token-image.ts

Make TokenImageRuleElement#alpha nullable and defaulting to `null`

---

src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/styles/actor/army/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/army/sheet.hbs

Tooltips will be fixed later. Also adds support for potion/ammunition pip updates and hp clamping

Add army styling updates and fixes

---

src/module/canvas/layer/template.ts
src/module/canvas/measured-template.ts
src/module/chat-message/listeners/cards.ts
src/module/item/spell/document.ts
src/scripts/ui/inline-roll-links.ts

Also limit grid snapping to highlights and final template drop

Move `MeasuredTemplate` preview handling to `TemplateLayerPF2e`

---

src/module/actor/character/document.ts

Broke by https://github.com/foundryvtt/pf2e/pull/11742

Fix adding kits to actors

---

src/module/actor/army/data.ts
src/module/actor/army/sheet.ts
static/lang/kingmaker-en.json
static/template.json
static/templates/actors/army/sheet.hbs

and consumption adjusted value and teeny localization

Add army recruitment dc

---

packs/equipment/serithtial.json
static/lang/re-en.json

Depends on https://github.com/foundryvtt/pf2e/pull/11868 for the RollOption label.

Add automation for Serithtial

---

packs/iconics/kyra-level-1.json

These were somehow showing as a _heal_ spell; not sure how that happened. Closes https://github.com/foundryvtt/pf2e/issues/11934

Refresh Rations on Level 1 Kyra

---

src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/styles/actor/army/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/army/sheet.hbs

Add rudimentary support for army alliance

---

src/module/canvas/layer/template.ts

Fix excessive grid-snapping for some shape types

---

packs/equipment/druids-crown.json

Also clean up description
Closes https://github.com/foundryvtt/pf2e/issues/11959

Fix bulk and usage of Druid's Crown

---

src/module/item/armor/sheet.ts
src/module/item/physical/document.ts
src/module/item/physical/helpers.ts
src/module/item/physical/sheet.ts
src/module/rules/rule-element/item-alteration/alteration.ts
src/module/sheet/helpers.ts
src/styles/item/_index.scss
static/lang/en.json
static/templates/items/backpack-details.hbs
static/templates/items/physical-sidebar.hbs
static/templates/items/sheet.hbs

Prevent bulk and size adjustments from saving upon closing item sheets

---

packs/kingmaker-features/army-tactics/toughened-soldiers.json
src/module/actor/army/sheet.ts
static/templates/actors/army/sheet.hbs

...and automated toughened soldiers

Sort army saves and move strike strike before buttons

---

src/module/actor/character/sheet.ts

Don't throw error on PC sheet when navigation panel isn't found

---

src/scripts/macros/treat-wounds.ts

Use new Magic Hands rules

---

src/module/item/container/document.ts
static/templates/actors/partials/item-line.hbs

Declare containers over capacity only when over 100% full in Bulk units

---

packs/feat-effects/stance-assume-earths-mantle.json

This seems to work, but I totally understand if it needs to be cleaned up or isn't in the right place etc. Please let me know what can be fixed or where this might actually need to go if it's not here. 
Stolen/adapted from https://discord.com/channels/880968862240239708/880969253765935174/1166941805535842324 with appreciation.

Add strength modifier addition/upgrade to Assume Earth's Mantle stance

---

src/module/system/damage/damage.ts
src/module/system/damage/helpers.ts
src/module/system/damage/roll.ts
src/module/system/damage/terms.ts
types/foundry/client/roll.d.ts

Track simplified roll terms that have been doubled

---

static/templates/items/heritage-sidebar.hbs

Fix tooltip in heritage sidebar

---

src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/styles/actor/army/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/army/sheet.hbs

Implement army potion consumption

---

packs/feat-effects/effect-precise-debilitations.json
packs/feats/bloody-debilitation.json
packs/feats/critical-debilitation.json
packs/feats/eldritch-debilitations.json
packs/feats/methodical-debilitations.json
packs/feats/precise-debilitations.json
packs/feats/tactical-debilitations.json
packs/feats/vicious-debilitations.json
static/lang/re-en.json

Also remove all the old note REs from debilitations.

Add effect for precise debilitations

---

src/styles/_colors.scss
src/styles/_reset.scss
src/styles/actor/character/_proficiency-ranks.scss
src/styles/actor/npc/_index.scss
src/styles/item/_header.scss
src/styles/item/_index.scss
src/styles/item/_rules.scss
src/styles/item/_sidebar.scss

Use common color and height for item-sheet form fields

---

src/module/rules/rule-element/ae-like.ts
src/module/rules/rule-element/grant-item/rule-element.ts

(if in-memory-only)
Also, fix AE-like logging

Relax prohibition of GrantItem REs from being on physical items

---

packs/feats/in-tune.json

Closes https://github.com/foundryvtt/pf2e/issues/12076

Fix traits and action cost of In Tune

---

static/templates/items/sheet.hbs

Fix broken template introduced in https://github.com/foundryvtt/pf2e/pull/12092

Fix item sheet nav

---

packs/classfeatures/final-doctrine-warpriest.json

Closes https://github.com/foundryvtt/pf2e/issues/12087

Upgrade favored weapon proficiency to master in Warpriest's Final Doctrine

---

packs/equipment/sapling-shield-greater.json
packs/equipment/sapling-shield-lesser.json
packs/equipment/sapling-shield-major.json
packs/equipment/sapling-shield-minor.json
packs/equipment/sapling-shield-moderate.json
packs/equipment/sapling-shield-true.json

Also switch to using itemId rather than adding to predicate

Modify Sapling Shield bulk when activated

---

packs/season-of-ghosts-bestiary/kagekuma.json
packs/spells/rewrite-memory.json

Fix source of Rewrite Memory

---

packs/equipment/wand-of-dazzling-rays-3rd-level.json
packs/equipment/wand-of-dazzling-rays-4th-level.json
packs/equipment/wand-of-dazzling-rays-5th-level.json
packs/equipment/wand-of-dazzling-rays-6th-level.json
packs/equipment/wand-of-dazzling-rays-7th-level.json
packs/equipment/wand-of-dazzling-rays-8th-level.json
packs/equipment/wand-of-dazzling-rays-9th-level.json
static/lang/re-en.json

Also clean up description and add icon

Add light automation for Wand of Dazzling Rays

---

src/module/actor/army/data.ts
src/module/actor/army/document.ts
src/styles/actor/army/_index.scss
static/templates/actors/army/sheet.hbs

No RBV though. That would be more involved I think.

Add senses to army

---

packs/kingmaker-features/army-war-actions-tactical/all-out-assault.json
src/module/actor/army/document.ts
src/module/rules/rule-element/fast-healing.ts

Damage synthetics turned out not to be necessary but if I already did the work might as well put it up

Add inline buttons to all out assault, extract army damage mods and allow fast healing

---

src/styles/actor/_spell-collection.scss
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/partials/spell-collection.hbs

Also set data-tooltip class where appropriate

Fix showing empty slot in spell-less focus entry

---

src/module/actor/character/sheet.ts
src/styles/actor/character/_proficiencies.scss
static/templates/actors/character/tabs/general.hbs

Move more PC-sheet listeners to global listener

---

packs/feats/gang-up.json
src/module/actor/data/base.ts
src/module/canvas/token/object.ts
src/module/migration/migrations/908-true-gang-up.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

did my best in reading everything and handling it appropriately.

Update Gang Up flanking rules for Remaster

---

packs/equipment/astral-greater.json
packs/equipment/astral.json

Also brush up descriptions.
Closes https://github.com/foundryvtt/pf2e/issues/12188

Fix level and price of Greater Astral rune

---

src/module/actor/sheet/base.ts
src/module/chat-message/helpers.ts
src/module/item/base/document.ts
src/scripts/sheet-util.ts

Determine roll mode from user input when sending self-effect message

---

packs/feats/bardic-lore.json
packs/feats/know-it-all-bard.json

Also add Recall Knowledge link to Bardic Lore

Use system description for Note for Know-It-All (Bard) and add outcomes

---

src/styles/actor/hazard/_index.scss
src/styles/actor/hazard/_sidebar.scss
static/templates/actors/hazard/sheet.hbs

and fonts in the header trait selection

Fix regression with hazard item summaries

---

src/module/actor/sheet/item-summary-renderer.ts

Preparatory work to have certain items be just sheet data.

Move item summary item retrieval to method

---

src/module/actor/army/document.ts
src/module/actor/army/sheet.ts
src/module/actor/creature/spell-preparation-sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/item-summary-renderer.ts
static/lang/kingmaker-en.json
static/templates/actors/army/sheet.hbs

Data cleanse and updates later, since TMun has something up currently.

Import basic war actions as synthetic items in the sheet

---

packs/conditions/stupefied.json

Closes https://github.com/foundryvtt/pf2e/issues/12212

Add inline flat check to Stupefied and update to remaster

---

packs/classfeatures/ash.json

Limit Ash Mystery benefit to Oracle class only

---

packs/feats/conceal-spell.json

Remove Manipulate trait from Conceal Spell feat

---

src/module/item/armor/sheet.ts
src/module/item/weapon/sheet.ts
src/styles/item/_index.scss
static/lang/en.json
static/templates/items/armor-details.hbs
static/templates/items/weapon-details.hbs

Fix selectability of weapon and armor property runes

---

src/module/item/spell/document.ts

Closes https://github.com/foundryvtt/pf2e/issues/12235

Fix certain innate spells being stuck at null uses

---

src/module/actor/npc/sheet.ts

Fix click handler for NPC attack generation

---

src/module/actor/sheet/base.ts

Closes https://github.com/foundryvtt/pf2e/issues/12231

Fix inventory drag/drop to tokens and other sheets

---

src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/styles/actor/_inventory.scss
static/templates/actors/partials/inventory.hbs
static/templates/actors/partials/item-line.hbs

Fix inventory looting by players

---

src/module/actor/character/document.ts

Fix application of handwrap runes to synthetic unarmed attacks

---

static/lang/en.json
static/templates/actors/partials/item-line.hbs
static/templates/chat/consumable-card.hbs

(and the message in the consumable's use button)

Fix display of wand charges in inventory

---

packs/spells/gouging-claw.json

Update gouging claw damage for remaster

---

src/util/dom.ts

Fix using wands from actor sheets

---

src/module/item/spell/document.ts

Minor grievances found while poking in here

Have Spell#traditions always show valid traditions

---

packs/feat-effects/effect-precise-debilitations.json

Change timing of Effect: Precise Debilitations to End of Turn

---

src/module/actor/data/iwr.ts

Fix definition of unholy IWR

---

packs/equipment/keep-stone-chunk.json
packs/equipment/keep-stone-ingot.json

Add Keep Stone Ingot and Chunk

---

packs/spells/whirlpool.json

Also clean up description
Closes https://github.com/foundryvtt/pf2e/issues/12324

Add Reflex defense to Whirlpool

---

packs/feats/witchs-armaments.json
static/lang/re-en.json

Fix maxTakable
Predicate choices
Add icons to choices and strikes
Localize
Fix publication

Update Witch's Armaments

---

src/module/actor/base.ts

Set actor signatures after data model initialization

---

src/module/item/weapon/document.ts

Keep RE-carrying ammunition linked to weapons even at zero quantity

---

src/module/item/spell/sheet.ts

Fix creation of fixed-heightening base damage data

---

src/module/actor/helpers.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts

Remove second application of strike-damage modifier adjustments

---

src/module/actor/sheet/base.ts
src/styles/actor/sidebar/_index.scss
src/styles/ui/_hover.scss
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/vehicle/sidebar.hbs

Move character/vehicle IWR edit buttons to heading

---

packs/feat-effects/effect-elementalist-dedication.json

Fix elementalist dedication effect for wood and metal

---

packs/iconics/feiya-level-1.json
packs/iconics/feiya-level-5.json
packs/pfs-season-4-bestiary/witch-of-the-owl.json
packs/rage-of-elements-bestiary/jaathoom-shuyookh.json
packs/sky-kings-tomb-bestiary/ulat-kini-mindreaver.json
packs/spell-effects/spell-effect-ill-omen.json
packs/spells/ill-omen.json
packs/stolen-fate-bestiary/fabled-harrowkin.json
packs/stolen-fate-bestiary/raven-nicoletta.json
packs/stolen-fate-bestiary/the-betrayal.json
packs/stolen-fate-bestiary/the-courtesan.json
packs/stolen-fate-bestiary/the-cricket.json
packs/stolen-fate-bestiary/the-crows.json
packs/stolen-fate-bestiary/the-dance.json
packs/stolen-fate-bestiary/the-fool.json
packs/stolen-fate-bestiary/the-inquisitor.json
packs/stolen-fate-bestiary/the-joke.json
packs/stolen-fate-bestiary/the-peacock.json
packs/stolen-fate-bestiary/the-queen-mother.json
packs/stolen-fate-bestiary/the-teamster.json
packs/stolen-fate-bestiary/the-trader.json
packs/stolen-fate-bestiary/the-twin.json
packs/stolen-fate-bestiary/the-unicorn.json
packs/stolen-fate-bestiary/the-wanderer.json
packs/stolen-fate-bestiary/the-winged-serpent.json
packs/strength-of-thousands-bestiary/golgopo.json

Add spell effect for Ill Omen

---

src/module/actor/base.ts

fixes https://discord.com/channels/170995199584108546/1065764070680186930/1186220781873668166

fix error message when unowned tokens heal from 0 HP

---

src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/module/actor/sheet/helpers.ts
src/styles/actor/_inventory.scss
src/styles/actor/_loot.scss
src/styles/actor/character/_inventory.scss
static/lang/en.json
static/templates/actors/partials/inventory.hbs
static/templates/actors/partials/item-line.hbs

Display unit bulk in inventory sheets

---

packs/actions/long-jump.json
packs/spells/tempest-surge.json

https://paizo.com/pathfinder/faq
Also fix missing space in Tempest Surge

Update Long Jump with PC1 errata

---

packs/kingmaker-bestiary/primal-bandersnatch.json

Also fix Claws reach and missing Pain to Quill
Closes https://github.com/foundryvtt/pf2e/issues/12406

Fix Primal Bandersnatch damage

---

packs/spell-effects/spell-effect-rejuvenating-flames.json
packs/spells/rejuvenating-flames.json

Closes https://github.com/foundryvtt/pf2e/issues/12405

Update Rejuvenating Flames healing link to autoleveling

---

src/module/item/physical/helpers.ts

Calculate material'd or runed armor/weapon/shield price from base of zero

---

src/scripts/sheet-util.ts

Fix `eventToRollMode`

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/styles/actor/character/_proficiencies.scss
src/styles/actor/character/_proficiency-ranks.scss
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/character/tabs/proficiencies.hbs
static/templates/actors/party/kingdom/tabs/activities.hbs

Move class dcs to proficiencies tab and shorten skills

---

packs/deities/atreia.json
packs/deities/ferrumnestra.json
packs/deities/kelizandri.json
packs/deities/laudinmio.json
packs/deities/shumunue.json
packs/deities/verilorn.json

Fix sanctification options and domains on some ROE deities

---

packs/equipment/ferrofluid-urchin-greater.json
packs/equipment/ferrofluid-urchin-lesser.json
packs/equipment/ferrofluid-urchin-moderate.json

Fix formatting on the ferrofluid items

---

packs/fists-of-the-ruby-phoenix-bestiary/canopy-elder.json
packs/pathfinder-bestiary-3/arboreal-archive.json
packs/pathfinder-bestiary-3/arboreal-reaper.json

Fix missing spells in arboreals and canopy elder

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/styles/actor/_index.scss
src/styles/actor/_spell-collection.scss
src/styles/actor/_spell-preparation.scss
static/templates/actors/army/sheet.hbs
static/templates/actors/character/partials/feat-slot.hbs
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/character/tabs/effects.hbs
static/templates/actors/character/tabs/pfs.hbs
static/templates/actors/crafting-entry-alchemical.hbs
static/templates/actors/crafting-entry-list.hbs
static/templates/actors/hazard/sheet.hbs
static/templates/actors/identify-item.hbs
static/templates/actors/limited/npc-sheet.hbs
static/templates/actors/npc/partials/action.hbs
static/templates/actors/npc/partials/sidebar.hbs
static/templates/actors/partials/action.hbs
static/templates/actors/partials/effects.hbs
static/templates/actors/partials/item-line.hbs
static/templates/actors/partials/spell-collection.hbs
static/templates/actors/party/kingdom/tabs/activities.hbs
static/templates/actors/party/sheet.hbs
static/templates/actors/spell-preparation-sheet.hbs

Also:
- Move a few more independent listeners to global handler
- Try removing listener until matched handler resolves

Move item-to-chat listeners to global handler

---

static/templates/items/spell-details.hbs

Put ritual data in its own fieldset on spell sheet

---

src/styles/actor/character/_proficiencies.scss
static/templates/actors/character/tabs/proficiencies.hbs

Final point to turn back regarding the whole modifier buttons and clicking on modifiers thing.

Restore character skill modifier buttons

---

packs/abomination-vaults-bestiary/jafaki.json

Add items-only spellcasting entry to Jafaki (AV)

---

packs/classfeatures/flurry.json
packs/iconics/harsk-level-1.json
packs/iconics/harsk-level-5.json

Revert "Update Flurry Edge following official clarification"

---

packs/spells/nudge-fate.json

No longer a sustained spell
Thanks Oz (oswaldospn) on Discord.

Update Nudge Fate

---

src/module/actor/creature/sheet.ts
src/styles/_colors.scss
src/styles/actor/_index.scss
src/styles/actor/_spell-collection.scss
src/styles/actor/_spell-preparation.scss
src/styles/actor/character/_index.scss
src/styles/actor/character/_spellcasting.scss
src/styles/actor/npc/_spells.scss
src/styles/legacy/_pf2e.scss
src/styles/mixins/_frames.scss
static/lang/en.json
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/npc/tabs/spells.hbs
static/templates/actors/partials/spell-collection.hbs
static/templates/actors/spell-preparation-sheet.hbs
static/templates/actors/vehicle/tabs/actions.hbs
static/templates/items/partials/spell-description-prepend.hbs

Also cleanup styling of spell collections

Move most spell-collection listeners to global handler

---

packs/spells/touch-of-corruption.json

Link spell effect in Touch of Corruption

---

packs/feats/eternal-wings-nephilim.json
packs/feats/eternal-wings-sylph.json
packs/feats/heros-wings.json
packs/feats/mighty-wings.json

Fix Eternal Wings and add fly speed to Hero's and Mighty Wings

---

src/module/actor/modifiers.ts

Have `CheckModifier` only accept constructed `ModifierPF2e` objects

---

packs/equipment/thousand-blade-thesis.json

Convert Thousand Blade Thesis to Container

---

src/module/item/base/sheet/sheet.ts
src/styles/_tags.scss
src/styles/item/_effect-sheet.scss
src/styles/item/_index.scss
src/styles/item/_rules.scss
src/styles/item/_sidebar.scss
src/styles/item/_weapon-sheet.scss
static/templates/items/physical-sidebar.hbs
static/templates/items/rules-panel.hbs

Normalize styling across disabled form/anchor elements in item sheets

---

src/module/actor/creature/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/helpers.ts
src/module/chat-message/data.ts
src/module/chat-message/document.ts
src/module/chat-message/listeners/cards.ts
src/module/item/base/document.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/helpers.ts
src/module/item/spellcasting-entry/trick.ts
src/module/scene/measured-template-document.ts
src/scripts/system/dragstart-handler.ts

Also change remaining uses of `castLevel` to `castRank`

Restore retrieval of cast rank when sending spell to chat

---

src/module/actor/army/document.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/sheet.ts
src/styles/_colors.scss
src/styles/actor/party/kingdom/_features.scss
src/styles/actor/party/kingdom/_index.scss
src/styles/actor/party/kingdom/_world.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/tabs/main.hbs
static/templates/actors/party/kingdom/tabs/world.hbs

Automate kingdom army consumption and add consumption breakdown

---

packs/abomination-vaults-bestiary/observation-deck-seugathi-researcher.json
packs/abomination-vaults-bestiary/seugathi-guard.json
packs/abomination-vaults-bestiary/seugathi-reality-warper.json
packs/abomination-vaults-bestiary/seugathi-researcher.json
packs/abomination-vaults-bestiary/seugathi-servant.json

Add Magic Item Mastery spellcasting to Seugathi NPCs and refresh spells

---

src/module/item/base/sheet/rule-element-form/actor-traits.ts
src/module/item/base/sheet/rule-element-form/index.ts
static/lang/re-en.json
static/templates/items/rules/actor-traits.hbs

Add rule element form for actor traits

---

src/module/actor/character/sheet.ts
static/lang/en.json
static/templates/actors/character/tabs/feats.hbs

Add button to create bonus feat

---

src/styles/actor/_index.scss
src/styles/actor/character/_character.scss
src/styles/actor/hazard/_header.scss
src/styles/actor/npc/_index.scss
static/templates/actors/character/tabs/character.hbs
static/templates/actors/familiar-sheet.hbs
static/templates/actors/hazard/partials/header.hbs
static/templates/actors/limited/npc-sheet.hbs
static/templates/actors/loot/sidebar.hbs
static/templates/actors/npc/partials/sidebar.hbs
static/templates/actors/npc/simple-sheet.hbs
static/templates/actors/vehicle/tabs/details.hbs

and fix npc portrait borders being shown when they shouldn't.

Increase visibility of show image hover icon

---

src/module/actor/character/sheet.ts
src/styles/actor/character/_character.scss
static/templates/actors/character/tabs/character.hbs

Overlap deity icon over value

---

src/styles/legacy/_pf2e.scss

Make NPC sheet text/number inputs slightly more visible

---

src/module/system/action-macros/specialty-basic/avert-gaze.ts
src/module/system/action-macros/specialty-basic/burrow.ts

Fix action section for the avert gaze and burrow action objects

---

src/module/actor/character/sheet.ts
src/module/actor/party/sheet.ts
src/module/actor/sheet/helpers.ts
src/styles/actor/character/_character.scss
src/styles/actor/character/_sidebar.scss
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/character/tabs/character.hbs

Move PC senses to sidebar

---

packs/equipment/staff-of-healing-greater.json
packs/equipment/staff-of-healing-major.json
packs/equipment/staff-of-healing-true.json
packs/equipment/staff-of-healing.json

I went very specific on the predicate - item:slug:heal may be good enough? It works fine as is though.

Add REs for Staff of Healing bonus HP

---

src/module/actor/creature/sheet.ts
src/module/actor/sheet/base.ts
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/vehicle/tabs/actions.hbs

Also updates vehicle action headers to the simpler style used in pc sheets

Fix regression browsing abilities in PC downtime/exploration and vehicles

---

packs/feat-effects/effect-bon-mot-critical-success.json
packs/feat-effects/effect-bon-mot.json

Changed `You are distracted and takes` to `You are distracted and take`

Fix Grammar on Bon Mot Effects

---

src/module/actor/vehicle/sheet.ts
src/styles/actor/character/_actions.scss
src/styles/actor/tabs/_actions.scss
src/styles/actor/vehicle/_index.scss

And makes frequencies usable period on vehicle sheets.

Make resize behavior static for character/vehicle frequency

---

src/module/actor/character/attack-popouts.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/module/rules/rule-element/roll-option.ts
src/styles/actor/_index.scss
src/styles/actor/army/_index.scss
src/styles/actor/tabs/_actions.scss
static/templates/actors/army/sheet.hbs
static/templates/actors/character/attack-popout.hbs
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/npc/tabs/main.hbs
static/templates/actors/partials/toggles.hbs
static/templates/actors/vehicle/tabs/actions.hbs

Finish implementation of roll-option-toggle placement

---

packs/classfeatures/wildsong.json
packs/feats/multilingual.json

Also add free language from Wildsong feat

Have Multilingual feat add language slots

---

packs/feats/shared-assault.json

Fix reference in Shared Assault

---

src/module/actor/actions/single-check.ts
src/module/system/action-macros/basic/escape.ts

Also needed for Arrest a Fall and Grab an Edge actions.

Add support for multiple candidate statistics in action object data

---

packs/feats/aldori-parry.json
packs/feats/call-gun.json
packs/feats/feys-trickery.json
packs/feats/harrower-dedication.json
packs/feats/invigorating-breath.json
packs/feats/living-vessel-dedication.json
packs/feats/out-of-hand.json
packs/feats/turn-to-mist.json

A pass to add self-effects and granted actions to feats that need them.

Add more self-effects and granted actions to Feats

---

static/lang/en.json
static/templates/actors/character/limited.hbs
static/templates/actors/character/partials/elemental-blast.hbs
static/templates/actors/character/partials/header.hbs
static/templates/actors/character/partials/strike.hbs
static/templates/actors/character/sheet.hbs
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/character/tabs/biography.hbs
static/templates/actors/character/tabs/character.hbs
static/templates/actors/character/tabs/proficiencies.hbs
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/hazard/partials/sidebar.hbs
static/templates/actors/loot/sheet.hbs
static/templates/actors/loot/sidebar.hbs
static/templates/actors/npc/partials/action.hbs
static/templates/actors/npc/partials/attack.hbs
static/templates/actors/npc/partials/sidebar.hbs
static/templates/actors/npc/sheet.hbs
static/templates/actors/npc/simple-sheet.hbs
static/templates/actors/npc/tabs/main.hbs
static/templates/actors/npc/tabs/notes.hbs
static/templates/actors/partials/action.hbs
static/templates/actors/partials/coinage.hbs
static/templates/actors/partials/item-line.hbs
static/templates/actors/partials/item-summary.hbs
static/templates/actors/partials/spell-collection.hbs
static/templates/actors/spell-preparation-sheet.hbs
static/templates/actors/vehicle/sheet.hbs
static/templates/items/sheet.hbs

Set tooltip class at top of sheets, set to classless for item summaries

---

src/module/system/action-macros/index.ts
src/module/system/action-macros/specialty-basic/arrest-a-fall.ts
static/lang/action-en.json

~~Depends on https://github.com/foundryvtt/pf2e/pull/12583~~

Add arrest a fall action object

---

src/module/system/action-macros/index.ts
src/module/system/action-macros/specialty-basic/grab-an-edge.ts
static/lang/action-en.json

~~Depends on https://github.com/foundryvtt/pf2e/pull/12583~~

Add grab an edge action object

---

packs/actions/sustain-an-effect.json

Add Sustain an Effect Exploration Activity

---

src/module/canvas/token/object.ts

Check that flanking buddies are allies

---

packs/feats/coven-spell.json

Correct level of Coven Spell feat

---

packs/feats/scholarly-defense.json

Adds functionality to scholarly defense rule elements

Brushup Scholarly Defense Rule Elements

---

packs/ancestryfeatures/magical-strikes.json

Automate the Sprite ancestry feature Magical Strikes

---

packs/spells/purifying-icicle.json

Update Purifying Icicle to deal extra vitality damage only against undead

---

packs/abomination-vaults-bestiary/khurfel.json
packs/equipment-effects/effect-emerald-fulcrum-lens.json
packs/equipment/emerald-fulcrum-lens.json

Also update description formatting and add healing link

Brush up Emerald Fulcrum Lens

---

src/module/rules/rule-element/base.ts
static/templates/actors/party/kingdom/partials/settlement.hbs

Closes https://github.com/foundryvtt/pf2e/issues/12320

Allow use of @kingdom in rule element resolving

---

src/styles/actor/hazard/_sidebar.scss

Fix hazard health line regression

---

src/module/actor/sheet/item-summary-renderer.ts
src/module/item/feat/document.ts
src/module/item/physical/document.ts
src/module/item/spell/document.ts
static/templates/actors/partials/item-summary.hbs
static/templates/chat/armor-card.hbs
static/templates/chat/backpack-card.hbs
static/templates/chat/consumable-card.hbs
static/templates/chat/equipment-card.hbs
static/templates/chat/feat-card.hbs
static/templates/chat/shield-card.hbs
static/templates/chat/weapon-card.hbs

Also add to feat and spell summaries

Restore rarity description tooltips in physical-item summaries

---

src/module/item/ability/helpers.ts
src/module/item/spell/document.ts
src/module/item/spell/overlay.ts

Remove guarantee of embedded item returns from spell-variant methods

---

src/module/actor/base.ts
src/module/actor/creature/document.ts
src/module/actor/sheet/base.ts
src/module/item/container/document.ts
src/module/item/container/helpers.ts
src/module/item/physical/document.ts

Restore container cycle checks to inventory drag/drop

---

src/module/system/settings/homebrew/data.ts
src/scripts/hooks/ready.ts

Vet languages during ready hook instead

Remove schema validation from language rarities setting

---

packs/feats/shadow-of-the-wilds.json
packs/feats/telluric-power.json
packs/feats/toppling-dance.json

Also tighten Telluric Power RollOption domain and fix link description for Shadow of the Wilds

Add toggle and trait automation for Toppling Dance

---

src/module/rules/rule-element/battle-form/rule-element.ts

(at least until a migration can be done)

Accommodate dromedary-cased senses in BattleForm REs

---

packs/familiar-abilities/familiar-of-balanced-luck.json
packs/feat-effects/effect-familiar-of-balanced-luck.json

Add effect for Familiar of Balanced Luck

---

src/styles/ui/sidebar/chat/_index.scss

Use system font for notes in chat messages

---

src/module/system/settings/automation.ts
src/module/system/settings/homebrew/data.ts
src/module/system/settings/homebrew/menu.ts
src/module/system/settings/index.ts
src/module/system/settings/menu.ts
src/module/system/settings/metagame.ts
src/scripts/register-templates.ts
static/lang/en.json
static/templates/system/settings/basic-setting.hbs
static/templates/system/settings/homebrew.hbs
static/templates/system/settings/menu.hbs

Supercedes https://github.com/foundryvtt/pf2e/pull/9922

Allow non-kingmaker worlds to enable kingdom and army sheets

---

src/styles/actor/character/_index.scss
src/styles/actor/character/_proficiencies.scss
src/styles/actor/character/_proficiency-ranks.scss
src/styles/actor/character/_sidebar.scss
static/templates/actors/character/partials/sidebar.hbs

Also slightly brighten inset box-shadow of rank tags

Clean up some needlessly complex markup on PC-sheet sidebar

---

packs/feats/beast-speaker.json
packs/heritages/vine-leshy.json

Also fix Vine Leshy selector to be standard

Tighten up predicate for Beast Speaker

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/popups/manage-attack-proficiencies.ts
src/styles/actor/character/_proficiencies.scss
static/templates/actors/character/tabs/proficiencies.hbs

Fix handler of delete-attack-proficiency links on PC sheet

---

packs/feat-effects/effect-devrins-cunning-stance.json
packs/feat-effects/stance-devrins-cunning-stance.json

Include RE from Marshal's Aura effect in Devrin's Cunning Stance effect

---

src/styles/actor/character/_sidebar.scss
static/templates/actors/character/partials/sidebar.hbs

Restore display of stamina on character sheet

---

packs/feats/druid-dedication.json

Add Wildsong language to Druidic Dedication feat

---

static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/partials/modifiers-tooltip.hbs

Fix opening AC modifiers on PC sheet

---

src/styles/actor/character/_character.scss

Fix PC sheet character details sizing

---

static/lang/re-en.json

Update Death Warden Dwarf's Note to remaster

---

src/module/system/check/check.ts

Fix rendering of notes in rerolled check messages

---

static/templates/items/sheet.hbs

Fix display of reaction glyphs on spell sheet headers

---

src/module/chat-message/document.ts
src/scripts/macros/rest-for-the-night.ts

Re-render PC sheet for all upon resting for the night

---

packs/feat-effects/stance-steam-knight.json

Change Steam Knight Stance speed bonus type to status

---

packs/equipment/antimagic.json

Closes https://github.com/foundryvtt/pf2e/issues/12896

Fix description of Antimagic rune

---

src/styles/actor/_spell-collection.scss
src/styles/actor/npc/_spells.scss
static/templates/actors/npc/tabs/spells.hbs
static/templates/actors/partials/spell-collection.hbs

Add room to certain areas of spell collections on actor sheets

---

packs/feats/hymn-of-healing.json
packs/spell-effects/spell-effect-hymn-of-healing.json
packs/spells/hymn-of-healing.json

Also other minor cleanup
Closes https://github.com/foundryvtt/pf2e/issues/12937

Add link to effect from Hymn Of Healing spell

---

src/styles/actor/hazard/_header.scss

Fix regression in hazard trait height

---

packs/spell-effects/spell-effect-darkened-sight.json
packs/spell-effects/spell-effect-travelers-transit.json
packs/spells/darkened-sight.json
packs/spells/travelers-transit.json

Adds a new effect for Darkened Sight.
Also adds a single consolidated ChoiceSet effect for Traveler's Transit.

Add effect for Darkened Sight and unify effects for Traveler's Transit

---

packs/feats/cauldron.json

Cap item level of Cauldron's crafting entry to character level

---

src/module/actor/hazard/document.ts
src/module/actor/hazard/sheet.ts
src/styles/actor/hazard/_index.scss
src/styles/actor/hazard/_sidebar.scss
static/templates/actors/hazard/partials/sidebar.hbs
static/templates/actors/hazard/sheet.hbs

Ensure mutually consistent display of hazard initiative and stealth DC

---

static/templates/actors/character/tabs/actions.hbs

Fix browse downtime actions button

---

src/global.ts
src/module/canvas/perception/modes.ts
src/module/canvas/token/object.ts
src/module/scene/token-document/document.ts
src/module/system/settings/automation.ts
src/module/system/settings/index.ts
src/scripts/config/index.ts
src/scripts/hooks/get-scene-control-buttons.ts
src/scripts/hooks/ready.ts
src/scripts/set-game-pf2e.ts
src/styles/scene/_index.scss
types/foundry/client/pixi/layers/base/interaction-layer.d.ts

- Make all tokens visible
- Brighten somewhat
- Add better visual indication the setting is enabled

Improve various aspects of GM vision

---

src/styles/actor/character/_proficiencies.scss
static/templates/actors/crafting-entry-alchemical.hbs

Fix line height of long proficiency labels

---

src/module/item/abc/document.ts
src/module/item/ancestry/document.ts
src/module/item/ancestry/sheet.ts
src/scripts/handlebars.ts
src/styles/item/_abc-sheet.scss
src/styles/item/_ancestry-sheet.scss
src/styles/item/_index.scss
static/lang/en.json
static/templates/items/ancestry-details.hbs

Clean up ancestry-sheet styling

---

static/lang/action-en.json

Closes https://github.com/foundryvtt/pf2e/issues/13014

Correct text of identify alchemy action object outcome notes

---

src/module/canvas/status-effects.ts
src/styles/ui/sidebar/chat/_conditions.scss
static/lang/en.json
static/templates/chat/participant-conditions.hbs

Also redo message template and style

Hide speaker in participant-conditions message if setting is enabled

---

src/module/actor/sheet/base.ts
src/scripts/ui/user-visibility.ts
src/styles/actor/_nav.scss
src/styles/actor/character/_sidebar.scss
src/styles/actor/npc/_sidebar.scss
types/foundry/client/core/settings.d.ts

Change width of actor sheets to correspond with `fontSize` setting

---

src/module/scene/document.ts
types/foundry/client/core/hooks.d.ts
types/foundry/client/data/documents/scene.d.ts
types/foundry/client/pixi/board.d.ts
types/foundry/client/pixi/canvas-layer/grid-layer.d.ts
types/foundry/common/primitives/set.d.ts
types/foundry/common/utils/collection.d.ts

Improve typings for Sets and Collections
Improve typings of some pixi functions
Add typings for i18nInit Hook
Add typing for createEmbeddedDocuments of type Note on Scene

Improve typings for various functions

---

packs/actions/armor-up.json
packs/spell-effects/spell-effect-instant-armor.json

Also fix source for Armor Up!
Closes https://github.com/foundryvtt/pf2e/issues/13044

Fix duration of Instant Armor

---

packs/age-of-ashes-bestiary/xotanispawn.json

Probably should have put all those missing senses in the same commit, but when I thought I was done, I keep finding more of them.

Fix Xotanispawn tremorsense

---

packs/spells/blinding-foam.json

Fix Blinding Foam base damage die size

---

packs/agents-of-edgewatch-bestiary/skinsaw-seamer.json

Add automation for Skinsaw Seamer's Flay

---

packs/pfs-season-2-bestiary/glorzia.json

Fix Glorzia's level

---

packs/strength-of-thousands-bestiary/froglegs.json

Add automation for Froglegs' Knife Fighter

---

packs/feat-effects/effect-spark-fist.json
packs/feats/arcane-fists.json
packs/feats/ferrousoul.json
packs/feats/hand-of-the-lich.json
packs/feats/mummy-dedication.json
packs/feats/spark-fist.json
packs/heritages/warrior-automaton.json

Closes https://github.com/foundryvtt/pf2e/issues/12986

Brush up some fist attack automation

---

packs/equipment/bracers-of-strength.json

Add inline damage link to Bracers of Strength

---

src/module/item/physical/helpers.ts

Don't factor in bulk when pricing precious-material shields

---

src/module/actor/spellcasting.ts
src/module/item/spell/document.ts

Set base spellcasting counteraction modifier for NPCs

---

packs/equipment/long-air-repeater.json

This one seems to be in the "obvious error with obvious correction" category

Fix usage of long air repeater

---

packs/spells/destructive-aura.json

Correct Destructive Aura from cone to emanation

---

packs/equipment/oil-of-potency-major.json

Correct price of major oil of potency

---

src/styles/actor/_index.scss
src/styles/actor/character/_character.scss
static/templates/actors/character/tabs/character.hbs

Restore spacing between character tab subsections

---

packs/spells/boost-eidolon.json

Closes https://github.com/foundryvtt/pf2e/issues/13139

Fix range of Boost Eidolon

---

src/module/actor/sheet/popups/identify-popup.ts
static/templates/actors/identify-item-chat-skill-checks.hbs

~~Depends on https://github.com/foundryvtt/pf2e/pull/12990 and https://github.com/foundryvtt/pf2e/pull/12733~~

Wire up identify alchemy and identify magic actions for item identification

---

packs/equipment/sansetsukon.json

Fix damage type for sansetsukon

---

packs/feat-effects/stance-tenacious-stance.json

Fill automation gaps in Stance: Tenacious Stance

---

packs/feats/basic-arcana.json
packs/feats/basic-blood-potency.json
packs/feats/basic-breakthrough.json
packs/feats/basic-concoction.json
packs/feats/basic-deduction.json
packs/feats/basic-devotion.json
packs/feats/basic-dogma.json
packs/feats/basic-flair.json
packs/feats/basic-fury.json
packs/feats/basic-hunters-trick.json
packs/feats/basic-kata.json
packs/feats/basic-maneuver.json
packs/feats/basic-martial-magic.json
packs/feats/basic-muses-whispers.json
packs/feats/basic-mysteries.json
packs/feats/basic-shooting.json
packs/feats/basic-synergy.json
packs/feats/basic-thaumaturgy.json
packs/feats/basic-thoughtform.json
packs/feats/basic-trickery.json
packs/feats/basic-wilding.json
packs/feats/basic-witchcraft.json
packs/feats/through-the-gate.json

Also slightly optimized the filtering in all cases

Ensure "basic" archetype feats filter by class feat

---

packs/vehicles/airship.json
packs/vehicles/bathysphere.json
packs/vehicles/carriage.json
packs/vehicles/cart.json
packs/vehicles/chariot-heavy.json
packs/vehicles/chariot-light.json
packs/vehicles/cutter.json
packs/vehicles/galley.json
packs/vehicles/glider.json
packs/vehicles/hot-air-balloon.json
packs/vehicles/longship.json
packs/vehicles/rowboat.json
packs/vehicles/sailing-ship.json
packs/vehicles/sky-chariot-heavy.json
packs/vehicles/sky-chariot-light.json
packs/vehicles/sky-chariot-medium.json
packs/vehicles/sled.json
packs/vehicles/sleigh.json
packs/vehicles/steam-giant.json
packs/vehicles/strider.json
packs/vehicles/velocipede.json
packs/vehicles/wagon.json

Also update some fire weakness to be conditional on unbroken
Closes https://github.com/foundryvtt/pf2e/issues/13167

Add Sled and update remaster vehicles

---

packs/heritages/oread.json
packs/heritages/sylph.json
packs/heritages/undine.json

Fix presence/placement of remaining geniekin traits

---

packs/equipment-effects/effect-potion-of-acid-resistance-greater.json
packs/equipment-effects/effect-potion-of-acid-resistance-lesser.json
packs/equipment-effects/effect-potion-of-acid-resistance-moderate.json
packs/equipment-effects/effect-potion-of-cold-resistance-greater.json
packs/equipment-effects/effect-potion-of-cold-resistance-lesser.json
packs/equipment-effects/effect-potion-of-cold-resistance-moderate.json
packs/equipment-effects/effect-potion-of-electricity-resistance-greater.json
packs/equipment-effects/effect-potion-of-electricity-resistance-lesser.json
packs/equipment-effects/effect-potion-of-electricity-resistance-moderate.json
packs/equipment-effects/effect-potion-of-fire-resistance-greater.json
packs/equipment-effects/effect-potion-of-fire-resistance-lesser.json
packs/equipment-effects/effect-potion-of-fire-resistance-moderate.json
packs/equipment-effects/effect-potion-of-sonic-resistance-greater.json
packs/equipment-effects/effect-potion-of-sonic-resistance-lesser.json
packs/equipment-effects/effect-potion-of-sonic-resistance-moderate.json

Update publication source of Potion of Resistance effects to remaster

---

packs/crown-of-the-kobold-king-bestiary/drazmorg-the-damned.json
packs/equipment/in-the-shadows-of-toil.json

Also fix description formatting

Fix traits on In the Shadows of Toil

---

packs/feats/emotional-surge.json
packs/feats/thoughtsense.json

And made Emotional Surge a self applied effect

Add predicated imprecise thoughtsense to Thoughtsense feat

---

packs/feat-effects/effect-thoughtform-summoning.json
packs/feats/mental-static.json
packs/feats/psi-strikes.json
packs/feats/thoughtform-summoning.json

Also converted Mental Static's roll into a damage roll ~~and linked Psi Strike's effect in the feat's description~~

Add Thoughtform Summoning effect

---

packs/heritages/dragonscaled-kobold.json

Update Dragonscaled Kobold resistance

---

src/module/actor/creature/document.ts

Prevent flanking highlighting from appearing for neutral actors

---

src/styles/actor/_index.scss

sheet-content is a crb-sheet thing, not a general sheet one.

Fix regression with party and loot sheet inventory

---

packs/equipment/reinforced-stock.json

Correct bulk of Reinforced Stock

---

src/module/actor/creature/sheet.ts
src/module/system/settings/homebrew/data.ts
src/module/system/settings/homebrew/menu.ts
src/module/system/tag-selector/languages.ts
src/styles/settings/_homebrew.scss
static/lang/en.json
static/templates/system/settings/homebrew.hbs

Also moved languages up to first tab due to its height

Add support for classifying languages as being unavailable for use

---

packs/feats/risky-surgery.json
static/lang/re-en.json

The feat was missing its AdjustSuccess RE as well so that was added back.

Cleanup and Localize Risky Surgery

---

packs/bestiary-effects/effect-artificers-command.json
packs/bestiary-effects/effect-battle-cry.json
packs/bestiary-effects/effect-blood-soak.json
packs/bestiary-effects/effect-bloom-regeneration.json
packs/bestiary-effects/effect-call-to-action.json
packs/bestiary-effects/effect-commanders-aura.json
packs/bestiary-effects/effect-consume-organ.json
packs/bestiary-effects/effect-defensive-slice.json
packs/bestiary-effects/effect-devour-soul-victim-level-15-or-higher.json
packs/bestiary-effects/effect-devour-soul.json
packs/bestiary-effects/effect-dire-warning.json
packs/bestiary-effects/effect-feed.json
packs/bestiary-effects/effect-fetid-screech-critical-failure.json
packs/bestiary-effects/effect-gloom-aura.json
packs/bestiary-effects/effect-grasping-tendrils.json
packs/bestiary-effects/effect-harmonizing-aura-allies.json
packs/bestiary-effects/effect-harmonizing-aura-enemies.json
packs/bestiary-effects/effect-haywire.json
packs/bestiary-effects/effect-inspired-feast.json
packs/bestiary-effects/effect-lost-plates.json
packs/bestiary-effects/effect-lost-red-cap.json
packs/bestiary-effects/effect-mutilating-bite.json
packs/bestiary-effects/effect-pain-frenzy.json
packs/bestiary-effects/effect-poison-frenzy.json
packs/bestiary-effects/effect-revert-form.json
packs/bestiary-effects/effect-song-of-the-swamp.json
packs/bestiary-effects/effect-soul-siphon.json
packs/bestiary-effects/effect-undead-mastery.json
packs/bestiary-effects/effect-wolf-shape.json

Fixes some too specific selectors, some too general selectors, some missing REs, and some incorrect REs.
Also moved some REs to badge counters instead of a clunky ChoiceSet.

Refresh some Bestiary Effects

---

packs/feats/diving-armor.json
packs/feats/reverse-engineer.json
packs/feats/ricochet-legend.json

as well as a Will save button to Ricochet Legend's description

Add rule elements to Diving Armor and Reverse Engineer

---

src/styles/_globals.scss
src/styles/main.scss

Following release of Chrome 121

Restore foundry-style scrollbar appearance

---

packs/equipment-effects/effect-drowsy-sun-eye-drops.json
packs/equipment/drowsy-sun-eye-drops.json
packs/equipment/poison-sedum.json

Also add icon for Poison Sedum

Add effect for Drowsy Sun Eye Drops

---

packs/equipment/palette-of-masterstrokes.json

Also fix activation cost and predicate

Fix name of Palette of Masterstrokes

---

packs/iconics/jirelle-level-1.json
packs/iconics/jirelle-level-5.json
src/module/migration/migrations/916-precise-strike-flag.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

Migrate precise strike damage to actor flags

---

packs/equipment/broken-tusk-pendant-greater.json
packs/equipment/broken-tusk-pendant.json
packs/equipment/philosophers-extractor.json

Also standardize predicate for Philosopher's Extractor

Add slug to Broken Tusk FlatModifier

---

packs/equipment-effects/effect-starsong-nectar.json
packs/equipment/druids-crown.json
packs/equipment/zuhras-gloves.json

Fix some localized strings

---

src/module/system/text-editor.ts

Also dispense with "pf2" prefixes

Add support for tagging @Damage rolls as immutable and to override traits

---

src/module/actor/modifiers.ts
src/module/rules/rule-element/damage-dice.ts
src/module/system/damage/dialog.ts
static/templates/chat/damage/damage-modifier-dialog.hbs

Closes #13349 
I cloned the fields from Flat Modifier and everything seems to work in my tests.

Add hideIfDisabled field to DamageDice RE

---

packs/feat-effects/effect-spell-parry.json
packs/feats/spell-parry.json

Add Spell Parry Effect and attach to Feat

---

packs/classfeatures/bloodline-aberrant.json
packs/classfeatures/bloodline-angelic.json
packs/classfeatures/bloodline-demonic.json
packs/classfeatures/bloodline-diabolic.json
packs/classfeatures/bloodline-draconic.json
packs/classfeatures/bloodline-elemental.json
packs/classfeatures/bloodline-fey.json
packs/classfeatures/bloodline-genie.json
packs/classfeatures/bloodline-hag.json
packs/classfeatures/bloodline-harrow.json
packs/classfeatures/bloodline-imperial.json
packs/classfeatures/bloodline-nymph.json
packs/classfeatures/bloodline-phoenix.json
packs/classfeatures/bloodline-psychopomp.json
packs/classfeatures/bloodline-shadow.json
packs/classfeatures/bloodline-undead.json
packs/classfeatures/bloodline-wyrmblessed.json
packs/feat-effects/effect-phoenix-blood-magic.json
packs/feat-effects/effect-undead-blood-magic.json
packs/feats/ancestral-blood-magic.json
static/lang/re-en.json

A lot of these existing effects can be done better (and be compressed) with current tech, but I stuck to making notes, linking effects and making damage buttons. I'll probably revisit the effects soon unless someone does first.

Automate Blood Magic notes

---

static/templates/items/partials/spell-description-prepend.hbs

Tiny error in the refactor Mr Shark, we lost our Areas 👀

Fix typo in spell description prepend

---

packs/classes/cleric.json
packs/classfeatures/divine-font.json
packs/feats/versatile-font.json
packs/iconics/kyra-level-1.json
packs/iconics/kyra-level-3.json
packs/iconics/kyra-level-5.json
packs/paizo-pregens/kyra-beginner-box.json
static/lang/re-en.json

~~Depends on https://github.com/foundryvtt/pf2e/pull/13399~~
Not sure if we want to handle migration for this feature.

Add automation for divine font selection

---

packs/classfeatures/the-silent-whisper.json
packs/classfeatures/the-tangible-dream.json
packs/classfeatures/the-unbound-step.json

Fix some Psychic Amps localization key references

---

src/global.ts
types/foundry/client/apps/app.d.ts
types/foundry/client/config.d.ts
types/foundry/client/ui/index.d.ts

Add hotbar and scene nav to global ui
Add CONFIG.Canvas.dragSpeedModifier
Add Application.prototype.bringToTop

Add missing types

---

packs/classfeatures/baba-yaga-patron.json
packs/classfeatures/faiths-flamekeeper.json
packs/classfeatures/mosquito-witch-patron.json
packs/classfeatures/silence-in-snow.json
packs/classfeatures/spinner-of-threads.json
packs/classfeatures/starless-shadow.json
packs/classfeatures/the-inscribed-one.json
packs/classfeatures/the-resentment.json
packs/classfeatures/wilding-steward.json
packs/feat-effects/effect-familiar-of-balanced-luck.json
packs/feat-effects/effect-familiar-of-keen-senses.json
packs/feat-effects/effect-familiar-of-restored-spirit.json
static/lang/re-en.json

Hopefully the future action stuff will let us do this for sustain too, but this is still pretty good.

Automate Witch's Patron Familiar Ability notes upon casting a hex

---

src/module/item/spell/document.ts
src/module/item/spellcasting-entry/item-spellcasting.ts

Supports Elemental Breath, but not Summon Elemental Herald (doesn't have variants).

Support variants with elemental traits for kinetic activation

---

packs/feats/guiding-luck.json
packs/feats/incredible-luck-halfling.json
packs/feats/shared-luck-halfling.json
static/lang/re-en.json

and upgrade frequency with Incredible Luck

Add upgrade notes to Halfling Luck

---

packs/feats/additional-companion.json
packs/feats/advanced-warden.json
packs/feats/deeper-dabbler.json
packs/feats/divine-access.json
packs/feats/ganzi-gaze.json
packs/feats/heightened-captivation.json
packs/feats/macabre-virtuoso.json
packs/feats/major-lesson.json
packs/feats/reclaimant-plea.json
packs/feats/soul-arsenal.json
packs/feats/specialized-beastmaster-companion.json
packs/feats/specialized-companion-druid.json
packs/feats/specialized-mount.json
packs/feats/stronger-debilitating-venom.json
packs/feats/ubiquitous-gadgets.json
packs/feats/vigilant-benediction.json
packs/feats/wilderness-spotter.json

In instances where a feat can only be taken multiple times based on character level, I set the max taking to the total number of times the feat can be taken levels 1-20.

Correctly set all Feat Max Taking values

---

src/global.ts
src/module/canvas/token/object.ts
src/scripts/set-game-pf2e.ts

Disable flanking for GM-hidden tokens

---

packs/equipment-effects/effect-arachnid-harness.json
packs/equipment/arachnid-harness-greater.json
packs/equipment/arachnid-harness.json
static/lang/re-en.json

Also update descriptions of items

Add icon to effect for Arachnid Harness and localize label

---

packs/feats/anchoring-aura.json

Delete requirement from desc in anchoring aura

---

src/module/apps/compendium-browser/index.ts
src/styles/actor/character/_spellcasting.scss
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/partials/spell-collection.hbs

Also Restore header to ritual entry and add move compendium browse button to it

Fix regression in spellcasting entry drag/drop

---

packs/spells/lifes-flowing-river.json

Closes https://github.com/foundryvtt/pf2e/issues/13515

Fix level of Life's Flowing River

---

src/module/actor/base.ts
src/module/item/spellcasting-entry/rituals.ts

(and defer retrieval of rituals for their collections)

Always create RitualSpellcasting instances

---

packs/equipment/celestial-staff.json
packs/equipment/hell-staff.json

Also fix some description formatting issues

Fix Celestial Staff and  Hell Staff to be specific items

---

packs/spells/delay-affliction.json

Also fix description formatting

Fix Delay Affliction to deliver healing

---

src/module/item/abstract-effect/document.ts

This will allow effects that are dragged from check messages to have that roll information

Add effect roll options with check context data

---

packs/spell-effects/spell-effect-summon-healing-servitor.json
packs/spells/summon-healing-servitor.json
packs/spells/vitality-lash.json

Also remove unneeded inline damage roll from Vitality Lash

Fix Summon Healing Servitor to be both damage and healing and add effect

---

packs/feats/archer-dedication.json
packs/feats/archers-aim.json
packs/feats/quick-shot.json
packs/feats/staggering-fire.json

Extend archer archetype feat support to weapons in crossbow group

---

packs/spell-effects/spell-effect-hallowed-ground.json
packs/spells/hallowed-ground.json

Also reorder damage partials to match text

Add effect for Hallowed Ground

---

packs/equipment/serpent-dagger.json
static/lang/re-en.json

Also brush up description formatting
Supersedes https://github.com/foundryvtt/pf2e/pull/13505
Checked with @ChasarooniZ

Add note to Serpent Dagger

---

packs/agents-of-edgewatch-bestiary/shredskin.json
packs/book-of-the-dead-bestiary/shredskin.json

Part of https://github.com/foundryvtt/pf2e/issues/13593

Fix Shredskin immunity to critical hits (except slashing)

---

packs/outlaws-of-alkenstar-bestiary/smog-giant.json
static/lang/re-en.json

Part of https://github.com/foundryvtt/pf2e/issues/13593

Add custom immunity for Smog Giant

---

packs/extinction-curse-bestiary/imperious-darkside-mirror.json
packs/fists-of-the-ruby-phoenix-bestiary/dimensional-darkside-mirror.json
packs/hazards/darkside-mirror.json

Part of https://github.com/foundryvtt/pf2e/issues/13593

Brush up Darkside Mirrors

---

packs/agents-of-edgewatch-bestiary/miogimo.json
packs/agents-of-edgewatch-bestiary/zealborn.json
packs/blood-lords-bestiary/rumin-purgo.json
packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
packs/fists-of-the-ruby-phoenix-bestiary/gumiho.json
packs/gatewalkers-bestiary/equendia.json
packs/kingmaker-bestiary/castruccio-irovetti.json
packs/kingmaker-bestiary/ngara.json
packs/kingmaker-bestiary/quintessa-maray.json
packs/monsters-of-myth-bestiary/kallas-devil.json
packs/night-of-the-gray-death-bestiary/conqueror-worm.json
packs/pathfinder-bestiary-2/chernobue.json
packs/pathfinder-bestiary-2/gosreg.json
packs/pathfinder-bestiary-2/spirit-naga.json
packs/pathfinder-bestiary-2/worm-that-walks-cultist.json
packs/pathfinder-bestiary-3/adult-sovereign-dragon-spellcaster.json
packs/pathfinder-bestiary-3/ancient-sovereign-dragon-spellcaster.json
packs/season-of-ghosts-bestiary/argyrzei.json
packs/season-of-ghosts-bestiary/hong-meigui.json
packs/shadows-at-sundown-bestiary/scarlet-walker.json
packs/spells/share-lore.json
packs/spells/subconscious-suggestion.json
packs/stolen-fate-bestiary/kannijo.json
packs/strength-of-thousands-bestiary/king-of-biting-ants.json

Also refresh copies of Subconscious Suggestion

Select better icons for Subconscious Suggestion and Share Lore

---

packs/feats/parallel-breakthrough.json
static/lang/re-en.json

Automate Parallel Breakthrough feat

---

packs/equipment/luck-blade-wishing.json
packs/equipment/luck-blade.json
packs/rollable-tables/17th-level-permanent-items.json
packs/rollable-tables/19th-level-permanent-items.json

Clean up enriched HTML in Luck Blade (Wishing)
Fix Luck Blade (Wishing) to be specific item
Replace lower-resolution system icons with identical core icons

Update Luck Blade descriptions

---

src/module/system/check/check.ts

Fix non-hero point rerolls

---

packs/classfeatures/singular-expertise.json

Fix inclusion of crossbows in Singular Expertise

---

packs/kingmaker-bestiary/armies/tok-nikrat-scouts.json

I'm unsure if the tactics are automated correctly.

Add Tok-Nikrat Scouts army

---

src/styles/actor/_inventory.scss
src/styles/actor/character/_inventory.scss

Removes inner borders and fixes header alignment.

Minor styling updates to inventories

---

src/module/rules/rule-element/choice-set/data.ts
src/module/rules/rule-element/choice-set/rule-element.ts

Normally this requires a separate AE-like.

Allow requesting actor flag be set directly in choice set RE

---

packs/agents-of-edgewatch-bestiary/shristi-melipdra.json

Tighten predicates on Heaven's Thunder and add FlatModifier slugs
Automate resistance for Sky and Heaven Stance

Brush up Shristi Melipdra

---

packs/feats/bard-dedication.json

Add choice set for muse to Bard Dedication

---

packs/pathfinder-bestiary-2/culdewen.json
packs/pathfinder-bestiary-2/drainberry-bush.json
packs/pathfinder-bestiary-2/yellow-musk-creeper.json

Also add incapacitation to Yellow Musk Creeper's Spray Pollen
See ​Pathfinder Bestiary 2 Errata​: https://paizo.com/pathfinder/faq

Fix errata'd rarity of Culdewen and Drainberry Bush

---

packs/blog-bestiary/chea.json
packs/blog-bestiary/eleukas.json
packs/blog-bestiary/mari-lwyd.json

Also clean up some unnecessary NPC strike descriptions and fix Chea's Wind Crash range
https://paizo.com/community/blog/v5748dyo6shj6?A-Caroling-Horse
https://paizo.com/community/blog/v5748dyo6shl0?NoPrep-Character-Chea
https://paizo.com/community/blog/v5748dyo6shjp?NoPrep-Character-Eleukas

Add automation for Mostly Harmless

---

packs/pathfinder-bestiary/treerazer.json

Remove incorrect predicate in favor of better selector

Fix Treerazer's Staggering Strike

---

packs/bestiary-effects/effect-swig.json
packs/npc-gallery/dockhand.json
packs/pfs-season-1-bestiary/dockhand-cultist.json
packs/pfs-season-3-bestiary/iron-ring-deckhand.json

Add description
Remove incorrect predicate in favor of better selector
Grant clumsy
Standardize action description and make self effect
Remove REs from dockhand cultist

Brush up Swig effect

---

packs/equipment/alchemists-haversack.json

Closes https://github.com/foundryvtt/pf2e/issues/13735

Fix Alchemist's Haversack to be container

---

src/module/actor/npc/sheet.ts

Hide the name of Lootable NPCs depending on Token Name Visibility setting

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/character/types.ts
src/module/actor/creature/data.ts
src/module/actor/creature/document.ts
src/module/actor/familiar/document.ts
src/module/actor/hazard/data.ts
src/module/actor/hazard/document.ts
src/module/actor/helpers.ts
src/module/actor/npc/data.ts
src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts
src/module/actor/party/sheet.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/rules/rule-element/battle-form/rule-element.ts
src/module/system/damage/weapon.ts
src/module/system/statistic/armor-class.ts
src/module/system/statistic/base.ts
src/module/system/statistic/data.ts
src/module/system/statistic/hit-points.ts
src/module/system/statistic/perception.ts
src/module/system/statistic/statistic.ts
src/scripts/macros/check-prompt/helpers.ts
src/scripts/macros/earn-income/macro.ts
static/templates/actors/npc/tabs/main.hbs

Fix non-mental NPC skills being affected by stupefied condition

---

packs/equipment/frost-brand.json

Add resistance to Frost Brand

---

packs/feats/consistent-surge.json
packs/feats/offensive-subroutine.json
packs/feats/protective-subroutine.json

Goof'd the predicate last time, it's fixed now.

Limit android feats description alterations to nanite surge feat

---

packs/feats/mummy-dedication.json

Revert "Fix Mummy Dedication ChoiceSet activating"

---

src/module/actor/loot/sheet.ts
src/module/actor/sheet/base.ts
static/lang/en.json

Only show unit price/bulk in merchant sheets

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/chat-message/helpers.ts

There's more that ought to be moved, but this is the simplest one as a start.
This will break Idle's module, since he's reimplementing extract logic to reproduce that functionality. I will inform him before release that he should start deleting code.

Handle damage notes extraction in actor.applyDamage()

---

src/module/actor/base.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/synthetics.ts

Workflow changes have rendered this no longer beneficial.

Remove deferral of RE failure warnings

---

packs/equipment/accursed-staff-greater.json
packs/equipment/accursed-staff-major.json
packs/equipment/accursed-staff.json
static/lang/re-en.json

Also change their icons because this is a spooky staff and the image was just a wooden stick

Add spell description alteration for accursed staff

---

build/run-migration.ts
packs/abomination-vaults-bestiary/viscous-black-pudding.json
packs/blood-lords-bestiary/facetbound-cascader.json
packs/equipment-effects/effect-brass-dwarf-weakness.json
packs/equipment/the-brass-dwarf.json
packs/feats/elemental-evolution.json
packs/pathfinder-bestiary-3/hadrinnex.json
packs/pathfinder-bestiary/quasit.json
packs/rage-of-elements-bestiary/gennayn.json
packs/rage-of-elements-bestiary/jann-shuyookh.json
packs/rage-of-elements-bestiary/living-lodestone.json
packs/rage-of-elements-bestiary/nanoshard-swarm.json
packs/season-of-ghosts-bestiary/meokdan.json
src/module/migration/migrations/920-suboption-selection.ts
src/module/rules/rule-element/roll-option.ts

To make way for dynamic suboptions

Move `RollOption` suboption selections to top level of rule object

---

packs/feats/restoring-blood.json

Update Restoring Blood to be vitality healing

---

src/module/system/check/check.ts
src/styles/ui/_roll-modifiers-dialog.scss

Closes https://github.com/foundryvtt/pf2e/issues/13723
Also fixes Off looking janky in roll dialog substitutions

Fix rendering and disabling check substitution

---

packs/equipment/rebounding-breastplate.json

Brush up Rebounding Breastplate description

---

packs/spells/briny-bolt.json

Add component traits to Briny Bolt

---

src/module/system/check/check.ts

Add Hero Point RollOption on rerolls

---

static/lang/re-en.json
static/templates/items/rules/flat-modifier.hbs

Show Force checkbox on FlatModifier Form when Attribute selected

---

packs/outlaws-of-alkenstar-bestiary/ibrium.json

Also refresh copies of affected spells

Add automation for Ibrium's Vitrumancy

---

packs/feat-effects/effect-ongoing-selfishness.json
packs/feat-effects/stance-everstand-stance.json
packs/feats/iron-repercussions.json
packs/feats/ongoing-selfishness.json
packs/feats/ranged-reprisal.json
packs/feats/unimpeded-step.json
packs/feats/vicious-vengeance.json
packs/feats/weight-of-guilt.json
static/lang/re-en.json

also a sneaky additional predicate to Everstand Stance's damage upgrade.

Add notes and automation for champion reaction upgrade feats.

---

src/module/item/base/document.ts
src/module/rules/rule-element/choice-set/rule-element.ts
src/module/rules/rule-element/grant-item/rule-element.ts

....and fixes a rarity option regression

Add parent and granter roll options to choiceset filters

---

src/module/actor/character/sheet.ts
src/module/system/conditions/manager.ts
src/scripts/hooks/babele-ready.ts
src/scripts/hooks/canvas-ready.ts
src/scripts/hooks/i18n-init.ts
src/scripts/hooks/index.ts
src/scripts/set-game-pf2e.ts
src/styles/actor/character/_character.scss
src/styles/actor/character/_proficiency-ranks.scss
src/styles/actor/character/_sidebar.scss
src/styles/settings/_index.scss
types/foundry/client/ui/context.d.ts

Also correct name/description localization of bundled conditions

Adjust some PC-sheet styling to accommodate non-English text

---

src/module/item/weapon/document.ts
src/module/item/weapon/sheet.ts
static/templates/items/weapon-details.hbs

Also move coercions to `_preUpdate` method

Prevent weapon damage dice changes made during data preparation from getting persisted

---

packs/fists-of-the-ruby-phoenix-bestiary/sixth-pillar-student.json

Add automation for Sixth Pillar Student's Bludgeoning Energy

---

packs/feats/disciples-breath.json

Not getting to indepth in fixing up Dragon Disciple any more given PC2's expected Dragon shakeup

Update Disciple's Breath to use @Damage and have public roll

---

src/styles/item/_spell-sheet.scss
static/templates/items/spell-details.hbs

Fix the spell damage box bugging out when a material is added

---

packs/age-of-ashes-bestiary/ilgreth.json
packs/agents-of-edgewatch-bestiary/baatamidar.json
packs/kingmaker-bestiary/fetch-behemoth.json
packs/pathfinder-bestiary-2/lerritan.json
packs/pathfinder-bestiary-2/olethrodaemon.json
packs/pathfinder-bestiary-2/veranallia.json
packs/spells/cataclysm.json

Update Cataclysm to use damage partials rather than damage link

---

CONTRIBUTING.md

Update CONTRIBUTING.md to reference ORC license

---

src/module/item/ability/document.ts

Add familiar ability RollOptions to Familiars

---

packs/spell-effects/spell-effect-unusual-anatomy.json
packs/spells/unusual-anatomy.json

Closes https://github.com/foundryvtt/pf2e/issues/13913

Fix heightening interval for Unusual Anatomy and add resistance to effect

---

src/module/encounter/combatant.ts
src/module/item/abstract-effect/data.ts
src/module/item/effect/document.ts
static/lang/en.json
static/templates/items/effect-sidebar.hbs

Also log the initial value for RE availability

Add effect-badge reevaluation event of "initiative-roll"

---

packs/pathfinder-bestiary-3/popobawa.json
packs/pfs-season-4-bestiary/sounrel-3-4.json
packs/pfs-season-4-bestiary/sounrel-5-6.json
packs/spells/animated-assault.json
packs/stolen-fate-bestiary/ndede.json

Remove unneeded damage links from Animated Assault and add autoleveling damage link

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/canvas/drop-canvas-data.ts
src/module/rules/rule-element/choice-set/prompt.ts
src/scripts/hooks/drop-canvas-data.ts
types/foundry/client/ui/editor.d.ts

Closes https://github.com/foundryvtt/pf2e/issues/7223 and supercedes https://github.com/foundryvtt/pf2e/pull/13862

Also support persistent damage conditions dropped on actor sheets

---

packs/blood-lords-bestiary/iron-taviah.json
packs/blood-lords-bestiary/sahni-bride-of-the-sea.json
packs/book-of-the-dead-bestiary/pale-sovereign.json
packs/quest-for-the-frozen-flame-bestiary/summer-hora-queen.json
packs/quest-for-the-frozen-flame-bestiary/summer-hora.json
packs/sky-kings-tomb-bestiary/heartbroken-dream.json
packs/spells/curse-of-lost-time.json

Also clean up description and remove unneeded damage links
Refresh all copies

Add damage partial to Curse Of Lost Time

---

src/module/item/weapon/document.ts
src/module/system/damage/weapon.ts

This will allow rule elements that hinge on dice faces count to properly function

Make dice faces change for two-hand trait directly from weapon

---

packs/pathfinder-dark-archive/cocoon-of-lucid-potential.json
packs/pathfinder-dark-archive/mother-mitera.json
packs/pfs-season-4-bestiary/grace-of-the-owl.json
packs/quest-for-the-frozen-flame-bestiary/turkek.json
packs/rage-of-elements-bestiary/ardande-gardener.json
packs/rage-of-elements-bestiary/zephyr-the-west-wind.json
packs/sky-kings-tomb-bestiary/voxnia.json
packs/spells/petal-storm.json
packs/spells/phase-bolt.json
packs/spells/sanguine-mist.json
packs/spells/timber.json

Update Petal Storm, Phase Bolt, Sanguine Mist, Timber

---

src/module/rules/rule-element/item-alteration/rule-element.ts

I don't _think_ anything would be adversely impacted by this.

Delay processing persistent damage recovery DC alterations

---

packs/feats/natural-swimmer.json
packs/feats/reactive-transformation.json

also tidy up Reactive Transformation prerequisite's formatting

Grant a swim speed with Natural Swimmer

---

src/styles/_colors.scss
src/styles/actor/_inventory.scss

Color encumbrance bar yellow when encumbered

---

packs/pfs-season-5-bestiary/enraged-shurrizih.json
packs/pfs-season-5-bestiary/shurrizih.json
packs/rage-of-elements-bestiary/jann-shuyookh.json
packs/spells/noxious-metals.json

Also clean up description
Refresh all copies

Fix damage type of Noxious Metals

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/rules/synthetics.ts

Calculate MAP after check context is acquired

---

src/module/actor/character/document.ts
src/module/actor/character/sheet.ts

Also display as single language on sheet

Prevent counting Common and its corresponding language as two allocated languages

---

src/module/actor/army/document.ts
src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/character/elemental-blast.ts
src/module/actor/helpers.ts
src/module/actor/types.ts
src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/system/action-macros/helpers.ts
src/module/system/damage/types.ts
src/module/system/statistic/statistic.ts

Start making `getRollContext` able to handle rolls by targets

---

src/styles/actor/_spell-preparation.scss
static/templates/actors/spell-preparation-sheet.hbs

Also fixes a tiny css issue with the image frames, but that's not really important enough to call out.

Use separate css for spell preparation form spells

---

packs/blood-lords-bestiary/kemnebi.json
packs/blood-lords-bestiary/necromancer-troop.json
packs/blood-lords-bestiary/virulak-necromancer.json
packs/book-of-the-dead-bestiary/provincial-jiang-shi.json
packs/extinction-curse-bestiary/xulgath-deepmouth.json
packs/gatewalkers-bestiary/protosoul.json
packs/outlaws-of-alkenstar-bestiary/parsus.json
packs/pathfinder-bestiary-3/quintessivore.json
packs/pfs-season-2-bestiary/clouded-quartz-7-8.json
packs/pfs-season-2-bestiary/disciple-of-urxehl-7-8.json
packs/pfs-season-2-bestiary/disciple-of-urxehl-9-10.json
packs/quest-for-the-frozen-flame-bestiary/ashen-swale.json
packs/quest-for-the-frozen-flame-bestiary/azi.json
packs/season-of-ghosts-bestiary/shinigami.json
packs/sky-kings-tomb-bestiary/narseigus-wormcaller.json
packs/spells/enervation.json

Remove damage partial from Enervation in favor of autoleveling inline damage links

---

src/module/item/consumable/document.ts

We need a standardized method to apply such things to deferred items but until I fully understand the full scope of it I'll leave that to the person who introduced all this if they want to.

Apply item alterations and sanctification to scrolls/wands

---

src/module/actor/base.ts
src/module/chat-message/helpers.ts

Probably closes https://github.com/foundryvtt/pf2e/issues/10927. This avoids creating new API, but doesn't handle the ephemeral effect side of things. I don't think it makes sense to move ephemeral effects and contextual clones to apply damage though, perhaps an idea will come to us regarding a better way to handle that in the future.

Handle extraction of healing received modifiers in applyDamage()

---

packs/feats/lunge.json

Useful for automatic flanking detection

Add automation to Lunge

---

src/module/item/abstract-effect/data.ts
src/module/item/effect/data.ts
src/module/item/effect/document.ts
static/lang/en.json
static/templates/items/effect-sidebar.hbs

Add support for Effect Badge Labels that loop to start

---

packs/feats/elemental-explosion.json

Fix Elemental Explosion's damage calculation

---

package-lock.json
package.json
src/module/item/helpers.ts
static/templates/items/partials/addendum.hbs
types/foundry/client/index.d.ts
types/foundry/common/data/fields.d.ts
types/foundry/package.json

Add markdown support to item description addenda

---

src/module/actor/character/document.ts
src/module/actor/data/base.ts
src/module/actor/helpers.ts
src/module/rules/rule-element/strike.ts
static/templates/actors/character/partials/strike.hbs

Make shield auxiliary actions available when in stances that restrict strikes

---

src/module/rules/rule-element/choice-set/rule-element.ts

Include range among index properties retrieved for choice sets

---

packs/feat-effects/effect-ongoing-selfishness.json
packs/feat-effects/effect-selfish-shield.json

Upgrade Selfish Shield resistance based on Divine Smite

---

src/module/item/base/document.ts

Set default trait dictionary in `ItemPF2e.traitChatData` to `validTraits`

---

packs/feat-effects/effect-fresh-produce.json

Closes https://github.com/foundryvtt/pf2e/issues/14087

Fix Fresh Produce void resistance

---

packs/season-of-ghosts-bestiary/ijda.json

I renamed the remaster spells to the old names, but otherwise left them intact
Closes https://github.com/foundryvtt/pf2e/issues/14092

Fix Ijda's spellcasting

---

packs/equipment-effects/effect-glowing-lantern-fruit-lantern-light.json
packs/equipment/mechanical-torch.json
static/lang/re-en.json

Probably not worth migrating Mechanical Torch

Switch localizable strings used for Mechanical Torch and Glowing Lantern Fruit

---

src/module/apps/compendium-browser/tabs/base.ts
src/module/apps/sidebar/compendium-directory.ts
src/scripts/hooks/ready.ts

Make minisearch instances able to process words in non-roman scripts

---

packs/feats/munitions-crafter.json

Correct quantity of level-1+ alchemical ammo producible via Munitions Crafter

---

packs/spells/soothing-mist.json

Fix kind to be both damage and healing
Fix type to be vitality
Make persistent damage link autoleveling

Brush up Soothing Mist

---

src/module/actor/character/document.ts
src/module/actor/modifiers.ts
src/module/actor/roll-context/base.ts
src/module/actor/roll-context/types.ts

Retrieve updated check/damage domains from context clones

---

packs/feats/twin-distraction.json

Fix Twin Distraction Class DC

---

static/templates/items/consumable-details.hbs

Fix localization path to "Material Effects" label in consumable template

---

src/module/actor/roll-context/base.ts

Fix some regressions in constructing roll contexts

---

packs/spells/agitate.json

https://2e.aonprd.com/Spells.aspx?ID=566

Correct Agitate save as not Basic

---

packs/deities/haagenti.json

Add Haagenti to Deities

---

packs/equipment/chest.json

Closes https://github.com/foundryvtt/pf2e/issues/14157

Fix Bulk of chest

---

packs/equipment/escape-fulu.json

https://2e.aonprd.com/Equipment.aspx?ID=2033

Correct Escape Fulu activation action cost

---

src/module/canvas/token/object.ts

Prevent gaining vision from controlled tokens without at least observer ownership

---

packs/rusthenge-bestiary/clockwork-belimarius.json

Had some stats wrongly inherited from the clockwork mage

Fix Clockwork Belimarius

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
static/lang/en.json

Restore range penalties to strike attack rolls

---

packs/equipment/root-boots.json

Closes https://github.com/foundryvtt/pf2e/issues/14195

Fix price of Root Boots

---

packs/spells/dive-and-breach.json

Obvious enough Paizo error
Closes #14202

Remove attack trait from Dive and Breach

---

packs/season-of-ghosts-bestiary/arms-of-the-drowned.json

Closes https://github.com/foundryvtt/pf2e/issues/14209

Fix action type of Arms of the Drowned's Rising Waters and fix rarity

---

src/module/actor/party/sheet.ts

And include what the common language is as well.

Omit common language from party sheet languages

---

static/templates/chat/check/roll.hbs

Update data-whose attributes to reflect roller/opposer language

---

src/styles/actor/_inventory.scss
src/styles/actor/npc/_inventory.scss
static/templates/actors/npc/loot-sheet.hbs
static/templates/actors/npc/tabs/inventory.hbs

Closes https://github.com/foundryvtt/pf2e/issues/14229
I tested characters, party, npc, loot, the other loot, and vehicle.

Fix scroll and sizing on npc loot sheet (the actor one)

---

src/module/actor/army/document.ts
src/module/system/statistic/statistic.ts
static/lang/kingmaker-en.json

Closes https://github.com/foundryvtt/pf2e/issues/14260

Fix rolling army skills and initiative

---

packs/outlaws-of-alkenstar-bestiary/clockwork-fabricator.json
packs/the-slithering-bestiary/fuming-sludge.json

Fix Clockwork Fabricator's Constrict damage link

---

packs/feats/steal-vitality.json

Remaster Vampiric touch -> Vampiric feast

Fix prerequisite of steal vitality

---

packs/season-of-ghosts-bestiary/yuni.json

Closes https://github.com/foundryvtt/pf2e/issues/14294

Fix Yuni's level

---

src/module/system/check/check.ts

Fix check reroll flavor `opposer` resolution

---

packs/pfs-season-5-bestiary/conference-zs-victims-9-10.json
packs/pfs-season-5-bestiary/conference-zs-victims.json

Please double-check the DCs, as I don't have the PDF.
Closes https://github.com/foundryvtt/pf2e/issues/14295

Add links to Society and Religion for Conference Z's Victims

---

packs/kingmaker-bestiary/kargstaad.json

Closes https://github.com/foundryvtt/pf2e/issues/14321

Add cold damage partial to Kargstaad's Hatchet Strike

---

packs/age-of-ashes-bestiary/kralgurn.json
packs/feats/fearsome-brute.json

Also automate Kralgurn's Fearsome Brute
Closes https://github.com/foundryvtt/pf2e/issues/14339

Fix Fearsome Brute multiplier for master Intimidation

---

packs/classfeatures/the-distant-grasp.json
packs/classfeatures/the-infinite-eye.json
packs/classfeatures/the-oscillating-wave.json
packs/classfeatures/the-silent-whisper.json
packs/classfeatures/the-tangible-dream.json
packs/classfeatures/the-unbound-step.json

Remove surface cantrips as a choice for archetype psychics

---

packs/pathfinder-monster-core/banshee.json

Add Monster Core's Banshee

---

packs/pfs-season-5-bestiary/topiary-beast.json
packs/pfs-season-5-bestiary/topiary-monster.json

Fix stats of Topiary beast and monster

---

packs/spell-effects/spell-effect-cascade-countermeasure.json
packs/spells/cascade-countermeasure.json

Add effect for Cascade Countermeasure

---

packs/abomination-vaults-bestiary/belcorra-haruvex.json
packs/agents-of-edgewatch-bestiary/copper-hand-illusionist.json
packs/agents-of-edgewatch-bestiary/grabble-forden.json
packs/agents-of-edgewatch-bestiary/venom-mage.json
packs/agents-of-edgewatch-bestiary/water-elemental-vessel-i2.json
packs/agents-of-edgewatch-bestiary/water-elemental-vessel.json
packs/crown-of-the-kobold-king-bestiary/narlynark.json
packs/extinction-curse-bestiary/corrupted-priest.json
packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-20.json
packs/kingmaker-bestiary/darivan.json
packs/kingmaker-bestiary/defaced-naiad-queen.json
packs/kingmaker-bestiary/foras.json
packs/kingmaker-bestiary/melianse.json
packs/npc-gallery/necromancer.json
packs/paizo-pregens/jaithe.json
packs/pathfinder-bestiary-2/lunar-naga.json
packs/pathfinder-monster-core/changeling-exile.json
packs/pathfinder-monster-core/sweet-hag.json
packs/pfs-season-1-bestiary/blue-streak-mage-7-8.json
packs/pfs-season-1-bestiary/kip-the-druid-1-2.json
packs/pfs-season-1-bestiary/kip-the-druid-3-4.json
packs/season-of-ghosts-bestiary/noppera-bo-impersonator-primal.json
packs/spells/spider-sting.json
packs/strength-of-thousands-bestiary/grippli-jinxer.json
packs/strength-of-thousands-bestiary/kurshkin.json
packs/strength-of-thousands-bestiary/reborn-sun-mage.json

Also tidy description formatting
Refresh all copies
Closes https://github.com/foundryvtt/pf2e/issues/14359

Fix damage type of Spider Sting

---

packs/actions/gallop.json
packs/kingmaker-bestiary/windchaser.json
packs/outlaws-of-alkenstar-bestiary/daelum.json
packs/pathfinder-bestiary/pegasus.json
packs/pathfinder-bestiary/riding-horse.json
packs/pathfinder-bestiary/riding-pony.json
packs/pathfinder-bestiary/skeletal-horse.json
packs/pathfinder-bestiary/war-horse.json
packs/pathfinder-bestiary/war-pony.json
packs/pathfinder-monster-core/pegasus.json
packs/pathfinder-monster-core/pukwudgie.json
packs/pathfinder-monster-core/riding-horse.json
packs/pathfinder-monster-core/riding-pony.json
packs/pathfinder-monster-core/skeletal-horse.json
packs/pathfinder-monster-core/war-horse.json
packs/pathfinder-monster-core/war-pony.json
packs/pfs-season-1-bestiary/desert-wind.json
packs/pfs-season-1-bestiary/skeletal-mount.json
packs/pfs-season-1-bestiary/zombie-riding-horse.json
packs/pfs-season-1-bestiary/zombie-warhorse.json
packs/pfs-season-2-bestiary/brittle-skeletal-horse.json
packs/travel-guide-bestiary/baccali-alpaca.json

Add automation for Gallop

---

src/styles/actor/_index.scss
src/styles/actor/npc/_index.scss

Fix styling of action traits on familiar sheet

---

src/module/item/weapon/data.ts
src/module/system/damage/weapon.ts

Scale scatter damage with number of weapon damage dice

---

packs/rusthenge-bestiary/vloriak.json

Closes https://github.com/foundryvtt/pf2e/issues/14397

Fix action cost and inline damage of Vloriak's Spew Rusted Shards

---

packs/sky-kings-tomb-bestiary/hryngar-forgepriest.json

Closes https://github.com/foundryvtt/pf2e/issues/14405

Remove incorrect Agathion trait from Hryngar Forgepriest

---

packs/stolen-fate-bestiary/mighty-bul-gae.json

Closes https://github.com/foundryvtt/pf2e/issues/14429

Fix defenses and size of Mighty Bul-Gae

---

packs/agents-of-edgewatch-bestiary/lusca.json
packs/kingmaker-bestiary/immense-mandragora.json
packs/kingmaker-bestiary/mandragora-swarm.json
packs/pathfinder-bestiary-2/mandragora.json
packs/pathfinder-bestiary-3/piranha-swarm.json
packs/pathfinder-bestiary/bunyip.json
packs/pathfinder-bestiary/great-white-shark.json
packs/pathfinder-monster-core/great-white-shark.json
packs/pfs-season-1-bestiary/great-white-shark-pfs-1-12.json
packs/pfs-season-2-bestiary/bloodthirsty-razortoothed-shark.json
packs/pfs-season-2-bestiary/bruorsivi-mandragora.json
packs/pfs-season-2-bestiary/lesser-bruorsivi-mandragora.json
packs/pfs-season-2-bestiary/razortoothed-shark.json
packs/pfs-season-2-bestiary/saddleback-bunyip.json
packs/pfs-season-5-bestiary/germinated-mandragora.json
packs/sky-kings-tomb-bestiary/gray-worm.json
packs/strength-of-thousands-bestiary/giant-tsetse-fly.json

Also tidy up perception details of "blood scent, blood scent"
Closes https://github.com/foundryvtt/pf2e/issues/14430

Fix skill bonuses for Immense Mandragora

---

src/module/rules/rule-element/item-alteration/schemas.ts

Fixes Ferrous Form. Maybe some other things too.

Fix validation of override mode damage dice faces item alterations

---

src/module/apps/world-clock/app.ts
src/module/system/settings/world-clock.ts
src/scripts/config/index.ts

It turns out this was half done, so I'm now concerned if there's some gotcha I was not aware of.

Add world time setting for imperial calendar

---

packs/agents-of-edgewatch-bestiary/agradaemon.json
packs/agents-of-edgewatch-bestiary/water-elemental-vessel-i2.json
packs/agents-of-edgewatch-bestiary/water-elemental-vessel.json
packs/extinction-curse-bestiary/saurian-worldwatcher.json
packs/mwangi-expanse-bestiary/maliadi.json
packs/pathfinder-bestiary-2/crystal-dragon-ancient-spellcaster.json
packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
packs/pathfinder-bestiary-2/marrmora.json
packs/pathfinder-bestiary-3/hesperid-queen.json
packs/pathfinder-bestiary-3/lampad-queen.json
packs/pathfinder-bestiary-3/living-rune-primal.json
packs/pathfinder-bestiary-3/tolokand.json
packs/pathfinder-monster-core/adamantine-dragon-ancient-spellcaster.json
packs/pfs-season-3-bestiary/eltha-embercall-11-12-28-cp.json
packs/rage-of-elements-bestiary/ifrit-shuyookh.json
packs/spell-effects/spell-effect-volcanic-eruption.json
packs/spells/volcanic-eruption.json
packs/strength-of-thousands-bestiary/unshadowed-anchor-root.json

Also refresh all copies.
Closes https://github.com/foundryvtt/pf2e/issues/14423

Add effect, area, and leveled damage link for Volcanic Eruption

---

packs/feats/ghostly-resistance.json

Fix Ghostly Resistance definitions

---

src/scripts/config/traits.ts

Allow Relic Trait to be added to Armor and Shields

---

packs/paizo-pregens/simeek.json

Fix Simeek Attribute Modifiers

---

static/system.json

the other changes are format on save, is that fine or did it mess up some settings?

fix compendium folder for Tian Xia world guide Compendium

---

packs/iconics/kyra-level-1.json
packs/iconics/kyra-level-3.json
packs/iconics/kyra-level-5.json
packs/kingmaker-bestiary/tristian-level-10.json
packs/pfs-season-5-bestiary/blessed-uirch-of-the-burning-suns.json
packs/pfs-season-5-bestiary/uirch-of-the-burning-suns.json
packs/spells/fire-ray.json

Add inline damage link to Fire Ray

---

packs/crown-of-the-kobold-king-bestiary/cilios.json

Also tidy description of Blinding Rot and remove Mummy Rot

Fix Cilios's Fist attack effect to be Blinding Rot

---

packs/iconics/kyra-level-5.json

Closes https://github.com/foundryvtt/pf2e/issues/14478

Add a 5th slot to Kyra (Level 5)'s Divine Font

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/spellcasting-dialog.ts
src/module/item/physical/sheet.ts
static/templates/actors/character/partials/sidebar.hbs
static/templates/actors/spellcasting-dialog.hbs
static/templates/items/armor-details.hbs
static/templates/items/weapon-details.hbs

The `selectOptions` helper is pretty neat.

Convert more instances of the deprecated select handlebars helper to selectOptions

---

src/module/item/base/sheet/sheet.ts
src/module/item/physical/sheet.ts
src/module/item/weapon/sheet.ts
static/templates/items/mystify-panel.hbs
static/templates/items/physical-sidebar.hbs
static/templates/items/weapon-details.hbs
static/templates/partials/publication-data.hbs

I _think_ everything still works but I ran out of time to test it again.

Convert all select handlebars helper in weapon sheet to selectOptions

---

src/module/system/damage/weapon.ts
static/lang/en.json

Closes #14471
If accepted, please credit 3XC4L1B3R with this instead of me.

[3XC4L1B3R ] Add Twin Trait Damage Support

---

src/module/item/base/sheet/rule-element-form/actor-traits.ts

Closes https://github.com/foundryvtt/pf2e/issues/14455
I can remove the rule element validation. I'm 50/50 about it.

Support resolvables in actor traits form

---

src/styles/ui/sidebar/_actor-directory.scss

Update party actor styling for v12

---

packs/equipment/artisans-toolkit.json

Caught this while playing last night. Not sure if this is large enough to really merit a PR on it's own, but here it is nonetheless.

Fix typo in Artisan's Toolkit description

---

packs/familiar-abilities/familiar-focus.json

Made manually cause I don't have access to my normal PC to make a change as normal

Brush Up of action Familiar Focus

---

src/module/rules/rule-element/choice-set/rule-element.ts

Closes https://github.com/foundryvtt/pf2e/issues/14574

Run predicates on choice sets options loaded from a path

---

packs/season-of-ghosts-bestiary/spiritual-disruptor.json

Closes https://github.com/foundryvtt/pf2e/issues/14573

Add inline Intimidation check to Spiritual Disruptor

---

src/module/rules/rule-element/choice-set/rule-element.ts

Fixes issues like not selecting a champion key score bricking an actor.

Fix ignored choicesets not disabling other rule elements

---

src/module/actor/roll-context/base.ts

Closes https://github.com/foundryvtt/pf2e/issues/14575
Including both is a new feature but the crux is the bugfix.

Restore target marks for ephemerals, and include both origin and target marks

---

src/module/actor/familiar/document.ts

Internally affects certain event propagations for encounters, I think.
Closes https://github.com/foundryvtt/pf2e/issues/14496

Remove familiar from former master on change

---

src/module/item/effect/document.ts

Show effect badge label in message when formula is rolled

---

src/module/actor/base.ts
src/module/apps/sidebar/chat-log.ts
src/module/chat-message/data.ts
src/module/chat-message/document.ts
types/foundry/common/documents/chat-message.d.ts

A small section of the larger one to reduce the number of lines we have to deal with and review.
Modules are pretty much all breaking in v12 anyways, so attempting to shim them won't really work, and the changes I'm asking for are quite extensive to properly support that anyways. This also means though that time is of the essence for this refactor :(

(In3luki) Move ChatMessagePF2e appliedDamage flag to system data

---

src/module/rules/rule-element/roll-option/rule-element.ts

Closes https://github.com/foundryvtt/pf2e/issues/14584

Handle disabled RollOption toggles when merged

---

src/module/actor/npc/document.ts
src/module/chat-message/listeners/cards.ts

PF2E.ConsumableUseLabel no longer exists in en.json

Fix use consumable label

---

packs/season-of-ghosts-bestiary/argyrzei.json

Closes https://github.com/foundryvtt/pf2e/issues/14599

Fix order of Argyrzei's Silver Blade damage partials

---

packs/season-of-ghosts-bestiary/algriever.json

Closes https://github.com/foundryvtt/pf2e/issues/14598

Add inline damage roll to Algriever Venom

---

packs/pfs-season-5-bestiary/shadow-of-sezruth.json

Closes https://github.com/foundryvtt/pf2e/issues/14582

Fix name of Shadow of Sezruth

---

package-lock.json
package.json
static/system.json

I forgot this little important step

Update system version in manifest to 5.15.2

---

src/styles/actor/_spell-collection.scss
src/styles/actor/_spell-preparation.scss

Closes https://github.com/foundryvtt/pf2e/issues/14616

Fix spell description being centered

---

src/module/actor/base.ts
src/module/apps/sidebar/chat-log.ts
src/module/chat-message/data.ts
src/module/chat-message/document.ts
types/foundry/common/documents/chat-message.d.ts

Revert "Move ChatMessagePF2e appliedDamage flag to system data"

---

packs/iconics/kyra-level-3.json
packs/iconics/kyra-level-5.json
packs/pathfinder-monster-core/bone-prophet.json
packs/pathfinder-monster-core/greater-herexen.json
packs/pathfinder-monster-core/herexen.json
packs/pathfinder-monster-core/hryngar-taskmaster.json
packs/pathfinder-monster-core/kholo-bonekeeper.json
src/module/migration/migrations/916-new-pc-toys.ts

Also reran the existing migrations, fixing some -=inSlot errors. This update is beneath notice, it only affects people migrating from older builds (and run-migrations)

Update older migration for newer megaton strike

---

types/foundry/client-esm/applications/elements/prosemirror-editor.d.ts
types/foundry/client-esm/applications/elements/string-tags.d.ts
types/foundry/client-esm/canvas/edges/edge.d.ts
types/foundry/client-esm/canvas/sources/base-light-source.d.ts
types/foundry/client-esm/canvas/sources/rendered-effect-source.d.ts
types/foundry/client/config.d.ts
types/foundry/client/data/documents/combat.d.ts
types/foundry/client/pixi/board.d.ts
types/foundry/client/pixi/core/interaction/mouse-handler.d.ts
types/foundry/client/pixi/groups/effects.d.ts
types/foundry/client/pixi/layers/base/interaction-layer.d.ts
types/foundry/client/pixi/layers/controls/ruler.d.ts

Ruler types aren't done, but they're closer, so good enough for me.

Start on some of the type changes for 12.321

---

static/system.json

Update default folder colors using Rigo's suggestions

---

packs/pathfinder-monster-core/cuckoo-hag.json
packs/pathfinder-monster-core/dryad-queen.json
packs/pathfinder-monster-core/fortune-dragon-adult-spellcaster.json
packs/pathfinder-monster-core/fortune-dragon-ancient-spellcaster.json
packs/pathfinder-monster-core/gongorinan.json
packs/pathfinder-monster-core/iron-hag.json
packs/pathfinder-monster-core/keketar.json
packs/pathfinder-monster-core/norn.json
packs/pathfinder-monster-core/sea-hag.json
packs/pathfinder-monster-core/sweet-hag.json
packs/seven-dooms-for-sandpoint-bestiary/kaleb-valdemars-body.json
packs/seven-dooms-for-sandpoint-bestiary/tiluatchek.json
packs/spells/cursed-metamorphosis.json

Also add inline Will save
Closes https://github.com/foundryvtt/pf2e/issues/14653

Fix traditions of Cursed Metamorphosis

---

packs/feat-effects/effect-juvenile-flight.json
packs/feats/fledgling-flight.json
packs/feats/fully-flighted.json

Added Rule Elements for Strix Ancestry Feats for flight

Improve automation of Strix flight feats

---

src/module/actor/character/document.ts

Update character _preUpdate logic for v12

---

src/module/item/spell/document.ts

This fixes some cleanup bugs that exist in v11, but nothing v12 specific I imagine. Still better safe than sorry.

Update spell update/create cleanup

---

static/lang/en.json

Fix Tekko-Kagi casing in Base Weapon List

---

packs/equipment/borts-blessing.json

Add AE-Like to Bort's Blessing for Language

---

packs/book-of-the-dead-bestiary/faithless-ecclesiarch.json

Closes https://github.com/foundryvtt/pf2e/issues/14708

Fix spell attack and DC for Faithless Ecclesiarch

---

static/templates/items/rules/token-light.hbs

That one slipped through the crack.

Changes nameAttr to valueAttr in TokenLight RE template

---

types/foundry/client-esm/applications/elements/document-tags.d.ts
types/foundry/client-esm/applications/elements/form-element.d.ts
types/foundry/client-esm/applications/elements/range-picker.d.ts
types/foundry/client-esm/applications/elements/string-tags.d.ts
types/foundry/client-esm/applications/forms/fields.d.ts
types/foundry/client-esm/canvas/sources/point-darkness-source.d.ts
types/foundry/client-esm/canvas/sources/point-vision-source.d.ts
types/foundry/client/application/form-application/document-sheet/macro-config.d.ts
types/foundry/client/apps/form.d.ts
types/foundry/client/data/collections/scenes.d.ts
types/foundry/client/pixi/board.d.ts
types/foundry/client/pixi/groups/effects.d.ts
types/foundry/client/pixi/layers/base/interaction-layer.d.ts
types/foundry/client/pixi/layers/effects/visibility.d.ts
types/foundry/client/pixi/perception/vision-mode.d.ts
types/foundry/client/pixi/placeable.d.ts

Only up to placeable, and skips over the roll stuff since that will need a full update regardless.
Of note, placeables now have a getSnappedPosition(). It might be worth rechecking our template hacks.

Add some minor type updates for 12.323

---

src/styles/item/_index.scss

Avoid padding and wrapping around GM Notes

---

packs/equipment/celestial-peach-rejuvenation.json

Remove duplicate cleanse affiction (cuz remaster)
(Unsure if that's ok? Dunno what the official line for this happenings is)

Update Celestial Peach (Rejuvenation) to remove duplicate spells

---

packs/book-of-the-dead-bestiary/disembodied-voices.json
packs/feats/winter-sleet.json

also fix defenses and add reset time to Disembodied Voices hazard

Restore second paragraph of Winter Sleet

---

packs/abomination-vaults-bestiary/afflicted-irnakurse.json

Fix Afflicted Irnakurse's conditions

---

packs/kingmaker-bestiary/lesser-jabberwock.json
packs/pathfinder-bestiary-2/jabberwock.json

Closes https://github.com/foundryvtt/pf2e/issues/14757

Remove traits from Jabberwock's Claws That Catch

---

packs/kingmaker-bestiary/irovettis-fetch.json

Closes https://github.com/foundryvtt/pf2e/issues/14756

Fix regeneration value for Irovetti's Fetch

---

packs/agents-of-edgewatch-bestiary/ofalth-zombie.json

Remove vitality immunity from ofalth zombie

---

packs/abomination-vaults-bestiary/jafaki.json
packs/abomination-vaults-bestiary/observation-deck-seugathi-researcher.json
packs/abomination-vaults-bestiary/seugathi-reality-warper.json
packs/abomination-vaults-bestiary/seugathi-researcher.json
packs/abomination-vaults-bestiary/seugathi-servant.json
packs/pfs-season-5-bestiary/weak-cacophonous-hound-echo.json
packs/pfs-season-5-bestiary/weak-cosmic-amoeba.json
packs/pfs-season-5-bestiary/weak-hound-echo.json

Fix SpecialStatistic rules on Seugathi NPCs

---

packs/feat-effects/stance-winter-sleet.json

Fix Winter Sleet Stance for errata

---

src/module/actor/base.ts
src/scripts/config/index.ts

Add base system actor and item classes to `CONFIG.PF2E`

---

packs/feat-effects/stance-winter-sleet.json
packs/feats/inner-fire-naari.json

Update Inner Fire feat name

---

src/module/actor/data/base.ts
src/module/canvas/token/object.ts

A small addition to allow for creation of Eidolon Side By Side mechanics.
> Duplicated due to having to change base branches, as requested by Supe https://github.com/foundryvtt/pf2e/pull/14788#issuecomment-2123531565

Add support for canGangUp: eidolon

---

packs/bestiary-effects/effect-conduct.json
packs/classfeatures/devourer-of-decay.json
packs/classfeatures/ripple-in-the-deep.json
packs/classfeatures/whisper-of-wings.json
static/lang/re-en.json

Gave them some icons too, and localized the Concert Frog's Conduct effect as well.

Localize Howl of the Wild's Witch Patrons and Wild Witch Armaments

---

packs/ancestryfeatures/awakened-mind.json
packs/equipment/constricting-whip-tail.json
packs/other-effects/effect-aura-of-protection.json
static/lang/re-en.json

also closes #14801 while I'm at it.

Add missing Howl of the Wild localization

---

packs/pathfinder-bestiary-2/black-dracolisk.json
packs/pathfinder-bestiary-2/blue-dracolisk.json
packs/pathfinder-bestiary-2/green-dracolisk.json
packs/pathfinder-bestiary-2/red-dracolisk.json
packs/pathfinder-bestiary-2/white-dracolisk.json

It's a minor thing, but I believe the removal of current indirectness should improve readability.

Differentiate the descriptions of colored dracolisks' abilities

---

packs/spells/heal-companion.json

Closes https://github.com/foundryvtt/pf2e/issues/14825

Update Heal Companion spell to remaster

---

src/styles/_forms.scss

Covered by core now with the exception of cursor change

Remove (most of) styling of range inputs

---

packs/equipment/gun-sword.json

Fix Gun Sword to correct damage values

---

packs/spell-effects/spell-effect-sweet-dream.json

Selector fixes for Sweet Dream Insight and Sweet Dream Glamor, so that they only effect skill checks as they should

Selector fixes for Sweet Dream

---

packs/spell-effects/spell-effect-organsight.json

Fix Organsight spell effects to apply to spells as well

---

packs/bestiary-effects/effect-paired-spikes.json
packs/howl-of-the-wild-bestiary/alicorn.json
packs/howl-of-the-wild-bestiary/almiraj.json
packs/howl-of-the-wild-bestiary/apothecary-bee.json
packs/howl-of-the-wild-bestiary/ascendant-griffon.json
packs/howl-of-the-wild-bestiary/barded-manticore.json
packs/howl-of-the-wild-bestiary/blooming-guardian.json
packs/howl-of-the-wild-bestiary/carnotaurus.json
packs/howl-of-the-wild-bestiary/chaos-falcon.json
packs/howl-of-the-wild-bestiary/concert-frog.json
packs/howl-of-the-wild-bestiary/crying-cicada.json
packs/howl-of-the-wild-bestiary/decapod-dinghy.json
packs/howl-of-the-wild-bestiary/desert-manticore.json
packs/howl-of-the-wild-bestiary/drthak.json
packs/howl-of-the-wild-bestiary/flynkett.json
packs/howl-of-the-wild-bestiary/royal-basilisk.json

Brush up some bestiary automation for Howl of the Wild

---

package-lock.json
package.json
static/system.json

Increment version to 5.16.1

---

packs/spells/downpour.json

Add Area to Downpour spell

---

packs/actions/inured-to-death.json
packs/actions/rearrange-bones.json
packs/backgrounds/mortuarium-survivor.json
packs/bestiary-effects/effect-sepulchral-drain.json
packs/equipment/bottled-night.json
packs/equipment/nyctessas-staff.json
packs/equipment/plate-of-yled-greater.json
packs/equipment/plate-of-yled-major.json
packs/equipment/plate-of-yled-true.json
packs/equipment/plate-of-yled.json
packs/equipment/steadfast-sentinel.json
packs/equipment/steelscour-greater.json
packs/equipment/steelscour-lesser.json
packs/equipment/steelscour-major.json
packs/equipment/steelscour-moderate.json
packs/equipment/void-salts.json
packs/feats/read-the-dust.json
packs/feats/strategic-repose.json
packs/feats/undead-spotter.json
packs/heritages/skeleton/compact-skeleton.json
packs/heritages/skeleton/fodder-skeleton.json
packs/heritages/skeleton/monstrous-skeleton.json
packs/heritages/skeleton/shifting-skeleton.json
packs/heritages/skeleton/sturdy-skeleton.json
packs/npc-gallery/nyctessa.json
packs/spells/bonewall-bulwark.json
packs/spells/carrion-mire.json
packs/spells/deathless-march.json
packs/spells/osseous-cage.json
static/licenses/OpenGameLicense.md

Add content from Wake the Dead 4 and 5

---

packs/feats/wonder-worker.json

Fix pre-req formatting on Wonder Worker

---

packs/feat-effects/effect-change-shape-werecreature.json

Add Finesse to Wererat claw attack

---

packs/spells/wrathful-storm.json

Add Area and Heightening to Wrathful Storm

---

packs/classfeatures/ligneous-instinct.json

Fix Ligneous Instinct rage damage type

---

packs/feats/animal-fleetness.json
packs/feats/feeding-frenzy.json

Automate Animal Fleetness and Feeding Frenzy

---

packs/feat-effects/effect-shielding-wave.json

Also remove reference to missing prompt (I couldn't think of a good one, so left it as default)

Fix Shielding Wave to apply either acid or fire resistance

---

src/module/chat-message/roll-inspector.ts
src/module/system/damage/dialog.ts
src/module/system/damage/helpers.ts
static/templates/chat/roll-inspector.hbs

Handle upgrade dice in roll inspector and "none" showing even if there are dice

---

packs/pathfinder-bestiary-2/gylou.json
packs/pathfinder-monster-core/gylou.json

Closes https://github.com/foundryvtt/pf2e/issues/14952

Remove move trait from Gylou's Reflexive Grab

---

packs/spell-effects/spell-effect-fire-shield.json
packs/spells/glass-shield.json

- update Glass Shield to include the effect back into the description (effect was yeeted out sometime during the last update).
- Update damage for Glass Shield.
- Update Fire Shield to include Shield HP (which scales with level) and hardness.

Update Glass Shield and Fire Shield

---

packs/spells/chilling-darkness.json
packs/spells/holy-light.json

Also update Holy Light description
Closes https://github.com/foundryvtt/pf2e/issues/14933

Update Chilling Darkness to use target traits rather than overlay

---

src/module/rules/rule-element/strike.ts

Closes https://github.com/foundryvtt/pf2e/issues/14958

Make Strike attribute resolvable

---

packs/season-of-ghosts-bestiary/ren-mei-li.json

Closes #14980
Also fixes Crafting skill and current HP

Add missing action and fix skill on SoG NPC

---

packs/classfeatures/spore-order.json

Change Spore Order to correct skill training

---

packs/bestiary-effects/effect-mutilating-bite.json

Add Max Badge Value to Mutilating Bite
