- packs/highhelm-bestiary/pagulin.json
I didn't test, but this will make the migration actually succeed on this later.
> Fix Pagulin survival variant

- src/scripts/config/traits.ts
> Add Illusion to NPC Attack Traits

- packs/spell-effects/spell-effect-fire-shield.json
- packs/spells/fire-shield.json
- static/lang/re-en.json
- Update spell effect to account for variable hardness by using a toggle.
- Update spell heightening damage from +1 to +2 as per the description found in PC1.
> Improve automation of Fire Shield

- packs/campaign-effects/effect-stoop.json
Kingmaker Chapter 3 "The Old Sycamore" p. 121
> Add campaign effect for Stoop

- src/module/system/damage/weapon.ts
Closes https://github.com/foundryvtt/pf2e/issues/14431 and closes https://github.com/foundryvtt/pf2e/issues/13368,
> Fix Striking RE

- src/module/actor/sheet/popups/item-transfer-dialog.ts
- src/styles/actor/_item-transfer-dialog.scss
- static/templates/popups/item-transfer-dialog.hbs
Closes https://github.com/foundryvtt/pf2e/issues/15052
> Do not show item purchase give button to players

- packs/book-of-the-dead-bestiary/unrisen.json
Added the ability to the actor sheet -
Closes #15043
> add Grab Ability to Unrisen (BotD) actor

- src/module/rules/rule-element/token-image.ts
- src/styles/item/_rules.scss
- static/templates/items/rules/partials/resolvable-value.hbs
- static/templates/items/rules/token-image.hbs
Closes https://github.com/foundryvtt/pf2e/issues/14767
> Fix Token Image RE form converting path to an array

- src/module/actor/creature/values.ts
Closes https://github.com/foundryvtt/pf2e/issues/15060
> Allow motion sense to be imprecise or vague

- packs/ancestries/centaur.json
- packs/ancestryfeatures/mount.json
- packs/ancestryfeatures/robust.json
Closes https://github.com/foundryvtt/pf2e/issues/15053
> Add ancestry features to centaur

- packs/spell-effects/spell-effect-incendiary-aura.json
- packs/spells/incendiary-aura.json
Closes https://github.com/foundryvtt/pf2e/issues/15072
> Fix duration for Spell Effect: Incendiary Aura

- src/module/canvas/perception/modes.ts
> Remove optimizations in system detection modes

- src/module/system/damage/weapon.ts
> Add venomous trait automation

- src/module/actor/creature/values.ts
- static/lang/en.json
> Add surki language

- src/module/item/container/document.ts
This only fixes our measure self cyclical. Anything more involved will need a new algorithm.
> Fix data prep for self cyclical containers

- packs/bestiary-family-ability-glossary/ulgrem-axaan-ichor-trail.json
> add Ulgrem Axaan Ichor Trail ability

- src/module/actor/character/document.ts
> Prevent strike MAP adjustments from being applied twice

- src/module/actor/character/automatic-bonus-progression.ts
- src/module/item/armor/sheet.ts
- src/module/item/physical/runes.ts
- static/templates/items/armor-details.hbs
> Bring rune hiding on armor sheets in line with weapon sheets

- src/scripts/ui/inline-roll-links.ts
I missed a spot with actor resolution in the global listeners pr
> Fix regression with actor fallback and kingdom rolls in chat messages

- packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
> Add "ranged 100 feet" trait and hide Blindness note in Kingmaker NPC

- packs/equipment/thousand-pains-fulu-blade.json
- packs/equipment/thousand-pains-fulu-burl.json
- packs/equipment/thousand-pains-fulu-icicle.json
- packs/equipment/thousand-pains-fulu-needle.json
- packs/equipment/thousand-pains-fulu-stone.json
- packs/equipment/thousand-pains-fulu-void.json
> Correct Thousand Pains Fulu usage

- packs/equipment-effects/effect-lions-bite.json
- packs/equipment/lions-shield.json
- packs/rollable-tables/6th-level-permanent-items.json
- static/lang/re-en.json
Also choose better icon
Closes https://github.com/foundryvtt/pf2e/issues/15168
> Brush up Lion's Shield

- src/module/actor/character/attack-popouts.ts
- src/module/actor/character/elemental-blast.ts
- src/module/actor/character/sheet.ts
- src/module/chat-message/listeners/cards.ts
- src/scripts/config/traits.ts
- src/scripts/macros/hotbar.ts
As per https://github.com/foundryvtt/pf2e/pull/15083#issuecomment-2167091853
This also includes some `lint:fix`ing... hope github doesn't break because of this.
> Change Kineticist Blasts to use EffectTraits

- packs/book-of-the-dead-bestiary/fallen-champion.json
- packs/rusthenge-bestiary/ordwi.json
- packs/spells/unimpeded-stride.json
Follow-up to https://github.com/foundryvtt/pf2e/pull/15127
> Replace level with rank in actor-owned Unimpeded Stride

- packs/feats/feral-senses.json
- packs/feats/you-dont-smell-right.json
- static/lang/re-en.json
> Add rule elements to Feral Sense and You don't smell right feats

- src/module/actor/npc/document.ts
Reduce diff size of https://github.com/foundryvtt/pf2e/pull/15033 only. I will have to rebase.
> Refactor NPC skill gen code to look more like character's

- src/module/actor/familiar/document.ts
- static/lang/en.json
- static/templates/actors/familiar/sheet.hbs
Closes https://github.com/foundryvtt/pf2e/issues/14565
Closes https://github.com/foundryvtt/pf2e/issues/11601
Or at least, closes it as far as we're likely going to actually bother.
> Allow null attributes for pets

- packs/feat-effects/stance-buckler-dance.json
- packs/feat-effects/stance-disruptive-stance.json
- packs/feat-effects/stance-fanes-fourberie.json
- packs/feat-effects/stance-graceful-poise.json
- packs/feat-effects/stance-impassable-wall-stance.json
- packs/feat-effects/stance-mobile-shot-stance.json
- packs/feat-effects/stance-powder-punch-stance.json
- packs/feat-effects/stance-ricochet-stance.json
- packs/feat-effects/stance-rough-terrain-stance.json
- packs/feat-effects/stance-twinned-defense.json
- packs/feat-effects/stance-whirlwind-stance.json
- packs/spell-effects/spell-effect-incendiary-ashes-failure.json
- packs/spell-effects/spell-effect-incendiary-ashes-success.json
And add missing "by" after granted
> Remove colon in "Granted by" line in effects

- src/module/canvas/layer/template.ts
- types/foundry/client/pixi/layers/base/placeables-layer.d.ts
The highlight is snapped, but not the placement nor circle itself current.
> Use snapping mode when placing bursts and emanations as well

- types/foundry/client-esm/applications/elements/multi-select.d.ts
- types/foundry/client-esm/canvas/regions/geometry.d.ts
- types/foundry/client-esm/canvas/regions/mesh.d.ts
- types/foundry/client/data/documents/client-base-mixes.d.ts
- types/foundry/client/data/documents/scene.d.ts
- types/foundry/client/pixi/layers/controls/ruler.d.ts
- types/foundry/client/pixi/placeable.d.ts
- types/foundry/client/pixi/placeables/tile.d.ts
Also fix several miscellaneous type compilation errors
> Update type definition of `Tile` class for V12

- src/module/actor/character/document.ts
- src/module/actor/modifiers.ts
- src/module/actor/npc/data.ts
- src/module/actor/npc/document.ts
- src/module/actor/npc/sheet.ts
- src/module/actor/npc/skills-editor.ts
- src/module/actor/sheet/base.ts
- src/module/item/base/sheet/sheet.ts
- src/module/migration/migrations/932-npc-system-skills.ts
- src/module/migration/migrations/index.ts
- src/module/migration/runner/base.ts
- src/styles/actor/npc/_skills-editor.scss
- static/lang/en.json
- static/template.json
- static/templates/actors/npc/skills-editor.hbs
- static/templates/actors/npc/tabs/main.hbs
- static/templates/items/lore-details.hbs
If approved, tikael has asked that I run the migration itself piecemeal so he can review it in chunks rather than dropping the atomic egg.
Includes sample migration.
> Convert NPC skills and skill variants to system data

- packs/age-of-ashes-bestiary/bshez-sand-claws-shak.json
change +2 Resilient Scale Armor count from 2 to 1
closes #15216
> update equipment on NPC Bshez "Sand Claws" +2 Resilient Scale Armor

- static/lang/re-en.json
Tied to #15032 -
I'm doing this as a separate PR. Once #15032 gets merged, I'll work on adding rule elements to the feat to allow for the selection.
> Add Revolutionary Innovation to localization

- packs/pathfinder-bestiary-3/ostovite.json
Closes https://github.com/foundryvtt/pf2e/issues/15244
> Fix Ostovite's Bone Chariot weakness

- src/module/system/text-editor.ts
Closes https://github.com/foundryvtt/pf2e/issues/15198
> Fix inline checks using resolve double applying penalties

- src/module/actor/character/document.ts
- src/module/actor/party/kingdom/builder.ts
- src/module/apps/compendium-browser/tabs/spell.ts
- src/module/item/base/sheet/rule-element-form/base.ts
- src/module/item/base/sheet/sheet.ts
- src/module/item/physical/document.ts
- src/module/item/spell/sheet.ts
- src/module/migration/migrations/895-fix-variant-spell-traits.ts
- src/module/rules/rule-element/choice-set/rule-element.ts
- src/module/rules/rule-element/iwr/immunity.ts
- src/module/rules/rule-element/iwr/resistance.ts
- src/module/rules/rule-element/iwr/weakness.ts
- src/module/scene/token-document/document.ts
- src/module/system/damage/weapon.ts
Infuriating on some of these, but so it goes
> Convert all uses of `R.equals` to `R.isDeepEqual`

- src/module/apps/sidebar/chat-log.ts
- src/module/system/check/check.ts
- src/module/system/check/roll.ts
- src/module/system/damage/damage.ts
- types/foundry/client/application/sidebar/sidebar-tab/chat-log.d.ts
- types/foundry/client/roll.d.ts
> Divert from manual roll input for blind checks and damage rolls

- packs/feats/geomancer-dedication.json
> Move Terrain Attunement's toggle to theatre of the mind

- packs/spells/cauterize-wounds.json
This way it's not affected by effects like Courageous Anthem
> Make inline damage roll for Cauterize Wounds immutable

- src/module/chat-message/document.ts
- src/module/item/physical/document.ts
This does Actor.X.Item.Y.Item.Z crimes. Alternative of https://github.com/foundryvtt/pf2e/pull/15255
> Support retrieving sub items from messages (nested uuid variant)

- src/module/item/shield/document.ts
> Include weapon-compatible traits when generating weapon from shield

- src/module/actor/base.ts
- src/module/actor/creature/document.ts
- src/module/actor/party/document.ts
- src/module/actor/vehicle/document.ts
- src/styles/actor/hazard/_index.scss
- static/templates/actors/hazard/sheet.hbs
Closes https://github.com/foundryvtt/pf2e/issues/14444
> Add roll option and aelike re support to hazards

- src/module/actor/base.ts
- src/module/actor/party/document.ts
- types/foundry/client/data/documents/actor.d.ts
- types/foundry/common/documents/actor.d.ts
Closes https://github.com/foundryvtt/pf2e/issues/15349
> Prevent parties from being created or moved into folders

- src/scripts/hooks/drop-canvas-data.ts
> Fix detection of item drops on tokens

- src/scripts/ui/inline-roll-links.ts
This probably shouldn't be a longterm solution: once afflictions are in, the inline check should reference it for item roll options (including traits) exclusively.
> Include `@Check` traits as item traits

- packs/feats/favored-prey.json
Reported by joshnoodlesoup on Discord
> Fix typo in Favored Prey

- src/module/rules/rule-element/battle-form/rule-element.ts
- src/module/rules/rule-element/battle-form/schema.ts
Fixes one of the issues in #15335
> Add ownIfHigher to Battleforms AC

- packs/classfeatures/verdant-core-deviant-classification.json
> add special statistic rule element to Verdant Core deviant class

- packs/actions/recall-the-teachings.json
> update aid DC for Recall the Teachings action

- src/module/actor/base.ts
- src/module/scene/token-document/document.ts
- src/module/scene/token-document/sheet.ts
- static/lang/en.json
Prevents infinite recursion during initialization
> Force party actors to retain actor link

- src/styles/actor/_red-action-boxes.scss
- src/styles/actor/character/_actions.scss
- src/styles/actor/tabs/_actions.scss
- src/styles/actor/vehicle/_index.scss
- static/lang/en.json
- static/templates/actors/npc/partials/action.hbs
- static/templates/actors/partials/action.hbs
Also renames the tracking css class to frequency
> Minor whitespace cleanup for actions on npc sheet

- src/module/apps/sidebar/actor-directory.ts
- types/foundry/client/apps/app.d.ts
- types/foundry/client/apps/sidebar/document-directory.d.ts
This is a longstanding override to address an upstream issue that is now being addressed upstream!
> Remove `ActorDirectoryPF2e#_render`

- static/lang/en.json
- Changed any remaster term changes.
- Update instances of /r to use `@Damage`
> update Weapon Property Rune localization

- packs/menace-under-otari-bestiary/pugwampi-bb.json
- packs/monsters-of-myth-bestiary/kuworsys.json
- packs/npc-gallery/burglar.json
- packs/npc-gallery/guard.json
- packs/npc-gallery/jailer.json
- packs/npc-gallery/physician.json
- packs/outlaws-of-alkenstar-bestiary/atticus.json
- packs/pathfinder-bestiary-3/deimavigga.json
- packs/pathfinder-bestiary-3/nyktera.json
- packs/pathfinder-bestiary/balisse.json
- packs/pathfinder-bestiary/kolyarut.json
- packs/pathfinder-monster-core/balisse.json
- packs/pathfinder-monster-core/pugwampi.json
- packs/rage-of-elements-bestiary/faydhaan-shuyookh.json
- packs/strength-of-thousands-bestiary/pugwampi-sot.json
> add missing Perception bonuses to select NPCs

- src/module/canvas/helpers.ts
- src/module/canvas/ruler.ts
- src/module/canvas/token/object.ts
- types/foundry/client/pixi/placeable.d.ts
- types/foundry/client/pixi/placeables/template.d.ts
- types/foundry/client/pixi/placeables/token.d.ts
Also allow tiny tokens to be drag-measured to any location in a square
> Shrink down token footprint calculation

- src/module/apps/sidebar/item-directory.ts
Same as a936c47922fb59db6a38f3c593274192010680e2
> Remove `ItemDirectoryPF2e#_render`

- src/module/actor/character/document.ts
- src/module/actor/npc/document.ts
Basically, the -lore at the end if the sluggified name does not contain "lore" also needs to be applied to the lookup table, or it'll fail to map to an item when editing.
> Fix regression with updating lore skills if name collision avoidance occured

- packs/pathfinder-bestiary/demilich.json
> Add Eye Gems spellcasting entry for Demilich

- src/module/canvas/token/object.ts
- src/module/rules/rule-element/token-image.ts
- src/module/rules/synthetics.ts
- src/module/scene/token-document/document.ts
[video](https://github.com/user-attachments/assets/d983f088-38e0-4b4a-b654-62906b0ec70d)
> Add animation options to `TokenImageRuleElement`

- src/util/misc.ts
> Fix unicode word boundaries in `sluggify`

- packs/classfeatures/debilitating-strike.json
- packs/classfeatures/double-debilitation.json
... enabling the addition of homebrew debilitations.
> Add mergeable to Debilitating Strike

- packs/feats/krakens-call.json
> add `Merfolk` trait to Kraken's Call feat.

- packs/actions/spit-ambient-magic.json
> correct typo in Spit Ambient Magic damage formula.

- src/module/canvas/ruler.ts
> Fix tiny tokens not traversing waypoints during drag measurement

- src/module/actor/character/document.ts
- static/templates/actors/character/partials/strike.hbs
- static/templates/actors/character/tabs/actions.hbs
Closes https://github.com/foundryvtt/pf2e/issues/15507
> Fix hiding strikes in character sheet

- src/module/system/damage/damage.ts
- src/module/system/damage/iwr.ts
- src/module/system/damage/types.ts
- src/module/system/damage/weapon.ts
- static/lang/en.json
- static/templates/chat/damage/iwr-breakdown.hbs
> Avoid resistance-redirecting to immunities

- src/module/actor/character/sheet.ts
> Show duplicate elemental blasts at normal location on PC sheet

- src/module/system/damage/iwr.ts
> Handle Concussive trait against targets having both immunity and resistance to same damage type

- src/module/canvas/measured-template.ts
> Fix line template snapping

- static/templates/items/shield-details.hbs
> Fix reinforcing rune select option labels on shield sheet

- packs/feat-effects/effect-weapon-infusion.json
- packs/feats/weapon-infusion.json
> Fix domain of weapon infusion toggles

- static/lang/re-en.json
Edit inline roll for temporary hit points to fix due to Foundry parsing change. Closes #15422
> Fix Note text on Glutton's Jaw effect

- packs/age-of-ashes-bestiary/tarrasque-the-armageddon-engine.json
- packs/agents-of-edgewatch-bestiary/ghaele-of-kharnas.json
- packs/extinction-curse-bestiary/qurashith.json
- packs/extinction-curse-bestiary/xilvirek.json
- packs/pathfinder-bestiary-2/bastion-archon.json
- packs/pathfinder-bestiary-2/vrolikai.json
- packs/pathfinder-bestiary/ghaele.json
- packs/pathfinder-bestiary/lyrakien.json
- packs/pathfinder-bestiary/terotricus.json
- packs/pathfinder-bestiary/treerazer.json
Also combine some damage partials
> Remove alignment traits from NPC strikes

- packs/actions/affix-a-talisman.json
- packs/actions/avoid-notice.json
- packs/actions/borrow-an-arcane-spell.json
- packs/actions/defend.json
- packs/actions/detect-magic.json
- packs/actions/follow-the-expert.json
- packs/actions/hustle.json
- packs/actions/investigate.json
- packs/actions/repeat-a-spell.json
- packs/actions/scout.json
- packs/actions/search.json
- packs/actions/squeeze.json
- packs/actions/sustain-an-effect.json
feel free to change the header -
Closes #15595
> update Exploration Activities source and text to Player Core/GM Core

- src/module/actor/character/document.ts
> Apply item alterations to basic unarmed attack

- src/module/canvas/layer/template.ts
The change in #15624 made one of the check I added useless so this MR seeks to remove it.
> Remove Redundant Grid Type Logic

- src/module/item/spell/document.ts
> Add "signature" roll option to signature spells

- src/module/item/deity/document.ts
- static/template.json
> Add temporary measure to ensure `DeitySystemData#skill` is an array

- src/module/item/consumable/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/15623
> Remove repeating limitation for ammo with multiple uses

- packs/feat-effects/effect-weapon-infusion.json
- src/module/rules/rule-element/ae-like.ts
> Add optional `testDomains` field to AE-likes

- packs/classfeatures/the-oscillating-wave.json
> add max dice to Dice Number formula for Amped Redistribute Potential

- packs/spells/albatross-curse.json
- packs/spells/antlion-trap.json
- packs/spells/blood-in-the-water.json
- packs/spells/camel-spit.json
- packs/spells/confusing-cry.json
- packs/spells/croak-voice.json
- packs/spells/foraging-friends.json
- packs/spells/frog-tongue.json
- packs/spells/hidebound.json
- packs/spells/luring-wail.json
- packs/spells/primal-chorus.json
- packs/spells/sacred-beasts.json
- packs/spells/spirit-of-the-beast.json
- packs/spells/summon-stampede.json
> Add icons to remaining Howl of the Wild spells

- src/module/rules/rule-element/adjust-degree-of-success.ts
> Resolve injected properties in AdjustDegreeOfSuccess predicates

- static/lang/re-en.json
> Emphasize spell names in psychic amp description alterations

- packs/feats/robust-health.json
Untyped Bonus type -> Circumstance bonus
> Brushup Robust Health

- packs/equipment-effects/effect-bestial-mutagen-greater.json
- packs/equipment-effects/effect-bestial-mutagen-lesser.json
- packs/equipment-effects/effect-bestial-mutagen-major.json
- packs/equipment-effects/effect-bestial-mutagen-moderate.json
> Update Bestial Mutagen automation

- packs/feats/herbalist-dedication.json
> Add missing text and proficiency scaling for Herbalist dedication

- static/templates/items/armor-details.hbs
- static/templates/items/shield-details.hbs
- static/templates/items/weapon-details.hbs
> Fix zero option of fundamental rune select elements on item sheets

- packs/classfeatures/stylish-tricks.json
> Correct text on Stylish Tricks

- src/module/system/settings/homebrew/data.ts
- src/module/system/settings/homebrew/helpers.ts
- src/module/system/settings/homebrew/menu.ts
- src/scripts/config/index.ts
- static/lang/en.json
Also lockout existing armor/consumable traits from equipment traits
> Add support for homebrew shield traits

- packs/equipment-effects/effect-insight-coffee-greater.json
- packs/equipment-effects/effect-insight-coffee-lesser.json
- packs/equipment-effects/effect-insight-coffee-moderate.json
- static/lang/re-en.json
also make Insight Coffee effects compatible with it
Closes #15714
> Fix Certain Stratagem damage roll

- packs/feats/into-the-fray.json
- packs/feats/lightning-snares.json
- packs/feats/running-tackle.json
- packs/feats/swift-guardian.json
> Correct details on some PC2 archetype feats

- packs/feats/dracomancer.json
- packs/feats/kobold-breath.json
Just these two, the other ones have them as prerequisites
> Grant Draconic Exemplar to Kobolds using legacy feats

- packs/actions/mark-for-death.json
> Update Mark for Death action

- packs/feat-effects/effect-elemental-blood-magic-self.json
- packs/feat-effects/effect-fey-blood-magic.json
- packs/feat-effects/effect-imperial-blood-magic.json
> Update some blood magic effect descriptions

- packs/kingmaker-bestiary/bloom-cultist.json
- packs/kingmaker-bestiary/darivan.json
- packs/rage-of-elements-bestiary/vault-builder.json
- packs/rage-of-elements-bestiary/zephyr-the-west-wind.json
- packs/rage-of-elements-bestiary/zuhra-shuyookh.json
- Replaced earlier versions of spells that did not have assigned icons.
- Added icon and touched up the description of the Monstrous Bloom ritual for Darivan and the Bloom Cultists actors,
> update spells on miscellaneous actors

- src/module/chat-message/document.ts
- src/scripts/ui/user-visibility.ts
> Fix regression in metagame-setting-dependent hiding of damage-button cues

- packs/spell-effects/aura-angelic-halo.json
- packs/spell-effects/spell-effect-angelic-halo.json
> change Sustain toggle for Angelic Halo effect and aura

- src/module/system/settings/homebrew/data.ts
- src/module/system/settings/homebrew/helpers.ts
- src/module/system/settings/homebrew/menu.ts
At least so long as adding skills is the only option
> Shorten key for skills in `ModuleHomebrewData`

- packs/feats/advanced-herbalism.json
> correct Advanced Herbalism from Class Feature to Class Feat

- packs/feats/dragons-flight.json
> Add Dragonblood trait to Dragon's Flight feat.

- packs/kingmaker-bestiary/lickweed.json
> Correct typo on Kingmaker actor (Lickweed)

- packs/equipment/long-hammer.json
> Correct Long Hammer's rarity to common

- packs/feats/alchemical-assessment.json
> Update Alchemical Assessment description

- packs/spells/invisible-item.json
- packs/spells/leaden-steps.json
> Update Invisible Item and Leaden Steps spell data

- packs/pathfinder-monster-core/ghoul-stalker.json
Closes https://github.com/foundryvtt/pf2e/issues/15811
> Fix Ghoul Stalker's token name

- packs/feats/untamed-form.json
> add Howl of the Wild options to the Untamed Form feat.

- packs/feats/youre-next.json
- static/lang/re-en.json
> Add description override to You're Next depending on the class

- packs/pathfinder-monster-core/harpy.json
> Correct Harpy Hungry Winds action cost

- packs/equipment/barding-of-the-zephyr.json
- packs/equipment/waverider-barding.json
> change Barding of the Zephyr and Waverider Barding to armor

- packs/equipment/barding-saddle.json
> update Barding Saddle to armor

- packs/feats/inner-strength.json
- packs/feats/scars-of-steel.json
- packs/feats/scouring-rage.json
- packs/feats/wounded-rage.json
- Add toggle for Scars of Steel
- Fix source on Inner Strength
- Fix typo and update damage roll on Scouring Rage
- Add rage self applied effect to Wounded Rage
> Brush up some Barbarian feats

- src/module/system/text-editor.ts
- src/scripts/ui/inline-roll-links.ts
> Fix DC label in check when rolling an inline roll with against

- packs/classfeatures/the-oscillating-wave.json
- packs/spell-effects/spell-effect-fire-shield.json
Supersedes #15845 
Closes #15822
> Brush up Fire Shield effect

- packs/feat-effects/effect-treat-wounds-immunity.json
> Update the icon for Treat Wounds Immunity

- packs/feats/tengu-weapon-familiarity.json
> Restrict weapon proficiency granted by Tengu Weapon Familiarity

- packs/classfeatures/bloodline-shadow.json
- packs/classfeatures/ligneous-instinct.json
also missed a second instance of a localization mistake on Shadow Bloodline, so here it goes
Closes #15870
> Add Barbarian Ligneous Instinct's speed decrease

- packs/pathfinder-monster-core/aeolaeka.json
- packs/prey-for-death-bestiary/the-first-blade.json
- packs/prey-for-death-bestiary/valkyrie-of-gorum.json
- packs/prey-for-death-bestiary/valkyrie-tempest.json
- packs/spells/weapon-storm.json
Also fix variant labels to be more alteration-friendly
> Update Weapon Storm's description to include area

- packs/spells/rejuvenating-flames.json
I caught this one while checking on pending requests (#14614).
> update healing dice roll for Rejuvenating Flames spell

- packs/classfeatures/bloodline-shadow.json
- packs/feats/tap-into-blood.json
- static/lang/re-en.json
Also third time is the charm with the Shadow Bloodline localization. Turns out it had a different path than everything else, my bad.
> Add description alterations for Tap Into Blood

- packs/feats/dirty-trick.json
> Allow Dirty Trick to be taken beyond level 1

- packs/actions/quick-tempered.json
This will help remind Barbarian's of the new rule to Rage on Initiative
> Add Note on Initiative to Quick Tempered

- packs/equipment/hammer-gun.json
> Correct Hammer Gun ranged usage damage type

- packs/spell-effects/spell-effect-light.json
Change to a more natural white and drop the alpha
> Lower the color intensity of the Light spell effect

- src/module/actor/conditions.ts
This enables Player Core 2 Oracle curses automation
> Add `cursebound` getter to `ActorConditions`

- packs/feats/duos-aim.json
- static/lang/re-en.json
Logic of Sniper's Aim ported over.
Fixes #14790
> Add automation to Duo's Aim

- src/module/rules/rule-element/choice-set/rule-element.ts
> Skip validation of choice set preselections

- packs/tian-xia-world-guide-bestiary/five-color-orchid-mantis.json
> add perception score and Darkvision to Five-colored Orchid Mantis Actor

- packs/equipment-effects/effect-taljjaes-mask-the-general.json
- packs/equipment-effects/effect-taljjaes-mask-the-hero.json
- packs/feats/archers-aim.json
some equipment effects were using them as well
Closes #14703
> Update weapon group selectors in Archer's Aim

- src/module/system/text-editor.ts
- static/templates/system/effects-panel.hbs
Closes #15924, supersedes #15971
> Retrieve items by UUID from Effects Panel for inline rolls

- packs/agents-of-edgewatch-bestiary/carvey.json
- packs/blog-bestiary/floolf.json
- packs/blood-lords-bestiary/zombie-chuul.json
- packs/fists-of-the-ruby-phoenix-bestiary/dromornis.json
- packs/stolen-fate-bestiary/derhii.json
Add automation for Dromornis's Rushing Attack.
Remove some unneeded roll links.
Brush up Floolf:
https://paizo.com/community/blog/v5748dyo6shme?Oops-We-Did-It-Again-Foolish-Monsters-2021-A
> Fix some NPC perception bonuses

- packs/one-shot-bestiary/doatara-the-poisoner.json
- packs/one-shot-bestiary/doatara-the-priest.json
> remove duplicate attacks from One-shot actors

- packs/feats/bleed-out.json
> correct action type for Bleed Out sorcerer feat

- packs/pathfinder-monster-core/dybbuk.json
Closes https://www.reddit.com/r/Pathfinder2e/comments/1enu87z/so_who_else_finds_incorporeal_being_resistant_to/
> Add "spirit" to Dybbuk's resist-all exceptions

- packs/feats/visual-fidelity.json
- add "see-invisibility" sense RE
Closes #15987
> brush up Visual Fidelity feat

- packs/backgrounds/town-troublemaker.json
> add Dirty Trick feat to Town Troublemaker background

- packs/paizo-pregens/the-tin-wizard.json
> brush up the Tin Wizard actor

- packs/bestiary-effects/effect-electricity-absorption.json
- packs/bestiary-family-ability-glossary/zombie-shock-arcing-strikes.json
- packs/outlaws-of-alkenstar-bestiary/disgorged-zombie.json
- packs/outlaws-of-alkenstar-bestiary/shock-zombie.json
Also add Note automation to (Zombie, Shock) Arcing Strikes
> Add effect for Electricity Absorption

- packs/classfeatures/sparkling-targe.json
> update rule element for Sparkling Targe to account for other traits

- packs/feats/sentinel-dedication.json
- updated rule element to add Heavy Armor proficiency if the actor meets the requirement
> update Sentinel Dedication rule elements to add Heavy Armor

- static/lang/en.json
> Link confused condition on Ashen rune notes

- packs/pathfinder-monster-core/shining-child.json
> add Spell Riposte spell to Shinning Child actor

- packs/equipment/curare.json
Closes https://github.com/foundryvtt/pf2e/issues/16057
> Brush up Curare

- static/templates/chat/strike-card.hbs
> Fix NPC strike image in messages generated by action macro

- packs/spells/chthonian-wrath.json
Replacing Abyssal Wrath into Chthonian Wrath in the name of the variants of the spell
> Renaming of variants of chthonian wrath

- packs/feats/sticky-bomb.json
> Update Sticky Bomb feat to now use class feature

- packs/classfeatures/armor-mastery.json
- packs/classfeatures/mighty-rage.json
- packs/outlaws-of-alkenstar-bestiary/anjelique-loveless.json
> Fix Barbarian Armor Mastery

- packs/classfeatures/arcane-cascade.json
Closes #16068 - see the issue for more details.
> update Arcane Cascade class feature RE to correct for malformed response

- packs/equipment/obsidian-edge-greater.json
- packs/equipment/obsidian-edge-major.json
- packs/equipment/obsidian-edge-true.json
- packs/equipment/obsidian-edge.json
> Fix Obsidian Edge base damage and range

- packs/equipment/camouflaging-chromatophores-greater.json
- packs/equipment/camouflaging-chromatophores-lesser.json
- packs/equipment/chair-storage.json
- packs/equipment/cipher-of-elemental-planes.json
- packs/equipment/doctrine-of-blissful-eternity.json
- packs/equipment/eidolon-cape.json
- packs/equipment/empathic-cords.json
- packs/equipment/empathy-charm.json
- packs/equipment/giant-catch-pole.json
- packs/equipment/gills.json
- packs/equipment/grimoire-of-unknown-necessities.json
- packs/equipment/singing-stone.json
- packs/equipment/storage.json
- packs/equipment/subtle-armor.json
- packs/equipment/sun-dazzler.json
- packs/equipment/tubeworm-gland.json
- packs/equipment/tyrants-writs.json
- packs/equipment/verdant-branch.json
- packs/equipment/violet-ray.json
- packs/equipment/violin-of-the-waves.json
- packs/equipment/weapon-harness.json
> give unique Core icons to Equipment items

- src/scripts/macros/treat-wounds.ts
> Fix Treat Wounds macro always using Risky Surgery given presence of feat

- packs/feats/agonizing-rebuke.json
the formula contradicted the description text.
> Fix formula for damage based on proficiency on agonizing rebuke

- packs/age-of-ashes-bestiary/barushak-il-varashma.json
- packs/spell-effects/spell-effect-fortify-summoning.json
- packs/spells/cordyceps-command.json
- packs/spells/fortify-summoning.json
> Update Fortify Summoning effect to remaster

- packs/rollable-tables/madcap-top-effect.json
Closes https://github.com/foundryvtt/pf2e/issues/16117
> Brush up Madcap Top roll table

- src/module/system/damage/iwr.ts
> Test against crit immunity exceptions when processing IWR

- packs/feats/portents-of-the-haruspex.json
- remove self-applying effect (should be applied to the enemy.
Closes #16133
> brush up Portents of Haruspex

- src/module/user/sheet.ts
- src/styles/_user.scss
- src/styles/main.scss
- static/templates/user/sheet.hbs
> Work around some upstream style quirks in `UserConfig`

- packs/feats/no-escape.json
Probably the result of some batch job.
> Remove incorrect link to Escape action in No Escape

- packs/actions/breath-weapon.json
- Should now use the correct path towards the localization
> correct localization for Breath Weapon action

- src/styles/_tags.scss
> Revert "Fix regression in coloration of trait tags"

- packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
- packs/equipment/dragon-rune-bracelet.json
- packs/equipment/ring-of-maniacal-devices-greater.json
- packs/equipment/ring-of-maniacal-devices.json
- packs/equipment/ring-of-recalcitrant-wishes.json
- packs/equipment/winders-ring.json
- packs/rollable-tables/11th-level-permanent-items.json
- packs/rollable-tables/18th-level-permanent-items.json
Update to remaster text
Add Thieves' Toolkit link
Tidy REs
Remove unneeded labels
> Brush up Ring of Maniacal Devices

- packs/equipment/cauthooj-bagpipes.json
- packs/equipment/clothing-desert.json
- packs/equipment/communion-mat.json
- packs/equipment/corrosive-engravings.json
- packs/equipment/dweomerveil.json
- packs/equipment/extendable-tail.json
- packs/equipment/final-blade.json
- packs/equipment/fossil-fragment-amber-mosquito.json
- packs/equipment/fossil-fragment-brontosaurus-phalange.json
- packs/equipment/fossil-fragment-deinonychus-claw.json
- packs/equipment/fossil-fragment-eurypterid-paddle.json
- packs/equipment/fossil-fragment-petrified-wood.json
- packs/equipment/fossil-fragment-triceratops-frill.json
- packs/equipment/fossil-fragment-tyrannosaur-tooth.json
- packs/equipment/harrow-spellcards.json
- packs/equipment/horrid-figurine.json
- packs/equipment/palanquin-of-night.json
- packs/equipment/pontoon.json
- packs/equipment/quick-change-outfit.json
- another round of these.
I need more tokens!!
> update icons for equipment items

- packs/kingmaker-bestiary/the-dancing-lady.json
Closes https://github.com/foundryvtt/pf2e/issues/16158
> Fix level of The Dancing Lady

- packs/heritages/versatile-heritages/dragonblood.json
> Set dragonblood rarity to uncommon

- packs/equipment/arboreal-boots-greater.json
> correct bonus for Greater Arboreal Boots

- packs/equipment/bottled-catharsis-lesser.json
- packs/equipment/bottled-catharsis-minor.json
- packs/equipment/surging-serum-lesser.json
- packs/equipment/surging-serum-minor.json
> update Bottled Catharsis and Surging Serum variants

- packs/equipment-effects/effect-potency-crystal-greater.json
- packs/equipment-effects/effect-potency-crystal-major.json
- packs/equipment-effects/effect-potency-crystal.json
> update duration and description for Potency Crystal effects

- packs/classfeatures/animal-instinct.json
> Add morph and primal traits to Rage action from Animal Instinct

- packs/ancestries/goblin.json
> Update Goblin publication data

- src/scripts/macros/treat-wounds.ts
- static/lang/action-en.json
Plus make general cleanup pass
> Kill the jquery in Treat Wounds macro

- src/module/chat-message/document.ts
- src/module/scene/helpers.ts
- src/module/scene/token-document/document.ts
- src/styles/legacy/_chat.scss
- src/styles/ui/sidebar/chat/_index.scss
- types/foundry/client/core/image.d.ts
> Add token images to chat messages

- packs/feats/goring-charge.json
> Add missing dice number to Goring Charge's rule element

- src/module/item/condition/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/16200
> Set default condition roll option prefix

- build/lib/compendium-pack.ts
- src/module/actor/base.ts
- src/module/actor/character/document.ts
- src/module/actor/data/base.ts
- src/module/item/base/data/system.ts
- src/module/item/base/document.ts
- src/module/item/consumable/document.ts
- src/module/migration/migrations/711-heritage-items.ts
- src/module/migration/migrations/719-shrug-flanking.ts
- src/module/migration/migrations/720-update-spell-descriptions.ts
- src/module/migration/migrations/723-cumulative-item-bonuses.ts
- src/module/migration/migrations/747-fixed-heightening.ts
- src/module/migration/migrations/766-wipe-url-sources.ts
- src/module/migration/migrations/794-add-wild-shape-choices.ts
- src/module/migration/migrations/800-self-effect-panache-rage.ts
- src/module/migration/migrations/841-v11-uuid-format.ts
- src/module/migration/migrations/917-scroll-wand-spell-ids.ts
- src/module/migration/migrations/923-kineticist-restructure.ts
- src/module/rules/rule-element/grant-item/rule-element.ts
- src/scripts/macros/hotbar.ts
- src/scripts/macros/raise-a-shield.ts
- src/util/uuid.ts
- types/foundry/common/data/fields.d.ts
- types/foundry/common/documents/actor.d.ts
- types/foundry/common/documents/item.d.ts
- types/foundry/common/documents/module.d.ts
> Switch to use of `_stats.compendiumSource` instead of `flags.core.sourceId`

- packs/ancestries/halfling.json
> Update Halfling ancestry publication to remaster

- packs/bestiary-effects/effect-lawbringer.json
- packs/outlaws-of-alkenstar-bestiary/atticus.json
- packs/outlaws-of-alkenstar-bestiary/corrupt-shieldmarshal-clan-pistol.json
- packs/outlaws-of-alkenstar-bestiary/corrupt-shieldmarshal-jezail.json
- packs/outlaws-of-alkenstar-bestiary/gunmarshal.json
- static/lang/re-en.json
Add effect using TokenMark
Add automation for speed bonus
Fix damage die size
> Brush up NPC Lawbringer ability

- packs/feats/vicious-incisors.json
> correct slugs on Vicious Incisors feat

- packs/spells/blessed-boundary.json
> correct action cost for Blessed Boundary spell

- packs/feats/vicious-incisors.json
change from `item:x` to `item:slug:x` per @stwlam
> brush up Vicious Incisors feat RE

- packs/quest-for-the-frozen-flame-bestiary/azi.json
> Correct spellcasting entry for Azi (NPC)

- packs/pathfinder-bestiary/giant-scorpion.json
- packs/pathfinder-monster-core/giant-scorpion.json
- packs/pfs-season-4-bestiary/mutated-scorpion.json
Closes https://github.com/foundryvtt/pf2e/issues/16257
> Fix save type of Giant Scorpion Venom

- packs/mwangi-expanse-bestiary/charau-ka-butcher.json
> Correct stats for Charau-ka butcher Actor

- packs/classfeatures/medium-armor-mastery.json
It's one of the Alchemist's class features.
> Update Medium Armor Mastery publication to PC2

- packs/feats/sanctify-water.json
> Update prerequisites for Sanctify Water feat

- packs/feats/sleek-reposition.json
Closes https://github.com/foundryvtt/pf2e/issues/16249
> Fix action type and cost of Sleek Reposition

- packs/age-of-ashes-bestiary/dragonstorm-fire-giant.json
- packs/pathfinder-bestiary/fire-giant.json
Also remove unneeded inline rolls in description and remove unneeded unlocalized labels
> Fix selectors for Dragonstorm Blade

- packs/feat-effects/effect-kishin-rage.json
- packs/feat-effects/effect-oni-form.json
- packs/feats/dokkaebi-fire.json
- packs/feats/flames-of-vision.json
- packs/feats/kishin-rage.json
- packs/feats/oni-rampage.json
- packs/feats/oni-weapon-familiarity.json
- packs/feats/storming-gaze.json
- packs/feats/tempest-gaze.json
- packs/feats/whispers-in-the-night.json
- packs/heritages/goblin/dokkaebi-goblin.json
- packs/heritages/versatile-heritages/hungerseed.json
- static/lang/re-en.json
Some Oni horns automation still left to do once an underlying bug is fixed
> Audit TXCG Goblin and Oni ancestry feats

- packs/feats/twirl-through.json
Closes https://github.com/foundryvtt/pf2e/issues/16306
> Fix level of Twirl Through

- src/scripts/config/traits.ts
> Add missing Processed trait description

- src/module/actor/data/iwr.ts
- src/module/system/damage/iwr.ts
> Fix processing of critical hits immunities

- src/module/rules/rule-element/grant-item/rule-element.ts
- src/util/uuid.ts
Closes https://github.com/foundryvtt/pf2e/issues/16299
> Include world items when granting items

- static/templates/items/rules/token-light.hbs
> Add blank option to TokenLight RE form's animation type

- packs/feats/majestic-presence.json
> Update Action Cost for Majestic Presence

- packs/gatewalkers-bestiary/ainamuuren.json
Closes https://github.com/foundryvtt/pf2e/issues/16376
> Fix Ainamuuren's Horns cold damage partial

- src/module/chat-message/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/16364
> Show active token image rather than the prototype token

- packs/feats/airborne-form.json
> Add `Evolution` trait to the Airborne Form feat

- packs/equipment/choleric-contagion.json
> Add `injury` trait and unique icon to Choleric Contagion

- packs/feats/clawdancer-dedication.json
- packs/feats/shieldmarshal-dedication.json
- packs/journals/archetypes.json
> add entries for Clawdancer and Shieldmarshal dedications to the Archetypes journal

- packs/curtain-call-bestiary/anguish-siktempora.json
- packs/pathfinder-bestiary-3/hatred-siktempora.json
- packs/pathfinder-bestiary-3/love-siktempora.json
- packs/pathfinder-bestiary-3/misery-siktempora.json
- packs/pathfinder-bestiary-3/triumph-siktempora.json
- packs/strength-of-thousands-bestiary/contemplative-meditant.json
- packs/strength-of-thousands-bestiary/contemplative-mentor.json
Also update automation for Temporal Sense for Contemplative Meditant and Contemplative Mentor
> Add Note reminder to Uncanny Pounce

- packs/classfeatures/zoophonia.json
Noticed this one while working the Condense class feature.
> Update icon for Zoophonia class feature

- packs/feats/mauler-dedication.json
> Include advanced weapons in Mauler Dedication's critical specialization

- packs/pathfinder-monster-core/seraptis.json
> Update Seraptis Actor proficiencies

- packs/feats/work-yourself-up.json
> Correct Action Cost for Work Yourself Up feat

- static/lang/re-en.json
also update the Spellswapping localization to bolden.
Closes #16445
> Correct labels in Improved Invigorating Elixir localization

- packs/spell-effects/spell-effect-dragon-form-adamantine.json
- packs/spell-effects/spell-effect-dragon-form-conspirator.json
- packs/spell-effects/spell-effect-dragon-form-diabolic.json
- packs/spell-effects/spell-effect-dragon-form-empyreal.json
- packs/spell-effects/spell-effect-dragon-form-fortune.json
- packs/spell-effects/spell-effect-dragon-form-horned.json
- packs/spell-effects/spell-effect-dragon-form-mirage.json
- packs/spell-effects/spell-effect-dragon-form-omen.json
> Remove vestigial horn statistics from Dragon Form spell effect

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/index.ts
- src/module/actor/character/data.ts
- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
- src/module/migration/migrations/774-unpersist-crafting-entries.ts
Should lead to no real discernable changes. Another PR to make the future diff more manageable.
> Internally rename CraftingEntry to CraftingAbility

- packs/pathfinder-bestiary-2/ice-yai.json
- packs/pathfinder-monster-core/snow-oni.json
Closes https://github.com/foundryvtt/pf2e/issues/16473
> Remove fire trait from Icy Deflection and brush up automation

- src/module/item/base/sheet/rule-element-form/base.ts
- src/module/item/base/sheet/rule-element-form/token-image.ts
- src/module/rules/rule-element/token-image.ts
- src/module/rules/synthetics.ts
- src/module/scene/token-document/document.ts
- static/lang/re-en.json
- static/templates/items/rules/token-image.hbs
> Add support for changing token ring subject via TokenImage RE

- packs/equipment/warpwobble-poison.json
> Add injury and mental traits to Warpwobble Poison

- packs/ancestryfeatures/animal-attack.json
Closes https://github.com/foundryvtt/pf2e/issues/16495
> Add some base types to Animal Attack

- packs/feats/oni-weapon-familiarity.json
> Remove unneeded martial weapon restriction from Oni Weapon Familiarity predicate

- packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
- packs/pathfinder-monster-core/conspirator-dragon-adult.json
- packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
- packs/pathfinder-monster-core/conspirator-dragon-ancient.json
- packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
- packs/pathfinder-monster-core/conspirator-dragon-young.json
- packs/prey-for-death-bestiary/vatumledor.json
> Fix rules on Conspirator Dragons

- packs/ancestries/kitsune.json
- packs/ancestryfeatures/change-shape.json
- packs/feats/myriad-forms.json
- packs/heritages/kitsune/celestial-envoy-kitsune.json
- packs/heritages/kitsune/dark-fields-kitsune.json
- packs/heritages/kitsune/earthly-wilds-kitsune.json
- packs/heritages/kitsune/empty-sky-kitsune.json
- packs/heritages/kitsune/frozen-wind-kitsune.json
- packs/heritages/kitsune/palace-echoes-kitsune.json
> Fix automation of Kitsune Change Shape

- packs/equipment/helm-of-zeal-greater.json
- packs/equipment/sash-of-prowess-greater.json
fixes greater version of items having the cost of the regular version of the item
> Fix prices of "Greater Helm of Zeal" and "Greater Sash of Prowess"

- packs/equipment-effects/effect-command-bravery.json
- packs/equipment-effects/effect-holy-chain.json
- packs/equipment/holy-chain.json
- packs/equipment/unholy-plate.json
- packs/equipment/warleaders-bulwark-greater.json
- packs/equipment/warleaders-bulwark.json
- static/lang/re-en.json
Also remove an unlocalised roll option from Holy Chain, italicise a reference to the item name, and make its light a bit less bright
> Automate Unholy Plate and update Warleader's Bulwark effect

- packs/wardens-of-wildwood-bestiary/durnolith.json
> Add agile trait to Durnolith claw attack

- packs/equipment/copper-pieces.json
- packs/equipment/gold-pieces.json
- packs/equipment/platinum-pieces.json
- packs/equipment/silver-pieces.json
> Update publication source for currency

- packs/classfeatures/exalted-reaction.json
> Add missing Item Alteration for Redemption cause Exalted Reaction

- packs/impossible-lands-bestiary/fleshforged-conformer.json
> Correct spell link for Fleshforged Conformer Wear Flesh ability

- packs/classfeatures/animal-instinct.json
- packs/classfeatures/bard-weapon-expertise.json
- packs/classfeatures/decay-instinct.json
- packs/classfeatures/dragon-instinct.json
- packs/classfeatures/fury-instinct.json
- packs/classfeatures/giant-instinct.json
- packs/classfeatures/ligneous-instinct.json
- packs/classfeatures/spirit-instinct.json
- packs/classfeatures/superstition-instinct.json
- packs/feats/unstoppable-juggernaut.json
- static/lang/re-en.json
> Fix Unstoppable Juggernaut and automate Superstition's Raging Resistance

- packs/actions/spit-ambient-magic.json
> Correct typo in Spit Ambient Magic inline damage roll

- packs/equipment-effects/effect-clay-sphere-weapon-damage-increase.json
> Use Damage Alteration to increase die size in Clay Sphere effect

- static/templates/actors/npc/tabs/spells.hbs
> Update NPC Spells template to support Spellcasting RollOptions

- packs/feats/and-will-do-so-once-more.json
This feat modifies the trigger conditions for "All This Will Happen Again" Samsaran feat, so I've added the text of the modification as an item alteration for the original feat.
> Add ItemAlteration to 'And Will Do So Once More' Feat

- packs/classfeatures/gymnast.json
> Add bravado trait roll option to Reposition on Gymnast swashbuckler style

- packs/equipment-effects/effect-tremorsensors.json
- packs/equipment/arachnolute.json
- packs/equipment/armor-latches.json
- packs/equipment/eyecatcher.json
- packs/equipment/falconsight-eye.json
- packs/equipment/frog-chair.json
- packs/equipment/mask-of-mercy.json
- packs/equipment/pelagic-helmet.json
- packs/equipment/printing-press.json
- packs/equipment/rappelling-kit.json
- packs/equipment/sifting-pan.json
- packs/equipment/spider-chair.json
- packs/equipment/spyglass-eye.json
- packs/equipment/steam-winch.json
- packs/equipment/swooping-wings.json
- packs/equipment/thrasher-tail.json
- packs/equipment/tlil-mask-greater.json
- packs/equipment/tlil-mask.json
- packs/equipment/toxic-blood.json
- packs/equipment/tracking-tag.json
- packs/equipment/tremorsensors.json
- packs/equipment/wrenchgear.json
> Add unique icons to equipment items

- packs/age-of-ashes-bestiary/dalos.json
> Fix predicate on Dalos' Heat Rock

- static/lang/en.json
> Update Identification Skills and Lore Tooltip text and page number to use GM Core

- packs/feats/graceful-leaper.json
> Add inline actions to Graceful Leaper

- packs/equipment-effects/effect-spun-cloud-white.json
I saw this one happen before my eyes and didn't act fast enough.
> Fix small typo in Spun Cloud (White) effect description

- packs/familiar-abilities/luminous.json
Using the newly added familiar toggles
> Add toggle for Luminous familiar ability

- packs/feats/feathered-flechettes.json
- packs/feats/thunderous-landing.json
- packs/feats/winged-warrior-dedication.json
- static/lang/re-en.json
also add some roll options on inline damage rolls and missing inline checks
> Add toggle for Winged Warrior Dedication fly speed bonus

- static/lang/en.json
> Update additional CRB reference to Remaster publication source

- packs/equipment/mammoth-bow.json
> Fix Mammoth Bow weapon category from advanced to martial

- packs/equipment-effects/effect-cloud-buns-greater.json
- packs/equipment-effects/effect-cloud-buns.json
- packs/equipment-effects/effect-dragon-pearl.json
- packs/equipment-effects/effect-ghost-fowl-porridge.json
- packs/equipment-effects/effect-iron-wine-weakness.json
- packs/equipment-effects/effect-iron-wine.json
- packs/equipment-effects/effect-preserved-moonflower.json
- packs/equipment-effects/effect-rainbow-vinegar-greater.json
- packs/equipment-effects/effect-rainbow-vinegar-moderate.json
- packs/equipment-effects/effect-rainbow-vinegar-weakness.json
- packs/equipment/chilled-fire-noodles-greater.json
- packs/equipment/chilled-fire-noodles.json
- packs/equipment/cloud-buns-greater.json
- packs/equipment/cloud-buns.json
- packs/equipment/dragon-pearl.json
- packs/equipment/ghost-fowl-porridge.json
- packs/equipment/iron-wine.json
- packs/equipment/preserved-moonflower.json
- packs/equipment/rainbow-vinegar-greater.json
- packs/equipment/rainbow-vinegar-moderate.json
> Add effects for TXCG Alchemical Foods and Magical Morsels

- src/module/sheet/helpers.ts
Allegedly fixes some open issues but I cannot find those issues. We can close them later if we find them.
> Avoid persisting temporarily removed actor and item traits

- packs/heritages/lizardfolk/bakuwa-lizardfolk.json
Value of Strength of +3 instead of 16.
> Fix description of Bakuwa Lizardfolk

- packs/seven-dooms-for-sandpoint-bestiary/ripnugget.json
> Correct Ripnugget's Intimidation score

- packs/bestiary-effects/effect-leaders-command.json
- packs/bestiary-effects/effect-share-pain.json
- packs/feat-effects/effect-acupuncturist.json
- packs/feat-effects/effect-hamstringing-strike.json
- packs/spell-effects/spell-effect-diabolic-edict.json
- packs/spell-effects/spell-effect-wish-twisted-form-failure.json
- packs/spell-effects/spell-effect-wish-twisted-form-success.json
- packs/spells/hearts-desire.json
Also touch up some formatting, and implementation of Diabolic Edict and Wish-Twisted Form spell effects
> Replace several string rules selections references with numerical references

- packs/feats/kin-hunter.json
> Fix the level of kin hunter feat

- packs/spell-effects/spell-effect-hand-of-the-apprentice.json
- packs/spells/hand-of-the-apprentice.json
No other way to access this spell besides Wizard
> Remove charisma and wisdom options from Hand of the Apprentice

- packs/bestiary-effects/effect-aggravating-aura.json
Also add description, source, and icon.
> Fix duration of Effect: Aggravating Aura

- packs/blood-lords-bestiary/theater-phantasm.json
Closes https://github.com/foundryvtt/pf2e/issues/16670
> Add automation for Emotional Consumption

- packs/classfeatures/powerful-alchemy.json
> Update Powerful Alchemy description and publication data

- packs/feats/shrink-the-span.json
- packs/spells/shrink-the-span.json
Fix https://github.com/foundryvtt/pf2e/issues/16684
> Correct rank of Shrink the Span spell

- packs/feat-effects/effect-come-and-get-me-temporary-hit-points.json
> Update Come and Get Me Temporary Hit Points Effect Wording

- packs/journals/gm-screen.json
- Alternative title: Blow up the GM Screen using C4 and redo from scratch.
> Refresh GM Screen and update journal entries

- src/scripts/config/traits.ts
- static/lang/en.json
Per https://github.com/TikaelSol/starfinder-field-test/issues/143 
Errata document - https://paizo.com/starfinderplaytest/faq
> Add `Volley 60 feet` to traits and localization.

- packs/rage-of-elements-bestiary/elemental-thicket.json
- packs/rage-of-elements-bestiary/kizidhar-shuyookh.json
- packs/rage-of-elements-bestiary/kizidhar.json
- packs/rage-of-elements-bestiary/painted-stag.json
Also add regeneration to Elemental Thicket
Closes https://github.com/foundryvtt/pf2e/issues/16732
> Brush up some RoE immunities and weaknesses

- packs/classfeatures/blessed-swiftness.json
- packs/classfeatures/champions-aura.json
- packs/feat-effects/effect-aura-of-despair.json
- packs/feat-effects/effect-blessed-swiftness.json
- packs/feats/divine-health.json
- static/lang/re-en.json
In addition to some minor clean up to other champion aura improvements
> Add effect for Blessed Swiftness' defense bonuses to allies

- src/module/actor/helpers.ts
- src/module/actor/loot/sheet.ts
- src/module/actor/sheet/popups/loot-npcs-popup.ts
- static/lang/en.json
- static/templates/actors/loot/sidebar.hbs
Adds a button to `Loot` actors to move their inventory to the party stash
Resolves #10185
> Add Send to Party in loot sheet

- packs/feats/aldori-duelist-dedication.json
> Fix ChoiceSet on Aldori Duelist Dedication

- packs/equipment-effects/effect-silvertongue-mutagen-greater.json
- packs/equipment-effects/effect-silvertongue-mutagen-lesser.json
- packs/equipment-effects/effect-silvertongue-mutagen-major.json
- packs/equipment-effects/effect-silvertongue-mutagen-moderate.json
Update Effect: Silvertongue Mutagen it now has new RE which automates the drawback completely "Become untrained in one skill you're trained in"
> Update Effect: Silvertongue Mutagen

- packs/familiar-abilities/kindling.json
> Fix description for kindling familiar ability

- packs/feats/vernai-training.json
Closes https://github.com/foundryvtt/pf2e/issues/16758
> Fix prerequisites for Vernai Training

- packs/equipment/masquerade-scarf-greater.json
- packs/equipment/masquerade-scarf.json
Closes https://github.com/foundryvtt/pf2e/issues/16757
> Brush up Masquerade Scarf

- packs/pathfinder-bestiary-3/gliminal.json
> Update Radiant Mantle's emission angle

- src/module/actor/character/sheet.ts
Closes https://github.com/foundryvtt/pf2e/issues/15753
> Fix drag/drop reordering of crafting formulas

- src/module/item/base/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/16512
> Fix refreshing items embedded in compendium actors

- src/module/canvas/ruler.ts
> Refrain from broadcasting drag measurement of GM-hidden tokens

- packs/abomination-vaults-bestiary/kragala.json
- packs/abomination-vaults-bestiary/nox.json
- packs/blood-lords-bestiary/harmony-in-agony.json
- packs/curtain-call-bestiary/fallenta.json
- packs/equipment/cloud-pouch.json
- packs/equipment/sentinel-horn.json
- packs/fists-of-the-ruby-phoenix-bestiary/laruhao.json
- packs/fists-of-the-ruby-phoenix-bestiary/razu.json
- packs/iconics/lem-level-5.json
- packs/kingmaker-bestiary/annamede-belavarah.json
- packs/kingmaker-bestiary/linzi-level-7.json
- packs/pathfinder-bestiary-2/trumpet-archon.json
- packs/pathfinder-monster-core/kanya.json
- packs/pfs-season-3-bestiary/thomil-bolyrius-3-4.json
- packs/pfs-season-3-bestiary/thomil-bolyrius-5-6.json
- packs/rollable-tables/6th-level-permanent-items.json
- packs/seven-dooms-for-sandpoint-bestiary/arika-avertin.json
- packs/stolen-fate-bestiary/drustan.json
- packs/strength-of-thousands-bestiary/iobane-magus.json
- packs/strength-of-thousands-bestiary/mpondo.json
- packs/the-enmity-cycle-bestiary/zridi.json
> Refresh copies of musical instruments

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/crafting.ts
- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
- src/module/actor/sheet/base.ts
- src/module/rules/rule-element/crafting-entry.ts
- static/templates/actors/character/tabs/crafting.hbs
A small slice of https://github.com/foundryvtt/pf2e/pull/16771
> Internally rename crafting ability selector to slug and name to label

- packs/feats/spinebreaker.json
- packs/feats/submission-hold.json
> Update text in Spinebreaker and Submission Hold feats to match PC2

- packs/classfeatures/animal-instinct.json
> Correct Animal Instinct's Tyrannosaurus Tail damage type

- packs/wardens-of-wildwood-bestiary/old-thornbarker.json
Invert meaning of toggle
Fix order of Scamp damage partials
Closes https://github.com/foundryvtt/pf2e/issues/16827
> Brush up Old Thornbarker's Sycophantic Scamps

- packs/feat-effects/effect-adamantine-body.json
Closes https://github.com/foundryvtt/pf2e/issues/16850
> Fix resistance value for Adamantine Body

- packs/equipment/surging-serum-minor.json
Added Alchemical, Elixir, & Healing traits to Surging Serum (Minor) since it was lacking them.
> Add missing traits to Minor Surging Serum

- packs/feat-effects/effect-fortify-shield.json
Update Effect: Fortify Shield to use ItemAlteration Rule Element instead of the ActiveEffectLike Rule Element, and also updated Effect: Fortify Shield to grant Effect: Raise a Shield
> Update Effect: Fortify Shield

- packs/feat-effects/effect-fortify-shield.json
> Add backlink to Fortify Shield

- packs/ancestryfeatures/empathic-sense.json
> Restrict Kashrishi's Empathic Sense to non-mindless creatures

- packs/pathfinder-monster-core/con-rit.json
Fix https://github.com/foundryvtt/pf2e/issues/16867
> Change action cost from 1 to 2 Con for Rit - Spit Venom

- packs/feat-effects/effect-champions-extra-damage.json
> Fix duration of Champion's extra damage effect

- packs/equipment-effects/effect-energizing-lattice.json
- packs/equipment/climbing-kit-extreme.json
- packs/equipment/confabulator.json
- packs/equipment/energizing-lattice.json
- packs/feat-effects/effect-liberating-step-vs-aberration.json
- packs/feat-effects/effect-liberating-step-vs-dragon.json
- packs/feat-effects/effect-liberating-step-vs-fiend.json
- packs/feat-effects/effect-liberating-step-vs-undead.json
- packs/feat-effects/effect-protective-mentor-boon-admired-pfs.json
- packs/feat-effects/effect-protective-mentor-boon-liked-pfs.json
- packs/feat-effects/effect-protective-mentor-boon-revered-pfs.json
- packs/feats/dragon-grip.json
- packs/feats/emberkin.json
- packs/feats/know-the-beat.json
- static/lang/re-en.json
and localize or remove some non-localized labels
> Add Strike failure note to Energizing Lattice effect

- packs/bestiary-effects/effect-aspers-elemental-aura.json
- packs/bestiary-effects/effect-bosuns-command.json
> Brush up Asper's Elemental Aura effect description

- src/module/actor/sheet/base.ts
- src/module/item/ability/data.ts
The change to the listener fixes other bugs as well, but these bugs are very rare to run that it may be worth not mentioning it.
> Fix ability frequencies rejecting 0

- src/scripts/hooks/init.ts
Closes https://github.com/foundryvtt/pf2e/issues/14123
> Fix Crash/Freeze when missing @Damage closing bracket

- packs/feat-effects/effect-cast-down.json
- packs/triumph-of-the-tusk-bestiary/skinslough.json
Also add backlink to Effect: Cast Down
> Add automation for Hard to Target

- packs/abomination-vaults-bestiary/mulventok.json
- packs/book-of-the-dead-bestiary/gallowdead.json
- packs/book-of-the-dead-bestiary/minister-of-tumult.json
- packs/kingmaker-bestiary/gromog.json
- packs/pathfinder-bestiary/bunyip.json
- packs/pfs-season-2-bestiary/saddleback-bunyip.json
- packs/tian-xia-world-guide-bestiary/kun.json
Also fix some AdjustStrike definitions to include `slug`
Add healing link to Mulventok's Stay in the Fight
> Add automation for Kun's Heart of Darkness

- packs/season-of-ghosts-bestiary/noppera-bo-occultist.json
> Add spellcasting entry to Noppera-Bo Occultist

- packs/feat-effects/effect-soaring-flight.json
- packs/feats/soaring-flight.json
> Correct action cost and duration for Soaring Flight feet and text on effect

- packs/equipment/cursebreak-bulwark.json
- packs/equipment/fortress-shield.json
Also clean up Cursebreak Bulwark
> Remove unneeded rule elements from Fortress Shield

- src/module/actor/base.ts
- src/module/actor/character/document.ts
- src/module/item/consumable/document.ts
- src/module/item/spell/document.ts
- src/module/item/weapon/document.ts
- src/module/rules/rule-element/item-alteration/rule-element.ts
- src/module/rules/rule-element/strike.ts
- src/module/rules/synthetics.ts
Also did a minor performance optimization, since I wasn't sure about constantly filtering on the entire rule element list in a hot loop.
> Apply item alterations to weapon alt usages

- src/module/item/ability/helpers.ts
> Fix removing frequencies from ability sheets

- packs/sky-kings-tomb-bestiary/glacial-worm.json
> Correct formatting in "Shake it Off" ability for Glacial Worm

- packs/feats/dangle.json
- packs/feats/geckos-grip.json
- packs/feats/shed-tail.json
Closes https://github.com/foundryvtt/pf2e/issues/17000
> Fix prerequisites of Dangle and Shed Tail, and improve automation of Gecko's Grip

- packs/feats/archer-dedication.json
- packs/feats/youre-next.json
In addition to lint
Closes #17012
> Brush up `You're next` feat description text

- packs/sky-kings-tomb-bestiary/glacial-worm.json
- packs/sky-kings-tomb-bestiary/gray-worm.json
> Brush up `Shake it Off` description on select Cave Worm variants

- packs/feats/fresh-ingredients.json
> Update `Fresh Produce` feat requirements to match Player Core 2 update

- packs/spell-effects/spell-effect-element-embodied-air.json
- packs/spell-effects/spell-effect-element-embodied-fire.json
- src/module/rules/rule-element/battle-form/rule-element.ts
- src/module/rules/rule-element/battle-form/types.ts
> Fix creation of ranged battle-form strikes

- src/module/item/base/document.ts
> Fix dropping compendium actors' spells from preparation sheet

- src/styles/actor/familiar/_index.scss
- static/templates/actors/familiar/sheet.hbs
> Fix styling of size tag on familiar sheet

- src/module/actor/character/feats/collection.ts
- src/scripts/config/index.ts
- static/lang/en.json
- static/templates/actors/character/tabs/effects.hbs
Also sneakily fixes a recent divine intercession regression
> Reorganize most feat category and slot localization strings

- packs/rage-of-elements-bestiary/nanoshard-swarm.json
> Add Electromagnetic Dispersal and precision damage immunity to Nanoshard Swarm actor

- static/lang/re-en.json
The noble branch one isn't automated as of yet
> Update Infinite Blades Celestial Arrow to PFS Clarification

- src/module/actor/modifiers.ts
- src/module/rules/rule-element/damage-dice.ts
- src/module/rules/rule-element/flat-modifier.ts
They are in turn included among modifier/dice roll options
> Add support for tagging modifiers and damage dice

- packs/equipment/crown-of-intellect.json
- packs/equipment/ring-of-sigils-greater.json
- packs/equipment/ring-of-sigils.json
> Update `worn` property on select items to match Pathfinder GM Core

- packs/classfeatures/the-radiant.json
- packs/classfeatures/victors-wreath.json
- static/lang/re-en.json
also added a missing localization string and inline traits
Closes #17080
Closes #17078
Closes #17081
> Add missing divine spark predicate to Victor's Wreath immanence

- packs/feats/virulent-strike.json
- packs/feats/wither-away.json
Closes https://github.com/foundryvtt/pf2e/issues/17113
> Add Wither Away and fix Virulent Strike

- packs/spells/earths-bile.json
Closes https://github.com/foundryvtt/pf2e/issues/17119
> Fix persistent damage and range for Earth's Bile

- packs/heritages/kholo/ant-kholo.json
- packs/heritages/kholo/cave-kholo.json
- packs/heritages/kholo/dog-kholo.json
- packs/heritages/kholo/great-kholo.json
- packs/heritages/kholo/sweetbreath-kholo.json
- packs/heritages/kholo/winter-kholo.json
- packs/heritages/kholo/witch-kholo.json
- packs/heritages/tripkee/poisonhide-tripkee.json
- packs/heritages/tripkee/riverside-tripkee.json
- packs/heritages/tripkee/snaptongue-tripkee.json
- packs/heritages/tripkee/stickytoe-tripkee.json
- packs/heritages/tripkee/thickskin-tripkee.json
- packs/heritages/tripkee/windweb-tripkee.json
> Fix ancestry slugs on Kholo and Tripkee heritages

- static/templates/actors/identify-item.hbs
> Close `tbody` tags in the item identification dialog

- packs/backgrounds/badlands-scout.json
- packs/backgrounds/belkzen-anthropologist.json
- packs/backgrounds/empty-hand-loyalist.json
- packs/backgrounds/foreign-diplomat.json
- packs/backgrounds/self-made.json
- packs/backgrounds/trade-representative.json
> Update Triumph of the Tusk backgrounds to use Remaster terminology

- packs/feats/animist-dedication.json
- packs/feats/basic-glory.json
- packs/feats/expert-animist-spellcasting.json
- packs/feats/master-animist-spellcasting.json
- packs/feats/spiritual-awakening.json
Basic feats for both Animist and Exemplar, and spellcasting proficiencies for Animist archetype.
> Add missing implementation of WoI multiclass archetypes

- packs/classfeatures/monk-expertise.json
- packs/feats/jalmeri-heavenseeker-dedication.json
Also tackle the Jalmeri Heavenseeker feat choice if you already have qi spells
> Automate Monk Expertise spellcasting upgrade

- packs/equipment/sakuras-sprig.json
Change envision for (concentrate) in Sakura's sprig and a typo
> Change sakura's sprig to remaster terms

- packs/feat-effects/effect-the-bigger-they-are.json
- packs/feats/the-bigger-they-are.json
- static/lang/re-en.json
Closes https://github.com/foundryvtt/pf2e/issues/17130
> Add automation for The Bigger They Are

- packs/actions/crash-against-me.json
- packs/classfeatures/skin-hard-as-horn.json
- packs/feat-effects/effect-crash-against-me-clang.json
- packs/feat-effects/effect-crash-against-me-note.json
- packs/feat-effects/effect-crash-against-me.json
- static/lang/re-en.json
> Implement Crash Against Me's resistance and add notes on triggering attacks

- packs/pathfinder-society-boons/evolving-destiny.json
- packs/pathfinder-society-boons/heroic-aegis.json
- packs/pathfinder-society-boons/inherited-wayfinder.json
- packs/pathfinder-society-boons/lantern-lodge-gear.json
- packs/pathfinder-society-boons/nexus-house-gear.json
- packs/pathfinder-society-boons/open-road-lodge-gear.json
- packs/pathfinder-society-boons/pathfinder-society-second-edition-replay.json
- packs/pathfinder-society-boons/penitent-pathfinder.json
- packs/pathfinder-society-boons/second-chance.json
- packs/pathfinder-society-boons/steady-hand.json
- packs/pathfinder-society-boons/treasure-bundle-insurance.json
- packs/pathfinder-society-boons/ward-against-fiends.json
- packs/pathfinder-society-boons/world-traveler.json
> Add PFS Glyph to select Pathfinder Society Boons

- src/module/system/damage/iwr.ts
> Fix processing of concussive trait in damage application

- packs/actions/fracture-mountains.json
- packs/classfeatures/titans-breaker.json
Third time is the charm, let's see if we can get it right this time.
I had previously implemented it with a wrong reading of the rules.
> Correct Fracture Mountains immanence damage adjustment

- packs/feats/mental-buffer.json
> Update predicate on Mental Buffer feat

- src/module/system/damage/weapon.ts
> Include damage type in base weapon splash damage when building formulas

- packs/feats/eternal-legend-dedication.json
> Change Eternal Legend Dedication to be a class feat

- src/module/actor/character/crafting/ability.ts
- src/styles/actor/character/_crafting.scss
- static/lang/en.json
- static/templates/actors/character/tabs/crafting.hbs
https://github.com/user-attachments/assets/8f1ed49c-0f77-4bb6-82b6-8cc37bcbdc0d
> Only show a single empty slot with remaining count when prepared crafting

- static/licenses/OpenGameLicense.md
Add missing items from Mid 2024 to March 2025 to license
> Update OGL License

- packs/classfeatures/avenger.json
> Predicate Avenger's sneak attack on Hunted Prey toggle

- src/styles/system/_choice-set-prompt.scss
> Fix width of inputs in choice set prompts

- static/licenses/OpenGameLicense.md
> Revert "Update OGL License"

- static/licenses/ORCLicense.md
- static/licenses/OpenGameLicense.md
Make system compatible with OGL, ORC, and the Texas Transportation Code (Probably)
> Add Licensing Terms

- static/lang/en.json
> Add `ConditionTypeCursebound` to en.json

- packs/feat-effects/effect-revitalizing-finisher.json
> Update Revitalizing Finisher Temporary HP formula

- src/module/actor/character/crafting/crafting.ts
- src/module/actor/helpers.ts
- src/module/actor/inventory/index.ts
I find it odd that rest for the night *and* daily craft delete infused items, but I guess better safe than sorry.
> Batch create and delete items when daily crafting

- packs/feats/spear-dancer.json
> Fix action cost of Spear Dancer

- packs/rollable-tables/major-art-object.json
Change the items below into text entries as they do not exist in the system but are still found in GM Core, p299.
* Solidified moment of time
* Thought lens of astral essence
* Major painting by a legend
> Update Major Art Objects rollable table

- packs/campaign-effects/malevolence/malevolence.json
> Brush up Malevolence effect

- packs/actions/mark-for-death.json
> Add Marked for Death's roll option to its Sneak Attack damage predicate

- packs/sky-kings-tomb-bestiary/redcap-cavalry.json
> Fix DC of Divine Revulsion for Redcap Cavalry

- packs/sky-kings-tomb-bestiary/repelling-surge.json
> Add missing thievery check to Repelling Surge hazard

- src/module/chat-message/helpers.ts
- src/scripts/macros/hotbar.ts
Supercedes https://github.com/foundryvtt/pf2e/pull/17336
> Fix item macros for actions without use buttons and support modifier keys

- src/module/actor/sheet/trick-magic-item-popup.ts
Nothing special, just localization issue.
> Fix `Trick Magic Item` popup labels

- packs/classfeatures/monk-expertise.json
> Fix malformed RE in Monk Expertise Class Feature

- packs/rage-of-elements-bestiary/lithic-locus.json
- packs/rage-of-elements-bestiary/vault-builder.json
- packs/sky-kings-tomb-bestiary/ashrin.json
- packs/sky-kings-tomb-bestiary/skibrellon.json
- packs/sky-kings-tomb-bestiary/veavieve.json
- packs/stolen-fate-bestiary/mivanian-soldier.json
- packs/stolen-fate-bestiary/raskus.json
Closes https://github.com/foundryvtt/pf2e/issues/17367
> Fix some compendium sources and refresh items

- src/module/item/deity/data.ts
- src/module/item/deity/document.ts
- src/module/item/deity/sheet.ts
- static/lang/en.json
- static/templates/items/deity-details.hbs
> Add Covenant category to deity items, allow devotee benefits for philosophies

- packs/equipment-effects/effect-focus-on-the-doomed-fear-penalty.json
- packs/equipment-effects/effect-focus-on-the-doomed.json
- packs/equipment/assassins-bracers-type-i.json
- packs/equipment/assassins-bracers-type-ii.json
- packs/equipment/assassins-bracers-type-iii.json
- static/lang/re-en.json
Closes https://github.com/foundryvtt/pf2e/issues/17384
> Add effects for Assassin's Bracers

- packs/feats/champion-dedication.json
- packs/feats/sentinel-dedication.json
> Fix armor scaling of Champion and Sentinel dedications

- packs/feats/advanced-alchemy.json
- static/lang/re-en.json
> Move Advanced Alchemy specific rule localization key to Alchemist

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/crafting.ts
- src/module/actor/character/crafting/index.ts
- src/module/actor/character/crafting/types.ts
- src/module/actor/character/data.ts
- src/module/actor/character/document.ts
- src/module/actor/character/sheet.ts
- src/module/actor/creature/document.ts
- src/module/actor/helpers.ts
- src/module/actor/inventory/index.ts
- src/module/rules/rule-element/special-resource.ts
- src/scripts/macros/rest-for-the-night.ts
- static/lang/en.json
- static/templates/actors/character/tabs/crafting.hbs
> Expend prepared formulas when daily crafting and add a reset button

- packs/deities/calistria.json
- packs/pathfinder-bestiary-2/giant-crab.json
- packs/pfs-season-6-bestiary/6-06/enraged-the-heartwood-rots.json
- packs/sky-kings-tomb-bestiary/lady-shimmersnip.json
Also fix action category of Enraged The Heartwood Rots's Children of the Night
> Fix penalty type for Vulnerable to Prone

- packs/feats/telepathic-union.json
> Add Telepathic Union feat

- src/module/item/spell/helpers.ts
- static/templates/items/partials/spell-description-prepend.hbs
> Add ritual stats to description prepend

- packs/extinction-curse-bestiary/guardian-of-the-faithful.json
- packs/pathfinder-monster-core/giant-animated-statue.json
- packs/pfs-season-1-bestiary/statue-of-set.json
- packs/prey-for-death-bestiary/shirota.json
- packs/wardens-of-wildwood-bestiary/timber-titan.json
- packs/wardens-of-wildwood-bestiary/usher.json
Also brush up Brazier automation
Add grab to Guardian of the Faithful's Stone Fist
Fix Usher's Flaming Coal base damage type
Fix missing compendiumSource for Shirota's Blood Sight Elixir (Greater)
> Coalesce damage for Burn Alive

- packs/feats/deadly-aspect.json
- packs/feats/draconic-aspect.json
> Limit Deadly Aspect to the Strike granted by Draconic Aspect

- src/util/misc.ts
Tiny thing I noticed while stealing your helper functions
> Have isVideoFilePath guard the correct type

- src/module/item/spell/data.ts
- src/module/item/spell/document.ts
- src/module/item/spell/helpers.ts
- src/module/item/spell/sheet.ts
- src/module/migration/migrations/744-migrate-spell-heighten.ts
- src/module/migration/migrations/894-no-lay-on-hands-vs-undead.ts
- src/module/migration/migrations/897-clear-lay-on-hands-damage.ts
- src/styles/actor/_item-summary.scss
- src/styles/legacy/_chat.scss
- static/lang/en.json
- static/templates/items/partials/spell-description-prepend.hbs
- static/templates/items/spell-details.hbs
Clears one of the tasks in the comments of https://github.com/foundryvtt/pf2e/issues/4882
> Add support for spell area heightening

- packs/spells/deluge.json
- packs/spells/erase-trail.json
- packs/spells/establish-ward.json
- packs/spells/etheric-shards.json
- packs/spells/illuminate.json
- packs/spells/sea-of-thought.json
- packs/spells/shockwave.json
All the ones *I* could find anyway. Using the support for it introduced in #17492
> Add interval area heightening on spells

- packs/iconics/nahoa-level-1.json
- packs/iconics/nahoa-level-3.json
- packs/iconics/nahoa-level-5.json
There was a lot of exemplar improvements and clean up since these were made.
> Refresh Nahoa's class features

- packs/feats/scattering-shout.json
> Add Scattering Shout mythic feat

- packs/war-of-immortals-bestiary/mythic-griffon.json
> Add Mythic Griffon to War of Immortals bestiary

- src/scripts/config/traits.ts
Closes  #17552
The trait is already in the data for Harmonic Hauberk
> Add illusion trait to armors

- packs/rage-of-elements-bestiary/vault-builder.json
This ability belongs to the vault keeper
> Remove slashing surge from vault builder

- src/styles/actor/party/kingdom/_builder.scss
https://github.com/user-attachments/assets/3f1212b1-ea9f-46d9-8d13-3760dc46039a
> Remove selection hover from builder to avoid confusion with active

- src/module/actor/character/sheet.ts
- static/templates/actors/character/tabs/crafting.hbs
This may have been more than was asked for, but Objects don't have a built-in order (so you can't reverse), so to get this to work nicely I had to get arrays, and then when I had an array of objects it made sense to organize them into a data structure.
I wanted to add tests, but it didn't look like there were a lot. I really could have used some documentation around getting a developer environment set up, maybe I missed it?
Refs #17546
> Reverse formula sort.

- src/styles/ui/_roll-modifiers-dialog.scss
Specifically lines interfering in V13
> Remove some unnecessary roll modifiers dialog styling

- packs/classfeatures/versatile-vials.json
- packs/equipment/versatile-vial.json
Thanks to Quick Alchemy now handling the item level.
> Move versatile vials scaling to physical item rather than the feature

- packs/equipment/blood-sight-elixir-greater.json
- packs/equipment/blood-sight-elixir-lesser.json
- packs/equipment/blood-sight-elixir-major.json
- packs/equipment/blood-sight-elixir-moderate.json
- packs/equipment/cats-eye-elixir.json
- packs/equipment/unsullied-blood-greater.json
- packs/equipment/unsullied-blood-lesser.json
- packs/equipment/unsullied-blood-major.json
- packs/equipment/unsullied-blood-moderate.json
- packs/paizo-pregens/kangir.json
- packs/paizo-pregens/yacob.json
- packs/prey-for-death-bestiary/shirota.json
- packs/rollable-tables/2nd-level-consumables.json
> Add inline links to Cat's Eye Elixir

- src/module/actor/character/crafting/ability.ts
- src/module/actor/character/crafting/crafting.ts
- src/module/actor/character/crafting/types.ts
- static/templates/actors/character/tabs/crafting.hbs
If you somehow go over the limit, which can occur if you mess with feats and such, this little warning pops up now:
> Allow setting quantity for daily crafting abilities instead of redragging

- packs/classfeatures/quick-alchemy.json
- packs/classfeatures/versatile-vials.json
- packs/feats/alchemist-dedication.json
Holding off on Quick Tincture and Wandering Chef until we have some tags for their stuff
> Add Crafting Ability and Special Resource for Alchemist's Quick Alchemy 

- src/module/chat-message/data.ts
- src/module/chat-message/roll-inspector.ts
- src/module/system/check/check.ts
- src/module/system/damage/damage.ts
- src/styles/ui/sidebar/chat/_roll-inspector.scss
- static/lang/en.json
- static/templates/chat/roll-inspector.hbs
Closes https://github.com/foundryvtt/pf2e/issues/15457
Also supercedes https://github.com/foundryvtt/pf2e/pull/15784 (which was created afterwards)
[
> Show post roll options in the inspector and include in notes

- src/module/chat-message/roll-inspector.ts
- src/module/item/base/sheet/sheet.ts
- src/styles/tooltip/_index.scss
- static/lang/en.json
- static/templates/chat/roll-inspector.hbs
- static/templates/system/roll-options-tooltip.hbs
> Add description for damage and modifier roll options in the roll inspector

- packs/feat-effects/stance-talon-stance.json
This updates the Talon Stance effect to use the talon image instead of the foot image
> Talon Stance now uses Talon image

- packs/feats/ageless-patience.json
- static/lang/re-en.json
also restrict its Note to only if there is there is no delta available
> Use AdjustDegreeOfSuccess rule element on Ageless Patience and localize its Note

- packs/spells/gale-blast.json
> Update Gale Blast heightening to match Player Core 2

- packs/fists-of-the-ruby-phoenix-bestiary/bul-gae.json
- packs/stolen-fate-bestiary/mighty-bul-gae.json
- packs/tian-xia-world-guide-bestiary/bul-gae.json
Note that the sources differ on whether it's "Requirement" or "Requirements".
> Fix description formatting for Shadow Leap

- packs/spells/lingering-composition.json
> Revert "Add DC by Level Performance check for Lingering Composition"

- src/module/actor/character/sheet.ts
- src/styles/actor/_inventory.scss
- src/styles/actor/character/_inventory.scss
- static/lang/en.json
- static/templates/actors/character/tabs/inventory.hbs
- static/templates/actors/partials/coinage.hbs
- static/templates/actors/partials/encumbrance.hbs
- static/templates/actors/partials/inventory.hbs
> Add search filter to inventory and make minor style adjustments

- packs/familiar-abilities/extra-alchemy.json
- packs/feat-effects/effect-extra-alchemy.json
- packs/feat-effects/effect-left-hand-blood.json
- packs/feats/chemical-contagion.json
also grant Toxicologist Greater Field Discovery with Chemical Contagion, and some lint
> Add effect for Extra Alchemy familiar ability

- packs/feats/fresh-ingredients.json
- static/lang/re-en.json
Fresh Ingredients as printed in PC2: https://2e.aonprd.com/Feats.aspx?ID=6340
> Update Fresh Ingredients feat

- static/lang/re-en.json
Was tempted to AdjustModifier the thing but no generic "wilderness" terrain option in terrains yet.
> Add wilderness label for Fresh Ingredients

- packs/howl-of-the-wild-bestiary/virtuosic-lyrebird.json
- packs/paizo-pregens/ezren-beginner-box.json
- packs/pathfinder-monster-core/air-scamp.json
- packs/pathfinder-monster-core/aiuvarin-elementalist.json
- packs/pathfinder-monster-core/dryad-queen.json
- packs/pathfinder-monster-core/fortune-dragon-adult-spellcaster.json
- packs/pathfinder-monster-core/fortune-dragon-ancient-spellcaster.json
- packs/pathfinder-monster-core/fortune-dragon-young-spellcaster.json
- packs/pathfinder-monster-core/horned-dragon-adult-spellcaster.json
- packs/pathfinder-monster-core/horned-dragon-ancient-spellcaster.json
- packs/pathfinder-monster-core/horned-dragon-young-spellcaster.json
- packs/pathfinder-monster-core/naiad-queen.json
- packs/pfs-season-5-bestiary/5-20/asper-hajeri-9-10.json
- packs/pfs-season-5-bestiary/5-20/asper-hajeri.json
- packs/prey-for-death-bestiary/mantis-keeper.json
- packs/spells/gust-of-wind.json
- packs/tian-xia-world-guide-bestiary/peng.json
> Add damage to Gust of Wind

- packs/rage-of-elements-bestiary/talos-gadgeteer.json
> Correct Talos Gadgeteer's gadget inventory selection

- packs/blood-lords-bestiary/ghoul-crocodile.json
- packs/feat-effects/effect-echolocation.json
- packs/feat-effects/effect-force-of-nature-silver-damage.json
- packs/feats/bear-hug-werecreature.json
- packs/feats/beastkin-resilience.json
- packs/feats/cornered-animal.json
- packs/feats/death-roll.json
- packs/feats/dire-growth.json
- packs/feats/echolocation.json
- packs/feats/fearful-symmetry.json
- packs/feats/feeding-frenzy.json
- packs/feats/feral-mending.json
- packs/feats/feral-scramble.json
- packs/feats/feral-senses.json
- packs/feats/force-of-nature.json
- packs/feats/pack-attack.json
- packs/feats/plague-rat.json
- packs/feats/pouncing-transformation.json
- packs/feats/rapid-hybridization.json
- packs/feats/scarred-hide.json
- packs/feats/touch-of-lunacy.json
- packs/feats/undying-beast.json
- packs/feats/werecreature-dedication.json
- packs/feats/you-dont-smell-right.json
- packs/pathfinder-monster-core/crocodile.json
- packs/pfs-season-5-bestiary/5-10/carcaras.json
- packs/pfs-season-5-bestiary/5-10/pampla.json
- packs/strength-of-thousands-bestiary/old-thrasher.json
- static/lang/re-en.json
Also brush up predicates for NPC Death Roll
> Brush up Werecreature Dedication

- packs/equipment/minds-light-circlet.json
- packs/equipment/tome-implement.json
> Fix roll option on Tome physical thaumaturge implement

- packs/classfeatures/gleaming-blade.json
> Correct action cost of Flowing Spirit Strike in Gleaming Blade description

- packs/kingmaker-bestiary/brush-thylacine.json
> Remove link to prone condition in Brush Thylacine description

- packs/classfeatures/mutagenist.json
- packs/feat-effects/effect-mutagenist-field-benefit.json
- static/lang/re-en.json
and use item level in Chirurgeon's Field Vials inline healing
> Add effect for Mutagenist's Field Benefit Temp HP

- packs/feats/animalistic-resistance.json
- packs/feats/dire-form.json
- packs/feats/gift-of-the-moon.json
- packs/spell-effects/spell-effect-moon-frenzy.json
* Brush up predicates for Animalistic Resistance
* Add automation for Dire Growth
* Add automation for Gift of the Moon
> Update select Beastkin Ancestry Feats

- packs/feats/weapon-infusion.json
- src/scripts/macros/hotbar.ts
- static/lang/re-en.json
Including some git branch gore for a little Christmas treat
> Add Range increment sizes to ranged weapon infusion suboption labels

- src/module/system/damage/iwr.ts
> Check against exceptions when applying precision resistance/weakness

- packs/classfeatures/advanced-vials-bomber.json
- static/lang/re-en.json
> Add precious material selection for Bomber's Advanced Vials

- packs/equipment/shadow-manse.json
> Correct rarity of Shadow Manse from Uncommon to Rare

- packs/classes/fighter.json
> Add automation for initial Fighter skill selection

- packs/classfeatures/fourth-gates-threshold.json
- packs/classfeatures/gate-junction.json
- packs/classfeatures/gates-threshold.json
- packs/classfeatures/second-gates-threshold.json
- packs/classfeatures/third-gates-threshold.json
> Fix kineticist junctions

- packs/equipment/iron-wine.json
- packs/equipment/saboteurs-friend.json
- packs/equipment/scholars-drop.json
- packs/equipment/sprite-apple-chartreuse.json
- packs/equipment/sprite-apple-golden.json
- packs/equipment/sprite-apple-pink.json
- packs/equipment/sprite-apple-teal.json
> Add `Alchemical Food` tag to Iron Wine and icons to select Alchemical foods

- packs/feats/instinctive-strike.json
Instinctive Strike is now a passive.
> Update Instinctive Strike to remaster

- packs/prey-for-death-bestiary/berserker-ordulf.json
- packs/prey-for-death-bestiary/celasik.json
- packs/prey-for-death-bestiary/dronuk.json
- packs/prey-for-death-bestiary/ordulf-bladecaller.json
Round 2 -
I missed the other Ordulf and failed to see the circumstance bonus on Dronuk's You're Next in the first round
> Update automation for additional Prey for Death actors

- packs/pathfinder-monster-core/cassisian.json
The beginner's test to this issue https://github.com/foundryvtt/pf2e/issues/17940
> Add area options to Cassisian.

- packs/feats/fey-ascension.json
> Update priority for AE-like rule elements on Fey Ascension feat

- packs/curtain-call-bestiary/augusta-wormwood.json
- packs/pathfinder-monster-core/dero-magister.json
- packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
- packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
- packs/pathfinder-monster-core/omen-dragon-young-spellcaster.json
- packs/pathfinder-monster-core/vampire-mastermind.json
- packs/spells/stupefy.json
- packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
> Update Stupefy to match Player Core duration and target

- packs/classfeatures/the-oscillating-wave.json
> Correct Oscillating Wave's Amped Ignition dice number

- packs/feats/regurgitate-mutagen.json
Closes https://github.com/foundryvtt/pf2e/issues/17982
> Fix action type and cost of Regurgitate Mutagen

- src/module/actor/helpers.ts
> Fix issue causing propulsive weapons to sometimes have dex-based attack statistics

- packs/classfeatures/initiate-benefit-regalia.json
> Add slug to Regalia's bonus to charisma skills

- src/module/item/armor/sheet.ts
- src/module/item/weapon/sheet.ts
- src/styles/item/_index.scss
- src/styles/item/_weapon-sheet.scss
- static/templates/items/armor-details.hbs
Closes https://github.com/foundryvtt/pf2e/issues/17850. Also sneakily fixes a minor regression with the armor precious material selection.
> Sort weapon and armor property runes

- packs/curtain-call-bestiary/hellshadow.json
> Correct Hellshadow NPC resistances values to match source

- packs/equipment/grub-gloves-greater.json
- packs/equipment/grub-gloves-lesser.json
- packs/equipment/grub-gloves-moderate.json
Add bonus type for Grub Gloves
> Add bonus type for Grub Gloves (Lesser), (Moderate), (Greater)

- packs/equipment-effects/effect-goz-mask-major.json
- packs/equipment/goz-mask-greater.json
- packs/equipment/goz-mask-major.json
- packs/equipment/goz-mask.json
Also add links to descriptions
> Add effect for Goz Mask (Major)

- packs/feats/channel-rot.json
- static/lang/re-en.json
> Add automation for Channel Rot's persistent damage

- packs/feats/boost-summons.json
- packs/feats/eidolons-wrath.json
- packs/feats/eternal-boost.json
- packs/feats/lifelink-surge.json
- packs/feats/reinforce-eidolon.json
- packs/feats/unfetter-eidolon.json
> Add spell links to select Summoner class feats

- src/module/item/helpers.ts
- src/module/item/spell/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/18060#issuecomment-2603379587
> Fix viewing spells with variants from compendium browser

- packs/feats/defend-our-union.json
> Fix category of defend our union feat

- packs/feats/clone-risen.json
- packs/feats/mirror-risen.json
Closes https://github.com/foundryvtt/pf2e/issues/18067
> Fix action type of Clone Risen and Miror Risen feats

- packs/feat-effects/effect-left-hand-blood.json
- packs/pfs-season-6-bestiary/6-09/shadowpact-goliath-spider.json
- packs/pfs-season-6-bestiary/6-09/shadowpact-tarantula.json
- packs/war-of-immortals-bestiary/mythic-griffon.json
> Fix some mismatched parentheses

- vite.config.ts
foundryconfig.json is already part of the git ignore.
> Support other ports in npm run hot using foundry config

- packs/pathfinder-monster-core/brimorak.json
> Update Brimorak actor size and add saving throw inline to Frothing Spew

- packs/spell-effects/spell-effect-stoke-the-heart.json
fixes the scaling of the stoke the heart spell effect to conform with base 2 with +2 heightening
> Fix scaling of Stoke the Heart spell effect

- src/module/actor/character/crafting/helpers.ts
- src/module/system/action-macros/crafting/craft.ts
> Fix Craft not using the right skills rank

- src/module/actor/creature/sheet.ts
- src/styles/actor/character/_sidebar.scss
- static/templates/actors/character/partials/sidebar.hbs
- static/templates/actors/npc/partials/sidebar.hbs
The use case is vitality network
> Support deltas in special resource input

- packs/equipment/frost-fair-yanyuedao.json
From Pathfinder Lost Omens: Tian Xia Character Guide (pg. 131)
> Fix source of frost fair yanyuedao

- packs/feats/rivethun-devotion.json
formatting of spell in description
> Fix format of spell in rivethun devotion feat

- src/module/actor/army/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/18171
> Use source values when computing kingdom army levelups

- src/module/rules/rule-element/item-alteration/rule-element.ts
Fixes description of the spell repertoire class feature.
> Resolve item alteration id for singleItem and additionalItems

- packs/equipment/grub-gloves-greater.json
- packs/equipment/grub-gloves-lesser.json
- packs/equipment/grub-gloves-moderate.json
> Correct rarity tag on Grub Gloves

- packs/feat-effects/effect-regalia.json
> Restrict Regalia's flanking override to paragon benefit

- packs/abomination-vaults-bestiary/nhimbaloths-cutter.json
> Remove Dazzling Brilliance from variant glass golem

- packs/spells/darkened-forest-form.json
- packs/spells/discomfiting-whispers.json
Closes https://github.com/foundryvtt/pf2e/issues/18202
> Fix action cost of Darkened Forest Form and Discomfiting Whispers

- packs/pathfinder-monster-core/fire-scamp.json
> Correct action cost for Fire Scamp's Flame Breath action

- src/module/item/base/document.ts
Should make bard gameplay a bit less awkward.
> Remove expired copies of an effect when adding a new one

- packs/classfeatures/razor-prongs.json
The automation was updated, but the description slipped through.
> Update description of Razor Prongs modification

- packs/classfeatures/slingers-precision.json
I don't have a PDF for Guns & Gears Remastered, so I took the text from Demiplane.
> Fix Slinger's Precision using description from Singular Expertise

- packs/feat-effects/effect-scouts-warning.json
> Add initiative selector to Scout's Warning

- packs/classfeatures/slingers-precision.json
> Restrict slinger's precision damage dice to non-repeating firearms

- packs/feats/apparitions-reflection.json
> Fix the description of apparition's reflection feat

- static/lang/re-en.json
> Update Unstable critical failure damage to remaster

- packs/feats/animal-companion-ranger.json
- packs/feats/masterful-companion.json
- packs/feats/shared-prey.json
- packs/feats/triple-threat.json
Salvaged from #15079 - credit should go to Rigo
> Apply description alterations to select Ranger feats

- packs/spell-effects/spell-effect-devil-form-erinys.json
- packs/spell-effects/spell-effect-devil-form-osyluth.json
- packs/spell-effects/spell-effect-insect-form-spider.json
Closes https://github.com/foundryvtt/pf2e/issues/18261
> Fix some BattleForm ranged attack increments

- packs/actions/elemental-blast.json
- packs/classfeatures/fire-gate.json
- packs/feats/improved-elemental-blast.json
Closes #18230
Also move some DamageDice to DamageAlteration
> Automate Improved Elemental Blast

- static/lang/re-en.json
> Downgrade unstable flat check DC to 13 if Crafting proficiency rank is legendary

- packs/seven-dooms-for-sandpoint-bestiary/ripnugget.json
> Correct traits on Ripnugget's Devastating Blast ability

- packs/actions/hunt-prey.json
- packs/equipment/hunters-arrowhead.json
- packs/feat-effects/effect-hunt-prey.json
- packs/feat-effects/effect-hunters-edge-flurry.json
- packs/feat-effects/effect-hunters-edge-outwit.json
- packs/feat-effects/effect-hunters-edge-precision.json
- packs/feat-effects/effect-masterful-hunters-edge-flurry.json
- packs/feat-effects/effect-masterful-hunters-edge-outwit.json
- packs/feat-effects/effect-masterful-hunters-edge-precision.json
- packs/feats/bounty-hunter-dedication.json
- packs/feats/dance-of-thunder.json
- packs/feats/game-hunter-dedication.json
- packs/feats/hamstringing-strike.json
- packs/feats/hunters-aim.json
> Apply `Token Mark` to Hunt Prey action and associated feats and effects

- packs/pathfinder-monster-core/scarecrow.json
> Add missing "fear effects" immunity to Scarecrow actor

- packs/feats/spell-woven-shot.json
> Remove `dedication` trait from Spell-Woven Shot feat

- packs/equipment/lantern-hooded.json
- static/lang/re-en.json
Adjusted rule elements so that the Hooded Lantern can be toggled like a torch or candle.
closes #18085
> Add missing hooded lantern interact automation

- packs/classfeatures/of-verse-unbroken.json
> Correct localization path for `Of Verse Unbroken` critical specialization

- src/module/item/consumable/document.ts
> Consume requested amount of ammunition when reducing quantity

- src/module/actor/character/apps/abc-picker/app.svelte
- src/module/actor/character/apps/abc-picker/app.ts
Also add sorting by rarity and (for heritages) whether versatile
> Include `originalName` in ABC picker searches

- src/module/actor/sheet/base.ts
> Allow use of search inputs by observers on non-editable actor sheets

- packs/equipment/sanguine-klar-greater.json
- packs/equipment/sanguine-klar.json
> Update Sanguine Klar items to include their runes

- packs/equipment/alicorn-trigger.json
- packs/equipment/blasting-stone-greater.json
- packs/equipment/blasting-stone-lesser.json
- packs/equipment/blasting-stone-major.json
- packs/equipment/blasting-stone-moderate.json
- packs/equipment/bottled-sunlight-greater.json
- packs/equipment/frost-vial-greater.json
- packs/equipment/frost-vial-lesser.json
- packs/equipment/frost-vial-major.json
- packs/equipment/frost-vial-moderate.json
> Update text for Blasting Stone and Frost Vial, and add icon to Alicorn Trigger

- packs/equipment-effects/effect-goo-grenade.json
Bring it up to standards of other condensed effects
> Update Goo Grenade Effect

- src/scripts/register-keybindings.ts
- types/foundry/client/keyboard/keyboard-manager.d.ts
> Fix registration of GM Vision keybind for macs

- src/global.ts
- types/foundry/client-esm/applications/_types.d.ts
- types/foundry/client-esm/applications/api/dialog.d.ts
- types/foundry/client-esm/applications/api/module.d.ts
- types/foundry/client/apps/av/cameras.d.ts
- types/foundry/client/apps/av/index.d.ts
- types/foundry/client/apps/client-settings.d.ts
- types/foundry/client/apps/index.d.ts
- types/foundry/client/apps/templates.d.ts
- types/foundry/client/config.d.ts
- types/foundry/client/ui/index.d.ts
- types/foundry/common/utils/helpers.d.ts
- types/foundry/common/utils/module.d.ts
- types/foundry/common/utils/semaphore.d.ts
These are some updates to the types that I've had to add while writing my own modules and using pf2e types as the baseline.
Each commit is one addition/modification to the types. Let me know if there are any modifications needed.
> Type updates

- packs/feat-effects/effect-ultimatum-of-liberation.json
> Update selector to `will` for Ultimatum of Liberation effect

- packs/classfeatures/weapon-innovation.json
> Push priority of weapon innovation fire damage toggle to after overdrive roll options

- packs/feats/detectives-readiness.json
Follow-up to https://github.com/foundryvtt/pf2e/pull/18406 as I forgot to change the predicate (forgot to check the case when it shouldn't be on by default)
> Add proper predicate to Detective's Readiness saving throw RE

- packs/one-shot-bestiary/dinner-at-lionlodge/auldegrund-grimcarver.json
- packs/one-shot-bestiary/dinner-at-lionlodge/simulacrum.json
> Correct formatting for Auldengrund Grimcarver's Simulacrum ritual

- packs/pathfinder-npc-core/devotee/rancorous-priesthood.json
> Correct Rancorous Priesthood's max focus pool points

- packs/classfeatures/slingers-precision.json
> Push Slinger's Precision Martial Proficiency priority to after other proficiency upgrades

- packs/classfeatures/flurry.json
> Correct predicates for `Flurry Edge` MAP Rule Elements

- src/module/actor/sheet/base.ts
Closes https://github.com/foundryvtt/pf2e/issues/18423
> Fix mystifying compendium items when alt dragging

- packs/backgrounds/adventure-paths/abomination-vaults/eldritch-anatomist.json
- packs/backgrounds/adventure-paths/fists-of-the-ruby-phoenix/abadars-avenger.json
- packs/backgrounds/goblinblood-orphan.json
- packs/backgrounds/lumber-consortium-laborer.json
- packs/backgrounds/star-athlete.json
Closes https://github.com/foundryvtt/pf2e/issues/18468
> Preselect Assurance choice for some backgrounds

- packs/classes/gunslinger.json
> Add Lead Constitution to Gunslinger's granted features

- packs/spell-effects/spell-effect-entreat-spirit.json
> Update Entreat Spirit effect to choose an int-, wis-, or cha-based skill

- packs/feats/reinforced-chassis.json
> Update Reinforced Chassis AC bonus alteration to be additive with other increases

- packs/pathfinder-npc-core/mystic/demonologist.json
> Add missing spell statistics to Demonologist

- packs/bestiary-effects/effect-conduct-the-experiment.json
- packs/bestiary-effects/effect-sages-analysis.json
- packs/pathfinder-npc-core/scholar/sage.json
Also add missing predicate and duration to Effect: Conduct the Experiment
> Add effect for Sage's Analysis

- packs/pathfinder-npc-core/ancestry-npcs/goblin/goblin-get-gang.json
> Correct text on Goblin Get Gang's `Goblins Bound and Goblins Swing!` ability

- packs/classfeatures/eldritch-trickster.json
- packs/feats/archetype/animist/animist-dedication.json
- packs/feats/archetype/bard/bard-dedication.json
- packs/feats/archetype/cleric/cleric-dedication.json
- packs/feats/archetype/druid/druid-dedication.json
- packs/feats/archetype/exemplar/exemplar-dedication.json
- packs/feats/archetype/magus/magus-dedication.json
- packs/feats/archetype/oracle/oracle-dedication.json
- packs/feats/archetype/psychic/psychic-dedication.json
- packs/feats/archetype/sorcerer/sorcerer-dedication.json
- packs/feats/archetype/summoner/summoner-dedication.json
- packs/feats/archetype/witch/witch-dedication.json
- packs/feats/archetype/wizard/wizard-dedication.json
Plus bonus fix to Exemplar Dedication's proficiencies
> Cleanup Eldritch Trickster implementation

- src/scripts/helpers.ts
- src/scripts/system/dragstart-handler.ts
- src/scripts/ui/inline-roll-links.ts
Closes https://github.com/foundryvtt/pf2e/issues/18287
> Get origin data when dragging effects from the actor sheet

- src/module/item/consumable/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/18118
> Skip failing embedded consumable spells during data preparation

- static/lang/en.json
This is a data check on all Languages to match released Books naming.  Updated Vishkanyan to Vishkanya.
> Updated Vishkanyan to Vishkanya in the languages

- packs/feats/class/exemplar/leap-the-falls.json
> Link Powerful Leap and Quick Jump in Leap the Falls

- packs/deities/core-gods/asmodeus.json
> Add Asmodeus' divine font

- packs/spell-effects/spell-effect-anima-invocation.json
> Add resistance on a success to Anima Invocation's spell effect

- packs/spell-effects/spell-effect-enlarge-companion.json
- packs/spell-effects/spell-effect-enlarge-heightened-4th.json
- packs/spell-effects/spell-effect-enlarge.json
> Fix Enlarge and Enlarge Companion effects to apply bonus to all melee damage

- packs/equipment/summoning-handscroll.json
> Fix trait in summoning handscroll

- packs/feats/archetype/palatine-detective/palatine-strike.json
> Add Strategic Strike dice number increase to Palatine Strike

- packs/classfeatures/ranger-expertise.json
> Update `Ranger Expertise` class feature to account for Vindicator Class Archetype

- packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/black-whale-guard-f3.json
- packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/black-whale-guard.json
- packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/ixusoth.json
- packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/myrucarx.json
- packs/feats/class/fighter/shatter-defenses.json
- packs/pathfinder-bestiary-3/hyakume.json
Also add automation for Painful Light
> Add some missing condition links

- packs/feat-effects/effect-one-moment-till-glory.json
- packs/feat-effects/effect-snap-out-of-it-marshal.json
- packs/feats/archetype/marshal/snap-out-of-it-marshal.json
Also adjust duration of Effect: One Moment till Glory
> Add effect for Snap Out of It! (Marshal)

- packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
- packs/pathfinder-monster-core/omen-dragon-adult.json
- packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
- packs/pathfinder-monster-core/omen-dragon-ancient.json
- packs/pathfinder-monster-core/omen-dragon-young-spellcaster.json
- packs/pathfinder-monster-core/omen-dragon-young.json
> Add traits to Omen Dragon's `Challenge Fate` ability

- packs/feats/class/monk/reflective-ripple-stance.json
Closes https://github.com/foundryvtt/pf2e/issues/18639
> Link self effect to Reflective Ripple Stance

- packs/feats/skill/distracting-performance.json
Closes https://github.com/foundryvtt/pf2e/issues/18645
> Fix action type and cost of Distracting Performance

- src/module/item/consumable/document.ts
Not a use case that ever actually happens in the wild. Supercedes https://github.com/foundryvtt/pf2e/pull/18629
> Fix ammo consumption of repeating double-barrel weapons

- packs/bestiary-effects/effect-align-the-stars.json
- packs/bestiary-effects/effect-verdant-aria.json
- packs/classfeatures/bloodrager.json
- packs/equipment-effects/effect-drake-rifle-cold.json
- packs/equipment-effects/effect-fanged-rune-animal-form.json
- packs/kingmaker-bestiary/gromog.json
- packs/shades-of-blood-bestiary/book-1-thirst-for-blood/lesser-shadow-scamp.json
- packs/shades-of-blood-bestiary/book-1-thirst-for-blood/vampire-servant.json
Fix a flag -> rollOption
Fix an RE key
Fix some token names
> Fix some selectors

- src/module/actor/character/document.ts
- src/module/item/weapon/document.ts
- src/module/rules/rule-element/choice-set/rule-element.ts
Also fix isEquipped() for variant Handwraps of Mighty Blows
Closes https://github.com/foundryvtt/pf2e/issues/18630
> Fix ChoiceSets not including variant Handwraps of Mighty Blows

- src/module/actor/character/document.ts
- src/module/actor/character/helpers.ts
- static/lang/action-en.json
Fists and non-real strikes can gain the parry trait (ex: Spirit Warrior Dedication)
> Add aux action for parry

- packs/classfeatures/ruffian.json
- packs/classfeatures/sneak-attack.json
> Extend ruffian's critical specialization to all sneak attack-qualifying weapons

- src/module/item/condition/document.ts
- src/module/rules/rule-element/grant-item/rule-element.ts
> Prevent duplicate RE application from in-memory-only conditions

- packs/equipment/elemental-fragment-major.json
- src/scripts/config/index.ts
- static/lang/en.json
Also fix usage for mental Fragment (Major)
Closes https://github.com/foundryvtt/pf2e/issues/18680
> Add localization for Other usage

- packs/feat-effects/effect-animalistic-brutality.json
- packs/feats/class/barbarian/animalistic-brutality.json
Closes https://github.com/foundryvtt/pf2e/issues/18692
> Add self effect for Animalistic Brutality

- packs/paizo-pregens/beginner-box/ezren-beginner-box.json
- packs/paizo-pregens/beginner-box/kyra-beginner-box.json
- packs/paizo-pregens/beginner-box/merisiel-beginner-box.json
- packs/paizo-pregens/beginner-box/valeros-beginner-box.json
> Move Beginner Box Pregens backstory text to the `Backstory` section

- src/module/item/weapon/document.ts
A little innocent refactor ~~that will allow me to perform a dash of black magic elsewhere don't mind me~~
> Use ammo required getter when consuming ammo

- packs/bestiary-family-ability-glossary/beheaded/beheaded-furious-headbutt.json
> Fix missing `toggleable` in Furious Headbutt

- src/scripts/hooks/drop-canvas-data.ts
Closes https://github.com/foundryvtt/pf2e/issues/18775
> Only allow dragging to visible tokens

- packs/pathfinder-bestiary/phantasmal-minion.json
- static/lang/re-en.json
Closes https://github.com/foundryvtt/pf2e/issues/18780
> Add custom Immunity for Phantasmal Minion

- packs/kingmaker-bestiary/imeckus-stroon.json
> Correct Imeckus Stroon's spellcasting label

- packs/age-of-ashes-bestiary/book-6-broken-promises/aiudara-wraith.json
Also add void healing ability
Closes https://github.com/foundryvtt/pf2e/issues/18810
> Fix action type and cost of Aiudara Wraith's Dimensional Shunt

- packs/equipment/aurochs-jerky.json
> Add missing price Aurochs Jerky

- src/module/item/base/sheet/sheet.ts
- src/module/item/spellcasting-entry/collection.ts
- src/module/item/spellcasting-entry/helpers.ts
- src/scripts/register-templates.ts
- static/lang/en.json
The localization entries aren't used yet, but they will be, its a matter of time. I need to give regular activations a try again soon.
> Include minor refactors from staff PR

- packs/feats/class/kineticist/body-of-air.json
Closes https://github.com/foundryvtt/pf2e/issues/18826
> Brush up Body of Air description

- packs/equipment-effects/effect-inflammation-flask.json
- packs/equipment/inflammation-flask-greater.json
- packs/equipment/inflammation-flask-lesser.json
- packs/equipment/inflammation-flask-major.json
- packs/equipment/inflammation-flask-moderate.json
> Correct Inflammation Flask's damage type and update effect automation

- packs/spells/8th-rank/whirlwind.json
Also update description to indicate extra area information is supplemental
> Update Whirlwind area to be cylinder

- packs/equipment/rending-gauntlets-greater.json
- packs/equipment/rending-gauntlets-lesser.json
- packs/equipment/rending-gauntlets-moderate.json
Closes https://github.com/foundryvtt/pf2e/issues/18840
> Correct usage of Rending Gauntlets

- src/module/system/statistic/statistic.ts
Closes https://github.com/foundryvtt/pf2e/issues/18720
> Fix trick magic item spell DC when using trained or expert skills

- packs/kingmaker-bestiary/leng-envoy.json
> Correct `Leng Envoy` Tongues spell tag

- packs/kingmaker-bestiary/armag-twice-born.json
- static/lang/re-en.json
Also add deathNote to No Time to Die
Closes https://github.com/foundryvtt/pf2e/issues/18847
> Add custom resistance for Armag Twice-Born

- packs/feats/class/magus/maguss-analysis.json
Should I expose it via a toggle?
> Add automation for Magus's Analysis

- packs/rage-of-elements-bestiary/metal-scamp.json
> Correct size on Metal Scamp actor

- packs/kingmaker-bestiary/minognos-ushad.json
Closes https://github.com/foundryvtt/pf2e/issues/18866
> Fix DC and damage of Minognos-Ushad's Wyvern Venom

- packs/pathfinder-npc-core/mercenary/mage-killer.json
Closes https://github.com/foundryvtt/pf2e/issues/18874
> Brush up Mage Killer

- src/styles/_tags.scss
- src/styles/actor/_inventory.scss
- src/styles/actor/familiar/_index.scss
- src/styles/actor/hazard/_index.scss
- src/styles/actor/hazard/_sidebar.scss
- src/styles/actor/loot/_index.scss
- src/styles/actor/npc/_index.scss
- src/styles/actor/npc/_sidebar.scss
- src/styles/actor/party/_index.scss
- src/styles/actor/vehicle/_index.scss
- src/styles/item/_header.scss
- src/styles/item/_sidebar.scss
Scrollbar gutters now include a up/down error, so its even more important that we set scrollbar-gutter: stable.
The tagify bit might be an issue even in v12 maybe. I would have to check.
> Fix minor styling issues for v13

- packs/kingmaker-bestiary/nugrah.json
Closes https://github.com/foundryvtt/pf2e/issues/18888
> Tidy description formatting of Nugrah's Swift Summon

- packs/kingmaker-bestiary/overgrown-viper-vine.json
Closes https://github.com/foundryvtt/pf2e/issues/18905
> Fix senses of Overgrown Viper Vine

- src/module/system/damage/formula.ts
Closes https://github.com/foundryvtt/pf2e/issues/18933
The bug occurs if there is a damage partial that is a negative constant with no dice, which only happens in this specific scenario. 
The `|| "0"` is no longer necessary, as that scenario only occurs in a zero constant with no dice scenario, which is handled now by the other branch.
> Fix penalties set to critical false when rolling critical damage

- packs/spell-effects/spell-effect-anima-invocation.json
Let me know if there's anything I miss or there's a better way to do this.
Closes #18938
> Add holy trait to Anima Invocation spell effect additional damage

- src/styles/system/_effects-panel.scss
> Fix glow effect and label of aura effects

- src/module/item/weapon/document.ts
- src/module/item/weapon/sheet.ts
- src/module/rules/rule-element/adjust-strike.ts
> Ensure weapon sheet update of property runes is array

- src/scripts/hooks/render-dialog.ts
- types/foundry/client/helpers/hooks.d.mts
Something I noticed while working on something else. We should consider a custom dialog like what 5e does at some point though.
> Restore item create opt-groups for V13

- packs/actions/blinding-of-the-needle.json
> Fix Blinding of the Needle action cost

- vite.config.ts
> Also wrap importet library CSS in `system` layer for Vite HMR

- src/module/item/base/sheet/rule-element-form/token-light.ts
- static/templates/items/rules/aura.hbs
- static/templates/items/rules/token-image.hbs
- static/templates/items/rules/token-light.hbs
plus one deprecation warning in `TokenLightForm`
> Replace deprecated `rangePicker` helper with `<range-picker>` elements

- packs/pfs-season-6-bestiary/6-15/azlanti-altered-lion-additional-legs.json
- packs/pfs-season-6-bestiary/6-15/azlanti-altered-lion-armor-plating.json
> Correct Saving Throw values for Azlanti Altered Lion variants

- src/module/item/abstract-effect/data.ts
- src/module/item/abstract-effect/schema.ts
- src/module/item/abstract-effect/values.ts
- src/module/item/affliction/data.ts
- src/module/item/affliction/document.ts
- src/module/item/affliction/sheet.ts
- src/scripts/hooks/init.ts
- src/scripts/hooks/load.ts
- src/styles/item/_affliction-sheet.scss
- src/styles/item/_index.scss
- static/template.json
- static/templates/items/affliction-details.hbs
- static/templates/items/affliction-sidebar.hbs
I added it back to the template, but omitting the data model in production and stripping it out in load should hopefully be enough of a disincentive.
> Convert AfflictionSystemData to DataModel and update sheet

- packs/bestiary-effects/effect-symbol-of-loyalty.json
The Grand Inquisitor's Symbol of Loyalty Effect should be status, thus I added "type": "status" to the file
> Add type "status" to the Symbol of Loyalty Effect

- packs/pfs-season-6-bestiary/quests/animated-flame.json
- packs/pfs-season-6-bestiary/quests/burning-building.json
- packs/pfs-season-6-bestiary/quests/elite-animated-flame.json
- packs/pfs-season-6-bestiary/quests/weak-animated-flame.json
- packs/pfs-season-6-bestiary/quests/ōmukade.json
Check to see if the naming works OK. It has a non-English O
> Add NPCs from Quest 24

- packs/classfeatures/deity-champion.json
- packs/classfeatures/deity-cleric.json
> Avoid skipping sanctification choice set for deities permitting no sanctification

- packs/pathfinder-bestiary-2/denizen-of-leng.json
> Add precision resistance to Denizen of Leng

- packs/feat-effects/effect-curse-maelstrom-state.json
> Correct Curse Maelstrom Effect effect radius formula

- packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/izhkarial.json
- packs/equipment/bands-of-force-greater.json
- packs/equipment/bands-of-force-major.json
- packs/equipment/bands-of-force.json
- packs/pathfinder-npc-core/martial-artist/black-belt.json
- packs/pathfinder-npc-core/martial-artist/grandmaster.json
- packs/pathfinder-npc-core/mystic/enchanting-ritualist.json
- packs/spore-war-bestiary/book-1-whispers-in-the-dirt/alzarius.json
- packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/iravalinn-morgethai.json
Bands of force worn type was set at wornbracers instead of wornarmbands.
> fix bands of force worn type

- packs/other-effects/effect-aquatic-combat.json
> Suppress Fire Damage and link `Remaining Air` effect to Aquatic Combat effect

- src/module/canvas/token/aura/map.ts
- src/module/scene/document.ts
- src/module/scene/helpers.ts
Re-opened MR to replace #19066 as it wasn't updating. I'm allowed to: https://github.com/foundryvtt/pf2e/pull/19066#issuecomment-2870203546
> Move aura grid type check to scene getter

- packs/other-effects/effect-aquatic-combat.json
> Correct treatment of Aquatic Combat Penalty

- packs/spell-effects/spell-effect-fiery-body-9th-level.json
- packs/spell-effects/spell-effect-fiery-body.json
- static/lang/re-en.json
* Add return damage automation through note
* Unify Fiery Body formatting for heightened variant
* Use the same wording
* Use the same paragraphs
> Add automation for Fiery Body return damage

- packs/kingmaker-bestiary/test-of-strength.json
> Remove extraneous Hidden link from Test of Strength Hazzard

- packs/kingmaker-bestiary/the-lonely-warrior.json
Closes https://github.com/foundryvtt/pf2e/issues/19089
> Brush up The Lonely Warrior

- src/module/scene/token-document/document.ts
> Fix re-rendering auras following embedded item changes

- packs/feats/archetype/bellflower-tiller/scarecrow.json
> Remove extraneous character in `Scarecrow` feat description

- packs/bestiary-effects/effect-dust-eternal.json
- packs/rage-of-elements-bestiary/elder-outcrop.json
Closes https://github.com/foundryvtt/pf2e/issues/19105
> Brush up Elder Outcrop

- packs/classfeatures/avenger.json
- packs/classfeatures/masterful-hunter-flurry.json
- packs/classfeatures/masterful-hunter-outwit.json
- packs/classfeatures/masterful-hunter.json
- packs/classfeatures/outwit.json
- packs/classfeatures/ranger-weapon-expertise.json
- packs/classfeatures/vindicator.json
- packs/equipment/hunters-anthem.json
> Correct predicates for for several Ranger `Hunted Prey` associated items

- packs/kingmaker-bestiary/trapdoor-ogre-spider.json
- packs/pathfinder-bestiary-2/ogre-spider.json
- packs/pfs-season-2-bestiary/2-18/ogre-spider-pfs-2-18.json
Closes https://github.com/foundryvtt/pf2e/issues/19110
> Tidy descriptions of Ogre Spider Venom

- packs/feat-effects/effect-kinetic-aura.json
- src/module/apps/sidebar/chat-log.ts
- src/module/chat-message/helpers.ts
- src/module/chat-message/listeners/cards.ts
- src/module/rules/rule-element/aura.ts
- static/templates/chat/action/collapsed.hbs
> Move apply-effect handler to `ChatLogPF2e`, fix aura-traits restriction

- static/lang/re-en.json
> Add localization for Investigator's Perception Mastery description.

- packs/feats/class/exemplar/hurl-at-the-horizon.json
> Automate hurl at the horizon

- src/module/actor/base.ts
- src/module/item/base/document.ts
Closes https://github.com/foundryvtt/pf2e/issues/19077
> Fix error when updating items on synthetic tokens

- packs/lost-omens-bestiary/mwangi-expanse/crystal-xorn.json
> Add Crystal Xorn variant

- packs/feats/class/exemplar/hurl-at-the-horizon.json
- packs/kingmaker-bestiary/valerie-level-1.json
- packs/kingmaker-bestiary/valerie-level-9.json
> Correct Damage Override for Valerie

- packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/urushil.json
- packs/pathfinder-bestiary/marilith.json
- static/lang/re-en.json
- Make Defensive Assault's effect a Self Applied effect.
- Also update Urushil (as pointed out by @simonward)
> Update automation for Marilith's `Focused Assault`

- src/module/apps/sidebar/actor-directory.ts
Closes https://github.com/foundryvtt/pf2e/issues/19177
> Fix error when actors that are party members are deleted

- src/module/chat-message/helpers.ts
Closes https://github.com/foundryvtt/pf2e/issues/19191
> Fix applying damage for v13
