src/module/item/base.ts
src/module/item/consumable/spell-consumables.ts

Also noticed and removed a check for an NPC actor type along the way--these methods, despite their names, currently only apply to hazards and will hopefully be gone soon

Remove more uses of `duplicate`

---

src/module/actor/character/index.ts
src/module/actor/character/types.ts
src/module/actor/creature/data.ts
src/module/actor/creature/index.ts
src/module/actor/familiar/index.ts
src/module/actor/npc/index.ts
src/module/actor/npc/skills-editor.ts
static/templates/actors/familiar-sheet.html

Also makes familiar and actor skill names the lower case longform name like character has it.
Eventually the shortform skills will be removed from actor.skills. The next release should publish a deprecation warning for short form names such as actor.skills.ath and actor.skills.thi

Expose longform actor skill names in actor.skills

---

packs/data/feats.db/mighty-bulwark.json
packs/scripts/run-migration.ts
src/module/actor/character/index.ts
src/module/actor/modifiers.ts
src/module/migration/migrations/754-mighty-bulwark-adjust-modifiers.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/system/statistic/index.ts

This will make the display of the (Mighty) Bulwark modifier less confusing (before it would show both Bulwark and Dexterity until rolled)

Add Adjust Modifier REs to Mighty Bulwark

---

src/module/actor/npc/index.ts
static/lang/en.json

Remove extraneous "Range" trait being added to NPC attacks

---

static/templates/chat/action-card.html
static/templates/chat/feat-card.html

Closes #2378 
Traits were already present in actions chat cards, but in the footer with the other properties instead of below the header like other cards, so I moved them.

Add traits for feat & actions chat cards

---

src/scripts/hooks/load.ts

Currently, whenever a button is clicked, it retains focus--even when the button is one that closes a Foundry application. When the document body doesn't have focus, canvas hotkeys stop functioning until the canvas is clicked again. Removing button focus after any click successfully preserves hotkey functionality with (hopefully) no significant side effects.
Upstream issue: https://github.com/foundryvtt/foundryvtt/issues/7270

Prevent buttons from retaining focus when clicked

---

CHANGELOG.md
README.md
system.json

* (stwlam) Add support for throwing melee weapons with Thrown trait--currently the weapon isn't lost when thrown, pending accounting of mitigating abilities
* (stwlam) Add secret feature allowing one to generate [redacted] from [redacted] on NPCs
* (Supe) Add syntax highlighter and linter for Rule Element editing
* (Supe) Add new (in-testing) Hazard sheet
* (Anathema) Rework readme for official status and license info
* (Friz) Add logic to grey Inventory, Effect and Notes tabs for NPC if relative tab is empty
* (JDCalvert) Make the AdjustStrike rule element replace existing traits of the same type and lower value
* (nikolaj-a) Add Repair and Treat Disease action macros
* (stwlam) Allow searching for any physical item trait in equipment browser: will expand to other browser tabs in future …

Release Notes 3.11.0

---

src/module/item/physical/helpers.ts
src/module/migration/migrations/746-standardize-pricing.ts

Updates the old migration to remove null as well if it finds it.

Handle null price values for Coins

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Fix failed import of repair action macro
* (stwlam) Restore functionality of several damage-related weapon traits
* (Supe) Handle aberrant price values on items
* (Supe) Show strike descriptions in new hazard sheet

Release Notes 3.11.1

---

packs/data/pathfinder-bestiary-2.db/babau.json
packs/data/pathfinder-bestiary-2.db/blodeuwedd.json
packs/data/pathfinder-bestiary-2.db/bralani.json
packs/data/pathfinder-bestiary-2.db/monadic-deva.json
packs/data/pathfinder-bestiary-2.db/movanic-deva.json

For better localization weapon name of magical weapons needs to be base weapon name and use automatic renaming.

Review Bestary 2: Changed name of mag. weapon to base weapon

---

src/module/actor/creature/index.ts

Restore legacy support for RE predication checking "attack" trait

---

src/module/item/runes.ts

Remove reference to non-existent success note for corrosive rune

---

packs/data/spell-effects.db/spell-effect-boost-eidolon.json

Closes #2525 
Removes not unarmed predicate from Effect: Boost Eidolon

Update Effect: Boost Eidolon Rule Element

---

packs/data/fall-of-plaguestone.db/graytusk.json
packs/data/fall-of-plaguestone.db/lord-nar.json
packs/data/fall-of-plaguestone.db/orc-alchemist.json
packs/data/fall-of-plaguestone.db/the-sculptor.json

Each of these had the old version of Ferocity without the DeathNote, and the alchemists weren't using the localizable items.

Audit of Orc NPCs from FoP

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (Supe) Add a roll inspection dialog, accessible from chat message context menu (currently supports check rolls)
* (Supe) Show when the beta hazard sheet is in edit mode in the application titlebar, display source and author
* (stwlam) Restore legacy support for RE predication checking "attack" trait (affected Draconic Rage, among other abilities)
* (stwlam) Fix localization of spell traditions in chat cards
* (stwlam) Fix players not being able to see save DCs from their own spells
* (stwlam) Include modifier adjustments and roll substitutions in action macros
* (stwlam) Fix issue causing modifier adjustments to not be included on manually-added modifiers
* (stwlam) Remove reference to non-existent success note for corrosive rune
* (stwlam) Fix issue causing container contents to …

Release Notes 3.11.2

---

packs/data/spell-effects.db/spell-effect-light.json

The light spell was washing out light colored tokens so it should be toned down a bit in color balance.
Before
After

Tone down the Light spell effect

---

packs/data/spell-effects.db/spell-effect-demon-form-babau.json
packs/data/spell-effects.db/spell-effect-elephant-form.json

Update Effect: Demon Form (Babau)
- add battleform predicate to enable precision / evil damage
Update Effect: Elephant Form
- re-add damage/attack modifiers for base spell

Update Demon Form (Babau) and Elephant Form effects.

---

packs/data/spell-effects.db/spell-effect-plant-form-flytrap.json
src/module/rules/rule-element/battle-form/rule-element.ts

This will remove the need for the REs themselves to have the predicate unless they come from a separate item

Automatically add "battle-form" predicate to other REs on same item

---

packs/data/equipment.db/holy-water.json
packs/data/equipment.db/unholy-water.json

Holy Water and Unholy Water were both created as Consumables, which is how they are classified in the CRB, but the Activate action for both is a Strike. Per stwlam: "but until the system adds proper support for item activation, a weapon item type is the closest functional approximation".

Update Holy and Unholy Water Items to be Weapons

---

src/module/rules/rule-element/ae-like.ts

priority is derived from mode, so missing mode and priority will warn about priority currently, when it should warn about mode first.

Warn about mode before priority for AELike

---

src/styles/ui/_tags.scss

Fix styling of long transparent tags in chat messages

---

src/module/apps/pick-a-thing-prompt.ts
src/module/rules/rule-element/choice-set/prompt.ts

This is done instead of creating a new button in which the user must click.
Upon dropping:

Show ChoiceSet homebrew drop in select menu

---

src/module/actor/creature/sheet.ts
src/module/actor/familiar/index.ts
src/module/actor/familiar/sheet.ts
src/module/actor/familiar/types.ts
src/module/actor/sheet/item-summary-renderer.ts
src/styles/actor/familiar/_index.scss
static/templates/actors/familiar-sheet.html

This allows familiar sheets to prevent certain types of items from being added to it, and also piggyback off of existing sheet events.

Make familiar sheet inherit from creature sheet

---

packs/data/feature-effects.db/effect-aquatic-combat-no-swim-speed.json
packs/data/feature-effects.db/effect-aquatic-combat.json

Added two effects, one for if the creature in question has a swim speed, and one for no swim speed.

Add effects for Aquatic Combat

---

src/module/actor/character/sheet.ts
src/module/actor/creature/sheet.ts
src/module/actor/creature/types.ts
src/module/actor/npc/sheet.ts
src/module/actor/npc/types.ts
src/scripts/register-templates.ts
src/styles/actor/character/_effects.scss
src/styles/actor/familiar/_index.scss
src/styles/mixins/_effects-list.scss
static/templates/actors/character/tabs/effects.html
static/templates/actors/familiar-sheet.html
static/templates/actors/npc/tabs/effects.html
static/templates/actors/partials/conditions.html
static/templates/actors/partials/dying-pips.html

As a side effect, this also removes the wonky looking divider border from NPC sheet, and fixes condition and effect name alignment.
This also removes character sheet condition capping for doomed/dying/wounded, but that is not only bugged but also didn't work from token hud or effect panel.

Support increment/decrement/source for conditions in the familiar sheet

---

packs/data/feats.db/catfolk-weapon-rake.json
packs/data/feats.db/conrasu-weapon-understanding.json
packs/data/feats.db/dwarven-weapon-cunning.json
packs/data/feats.db/elven-weapon-elegance.json
packs/data/feats.db/genie-weapon-flourish.json
packs/data/feats.db/gnoll-weapon-practicality.json
packs/data/feats.db/gnome-weapon-innovator.json
packs/data/feats.db/goblin-weapon-frenzy.json
packs/data/feats.db/grippli-weapon-innovator.json
packs/data/feats.db/halfling-weapon-trickster.json
packs/data/feats.db/hobgoblin-weapon-discipline.json
packs/data/feats.db/kobold-weapon-innovator.json
packs/data/feats.db/orc-weapon-carnage.json
packs/data/feats.db/vanths-weapon-execution.json

Missing tengu, as they're complex and need a choice set

Migrate ancestry critical specialisation feats to CriticalSpecialization rule element

---

src/module/actor/vehicle/sheet.ts
src/scripts/config/traits.ts
src/styles/actor/vehicle/_index.scss
src/styles/ui/_tags.scss
static/templates/actors/vehicle/sidebar/vehicle-resistances.html
static/templates/actors/vehicle/sidebar/vehicle-saves.html
static/templates/actors/vehicle/vehicle-header.html

Also remove extraneous bits from VehicleSheetPF2e#getData and add traits needed for published vehicles
Closes #2630
Before:
After:

Fix display of traits and IWR on vehicle sheet

---

packs/data/classfeatures.db/panache.json
packs/data/classfeatures.db/vivacious-speed.json
packs/data/feature-effects.db/effect-panache.json

Panache needs more cleanup in the other feats so as to not rely on a statically-set roll option, but this is a start.

Remove toggle from Panache class feature, add RE slugs where necessary

---

packs/data/abomination-vaults-bestiary.db/dread-wisp.json
packs/data/abomination-vaults-bestiary.db/flickerwisp.json
packs/data/abomination-vaults-bestiary.db/groetan-candle.json
packs/data/abomination-vaults-bestiary.db/voidglutton.json
packs/data/abomination-vaults-bestiary.db/will-o-the-deep.json

Updated Dread Wisp, Flickerwisp, Groetan Candle, Voidglutton, and Will-o'-the-Deep. Resolves https://github.com/foundryvtt/pf2e/issues/2329.

Update Token Light Effects on various Abomination Vaults NPCs

---

packs/data/feats.db/game-hunter-dedication.json
packs/data/feats.db/triple-shot.json
src/module/rules/rule-element/roll-option.ts

If a roll option toggle is disabled due to its `disabledIf` predicate failing, an additional `disabledValue` property (defaults to false) can control whether the roll option is still active when toggled on but disabled

Refine roll-option toggle disabling with disabledValue property

---

src/module/apps/ui/compendium-directory.ts
src/scripts/hooks/ready.ts
src/scripts/register-module-art.ts
types/foundry/client/collections/compendium-collection.d.ts

Also adds a pair of debug messages at start and completion of reindexing

Ensure module-art registration completes before compendium reindexing

---

packs/data/feat-effects.db/effect-guided-by-the-stars.json
packs/data/feat-effects.db/effect-shed-tail.json
packs/data/feats.db/envenom-fangs.json
packs/data/feats.db/geckos-grip.json
packs/data/feats.db/lizardfolk-lore.json
packs/data/feats.db/parthenogenic-hatchling.json
packs/data/feats.db/razor-claws.json
packs/data/feats.db/read-the-stars.json
packs/data/feats.db/reptile-rider.json
packs/data/feats.db/scion-transformation.json
packs/data/feats.db/swift-swimmer.json
static/lang/re-en.json

Reptile Rider refers to an action that doesn't exist in PF2, and so I've assumed they mean Command an Animal, like all the other ancestry riding feats.
Scion Transformation is permanent, and so I've copied the rules effects from Enlarge.

Automate lizardfolk feats

---

src/module/actor/sheet/base.ts

This makes it so that the item being dragged *always* goes before the item being dragged to, regarding of direction.

Make spell dragdrop resorting consistent with other drag/drop behaviors

---

src/module/actor/sheet/popups/ability-builder.ts
src/module/item/background/data.ts
src/module/item/background/index.ts
static/lang/en.json
static/templates/actors/ability-builder.html

- Localize unlocalized headers
- Crunch down more non-rendering whitespace
- Use HandleBars helpers when available
- Change input name attributes that resemble data properties
- Remove unecessary id attributes

Make second cleanup pass on boost management

---

packs/data/fall-of-plaguestone.db/spear-launcher.json

The description of this hazard is different from what is in the CRB, so adding a new version that matches the text from Fall of Plaguestone.

Add Spear Launcher Hazard to Fall of Plaguestone

---

packs/data/backgrounds.db/amnesiac.json
packs/data/backgrounds.db/discarded-duplicate.json
packs/scripts/run-migration.ts
src/module/migration/migrations/762-update-background-items.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
static/templates/actors/ability-builder.html

UI shows this correctly, but unable to add a third one from the UI, so this is done manually.

Update Amnesiac and Discarded Duplicate to include a third free boost (with migration)

---

src/module/system/statistic/index.ts
src/scripts/sheet-util.ts

This change fixes some minor inconsistencies depending on the type of event the browser emits. Specifically, there was an issue with Token Action HUD where skill checks weren't picking up modifier keys properly because Firefox (at least on my machine) was emitting a MouseEvent, meaning the branch to check modifiers was missed and shift/ctrl didn't affect the roll settings.

Fix erroneous use of PointerEvent in place of MouseEvent

---

src/module/system/damage/roll-dialog.ts

Fix display of action traits on Strike damage rolls

---

packs/data/equipment.db/adventurers-pack.json

It should be 10 pieces of chalk, not just 1. This also causes a pricing discrepancy. A miniscule one, but a discrepancy nonetheless.

Update Adventurer's Pack with the correct amount of chalk

---

packs/data/extinction-curse-bestiary.db/headless-xulgath.json
packs/data/extinction-curse-bestiary.db/hooklimb-xulgath.json
packs/data/extinction-curse-bestiary.db/pin-tingwheely.json
packs/data/extinction-curse-bestiary.db/resin-seep-xulgath.json
packs/data/extinction-curse-bestiary.db/runkrunk.json
packs/data/extinction-curse-bestiary.db/xulgath-bomber.json
packs/data/pathfinder-bestiary.db/clay-golem.json

Update Headless Xulgath, Hooklimb Xulgath, Resin-Seep Xulgath, and Runkrunk.
Additionally, fix spells per SpartanCPA's suggestion on Pin Tingwheely. Also matched Clay Golem from B1 to Runkrunk, and fixed a small grammar error in Xulgath Bomber.

Update NPCs from EC Book 3 Ch 3

---

packs/data/pfs-season-3-bestiary.db/cobbled-bruiser.json
packs/data/pfs-season-3-bestiary.db/cobbled-brutalizer.json
packs/data/pfs-season-3-bestiary.db/ninth-army-guard.json
packs/data/pfs-season-3-bestiary.db/ninth-army-mage.json
packs/data/pfs-season-3-bestiary.db/ninth-army-operative.json
packs/data/pfs-season-3-bestiary.db/ninth-army-soldier.json
packs/data/pfs-season-3-bestiary.db/ninth-army-war-mage.json
packs/data/pfs-season-3-bestiary.db/thomil-bolyrius-3-4.json
packs/data/pfs-season-3-bestiary.db/thomil-bolyrius-5-6.json
packs/data/pfs-season-3-bestiary.db/weakened-cobbleswarm.json

Note: Weakened cobbleswarm isn't in the guide, but is prepped based on the description given in the cobbled Bruiser with the modified stat block.

Add NPCs from PFS 3-16

---

packs/data/pathfinder-bestiary.db/gibbering-mouther.json
packs/data/pathfinder-bestiary.db/nightmare.json
packs/data/pfs-season-3-bestiary.db/angry-void-boils.json
packs/data/pfs-season-3-bestiary.db/horrid-nightmare.json
packs/data/pfs-season-3-bestiary.db/shadow-pfs-3-17.json
packs/data/pfs-season-3-bestiary.db/smoldering-nightmare.json
packs/data/pfs-season-3-bestiary.db/void-boils.json
packs/data/pfs-season-3-bestiary.db/waking-nightmare.json
packs/data/pfs-season-3-bestiary.db/waking-terror.json

Corrects Gibbering Mouther and Nightmare
PFS difference for Shadow 3-17: Note that variant shadow has enfeebled 2 on a critical hit. The B1 version does not.

Add NPCs and Hazards from PFS 3-17

---

src/module/actor/character/index.ts
src/module/system/statistic/index.ts

It doesn't seem like NPC's types include it. Could be added, but that's not a fix I think

Fix roll twice api option for character strikes, add for skills/saves

---

packs/data/heritages.db/undine.json

Removes quotation marks from Swim BaseSpeed Rule Element value on Undine heritage.
Resolves warnings in console and correctly displays swim speed on character sheet.

Update Undine Heritage BaseSpeed Rule Element

---

packs/data/feats.db/slayers-strike.json

Closes #2832 
Corrects Slayer's Strike DamageDice RE doman from "saving-throw" to "damage"

Update Slayer's Strike Rule Element

---

packs/data/equipment.db/forge-warden.json

Page 588: Forge warden's durability is too low. Increase its basic shield statistics to Hardness 10, HP 40, BT 20.

Fix Forge Warden shield stats from CR errata 1.

---

src/styles/legacy/_chat.scss
static/templates/chat/spell-card.html

Coupled with the margin tweak, this reduces the awkward gap for info only spells

Fix malformed spell chat message html

---

packs/data/deities.db/enkaar-the-malformed-prisoner.json
packs/data/deities.db/eyes-that-watch.json
packs/data/deities.db/grasping-iovett.json
packs/data/deities.db/husk.json
packs/data/deities.db/lady-razor.json
packs/data/deities.db/reshmit-of-the-heavy-voice.json
packs/data/deities.db/thalaphyrr-martyr-minder.json

Bestiary 3 has a sidebar where an Owb Prophet can act as a deity. This PR adds the provided information for these options. Note that none of the Forsakens listed specify a folllower alignment, edict, anathema, or divine ability for the "Raised by Faith" background. All of that information appears to be GM Fiat

Add Owb Prophet Forsakens as Deities

---

packs/data/feats.db/skill-mastery-rogue.json

Corrects skill type for Archetype Skill "Skill Mastery (Rogue)" from "Class" to "Archetype"

Update Skill Mastery (Rogue) to correct feat type

---

src/module/actor/sheet/item-summary-renderer.ts
src/module/chat-message/data.ts
src/module/chat-message/index.ts
src/module/chat-message/listeners/cards.ts
src/module/item/sheet/data-types.ts
src/module/item/spell/data/types.ts
src/module/item/spell/index.ts
src/module/item/spell/overlay.ts
src/module/item/spell/sheet.ts
src/module/item/spellcasting-entry/index.ts
static/lang/en.json
static/templates/actors/spellcasting-spell-list.html
static/templates/chat/spell-card.html
static/templates/items/item-sheet.html
static/templates/items/spell-details.html
static/templates/items/spell-variant-prompt.html

This enables the creation of spell variants based on cast time (like Heal) and adds a prompt to select which variant to cast.
https://user-images.githubusercontent.com/41452412/173586017-499d679d-8195-4f75-88c7-70bd819c9553.mp4
Example setup for the Heal spell with variants:
- The description of the base spell can stay the same:
- Add a new variant in the details tab:
- Variants have their own spell sheet and can be edited independently of the base spell:
- Add additional variants as needed:
<br>
<br>
The variants can be sorted via drag and drop on the spell sheet and the prompt buttons are displayed in the same order.

Add support for spell variants of spells with a variable cast time

---

packs/data/feat-effects.db/effect-blade-ally-anarchic-rune.json
packs/data/feat-effects.db/effect-blade-ally-axiomatic-rune.json
packs/data/feat-effects.db/effect-blade-ally-disrupting-rune-greater.json
packs/data/feat-effects.db/effect-blade-ally-disrupting-rune.json
packs/data/feat-effects.db/effect-blade-ally-fearsome-rune.json
packs/data/feat-effects.db/effect-blade-ally-flaming-rune.json
packs/data/feat-effects.db/effect-blade-ally-ghost-touch-rune.json
packs/data/feat-effects.db/effect-blade-ally-holy-rune.json
packs/data/feat-effects.db/effect-blade-ally-keen-rune.json
packs/data/feat-effects.db/effect-blade-ally-unholy-rune.json

Closes #2867 
Adds Critical Specialization Rule Elements to `Effect: Blade Ally x`
Update ChoiceSet with `"flag":"weaponSelect"`
Updated all REs to use new flag.
Update Effect: Blade Ally Disrupting Rune note RE
Update several REs to predicate on correct traits (evil, good etc.)

Update Blade Ally Effects

---

src/module/actor/sheet/item-summary-renderer.ts
src/module/chat-message/index.ts
src/module/chat-message/listeners/cards.ts
src/module/item/spell/index.ts
src/module/item/spell/overlay.ts
src/module/item/spell/sheet.ts
src/module/item/spellcasting-entry/index.ts
src/styles/legacy/_chat.scss
static/lang/en.json
static/templates/actors/spellcasting-spell-list.html
static/templates/chat/spell-card.html
static/templates/items/item-sheet.html

- Remove the SpellVariantPrompt class.
- Show spell variants as inline buttons on the spell chat card.
- Update the existing chat card with the selected variant data.
- Add a button to variant spell chat cards that allows the selection of another variant.
- Disable editing the description of spell variants.
- Remove spell chat buttons for users that are not the owner of that spell.

Update spell variant implementation

---

src/scripts/hooks/canvas-ready.ts

Game initialization is such that ActorPF2e#checkAreaEffects is called twice, with the second from the canvasReady hook. If both calls find an effect to remove, they'll both send up a request to remove it get back an error from the server.

Remove redundant area-effect check on initial canvas-ready call

---

packs/data/feats.db/healing-bomb.json

The trait "Additive 2" does not appear in Foundry for the feat Healing Bomb. This is because it has the trait value "additive 2" instead of "additive2".

Fixed the healing bomb feat traits

---

src/module/system/action-macros/crafting/repair.ts

For the Repair basic action, add all traits of the target item as roll options with the format "target:trait:xyz". This will allow situational modifiers to predicate on those traits.

Add target item traits as roll options for the Repair action

---

packs/data/pathfinder-bestiary.db/poltergeist.json
packs/data/pfs-season-1-bestiary.db/elite-skeletal-giant-pfs-1-18.json
packs/data/pfs-season-1-bestiary.db/flesh-golem-pfs-1-25.json
packs/data/pfs-season-1-bestiary.db/guard-pfs-1-17.json
packs/data/pfs-season-1-bestiary.db/murderous-bathhouse-3-4.json
packs/data/pfs-season-1-bestiary.db/murderous-bathhouse-5-6.json
packs/data/pfs-season-1-bestiary.db/palace-guard-pfs-1-17.json
packs/data/pfs-season-1-bestiary.db/the-ascendant-3-4.json
packs/data/pfs-season-1-bestiary.db/the-ascendant-5-6.json
packs/data/pfs-season-1-bestiary.db/unkillable-zombie-brute-pfs-1-13.json
packs/data/pfs-season-1-bestiary.db/zombie-brute-pfs-1-18.json
packs/data/pfs-season-2-bestiary.db/fence-pfs-2-00.json
packs/data/pfs-season-2-bestiary.db/kobold-warrior-pfs-2-11.json
packs/data/pfs-season-3-bestiary.db/fasiel-ibn-sazadin-1-2.json
packs/data/pfs-season-3-bestiary.db/fasiel-ibn-sazadin-3-4.json
packs/data/pfs-season-3-bestiary.db/filth-fire-pfs-3-01.json
packs/data/pfs-season-3-bestiary.db/grimple-pfs-3-18.json
packs/data/pfs-season-3-bestiary.db/nuglub-pfs-3-18.json

Adds ability glossary entry to Poltergeist in bestiary 1.
Corrects naming of several season 1, 2, and 3 PFS entries

Add NPCs from PFS 1-13

---

packs/data/pathfinder-bestiary.db/goblin-pyro.json
packs/data/pfs-season-1-bestiary.db/collapsing-floor.json
packs/data/pfs-season-1-bestiary.db/crowd-agitator.json
packs/data/pfs-season-1-bestiary.db/crowd-with-chamberpots.json
packs/data/pfs-season-1-bestiary.db/crowd-with-trash.json
packs/data/pfs-season-1-bestiary.db/crumbling-floor.json
packs/data/pfs-season-1-bestiary.db/deeply-flawed-ritual.json
packs/data/pfs-season-1-bestiary.db/flawed-ritual.json
packs/data/pfs-season-1-bestiary.db/fleshforge-dreg-acid-spit.json
packs/data/pfs-season-1-bestiary.db/fleshforge-dreg-leaping-charge.json
packs/data/pfs-season-1-bestiary.db/fleshforge-dreg-reach.json
packs/data/pfs-season-1-bestiary.db/fleshforge-dreg-roots.json
packs/data/pfs-season-1-bestiary.db/fleshforge-dreg-shield.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-acid-spit.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-breath-weapon.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-leaping-charge.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-reach.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-roots.json
packs/data/pfs-season-1-bestiary.db/fleshforge-prototype-shield.json
packs/data/pfs-season-1-bestiary.db/goblin-warrior-pfs-1-01.json
packs/data/pfs-season-1-bestiary.db/greater-shadow-wisp.json
packs/data/pfs-season-1-bestiary.db/rending-hands.json
packs/data/pfs-season-1-bestiary.db/scrabbling-hands.json
packs/data/pfs-season-1-bestiary.db/shadow-wisp.json
packs/data/pfs-season-1-bestiary.db/unkillable-zombie-brute-pfs-1-01.json
packs/data/pfs-season-1-bestiary.db/weak-ceustodaemon-pfs-1-01.json
packs/data/pfs-season-1-bestiary.db/whispering-souls.json
packs/data/pfs-season-1-bestiary.db/whispering-spirits.json

Corrects B1 Goblin Pyro, which had its own strike block for torch (improvised, autogenerated one was incorrect).
Closes #1601

Add or Update NPCs from PFS 1-01

---

packs/data/spells.db/harm.json
packs/data/spells.db/heal-animal.json
packs/data/spells.db/heal-companion.json
packs/data/spells.db/heal.json

Heal and harm have two versions of the 2 action, for a living/undead target, so that the bonus healing for the correct target can be added.
Formatting of the spells aligned to match CRB (i.e. **(somatic)** rather than (somatic) or **somatic**, and no bullet before action symbol).

Add spell variants for heal, harm, heal animal, heal companion

---

src/module/actor/character/data/types.ts
src/module/actor/character/index.ts

If left alone, it caps focus to 3, but if an AELike or module alters it, that becomes the new mechanical limit.

Add a secret focus cap property that can be overwritten by REs/modules

---

packs/data/bestiary-effects.db/effect-countered-by-fire.json
packs/data/bestiary-effects.db/effect-countered-by-water.json
packs/data/bestiary-effects.db/effect-fed-by-wood.json
packs/data/pathfinder-bestiary-3.db/adult-sky-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/adult-sky-dragon.json
packs/data/pathfinder-bestiary-3.db/adult-underworld-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/adult-underworld-dragon.json
packs/data/pathfinder-bestiary-3.db/ancient-sky-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/ancient-sky-dragon.json
packs/data/pathfinder-bestiary-3.db/ancient-underworld-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/ancient-underworld-dragon.json
packs/data/pathfinder-bestiary-3.db/young-sky-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/young-sky-dragon.json
packs/data/pathfinder-bestiary-3.db/young-underworld-dragon-spellcaster.json
packs/data/pathfinder-bestiary-3.db/young-underworld-dragon.json

I realized I created some inconsistency for the imperial dragons, because some had effects for their "countered by ..." and "fed by ..." abilities while others were done with toggles. I changed all to effects for better duration tracking.

B3 - Add countered by and fed by effects to imperial dragons

---

packs/scripts/run-migration.ts
src/module/item/base.ts
src/module/migration/migrations/765-choice-owned-item-types.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/choice-set/data.ts
src/module/rules/rule-element/choice-set/rule-element.ts

Existing ones should still pick weapons, but the types array will allow non-spells. There is a migration, but it doesn't affect our compendium at all.

Expand choice set owned items to non-weapons

---

src/module/migration/migrations/653-aes-to-res.ts
src/module/rules/rule-element/ae-like.ts
src/util/misc.ts

Retested each, including via running `extractPacks all` to confirm no JSON files are renamed.

Remove lookbehind assertions

---

src/module/actor/base.ts
src/module/canvas/token/auras.ts

When multiple tokens are within an aura, it may be the case the more than one refer back to a single actor. This won't solve every issue with auras hitting an actor twice, but it eliminates one source of the problem.

Ensure unique actors are checked for aura effects

---

src/module/actor/character/data/sheet.ts
src/module/actor/character/data/types.ts
src/module/actor/character/feats.ts
src/module/actor/character/index.ts
src/module/actor/character/sheet.ts
src/module/item/class/index.ts
src/module/item/feat/index.ts
static/templates/actors/character/tabs/feats.html

Should be easier to add new custom feat groups after this. However the way feats are assigned still bothers me, but I don't know a good way to handle that yet. If actor.items is sorted, I could do it in prepareActorData() and it might be cleaner?
After this, it should be easy to store bonus feat categories in actor flags or homebrew settings or whatever and construct them.

Refactor feat group assignment into feat categories

---

.betterer.results
src/module/system/action-macros/acrobatics/maneuver-in-flight.ts
src/module/system/action-macros/acrobatics/tumble-through.ts
src/module/system/action-macros/athletics/long-jump.ts
src/module/system/action-macros/deception/create-a-diversion.ts
src/module/system/action-macros/deception/impersonate.ts
src/module/system/action-macros/deception/lie.ts
src/module/system/action-macros/diplomacy/gather-information.ts
src/module/system/action-macros/exploration/avoid-notice.ts
src/module/system/action-macros/exploration/track.ts
src/module/system/action-macros/nature/command-an-animal.ts
src/module/system/action-macros/stealth/hide.ts
src/module/system/action-macros/stealth/sneak.ts
static/lang/en.json

Potential fix for: https://github.com/foundryvtt/pf2e/issues/2973
Actions with a Success note but not Critical Success note or with a Failure note but no Critical Failure note won't display any note when rolling a Critical Success or Failure. 
Since the effect of an action in these cases is identical to the regular Success or Failure case, we can duplicate the notes instead of showing nothing.

add missing crit success and fail notes to actions

---

src/module/actor/base.ts
src/module/scene/document.ts
src/module/scene/token-document/document.ts

Also adds a lock for `ScenePF2e#checkAuras` to prevent concurrent executions

Remove aura effects on token deletion

---

src/module/item/abc/index.ts
src/module/item/base.ts

Besides ABC items, heritage and feats also need to be handled

Move PC hit-point overage handling to base item class

---

packs/data/one-shot-bestiary.db/kelorbeyan-guard.json

Corrects Kelorbeyan Guard Longsword attack modifier from +0 to +14 per Mark of the Mantis statblock.

Update Kelorbeyan Guard Longsword attack modifier.

---

src/scripts/macros/treat-wounds.ts

The macro wasn't working for characters that don't have the Chirurgeon or Natural Medicine skill because the `name="skill"` HTML element was missing.
Also the DC was always based off the highest possible skill rank instead of the selected value.

Fix Treat Wounds macro

---

packs/data/spell-effects.db/spell-effect-elemental-form-air.json
packs/data/spell-effects.db/spell-effect-elemental-form-earth.json
packs/data/spell-effects.db/spell-effect-elemental-form-fire.json
packs/data/spell-effects.db/spell-effect-elemental-form-water.json

Non-medium creates using 5th level elemental form would previously be left at their non-medium size even though the spell specifies that you become a medium elemental. Now the 5th level spell effect will properly set the token size to medium.

update elemental form to properly size non-medium creates.

---

packs/data/feat-effects.db/effect-dread-marshal-stance.json
packs/data/feat-effects.db/effect-inspiring-marshal-stance.json
packs/data/feat-effects.db/effect-reflective-ripple-stance.json
packs/data/feat-effects.db/stance-everstand-stance.json

Closes #3045
Changes Duration from Unlimites to "End of Encounter" on:
- Effect: Dread Marshal Stance
- Effect: Inspiring Marshal Stance
- Effect: Reflective Ripple Stance
- Effect: Everstand Stance
Removes "Sustained" from Effect: Reflective Ripple Stance.
Adds "Show Token icon" to Effect: Reflective Ripple Stance.

Update 4 Stance Effects Duration

---

packs/data/deities.db/atheism.json

There is currently only one data entry with more than one source: the "Atheism" deity.
```
"source": {
"value": "Pathfindier Core Rulebook, Pathfinder Lost Omens: Gods & Magic"
},
```
In addition to a spelling error ("Pathfindier" instead of "Pathfinder"), it uses "," as a separator. However, some sources such as "Pathfinder Lost Omens: Absalom, City of Lost Omens" use a "," in their name, invalidating the use of "," as a separator.
The future-proof way to solve this would be to change the data type to an array but that would mean changing every data entry. This is not ideal, especially for only one problematic entry.
As a compromise, I would only change the "," to ";" in this specific data entry (and all future data entries with mixed sources), hoping that Paizo will never release …

Fixed source value and separator for the Atheism deity

---

packs/data/spells.db/aspirational-state.json
src/scripts/config/traits.ts

With the fixes added previously to allow multiple schools to be added via Traits, this should work for resolving https://github.com/foundryvtt/pf2e/issues/2447 at this time.

Add Aspirational State Ritual from PFS 2-22

---

src/module/actor/sheet/popups/ability-builder.ts

I accidentally slipped in the new name in the template, this renames it in the code as well. It'll soon contain the number of voluntary flaws in that one slot (so we can handle double flaws).

Fix regression with voluntary flaws

---

packs/data/spell-effects.db/spell-effect-righteous-might.json
src/module/actor/character/data/types.ts
src/module/actor/modifiers.ts
src/module/item/deity/document.ts
src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/battle-form/types.ts
src/module/rules/rule-element/damage-dice.ts
src/module/rules/rule-element/iwr/base.ts
src/module/system/damage/weapon.ts

This will allow a Battle Form strike to be a compendium weapon query, which is pulled from the actor's deity.
Closes #2797

Build out support for (most of) Righteous Might spell effect

---

src/styles/item/_index.scss
src/styles/item/_rules.scss
src/styles/ui/_tags.scss
static/templates/items/spell-details.html

There's a new issue where if you have 4 traditions and delete one, it flashes to 2 lines and goes back to 1 line, but I don't think it matters too much.

Avoid traditions/traits line wrapping

---

packs/data/equipment.db/staff-of-illusion-greater.json
packs/data/equipment.db/staff-of-illusion-major.json
packs/data/equipment.db/staff-of-illusion.json

Also adds Ventriloquism to the 2nd level spells provided by the Staffs; this is present in all three versions of the CRB.
Closes https://github.com/foundryvtt/pf2e/issues/3010.

Correct description of the Staff of Illusion Items

---

packs/data/age-of-ashes-bestiary.db/falrok.json
static/lang/re-en.json

Changed RuleElement of AoA: Falrok to use re-en.json

Localize Skill Variant for Falrok (AoA)

---

packs/data/conditionitems.db/drained.json
src/module/item/base.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/lose-hit-points.ts

Potential fix for https://github.com/foundryvtt/pf2e/issues/2962
I hope there can be a neater solution to this but I struggled to find something that didn't resort to hard coding. The problems with drain are:
- Hooking into preUpdateActor won't work since the condition is being updated, not the actor
- Making a new preUpdateItem method could be promising but...
- Since we're incrementing a condition we need to know the previous value and new value, to avoid removing too much health
There were other issues but essentially I struggled to find a way to do this in a clean, generic way. This solution works but it most likely would be better somewhere else instead of on an RE. Happy to hear suggestions.

Fix Drained Condition Health Removal

---

src/global.d.ts
src/module/actor/npc/sheet.ts
src/module/actor/npc/types.ts
src/module/system/settings/index.ts
static/lang/en.json
static/templates/actors/partials/item-line.html

This is the last bit of polish for the initial feature release, so the PR also removes the secret setting that hid it.

Get confirmation from user before replacing generated NPC attacks

---

src/module/item/action/data.ts
src/module/item/action/index.ts
src/module/item/action/sheet.ts
src/module/item/data/base.ts
src/module/item/feat/data.ts
src/module/item/feat/index.ts
src/module/item/feat/sheet.ts

Not just less noise, but feats with 2 uses for hours should no longer display 1 use.

Frequency value is optional data

---

src/module/scene/token-document/aura/index.ts

It turns out it queries the scene too early

Move TokenAura#radiusPixels back to getter

---

packs/data/spells.db/dancing-shield.json
packs/data/spells.db/dividing-trench.json
packs/data/spells.db/falling-sky.json
packs/data/spells.db/focusing-hum.json
packs/data/spells.db/foresee-the-path.json
packs/data/spells.db/frenzied-revelry.json
packs/data/spells.db/ghostly-shift.json
packs/data/spells.db/isolation.json
packs/data/spells.db/pact-broker.json
packs/data/spells.db/rally-point.json
packs/data/spells.db/scouring-pulse.json
packs/data/spells.db/shadow-zombie.json
packs/data/spells.db/string-of-fate.json
packs/data/spells.db/time-skip.json
packs/data/spells.db/wall-of-virtue.json

Review spells by pulling data from Archives of Nethys' Elasticsearch backend. All changes were manually reviewed against the original PDFs; except Shadow Zombie, which I do not own.

Review spells against Nethys

---

src/module/system/damage/roll-dialog.ts
src/module/system/damage/weapon.ts

If there is both dice and a modifier to a non-base damage type, the modifier will be dropped.
Before and after:
Closes #3272

Fix cases of wrongly excluded flat damage modifiers

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Make aura effects have unlimited duration (still removed on exiting aura if configured so)
* (stwlam) Warn GMs when the "Foundry Community Macros" module is enabled
* (stwlam) Fix cases of secondary damage types (e.g., draconic rage fire damage) being wrongly excluded if there are also extra dice of the same damage types
* (stwlam) Take small measure to ensure FlatModifier REs to have unique slugs
* (Manni) Fix details and localization of some Age of Ashes actors
* (SpartanCPA) Remove duplicate Sylvan Wine effect and mistakenly added wineskin item
* (stwlam) Set Aura of Misfortune effect to not automatically remove itself on roll
* (stwlam) Add auras to Overwatch Dedication and Wide Overwatch feats
* (stwlam) Add abjuration trait to Spellguard Blade
* (Tikael) Audit rule …

Release Notes 3.13.5

---

src/module/actor/base.ts

We can break backwards compatibility if you'd rather to do that, but I'd like to at least support `@actor.level` for simple roll macros.

Support @ actor in roll macros

---

static/templates/compendium-browser/filters.html

In the "Spells" tab of the compendium browser, the "Casting time" select element has a weird behavior where selecting a value correctly filters the data but the option displayed by the select element does not change.
It is because a local variable in the handlebars template has the same name as the handlebars helper "select". Changing the name of the variable fixes the issue.
I also renamed an other "select" variable for consistency.

Fix the timefilter select behavior in the spell compendium browser

---

src/module/apps/compendium-browser/index.ts

For when there actually is such a property in the index.

Update PackLoader check to use `system`

---

src/module/actor/spellcasting.ts
src/module/item/consumable/index.ts
src/module/item/spellcasting-entry/index.ts

Basic oscillating wave using items support, but not oscillating wave archetype using items support. The latter is more complicated.
Also updates consumables for v10, but only for new consumables. We need migrations for the old ones.

Allow scrolls/wands for entries that contain the spell

---

packs/data/equipment.db/chakram.json
packs/data/equipment.db/tamchal-chakram.json

Updating to adhere to specifics of Thrown trait:
> When this trait appears on a melee weapon, it also includes the range increment. Ranged weapons with this trait use the range increment specified in the weapon’s Range entry.

Fix melee/ranged status of chakrams

---

src/module/migration/runner/base.ts
types/foundry/common/abstract/document.d.ts

`Item.migratedData` removes `data` and adds `system` but does not update the database so the item has both after the migration but I believe that shouldn't be a problem.

Add a way to catch up embedded item source data to the current DataModel

---

src/styles/item/_sidebar.scss
src/styles/legacy/_pf2e.scss

Why are we even selecting on input names? :\

Convert "data." to "system." in css name attribute selectors

---

static/templates/actors/character/sheet.html

Use newly available wand-magic-sparkles icon for PC spellcasting tab

---

src/styles/actor/character/_proficiencies.scss
static/templates/actors/character/tabs/proficiencies.html

This was broken when I did the change for action headers, aka the crafting/spellcasting thing.

Update character proficiency tab to new headers

---

src/module/actor/base.ts
src/module/item/base.ts
src/module/rules/rule-element/grant-item/base.ts

- GrantItem RE was no longer operating on original item source
- `Actor#_preCreate` is passed incomplete actor source, causing unhandled exceptions in property lookups

Fix pair of regressions from V10 conversion work

---

src/module/actor/base.ts
src/module/rules/rule-element/token-image.ts
src/module/scene/token-document/document.ts
types/foundry/client/documents/token-document.d.ts

`TokenDocument#_onUpdateBaseActor` is documented as being `@protected` but then called publicly in foundry.js

Update TokenImage RE for V10

---

src/module/journal-entry/sheet.ts
src/scripts/hooks/index.ts
src/scripts/hooks/render-journal-page-sheet.ts
src/styles/system/journal/_index.scss
types/foundry/client/application/journal/journal-page-sheet.ts
types/foundry/client/core/hooks.d.ts
types/foundry/client/documents/constructors.d.ts
types/foundry/client/documents/journal-entry-page.d.ts
types/foundry/client/documents/journal-entry.d.ts
types/foundry/common/data/data/index.d.ts
types/foundry/common/data/data/journal-entry-data.d.ts
types/foundry/common/data/data/journal-entry-page-data.d.ts
types/foundry/common/documents/base-journal-entry-page.d.ts
types/foundry/common/documents/base-journal-entry.d.ts
types/foundry/common/documents/index.d.ts

TinyMCE uses an iframe, so for that we'll need to subclass JournalTextPageSheet and replace it during sheet registration to inject the theme, or use setTimeout(blah, 0) to wait for the iframe to initialize and then inject it there as part of the hook.  We're waiting on an answer from Kim before merging.
I wouldn't mind the hacky hack the iframe approach since tinymce is apparently being phased out.

Cascade pf2e styling to prosemirror editor sheet

---

src/module/actor/base.ts
src/module/canvas/token/object.ts
src/module/item/abc/manager.ts
src/module/item/base.ts
src/module/scene/token-document/document.ts
src/module/system/effect-tracker.ts
src/module/system/settings/automation.ts
src/scripts/hooks/migration-complete.ts

In V9, `document.prepareData()` called `document.reset()`, restoring the document's data to its source state. Now the relationship has been inverted (`document.reset()` resets and then calls `document.prepareData()`), meaning `document.prepareData()` can prepare over an already-prepared state.

Avoid double data preparation

---

src/module/system/text-editor.ts
types/foundry/client/core/text-editor.d.ts

Based on `Roll#evaluate`.
The first overload in `TextEditorPF2e` was necessary to pass type checks, not sure why.

Add async overloads to `TextEditor.enrichHTML` and `TextEditorPF2e.enrichHTML`

---

types/foundry/client/collections/compendium-collection.d.ts

Also updates `CompendiumIndexData` to reflect that the `img` property is now always retrieved

Add type definition for `fromUuidSync` helper function

---

src/module/rules/rule-element/token-light.ts
src/module/scene/token-document/document.ts

Foundry V10 now calls Document#_initialize every data preparation cycle, whereas it used to only call it during class construction.

Set `TokenDocumentPF2e#initialized` only once

---

src/module/actor/character/index.ts

Fix for #3403 
Level 0 characters are [still allowed to take level 1 boosts](https://2e.aonprd.com/Rules.aspx?ID=1344)
Could also rename `Level 1` to `Initial`? But I think level 0 characters are niche enough to not warrant a change.

Allow ability score boosts at level 0

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/apps/compendium-browser/data.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/data.ts

I would like to use the game.pf2e.compendiumBrowser.openTab function in macros to open the compendium browser with feats or spells of a particular level but it does not currently take a "minLevel" parameter.
To keep the function backwards compatible, I added the parameter in the last position with a default value. I would be happy to change it to something like levelFilter: { min: number; max: number; } if need be.

Expand filter parameters for game.pf2e.compendiumBrowser.openTab()

---

src/global.d.ts
src/scripts/set-game-pf2e.ts

I don't want us to have to support these as blessed public API when they might get the 🪓 at some point in the near future.

Remove `AbilityModifier` and `ProficiencyModifier` from `game.pf2e`

---

packs/data/feats.db/basic-lesson.json
packs/data/feats.db/glean-lore.json
packs/data/spells.db/breath-of-life.json
packs/data/spells.db/claim-undead.json
packs/data/spells.db/debilitating-dichotomy.json
packs/data/spells.db/thunderburst.json

A few Oracle items had random new paragraphs, likely a result of copying straight from a PDF.
Also fixed Breath of Life, had an incorrect Dying link, and basic lesson, had a stray `<hr />`

Correct formatting errors for Oracle

---

packs/scripts/run-migration.ts
src/module/migration/migrations/775-agile-finesse-ranged.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

The system's alternate usages now classify thrown melee weapons as ranged weapons when thrown, requiring an adjustment to REs that predicate on them.
Closes #3605

Fix features requiring agile/finesse/ranged weapons

---

src/module/item/condition/index.ts
src/scripts/hooks/init.ts
types/foundry/client/config.d.ts
types/foundry/client/pixi/placeable-object/token.d.ts

Core randomly hooks up two status effects with vision: invisibility and blindness. It should still serve as a good basis for reimplementing RBV.

Link up system conditions to V10's status effect automation

---

src/styles/item/_rules.scss

This bug also exists in the previous version

Fix rules json editor vertically overflowing with more lines

---

packs/data/equipment.db/caterwaul-sling.json

It had a specific icon before but it's not a slingshot, it's a sling.

Change Caterwaul Sling icon to Sling

---

CHANGELOG.md

* (Supe) Improve visibility of traits when viewing item sheets from locked compendiums
* (stwlam) Restore PFS level bump to damage rolls
* (stwlam) Include constitution modifier when calculating level-zero PC hit points
* (stwlam) Exclude negative ability modifiers from battle form damage
* (stwlam) Fix issue preventing penalties to strength-based damage rolls from affecting NPCs
* (Supe) Fix issue preventing action frequency values from being updated
* (SpartanCPA, Tikael) Add content from book 2 of _Blood Lords_

Release Notes 3.13.6

---

packs/data/backgrounds.db/magical-experiment.json
static/lang/re-en.json

Technically the darkvision will end up not being automated if your low light vision is from your heritage, but that's a niche case for a subset of a rare background so I'm not worried.
Closes #3574

Add automation to the Magical Experiment background.

---

src/module/actor/sheet/base.ts
src/module/item/sheet/base.ts
src/util/tags.ts

https://user-images.githubusercontent.com/1286721/188336177-0366a9ce-f5e7-4061-920e-7ece612d6c80.mp4
The only glitchiness seems to be if while the dropdown is open, you change windows, then come back. But that's tagify in general.

Refocus tagify on re-render

---

src/module/system/text-editor.ts
src/styles/legacy/_chat.scss
src/styles/mixins/_tinymce.scss

Turns out those empty `<p>` tags have always existed, but in foundry v10 they all have a minimum height now.

Fix empty gap created by @Localize and use all sub-elements

---

src/styles/actor/tabs/_bio.scss
static/templates/actors/vehicle/tabs/vehicle-description.html

The styles affect character sheets, by making the biography appearance editors slightly bigger when you start editing as well. I can only consider this a good thing.

Fix display and deprecation warnings in vehicle biography screen

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Fix issue causing auras to not appear until after their source is removed
* (stwlam) Fix issue causing some AE-like rule elements to not apply
* (stwlam, Supe) Fix vision and detection modes not functioning when rules-based vision is disabled
* (Supe) Fix display and deprecation warnings in vehicle biography tab
* (Supe) Fix display of scrollbars in hazard sheet
* (Supe) Fix UI error thrown when editing hazard traits
* (Dooplan) Fix level of Icewyrm
* (Shandyan) Automate strix feats

Release Notes 4.0.0-beta2

---

src/module/apps/compendium-browser/tabs/base.ts

The params on `mergeObject` seemed to be backwards: the current `filterData` should be the object being overwritten by the default values. Plus there doesn't seem to be a reason to declare `filterData` as `{ search }` beforehand.

Clear search bar in compendium browser when filters are cleared

---

src/module/actor/sheet/base.ts
src/module/item/sheet/base.ts
src/module/sheet/helpers.ts

This isn't broken in the 4.0.0-beta2, and only revealed itself once actor traits was unflattened. This adds an additional check to make sure its the same sheet, which is what it should have done in the beginning.

Fix tagify refocus regression for npc embedded item traits

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (LebombJames) Clear search bar in compendium browser when filters are cleared
* (stwlam) Restore damage types to spell sheet
* (stwlam) Fix race condition causing kits to inflate with incorrect item quantities
* (stwlam) Fix issue causing advanced alchemy formulas to not be removable
* (Supe) Fix removing Elite/Weak adjustments

Release Notes 4.0.0-beta3

---

static/lang/en.json

Foundry calls them "Combat Encounter" and "Counter Encounters," respectively.

Rename another DnD-ism introduced in V10

---

src/module/actor/base.ts
src/scripts/hooks/drop-canvas-data.ts

This only became possible when familiar sheets were refactored to inherit from `ActorSheetPF2e`.

Add support for item drops on familiar tokens

---

src/module/item/physical/index.ts

Show the correct item name in parentheses when mystified

---

src/module/chat-message/document.ts
src/module/chat-message/listeners/cards.ts
src/util/dom.ts

Seems to continue working for spells and strikes. Interestingly enough, the original logic resolved spells to unarmed strikes, so I had to add an extra check.

Add strike getter to chat message for module use

---

src/module/system/text-editor.ts
types/foundry/client/core/text-editor.d.ts

The built in text editor enrich is able to handle null. Our override was not. Fixes #3873 
Though I'm uncertain if we even need this bit of code here.

Fix error when enriching null strings

---

src/module/chat-message/document.ts
src/module/chat-message/listeners/cards.ts

I'll rewrite chat message strike handling code after the next release, and then get item() will return the strike item. However I suspect that retrieving the strike from a message will still be needed for the chat message handling code regardless.

Make ChatMessage's strike getter semi-private in the meantime

---

src/module/item/sheet/base.ts
src/module/item/sheet/data-types.ts
static/templates/items/item-sheet.html

There's a small delay where the traits visibly shift around after adding it, since tagify will add the new tag then foundry will update. I think that should be fine 🤷 .

Sort item traits in sheet header

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Add support for item drops on familiar tokens
* (stwlam) Add a basic hearing detection mode
* (stwlam) Only show repost buttons on chat messages to message owners
* (stwlam) Consolidate shallow/deep search in compendium sidebar
* (stwlam) Change default order-by for most compendium browser tabs to level
* (GravenImageRD) Show the correct item name in parentheses when mystified
* (In3luki) Fix Compendium Browser pack selection not being saved
* (stwlam) Fix removal of basic unarmed attack causing strike-index mismatching
* (stwlam) Fix composite longbows/shortbows sometimes not being recognized as equivalent to standard longbows/shortbows
* (stwlam) Fix strike drops on hotbar
* (stwlam) Fix pair of rendering issues with darkness adjuster when viewed scene is changed
* (stwlam) …

Release Notes 4.0.1

---

types/foundry/client/game.d.ts
types/foundry/client/ui/index.d.ts
types/foundry/client/ui/tooltip.d.ts

The `private` methods are defined as private in the JSDoc. `clearPending` is defined as `interal` so I made it `proteced`.
The JSDoc for `deactivate` is probably wrong and it should be public.

Add type definitions of `TooltipManager`

---

src/module/chat-message/document.ts
src/module/chat-message/listeners/cards.ts

Took a crack at starting cleanup for the card message handling but to be honest I don't know how to fully clean this thing up.

Make ChatMessage#item return the strike weapon if available

---

src/module/item/armor/data.ts
src/module/item/consumable/data.ts
src/module/item/container/data.ts
src/module/item/equipment/data.ts
src/module/item/physical/data.ts
src/module/item/weapon/data/types.ts
src/module/migration/migrations/786-remove-identified-data.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

No identification data is in compendium JSON, so no internal migration needed.

Remove stored identified data on physical items

---

packs/scripts/run-migration.ts
src/module/migration/migrations/787-resolvables-to-system.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

I must have accidentally dropped this part from the migration while writing it, but not before having it run on compendium JSON. :\

Migrate weapon and spell resolvables to use .system

---

packs/data/extinction-curse-bestiary.db/doblagub.json
packs/data/feats.db/feverish-enzymes.json
packs/data/feats.db/hellknight-dedication.json
packs/data/feats.db/skill-mastery-rogue.json
packs/data/feats.db/terrified-retreat.json
packs/data/outlaws-of-alkenstar-bestiary.db/slick.json
packs/data/pathfinder-bestiary-2.db/froghemoth.json
packs/data/pathfinder-bestiary-2.db/giant-chameleon.json
packs/data/pfs-season-3-bestiary.db/khisisi-5-6.json
packs/data/pfs-season-3-bestiary.db/khisisi-7-8.json
static/lang/re-en.json

- (Dods) Add automation to Skill Mastery (Rogue)
- (Friz) Fix rule elements on Terrified Retreat, Feverish Enzymes, and Hellknight Dedication feats
- (Friz) Brushup Doblagub
- (Timingila) Updated Despair aura of Khisisi
- (Xdy) Fix All-Around Vision on several NPCs

Data Entry World fixes for September 3 2022

---

src/module/item/sheet/base.ts
src/styles/item/_index.scss

This also removes the specific font size override on certain form elements in the item sheet. That font size override should be done more generally rather than being tied to a layout element, but we stand to change too much if we apply it globally so I just removed it for now. Sneaky fix for a sizing inconsistency in the flat modifier rule element form.

Fix certain item sidebar styling

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Hide damage buttons for not-damaging weapons (e.g., Tanglefoot Bag)
* (Supe) Have ChatMessage#item return the strike weapon if available (for module usage)
* (In3luki) Fix distribute coin popup
* (stwlam) Prevent context menu from appearing on right click in status effects menu for some OS/browser combinations
* (stwlam) Include journal entries in compendium search
* (stwlam) Fix issue causing post-to-chat button to not appear for @Check expressions in journal entry pages
* (stwlam) Migrate weapon and spell resolvables in rule elements for V10 compatibility
* (stwlam) Fix persistent damage icon path
* (stwlam) Fix multiple issues causing roll notes to display with superfluous line breaks
* (stwlam) Fix obscuring sender names on chat messages when feature is enabled
* (stwlam) …

Release Notes 4.0.4

---

src/module/system/rolls.ts

This shouldn't have any negative side effects as the flavor is enriched in `ChatMessagePF2e#getHTML` anyways.
Closes #3931

Fix metagame information being stripped from message flavor before the chat message is created

---

static/templates/items/class-details.html

I've also moved the class feature block before the inline template declarations.

Fix display of class features in the class item sheet details tab

---

src/module/actor/creature/sheet.ts
src/module/actor/creature/spell-preparation-sheet.ts
src/module/actor/creature/types.ts
src/module/actor/spellcasting.ts
src/module/item/spellcasting-entry/collection.ts
src/module/item/spellcasting-entry/data/sheet.ts
src/module/item/spellcasting-entry/index.ts
static/templates/actors/character/tabs/spellcasting.html
static/templates/actors/npc/tabs/spells.html

Everything should still work the same since nothing actually sets the spell collection to null currently. The structure of the result of getSpellData() is starting to get creaky at the seams, but I'd rather not break compatibility with TAH for no good reason.

Optional-ize Spell collection

---

packs/data/equipment-effects.db/effect-blaze.json

Fixed Blaze effect by replacing "not" with "all", in the predicate.

Fix Blaze effect

---

src/module/actor/character/index.ts
src/module/actor/creature/index.ts
src/module/actor/hazard/index.ts
src/module/actor/npc/index.ts
src/module/actor/vehicle/index.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts
src/module/system/text-editor.ts

If we ever need to add additional roll notes, that can be a roll() argument or we can bring back the argument and make it behave accordingly depending on the use case.

Extract notes in statistic rather than passing it in

---

src/module/system/statistic/index.ts

The function its being passed to can handle duplicate roll options since it resolves into a Set anyways.

Fix regression with statistic inline rolls

---

src/module/actor/base.ts
src/module/actor/character/index.ts
src/module/actor/familiar/index.ts
src/module/actor/npc/index.ts
src/module/rules/rule-element/adjust-degree-of-success.ts
src/module/rules/synthetics.ts
src/module/rules/util.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts

Bonus: Statistic.data is now fully private.  I don't know if I caught all cases, but character saves adjust properly and those are the most important. Skills such as silvertongue mutagen work even with @xdy module, which is being extra naughty and using the deprecated StatisticModifier skill check functions. 
The "type" parameter in the AdjustDegreeOfSuccess rule element is no longer necessary (was it ever?), we can cull it from data with a migration later.

Move degree of success adjustments into synthetics

---

src/module/actor/character/index.ts

closes #3664, supersedes #4048,

Lower enforced PC ability score cap to 1

---

src/scripts/config/index.ts

Add undetected condition to token HUD

---

.betterer.results
src/module/actor/creature/sense.ts
src/scripts/config/index.ts
static/lang/en.json

WIP PR: 
I'm working on adding spiritsense to the list of senses in the system (re: issue #3942), and I've added it to src\scripts\config\index.ts Record of senses and to the src\module\actor\creature\sense.ts Set of SENSE_TYPES. 
I'm not getting the validation error any more, but in the list of available senses I'm not getting the nice label (I'm not great at style/html stuff) 
I've checked in static\templates\system\tag-selector\senses.html, but I can't find anything there that would make spiritsense any different from say motionsense or lifesense

Add spiritsense to types of senses

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (In3luki) Update Compendium Browser text search to utilize `MiniSearch`
* (sturteva) Add spiritsense to available creature sense types
* (stwlam) Add limited support for DamageDice REs in spells (reflected in Healing/Harming Hands feats)
* (stwlam) Add support for hearing through walls that don't block sound (thanks to dev8675309 for assistance!)
* (stwlam) Incorporate V10 tremorsense detection mode
* (stwlam) Add undetected condition to token HUD
* (stwlam) Lower enforced PC ability score cap to 1 while in manual-entry mode
* (Supe) Add structured form for editing FlatModifier rule elements
* (stwlam) Fix token mirroring when scale is locked
* (stwlam) Fix issue causing secret text in journal entry text pages to become visible to players
* (InfamousSky) Add Glass Skin feat
* …

Release Notes 4.1.0

---

src/module/item/spellcasting-entry/collection.ts
src/module/item/spellcasting-entry/index.ts

I was going to put a deprecation warning, but there isn't much sense doing so before we're done refactoring collections. That said I don't think anyone uses SpellcastingEntryPF2e#highestLevel

Fix detection of highest level for spell collection

---

CHANGELOG.md
package-lock.json
package.json
system.json

* (stwlam) Fix extraction of predicated damage dice
* (stwlam) Fix localization of non-land speeds
* (Supe) Fix detection of highest level for spell collection
* (stwlam) Restore iconics' prototype tokens
* (stwlam) Fix language known by Uthuls (bestiary 1)

Release notes 4.1.1

---

src/module/actor/character/index.ts
src/module/actor/creature/data.ts
src/module/actor/creature/index.ts
src/module/actor/familiar/index.ts
src/module/actor/hazard/index.ts
src/module/actor/npc/index.ts
src/module/actor/vehicle/data.ts
src/module/actor/vehicle/index.ts
src/module/system/action-macros/types.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts

This makes it so that statistic.check and statistic.dc always returns a value. After this, we can no longer have dc only and check only statistics. 
Also renames compat data to trace data and changes slug/name to match changes to StatisticModifier.

Ensure statistic check/dc always exists + other misc changes

---

src/module/actor/character/index.ts
src/module/actor/npc/index.ts
src/module/actor/sheet/spellcasting-dialog.ts
src/module/item/spellcasting-entry/data/types.ts
src/module/item/spellcasting-entry/index.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts
static/lang/en.json
static/templates/actors/character/tabs/spellcasting.html
static/templates/actors/spellcasting-dialog.html

Requires #4019. It also changes class dc to use statistic (all the inline rolls continue to work, as do automatic prof bumps). Modifiers are also automatically retrieved from the synthetics rather than injected.
This changes spellcasting to stem from a base tradition proficiency. This base tradition proficiency could also be extended with alternative domains to create a counteract statistic in the future (that would not gain a +1 from inspire courage). 
The extend's function signature is *gnarly*. Typescript doesn't seem capable of understanding that StatisticCheckData is an object for the purposes of DeepPartial. Perhaps a typescript update would allow a simpler type. Or maybe you have another idea.

Support class dc for spellcasting features

---

src/scripts/register-module-art.ts

The use case for how pdf to foundry means that the art mapping is dynamic based on which modules have been imported, so it should live in a place that can't be populated by the installer before. Because of this, an error is displayed when the pdf to foundry module is enabled and its art mapping file hasn't been created yet

Prevent 404 error from displaying an error when fetching art mappings.

---

src/module/apps/compendium-browser/index.ts
static/lang/en.json

Closes #4123 (Maybe there will be an upstream fix)

Add warning message to `PackLoader` if a pack couldn't be loaded

---

src/module/item/feat/sheet.ts
src/module/item/sheet/base.ts

I've removed two listeners that were targeting the lore sheet and should no longer be needed.
I've also removed a listener from the rules editing block that was targeting a `textarea` in the `ProseMirror` editor that doesn't exists as far as I can tell.
Additionally I've moved one listeners to the feat sheet that was only used on that sheet.

Remove JQuery from base item sheet

---

src/module/chat-message/document.ts

Fixes message.item for newly spun on chat messages such as certain modules.

Pull strike index from StrikeAttackRoll instead of DOM

---

src/styles/_tags.scss
src/styles/settings/_homebrew.scss

Closes #2950
If a tag is longer than the width allows, currently the text overflows on the bottom but the border doesn't expand with it. This change makes the border expand so it looks right, only if the text requires it.

Fix overflow for long tag elements

---

packs/data/spell-effects.db/spell-effect-amplifying-touch.json
packs/data/spell-effects.db/spell-effect-armor-of-bones.json
packs/data/spell-effects.db/spell-effect-bane.json
packs/data/spell-effects.db/spell-effect-bathe-in-blood.json
packs/data/spell-effects.db/spell-effect-bless.json
packs/data/spell-effects.db/spell-effect-blood-ward.json
packs/data/spell-effects.db/spell-effect-blunt-the-final-blade-critical-success.json
packs/data/spell-effects.db/spell-effect-bullhorn.json
packs/data/spell-effects.db/spell-effect-call-to-arms.json
packs/data/spell-effects.db/spell-effect-calm-emotions.json
packs/data/spell-effects.db/spell-effect-celestial-brand.json
packs/data/spell-effects.db/spell-effect-corrosive-body-heightened-9th.json
packs/data/spell-effects.db/spell-effect-corrosive-body.json
packs/data/spell-effects.db/spell-effect-heroism.json
packs/data/spell-effects.db/spell-effect-inspire-courage.json

Remove unneeded labels and condense flat modifiers when possible to use multiple selectors.

Brushup spell effect REs A-C

---

src/module/item/effect/document.ts
src/module/rules/rule-element/base.ts

Also avoid ignoring REs for temporarily-constructed effects

Move handling of RE-ignoring due to expiration to `EffectPF2e`

---

src/styles/packs/_tab.scss

Fix rarity tag height in the Compendium Browser

---

packs/data/pathfinder-bestiary-3.db/sturzstromer.json

Fix a typo 240 feet instead of 24 feet

Fix the range of sturzstromer tremorsense ability

---

src/module/canvas/layer/template.ts

Changes:
- Added logic to check if the current scene hasHexGrid and to snap the template to every 30 degrees instead of every 45 in the case that it does. This should complement pr #4143 which addressed issue #4126 .

Add logic to snap templates to 30 degree instead of 45 on a hex grid when initially placing a template.

---

packs/data/classfeatures.db/advanced-alchemy.json
packs/data/classfeatures.db/field-discovery-bomber.json
packs/data/classfeatures.db/field-discovery-chirurgeon.json
packs/data/classfeatures.db/field-discovery-mutagenist.json
packs/data/classfeatures.db/field-discovery-toxicologist.json
packs/data/feats.db/deeper-dabbler.json
packs/data/feats.db/efficient-alchemy-paragon.json
packs/data/feats.db/elaborate-talisman-esoterica.json
packs/data/feats.db/expert-alchemy.json
packs/data/feats.db/expert-fireworks-crafter.json
packs/data/feats.db/expert-herbalism.json
packs/data/feats.db/expert-poisoner.json
packs/data/feats.db/gadget-specialist.json
packs/data/feats.db/master-alchemy.json
packs/data/feats.db/munitions-machinist.json
packs/data/feats.db/plentiful-snares.json
packs/data/feats.db/snare-genius.json
packs/data/feats.db/snare-specialist.json
packs/data/feats.db/snarecrafter-dedication.json
packs/data/feats.db/talisman-dabbler-dedication.json
packs/data/feats.db/talisman-esoterica.json
packs/data/feats.db/ubiquitous-gadgets.json
packs/data/feats.db/ubiquitous-snares.json
packs/data/iconics.db/fumbus-level-1.json
packs/data/iconics.db/fumbus-level-3.json
packs/data/iconics.db/fumbus-level-5.json
src/module/migration/migrations/774-unpersist-crafting-entries.ts
src/module/rules/rule-element/crafting/entry.ts

Closes #4189 
The AE-likes never needed to be set in the "afterDerived" phase, but it won't hurt anything that ones out in the wild do.

Fix AE-likes modifying crafting entries

---

package-lock.json
package.json
src/module/encounter/combatant.ts
src/module/item/effect/document.ts

Includes two fixes to make the update possible.
Both `this.parent` in `CombatantPF2e#hasHigherInitiative` and `badge` in `EffectPF2e#_preUpdate` were resolving to `never` after the checks.

Update TypeScript to 4.8

---

.betterer.results
src/module/actor/character/data/sheet.ts
src/module/actor/character/data/types.ts
src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/vehicle/data.ts
src/module/actor/vehicle/sheet.ts
src/module/item/consumable/data.ts

I have no idea why `ConsumableSystemData` was extending `ActivatedEffectData`. The new type for `uses.per` might be incorrect but it looks like it isn't used anywhere. Also, the only references to `ConsumablePF2e#system.uses` I could find where `uses.value` and `uses.max`. Removing the unused properties could eliminate a lot of lines from the pack data.
The one remaining `any` type is a `[key: string]: any` in `StatisticModifier`. Removing that blows up a lot of stuff and I'm not sure what the best way to fix it would be.

Fix remaining betterer warnings outside type definitions except one

---

.betterer.results
src/module/actor/character/data/sheet.ts
src/module/actor/character/data/types.ts
src/module/actor/character/index.ts
src/module/actor/creature/data.ts
src/module/actor/creature/index.ts
src/module/actor/creature/sheet.ts
src/module/actor/creature/types.ts
src/module/actor/familiar/data.ts
src/module/actor/familiar/index.ts
src/module/actor/hazard/index.ts
src/module/actor/modifiers.ts
src/module/actor/npc/data.ts
src/module/actor/npc/index.ts
src/module/actor/npc/sheet.ts
src/module/actor/npc/types.ts
src/module/system/action-macros/helpers.ts

The removed `varaints` are `Lore` variants that are not used anywhere else in the code as far is I can tell. Also the `New Skill Variant` button on the lore item sheet is non-functional.

Remove last explicit any type

---

static/templates/actors/partials/item-line.html

Don't show uses for single-use items in sheet inventories

---

src/module/chat-message/document.ts

Once upstream uses it themselves next release, we'll benefit from it immediately.

Utilize `ChatMessage#getRollData`

---

src/module/actor/character/index.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts

Alternatively we can migrate all class dcs to point to .dc instead of .value, or to point to `@actor.classDCs.dc.value`.

Fix inline rolls for class dcs

---

src/module/system/check-modifiers-dialog.ts
static/templates/chat/check-modifiers-dialog.html

Clicking add when the value box is empty now adds a +1 modifier. I get caught by this every so often, so I suspect its a semi-common issue no one raises an issue about because they go "oh" at the prompt.

Set default for custom check modifiers equal to the placeholder (+1)

---

packs/data/classfeatures.db/arcane-cascade.json
packs/data/feats.db/student-of-the-staff.json

This fixes some oversights in my initial implementation of Student of the Staff automation, avoiding console errors when not in arcane cascade and correctly scaling up the extra critical damage dice with the weapon striking runes as the deadly trait is meant to do.

Student of the staff deadly scaling

---

src/module/actor/character/index.ts
src/module/actor/sheet/spellcasting-dialog.ts
static/templates/actors/spellcasting-dialog.html

This hides the ability selection as well when the proficiency is set to anything other than class tradition. Base tradition statistics do not have set abilities, and thus its safe to prioritize the base statistic's ability over the entry's.

Set correct ability when class dcs are picked

---

src/module/scene/token-document/document.ts

Core looks for an active effect rather than the overlay, so we need to do something different

Make check for death overlay in `TokenDocumentPF2e#hasStatusEffect`

---

src/module/actor/base.ts
types/foundry/client/documents/actor.d.ts
types/foundry/common/documents/actor.d.ts

This is to help move closer to V10 types by getting rid of some types pulled from `this["data"]`

Use merge declarations for actor embedded document types

---

src/module/actor/character/index.ts
src/module/actor/creature/index.ts
src/module/actor/modifiers.ts

This also addresses the bonuses being affected by the configurable variant values when the variant is disabled

Fix PWoL variant not honoring untrained proficiency penalties

---

src/module/notes.ts
src/module/system/rolls.ts

I'm pretty tempted on eventually refactoring the note string filter but not today.
Marked as a bugfix since this was a loss of functionality in an unfortunately public facing thing with no substitute.

Restore raw note functionality to CheckPF2e

---

src/styles/ui/sidebar/chat/_damage.scss
static/templates/chat/damage/buttons.html

The styling is much less finicky now.
Before:
After:

Use fa-stack for heal button, enlarge labels slightly

---

src/module/canvas/status-effects.ts

Before and after between different loads

Fix start of turn status message

---

src/styles/ui/_combat.scss

The h3 styling has not worked for v10, and even if changed the styling change is almost unnoticeable (the font size for the round is the same, the only change is the font weight, and only marginally). So I just removed it since it no longer really served a purpose.

Fix display of drag gap and mystified name (gm view) in encounter view popouts

---

static/templates/actors/loot/sidebar.html

Before and after image:
Fixes #3229

Show players the total bulk for Loot actors they own.

---

src/styles/item/_rules.scss

I suspect it was broken for non-embedded items, but I can't be sure.

Fix styling of flat modifier form in certain cases

---

src/module/rules/rule-element/damage-dice.ts

The recent fix (#4350) removed the part of the damage dice validation that looked for the existence of the `damageType` or `dieSize` fields in the DamageDice `override` field. As a result, any override with _only_ these fields would be classed as invalid.
I've re-added these fields to the validation, merely testing that they are strings. The validity of the string is checked later, after resolving properties.

Fix damage dice validation for damageType and dieSize overrides

---

packs/data/iconics.db/droogami-level-1.json
packs/data/iconics.db/droogami-level-5.json
packs/data/iconics.db/feiya-level-5.json
packs/data/iconics.db/harsk-level-5.json
packs/data/iconics.db/jirelle-level-5.json
packs/data/iconics.db/korakai-level-1.json
packs/data/iconics.db/korakai-level-5.json
packs/data/iconics.db/lem-level-5.json
packs/data/iconics.db/lini-level-1.json
packs/data/iconics.db/lini-level-5.json
packs/data/iconics.db/quinn-level-1.json
packs/data/iconics.db/quinn-level-5.json
packs/data/iconics.db/sajan-level-1.json
packs/data/iconics.db/sajan-level-5.json
packs/data/iconics.db/seoni-level-1.json
packs/data/iconics.db/seoni-level-5.json

- Feiya5 missing expert skills
- Harsk5 had lvl4 class feat in lvl2 slot
- Jirelle5 had lvl4 class feat in lvl2 slot
- Korakai pronouns s/b "M/He/Him"
- Lem5 missing expert skills
- Lini5 had lvl4 class feat in lvl2 slot
- Lini/Droogami pronouns s/b "F/She/Her"
- Sajan pronouns s/b "M/He/Him"
- Sajan5 had lvl4 class feat in lvl2 slot
- Sajan5 Powerful Leap cannot be taken until level 4. Swapped with Quick Jump
- Quinn pronouns s/b "M/He/Him"
- Quinn's Magnifying Glass replaced from compendia (previously showed as lvl 0)
- Seoni pronouns s/b "F/She/Her"
- Seoni had lvl4 class feat in lvl2 slot

Minor corrections of Iconic sheets

---

src/module/canvas/perception/modes.ts
types/foundry/client/documents/mixins/canvas-document-mixin.d.ts
types/foundry/client/pixi/layers/effects/visibility.d.ts

Closes #4359.
This leaves such placeables still visible to GMs but cuts out the unnecessary performance cost of full detection testing against them.

Return false early when testing detection of GM-hidden placeable objects

---

src/module/item/abc/manager.ts
static/lang/en.json
static/templates/items/class-details.html

Conversion to uuid has made the split between compendium/non-compendium no longer necessary. I guess we can see later if the extra migration becomes a problem for world items.
Fixes #4361

Fix double-granting world items from ABC items

---

src/module/macro.ts

Workaround for https://github.com/foundryvtt/foundryvtt-premium-content/issues/120 until upstream issue is addressed

Allow parameters to be shadowed in script macros' eval scopes

---

src/module/system/damage/roll-dialog.ts
src/module/system/damage/types.ts
static/templates/chat/damage/damage-card-content.html

This utilizes the previously unused `damage-card-content.html` template to render the damage roll conent instead of building it with string concatenations.
As a bonus `damageType` and `damageCategory` are now localized strings instead of a capitalized slug,
Before:
After:

Refactor damage roll chat message content rendering

---

src/module/item/physical/sheet.ts
static/templates/items/activation-panel.html

The description editor is currently unsued but it was generated a deprecation warning.

Remove deprecated use of `content` parameter in item activation panel editor

---

src/styles/ui/sidebar/chat/_damage.scss
static/templates/chat/damage/buttons.html

Fix style of damage cards with triple-damage buttons

---

src/module/actor/modifiers.ts
src/module/system/statistic/index.ts

This fixes modifier adjustments for sub-domain adjustments on parent domains is still broken (such as spell-attack adjustment on an all modifier)

Fix modifier adjustments for top level selectors

---

packs/data/iconics.db/korakai-level-1.json
packs/data/iconics.db/korakai-level-5.json
packs/data/iconics.db/kyra-level-1.json
packs/data/iconics.db/kyra-level-3.json
packs/data/iconics.db/kyra-level-5.json
packs/data/iconics.db/lini-level-1.json
packs/data/iconics.db/lini-level-5.json
packs/data/iconics.db/merisiel-level-1.json
packs/data/iconics.db/merisiel-level-3.json
packs/data/iconics.db/merisiel-level-5.json
packs/data/iconics.db/valeros-level-1.json
packs/data/iconics.db/valeros-level-3.json
packs/data/iconics.db/valeros-level-5.json
packs/data/paizo-pregens.db/bottlespeaker.json
packs/data/paizo-pregens.db/eteleon.json
packs/data/paizo-pregens.db/grimmnir.json
packs/data/paizo-pregens.db/izni.json
packs/data/paizo-pregens.db/kellsti.json
packs/data/paizo-pregens.db/kyra-beginner-box.json
packs/data/paizo-pregens.db/lavanna-saltspray.json
packs/data/paizo-pregens.db/melvok.json
packs/data/paizo-pregens.db/savshin-starwatcher.json
packs/data/paizo-pregens.db/ufi.json

Heal/harm have new fancy versions. This puts fancy on iconics/pregens.  Also some misc errors found. 
- Update Heal on Lini, Korakai, Kyra, Bottlespeaker,  Eteleon, Izni, Kellsti, Lavanna, Melvok, Savshin Starwatcher, Ufi
- Update Harm on Korakai, Eteleon, Grimmnir
- Replace Wand of Heal on Lavanna
- Update Lavana's divine font to 3 castings
- Valeros pronouns s/b "M/He/Him"
- Merisiel pronouns s/b "F/She/Her"

Updated Iconics/Pregens to use action-based Heal/Harm spell

---

src/module/macro.ts

Supersedes #4422, which for some reason can't be merged.

Accommodate macros ending with single-line comments

---

src/module/canvas/measured-template.ts
types/foundry/client/pixi/placeable-object/measured-template.d.ts

Closes #4443
Since we completely replace the parent method for circles and cones, this check needs to be pulled over.

Refrain from highlighting measured templates invisible to players

---

src/module/item/spell/document.ts
src/module/item/spellcasting-entry/data/types.ts
src/module/item/spellcasting-entry/index.ts
src/module/item/spellcasting-entry/trick.ts

Since I couldn't figure out a clean way to get private casting going (why would you blind roll a spell instead of private roll? Blind roll is the global ctrl roll mode) this can wait till next release. Trick Magic Item heightening still works.

Add roll mode param to cast() function

---

src/styles/actor/_inventory.scss
src/styles/actor/_spell-list.scss
src/styles/actor/character/_actions.scss
src/styles/actor/character/_crafting.scss
src/styles/actor/character/_effects.scss
src/styles/actor/character/_feats.scss
src/styles/mixins/_frames.scss

Before: (Notice the black border touching the frame and the inner one containing the image)
After:
The rounding of the corners is just a minor aesthetic thing; I just thought it looked nicer but I'm not married to the idea

Remove double borders from frames and round corners

---

src/module/item/sheet/base.ts

The close button is disabled for the rules editing element when looking at something from compendium, creating a scenario in which the user cannot navigate backwards.
This is done on foundry's side, so this PR attempts to remedy that by explicitly removing the disabled attribute from the close button.

Fix close button for rules editing

---

src/module/item/spell/document.ts

This was probably a v10 change but I don't have v9 installed anymore so I can't verify. The fix duplicates line `36407` in `foundry.js`.
Closes #4554

Fix `Spell#createTemplate` default width

---

src/module/canvas/ghost-measured-template.ts

The console was complaining about a non-passive listener on a wheel event.

Change the mouse wheel listener in `GhostTemplate` into a passive listener

---

src/module/actor/character/index.ts

Prepare skills after perception but before AC, allowing the use of skills for AC computations (which some feats might need to use).

Prepare character skill data sooner

---

packs/data/agents-of-edgewatch-bestiary.db/almiraj.json
packs/data/agents-of-edgewatch-bestiary.db/binumir.json
packs/data/agents-of-edgewatch-bestiary.db/boiling-fountains.json
packs/data/agents-of-edgewatch-bestiary.db/gref.json
packs/data/agents-of-edgewatch-bestiary.db/kekker.json
packs/data/agents-of-edgewatch-bestiary.db/kemeneles.json
packs/data/agents-of-edgewatch-bestiary.db/shredskin.json
packs/data/agents-of-edgewatch-bestiary.db/siege-shard.json

corrected formatting on Almiraj horn
added hardness to Boiling Fountains
Fixed reference to different creature in Kekker and Gref
Corrected Kemeneles AC with Mage Armor spell effect in consideration
Added number of actions for Control Body to Shredskin, added link to Escape in Enshroud ability
Added missing traits on Agonizing Wail for Binumir
added link to Prove Peace activity in Siege Shard's Exorcism ability

Brushup Agents of Edgewatch Book 1

---

src/module/canvas/ghost-measured-template.ts

Passive listeners can't call `preventDefault` so that has to be reverted. Explicitly setting `passive: false` still prevents the console warning. 
Note to self: Test listener changes in different browsers. 🙃 
Closes #4591

Fix measured template rotation triggering the browser zoom in Firefox and Edge

---

packs/data/pathfinder-bestiary-2.db/peryton.json

Closes [#4606](https://github.com/foundryvtt/pf2e/issues/4606)

Fix Peryton Heart Ripper ability

---

src/module/actor/character/helpers.ts

A crowbar is required only when forcing open something via prying.

Default no-crowbar penalty to disabled

---

src/module/canvas/ghost-measured-template.ts

Adjust ghost-measured-template placed from chat to behave more like placed templates with regards to rotation. Added additional logic for hex grids. This should complement pr #4143 and pr #4173 which addressed issue #4126 .
- Set ctrl to rotate by 5deg (this did not change)
- Set ctrl+shift to rotate by 15deg (this used to be 15deg for square or grid-less and 30deg otherwise)
- Set shift to rotate by 60deg on hex and 45deg on anything else (this used to just be 45deg which was quite useless on hex)
- Compensate for hex row format by offsetting the original angle by 30deg so 60deg aligns properly. (this could be omitted if the hex angle is set to 30deg but makes hex much more usable)
- Reduce recalculations. (set this.document.direction to value just calculated in …

Adjust ghost-measured-template rotation logic

---

src/module/chat-message/document.ts
src/module/item/spell/document.ts

Mostly applicable for modules but also followup work. Should probably be in the patch notes so that module authors know they can remove their weird workarounds now.

Heighten spells retrieved from chat messages

---

src/module/actor/base.ts
src/module/actor/creature/sheet.ts
src/module/apps/effects-panel.ts
src/module/item/abstract-effect/document.ts
src/module/item/condition/document.ts
src/module/item/effect/data.ts
src/module/item/effect/document.ts
src/module/system/conditions/manager.ts
src/module/system/conditions/types.ts
src/styles/mixins/_effects-list.scss
src/styles/system/_effects-panel.scss
static/lang/en.json
static/templates/actors/familiar-sheet.html
static/templates/actors/partials/conditions.html
static/templates/items/effect-sidebar.html
static/templates/system/effects-panel.html

https://user-images.githubusercontent.com/43446478/198745341-3c8c56de-92c4-4171-bce3-ff8ef09f15a7.mp4
This PR adds a feature that allows GM to apply effects to player characters, NPCs, and familiars, without revealing them to them.
- This is only for effects, but a way was paved for conditions if hiding conditions is ever desired.
- Effects are hidden from players on their characters' effects tabs, the effects panel on the top right, and the tokens on the scene.
- For the GM, effects that are hidden from players show up
- with a dotted outline and `--visibility-gm-bg` colour in the PC effects tab,
- with a `--visibility-gm-bg` drop shadow and a "SECRET" secondary tag on the effects panel,
- plainly on tokens on the scene.
- Effects can quickly be toggled on and off on the effects tabs of …

Allow effects to be hidden from players

---

src/module/apps/compendium-browser/tabs/feat.ts

Previously the prerequisite string was only checked for the translation key so it failed for translated prerequisites.
As longs as prerequisites stay strings this is the best we can do.
Closes #4671

Add support for translated skills in Compendium Browser feat tab skill filter

---

packs/data/bestiary-ability-glossary-srd.db/change-shape.json
packs/data/blood-lords-bestiary.db/yshula.json
packs/data/kingmaker-bestiary.db/gaetane.json
packs/data/kingmaker-bestiary.db/kundal.json
packs/data/kingmaker-bestiary.db/vilderavn-herald.json
packs/data/kingmaker-bestiary.db/virthad.json

Also gets rid of it on the change shape action, since we can't edit or see custom traits on actions now anyways.

Remove accidentally included custom trait on some NPCs

---

src/module/actor/hazard/data.ts
src/module/actor/hazard/sheet.ts

Fixes opening hazards. Eventually rather than "empty = don't show" we might want dedicated delete buttons for each text section, and filter on being null instead of empty string.

Make hazard text data optional

---

src/module/apps/ui/actor-directory.ts

`ActorDirectory_render` has a bug (or just limitation) where it only looks at top-level actor-update keys when deciding whether to re-render. We flattened the update diff, but top-level keys are still needed for upstream scanning through them (like anything in the `ownership` object).

Pass up flattened and unflattened data in `ActorDirectoryPF2e#_render`

---

src/styles/actor/_spell-list.scss

Bring it in line with the rest of the `<h4>`s on the different tabs of character sheet

Set Spell Name cursor type to pointer

---

src/module/actor/sheet/base.ts

If the GM holds the `alt` key while dragging an effect onto a token or an actor sheet, the effect will be forcibly set to `unidentified`.

Allow the use of 'alt' key to add an unidentified effect

---

src/global.d.ts
src/module/actor/base.ts
src/module/actor/character/sheet.ts
src/module/actor/creature/index.ts
src/module/apps/ui/encounter-tracker.ts
src/module/canvas/status-effects.ts
src/module/canvas/token/object.ts
src/module/item/condition/document.ts
src/module/migration/migrations/797-metagame-settings.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/scene/token-document/document.ts
src/module/system/action-macros/crafting/craft.ts
src/module/system/action-macros/helpers.ts
src/module/system/degree-of-success.ts
src/module/system/rolls.ts
src/module/system/settings/menu.ts
src/module/system/settings/metagame.ts
src/module/system/text-editor.ts
src/scripts/macros/treat-wounds.ts
src/scripts/ui/user-visibility.ts
static/lang/en.json
static/templates/chat/check/target-dc-result.html

Under the hood it still uses the old user visibility stuff, we can knock those out as they come up / cause problems.

Convert metagame visibility settings to booleans, change metagame prefix

---

src/module/actor/character/helpers.ts
src/module/actor/character/index.ts
src/module/item/armor/document.ts
src/module/item/armor/sheet.ts
src/module/item/armor/types.ts
src/module/item/physical/document.ts
src/module/item/weapon/document.ts
src/module/item/weapon/types.ts
src/module/system/tag-selector/index.ts
src/scripts/config/index.ts
src/scripts/config/traits.ts
src/styles/item/_index.scss
static/lang/en.json
static/templates/items/armor-details.html
static/templates/items/armor-sidebar.html
static/templates/items/weapon-sidebar.html

Closes #3793.
Penalties are currently only applied to armor and weapons: we'll need to figure out what besides those qualify for "checks involving a shoddy item take a –2 item penalty."

Implement "shoddy" tag for physical items

---

src/module/apps/ui/actor-directory.ts

I'm not really happy with creating a new handlebars helper that is only used for this but it I believe it is the best solution.
As the actor rendering is done inside `templates/sidebar/document-directory.html` with an array of full `Document` instances the alternative would have been to subclass `SidebarDirectory` and override `SidebarDirectory#getData` to generate new render data for each actor, including the user permission, and passing that to a modfied template.
Closes #4482

Fix actor sidebar showing the actor level to users that lack permission

---

src/module/system/rolls.ts

`CheckRoll` expects the `data` object as the second constructor parameter and `option`s  as the third.
What previously was passed in as `data` corresponds to the current `options`. I'm not sure when that was changed.
Closes #4751

Fix CheckPF2e rerolls being constructed from wrong data

---

packs/data/extinction-curse-bestiary.db/counteflora.json
packs/data/extinction-curse-bestiary.db/ginjana-mindkeeper.json
packs/data/extinction-curse-bestiary.db/headless-xulgath.json
static/lang/re-en.json

Brushup EC3 NPCs: Counteflora, Ginjana Mindkeeper, Headless Xulgath.
Adds JunglesOrFlowerFields skill variant entry into re-en.json for Counteflora.

Brushup EC Book 3 NPCs: Counteflora, Ginjana Mindkeeper, Headless Xulgath

---

packs/data/bestiary-effects.db/effect-cat-siths-mark.json
packs/data/bestiary-effects.db/effect-ill-omen.json
packs/data/extinction-curse-bestiary.db/cat-sith.json
packs/data/extinction-curse-bestiary.db/runkrunk.json
packs/data/extinction-curse-bestiary.db/xulgath-stoneliege.json
packs/data/extinction-curse-bestiary.db/yaganty.json

Brushup EC Book 3 NPCs: Yaganty, Xulgath Stoneliege, Runkrunk, and Cat Sith. Adds two effects for Cat Sith abilities.

Brushup EC Book 3 NPCs: Yaganty, Xulgath Stoneliege, Runkrunk, and Cat Sith

---

src/module/actor/sheet/base.ts

This will allow us to condense some effects as we can just use the badge number in the label similar to how conditions are handled.

Allow effect badge counters to be set on drag

---

src/module/scene/token-document/document.ts

This is a workaround for an actor-data preparation issue in which retrieving a synthetic actor before it's made will cause a stack overflow

Release token when setting actorLink to false

---

src/module/system/check-modifiers-dialog.ts
src/module/system/check/check.ts
src/module/system/rolls.ts

This should lead to actual secret trait feeling less buggy. Clicking a secret roll button will set the roll mode to blind in the dropdown of the dialog, rather than doing it as a surprise last minute.

Set secret trait roll mode before dialog and remove secret parameter

---

packs/data/feats.db/chronoskimmer-dedication.json
src/module/actor/creature/index.ts
static/lang/re-en.json

Resolves #4107
I'm not entirely sure whether I need to follow in the steps of the example for assurance where other modifiers need to be suppressed.
Adds roll options to improve automation. Does not automate the flat check.

Add automation to chronoskimmer

---

src/module/chat-message/data.ts
src/module/system/check/strike/attack-roll.ts

This was just a backward compatiblity attempt so that recent attack roll chat messages prior to updating would be considered damaging

Make `RollDataPF2e#damaging` required

---

packs/data/bestiary-effects.db/effect-deceitful-feast-failure.json
packs/data/extinction-curse-bestiary.db/brughadatch.json
packs/data/extinction-curse-bestiary.db/gahlepod.json
packs/data/extinction-curse-bestiary.db/starved-staff.json
packs/data/extinction-curse-bestiary.db/xulgath-herd-tender.json

Brushup for: Xulgath Herd-Tenders, Gahlepod, Starved Staff, Brughadatch
New effect: "Effect: Deceitful Feast (Failure)" for Brughadatch

Brushup EC Book 4 NPCs part 1

---

src/module/system/text-editor.ts

`showDC` is now equivalent to `showDC:all`.

Add support for non-valued showDC arguments in @Check

---

packs/data/crown-of-the-kobold-king-bestiary.db/tallow-guardian.json

`null` seemed wrong to me, and I checked [pf2e tools](https://pf2easy.com/index.php?id=22710) to confirm (this compendium isn’t on aonprd yet).

Fix cha modifier of tallow guardian

---

src/module/rules/rule-element/choice-set/rule-element.ts

Prevent double name adjustments from ChoiceSets when transfering items

---

packs/data/bestiary-effects.db/effect-bloodline-magic-stirvyn-banyan.json
packs/data/extinction-curse-bestiary.db/ledorick-banyan-possessed.json
packs/data/extinction-curse-bestiary.db/mukradi-summoning-runes.json
packs/data/extinction-curse-bestiary.db/poisoned-secret-door-trap.json
packs/data/extinction-curse-bestiary.db/stirvyn-banyan.json
packs/data/extinction-curse-bestiary.db/tashlock-banyan.json

Brushed up NPCs-- Poisoned Secret Door Trap, Ledorick Banyan, Stirvyn Banyan, Tashlock Banyan
Added variant-- Ledorick Banyan (Possessed)
Added effect-- Effect: Bloodline Magic (Stirvyn Banyan)

Brushup EC Book 4 NPCs part 4

---

packs/data/feats.db/skill-training.json

While the predicate of rank `0` will likely stop anything weird happening, this feels "more correct"

Set Skill Training AE-like to upgrade

---

packs/data/equipment.db/injection-spear.json
static/lang/en.json

I see no reason for the injection spear not to have its own base weapon type; it's a distinct weapon, rather than a modification of a spear.

Create new base weapon type for injection spear

---

packs/data/feats.db/hidden-thorn.json

Some flowers can hide their thorns, and yours happen to be hidden along your arms. You gain a thorns unarmed attack that deals 1d6 piercing damage. Your thorns are in the **knife** weapon group and have the finesse and unarmed traits.

fix hidden thorn weapon group

---

src/module/canvas/perception/hearing-source.ts
src/module/canvas/perception/modes.ts
src/module/canvas/token/object.ts

From profiling, this will cut the CPU load of hearing detection by 90%+.

Use PointSource instead of ad hoc wall collision testing for hearing

---

packs/data/classfeatures.db/lesson-of-bargains.json

Reuses icon for lesson of favours (same pact).
Closes #4974

Adds lesson of bargains major lesson for pact witch

---

src/module/actor/base.ts
src/module/actor/character/index.ts
src/module/actor/creature/index.ts
src/module/actor/creature/types.ts
src/module/actor/data/base.ts
src/module/actor/helpers.ts
src/module/actor/npc/index.ts
src/module/actor/types.ts
src/module/system/check/check.ts
src/module/system/check/types.ts
src/module/system/damage/helpers.ts
src/module/system/damage/weapon.ts
src/module/system/rolls.ts

preparation for giving hazards proper strikes

Move strike-roll context methods from `CreaturePF2e` to `ActorPF2e`

---

packs/data/paizo-pregens.db/grimmnir.json
packs/data/paizo-pregens.db/izni.json
packs/data/paizo-pregens.db/rhin.json
packs/data/pathfinder-bestiary-2.db/planetar.json
static/template.json

Closes [#4691](https://github.com/foundryvtt/pf2e/issues/4691)
Migration728FlattenPhysicalProperties indicates that flattened is correct.

Fix uses of “collapsed” to be boolean

---

packs/data/feats.db/battle-cry.json

Refine the attack note of Battle Cry to display only when all criteria are met instead of on all attacks.
I'm using this tiny change to dip my toe into the Contribution waters.

Refine the attack note of Battle Cry 

---

packs/scripts/extract.ts
src/module/actor/creature/index.ts
src/module/actor/npc/data.ts
src/module/migration/runner/index.ts
static/template.json

This will speed up migrations on newer worlds, at least.

Skip migration of synthetic actors lacking migratable actor data

---

src/module/rules/rule-element/roll-twice.ts

This allows for inline properties such as `{item|flags.pf2e.rulesSelections.skill}` to return as a valid selector and function properly with RollTwice

Allow for injected selectors in RollTwice

---

src/module/actor/base.ts
src/module/actor/character/index.ts
src/module/actor/helpers.ts

One is protected and unused, and the other has been deprecated with a promise of impending removal.

Remove `getDamageRollContext` and `rollSaves` methods from `ActorPF2e`

---

src/module/actor/character/crafting/helpers.ts
src/module/actor/sheet/item-summary-renderer.ts
src/module/item/base.ts
src/module/item/sheet/base.ts
src/module/item/spell/document.ts
src/module/system/damage/roll-dialog.ts
src/scripts/macros/hotbar.ts

While working on a module, i realized that there were some inconsistent calls to the `TextEditor.enrichHTML`, in 7 occurences, the call was made using `game.pf2e.TextEditor.enrichHTML` instead, making wrapping around `TextEditor.enrichHTML` not working in all those cases.
I took the liberty to just change those hopping it is fine.

Make sure only TextEditor.enrichHTML calls are being made

---

src/module/actor/base.ts
src/module/actor/character/sheet.ts
src/module/actor/helpers.ts
src/module/actor/vehicle/sheet.ts
src/module/item/data/base.ts
src/util/misc.ts

The helpers are not exposed, so if someone wants to be able to get icons from action costs, they should probably let us know before is too late.

Deprecate ActorPF2e#getActionGraphics()

---

src/module/apps/ui/actor-directory.ts

Folders were being selected in the query selection that checks for permissions to see the level. In such cases, the first valid descendant would have its level removed, leading to the first, or multiple in case of nesting, actors to have their level always hidden if they were in a folder. By only checking for actors, folders are excluded and levels should show correctly.
Before:
After:
Players still only see their owned actors' levels:

Fix level not showing on first actor(s) in folders

---

src/styles/_globals.scss
src/styles/mixins/_animations.scss

Current (top button is hovered):
In AV premium module:
New:
on hovering the top icon:
In AV premium module:

Update style of inlines with repost buttons

---

src/module/chat-message/data.ts
src/module/chat-message/document.ts
src/module/chat-message/helpers.ts
src/module/chat-message/listeners/cards.ts
src/module/item/spell/document.ts
src/module/system/check/check.ts
src/module/system/statistic/index.ts

The sooner we can get off of SpellPF2e#toMessage() the better.

Add roll inspector support for casted spells

---

packs/data/other-effects.db/effect-cover.json
static/lang/re-en.json

Prone with prone-cover vs melee attack:
Prone with prone-cover vs ranged attack:

Add special prone-condition option to Cover effect

---

src/module/actor/character/automatic-bonus-progression.ts
src/module/rules/rule-element/battle-form/rule-element.ts

Relic of original implementation when suppressing potency bonuses was a game of whack-a-mole. Also does some unification of relevant domains.

Remove disabling of ABP in BattleForm RE

---

static/template.json

These inform the server which fields have HTML in them and should be sanitized against security vulnerabilities. Coverage won't be perfect (we can't include arrays or objects with randomly-generated keys), but it's better than nothing.

Add `htmlFields` arrays to template.json

---

src/module/rules/rule-element/fast-healing.ts
src/module/system/damage/damage.ts
src/scripts/macros/encouraging-words.ts
src/scripts/macros/treat-wounds.ts
types/foundry/client/documents/chat-message.d.ts
types/foundry/common/data/data/chat-message-data.d.ts

Foundry documents it as deprecated and shims it but for some reason doesn't throw a deprecation warning.

Remove use of deprecated `roll` property in `ChatMessage` create data

---

src/module/actor/creature/sheet.ts
static/templates/actors/npc/partials/header.html

This extends data-property, our own workaround to the foundry submit pipeline, to selects of any data type. Inputs are pretty much numerical only though.
I think perhaps in a previous version the type used to become number when entering data, but that's probably been lost for a while. We can probably re-instate that if it contains the "modifier" class or based on data-dtype.
Fixes #4955

Fix RE prepared data sticking around for certain NPC header properties

---

src/module/system/damage/values.ts
src/styles/ui/sidebar/chat/_damage.scss

Tweak colors/icons of some damage types

---

src/scripts/hooks/canvas-ready.ts

When redrawing tokens during a scene, animated tokens (and perhaps other tokens with art that loads slowly?) would sometimes have `visible` set to `false` incorrectly. The `isVisible` getter seems to always behave correctly though, so this simple one-line change fixes this issue.
Tokens that have been hidden by the GM or are out of sight due to walls/darkness still seem to work properly with this PR, but this may have other implications I'm not aware of, and I'm happy to change this PR if necessary.
Closes #5283

Fix tokens with animated art disappearing on reload/scene switch

---

src/module/item/sheet/rule-elements/index.ts
src/module/rules/rule-element/grant-item/index.ts
src/module/rules/rule-element/grant-item/rule-element.ts

- Force `replaceSelf` and `allowDuplicate` to be false
- Fail validation if no predicate is included

Add safeguards to `GrantItemRuleElement#reevaluateOnUpdate`

---

src/module/rules/rule-element/grant-item/helpers.ts

Instead of processing the granter's grant data and then the grantee's own grant data, it now handles "restrict", "cascade", and finally "detach", with each looking at granter and then grantee.

Reorganize grant-deletion processing

---

src/module/actor/loot/data.ts
src/module/actor/loot/sheet.ts
src/module/migration/migrations/810-loot-description-value.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
static/template.json
static/templates/actors/loot/sidebar.html

This fixes the HTML sanitation error and allows loot actors to be created again.

Remove `value` property from loot actor description

---

src/module/actor/character/sheet.ts

`CharacterSheetPF2e##onChangeAdjustStat` makes an update in addition to the normal form submission workflow, causing unexpected issues in pre-update handling

Prevent double updates when changing skill proficiencies

---

src/module/actor/base.ts
src/module/rules/helpers.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/grant-item/rule-element.ts
types/foundry/common/abstract/document.d.ts

Also creates/deletes all at once instead of for each reevaluated grant

Move calling of RE `preUpdateActor` to `ActorPF2e.updateDocuments`

---

src/module/chat-message/chat-roll-details.ts
src/module/chat-message/data.ts
src/module/item/spell/document.ts
src/module/system/damage/damage.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts
src/styles/ui/sidebar/chat/_chat-roll-details.scss
src/util/misc.ts
static/templates/chat/chat-roll-details.hbs
tests/module/utils.test.ts

Note that currently we don't have a way to tell which modifiers were used in which outcomes, since damage templates do every category at once. That said, with the critical property being shown, I think people can still deduce it anyways.

Include damage modifiers and dice in roll inspector

---

src/module/system/text-editor.ts
src/scripts/hooks/drop-canvas-data.ts
src/scripts/system/dragstart-handler.ts

I am blanking on visual changes to make it obvious its drag/droppable though. 
We will also need a migration for persistent damage inline rolls (the previous migration kinda skipped it, some still have the {1}[persistent,acid] syntax). The migration will also need to remove all embedded persistent damage conditions following an inline roll (which was never necessary in the module do not put that evil on me!)

Create persistent damage conditions from drag drop inline rolls

---

src/module/item/condition/document.ts
src/module/system/damage/roll.ts

This will instruct persistent-damage instances to evaluate themselves

Add `evaluatePersistent` option to `DamageRoll`

---

src/module/system/damage/roll.ts

A damage instance's "domain" to compare against IWR predicates

Add a getter for a damage instance's "formal description"

---

src/module/actor/base.ts
src/module/item/condition/data.ts
src/module/item/condition/document.ts

Now that its kinda done, in hindsight it might have been possible to make slug the adjusted one, and then introduce a "base slug" (or pull slug from source data). For example, persistent-damage-fire has a base/source slug of persistent-damage. But it might require tweaks and some startsWith() shenanigans, so I'd prefer to try that refactor post launch. It should have no effect for the api unless someone is fetching condition.key directly, and this update should prevent any modules (*cough cough mine*) from having to do that.

Enable condition retrieval/recovery via persistent-damage-x string

---

src/module/item/condition/document.ts
src/module/system/damage/values.ts

Add temporary mapping for persistent damage icons for each type

---

src/module/actor/sheet/base.ts

This doesn't fix what happens when you click on them, but I didn't break that :P

Fix dragging persistent inline rolls from actor item summaries

---

src/module/item/spell/document.ts
src/scripts/dice.ts

Fixes spell breakdowns and negative ability modifiers. Removes the "energy" from the below:

Remove superfluous main category and fix negative spell modifiers

---

src/scripts/dice.ts

Foundry parser does interesting things with negative formulas.
That said, why would you ever cast this daze?

Fix first level daze with negative modifier

---

src/module/system/check-modifiers-dialog.ts

This also fixes tooltipster being initiaized on every render and the corresponding console warning.
I've tested all listeners and they work the same as before.

Remove most JQuery from check roll dialog listeners

---

roll-grammar.peggy
src/module/system/damage/helpers.ts
src/module/system/damage/roll.ts
src/module/system/damage/terms.ts
src/scripts/hooks/load.ts
types/foundry/client/roll-term/dice-term/die.d.ts
types/foundry/client/roll-term/math-term.d.ts
types/foundry/client/roll-term/numeric-term.d.ts

This will take care of inline rolls with math terms.
Before:
After:

Add `IntermediateDie` term class to handle non-numeric numbers/faces

---

src/module/item/condition/document.ts

Not sure if actually regresion or new bug. Depends on when you fixed the Persistent Damage (1d6 persistent fire) thing.

Fix chat message regression for inflicted persistent damage

---

packs/data/feat-effects.db/effect-ancestor-curse.json

I'm running an Ancestors oracle and ran into some challenges with the curse's effects not applying properly. Here's as many of the fixes as I could figure out how to implement.
* "flag" needed to be changed to "rollOption" in order for any of the other rule elements to actually apply.
* Added failure notes for Perception checks when not on the Skillful ancestor.
* Don't apply Battle ancestor's attack bonus to spell attacks (it should only be for Strikes)
* No longer limit the bonus from the Spellcasting ancestor to damaging effects (because it's also supposed to apply to healing).
The only elements of the curse that still aren't handled properly after these changes is that the damage bonus from the Spellcasting ancestor should apply to any non-cantrip spells, not just those cast from …

Fixes for ancestors oracle curse effects not applying correctly

---

packs/data/feat-effects.db/effect-ancestor-curse.json

Fixes the major remaining issue with the Ancestors oracle curse; the Spellcasting ancestor's damage increase should apply to all non-cantrip spells, not just those cast from spell slots. Previously, things like focus spells and innate spells were being excluded; this PR should fix that.

Apply ancestors oracle spell damage bonus to correct spells

---

src/module/item/spell/document.ts

Spells with materials continue to work. The nested instance has splash, but not the top-level one.

Do not include splash in main damage instance flavor for spells

---

src/module/system/damage/formula.ts

Feel free to alter the PR title to be more appropriate. I couldn't come up with a more descriptive one.

Fix handling of splash damage in sumExpression function

---

packs/data/monsters-of-myth-bestiary.db/ainamuuren.json
packs/data/pathfinder-bestiary-2.db/woolly-rhinoceros.json

Small fix to the spelling of the Woolly Rhinocerous sheet and token. Also corrects the spelling in one NPCs spellcasting entry.

Correct spelling of Woolly Rhinoceros

---

src/module/actor/base.ts

This wasn't firing off a deprecation warning until 10.291.

Update Actor construction with module art scale properties V10 standard

---

packs/data/ancestryfeatures.db/claws.json

Adding the slug in English will allow this added strike to be target by other feats. At the moment, as the label of the claw is localized, a feat like [Razor claws](https://github.com/foundryvtt/pf2e/blob/master/packs/data/feats.db/razor-claws.json) doesn't work if localized. Forcing the english slug fixes the problem.

Update claws.json to make it translation friendly

---

src/module/actor/character/data/types.ts
src/module/actor/sheet/popups/ability-builder.ts
src/module/item/ancestry/data.ts
src/module/item/ancestry/document.ts
src/styles/actor/character/_ability-builder.scss
static/templates/actors/character/ability-builder.hbs

BONUS: Ancestries without locked flaws have better alignment too.
Getting new flaw structure in eventually might be needed, though we'll need to reconcile it with the existing one somehow. In my opinion, its a separate thing to handle entirely from this PR.
https://user-images.githubusercontent.com/1286721/210765134-46ac6539-0c3b-4ed2-b465-c19454bdee39.mp4

Add support for alternate ancestry boosts

---

src/module/item/weapon/document.ts

Striking Rune: "A striking rune [...], increasing the weapon damage dice it deals to two instead of one"
Devastating Attacks: "At 4th level, your weapon and unarmed Strikes deal two damage dice instead of one."

Only increase weapon dice number from striking/ABP if originally 1

---

src/module/actor/character/document.ts
src/module/actor/creature/document.ts

This is a massive performance improvement for a workbench feature that I actually made worse with a PR by removing support for deprecated skills (as in, 800ms improvement....), but I suspect it'll lead to marginal ones for anything referencing @actor.skills.
We can completely get rid of this silly cache solution once its fully converted to statistic. The final holdout is initiative and encounter stuff....

Cache result of character/creature skills

---

packs/data/spell-effects.db/spell-effect-clawsong-deadly-d8.json

At the moment the rule element for the Deadly part adds a D8 dice all the time to the damage roll, instead of just adjusting the strike to give it Deadly (D8). This will fix it.
Before: 
After:

Fix deadly variant of Clawsong spell effect

---

packs/data/spell-effects.db/spell-effect-clawsong-versatile-piercing.json

Fix Clawsong versatile-piercing rule element.
Before:
After:

Fix Clawsong versatile spell effect

---

packs/data/abomination-vaults-bestiary.db/azvalvigander.json
packs/data/abomination-vaults-bestiary.db/beluthus.json
packs/data/abomination-vaults-bestiary.db/blood-of-belcorra.json
packs/data/abomination-vaults-bestiary.db/bone-gladiator.json
packs/data/abomination-vaults-bestiary.db/caliddo-haruvex.json
packs/data/abomination-vaults-bestiary.db/child-of-belcorra.json
packs/data/abomination-vaults-bestiary.db/cynemi.json
packs/data/abomination-vaults-bestiary.db/deadtide-skeleton-guard.json
packs/data/abomination-vaults-bestiary.db/deep-end-sarglagon.json
packs/data/abomination-vaults-bestiary.db/drill-field-barbazu.json
packs/data/abomination-vaults-bestiary.db/falxi-orshendiel.json
packs/data/abomination-vaults-bestiary.db/galudu.json
packs/data/abomination-vaults-bestiary.db/hellforge-barbazu.json
packs/data/abomination-vaults-bestiary.db/jafaki.json
packs/data/abomination-vaults-bestiary.db/khurfel.json
packs/data/abomination-vaults-bestiary.db/ladys-whisper.json
packs/data/abomination-vaults-bestiary.db/murmur.json
packs/data/abomination-vaults-bestiary.db/nyzuros.json
packs/data/abomination-vaults-bestiary.db/observation-deck-seugathi-researcher.json
packs/data/abomination-vaults-bestiary.db/padli.json
packs/data/abomination-vaults-bestiary.db/poisoning-room-specter.json
packs/data/abomination-vaults-bestiary.db/quara-orshendiel.json
packs/data/abomination-vaults-bestiary.db/salaisa-malthulas.json
packs/data/abomination-vaults-bestiary.db/stonescale-spirits.json
packs/data/abomination-vaults-bestiary.db/summoning-chamber-erinys.json
packs/data/abomination-vaults-bestiary.db/torture-chamber-barbazu.json
packs/data/abomination-vaults-bestiary.db/urthagul.json
packs/data/abomination-vaults-bestiary.db/warped-brew-morlock.json

These are mostly "item refreshes" since some of these used old versions of items with no art, or no items at all. The main true change intended was to remove the key from Padli's inventory, so if the quality of this MR is not up to par, feel free to axe the other changes and only include that one.

Update items on some of the unique AV NPCs

---

packs/data/equipment.db/blight-bomb-greater.json
packs/data/equipment.db/blight-bomb-lesser.json
packs/data/equipment.db/blight-bomb-major.json
packs/data/equipment.db/blight-bomb-moderate.json
packs/data/equipment.db/goo-grenade-greater.json
packs/data/equipment.db/goo-grenade-lesser.json
packs/data/equipment.db/goo-grenade-major.json
packs/data/equipment.db/goo-grenade-moderate.json
packs/data/equipment.db/junk-bomb-greater.json
packs/data/equipment.db/junk-bomb-lesser.json
packs/data/equipment.db/junk-bomb-major.json
packs/data/equipment.db/junk-bomb-moderate.json
packs/data/equipment.db/pernicious-spore-bomb-greater.json
packs/data/equipment.db/pernicious-spore-bomb-lesser.json
packs/data/equipment.db/pernicious-spore-bomb-major.json
packs/data/equipment.db/pernicious-spore-bomb-moderate.json
packs/data/equipment.db/redpitch-bomb-greater.json
packs/data/equipment.db/redpitch-bomb-lesser.json
packs/data/equipment.db/redpitch-bomb-major.json
packs/data/equipment.db/redpitch-bomb-moderate.json
packs/data/equipment.db/tallow-bomb-greater.json
packs/data/equipment.db/tallow-bomb-lesser.json
packs/data/equipment.db/tallow-bomb-major.json
packs/data/equipment.db/tallow-bomb-moderate.json
packs/data/equipment.db/twigjack-sack-greater.json
packs/data/equipment.db/twigjack-sack-lesser.json
packs/data/equipment.db/twigjack-sack-major.json
packs/data/equipment.db/twigjack-sack-moderate.json

Some notes:
Goo Grenade: Missing note and effect for speed penalty.
I left the notes for these bombs for now, as they contain extra info:
Pernicious Spore Bomb: "The bomb's splash area is coated in vegetation, becoming difficult terrain for 1 round."
Redpitch Bomb: "On a critical hit, the target is Clumsy until the start of my next turn."
Tallow Bomb: "the target is Sickened from the stench of burning fat. The creature can't reduce its sickened value below 1 while the persistent fire damage lasts."

Add persistent damage to alchemical bombs

---

src/module/chat-message/document.ts
static/lang/en.json
static/templates/chat/persistent-damage-recovery.hbs

I stab my own module. I will miss trolling people by calling it `pf2e Persistent Damage`.
I will have to fix the title name separately, I believe that's an issue with Statistic.

Add persistent recovery button and auto-recover on success

---

packs/data/classfeatures.db/armor-expertise.json

Note that this doesn't include chain's critical damage reduction. I suppose we could implement that as a resistance, but it'll take some additional work.

Add resistance REs to Armor Expertise

---

src/scripts/register-templates.ts

Just to prevent the multiple concurrent requests for the same template files that will occur on initial load.

Pre-register roll message templates

---

src/module/item/physical/runes.ts

Rune doesn't proc on any kind of hit.

Remove Serrating Critical Success Note

---

src/styles/system/journal/_index.scss
src/styles/system/journal/critical-fumble-deck.scss

More specificity to the CSS selectors added so the more generic CRB Journal Styles in Dorako UI do not override the look and feel of Critical Hit/Fumble cards.
Also allows the System to specify CSS for Journals without overriding the these specific types of journal entries.
Before:
After:

Add more specificity to the CSS selectors for Critical Hit/Fumble Journals

---

packs/data/pathfinder-bestiary-3.db/tzitzimitl.json

The [Tzitzimitl](https://2e.aonprd.com/Monsters.aspx?ID=1353) was missing the DC / modifier for the innate spells, ritual was set correctly.

Fix Tzitzimitl spellcasting DC for innate spells

---

src/module/chat-message/document.ts
src/scripts/ui/inline-roll-links.ts

I'd like to leave the inline link flat-check domain for now in case anyone is still using it, though I think once we get new roll types it'll be on consideration for chopping block.

Remove all domain from flat checks

---

packs/data/criticaldeck.db/critical-fumble-deck-41.json
packs/data/criticaldeck.db/critical-fumble-deck-51.json
packs/data/criticaldeck.db/critical-fumble-deck-52.json
packs/data/other-effects.db/effect-dazzled-until-end-of-your-next-turn.json
packs/data/other-effects.db/effect-deafened-until-end-of-your-next-turn.json

Specifically fumble cards 41, 51 and 52.
The remaining cards that give conditions till end of next turn give numerical conditions (e.g. Slowed 2) so aren't suitable to grant like this.

Add effect with an RE for critical fumble deck cards that cause Deafened or Dazzled until the end of next turn.

---

src/module/actor/character/document.ts
src/module/actor/character/sheet.ts
src/module/actor/sheet/spellcasting-dialog.ts
src/module/item/class/document.ts
static/lang/en.json
static/templates/actors/spellcasting-dialog.hbs

This removes the exclusion of untrained class DCs when populating `system.proficiencies.classDCs`. A character with only a single untrained class DC won't have it appear on their sheet, but it will be present and available for the occasional mechanical necessity. Class DC options when creating spellcasting entries will only include trained (or better) class DCs, and will appear as "Class DC ([class name])"

Always add class DCs for PCs, refine appearance

---

src/module/scene/token-document/document.ts

I can't guarantee that this will fix forge. But looking at their PR, I have a decent amount of faith this will work (though perhaps we'll have to do the same in more locations as well).

Allow token images on other hosts to be default

---

src/module/rules/rule-element/token-image.ts

Currently `scale` only takes integers, which can be hard to set up properly for tokens with pop-out elements.

Allow for decimal scales in TokenImage

---

src/module/actor/sheet/base.ts
src/module/actor/sheet/item-summary-renderer.ts
src/module/apps/hotbar.ts
src/module/item/base.ts
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/npc/partials/attack.hbs
types/foundry/client/documents/mixins/client-document-mixin.d.ts

I had to untangle some deep-running mess, so this should wait until 4.7 work starts.
A melee item's drag data needs all necessary properties for creating an strike macro if dropped the hotbar and an item clone if dropped onto another sheet.

Fix dropping melee items on other sheets

---

packs/data/backgrounds.db/harrow-led.json
packs/data/backgrounds.db/raised-by-belief.json

Closes https://github.com/foundryvtt/pf2e/issues/5790

Add second open ability boost to Harrow-Led and raised by Belief backgrounds

---

static/template.json

How did this ever work at any point after the entire coins refactor? Wondering if it was some change in template.json I didn't notice.

Fix newly created kits erroring on sheet open

---

packs/data/pathfinder-bestiary-2.db/grendel.json

damage are 2d6 persistent bleed damage according to the book and AoN.

Fix Grendel Tooth grind ability

---

src/module/rules/rule-element/adjust-strike.ts

In the recent update to allow `remove` and `subtract` weapon traits using the `AdjustStrike` rule element, an issue was introduced where, if a scorable trait was added (e.g. fatal-d12) and there was already a trait with the same name (e.g. fatal-d10) on the weapon, then the existing trait would be removed but the new trait would not be added.
Fixes #5775.

Fix AdjustStrike trait upgrade

---

src/module/item/spellcasting-entry/collection.ts
static/lang/en.json

Starting some work on better integrating psychic into the system, this seemed a good first step to stop people from putting amped spells into normal spellcasting entries.

Prevent focus spells from being added to other spellcasting collections

---

src/module/scene/token-document/aura/index.ts

I'm not 100% sure this has no negative side effects but it seems to be working fine.
Closes #5905

Cache the first `TokenAura.squares` getter result instead of recreating it each time it is called

---

src/module/rules/index.ts
src/module/rules/rule-element/adjust-modifier.ts
src/module/rules/rule-element/adjust-strike.ts
src/module/rules/rule-element/ae-like.ts
src/module/rules/rule-element/aura.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/data.ts
src/module/rules/rule-element/flat-modifier.ts
src/module/rules/rule-element/index.ts
src/module/rules/rule-element/iwr/base.ts
src/module/rules/rule-element/roll-note.ts
src/module/rules/rule-element/substitute-roll.ts
src/module/system/predication.ts
src/module/system/schema-data-fields.ts
types/foundry/common/abstract/data.d.ts
types/foundry/common/data/fields.d.mts
types/foundry/common/data/index.d.ts
types/foundry/common/index.d.ts
types/foundry/index.d.ts
types/foundry/util.d.ts

This includes both `RuleElementPF2e` getting a `DataModel` parent as well as initial work on writing schema definitions for subclasses. It makes use of a `LaxSchemaField` class that doesn't prune unrecognized fields so that the remaining conversion work can be done over time.

Have `RuleElementPF2e` extend `DataModel`

---

src/styles/ui/_hover.scss

Tweak style of modifiers tooltip labels to accommodate hyphenated words

---

src/module/apps/sidebar/index.ts
src/module/apps/sidebar/item-directory.ts
src/scripts/hooks/init.ts
src/styles/ui/sidebar/_index.scss
src/styles/ui/sidebar/_item-directory.scss
static/lang/en.json
static/templates/sidebar/actor-document-partial.hbs
static/templates/sidebar/item-document-partial.hbs

To bring the item sidebar in line with the actor one, and to improve UX to see item levels at a glance, particularly for creating homebrew.

Add item level display to item directory

---

src/scripts/config/index.ts
src/scripts/hooks/load.ts

Brighten darker scene default colors for basic usability

---

src/module/system/check/check.ts

Using the native DOM Event in anticipation of eventually jettisoning JQuery here

Pass originating `Event` to check callbacks

---

src/module/apps/effects-panel.ts
src/module/item/abstract-effect/data.ts
src/module/item/condition/document.ts
src/module/item/effect/document.ts
src/module/item/effect/sheet.ts
src/styles/item/_sidebar.scss
src/styles/system/_effects-panel.scss
static/lang/en.json
static/templates/items/effect-sidebar.hbs
static/templates/system/effects-panel.hbs

Labels exist in data yet but they're not shown. We can probably add it to the tooltip under the name?

Add support for effect counter labels and formula badges

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/data.ts
src/module/item/abstract-effect/data.ts
src/module/item/abstract-effect/index.ts
src/module/item/action/data.ts
src/module/item/action/index.ts
src/module/item/affliction/data.ts
src/module/item/ancestry/data.ts
src/module/item/base.ts
src/module/item/data/base.ts
src/module/item/effect/data.ts
src/module/item/feat/data.ts
src/module/item/physical/data.ts
src/module/item/spell/data.ts
src/module/rules/rule-element/aura.ts

Before any eager beavers or weasels go to town with this, it should not be used when the aura requires a saving throw or isn't automatically applied to those merely present in the aura (so no start-of-turn or end-of-turn triggering)

Add support for enemy- and all-affecting auras

---

packs/scripts/extract.ts

This warning clutters our extracts on data entry. If the warning is valid it will fail the pipeline, but 99% of the time on large data entry projects it just spams terminal and hides warnings we care about like missing action categories. The reason it comes up so often is because the script enters condition and action links with the name rather than the UUID, which makes several things easier for us.

Remove warning from extract

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/item/spell/document.ts
src/module/system/damage/modifier-dialog.ts
src/module/system/damage/weapon.ts
src/scripts/sheet-util.ts
src/styles/ui/_damage-dialog.scss
src/styles/ui/_index.scss
static/lang/en.json
static/templates/chat/damage/damage-modifier-dialog.hbs

It's only enabled in development  for now and can be opened by holding shift while pressing a damage button.
The UI could still use some refinement but it's looking ok in my opinion.
Weapon Damage:
Spell Damage:

Add a dialog to modifiy damage roll modifiers

---

packs/data/feats.db/diverse-weapon-expert.json

The Diverse Weapon Expert feat already used rule elements to set up the new proficiency for simple and martial weapons, but was missing the proficiency for advanced weapons.

Have Diverse Weapon Expert upgrade advanced weapon proficiency to trained

---

packs/data/kingmaker-bestiary.db/tulvak.json

Fix typo: "green gag" -> "green hag"

Fix typo in blurb of Tulvak's stat block

---

packs/data/bestiary-effects.db/effect-utter-despair.json
packs/data/extinction-curse-bestiary.db/dyzallin-shraen.json

Note that right-clicking on the Frightened 2 can reduce it to 1, but it can't be removed.

Add effect for Utter Despair

---

src/styles/packs/_settings.scss

Fixes foundryvtt/pf2e#5078
This pushes the save button to the bottom of the screen so that the user can expand the compendium to as large as they'd like without getting a lot of white space.
Note: This is my first contributing PR to a GitHub project that isn't mine so let me know if I need to include anything else!

Fix placement of save button in compendium browser on resizing

---

src/module/actor/creature/document.ts
src/module/system/damage/weapon.ts

Looking for the pattern of processing an entire list, then pop() to only use last element.

Optimize instances of processing an entire array only to use pop() to get the last element

---

src/module/item/melee/document.ts
src/module/item/melee/sheet.ts
static/lang/en.json

Temporary measure until NPC damage refactor

Prevent creation of NPC splash/precision damage without matching partial

---

src/module/rules/rule-element/adjust-modifier.ts
src/module/rules/rule-element/adjust-strike.ts
src/module/rules/rule-element/ae-like.ts
src/module/rules/rule-element/crit-spec.ts
src/module/rules/rule-element/data.ts
src/module/rules/rule-element/flat-modifier.ts
src/module/rules/rule-element/iwr/base.ts
src/module/rules/rule-element/iwr/immunity.ts
src/module/rules/rule-element/iwr/resistance.ts
src/module/rules/rule-element/iwr/weakness.ts
src/module/rules/rule-element/roll-note.ts
src/module/system/schema-data-fields.ts
types/foundry/common/abstract/data.d.mts
types/foundry/common/data/fields.d.mts

When `DataField#required` is `false` and `DataField#initial` is `undefined`, the generated property on the parent `DataModel` may also be `undefined`. Minimal runtime updates.

Improve accuracy of generated `DataModel` fields

---

src/module/item/abstract-effect/document.ts
src/module/item/condition/document.ts

Reconsidering the design of this: making an origin item (e.g., heightening a spell) useful is non-trivial, and it's already expensive enough to retrieve the actor via `fromUuidSync`.

Only retrieve origin actor from dragged effects

---

src/module/actor/base.ts
src/module/item/base.ts
src/module/rules/rule-element/battle-form/rule-element.ts

The defaults are set after the constructor completes, clobbering what gets set during data preparation.

Don't set defaults to `ActorPF2e` and `ItemPF2e` properties

---

packs/data/agents-of-edgewatch-bestiary.db/graveknight-of-kharnas.json
packs/data/feats.db/garudas-squall.json
packs/data/kingmaker-bestiary.db/ntavi.json
packs/data/npc-gallery.db/pathfinder-venture-captain.json
packs/data/npc-gallery.db/veteran-reclaimer.json
packs/data/strength-of-thousands-bestiary.db/bharlen-sajor.json
packs/data/strength-of-thousands-bestiary.db/graveknight-captain.json
packs/data/strength-of-thousands-bestiary.db/graveknight-champion.json

Doesn't change note REs into damage REs, e.g. for pick.
Doesn't change the brawling notes, as the class DC based inline save doesn't work for NPCs.

Replace explicit NPC crit spec text with PF2E.Item.Weapon.CriticalSpecialization.*

---

src/module/actor/base.ts

For some reason, `Actor#update` no longer returns itself following the update if the actor is synthetic.

Fix application of "deadAtZero" setting

---

packs/data/classfeatures.db/incredible-movement.json

So other feats targeting it (like https://github.com/foundryvtt/pf2e/blob/master/packs/data/feat-effects.db/stance-stoked-flame-stance.json) continue to work even if localized

Adding slug to Incredible Movement RE

---

packs/data/age-of-ashes-bestiary.db/barushak-il-varashma.json
packs/data/age-of-ashes-bestiary.db/immortal-ichor.json
packs/data/age-of-ashes-bestiary.db/spiritbound-aluum.json
packs/data/age-of-ashes-bestiary.db/teyam-ishtori.json

Found some remaining oddballs in the age of ashes spells. Immortal ichor for example had the levels of his spells changed instead of them being heightened.

Update age of ashes spell exceptions

---

static/templates/actors/character/tabs/actions.hbs

It's nice to see and it doesn't appear as one of the traits.
For ranged attacks added by a Strike RE, there's no other way to find it.

Add range increment display to strike action item

---

packs/data/feats.db/hidden-thorn.json
packs/data/feats.db/murderous-thorns.json
static/lang/re-en.json

The BattleForm RE uses "Thorns".  It's written "thorns" in the book.  But the translation entry was "Thorn".

Fix name of Thorns battle form translation and update Hidden/Murderous Thorn(s) feats

---

src/module/system/action-macros/acrobatics/maneuver-in-flight.ts
src/module/system/action-macros/acrobatics/tumble-through.ts
src/module/system/action-macros/athletics/long-jump.ts
src/module/system/action-macros/deception/create-a-diversion.ts
src/module/system/action-macros/deception/impersonate.ts
src/module/system/action-macros/deception/lie.ts
src/module/system/action-macros/diplomacy/gather-information.ts
src/module/system/action-macros/helpers.ts
src/module/system/action-macros/nature/command-an-animal.ts
src/module/system/action-macros/stealth/conceal-an-object.ts
src/module/system/action-macros/stealth/hide.ts
src/module/system/action-macros/stealth/sneak.ts
src/module/system/action-macros/thievery/palm-an-object.ts
src/module/system/action-macros/thievery/steal.ts
static/lang/en.json

De-duplicate roll notes for action macros with similar result on both success and critical success or on both failure and critical failure.

Refine action macro degree of success roll notes

---

src/styles/item/_header.scss
src/styles/ui/sidebar/_item-directory.scss

Use `object-fit: contain` for item icons on sheets and sidebar

---

src/module/actor/character/automatic-bonus-progression.ts
src/module/actor/character/document.ts
src/module/item/physical/runes.ts
src/module/item/weapon/data.ts
src/module/item/weapon/document.ts
src/module/system/damage/weapon.ts
src/module/system/tag-selector/index.ts

Among other issues, adjusted weapon names were getting set before runes on weapons were finalized, and strike adjustments were getting missed. This is a refactor to consolidate sourcing of rune data during item data preparation and for damage formula construction.

Rewrite order of weapon rune preparation

---

src/module/actor/character/data/types.ts
src/module/actor/character/document.ts
src/module/actor/data/base.ts

With the exception of the basic unarmed attack, which is forced to the end of the readied strikes

Sort strikes on PC sheet alphabetically

---

src/module/actor/creature/document.ts
src/module/actor/vehicle/document.ts
src/module/rules/rule-element/adjust-modifier.ts
src/module/rules/rule-element/flat-modifier.ts
static/templates/actors/vehicle/sidebar/vehicle-armorclass.hbs
static/templates/actors/vehicle/sidebar/vehicle-health.hbs

Hardness uses data-property in case ae-likes touch it, but otherwise doesn't receive modifiers until we find something in the game that tweaks it. This doesn't make clumsy/enfeebled work for hazard strikes, since hazard strikes don't add {ability}-based selectors.
After this we can probably make rework speed, but anything more will require the ability to retrieve an abilities/effect's source actor (making collision dc match class dc, for example).

Prepare vehicle hp, run ae-likes, and enable usage of certain REs in vehicles/hazards

---

packs/data/classfeatures.db/armor-innovation.json
src/module/rules/rule-element/choice-set/rule-element.ts

If a roll option is declared for a Choice Set, it obviously never wants a UUID. Given that, a `recordSlug` property isn't actually necessary.

Simplify slug recording for `ChoiceSet#rollOption`

---

packs/data/feats.db/shared-stratagem.json

The text has been modified slightly from the original for better readability. It reads:
> The creature you hit is Flat-Footed to **a designated** ally on the next attack **the ally** makes against the creature before the start of your next turn.
> The creature you hit is Flat-Footed to **that** ally on the next attack **the designated ally** makes against that creature before the start of your next turn.

Shared Stratagem Note

---

packs/data/kingmaker-bestiary.db/breath-of-despair.json

Breath of Despair has Stealth +13 in the books (page 133) but in the module is +3

Fixed stealth for Breath of Depair

---

src/module/actor/sheet/item-summary-renderer.ts
src/module/item/base.ts
src/module/item/weapon/document.ts
src/styles/actor/_spell-list.scss
static/templates/actors/partials/conditions.hbs
static/templates/actors/partials/item-summary.hbs

I'll look into toggle behavior smoothness and verifying the affected by stuff at a later date. The affected by likely doesn't work because it wants a flattened condition object, but its less broken than it was before (at least the condition summary renders).

Show condition summary and render item summary in template

---

src/module/scene/token-document/aura/index.ts
src/module/scene/token-document/document.ts

This was a property from the RE's initial development, but it was instead moved to the aura effect data

Remove unused `AuraData#includesSelf`

---

src/module/system/action-macros/ancestry/automaton/arcane-slam.ts
src/module/system/action-macros/athletics/disarm.ts
src/module/system/action-macros/athletics/grapple.ts
src/module/system/action-macros/athletics/shove.ts
src/module/system/action-macros/athletics/trip.ts
src/module/system/action-macros/helpers.ts
src/module/system/action-macros/types.ts

Refactor action check roll code to have item bonus logic from traits in the action code itself. This is mostly affecting the various combat maneuver actions with the attack trait at this point. The refactoring should cut down a bit on the shared action code while still making it more flexible for future actions.

Move action-specific bonuses from traits to the individual actions

---

packs/data/pathfinder-bestiary-2.db/carbuncle.json

Fix carbuncle (of bestiary 2): Levitate target has to be "Self only"

Fix target of levitate spell in carbuncle to Self only

---

src/module/system/damage/formula.ts

Wrap precision/splash damage in parentheses if necessary

---

src/module/apps/compendium-browser/tabs/action.ts
src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/data.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/compendium-browser/tabs/feat.ts
src/module/apps/compendium-browser/tabs/hazard.ts
src/module/apps/compendium-browser/tabs/spell.ts
static/templates/compendium-browser/filters.hbs

Also changes the trait filter from `some` to `every` to work as expected when multiple traits are selected.

Tagify remaining Compendium Browser trait filters

---

src/module/apps/hotbar.ts
src/scripts/macros/hotbar.ts

Repurposes the now unused `actorId` to contain the item id of the strike origin with a fallback to strike slug for backwards compatibility.
Closes #6366

Find macro strike by item id instead of strike slug

---

src/module/system/action-macros/helpers.ts
src/module/system/action-macros/types.ts
src/scripts/register-templates.ts
static/templates/chat/action/flavor.hbs
static/templates/chat/action/header.hbs

Allow an action to dynamically build the subtitle of the action chat card - which will usually be the check type, like "Mercantile Lore Check" - from the actor performing the action and the target of the action. This will be helpful for the Discover and Influence actions that might often rely on lore skills where we need the convert the slug to the translated name from either of those actors.

Support building action subtitle from actor and target

---

packs/data/blog-bestiary.db/firebrand-ancient-brass-dragon.json
packs/data/pathfinder-bestiary-2.db/adult-magma-dragon-spellcaster.json
packs/data/pathfinder-bestiary-2.db/adult-magma-dragon.json
packs/data/pathfinder-bestiary-2.db/ancient-magma-dragon-spellcaster.json
packs/data/pathfinder-bestiary-2.db/ancient-magma-dragon.json
packs/data/pathfinder-bestiary-2.db/young-magma-dragon-spellcaster.json
packs/data/pathfinder-bestiary-2.db/young-magma-dragon.json

wing deflection is missing rule elements that can be found in other creatures like `packs/data/pathfinder-bestiary.db/adult-brass-dragon.json`

Add rule elements for wing deflection reaction

---

packs/data/classfeatures.db/ruffian.json
packs/data/classfeatures.db/sneak-attack.json
packs/data/feats.db/butterflys-sting.json
packs/data/feats.db/magical-trickster.json
packs/data/feats.db/sneak-attacker.json
packs/data/iconics.db/merisiel-level-1.json
packs/data/iconics.db/merisiel-level-3.json
packs/data/iconics.db/merisiel-level-5.json
packs/data/kingmaker-bestiary.db/nok-nok-level-1.json
packs/data/kingmaker-bestiary.db/nok-nok-level-5.json
packs/data/paizo-pregens.db/kaako-ashfeather.json
packs/data/paizo-pregens.db/merisiel-beginner-box.json
packs/data/paizo-pregens.db/muruwa.json
packs/data/paizo-pregens.db/quizrel.json
packs/data/paizo-pregens.db/reaching-rings.json
packs/data/paizo-pregens.db/zeah.json
packs/data/paizo-pregens.db/zerryd.json
packs/scripts/run-migration.ts
src/module/migration/migrations/824-sneak-attack-damage-source.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/damage-dice.ts

This sets PC sneak attack damage dice number and die size at `actor.flags.pf2e.sneakAttackDamage`, allowing Sneak Attack's DamageDice RE (and other abilities like Magical Trickster) to pull the correct damage regardless of the PC's class or other feats.

Source sneak attack damage from a common actor flag

---

packs/data/classfeatures.db/battledancer.json
packs/data/classfeatures.db/braggart.json
packs/data/classfeatures.db/fencer.json
packs/data/classfeatures.db/gymnast.json
packs/data/classfeatures.db/panache.json
packs/data/classfeatures.db/wit.json
static/lang/re-en.json

Add action roll notes informing swashbucklers when they gain panache

---

src/module/rules/rule-element/damage-dice.ts

Return deferred damage dice that fail their predication test as disabled instead of omitting them

---

src/module/canvas/perception/modes.ts

The hearing range is ignored (#5819). I understand that this is an optimization, but, if RBV is disabled, the hearing range configured by the user isn't necessarily infinite. Also this override breaks Perfect Vision's Vision Limitation for the Hearing mode: the limit is applied in a patch of `DetectionMode.prototype._testRange`, which is bypassed by the current hearing mode implementation.

Fix hearing range test

---

packs/data/bestiary-effects.db/effect-hydra-heads.json

the effect will still be changed to the hydras starting amount of heads on the npc actor, this will just make it so when a hydra grows more heads from 0, dragging on the effect again will not jump the head count to 5

Set Hydra Heads effect counter default to 1

---

packs/data/equipment-effects.db/effect-silversheen.json
packs/data/equipment.db/silversheen.json

This helps further automate IWR with respect to silvered weapons.
This was inspired by the automation of the monk class feat Metal Strikes https://2e.aonprd.com/Classes.aspx?ID=8
The reason for the counter being 10 is for ammunition

Add silversheen equipment effect

---

src/module/system/settings/automation.ts

The GMG assumes all creatures are lootable:
> If you gave a creature gear equivalent to a PC, your PCs would gain a huge amount of treasure by defeating a large group of them. Using Table 2–4: Safe Items can help you avoid that. A creature can have a single permanent item of the listed level without issue.

Flip default of "lootableNPCs" setting

---

src/module/canvas/helpers.ts

tell javaScript that we are sorting numbers instead of apples and n-dimensional planes.

fix range calculation

---

src/module/canvas/helpers.ts
src/module/canvas/measured-template.ts

I'm pretty sure this used to be a thing so it's either a bugfix or an enhancement.
Before:
After:

Highlight grid area of `MeasuredTemplatePF2e` previews

---

src/module/actor/base.ts

Some people are still using Combat Enhancements, and it apparently does drag-and-drop reordering by setting decimal initiative values

Truncate initiative when setting as roll option

---

packs/data/age-of-ashes-bestiary.db/lazurite-infused-stone-golem.json

Changed wrong damage type necrotic to negative in lazurite-infused stone golem from age-of-ashes-bestiary

Data entry: Changed wrong damage type necrotic in lazurite-infused stone golem

---

packs/data/feats.db/order-explorer.json

Removing the dash in the flag makes it work
Fixes #6681

Fix Order Explorer automation

---

src/module/actor/base.ts

Avoid accessing `Token#actor` while its return is being constructed

---

packs/data/feats.db/dread-striker.json
src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/data/base.ts
src/module/actor/helpers.ts
src/module/actor/modifiers.ts
src/module/actor/types.ts
src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/rules/index.ts
src/module/rules/rule-element/ephemeral-effect.ts
src/module/rules/rule-element/grant-item/rule-element.ts
src/module/rules/rule-element/mixins.ts
src/module/rules/synthetics.ts
src/module/system/conditions/manager.ts
src/module/system/statistic/index.ts
static/lang/re-en.json

This rule element allows an attacker to push an effect onto a target for a single attack or damage roll--and also for the target to push an effect onto the attacker for the same roll. This is done by adding effect items to contextual clones while assembling attack/damage roll contexts.

Add EphemeralEffect rule element

---

src/module/actor/helpers.ts
src/module/canvas/status-effects.ts
src/module/encounter/document.ts
src/module/system/effect-tracker.ts
src/module/system/settings/index.ts
src/module/system/settings/variant-rules.ts
src/scripts/hooks/ready.ts

This turned out to be extremely annoying for anyone doing something in their actor sheet when a turn changes

Don't rerender actor sheets every turn change

---

packs/data/feat-effects.db/stance-jellyfish-stance.json
packs/data/feats.db/jellyfish-stance.json

FotRP Hardcover changed this to level 8 (from 6) and 1d6 damage (from 1d8)

Update Jellyfish Stance per FotRP Hardcover

---

src/module/actor/base.ts

This came up while I was testing the combination of a `MarkToken` with an `EphermeralEffect` predicated on the mark.
Fully replacing the original roll options with the new options from the clone probably is the safest way to do it.
Test Feat (Mastemind Racket):
```json
{
"key": "EphemeralEffect",
"predicate": [
"target:mark:effect-mastermind"
],
"selectors": [
"attack",
"strike-damage"
],
"uuid": "Compendium.pf2e.conditionitems.AJh5ex99aV6VTggg"
}
```
```json
{
"key": "MarkToken",
"slug": "effect-mastermind"
}
```

Generate `target` roll options before extracting `EphemeralEffect`s

---

src/module/item/weapon/document.ts

Add details such as id, slug, level, material type and grade, and traits for ammunition to roll options for damage rolls with weapons using ammunition.

Expand damage roll options for strikes with ammunition details

---

src/module/actor/base.ts
src/module/item/armor/document.ts
src/module/item/base.ts
src/module/item/weapon/document.ts

Workaround of https://github.com/foundryvtt/foundryvtt/issues/7987
This will halt embedded item data preparation if not called by the parent actor's `prepareEmbeddedDocuments` method. Besides the unecessary CPU cycle expenditure, it also creates some peril for system workflows in cases where an item inspects its parent on the assumption that the parent has begun its own data (re-)preparation.

Prevent double data preparation of embedded items

---

src/module/item/spell/sheet.ts
static/templates/items/spell-overlay.hbs

Also removes an errant quote in `spell-overlay.hbs`.

Fix creation of damage instances for fixed heightened overlays

---

src/module/rules/rule-element/roll-option.ts
src/module/rules/synthetics.ts
static/templates/actors/character/tabs/actions.hbs

Add a scope field to the RollOption rule element, which will allow restricting a roll option toggle to specific UI regions. If scope is omitted or set to "actions-tab", the toggle will show up in the default region on the Actions tab.

Add scope to roll option rule element

---

src/module/item/sheet/base.ts

Currently an error is thrown when a spell variant sheet is openend because it doesn't have a description editor.

Prevent GM notes button from appearing on variant spell sheets

---

src/module/actor/base.ts
src/module/item/condition/document.ts

* If you make someone frightened 1, then grant frightened 2, this now sets frightened 2 to the active condition.
* getCondition() without an argument now returns the active condition, and getCondition({ all: true }) now sorts properly.

Fix unlocked lower value conditions out-prioritizing higher value ones

---

src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/data.ts

The checkbox listeners expects string values so it's comparing 🍎 to 🟠 when the value is set by `openSpellTab`,

Fix `CompendiumBrowser#openSpellTab` using `number`s instead of `string`s for level

---

src/module/canvas/token/object.ts
src/module/item/condition/document.ts

This is fixing an old enough issue that its restoration might be considered an "enhancement" again.

Append numeric badge values to condition names

---

src/module/actor/npc/sheet.ts

This was used before effects were moved to a dedicated tab on NPC sheets

Remove unused listener on NPC sheet

---

src/module/chat-message/listeners/cards.ts

The spell's getRollOptions() already handles all of these (except "spell", which really shouldn't be used)

Remove redundant save options in save event handler

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/apps/compendium-browser/data.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/action.ts
src/module/apps/compendium-browser/tabs/base.ts
src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/data.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/compendium-browser/tabs/feat.ts
src/module/apps/compendium-browser/tabs/hazard.ts
src/module/apps/compendium-browser/tabs/spell.ts

This replaces the current clunky (and not type aware) initial filtering implementation. The initial filter is now a copy of the initialized `filterData` of a `CompendiumBrowserTab` that can be requested by calling `CompendiumBrowserTab#getFilterData`.
The returned object is fully typed (this could still be improved by narrowing the type of `CheckboxData.options`) and can be savely mutated.
`CompendiumBrowser#openTab` now expects a full `filterData` object as an optional second parameter.
A tab can now also be opened by calling `CompendiumBrowserTab#open` which also accepts initial `filterData` for that tab as an optional parameter.

Refactor initial filtering of Compendium Browser tabs

---

src/module/system/damage/damage.ts
src/module/system/damage/types.ts

Show the degree of success as critical success, success, failure, and critical failure instead of critical hit, hit, miss, and critical miss when the source of the damage roll is set to check.

Allow checks as the source of damage rolls

---

src/module/actor/character/crafting/entry.ts
src/module/actor/character/crafting/formula.ts
src/module/actor/character/document.ts
src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/item/consumable/document.ts
src/styles/actor/character/_crafting.scss
static/lang/en.json
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/crafting-entry-alchemical.hbs
static/templates/actors/crafting-entry-list.hbs

- Some CSS improvements for better header alignment.
- Removed a big chunk of `jQuery` from the tabs listeners.
- All Formulas are now sortable.
- All Formula items can now be sent to chat by clicking on the item image.
- All Formulas now support expanding their item summary.
- Deleting or unpreparing a formula now opens a confirmation dialog before deletion.
- The Compendium Browser buttons now open with the maximum level of the header they were clicked in.
Before:
After:
Closes #6086, #1776

Improve character sheet crafting tab

---

src/module/system/damage/weapon.ts

When the the damage type of a weapon is changed, the deadly dice should use the same damage type (not size!) as the base. Otherwise, if using something like Soulforger's Planar Pain on a weapon with the Deadly trait, the deadly die will never do elemental damage when it should. See #6858
Before:
After:

Override damage type of deadly dice when main damage type is changed

---

src/scripts/macros/earn-income/helpers.ts

This didn't actually do anything and predates the system implementation of assurance

Remove "Use Assurance" checkbox from Earn Income dialog

---

packs/data/feats.db/halfling-weapon-familiarity.json

> Characters with the Halfling Weapon Familiarity ancestry feat are trained in the frying pan.

Add frying pan training to Halfling Weapon Familiarity

---

types/foundry/client/documents/mixins/canvas-document-mixin2.d.ts
types/foundry/client/documents/mixins/index.d.ts
types/foundry/client/pixi/placeable-object/base.d.ts

Continuing the refactor and eventual replacement of the `ClientDocument` and `CanvasDocument` types

Add `CanvasDocumentMixin2` type definition

---

packs/data/spells.db/thunderburst.json

Bludgeoning was marked untyped, and was missing Sonic damage

Fix damage types on thunderburst

---

src/module/item/base.ts

We don't want to discard signature, heightenedLevel, uses.

Preserve all spell location data when using item.refreshFromCompendium()

---

src/module/actor/base.ts
src/module/system/action-macros/helpers.ts
src/module/system/check/check.ts
src/module/system/degree-of-success.ts
src/module/system/statistic/index.ts

Once everything is a `Statistic`, `CheckDC` can mostly just be replaced with it.

Expand adjusted DC tooltips to all targeted checks

---

packs/data/feats.db/dragons-presence.json

Dragon's Presence says "when you attempt to Demoralize a foe of **your level or lower**". This change fixes the rule element to also apply to equal-level foes.

Fix Dragon's Presence RE predicates

---

src/module/actor/creature/sheet.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/action.ts
src/module/apps/compendium-browser/tabs/data.ts
static/templates/actors/character/tabs/actions.hbs

The intent of this PR is to make the "Browse" buttons on the Actions tab of the player sheet more intuitive.
The PR fulfills this by filtering the resulting compendium list based on which button was pressed. In order to do so I needed to add the "Action Type" checkbox filter to the action compendium so that actions / reactions / free actions were filtered correctly.
I expect there to be feedback on this as this is my first submission and my primary motivation was getting it working for my upcoming sessions.

Filter compendium results based on action "Browse" button's context

---

src/module/apps/effects-panel.ts
src/styles/system/_effects-panel.scss
static/templates/system/effects-panel.hbs

This PR addresses feature request https://github.com/foundryvtt/pf2e/issues/4316. Specifically, it:
- Modifies the Effect Panel so that afflictions, conditions, and effects show effect descriptions in the hovering effect information. The description can be scrolled in its own UI element if the effect description is overly long. The description text can display enriched document links, which can be interacted with. 
- Adds an icon to the right of the effect name in the hovering effect information that allows the full effect description to be sent to chat. The send to chat icon uses the same hover indication as the effect info persistent damage recovery roll link (orange text-shadow).
I've added screenshots below that demonstrate the changes. This PR does potentially overlap with …

Effect panel shows effect descriptions and can send effects to chat

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/actor/types.ts
src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/system/action-macros/helpers.ts
src/module/system/check/types.ts
src/module/system/statistic/index.ts

- Rename to `#getRollContext` (and `#getAttackRollContext` to `#getCheckRollContext`)
- Permit itemless rolls to utilize the methods (but guarantee that if an item is passed, one will be returned)

Broaden usability of `ActorPF2e#getStrikeRollContext`

---

packs/data/classfeatures.db/bloodline-elemental.json
static/lang/re-en.json

The damage type override doesn't work, we can either leave it off or just let it sit there until it does function.

Allow Elemental Bloodline Sorcerer to select an Elemental Type

---

src/module/item/spell/document.ts
src/module/item/spell/sheet.ts
static/templates/chat/spell-card.hbs

- Variant buttons for spells that deal no damage are now displayed.
- Creation of interval heightening entries was using `data` as fallback property which lead to the update being silently dropped for variants. Not sure why.
- Variants that had the same action time as their parent were not displaying any action icon. Now they show the parents action icon instead.
- Updating of non-embedded variants was failing because of the `options.parent` check in `SpellPF2e#update`. Removing that should have no side effects.

Fix spell variant interval heightening creation, chat card display for saves and action icons for variants with no action override

---

src/module/actor/base.ts

This method is frequently used in user macros and leads to aberrant results when the argument isn't an actual slug

Enforce slugginess of `ActorPF2e#toggleCondition` argument at runtime

---

src/module/item/consumable/document.ts

Also don't show "1/1 charges", which accounts for most consumables
Closes #7093

Fix display of rarity in consumable chat cards

---

src/module/rules/rule-element/grant-item/rule-element.ts

This has never actually worked but lacked messaging saying as much.

Formally restrict GrantItem from being usable on physical items

---

src/module/actor/actions/base.ts
src/module/actor/actions/index.ts
src/module/actor/actions/simple.ts
src/module/actor/actions/single-check.ts
src/module/actor/actions/types.ts
src/styles/ui/sidebar/chat/_check.scss
static/lang/en.json
static/templates/system/actions/simple/chat-message-flavor.hbs

Define an initial interface for actions, as well an implementation and data structures for simple actions without any check involved and actions involving a single check.
**Take Cover**
```js
const action = new SimpleAction({
cost: 1,
description: "You press yourself against a wall or duck behind an obstacle to take better advantage of cover. If you would have standard cover, you instead gain greater cover, which provides a +4 circumstance bonus to AC; to Reflex saves against area effects; and to Stealth checks to Hide, Sneak, or otherwise avoid detection. Otherwise, you gain the benefits of standard cover (a +2 circumstance bonus instead). This lasts until you move from your current space, use an attack action, become unconscious, or end this effect as a free action.",
effect: …
```

Initial structure for more data-driven actions

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/system/check/types.ts

Always include token name when retrieving message speaker for checks

---

src/module/actor/initiative.ts
src/module/actor/sheet/base.ts
src/module/apps/sidebar/chat-log.ts
src/module/chat-message/listeners/set-as-initiative.ts
src/module/encounter/combatant.ts
src/module/encounter/document.ts
static/lang/en.json
types/foundry/common/documents/combatant.d.ts

- A combatant is created on rolling initiative if one doesn't exist already
- Roll params are passed from the character sheet again
- The `initiativeStatistic` is always set for characters and npcs
Closes #7164

Fix regressions with rolling initiative

---

src/module/item/physical/sheet.ts
static/templates/items/armor-sidebar.hbs
static/templates/items/backpack-sidebar.hbs
static/templates/items/book-sidebar.hbs
static/templates/items/consumable-sidebar.hbs
static/templates/items/equipment-sidebar.hbs
static/templates/items/formula-sidebar.hbs
static/templates/items/treasure-sidebar.hbs
static/templates/items/weapon-sidebar.hbs

- Use correct variable name in treasure sidebar template
- Remove superfluous `this` in all physical-item sidebar templates
- Have `PhysicalItemSheetPF2e#_updateObject` normalize falsish price strings

Fix some issues with price inputs on item sheets

---

packs/data/equipment.db/formulated-sunlight.json

Since the quantity and charges were swapped, it counted as 7 separate objects for purposes of bulk and wealth calculations.

Adjust "Formulated Sunlight" quantity and charges to match rations

---

src/module/apps/effects-panel.ts
src/styles/system/_effects-panel.scss
static/templates/system/effects-panel.hbs

- Fixed in-memory conditions not going to chat
- Move left-click/right-click instructions to directly below effect name
- Set cursor of to-chat link to pointer by wrapping it in an anchor tag
- Add a small amount of padding above to-chat link to reduce chance of accidentally moving cursor to preceding effect
Before:
After:

Fix some quirks and tweak styling of effects panel info boxes

---

src/styles/actor/_index.scss
src/styles/actor/character/_character.scss
src/styles/actor/familiar/_index.scss
src/styles/actor/hazard/_header.scss
src/styles/actor/loot/_index.scss
src/styles/actor/npc/_index.scss
src/styles/actor/vehicle/_index.scss
static/templates/actors/character/tabs/general.hbs
static/templates/actors/familiar-sheet.hbs
static/templates/actors/hazard/partials/header.hbs
static/templates/actors/loot/sidebar.hbs
static/templates/actors/npc/partials/sidebar.hbs
static/templates/actors/vehicle/tabs/vehicle-details.hbs

This PR resolves https://github.com/foundryvtt/pf2e/issues/6851. It:
- Adds "show image" functionality to most actor sheet types, with a show image icon that appears only when the actor image is hovered. Player Character and NPC sheets already had this, and this PR adds it to Hazard, Loot, Familiar, and Vehicle sheets. I wasn't able to check or work with Party sheets due to errors. 
- HTML/CSS classes for actor images are now more consistent across these sheets. 
- The mouse cursor switches to pointer on hover for all of these six sheet types. Previously, I think only Player Characters, Hazards, and Vehicles used pointer cursor.
I'll add images of the various sheets with the show image icon displayed. Since there are a variety of actor image sizes and frame styles, each of the Show Image …

Allow more actor sheet images to be shown to players

---

src/scripts/config/index.ts
src/scripts/config/traits.ts
static/lang/en.json

After checking how Deadly traits work, there is no code-change needed beyond adding it to the index.

Add Deadly D4 trait

---

src/module/actor/creature/document.ts
src/module/system/statistic/index.ts

Doesn't change the check label, but makes it match what the skills do.

Fix perception label in modifiers dialog

---

packs/data/feat-effects.db/effect-dread-marshal-stance.json

This reverts commit f9841fd4d678071d8b7af163d2225ee49d03b324.
> Your marshal's aura increases to a 20-foot emanation, and it grants you and allies a status bonus to damage rolls equal to the number of weapon damage dice of the unarmed attack or weapon you are wielding that has the most weapon damage dice.

Revert "Fix Dread Marshal Stance extra damage to be on strike damage"

---

src/module/actor/actions/simple.ts
src/module/actor/actions/single-check.ts
src/module/system/action-macros/basic/take-cover.ts
src/module/system/action-macros/index.ts
static/lang/action-en.json

Add an implementation of the Take Cover action to the global collection of actions in `game.pf2e.actions`.
Additionally, add a property to the action use options that allows the caller to suppress (value of `false`) or override (a UUID value or Effect item instance) the effect applied to the actor when the action is used. This is needed for specialized cases of certain action, like Take Cover with a tower shield that might not necessarily grant the usual effect of the action.
Also properly localize action names in chat card when action is used.

Add Take Cover action implementation

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts

This cropped up when I was testing out linting with [Rome](https://rome.tools) which checks for unused template literals.

Fix item id in strike damage domains

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/modifiers.ts
src/module/actor/npc/document.ts
src/module/actor/sheet/trick-magic-item-popup.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/base.ts
src/module/apps/sidebar/encounter-tracker.ts
src/module/item/abstract-effect/document.ts
src/module/item/base.ts
src/module/item/condition/document.ts
src/module/item/feat/document.ts
src/module/item/melee/document.ts
src/module/item/physical/document.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/scene/token-document/document.ts

Eventually we'll need to flip on `useDefineForClassFields` in tsconfig.json, which will actually emit class fields in the transpile result. Using `declare` will prevent that, preserving the current behavior.

Use `declare` instead of non-nullish assertions on class fields 

---

src/module/actor/base.ts

This used to accidentally work because reach wasn't defined on ranged weapons, but that has since been changed. Explicitly check the isMelee property, which is based on ranged increments instead of reach.
fixes #7318

Correct test for when flanking is applied

---

src/module/actor/party/document.ts
src/module/encounter/combatant.ts
src/module/scene/token-document/document.ts

This does a few things
* The party is marked as in combat if *all* members are in combat
* Members with active tokens get added to combat (if they aren't already)
* Members without active tokens create a notification (same as if an actor rolls from the sheet without a token)
Later on we should dump all actors to the scene first (thus skipping the need for the notification) but I'd like to have the sidebar changes in place before we start doing that, just to have more info on what the overall flow will be.

Add party members to initiative instead of self

---

src/module/actor/sheet/base.ts

~I'm not really happy with creating another `Sortable` instance but this is the only way I could get it to work.~
Found a better way.

Fix dragging of content links in inventory item description

---

src/module/actor/actions/base.ts
src/module/actor/actions/single-check.ts
src/module/actor/actions/types.ts
src/module/system/action-macros/index.ts
src/module/system/action-macros/medicine/administer-first-aid.ts
src/module/system/action-macros/medicine/treat-disease.ts
src/module/system/action-macros/medicine/treat-poison.ts
static/lang/action-en.json

Administer First Aid, Treat Disease, and Treat Poison.
Add better support for description chat cards when action has variants, and also allow action variants to override difficult class calculation based on target

Convert medicine skill actions

---

src/module/actor/character/data/types.ts
src/module/actor/character/document.ts
src/module/rules/rule-element/battle-form/rule-element.ts

* Skill modifier replacements were broken entirely due to skill `Statistic`s being cached
* Skill modifier breakdowns were showing old values from initial data preparation
* Strike attack-roll modifiers were displaying incorrectly on PC sheets

Fix several issues with battle forms

---

package-lock.json
package.json
vite.config.ts

The file-size savings isn't nothing (~500kb), but identifier minification would make investigating issue reports harder, and it's very unaccommodating to module authors

Preserve javascript identifiers in production builds

---

src/module/item/abstract-effect/document.ts

I think I just forgot about `getSelfRollOptions` at the time.

Limit retrieval of effect-origin roll options

---

src/module/rules/rule-element/token-image.ts
src/module/rules/synthetics.ts
src/module/scene/token-document/document.ts
types/foundry/common/documents/token.d.ts

Before I fight typescript to resolve the errors is this something we'd be fine with adding in? It will help quite a bit with a third party thing I am working on and it's kind of a neat thing to be able to manage the tint/opacity of a token with a rule element.

Add tint and alpha overrides to TokenImage

---

src/module/apps/pick-a-thing-prompt.ts

If the ChoiceSet is configured to "allowNoSelection": true, then clicking "Decline" results in a selectedIndex of null. The cast of Number(selectedIndex) evaluates to 0.

Fix declining a pick from a ChoiceSet defaulting to first item

---

packs/data/feats.db/interweave-dispel.json

A core rulebook data error that somehow lasted this long! Surprising since it's actually a good feat.

Fix action cost of Interweave Dispel

---

src/module/item/spell/document.ts

For example, hobgoblin NPCs have a bonus to area effect saving throws when in formation, and the hobgoblin ancestry feat Formation Training provides a similar bonus. Also useful for items like Blast Suit. The rolloption "area-damage" isn't sufficient for spells like Entangle which don't do damage.

Add "area-effect" to spell RollOptions

---

src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/migration-summary.ts
src/module/apps/world-clock/app.ts
src/module/canvas/status-effects.ts
src/module/chat-message/helpers.ts
src/module/chat-message/listeners/cards.ts
src/module/encounter/document.ts
src/scripts/config/index.ts
src/util/misc.ts

I'm using an import of `en.json` for the world clock app.  Not sure if that's a bad idea. Seems to work as a drop in replacement for `LocalizePF2e` in that case though.

Remove `LocalizePF2e` from `@module/apps`, `@module/canvas`, `@module/chat-message`, `@module/encounter`

---

src/module/system/damage/formula.ts

Fixes `2d6 + -2` Piercing showing up as a breakdown tag for things like mitflits

Fix breakdown tag for negative base modifier

---

src/module/rules/rule-element/adjust-degree-of-success.ts
src/module/system/degree-of-success.ts

As the title says, this PR adds 4 new options for DoS adjustment in the aforementioned RE.   
Additionally, this PR also fixes the issue where `two-degrees-XYZ` adjustments *theoretically* worked, but in practice the validator never let them through because they were missing from the list of valid amounts (this caused a whole single bug in the system with the Reckless Abandon Goblin feat).

Allow AdjustDegreeOfSuccess RE to adjust to a specific degree of success

---

packs/data/equipment-effects.db/effect-cognitive-mutagen-greater.json
packs/data/equipment-effects.db/effect-cognitive-mutagen-lesser.json
packs/data/equipment-effects.db/effect-cognitive-mutagen-major.json
packs/data/equipment-effects.db/effect-cognitive-mutagen-moderate.json

This implements the drawbacks for all 4 versions of the Cognitive Mutagen. -2 to the encumbrance limit, and -4 to the max bulk.

Implement drawbacks to Cognitive Mutagens

---

src/module/actor/npc/sheet.ts

This PR addresses #7425. It removes the token name from the title of a loot sheet when the user cannot see the token's name.

Hide NPC names on Loot Sheets

---

src/module/item/melee/document.ts
src/module/item/spell/document.ts
src/module/item/spell/helpers.ts
src/module/item/spell/index.ts
src/module/system/damage/formula.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts
src/scripts/dice.ts

Enables the ability to add damage dice to spells. Also sneaky fix so that elite only applies to the first instance of damage.

Refactor spells to use regular damage pipeline

---

packs/data/actions.db/breath-weapon-acid-cone.json
packs/data/actions.db/breath-weapon-acid-line.json
packs/data/actions.db/breath-weapon-cold-cone.json
packs/data/actions.db/breath-weapon-cold-line.json
packs/data/actions.db/breath-weapon-electricity-cone.json
packs/data/actions.db/breath-weapon-electricity-line.json
packs/data/actions.db/breath-weapon-fire-cone.json
packs/data/actions.db/breath-weapon-fire-line.json
packs/data/actions.db/breath-weapon-negative-cone.json
packs/data/actions.db/breath-weapon-negative-line.json
packs/data/actions.db/breath-weapon-piercing-cone.json
packs/data/actions.db/breath-weapon-piercing-line.json
packs/data/actions.db/breath-weapon-poison-cone.json
packs/data/actions.db/breath-weapon-poison-line.json

Fix the damage on the dragon eidolon's breath weapons by changing `floor` to `ceil` in the damage roll.

Fix damage on Eidolon breath weapons

---

static/templates/actors/hazard/sheet.hbs

Hazard sheet did still use the old `system.source` instead of `system.details.source`for the value of the input fields. This results in empty values shown in the fields, and also can overwrite the existing data with those empty values.

Fix for hazard sheet after migrated source data

---

packs/data/actions.db/drain-bonded-item.json

Fixed drain bonded item from at will -> once per day to align with the description

Add correct uses to Drain Bonded Item

---

packs/data/ancestryfeatures.db/advanced-undead-benefits.json
packs/data/feats.db/daywalker-vampire.json

This addresses #7556; the Daywalker feat from the Vampire dedication now grants the advanced undead benefits.
Additionally, the advanced undead benefits feature now grants poison resistance like it's supposed to.

Fix Advanced Undead Benefits

---

packs/data/feat-effects.db/stance-tiger-stance.json

Added `slug` field to Tiger Claw strike (from the Tiger Stance).
The absence of `slug` caused bleed-on-crit and Tiger Slash to not apply when Tiger Claw strike name was translated.

Add Tiger Claw slug

---

packs/data/spell-effects.db/spell-effect-elemental-form-air.json
packs/data/spell-effects.db/spell-effect-elemental-form-earth.json
packs/data/spell-effects.db/spell-effect-elemental-form-fire.json
packs/data/spell-effects.db/spell-effect-elemental-form-water.json
packs/data/spell-effects.db/spell-effect-fey-form-dryad.json
packs/data/spell-effects.db/spell-effect-fey-form-elananx.json
packs/data/spell-effects.db/spell-effect-fey-form-naiad.json
packs/data/spell-effects.db/spell-effect-fey-form-redcap.json
packs/data/spell-effects.db/spell-effect-fey-form-unicorn.json
packs/data/spell-effects.db/spell-effect-insect-form-ant.json
packs/data/spell-effects.db/spell-effect-insect-form-beetle.json
packs/data/spell-effects.db/spell-effect-insect-form-centipede.json
packs/data/spell-effects.db/spell-effect-insect-form-mantis.json
packs/data/spell-effects.db/spell-effect-insect-form-scorpion.json
packs/data/spell-effects.db/spell-effect-insect-form-spider.json
packs/data/spell-effects.db/spell-effect-monstrosity-form-phoenix.json
packs/data/spell-effects.db/spell-effect-monstrosity-form-purple-worm.json
packs/data/spell-effects.db/spell-effect-monstrosity-form-sea-serpent.json
packs/data/spell-effects.db/spell-effect-ooze-form-black-pudding.json
packs/data/spell-effects.db/spell-effect-ooze-form-gelatinous-cube.json
packs/data/spell-effects.db/spell-effect-ooze-form-gray-ooze.json
packs/data/spell-effects.db/spell-effect-ooze-form-ochre-jelly.json
packs/data/spell-effects.db/spell-effect-plant-form-arboreal.json
packs/data/spell-effects.db/spell-effect-plant-form-flytrap.json
packs/data/spell-effects.db/spell-effect-plant-form-shambler.json

These are interfering with the comparison between the PC's own attack modifier and the form's, and they're already squelched as needed

Remove `disableABP` flag from battle form effects

---

src/module/actor/character/document.ts
src/module/item/physical/document.ts
src/module/item/physical/usage.ts
src/module/rules/rule-element/base.ts
static/templates/actors/partials/carry-type.hbs

- An item with a "carried" usage is considered equipped so long as it's not dropped
- A dropped item is never counted as equipped or invested
- All REs are disabled for dropped items, even if they don't require equipping

Add support for "carried" usage, disable rule elements for dropped items

---

src/module/actor/base.ts
src/module/actor/party/document.ts
src/module/apps/sidebar/actor-directory.ts
src/scripts/hooks/load.ts
src/styles/ui/sidebar/_actor-directory.scss
static/templates/sidebar/party-document-partial.hbs
types/foundry/client/application/sidebar/sidebar-tab/sidebar-directory/base.d.ts
types/foundry/client/ui/index.d.ts
types/foundry/common/documents/actor.d.ts

Several ideas floated around for how to handle the case for where there exist multiple parties, but until we get more input from people who run such games this is currently the way I'd like to handle it.
So a new party list is created and injected during rendering into the actor list. This avoids us having to replace the sidebar template. The following scenarios are covered (unless I messed up somewhere):
1) Drag into party adds as member into party
2) Drag away from party removes as member
3) Party can be resorted (members are always alphabetical).
4) Right click party does what's intended
5) Right click a member of a party adds Remove Member to the options
6) Clicking on party icon opens the sheet. Clicking on the name collapses/hides the "folder".
7) Clicking on add actor on the party …

Render parties like folders in sidebar

---

src/module/rules/rule-element/base.ts

These were preventing getters from being accessed.

Remove V9 shims in RE bracket resolution

---

packs/data/ancestryfeatures.db/fangs.json

Add "slug" to Anadi fangs to trigger rule correctly.
If change language then "slug" for this item uses translated version and breaks other rules like effects

Add slug to Anadi fangs

---

packs/data/spell-effects.db/spell-effect-inscrutable-mask.json
packs/data/spells.db/inscrutable-mask.json

Closes https://github.com/foundryvtt/pf2e/issues/7626
Any suggestions for a better RollOption than "terrain:lighting:dimLightOrDarkness"?

Add effect for Inscrutable Mask

---

src/module/system/text-editor.ts

This is not really a bugfix, more making it slightly more user friendly. It's expanding the system to accept `@Check[type:Athletics]` or `@Check[type:Engineering Lore]` without causing issues where the skill isn't found. This fixes some problems with the AV module journals as they have capitalized skill names, but enabling lore skills without needing an explicit label is actually useful for the system.

Ensure inline type parameter is sluggified

---

src/module/item/affliction/data.ts
src/module/item/affliction/document.ts
src/module/item/affliction/sheet.ts
src/module/system/damage/types.ts
static/templates/items/affliction-details.hbs

Also refactors spell damage construction (though I'm still iffy on whether build should throw or warn and return null) and fixes some affliction issues.
Once we decide what the selectors should be, we can add retrieving modifiers and what-not.

Autoroll affliction damage on stage change

---

src/module/rules/rule-element/choice-set/rule-element.ts

This isn't documented and trips up users writing their own choice sets. We can look at linting system usage of it.

Loosen string format requirement of choice set flags

---

src/global.d.ts
src/module/item/sheet/base.ts
src/module/system/settings/index.ts

Data entry typically runs on production builds, so limiting it to dev build mode has it not reaching the target audience.

Add setting to control visibility of `refreshFromCompendium` buttons

---

src/module/encounter/combatant.ts

Before this fix, TempHP REs that use onTurnStart don't correctly refresh the character sheet

Render actor when rule elements have start of turn updates

---

src/module/actor/character/sheet.ts

Took me slightly longer than I said, but, first PR (to anything, ever, so if I did a bad let me know): fixed the dot

Include compendia from modules beginning with `pf2e` in early migrations

---

src/module/actor/character/document.ts
src/module/system/statistic/index.ts

Fixes inclusion of rank and ability properties, and prevents bad data when extending character skills and perception. Closes #7579.

Fix statistic extend data for initiative and spellcasting

---

packs/data/agents-of-edgewatch-bestiary.db/lie-master.json
packs/data/extinction-curse-bestiary.db/kimilekki.json
packs/data/feats.db/become-thought.json
packs/data/pathfinder-bestiary-3.db/hekatonkheires-titan.json
packs/data/pathfinder-bestiary-3.db/tidehawk.json
packs/data/pathfinder-bestiary.db/barghest.json
packs/data/pathfinder-bestiary.db/glabrezu.json
packs/data/pathfinder-bestiary.db/phoenix.json
packs/data/pfs-season-2-bestiary.db/onyx-alliance-agent-5-6.json
packs/data/pfs-season-2-bestiary.db/onyx-alliance-agent-7-8.json
packs/data/strength-of-thousands-bestiary.db/dimari-diji.json
src/scripts/config/index.ts
static/lang/en.json

Uses them for the appropriate npcs I could find.
Fixes #6361

Add frequencies for month and year.

---

src/module/item/spell/document.ts
src/module/system/damage/formula.ts
src/module/system/damage/weapon.ts

I'm a bit disgusted I had to hardcode. I could hardcode against the weapon-persistent slug instead.

Fix breakdown tag for weapon persistent damage

---

packs/data/feats.db/lifebloods-call.json

A bit kludgy and maybe we should consider stamping the condition values on the actor flags instead, which would clean this up and some other things that operate similarly.

Automate Lifeblood's Call

---

packs/data/agents-of-edgewatch-bestiary.db/skitterstitch.json
packs/data/bestiary-effects.db/effect-pest-haven.json
packs/data/pathfinder-bestiary-3.db/skinstitch.json

It's not clear whether the Skitterstitch should have the Flay and Stitch Skin actions ("These elite skinstitch variants have different attacks from the standard skinstitch, including a deadly poison."), so I've left the abilities in place for now.

Automate Skinstitch Flay damage. Add Pest Haven effect.

---

src/global.d.ts
src/module/apps/compendium-browser/data.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/action.ts
src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/compendium-browser/tabs/feat.ts
src/module/apps/compendium-browser/tabs/hazard.ts
src/module/apps/compendium-browser/tabs/spell.ts
src/module/system/settings/index.ts
src/styles/packs/_settings.scss
static/lang/en.json
static/templates/compendium-browser/browser-settings.hbs

This adds a new world setting, to save, which entries should to be displayed in the compendium browser by specifying wanted sources. For the GM a new section in the "Load Packs"/Settings page is added to set this up. By default this behaves as before, letting all entries show up.
In the bellow screenshots it shows the equipment tab before setting up the new settings, setting up the settings and then the filtered equipment list.
Equipment Before:
New Settings:
Equipment After, note the changed sources filter. Also the Alchemical Crossbow is not showing up anymore:
This mostly works, but there are at least the following issues:
It may be possible to add the new world setting to the existing CompendiumBrowserSettings. I'm not sure if that is the best idea, it would at least require a new …

Allow GM to select allowed sources for the compendium browser

---

src/module/system/predication.ts

Without this fix, this predicate fails:
```
"predicate": [
{
"lt": [
"self:size",
"target:size"
]
}
]
```
This is because in testBinaryOp(), domains contains:
self:size:2, self:size:medium, target:size:4, target:size:huge
This results in values of:
self:size: (2,NaN)
target:size: (4,NaN)
After this fix, the values are:
self:size: (2)
target:size: (4)

Prevent partial statements from including NaN in the values

---

src/module/actor/sheet/base.ts

I should have added a comment when I fixed this previously. It's not really obvious that the position in `activateListeners` matters for the drag & drop initialization.

Fix loot sheet inventory drag & drop with limited sheet permissions

---

src/module/actor/base.ts
src/module/actor/hazard/document.ts
src/module/actor/npc/document.ts
src/module/actor/types.ts
src/module/chat-message/helpers.ts
src/module/system/damage/iwr.ts
static/lang/en.json

Closes #7634 
Adamantine dagger treating the animated armor's hardness as half its actual value:

Implement damage reduction from hardness

---

src/module/actor/creature/sense.ts
src/scripts/config/index.ts
static/lang/en.json

Currently https://2e.aonprd.com/Feats.aspx?ID=3676 throws a warning since Thoughtsense isn't a valid sense

Add thoughtsense as a sense type

---

packs/data/equipment-effects.db/effect-energizing-lattice.json

Energizing lattice's additional damage should be predicated on the roll option being present

Add predicate to energizing lattice extra damage

---

src/scripts/macros/rest-for-the-night.ts

This is useful when you have multiple wands of the same type, allowing you to track them as a single item stack with multiple charges, or for homebrew wands with more than one charge.

Restore wands to max charges when resting rather than 1

---

src/module/actor/base.ts
src/module/apps/sidebar/chat-log.ts
src/module/chat-message/data.ts
src/styles/ui/sidebar/chat/_damage.scss
src/styles/ui/sidebar/chat/_index.scss
static/lang/en.json
static/templates/chat/damage/damage-taken.hbs

The Crucible damage reversion looked neat so I implemented it for the system.
This records all applied updates in a flag on the damage chat message and adds a new context menu entry to revert everything stored in the flag.
It handles hp, temp hp, stamina, etc. and also shield hp and all persistent damage effects that were created.
[revert-damage.webm](https://github.com/foundryvtt/pf2e/assets/41452412/a0e072e5-4227-4fb4-857b-b21b313faabe)
[revert-healing.webm](https://github.com/foundryvtt/pf2e/assets/41452412/eeb9f80e-e6b4-458c-b78f-b682962ecc2f)

Add a method to fully revert applied actor damage

---

src/module/actor/base.ts
src/module/chat-message/document.ts
static/templates/chat/damage/damage-taken.hbs

This makes more sense than checking permissions on chat message creation as everyone else ends up with the same message.

Fix revert damage button visibility

---

packs/data/blood-lords-bestiary.db/ghoul-antipaladin.json
packs/data/blood-lords-bestiary.db/seldeg-bheldis.json
packs/data/fists-of-the-ruby-phoenix-bestiary.db/tino-tung-level-13.json
packs/data/fists-of-the-ruby-phoenix-bestiary.db/tino-tung-level-9.json
packs/data/npc-gallery.db/antipaladin.json
packs/data/pathfinder-bestiary.db/horned-archon.json
packs/data/pathfinder-bestiary.db/lantern-archon-gestalt.json
packs/data/pathfinder-bestiary.db/lantern-archon.json
packs/data/pathfinder-bestiary.db/legion-archon.json
packs/data/pathfinder-bestiary.db/shield-archon.json
packs/data/pfs-season-3-bestiary.db/tyrannical-interrogator.json
packs/data/quest-for-the-frozen-flame-bestiary.db/lomok.json
packs/data/stolen-fate-bestiary.db/drustan.json
packs/data/strength-of-thousands-bestiary.db/wereant-sentinel.json

Set missed slug for NPC reactions
Retributive Strike, Glimpse of Redemption, Liberating Step, Iron Command, Selfish Shield, Destructive Vengeance
It's need to trigger these reactions with [module](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction)

Set missed slug for NPC reactions

---

src/module/actor/creature/sheet.ts
src/module/actor/sheet/base.ts
static/templates/actors/character/sidebar/initiative.hbs
static/templates/actors/character/sidebar/perception.hbs

The `.attribute-name` selector is only used for attribute checks in the NPC sheet now, and that has its own listener.

Refactor rolling perception checks from the character sheet to remove deprecation warning

---

src/module/apps/compendium-browser/index.ts
static/lang/en.json

This is needed with the length of the new source settings. I've added an info message because hitting save has no visible effect now.

Save scroll position of Compendium Browser settings and show a message when the settings were saved

---

src/styles/actor/character/_index.scss

Ensure inventory icons are 24px wide on PC sheet

---

src/module/rules/rule-element/choice-set/rule-element.ts

As per our conversation, I have been using the `inflateChoices` and `queryCompendium` methods on `ChoiceSetRuleElement` and would like them to be public.
Thanks

Make inflateChoices and queryCompendium public methods for ChoiceSetRuleElement

---

src/module/item/spell/data.ts
src/module/item/spell/document.ts
src/module/item/spell/sheet.ts

Some JQuery removal and type annotations kinda bloated it up a bit. I needed to do some sheet changes to catch every single gap.

Convert empty damage formulas to 0 during spell-data preparation

---

src/module/system/schema-data-fields.ts
types/foundry/common/data/fields.d.ts

An upstream exception will still be thrown for invalid data, but it will at least be a handled one.

Don't attempt data cleaning in `PredicateField`

---

src/module/migration/migrations/827-fix-tv-shield-traits.ts
src/module/migration/migrations/838-strike-attack-roll-selector.ts

Noticing some bad data appearing in user issue reports--probably from modules?

Add some sanity checks to pair of migrations

---

packs/data/equipment.db/class-kit-alchemist.json

Previously, it was impossible to actually add the alchemist kit to a character due to the missing item.

Remove obsolete sheath item from alchemist class kit

---

src/module/item/weapon/document.ts

Temporary measure until migration

Set `WeaponPF2e#system#ability` to `null` if not an ability abbreviation

---

src/module/item/abstract-effect/document.ts

Default origin to self if no origin was recorded

---

packs/data/equipment.db/blindpepper-bomb.json

This reverts commit 58f39957f9f4429beb4d9e80aa8f61c0b7fac450.
Blindpepper Bomb is a consumable.

Revert "Add "bomb" trait to Blindpepper Bomb (#8027)"

---

static/lang/en.json

It's either this or change the `slug` in `@system/statistic/armor-class.ts` to `ac`.

Fix attack roll result flavor showing `DC` instead of `AC`

---

src/module/migration/migrations/840-array-wrap-predicates.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/system/settings/index.ts

The system in part relied on Foundry's `ArrayField` for predicate validation, which is excessively loose: it will wrap anything that is not an array in one and declare it valid. The system is now stricter in its predicate validation, but some homebrew and modules had previously-coerced/validated predicates that are now invalid.

Migrate predicates that are not arrays

---

src/module/actor/sheet/popups/ability-builder.ts
src/module/item/ancestry/document.ts
src/styles/actor/character/_ability-builder.scss
static/lang/en.json
static/templates/actors/character/ability-builder.hbs

Representing the data as a row of buttons reduces the amount of logic the template has to perform. Also converted some the divs to more fitting elements while I was at it.
This should wait until work on 5.0 starts. After this I'll do some tweaks for voluntary flaws and and try to remove the remaining invisible buttons.

Reduce sheet-side logic in ability builder template

---

build/lib/extractor.ts

Labels are removed when they are identical to their respective document names

Conditionally remove @UUID link labels on extract

---

src/module/system/text-editor.ts
src/scripts/ui/inline-roll-links.ts
static/lang/en.json

(Per request of @TMunsie)
This allows using syntax like `@Check[type:athletics,acrobatics]` to create two rollable buttons at once. When this syntax is used, there are a few changes:
- The rollable buttons are created in a new block of text (div) rather  than inline, with each button occupying a single line.
- The rollable buttons are "grouped", and posting one to chat will post  all of the buttons to chat.
- The post to chat button uses a different icon (`fa-comment-alt-dots`) to  indicate the buttons are grouped. 
Otherwise, everything else works the same. Parameters and display text are applied to all rollable buttons, with the exception of the `adjustment` parameter, which has also been enhanced in this PR. The `adjustment` parameter can now be applied to fixed DCs (rather than just …

Add shorthand syntax for multiple rollable check buttons

---

src/global.d.ts
src/module/actor/party/data.ts
src/module/actor/party/document.ts
src/module/actor/party/invalid-campaign.ts
src/module/actor/party/kingdom/data.ts
src/module/actor/party/kingdom/helpers.ts
src/module/actor/party/kingdom/index.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/values.ts
src/module/actor/party/types.ts
src/module/apps/sidebar/actor-directory.ts
src/module/system/settings/index.ts
static/lang/en.json

This PR creates a method to define and initialize extended party campaign data. The idea is that when kingmaker is enabled, the party will initialize a data model during data preparation. This object can be used by the sidebar to inject additional buttons into the side.
The campaign data is stored in system.campaign. This sort of structure makes it so that a party can only have a single campaign data extension. To prevent corruption, it checks for type mismatches during data preparation, and shows a warning (with an opportunity to delete data) if said corruption occurs.
The ability to register additional campaign types will be done at a later date. I was more interested in solving the data structure than the needs for campaigns we may or may not eventually support. The crown party button …

Add initial kingdom model and extended campaign data support

---

packs/data/feat-effects.db/effect-curse-of-living-death.json
packs/data/feat-effects.db/effect-curse-of-the-heros-burden.json

Closes https://github.com/foundryvtt/pf2e/issues/8084

Fix missing extreme for Curse of Living Death and Curse of the Hero's Burden

---

src/module/item/affliction/document.ts
src/module/item/spell/document.ts
src/module/item/spell/helpers.ts
src/module/system/damage/formula.ts
src/module/system/damage/types.ts

Theoretically we could make the base damage loop not an if/else but I'm a bit concerned about changing that at this time.

Fix base damagetype and diesize lookup for 0 base damage

---

src/module/rules/rule-element/damage-dice.ts
src/module/system/damage/formula.ts
src/module/system/damage/weapon.ts

The bugfix half of it is that a `diceNumber` override of zero _wasn't_ permitted but would slip through if a `dieSize` override was also present.

Explicitly allow damage dice overrides of zero `diceNumber`

---

src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts

This isn't currently used in the system, but some modules peek at it for their own features

Fix breakdown data of NPC land speeds

---

static/lang/re-en.json

If this PR is accepted, it will correct success message for Wellspring Surge to be 3 rounds instead of 1 minute.

Correct success message for Wellspring Surge to be 3 rounds

---

src/module/actor/character/sheet.ts
static/templates/actors/character/tabs/actions.hbs

The part that's a bugfix is data-item-summary-id. This bug occured when we converted item summaries from jquery. The rest is preparation for some work on exploration actions.
This does make it possible to have exploration activities with an action cost (where before it would always put under encounter) but if anyone does that they can have their sillyness.
Can wait for V11.

Refactor action rendering and maintain summary expanded state

---

static/templates/actors/character/tabs/actions.hbs

In V11 the tab css class is required on all content divs.

Restore navigation of PC actions

---

src/module/canvas/measured-template.ts
src/module/chat-message/data.ts
src/module/chat-message/document.ts
src/module/item/base.ts
src/module/item/spell/document.ts
src/module/scene/measured-template-document.ts
src/module/system/check/check.ts
src/module/system/damage/damage.ts

There are currently 3 different versions of `flags.pf2e.origin` for storing/retrieving an item:
- ChatMessage contains the full item data, correctly applying spell overlays (variant/heighten) when retrieving the item
- Check/Damage only stores the item uuid, making it impossible to fetch the full item with that message alone
- `SpellPF2e.createTemplate` has its own completely different format
This PR is my attempt at unifying the creation of (and retrieval from) `flags.pf2e.origin`. This would fix #2122 (to check another box in #4882).

Move cast level and spell variant info to origin flag

---

build/lib/compendium-pack.ts
build/lib/extractor.ts
build/lib/helpers.ts
build/lib/level-database.ts

`_folders.json`:
```json
[
{
"_id": "9yPIhYbJgpWehmoK",
"color": null,
"flags": {},
"folder": null,
"name": "Depth 1",
"sort": 0,
"sorting": "a",
"type": "Actor"
},
{
"_id": "nreMN2PeB99ghBdO",
"color": null,
"flags": {},
"folder": "vBrUjiFDMIvq7pqX",
"name": "Depth 3",
"sort": 0,
"sorting": "a",
"type": "Actor"
},
{
"_id": "vBrUjiFDMIvq7pqX",
"color": null,
"flags": {},
"folder": "9yPIhYbJgpWehmoK",
"name": "Depth 2",
"sort": 0,
"sorting": "a",
"type": "Actor"
}
]
```

Support embedded compendium folders in pack scripts

---

static/templates/sidebar/compendium-directory.hbs

Before (core placeholder):
After:

Restore system placeholder for compendium search input

---

src/styles/legacy/_chat.scss
src/styles/ui/sidebar/chat/_index.scss

This has always been problematic and is no longer tenable with V11's "Jump to Bottom" feature

Remove global style overrides for chat log

---

src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/iwr/base.ts

This is to allow predicates to include statements that are added later in derived data preparation

Move IWR RE processing to `afterPrepareData` callback

---

src/module/actor/base.ts

I have no idea why it worked at all with the post-update actor data 🤔

Fix damage reversion of numeric-only damage

---

build/lib/compendium-pack.ts

See https://github.com/foundryvtt/foundryvtt/issues/9590

Restore `effects` property of items and actors in the pack builder

---

packs/feats/holy-castigation.json

I'll turn these into names on extract to prevent this in the future.

Fix ephemeral effect transmitted by Holy Castigation feat

---

packs/classfeatures/twisting-tree.json

Using an override has the system not consider it to be an upgrade, which allows for increase stacking

Fix Twisting Tree damage die upgrade

---

packs/agents-of-edgewatch-bestiary/clockwork-chopper.json
packs/agents-of-edgewatch-bestiary/clockwork-injector.json
packs/agents-of-edgewatch-bestiary/daemonic-skinner.json
packs/agents-of-edgewatch-bestiary/gage-carlyle.json

Add resistances and weaknesses to Clockwork Chopper and Clockwork Injector. Fix Daemonic Skinner's Spell Choke DC.
Fix broken links in Gage Carlyle's Charming Liar and Smooth Operator.
Closes https://github.com/foundryvtt/pf2e/issues/8189

Fix some Agents of Edgewatch NPCs

---

packs/classfeatures/deity.json
src/module/rules/rule-element/choice-set/data.ts
src/module/rules/rule-element/choice-set/rule-element.ts
types/foundry/client/data/collections/compendium-collection.d.ts
types/foundry/common/types.d.ts

Sample implementation with the cleric's deity class feature. We'll need to convert the rest, but the `allowedDrops` predicates should be helpful (before getting removed in some cases).

Replace ChoiceSet pack queries with index lookups and predicate testing

---

.gitignore
build/clean.ts
build/lib/compendium-pack.ts
package.json
vite.config.ts

static/packs will need to be deleted from people's machines for builds to work properly after this. Perhaps I should delete it just in case?
After this static files are not deleted (only overwritten) between refreshes in npm run watch, but they are deleted when `npm run watch` or `npm run build` is ran. Perhaps that is fine.

Fix npm run watch crashes when updates are made while a world is running

---

src/module/scene/token-document/document.ts
types/foundry/client/data/documents/token-document.d.ts
types/foundry/common/documents/token.d.ts

going to need to investigate how to restore this (assuming it's still necessary)

Remove override of no-longer-existing _onUpdateTokenActor

---

src/module/canvas/layer/template.ts
types/foundry/client/pixi/placeables-layer/base.d.ts

This fixes manual drawing of `MeasuredTemplate`s

Fix `TemplateLayerPF2e#_onDragLeftMove`

---

src/module/actor/inventory/index.ts
src/module/apps/compendium-browser/index.ts

Closes #8014.
Only stacks with items at the top level. We may or may want the logic to include items in containers, but this will impact other system features.

Stack items acquired or purchased from the compendium browser

---

packs/classfeatures/muscular-exoskeleton.json
packs/classfeatures/otherworldly-protection.json
packs/classfeatures/subtle-dampeners.json

This changes Muscular Exoskeleton and Subtle Dampeners to depend on crafting rank and not athletics. It also changes Otherworldly Protection to give positive resistance when the character has negative healing.

Fix minor issues with some armor modifications

---

src/module/item/spell/document.ts

Fixes #8328. In the future it would be nice to replace most sheet actor.items.get() calls with something that handles up-leveling so we're not doing any of this stuff in the documents.
While this error affects message.item, it didn't seem to affect variants at all. Interesting.

Fix heighten level when retrieving spells from chat message

---

src/module/migration/runner/base.ts
src/module/migration/runner/index.ts
tests/mocks/actor.ts
tests/module/migration.test.ts

After some testing I was able to confirm that embedded items can be created and updated on synthetic actors in the same way as world actors.

Trim down migration runner handling of synthetic actors & AEs

---

packs/pathfinder-bestiary/bunyip.json
packs/pfs-season-2-bestiary/saddleback-bunyip.json
src/scripts/config/traits.ts
static/lang/re-en.json

Minor issue is that I couldn't use  GrantItem to grant Compendium.pf2e.bestiary-ability-glossary-srd.Item.Grab, even with "reevaluateOnUpdate": true. Not sure if it's an issue, given that the grab ability is emitted to chat when applicable anyway. If desired, we could just add the ability to the NPCs.
If accepted, "Effect: Crocodile Form" and "Effect: Snake Form" can be added to the migration/deletion list.

Update Bunyip Shift Form from effect to RollOption with suboptions

---

src/module/rules/rule-element/battle-form/rule-element.ts

The label ended up as an empty string when `strikeData.label` is undefined. That was one of the last things I changed and I forgot to test it. 😭

Fix strike label in `BattleFormRuleElement`

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/chat-message/data.ts
src/module/chat-message/helpers.ts
src/styles/ui/sidebar/chat/_damage.scss
static/templates/chat/damage/damage-taken.hbs

```json
{
"key": "FlatModifier",
"selector": "healing-received",
"value": 5,
"predicate": [
{
"or": [
"action:treat-wounds",
"action:battle-medicine"
]
}
]
}
```
```json
{
"key": "Note",
"selector": "healing-received",
"text": "You recover an additional 5 Hit Points from a successful attempt to Treat your Wounds or use Battle Medicine on you. After you or an ally use Battle Medicine on you, you become temporarily immune to that Battle Medicine for only 1 hour, instead of 1 day.",
"title": "{item|name}",
"predicate": [
{
"or": [
"action:treat-wounds",
"action:battle-medicine"
]
}
]
}
```

Limited support for target-specific healing received modifiers and roll notes

---

build/lib/compendium-pack.ts
build/lib/extractor.ts
build/lib/level-database.ts
src/module/macro.ts
types/foundry/client/data/documents/macro.d.ts
types/foundry/common/documents/macro.d.ts

The method was made #private in V11, so we're locked out.

Remove `Macro` script execution override, add `MacroSchema` type

---

packs/spells/thoughtful-gift.json

"Thoughtful Gift" gains the Exploration trait when cast, as its cast time of "1 (up to 3 if heightened)" is treated as unstructured.
~~Changed to 1 action to match the PDF.~~
Changed to "1 to 3".

Fix cast time of Thoughtful Gift

---

src/module/item/deity/document.ts
src/module/item/deity/sheet.ts

Also exclude apocryphal domains from list but then include as selectable for feats like Domain Initiate

Bump max domains settable from deity sheet to 6

---

packs/pathfinder-bestiary/ofalth.json

The effect should apply to all creatures in the aura, also this thing is missing the olfactory trait and I'm tempted to correct that glaring Paizo omission.

Automate Ofalth aura

---

src/module/actor/party/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/styles/actor/_nav.scss
static/lang/en.json
static/templates/actors/party/regions/inventory-members.hbs

On the inventory tab of the party, open the inventory tab of the character.
I could move the implementation to an openTab() function on the character sheet that can be overriden to handle sub tabs (will be useful for exploration) but I'll get to that when it comes time to get to that.
render() is not an async function, so this isn't something we can do from the party sheet without resorting to hooks.

Open inventory tab for party members on inventory tab

---

src/module/data.ts
src/module/migration/runner/base.ts
src/module/migration/runner/index.ts

This is unfortunately causing deltas to bloat due to timestamps having differences of milliseconds

Refrain from recording timestamps on migration records

---

src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/battle-form/schema.ts
src/module/system/schema-data-fields.ts
types/foundry/common/data/fields.d.ts
types/foundry/common/data/validation-failure.d.ts

Includes a sample implementation in the battle form rule element.
Validation error:
`keys` option set to `["test"]`:

Add a `RecordField` that handles `Record<string, DataField>` data

---

src/module/actor/inventory/bulk.ts
src/module/item/physical/bulk.ts
static/lang/en.json
static/templates/actors/character/tabs/inventory.hbs

Also improve localization
This information is redundant in the encumbrance display, and I've seen two users confused by it within a few days of each other.
Before:
After:

Remove "light overflow" from encumbrance bar on PC sheet

---

src/scripts/hooks/canvas-ready.ts

It _seems_ this is no longer needed in V11.

Remove token redraws in canvasReady hook

---

src/module/actor/base.ts
src/module/scene/token-document/document.ts
src/scripts/hooks/canvas-ready.ts
types/foundry/client/data/documents/token-document.d.ts

V11 made it possible to trim down and consolidate system handling of token re-renders from actor updates

Move token re-renders from actor updates to new designated location

---

src/module/collection/actors.ts

This allows game.actors.party to retrieve the active party.

Add getter placeholder for active party

---

src/module/actor/base.ts
src/module/actor/party/document.ts
src/module/actor/party/types.ts
src/module/item/base.ts

We could allow `@details` without deprecation warning if you think that'd be better.

Include actor roll data in item roll data

---

src/module/canvas/token/object.ts

A further improvement would be to make the LoS polygon a composite of circles at multiple origin points, but it'll be harder to get to the client code that creates the polygon.
This isn't in reference to an explicit vision rule but related to a diagram explaining cover rules: it is assumed that Kyra _can_ (barely) see the ogre.
Before:
After:
Reference: https://2e.aonprd.com/Images/Rules/Rules459.png

Adjust token-visibility testing to be more compliant with 2e rules

---

src/module/encounter/document.ts
static/system.json

Also extend `Combat#_manageTurnEvents` workaround to 11.305

Indicate verified compatibility with 11.305

---

src/module/canvas/token/object.ts
types/foundry/client/pixi/placeables/token.d.ts
types/foundry/common/documents/token.d.ts

Obscure token sprite if hearing/tremorsense detection filter is applied

---

src/module/rules/rule-element/fixed-proficiency.ts
src/module/rules/rule-element/lose-hit-points.ts
src/module/rules/rule-element/martial-proficiency.ts

Tested with:
`FixedProficiency` -> `Spell Effect: Object Memory (Weapon)`,
`LoseHitPoints` -> `Drained`,
`MartialProficiency` -> `Dwarven Weapon Familiarity` (Harsk lvl 5) and  `Gunslinger` Class

Add schemas to `FixedProficiencyRuleElement`, `LoseHitPointsRuleElement` and `MartialProficiencyRuleElement`

---

src/module/apps/compendium-browser/data.ts
src/module/apps/compendium-browser/index.ts
static/templates/compendium-browser/settings/pack-settings.hbs

Because of the new ability to add folders for compendia, and to give each compendium a distinct banner, peeps have started to name their compendia simpler and more to-the-point.
This PR just makes it so that the origin package where the pack comes from is added  to the end of the checkbox label on the Settings tab, so you know which of the several dozen "Feats" you're actually toggling on.

Add pack's source package after its name in brackets on the Compendium Browser's Settings tab

---

src/module/rules/rule-element/multiple-attack-penalty.ts
src/module/rules/rule-element/roll-twice.ts
src/module/rules/rule-element/sense.ts

Tested with:
`MultipleAttackPenaltyRuleElement` -> `Flurry` (Harsk Level 5),
`RollTwiceRuleElement` -> `Effect: Black Cat Curse` and `Spell Effect: True Strike`,
`SenseRuleElement` -> `Spell Effect: One With the Land` and `Dwarf` class (Harsk Level 5)

Add schemas to `MultipleAttackPenaltyRuleElement`, `RollTwiceRuleElement` and `SenseRuleElement`

---

src/module/rules/rule-element/token-effect-icon.ts
src/module/rules/rule-element/token-image.ts
src/module/rules/rule-element/token-light.ts
src/module/rules/rule-element/token-name.ts
src/module/rules/rule-element/weapon-potency.ts

The last batch. Tested with:
`TokenEffectIconRuleElement` -> `Torch`,
`TokenImageRuleElement` -> Manually (unused in the system),
`TokenNameRuleElement` -> Manually (unused in the system),
`TokenLightRuleElement` -> `Torch`,
`WeaponPotencyRuleElement` -> `Spell Effect: Magic Fang`

Add schemas to `TokenEffectIconRuleElement`, `TokenImageRuleElement`, `TokenNameRuleElement`, `TokenLightRuleElement` and `WeaponPotencyRuleElement`

---

types/foundry/client/pixi/helpers/index.d.ts
types/foundry/client/pixi/helpers/quadtree.d.ts
types/foundry/client/pixi/placeables-layer/base.d.ts
types/foundry/client/pixi/placeables-layer/drawings-layer.d.ts
types/foundry/client/pixi/placeables-layer/lighting-layer.d.ts
types/foundry/client/pixi/placeables-layer/notes-layer.d.ts
types/foundry/client/pixi/placeables-layer/sounds-layer.d.ts
types/foundry/client/pixi/placeables-layer/template-layer.d.ts
types/foundry/client/pixi/placeables-layer/tiles-layer.d.ts
types/foundry/client/pixi/placeables-layer/token-layer.d.ts
types/foundry/client/pixi/placeables-layer/walls-layer.d.ts

`CanvasQuadtree` is just a `Quadtree` that returns `canvas.dimensions.rect` as its `bounds`.

Add types for `Quadtree` and `CanvasQuadtree`

---

src/module/actor/character/crafting/helpers.ts
src/module/actor/creature/sheet.ts
src/module/actor/sheet/helpers.ts
src/module/actor/sheet/popups/casting-item-create-dialog.ts
src/module/chat-message/document.ts
src/module/item/base.ts
src/module/item/consumable/spell-consumables.ts
src/module/item/deity/sheet.ts
src/module/item/spell/document.ts
src/module/item/spell/sheet.ts
src/module/item/spellcasting-entry/collection.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/trick.ts
src/module/item/spellcasting-entry/types.ts
src/module/scene/measured-template-document.ts
src/module/system/statistic/index.ts
static/templates/chat/spell-card.hbs

I took care to not yet rename anything that is a key in an object passed to a template.

Start process of referring to spell levels as ranks

---

packs/equipment/lethargy-poison.json

Fixed an incorrect trait of Lethargy Poison.

Update traits for Lethargy Poison to change conjuration to consumable

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/creature/document.ts
src/module/actor/party/document.ts
src/module/actor/vehicle/document.ts
src/module/item/action/document.ts
src/module/item/affliction/document.ts
src/module/item/base.ts
src/module/item/condition/document.ts
src/module/item/effect/document.ts
src/module/item/feat/document.ts
src/module/item/kit/document.ts
src/module/item/physical/document.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/weapon/document.ts
types/foundry/client/data/documents/active-effect.d.ts
types/foundry/client/data/documents/actor.d.ts
types/foundry/client/data/documents/chat-message.d.ts
types/foundry/client/data/documents/scene.d.ts
types/foundry/client/data/documents/token-document.d.ts
types/foundry/common/abstract/document.d.ts
types/foundry/common/documents/active-effect.d.ts
types/foundry/common/documents/actor.d.ts
types/foundry/common/documents/fog-exploration.d.ts
types/foundry/common/documents/macro.d.ts

They can now return `Promise<boolean | void>`.

Update `Document#_pre(Create|Update|Delete)` return types for V11

---

src/module/item/action/sheet.ts
static/template.json

Also removed code that wasn't doing anything (since the sheet's image is the source item). Characters use the action cost as the action icon regardless of the action's item image.

Fix default ability action cost

---

build/run-migration.ts

Should lead to no behavior changes currently but required for kingmaker stuff to work. Also organize all top level imports.

Support folders in run-migration

---

src/scripts/macros/raise-a-shield.ts

While the `raiseAShield` action prevents the use of the shield when it is `broken`, it doesn't prevent it when it is `destroyed`, so i just added the condition and warning into the action.
The `isBroken` getter specifically avoid returning `true` when the shield is destroyed.

Add isDestroyed check to the raiseAShield action

---

packs/feat-effects/effect-unleash-psyche.json

"Your Psyche remains Unleashed for 2 rounds"
Effect currently has duration 2 and expire at turn-end.
If you unleash on Round 2, it will expire at the end of round 4 meaning you are unleashed for rounds 2,3 & 4, which is too long.
Setting to turn-start means you are unleashed for rounds 2 & 3 only.

fix expiry for unleash psyche effect

---

src/module/apps/compendium-browser/tabs/data.ts
src/module/apps/compendium-browser/tabs/spell.ts

No longer usable since schools aren't part of index data

Remove spell school filter from compendium browser

---

src/module/system/damage/roll.ts

This allows any `@` stuff to work in spells again. This is the same regex substitution foundry does in their own roll validation function.

Fix spell validation for spells with roll data

---

src/module/actor/base.ts
src/module/actor/creature/data.ts
src/module/actor/creature/document.ts
src/module/item/armor/document.ts
src/module/item/base.ts
src/module/item/physical/document.ts
src/module/rules/rule-element/item-alteration/alteration.ts
src/module/rules/rule-element/item-alteration/rule-element.ts
src/module/rules/rule-element/item-alteration/schemas.ts
static/lang/en.json
static/templates/items/armor-details.hbs

It ended up being a tight-rope walk to generate the expected results: current HP must be proportionally adjusted but also reduced back down if a max-HP increase goes away for whatever reason.

Add management of physical-item max HP alterations

---

src/scripts/ui/inline-roll-links.ts

This *might* also have beneficial effects for ROE stuff, since it enables item retrieval and item roll options for everything. I don't know for sure though. I *think* this can be opened up to non-saves as well, but I want to be sure we need that first.
We can do weapons as well once roll notes can refer to their origin item (so stunning fist no breaky).
Feats use actor level for incapacitation (in StatisticCheck#roll()) so those continue to work just fine. 
I tested with the Drover's Band (beware AV spoilers).

Enable incapacitation trait for physical non-weapon items

---

packs/feat-effects/effect-curse-of-ancestral-meddling.json
packs/feat-effects/effect-curse-of-creeping-ashes.json
packs/feat-effects/effect-curse-of-engulfing-flames.json
packs/feat-effects/effect-curse-of-living-death.json
packs/feat-effects/effect-curse-of-outpouring-life.json
packs/feat-effects/effect-curse-of-the-heros-burden.json
packs/feat-effects/effect-curse-of-the-perpetual-storm.json
packs/feat-effects/effect-curse-of-the-skys-call.json
packs/feat-effects/effect-curse-of-torrential-knowledge.json
packs/feat-effects/effect-curse-of-turbulent-moments.json
packs/feats/oracle-dedication.json

- Alter in-memory condition grants for Cosmos and Time curses
- Prevent effects of moderate-stage curses from applying to characters without the oracle class
- Have the Oracle Dedication feat impose flat-footed at the moderate curse stage

Touch up oracular curses with stupid RE tricks

---

packs/feats/adopted-ancestry.json
packs/feats/ancestral-paragon.json
packs/heritages/half-elf.json
packs/heritages/half-orc.json
src/module/actor/character/data.ts
src/module/item/ancestry/document.ts

The `countsAs` array is no longer usable now that we're no longer able to make NeDB queries, so the additional traits fed into Ancestal Paragon need to be more statically defined.

Fix Ancestral Paragon choice set and underlying data availability

---

packs/conditions/encumbered.json
src/global.d.ts
src/module/actor/creature/document.ts
src/module/actor/creature/helpers.ts
src/module/system/settings/automation.ts
static/lang/en.json

Disabled by default to assess tension with current inventory practices among users

Add encumbrance automation

---

src/module/actor/party/document.ts

The copy paste is a bit shameful but the alternative is physical items be party aware and that's even more shameful.

Skip physical items for party rule elements

---

packs/stolen-fate-bestiary/blood-pear-tree.json

Closes https://github.com/foundryvtt/pf2e/issues/8880

Fix name for Blood-Pear Tree's Bloody Pear and remove Blight ability

---

packs/feat-effects/effect-curse-of-ancestral-meddling.json

Specifically downtime & exploration actions, as well as initiative rolls (need to add roll option for that)

Exclude ancestors curse flat-check notes from some rolls

---

src/module/item/spell/document.ts

> Increase the damage of its Strikes and other offensive abilities by 2. If the creature has limits on how many times or how often it can use an ability (such as a spellcaster’s spells or a dragon’s Breath Weapon), increase the damage by 4 instead. 
While it says "spells" universally, the context is for limited use abilities.

Fix elite/weak adjustment for cantrips

---

src/module/system/action-macros/helpers.ts
src/scripts/ui/inline-roll-links.ts
static/lang/action-en.json

The action header will be used if the check is against a defense and the originating item is an encounter action.

Use action header in messages for some inline check vs defenses

---

packs/iconics/sajan-level-1.json
packs/iconics/sajan-level-5.json
packs/iconics/seelah-level-5.json
packs/iconics/valeros-level-5.json

It appears there was a bad migration on these 4 Iconics and some of their ability boosts fell off at some point.

Add missing ability boosts for 4 Iconics.

---

src/module/system/damage/helpers.ts
src/module/system/text-editor.ts

There might be a better way to do the intermediate term stuff, I'm all ears.
This falls back to regular formula handling if there's an error or if there is an`@actor` term anywhere and the rolldata doesn't provide one (which would just render 0 damage otherwise).

Parse @Damage with intermediate expressions + fallback in some cases

---

src/module/actor/character/data.ts
src/module/actor/character/document.ts
src/module/actor/character/sheet.ts
src/module/actor/creature/data.ts
src/module/actor/data/base.ts
src/module/actor/sheet/popups/manage-attack-proficiencies.ts
src/module/migration/migrations/602-update-diehard-feat.ts
src/module/migration/migrations/605-catch-up-to-template-json.ts
src/module/migration/migrations/612-normalize-rarities.ts
src/module/migration/migrations/620-rename-to-webp.ts
src/module/migration/migrations/651-ephemeral-focus-pool.ts
src/module/migration/migrations/653-aes-to-res.ts
src/module/migration/migrations/682-biography-fields.ts
src/module/migration/migrations/686-hero-points-to-resources.ts
src/module/migration/migrations/710-rarity-to-string.ts
src/module/migration/migrations/711-heritage-items.ts
src/module/migration/migrations/712-actor-shield-structure.ts
src/module/migration/migrations/722-crafting-system-data.ts
src/module/migration/migrations/743-fix-weakness-structure.ts
src/module/migration/migrations/774-unpersist-crafting-entries.ts
src/module/rules/synthetics.ts
src/module/system/settings/homebrew/helpers.ts
static/template.json

As part of the split from `CharacterSystemData`, refactor some runtime code (mostly old migrations) and prune some unneeded properties from template.json.

Add separate `CharacterSystemSource` type

---

src/module/item/action/document.ts

Most people can only die once, which makes dying a limited and valuable resource.

Make death note abilities compute correct npc adjustments

---

src/module/actor/npc/document.ts

Without this change, in statistic/index.ts:147 this.ability is null, and so the casting modifier is not propagated to the drag handler.
For an example, cast "False Life" from an NPC and drag the effect onto them.

Set the ability on the NPCs casting statistic

---

src/module/actor/initiative.ts
src/module/encounter/document.ts

Currently if multiple combatants have the same world actor, initiative can only be rolled for the first in the list. I don't actually know of any use case for this scenario, but core allows it to function.

Fix rolling initiatives for multiple combatants with common world actor

---

src/styles/system/_effects-panel.scss

Further-enlarged font and widened total area
Before:
After:

Tweak style of item descriptions in effects panel

---

src/scripts/config/index.ts
static/lang/en.json

Paizo used both spellings in the book, but the glossary uses this one so we should go with that.

Fix spelling of Sussuran language

---

src/module/actor/party/document.ts
src/module/actor/party/sheet.ts
src/module/item/base.ts
static/templates/actors/party/sheet.hbs
static/templates/sidebar/party-document-partial.hbs

Fixes RK button not working for players, party folder closing when members are updated, and kingmaker stale folder bugs.
Casting `this` is a crime, but without that typescript complains that the type is infinitely recursive.

Fix more party sheet bugs

---

src/module/actor/character/document.ts

This was already a breaking change with the removal of ability scores, so it might as well be right!

Fix prefix of PC attribute roll options

---

src/module/actor/party/document.ts
src/module/actor/party/sheet.ts
src/module/system/settings/metagame.ts
src/styles/actor/party/_index.scss
src/styles/actor/party/_overview.scss
static/templates/actors/party/regions/exploration.hbs
static/templates/actors/party/regions/inventory-members.hbs
static/templates/actors/party/regions/overview.hbs
static/templates/actors/party/sheet.hbs

* Swap exploration and inventory (so that exploration is the first tab if stats are disabled)
* Show health bar (without values) if stats (aka overview) is disabled
* Show an individual's stats regardless of setting if the user is an observer (instead of an owner)
* Show party stats setting is now visible in production worlds if a party actor exists (since its very near ready to release)
* Fix overview health bar alignment
* Fix pointer showing in places clicking would have no effect (due to permissions)
* Fix party members not properly getting removed from their original folder before transfer

More party sheet tweaks and fixes

---

src/module/system/statistic/index.ts

This could definitely use a refactor at this point, but just to get impulse attacks showing up more-or-less correctly

Inform `Statistic` of targeted class-statistic checks

---

src/module/scene/token-document/document.ts

In our testing we noticed an issue when attempting to re-import AV. I had already spent the time to track down the issue so I thought I might submit a PR for it rather than simply log a report. Apologies if I've missed some additional process required.
The repro steps for the issue are to attempt to re-import any adventure that contains Scenes and Actors over the already-imported adventure.
The root cause is that foundry tracks all dependent TokenDocument instances for a given Actor, which in this case includes the TokenDocument instances that are created when the Adventure Document is initialised. I realise this is potentially surprising behaviour but there are good reasons that foundry tracks all dependents rather than just some of them.
These TokenDocuments have parents that are …

Tolerate TokenDocument instances having BaseScene parents in _onRelatedUpdate

---

src/module/chat-message/listeners/cards.ts

#8976 consolidated the chat card action button names, but left the old "save" action in the permission check.
Checking against the new "spell-save" action name allows non-GMs to roll saves against a spell card owned by another player

Fix spell-save button in chat cards

---

src/module/system/text-editor.ts

This avoids the need for the max(1, formula) hack and also makes most formulas prettier in unowned items.

Assume actor is level 1 in @Damage instead of skipping

---

src/module/actor/party/data.ts
src/module/actor/party/document.ts
src/module/actor/party/sheet.ts
static/lang/en.json
static/templates/actors/party/regions/exploration.hbs
static/templates/actors/party/regions/overview.hbs

On request, this introduces a skills summary. Given a skills summary now exists, the number of "best skills" has been reduced to 4.

Fix party sheet speeds and update summary

---

src/module/item/action/document.ts
src/module/item/action/helpers.ts
src/module/item/action/sheet.ts
src/module/item/campaign-feature/document.ts
src/module/item/campaign-feature/sheet.ts
src/module/item/feat/document.ts
src/module/item/feat/sheet.ts

Feats embed actions (and so do campaign features) so its only right that they reach into actions to do the action stuff.
Eventually we can get spells also using action cost utilities, once we refactor actions/feats to both support variable action costs somehow.

Consolidate action/feat duplicate code into helpers

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/rules/rule-element/aura.ts

A level set in an Aura RE will be propagated to the effects the aura transmits.

Allow Aura RE to include effect level

---

src/scripts/config/traits.ts

Fix the bug that caused "Composite" trait to not show a proper description.
Bug was caused by omission of "PF2E." in the map in traits.ts.
Fixes #9102

Fix bugged description for Composite trait

---

src/module/item/physical/runes.ts

Loot actors are always level 0, so currently they never show any property runes due to lack of attack potency

Show all property runes on ABP magic items embedded in loot actors

---

packs/stolen-fate-bestiary/the-shadow-prince.json

Remove Persistence of Memory ability from Shadow King's statblock to match module: https://2e.aonprd.com/Monsters.aspx?ID=2559

Remove Persistence of Memory ability from Shadow King's statblock

---

src/module/actor/character/document.ts
src/module/actor/character/types.ts
src/module/actor/creature/document.ts

- "spell" and "spell-attack": highest spellcasting statistic as measured by attack modifier
- "spell-dc": highest spellcasting statistic as measured by DC
- "class-spell": highest among all class and spellcasting statistics
- "class" and "class-dc": alias of "classDC"

Add more class/spell search options to `ActorPF2e#getStatistic`

---

src/module/item/affliction/document.ts
src/module/item/condition/document.ts

There are two known issues:
1) The current "lock" solution doesn't work for effects, and we're going to need something more standardized. However, I'm short on ideas. grantedBy's mechanism only works if we have itemGrants data in the affliction, which we probably shouldn't.
2) isLocked doesn't prevent condition updates nor deletions. I'll need to handle this separately.

Grant conditions when affliction stage changes

---

src/module/chat-message/listeners/cards.ts

This was part of the initial development and leftover after changing to use the "hidden" class.

Remove errant leftover setting of clear-template-buttons display style

---

packs/abomination-vaults-bestiary/barcumbuk.json
packs/abomination-vaults-bestiary/drill-field-barbazu.json
packs/abomination-vaults-bestiary/hellforge-barbazu.json
packs/abomination-vaults-bestiary/torture-chamber-barbazu.json
packs/pathfinder-bestiary/erinys.json

Adventure text makes it clear that the flaming rune is intended to be on the NPC strike.

Update rule elements on several AV actors

---

src/styles/actor/party/_index.scss

Before: barely visible numbers on edge of exploration/inventory sidebars
After: no more numbers

Remove numbers from party sheet sidebars

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/npc/data.ts
src/module/actor/npc/document.ts
src/module/actor/sheet/spellcasting-dialog.ts
src/module/item/spellcasting-entry/document.ts
static/templates/actors/spellcasting-dialog.hbs

Main concern I have is if its ok to run spellcasting preparation after "afterPrepareData()".
After this the gate attenuator will work for kineticist item casting. And theoretically we can make extend statistics like "wizard spellcasting" if we choose to do that.

Support extending statistic rule elements for spellcasting

---

src/module/rules/rule-element/item-alteration/alteration.ts

Set `brokenThreshold` after altering physical-item max hit points

---

packs/feats/weapon-improviser-dedication.json
src/module/actor/character/document.ts
src/module/actor/character/helpers.ts

Retrieval of the penalties shouldn't have been in `getCheckRollContext`: it has all the context its needs during regular data preparation. Also updated kickback predicate for remaster refactors and used better RE on the Weapon Improviser Dedication feat.

Fix improvised and kickback penalties not manifesting on PC sheet

---

src/module/system/text-editor.ts

Not correct for spells but actor level shouldn't be a param in spells anyways. This is mostly for action/feat/physical/campaignFeature

Use item level as default actor level in @Damage

---

src/scripts/hooks/render-settings.ts
static/lang/en.json

Players see this instead:
These are two different browsers, which is why there's minor font rendering differences

Show remaster journal button in settings sidebar

---

src/module/system/check/check.ts

While making a PR for the Workbench module, I had to feel around for the list of tags I wanted. Terrible!

Add CSS class to each list of tags in check messages

---

src/module/system/text-editor.ts
src/scripts/🐵🩹.ts
src/util/uuid.ts

Upstream retrieves documents from UUID links sequentially, which has a noticable load time with text containing many links: retrieve everything at once beforehand with the faster `UUIDUtils.fromUUIDs` system helper.

Speed up `TextEditor._enrichContentLinks`

---

src/module/actor/character/sheet.ts
src/styles/actor/character/_attribute-builder.scss
src/styles/actor/character/_index.scss
src/styles/actor/party/kingdom/_builder.scss
src/styles/mixins/_animations.scss
static/templates/actors/character/tabs/general.hbs

Shows the animated glowy thing like in the boost manager:

Alert user on PC sheet when there are unallocated boosts

---

src/module/system/damage/helpers.ts
src/module/system/damage/roll.ts
src/module/system/damage/terms.ts
types/foundry/client/roll.d.ts

Simplify deterministic `RollTerm`s as soon as possible in damage rolls

---

packs/sky-kings-tomb-bestiary/lady-shimmersnip.json
packs/sky-kings-tomb-bestiary/soulbound-doll-sky-kings-tomb.json

Soulbound Doll with Phantom Pain was missing and it has been confirmed that this should replace the alignment based spell in this case
We also got a confirmation that Lady Shimmersnip is intended to be large.

Fix Lady Shimmersnip, Add Soulbound Doll for SKT

---

src/module/item/spell/document.ts
src/module/item/spellcasting-entry/types.ts

They were already there for the statistic itself (and therefore attack rolls), but they weren't there for damage rolls.

Include spellcasting roll options in damage rolls

---

packs/classfeatures/sparkling-targe.json

Doesn't automatically increase the hardness when defending against a spell, but it does work with the toggle on. Also adds the missing feat grant.

Use ItemAlteration for Sparkling Targe

---

packs/feat-effects/effect-ancestral-influence.json
src/module/encounter/combatant.ts
src/module/item/abstract-effect/data.ts
src/module/item/effect/document.ts
src/module/item/effect/sheet.ts
src/styles/item/_effect-sheet.scss
src/styles/item/_sidebar.scss
static/lang/en.json
static/templates/items/effect-sidebar.hbs

Oopsie'd the implementation of Ancestral Influence: it should reevaluate on turn end, not turn start.
This is going to need further expansion to handle reevaluation on rolling initiative, but that can come later.

Add formula reevaluation on turn end

---

packs/iconics/ezren-level-1.json
packs/iconics/ezren-level-3.json
packs/iconics/ezren-level-5.json
packs/paizo-pregens/ezren-beginner-box.json
src/module/item/base.ts

Also add options to control what gets refresh in `ItemPF2e#refreshFromCompendium`, starting with `name`

Refresh spells on the Ezrens

---

src/module/migration/migrations/793-make-predicates-arrays.ts

This needs to be added to a new migration, but popping it into 793 for now--where it should have been from the start.

Ensure predicates in custom modifiers are arrays

---

src/module/actor/character/helpers.ts

`WeaponAuxiliaryAction.execute` calls `Actor.adjustCarryType` (which is async) but doesn't wait for it to complete. This means that if we call `WeaponAuxiliaryAction.execute` programmatically, even with an `await`, then `Actor.adjustCarryType` will not have completed by the time `execute`'s returned Promise is resolved, and there is no way to determine when the `adjustCarryType` operation has actually completed.
This change makes `WeaponAuxiliaryAction.execute` await the completion of `Actor.adjustCarryType` before continuing.

Wait for adjustCarryType to complete before considering execute complete

---

src/module/actor/party/helpers.ts
src/module/system/settings/index.ts

Thinking again, we might want to preserve organization for people running games with multiple parties. Some worlds may also have guest/former player characters just hanging around.
Minor refactor for the settings, since the "fake" settings were beginning to become a bit hard to separate from the real ones.

Don't add members to new party

---

packs/kingmaker-features/kingdom-features/experienced-leadership.json
src/module/actor/party/document.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/module/actor/party/kingdom/values.ts
src/styles/actor/party/kingdom/_main.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/main.hbs

For some reason, statistic.modifiers doesn't get modifier adjustments applied, but statistic.check.modifiers does. This means that the modifiers tooltip is not showing correct values. That doesn't seem to be a kingdom bug though, and more of a Statistic one.

Implement kingdom invested roles and Experienced Leadership

---

src/module/actor/character/attribute-builder.ts
static/lang/en.json
static/templates/actors/character/attribute-builder.hbs

I noticed this when poking around, but its not possible to use manual ability boosts right now in any reasonable way without tracking your boosts elsewhere. This rectifies that.
This also fixes a bug where selected key score wasn't selected in manual.

Add way to track partial boost in manual mode

---

src/module/system/check/check.ts

Temporary measure until the macros can be further-gutted

Prevent action macros from creating duplicate h4 elements

---

src/module/chat-message/helpers.ts

I could open up the entire if statement based on the results of hasDamage, but I'm doing only roll notes now to be on the safe side. Let me know if I'm free to open the floodgates.
Later on I can pass the domain to applyDamage, create a context flag, and get roll inspector in there.

Enable roll notes for damage-received

---

packs/classfeatures/precise-strike.json
packs/feats/lethal-finisher.json
packs/feats/perfect-finisher.json
packs/feats/stunning-finisher.json
packs/feats/targeting-finisher.json
packs/feats/unbalancing-finisher.json
static/lang/re-en.json

Some rough edges still, bleeding finisher should be doable now but needs to dance around those rare level 16 multiclass swashbucklers maybe. That can be done as a follow up. Lethal finisher is going to be a problem, it's extra damage that depends on the target's save result which could be done through a toggle like this
```json
{
"domain": "all",
"key": "RollOption",
"label": "PF2E.SpecificRule.Prompt.DegreeOfSuccessTarget",
"option": "finisher:fatal:dice",
"suboptions": [
{
"label": "PF2E.Check.Result.Degree.CheckcriticalSuccess",
"value": "0"
}, {
"label": "PF2E.Check.Result.Degree.Checksuccess",
"value": "6"
}, {
"label": "PF2E.Check.Result.Degree.Checkfailure",
"value": "12"
}, {
"label": "PF2E.Check.Result.Degree.CheckcriticalFailure",
"value": "18"
}
],
"toggleable": true, …
```

Brushup automation for Swashbuckler finishers

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/chat-message/document.ts
src/module/system/check/check.ts
src/module/system/check/index.ts
src/module/system/check/roll.ts
src/module/system/check/types.ts
src/module/system/statistic/index.ts
src/styles/ui/sidebar/chat/_action.scss
static/templates/chat/check/roll.hbs

This is a step towards being able to use the same roll class for strikes. It adds a dedicate template for `CheckRoll`s that includes action, damage, and other information.

Fill out check data to be usable by damaging actions

---

packs/spells/ancient-dust.json

Does not account for no persistent damage on succeeded save. Previous version resulted in NaN persistent damage.

Convert Ancient Dust to non-text based persistent damage application

---

src/scripts/ui/inline-roll-links.ts
static/templates/chat/action/header.hbs

This was a temporary solution until `SpecialStatistic` REs were added. Also tweak presentation of such rolls.

Remove determination of attack roll in `InlineRollLinks`

---

src/module/item/armor/document.ts
src/module/item/armor/sheet.ts

Shields don't function if they can't be held, and the armor UI has no affordances to change the usage.
The armor template defaults to "wornarmor": https://github.com/foundryvtt/pf2e/blob/e3889d815e906e3a840d6740111c9d9725fbb821/static/template.json#L724
An earlier migration fixed this for existing items, but does not address newly created items:
https://github.com/foundryvtt/pf2e/blob/e3889d815e906e3a840d6740111c9d9725fbb821/src/module/migration/migrations/718-carry-type.ts#L26

Update armor usage when category changed to shield

---

src/module/item/melee/document.ts
src/scripts/macros/hotbar.ts
static/templates/actors/npc/partials/attack.hbs

The "chat data" and template of melee items aren't usable, so this is effectively a bugfix.

Post strike upon clicking NPC/hazard to-chat buttons

---

src/global.ts
src/module/system/settings/index.ts
types/foundry/client/ui/index.d.ts

`skipLibCheck` means no .d.ts files will be type-checked

Fix type errors in global.d.ts, rename to global.ts

---

src/module/actor/modifiers.ts
src/module/actor/party/kingdom/model.ts

This broke when party.level stopped fetching the campaign level.

Fix kingdom skill calculation

---

packs/feat-effects/effect-nanite-surge-bonus.json
packs/feat-effects/effect-nanite-surge.json
packs/feats/nanite-surge.json

Let me know if the templates (both in the effect and/or the feat) outta be removed.

Implement Nanite Surge status bonus as a second self remove effect

---

packs/book-of-the-dead-bestiary/gallowdead.json

I don't believe there's currently a way to apply "reach-120" to an NPC attack via REs. I've left the suboption in place to disambiguate the choice to the GM.

Add automation for Gallowdead's Charge Chain

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts

Possibility to add own option for damage/attack
`_token.actor.system.actions[0].roll({event, options: ['test']})`
`_token.actor.system.actions[0].damage({event, options: ['test']})`

Include roll options passed to strike methods when rolling

---

static/lang/en.json
static/templates/actors/party/regions/exploration.hbs

The Party Speed label is still in use by the Travel Duration macro, which we should probably wire into the active party if we're still interested in maintaining that. I don't even know why it exists (or that it existed).

Update party travel labels to adhere to mechanics

---

src/styles/actor/npc/_index.scss

Remove tag line-height styling from NPC sheet

---

src/module/notes.ts
src/module/system/check/check.ts
src/module/system/damage/damage.ts
src/module/system/text-editor.ts
src/scripts/ui/user-visibility.ts
src/styles/ui/sidebar/chat/_index.scss

Also:
- Add itemId to note markup indicating which item the note came from
- Check metagame setting to determine default `showDC` for inline checks

Refactor note markup to use `createHTMLElement`

---

src/module/actor/loot/document.ts
src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts
src/module/canvas/token/object.ts
types/foundry/client/application/form-application/document-sheet/base.d.ts

This grants access to player NPC sheets via telling upstream what the player can specifically do at each check stage.

Handle NPC lootability without faking ownership level

---

src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_index.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/sheet.hbs

This is a resource that is omnipresent during the kingdom turn. Without an omnibar (nor the time to build one) the header is the current best place to put it.

Add resource points to kingdom header

---

src/module/item/spell/document.ts
src/styles/legacy/_chat.scss
static/lang/en.json
static/templates/chat/spell-card.hbs

Hide spell DCs when appropriate

---

packs/spell-effects/spell-effect-conductive-weapon.json
packs/spells/conductive-weapon.json
static/lang/re-en.json

~~I don't believe there's currently a way to modify a property rune's damage with an RE.~~
Faked the property rune for metal targets.

Add effect for Conductive Weapon

---

packs/actions/energy-shot.json
packs/actions/into-the-fray.json
packs/actions/living-fortification.json
packs/actions/one-shot-one-kill.json
packs/actions/spring-the-trap.json
packs/actions/ten-paces.json
packs/feat-effects/effect-living-fortification-parry-trait.json
packs/feat-effects/effect-living-fortification.json

Added notes to the Gunslinger initiative rolls with the description of authorized actions.
Added a toggle to provide Living Fortification AC buffs for the Vanguard.

Improved Gunslinger initial deeds

---

src/module/encounter/document.ts
src/scripts/macros/xp/index.ts

Still thinking of settings for this, but as a default: threat is relative to participating combatants, but XP is per player in the party, regardless of whether they were in the encounter.

Show encounter threat by participating combatants, XP for whole party

---

src/module/actor/party/document.ts
types/foundry/common/abstract/data.d.ts

DataModel update side only. Doesn't include the RecordField changes or any of the stuff relying on it.

Support deletions in kingdom data

---

build/run-migration.ts
packs/equipment/belt-of-good-health.json
packs/equipment/caverns-heart.json
packs/equipment/demons-knot.json
packs/equipment/pyrite-rat.json
packs/equipment/sentinel-horn.json
packs/equipment/sigil-of-the-first-clan.json
packs/equipment/terror-spores.json
packs/equipment/tome-of-dripping-shadows.json
packs/equipment/toxic-effluence.json
packs/equipment/volcanic-vigor-greater.json
packs/equipment/volcanic-vigor.json
packs/sky-kings-tomb-bestiary/ashrin.json
packs/sky-kings-tomb-bestiary/hryngar-assassin.json
packs/sky-kings-tomb-bestiary/narseigus-wormcaller.json
src/module/item/armor/document.ts
src/module/item/physical/sheet.ts
src/module/item/weapon/document.ts
src/module/migration/migrations/860-rm-group.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

`baseItem` is already being handled in `PhysicalItemPF2e#_preUpdate`

Normalize weapon/armor group from `_preUpdate` methods, migrate away errant `group` property

---

src/module/system/check/check.ts

This was added during our brief attempt to use custom tags in flavor HTML.

Remove `unsafe` property in system message flags

---

src/module/rules/rule-element/strike.ts

This is to allow other fist strikes (like from Ape animal instinct) to replace it.

Lower priority of fist shorthand strike to 99

---

src/global.ts
src/module/item/physical/document.ts
src/module/item/physical/helpers.ts
src/module/rules/rule-element/item-alteration/alteration.ts
src/scripts/set-game-pf2e.ts

The name-generation method doesn't work very well (or at all) for some languages. This will allow localization-module authors to replace the function with their own.

Move `PhysicalItemPF2e#generateModifiedName` to globally-exposed helper

---

static/templates/actors/partials/item-summary.hbs
static/templates/items/spell-details.hbs
static/templates/items/spell-overlay.hbs

Several `<button>` elements in the Item Summary and Spell Details interfaces were not given a `type` attribute, defaulting them to type `submit`. Because these interfaces are included inside of `<form>` elements, it made them viable targets for _implicit submission_ of the form when certain actions are taken, most notably when the Enter key was pressed in another input. This creates a synthetic click event and triggers the button's corresponding handlers, that are seemingly unrelated to the field the user has focused.
These buttons were changed to `type="button"`:
- triggered from anywhere on the character sheet:
- use consumable
- item summary spell attack and spell damage
- triggered from anywhere in a spell details window:
- add heightening (fixed & interval)
- all of the …

Fix item summary / spell buttons firing when pressing enter elsewhere in the form

---

src/module/item/base.ts
src/module/scene/token-document/document.ts

Same measure as for `ItemPF2e`

Prevent premature data preparation in `TokenDocumentPF2e`

---

src/module/apps/compendium-browser/tabs/feat.ts
src/scripts/config/traits.ts

Fixes a regression pointed out by @tdhsmith in the last PR. The other selected traits are no longer dropped if an ancestry trait is present.
Also adds `Reflection` to the `ancestryTraits` config.

Fix regression in feat tab trait filtering introduced by `#10044`

---

src/module/actor/character/feats.ts

Introduce a very simple default filter for free archetype feats. If you do not yet have a dedication, this filters by the `dedication` trait; if you DO have a dedication, this filters by the `archetype` trait.
More advanced logic (e.g. for specific archetypes) might be possible but seems overwrought and too likely to run into issues with how individual tables adjudicate gray areas and introduce house rules.
Closes #10006

Add default filter to free archetype feat slots

---

src/module/actor/party/sheet.ts

To improve the usability of the stash screen for sorting loot, it seemed simpler to allow the party member blocks in the inventory sidebar to function as special drop targets for dragged items:
https://github.com/foundryvtt/pf2e/assets/1791252/c97af133-dfb1-4995-bd8c-ca859b2c65a4
This is a pretty simple reuse of `ActorSheetPF2e.moveItemBetweenActors` and thus has the standard restrictions of requiring a GM active for Player-initiated transfers.

Allow divvying of party stash using inventory members sidebar

---

packs/feat-effects/effect-envenom-fangs.json
packs/feats/envenom-fangs.json
packs/feats/fangs.json
packs/feats/sharp-fangs.json

Also add icons for fang strikes.
Closes https://github.com/foundryvtt/pf2e/issues/10051

Add effect for Envenom Fangs

---

packs/classfeatures/armor-expertise.json
packs/feats/acrobat-dedication.json
packs/feats/armor-specialist.json
packs/feats/hellknight-dedication.json
packs/feats/tumble-behind-swashbuckler.json
packs/feats/unshaken-in-iron.json
static/lang/re-en.json

- Skeletal group resistance applied on **Armor Expertise** and **Armor Specialist**
- **Hellknight Dedication** special resistance, triggered by
- missing-but-implied toggle to indicate character is wearing hellknight plate
- Copied base armor specialization REs to **Unshaken in Iron** with extra predicates to detect armor proficiency. However this does _not_ attempt to handle the extra bonuses from Tenacious Stance yet.

Add more armor specialization automation

---

static/templates/chat/spell-card.hbs

I'm not sure what exactly changed here but a heightened spell is technically a variant so it shoudn't have worked from the start.
Checking for applied overlays instead should only catch the correct instances.
The naming of Variant/Overlay/Override is a bit confusing.

Fix `Select Other Variant` button being show on heightened spell chat cards

---

src/module/rules/rule-element/aura.ts

Following precedent set by core measure template textures
An opaque texture can be quite obstructing (see bottom example below), but I figure there ought to be a predictable default consistent with core measured templates.

Set default aura texture alpha to 1

---

packs/spells/beheading-buzz-saw.json

Also sorted damage entries and added Heightened info to description.

Add icon and secondary save link to Beheading Buzz Saw

---

packs/spell-effects/spell-effect-flame-dancer.json
packs/spell-effects/spell-effect-phoenix-ward.json
packs/spells/cave-fangs.json
packs/spells/dancing-fountain.json
packs/spells/flame-dancer.json
packs/spells/personal-ocean.json
packs/spells/phoenix-ward.json
packs/spells/wall-of-metal.json

Also add icons to Cave Fangs, Dancing Fountain, Flame Dancer, Personal Ocean, Phoenix Ward, Wall of Metal.

Add effects for Flame Dancer and Phoenix Ward

---

packs/feats/versatile-blasts.json

Currently validation fails if no kinetic aura is active.

Fix predication of Versatile Blast feat

---

static/templates/chat/feat-card.hbs

The `actionGlyph` helper returns nothing if the passed value is invalid so no extra checks needed.

Show action cost in feat chat card when available

---

src/module/actor/party/kingdom/builder.ts
static/templates/actors/party/kingdom/builder.hbs

This was originally conceived when I wanted to make it possible to edit the charter/government/etc. But now I think were I to do that, I'd add a "Custom" entry instead.

Remove kingdom builder unset button

---

src/scripts/config/index.ts
src/scripts/config/traits.ts
src/util/misc.ts

`deityDomains` only works with `mapToObject` because we don't need to return the original key.

Build config objects with Remeda functions and eliminate instances of accumulator spreading in reduces

---

src/styles/actor/party/kingdom/_builder.scss
src/styles/actor/party/kingdom/_features.scss
static/templates/actors/party/kingdom/partials/build-entry-boosts.hbs

Add tag styling for kingdom boosts and skills

---

src/module/scene/token-document/document.ts
static/lang/en.json

Just a bunch of unrelated typos.
Found by looking through the thousand or so automatically-found dictionary warnings in my IDE (IntelliJ IDEA).

Fix various typos in en.json (#10178)

---

src/module/rules/rule-element/roll-note.ts

This allows {item|blah} and {actor|blah} stuff to work in roll note predicates like they do for modifiers and the like.

Resolve roll note predicates

---

src/module/actor/character/elemental-blast.ts
src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/system/damage/weapon.ts
src/module/system/text-editor.ts

In general, prevents non-persistent damage dice and modifiers from applying to pure persistent damage.
I did it during the extractDamageSynthetics step so that the damage dice dialog continues to work as expected.
Doing it in createDamageFormula() led to enabled modifiers/dice in the dialog that were mysteriously ignored 🤣

Don't apply bonus fire damage dice to Dehydrate

---

src/module/actor/party/sheet.ts
src/module/actor/sheet/data-types.ts
src/styles/actor/_coinage.scss
static/templates/actors/partials/coinage.hbs

The button is now disabled instead if there are no players or coins to distribute.

Always show party coin distribute to gamemasters

---

src/module/actor/npc/sheet.ts
src/module/actor/npc/types.ts
static/templates/actors/npc/tabs/main.hbs

For abilities without a sort property (such as those coming from compendiums), it tries to push the original order of free > reaction > action.

Support reordering NPC abilities

---

src/module/actor/sheet/loot/loot-npcs-popup.ts
src/styles/actor/loot/_index.scss
static/templates/actors/loot/loot-npcs-popup.hbs

This has the same logic as `PhysicalItemPF2e#isStackableWith`.
I've also fixed the popup UI after recording the video:
Closes #8796

Stack item quantities of items looted with the `LootNPCsPopup`

---

build/run-migration.ts
src/module/actor/data/base.ts
src/module/actor/helpers.ts
src/module/item/weapon/data.ts
src/module/migration/migrations/864-rm-weapon-map.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
static/template.json
static/templates/items/weapon-details.hbs

After running the migration on a weapon with MAP set from the sheet:

Remove MAP property from weapon system data, transferring to RE if set

---

src/module/apps/effects-panel.ts
src/module/item/condition/persistent-damage-dialog.ts
src/styles/system/_effects-panel.scss
static/templates/system/effects-panel.hbs

A certain module (and previous PR by someone) did it as shift+click, but an actual clickable button is hopefully less controversial. It doesn't show for conditions unless the condition is persistent damage (which opens up the persistent damage dialog and highlights the relevant formula).

Allow editing effects from effect panel tooltip

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/system/damage/weapon.ts

I'm not sure about "all", and I think `WeaponDamagePF2e.#getSelectors()` should probably be utilized instead of this list somehow, but this should help currently. I'm not sure on what the effects would be of making that method public and calling it from the damage function.

Include attack-damage for strikes and fix damage domains for roll context

---

src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/rules/rule-element/adjust-modifier.ts
src/module/system/damage/helpers.ts

Also acquire adjustments for attribute modifiers in spell damage
It's a little awkward that attribute modifiers get their damage type set early. Maybe that can be refactored so that dice damage type overrides will propagate to them.

Add support for spell damage dice type overrides

---

src/module/chat-message/listeners/cards.ts

Remove options from strike attack roll passed to message damage buttons

---

packs/equipment/saddlebags.json

`Saddlebags come in a pair. Each can hold up to 3 Bulk of items, and the first 1 Bulk of items in each doesn't count against your mount's Bulk limit. The Bulk value given is for saddlebags worn by a mount. If you are carrying or stowing saddlebags, they count as 1 Bulk instead of light Bulk.`
It looks like saddlebags are setup so that the pair of bags are one item. This fixes it so that the first two bulk of items are negated properly.

Fix saddlebags bulk reduction

---

src/module/actor/npc/document.ts
src/module/item/weapon/document.ts
types/foundry/common/abstract/document.d.ts

This is to allow melee items generated from Strike synthetics to have IDs.

Add `keepId` option (default `false`) to `WeaponPF2e#toNPCAttack`

---

packs/bestiary-effects/effect-bark-orders.json
packs/bestiary-effects/effect-darivans-bloodline-magic.json
packs/bestiary-effects/effect-defensive-slice.json
packs/bestiary-effects/effect-drain-luck.json
packs/bestiary-effects/effect-reminder-of-doom.json
packs/kingmaker-bestiary/chief-sootscale.json

Also remove RollOption from Effect: Defensive Slice and fix selector for Effect: Drain Luck.
Fix expiry for Effect: Bark Orders.

Add icons to some Kingmaker effects

---

src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_activities.scss
src/styles/actor/party/kingdom/_world.scss
static/templates/actors/party/kingdom/tabs/world.hbs

Minor border/overflow stuff. Settlement tab still looks like sin, but a little less so. Plus a tiny bugfix.

Tweak settlement/activities style and scroll filter summary into view

---

packs/classfeatures/gate-junction.json

If implemented this fixes the issue with the air gate junction granting the incorrect bonus to stealth if you select skill junction.

Fix air gate junction granting incorrect bonus to stealth

---

src/module/actor/party/kingdom/model.ts

If implemented this fixes the issue with the resource collection on kingdom upkeep granting free commodities. Previously it was setting the commodities to the maximum allowed value.

Fix kingdom resource collection giving free commodities

---

src/module/rules/rule-element/ae-like.ts

This can happen if a choice set is dismissed without making a selection, with the selection being injected into an AE-like path.

Invalidate AE-like paths containing /\bnull\b/

---

src/module/actor/sheet/base.ts
src/module/item/sheet/base.ts
src/styles/item/_rules.scss
src/util/misc.ts
static/templates/actors/character/tabs/feats.hbs
static/templates/actors/character/tabs/spellcasting.hbs
static/templates/actors/npc/tabs/spells.hbs
static/templates/actors/party/kingdom/tabs/features.hbs
static/templates/actors/spellcasting-spell-list.hbs
static/templates/items/rules-panel.hbs
static/templates/items/rules/outer.hbs

https://github.com/foundryvtt/pf2e/assets/1286721/11ab2e76-2756-4c7c-9fd6-c89d1477c41f
This also changes all existing drag-handles to need to be under a `data-foundry-list`. Reordering spells, npc/character spellcasting entries, and feats seem to continue to work.

Add drag/drop reordering of rule elements

---

build/run-migration.ts
packs/equipment/rod-of-razors.json
packs/equipment/throwing-shield.json
packs/feat-effects/stance-vitality-manipulation-stance.json
packs/feat-effects/stance-wild-winds-stance.json
packs/feats/core-cannon.json
packs/feats/energy-beam.json
packs/feats/foxfire.json
packs/feats/scalding-spit.json
packs/feats/seedpod.json
packs/feats/sprites-spark.json
packs/feats/venom-spit.json
packs/heritages/hooded-nagaji.json
packs/heritages/spined-azarketi.json
packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
packs/kingmaker-bestiary/castruccio-irovetti.json
packs/paizo-pregens/takemiru.json
src/module/migration/migrations/868-strike-re-range.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/strike.ts

Retires a long-running in-place migration.

Move range increment/max data to single object in Strike RE

---

src/module/item/sheet/base.ts
src/module/item/sheet/rule-element-form/base.ts

Comparing the source breaks when multiple updates are performed in quick succession. I assume there is a race condition somewhere down the line.
I think recording the rule element key and position in the index should be safe enough to identify if a form can be reused.
Unique ids in the rule elment source would be even better in this case but I don't think that is something we want to add.

Fix rule element form reuse not working with quick consecutive updates

---

packs/equipment-effects/effect-crimson-fulcrum-lens.json
packs/equipment/crimson-fulcrum-lens.json

Description update is just changing "pf2-icon" class to "action-glyph"

Brush up rule elements on Crimson Fulcrum Lens

---

src/module/item/sheet/rule-element-form/aura.ts
static/lang/re-en.json
static/templates/items/rules/aura.hbs

Treat 0 opacity auras as having null borders

---

src/module/chat-message/listeners/set-as-initiative.ts

When rerolling using a hero point, this removes the initiative button from the old roll and re-adds it to the new roll
Resolves #10357

Add set-as-initiative button to new roll for rerolls

---

packs/feats/exorcist-dedication.json
static/lang/re-en.json

Also emphasize "spirit dwelling" in description.
I just made a toggle on the feat, since that should avoids locking us into a migration path.
Considered making it an effect, but we don't really have a meaningful way to track spirit types so not sure how useful it would be. It could also be attached to a spirit dwelling item, but not sure how far we want to go down that rabbit hole.

Add light automation to Exorcist Dedication

---

src/module/scene/token-document/sheet.ts

It's only possible to have a single sheet registered for token documents, so there's no reason to have a sheet config link.
Closes #10383

Don't show sheet config in `TokenConfig` sheet

---

src/styles/actor/_index.scss

This creates a new stacking context on the actor sheet's "sheet-body" element, which prevents elements (mainly action-header) and text within from rendering above the navigation icons.
Before:
After:

Fix sheet body content cutting off/overlapping with navigation icons

---

src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/styles/ui/sidebar/_actor-directory.scss
static/lang/kingmaker-en.json

This adds a new phase of active, called "building", which allows players to open up the kingdom builder on their own without the GM needing to activate show sheets. 
When confirmed, the kingdom builder is opened to all players, and all players can now see the following on the party folder:
The GM can reverse this (but it won't reset data) by clicking the new Cancel Creation button. This closes the sheet for all players resets the party crown icon back to crown+:

Add new kingdom building phase and pop open sheet

---

src/module/item/sheet/base.ts
src/styles/item/_index.scss
static/templates/items/sheet.hbs

https://github.com/foundryvtt/pf2e/assets/1286721/05589d73-d2c1-4b9e-abfe-ffedcd08dd81
Re-render sets it back, and currently there is no way to close the editor that doesn't also cause a re-render.
This is the bug I'm trying to fix:

Fix double scrollbars on item sheet and make GM notes easier to edit

---

src/styles/item/_index.scss

Missed a spot. I think this should probably be something we put in the sheet reset since it seems we need to work around this very often. The cause is that tinymce sets a inline height style. The journals get around it by removing the height property in activateEditor(). But flex seems to also solve the issue.

Handle item sheet resizing in description editing

---

build/run-migration.ts
src/module/actor/character/document.ts
src/module/migration/migrations/869-refresh-mighty-bulwark.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts

Also remove the last internal "self:armor:*" roll option

Refresh rule elements on copies of Mighty Bulwark

---

src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/schema.ts
static/lang/kingmaker-en.json

Explicit check is from the days when it was an ObjectField and editing ABC entries was on the table. It was converted to SchemaField and the feature was descoped.

Fix detection of selected republic/thaumocracy in kingdom builder

---

src/module/item/sheet/base.ts
src/module/item/sheet/rule-element-form/base.ts

We could either include this to mitigate any unforseen form problems, or delay if the forms seem to be fine because this is a fundamental change. Either option is fine.

Only update rule elements that have been directly modified

---

src/styles/item/_index.scss
src/styles/item/_rules.scss
static/templates/items/rules/fast-healing.hbs
static/templates/items/rules/flat-modifier.hbs
static/templates/items/rules/grant-item.hbs
static/templates/items/rules/multiple-attack-penalty.hbs
static/templates/items/rules/note.hbs
static/templates/items/rules/partials/resolvable-brackets.hbs
static/templates/items/rules/token-image.hbs
static/templates/items/rules/token-light.hbs

This gets rid of the spaced-fields css, fixes the hover button layout twitching, and adds some of the styling we wanted as general styles. Also updates left side alignment of form elements (using label class short...) and redoes the fast healing form.

Clean up styling on RE forms and minor tweaks

---

packs/blood-lords-bestiary/harmony-in-agony.json
packs/blood-lords-bestiary/weeping-jack.json
packs/pathfinder-bestiary-3/pukwudgie.json
static/lang/re-en.json

Wasn't sure if I should add CreatureSize to Harmony In Agony and Weeping Jack's Shape Change REs. Giant Bats are large, but it's not explicitly called out in their stat blocks.
The rules for Shape Change say: "... might potentially change its senses or size. Any changes are listed in its stat block."

Add Change Shape Strike automation for Pukwudgie, Harmony In Agony, Weeping Jack

---

src/module/system/damage/helpers.ts

Without this fix inline number splash and precision lose their flavor. 
For example `@Damage[(1d4[splash])[fire]]` works fine.
However, `@Damage[(1[splash])[fire]]` does not.
This addresses the issue by also checking if Grouping.term is not isDeterministic or is NumericTerm.
Another test: `@Damage[1d4[acid],(1[splash])[fire],(1[precision])[poison]]`

Fix loss of flavor on numeric inline splash and precision

---

src/module/actor/base.ts

This makes certain merge rules more predictable. Currently it means that aura merges won't succeed during testing but fail during the actual game.

Prepare effect rule elements last

---

src/module/rules/rule-element/aura.ts

The if statement didn't do anything as source is modified by schemas, and initial data guarantees every property exists, making mergeObject() not do anything.
The end result should be the same.

Remove ineffective if/merge in aura merge

---

packs/blog-bestiary/eleukas.json

Blog post is [here](https://paizo.com/community/blog/v5748dyo6shjp?NoPrep-Character-Eleukas).

Add automation for Visperath's persistent acid damage

---

packs/spell-effects/spell-effect-light.json

Closes #10495
We don't need extraneous text in the description that isn't part of the automation and not helpful to users, so it's been cut down to just what the effect actually does.

Update Light spell effect description

---

src/module/actor/character/document.ts
src/module/actor/character/elemental-blast.ts
src/module/actor/helpers.ts
src/module/item/affliction/document.ts
src/module/item/spell/document.ts
src/module/system/damage/damage.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts
src/module/system/text-editor.ts
static/templates/chat/damage/damage-modifier-dialog.hbs

The DamageContext already contains domains and notes, and the code was sometimes inconsistent about which it used. The CheckRollContext and DamageRollContextFlag also has those fields, so we prioritize them for damage as well.
The context.notes sideeffect in the weapon damage calculate rubs me the wrong way, however that function already does a lot of roll option side-effects to the context, so it'll need a deeper refactor to remove that from there.

Reduce duplicate fields in DamageTemplate

---

packs/book-of-the-dead-bestiary/relictner-eroder.json
packs/book-of-the-dead-bestiary/shadern-immolator.json
packs/night-of-the-gray-death-bestiary/gray-gardener-enforcer.json
packs/pathfinder-bestiary-3/angheuvore-flesh-gnawer.json
packs/pathfinder-bestiary-3/etioling-blightmage.json
packs/pathfinder-bestiary-3/gurgist-mauler.json
packs/pathfinder-bestiary-3/lifeleecher-brawler.json
packs/pfs-season-1-bestiary/iloise-5-6.json
packs/pfs-season-1-bestiary/iloise-7-8.json

Also fix Etioling Blightmage's action type and count.
~~**Note:** I don't have "Pathfinder Society Scenario #1-25: Grim Symphony" to check that Iloise's ability should have the traits "divine" and "necromancy". I'm assuming it's the same as the others.~~
Iloise's ability does not have these traits.

Add missing links and traits to Death Gasp

---

packs/pathfinder-bestiary-2/aurumvorax.json

I don't believe it's currently possible to automate the bonus to Athletics DC against attempts to escape its grab.
Tried:
```
{
"key": "FlatModifier",
"predicate": [
"action:escape"
],
"selector": "athletics-dc",
"type": "circumstance",
"value": 4
}
```
but it didn't appear to function.

Add automation for Aurumvorax's Tenacious Stance

---

src/module/system/check/dialog.ts
src/module/system/damage/dialog.ts

This prevents modifiers that users uncheck from suddenly disappearing in the dialog.

Keep manually disabled modifiers in the dialog even if hideIfDisabled

---

src/styles/item/_index.scss
src/styles/item/_spell-sheet.scss
static/templates/items/activation-panel.hbs
static/templates/items/affliction-details.hbs
static/templates/items/ancestry-details.hbs
static/templates/items/armor-details.hbs
static/templates/items/background-details.hbs
static/templates/items/campaign-feature-details.hbs
static/templates/items/class-details.hbs
static/templates/items/consumable-details.hbs
static/templates/items/effect-sidebar.hbs
static/templates/items/equipment-details.hbs
static/templates/items/kit-details.hbs
static/templates/items/melee-details.hbs
static/templates/items/partials/ability-activation.hbs
static/templates/items/rules/grant-item.hbs
static/templates/items/spell-details.hbs
static/templates/items/spell-overlay.hbs
static/templates/items/weapon-details.hbs
static/templates/system/tag-selector/basic.hbs

- `.form-group-stacked` CSS selector is moving to `.form-group.stacked` in core
- `details-container-flex-row` is most equivalent to core (and semantic) CSS class, `form-fields`: system overrides are preserved

Remove usage of `form-group-stacked` and `details-container-flex-row`

---

src/module/apps/effects-panel.ts
src/module/item/abstract-effect/data.ts
src/module/item/abstract-effect/document.ts
src/module/item/abstract-effect/helpers.ts
src/module/item/affliction/data.ts
src/module/item/affliction/document.ts
src/module/item/affliction/sheet.ts
src/module/item/condition/data.ts
src/module/item/condition/document.ts
src/module/item/effect/data.ts
src/module/item/effect/document.ts
static/template.json
static/templates/items/affliction-details.hbs

This is similar to the inheritance parts of https://github.com/foundryvtt/pf2e/pull/9108 but since conditions also require durations in a later date (stunned for 1 round...) I put most of it in the base class.
This needs some UI in the effect panel, but testing in the console appears to function correctly.

Add support for affliction duration and stage duration

---

src/module/actor/helpers.ts

If merged, resolves #10494
It looks like the `self:participant:own-turn` comparison in the entries array in `createEncounterRollOptions()` is comparing a constructed and not-yet-constructed actor when targeting. I quickly did a console log to see what was happening:
```js
console.log(encounter.combatant?.actor === actor);
console.log(encounter.combatant?.actor, actor);
```
and got
The first pair (two combatants) of logs are when nothing is targeted, the second pair are when an enemy is targeted.

Change combatant comparison to constructed object

---

packs/classfeatures/armor-innovation.json
packs/classfeatures/harmonic-oscillator.json
packs/classfeatures/metallic-reactance.json
packs/classfeatures/muscular-exoskeleton.json
packs/classfeatures/otherworldly-protection.json
packs/classfeatures/phlogistonic-regulator.json
packs/classfeatures/speed-boosters.json
packs/classfeatures/subtle-dampeners.json
src/module/item/feat/document.ts

Initial weapon modifications have very individual requirements for each, making this approach a little less viable.

Use pack query for armor innovation's initial modification choice set

---

static/lang/en.json

The deities already had these, so they clearly got dropped in the shuffle of getting RoE out.

Add metal and wood domains

---

packs/blood-lords-bestiary/matron-uldrula.json

The core issue is that "hp-remaining" is not available until afterDerived, so the RollOption predicate doesn't work. Setting the RollOption to "phase": "afterDerived" fixes the RollOption, but this is too late to affect AC.

Fix Matron Uldrula's Shard Shield

---

packs/spell-effects/spell-effect-corrosive-body.json
packs/spell-effects/spell-effect-fiery-body.json
packs/spells/corrosive-body.json
packs/spells/fiery-body.json

- Condenses spell effects for Corrosive Body and Fiery Body with a ChoiceSet predicated on parent level.
- Adds description of 9th level heightened effects to both spell effects' descriptions, and links to Acid Splash in Corrosive Body's description.
- Adds damage entry for Corrosive Body and adds heightened damage for Fiery Body.
- Adds predicates preventing both spells from buffing their own damage.

Condense effects for Corrosive Body and Fiery Body

---

packs/spell-effects/spell-effect-flame-wisp.json
src/module/item/abstract-effect/data.ts
src/module/item/affliction/document.ts
src/module/item/condition/document.ts
src/module/item/effect/document.ts
src/styles/item/_effect-sheet.scss
src/styles/item/_sidebar.scss
static/lang/en.json
static/templates/items/effect-sidebar.hbs
static/templates/system/effects-panel.hbs

Once this is in I'll push shattershields (once I find icons for it....)
Also tweaks adding new labels to be a button in the header, to make it easier to add them in mass
Is there an existing good way to localize "Infinity" given its a number in and of itself or do I add a localization entry for it?

Add configurable effect badge min/max, tweak flamewisp effect to use

---

src/module/system/text-editor.ts
src/styles/_colors.scss
src/styles/_globals.scss
static/lang/en.json

If we are about to release, its ok to delay since I suspect there will be scenarios where this might be wrong. This presumes it's always adjusted higher, I'd like to see a scenario where it can actually be adjusted lower before accounting for that.

Highlight adjusted @Damage and show base value in a tooltip

---

src/scripts/ui/inline-roll-links.ts

Fixes inline kingdom checks for players

Always use the parent for party checks

---

src/module/system/check/check.ts
src/module/system/statistic/statistic.ts

Prevent attack item traits from appearing on saving throws

---

src/module/actor/character/feats.ts

Because [the bonus feat group now uses `assignFeat` instead of `feat.push`](https://github.com/foundryvtt/pf2e/pull/10677#discussion_r1357635350), the bonus feat group now goes through a bunch of checks it previously didn't when getting a new feat assigned to it -- one of which is the check to only allow feats whose category is the same as the current group's ID.
This causes the bonus feat group to reject any feat whose category is not bonus feat.
Since custom groups don't (read: shouldn't) have IDs that match the existing categories, and since `assignFeat` is probably the more "proper" way to add feats, I decided to just hardcode one specific exception to the bonus feat group.

Fix bonus feats not appearing on the character sheet

---

src/module/apps/compendium-browser/loader.ts
src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/equipment.ts

I'm not sure if `"system.source.value"` is needed anymore so I left it in.
Closes #10750

Fix compendium browser publication source loading

---

packs/spell-effects/spell-effect-vitrifying-blast.json
packs/spells/vitrifying-blast.json

Only handle the weakness, as I don't believe you can update the slowed badge value based on the granter's badge value.
Also, this is useful for the successful save as it doesn't grant slowed.

Add effect for Vitrifying Blast

---

src/module/item/spellcasting-entry/collection.ts

These were never changed after spell chat data went away. The methods themselves are still async for now (I suspect future improvements may require it).

Remove some unnecessary awaits in spell sheet data

---

src/module/apps/hotbar.ts
static/lang/en.json

Don't create non-effect macros from compendium item hotbar drops

---

src/styles/_globals.scss

Automatically italicize spell content links

---

src/module/actor/character/elemental-blast.ts
src/module/item/spell/document.ts
src/module/system/damage/weapon.ts

Including in attack rolls will require a little more work.

Include `target` as resolvable in strike, spell, and blast damage rolls

---

src/module/actor/helpers.ts
src/module/actor/modifiers.ts

Skip ignored attribute modifiers when extracting for strike damage rolls
