foundryvtt/pf2e

packs/data/equipment.db/ghost-charge-greater.json, packs/data/equipment.db/ghost-charge-lesser.json, packs/data/equipment.db/ghost-charge-major.json, packs/data/equipment.db/ghost-charge-moderate.json
Cleanup item properties on all ghost charges (automated)
Closes #2337
=> Correct Ghost Charge rule element

packs/data/bestiary-family-ability-glossary.db/ghost-fade.json
=> Add missing ghost ability fade

src/module/actor/sheet/data-types.ts, src/module/item/base.ts, src/module/item/data/helpers.ts, src/module/item/data/index.ts, src/module/item/data/values.ts, src/module/item/physical/data.ts, src/module/item/physical/types.ts, src/module/item/physical/values.ts, src/scripts/register-sheets.ts
Also moves `PHYSICAL_ITEM_TYPES` and `PhysicalItemType` to @item/physical/values and @item/physical/types, respectively
=> Add support for ItemPF2e#isOfType("physical")

src/module/actor/npc/index.ts, src/module/actor/npc/sheet.ts, src/module/item/weapon/index.ts, src/module/item/weapon/values.ts
=> Generate NPC attacks for alternative usages of weapons

src/module/system/check-modifiers-dialog.ts
Fix https://github.com/foundryvtt/pf2e/issues/2223
=> Update rollTwice in context on change

packs/data/equipment.db/metronomic-hammer.json, packs/data/feats.db/gravelands-herbalist.json
=> Fix spelling of Metronomic Hammer and Gravelands Herbalist

src/module/actor/character/index.ts, src/module/actor/creature/index.ts, src/module/actor/familiar/index.ts, src/module/actor/hazard/index.ts, src/module/actor/npc/index.ts, src/module/item/spellcasting-entry/trick.ts, src/module/system/action-macros/basic/sense-motive.ts, src/module/system/statistic/data.ts, src/module/system/statistic/index.ts, src/module/system/text-editor.ts, src/scripts/ui/inline-roll-links.ts, static/lang/en.json, static/templates/actors/spellcasting-dialog.html
also deprecates some functions
=> Add labels to statistics and derive check labels via parent labels

packs/data/equipment.db/peachwood-talisman.json
=> Add Peachwood Talisman

packs/data/one-shot-bestiary.db/giant-pirate-skeleton.json, packs/data/pfs-season-2-bestiary.db/bloody-vortex-3-4.json, packs/data/pfs-season-2-bestiary.db/bloody-vortex-5-6.json, packs/data/pfs-season-2-bestiary.db/demonplague-zombie.json, packs/data/pfs-season-2-bestiary.db/mercenary-trapper-3-4.json
I completely rebuilt the actors from scratch. They were bad.
=> Purge derived data from `Bloody Vortex`

packs/data/troubles-in-otari-bestiary.db/brimstone-rat.json, packs/data/troubles-in-otari-bestiary.db/bugbear-marauder.json
NPC updates for Troubles in Otari Bestiary
=> Update brimstone rat and bugbear marauder

src/module/apps/compendium-browser/tabs/base.ts
=> Preserve search text when resetting filters in compendium browser

packs/data/classfeatures.db/antipaladin.json, packs/data/classfeatures.db/desecrator.json, packs/data/classfeatures.db/liberator.json, packs/data/classfeatures.db/paladin.json, packs/data/classfeatures.db/redeemer.json, packs/data/classfeatures.db/tyrant.json
=> Adds grantItem for reactions for champion subtypes

src/module/system/damage/weapon.ts
=> Inspect weapon traits array for damage-affecting traits

packs/data/pathfinder-bestiary-2.db/ice-mephit.json, packs/data/pathfinder-bestiary-2.db/yamaraj.json
Removed () around hp details in "Ice Mephit" and "Yamaraj"
=> Fix HP details field of Ice Mephit and Yamaraj

src/styles/actor/hazard/_index.scss, static/templates/actors/hazard/sheet-new.html
=> Add source and author to new hazard sheet

packs/data/equipment.db/peachwood-branch.json, packs/data/equipment.db/peachwood-lumber.json
Adds Peachwood Lumber and Branch to Equipment.
=> Add missing Peachwood Equipment

src/module/actor/base.ts, src/module/actor/creature/index.ts
Adjustments weren't getting picked up for (1) custom modifiers and (2) modifiers with the "all" selector.
=> Cover two gaps in modifier adjustments getting applied

src/module/system/action-macros/helpers.ts
Actions macros build skill checks with a giant pile of gratuitiously duplicated code, so need to include here as well
=> Include modifier adjustments and roll substitutions in action macros

src/module/apps/ui/chat-log.ts, src/module/chat-message/chat-roll-details.ts, src/module/chat-message/index.ts, src/styles/ui/sidebar/chat/_chat-roll-details.scss, src/styles/ui/sidebar/chat/_index.scss, static/lang/en.json, static/templates/chat/chat-roll-details.html
=> Add nerd details dialog to chat right click menu

packs/data/equipment.db/victory-plate-greater.json
=> Fix description and rune on Victory Plate (Greater)

packs/data/spells.db/scrying.json
Fixes https://github.com/foundryvtt/pf2e/issues/2560.
=> Fix typo in Scrying

src/module/actor/character/index.ts, src/module/actor/creature/index.ts
=> Add manipulate trait when striking with alchemical bombs

src/module/system/damage/roll-dialog.ts
This is a temporary solution until the whole awful mess is replaced.
=> Work around damage roll code failing to correctly add kh modifier

src/module/system/conditions/manager.ts
Prevents unlinked conditions from leaking.
To reproduce the thing this fixes on live, set the PC to dying and not dying repeatedly, and then check the console. You'll see many instances of prone and flat footed. If you start removing from the effect panel, it doesn't remove cleanly.
=> Prevent prone and flat footed condition leaks on repeat unconciousness

packs/data/feats.db/grasping-reach.json
Fixes https://github.com/foundryvtt/pf2e/issues/2322.
=> Automate Grasping Reach

packs/data/actions.db/mark-for-death.json, static/lang/re-en.json
Fixes https://github.com/foundryvtt/pf2e/issues/2334
=> Automate Mark for Death Action

src/module/actor/base.ts, src/module/actor/character/data/types.ts, src/module/actor/character/index.ts, src/module/actor/character/sheet.ts, src/module/actor/creature/index.ts, src/module/actor/creature/sheet.ts, src/module/actor/sheet/popups/ability-builder.ts, src/module/item/ancestry/data.ts, src/module/item/ancestry/index.ts, src/module/item/background/data.ts, src/module/item/background/index.ts, src/module/item/class/data.ts, src/module/item/class/index.ts, src/scripts/handlebars.ts, src/scripts/register-templates.ts, src/styles/actor/_index.scss, src/styles/actor/character/_ability-builder.scss, src/styles/actor/character/_character.scss, static/lang/en.json, static/template.json, static/templates/actors/ability-builder.html, static/templates/actors/character/partials/abilities.html, static/templates/actors/character/tabs/general.html
Builds on previous PR to have a UI. Based on work from Mats
=> Add ability score builder UI

packs/data/feats.db/skill-training.json
Change predicate from "arc" to "med"
=> Update Skill Training Predicate for Medicine

src/module/item/class/index.ts, src/styles/_fonts.scss, src/styles/actor/character/_ability-builder.scss, src/styles/actor/character/_character.scss, static/lang/en.json, static/templates/actors/ability-builder.html
- Pre-select key ability if only one option is available
- Fix spell/punctuation of messages
- Show appropriate ("pointer", "not-available") cursor when hovering buttons
- Use font-size variables
- Auto-format template markup, reduce unrendered whitespace
- Make underlined links dotted (only provide tooltips)
- Slow down pulse animation
=> Make polish pass on ability builder UI

packs/data/actions.db/invoke-celestial-privilege.json, packs/data/feats.db/between-the-scales.json, packs/data/feats.db/briar-battler.json, packs/data/feats.db/cringe.json, packs/data/feats.db/draconic-sycophant.json, packs/data/feats.db/dragonblood-paragon.json, packs/data/feats.db/dragons-breath.json, packs/data/feats.db/dragons-presence.json, packs/data/feats.db/kobold-lore.json, packs/data/feats.db/scamper.json, packs/data/feats.db/slither.json, packs/data/feats.db/snare-setter.json, packs/data/feats.db/vicious-snares.json, packs/data/feats.db/wyrmling-flight.json, static/lang/re-en.json
Only 1 kitsune action needed RE adding, so it's covered in this PR.
=> Automate kobold feats, and kitsune action

src/module/actor/character/data/types.ts, src/module/actor/character/index.ts, src/module/actor/creature/data.ts, src/module/actor/creature/index.ts
Closes #2574 and moves the dying stuff to creature in preparation for the later stuff.
=> Fix wounded cap with diehard

src/module/system/conditions/manager.ts
Includes the token hud and effect manager.
=> Apply cap to wounded/dying/doomed from all sources

src/module/actor/character/data/sheet.ts, src/module/actor/character/index.ts, src/module/actor/character/sheet.ts, src/module/actor/creature/index.ts, src/module/actor/creature/sheet.ts, src/module/actor/creature/types.ts, src/scripts/register-templates.ts, src/styles/actor/sidebar/_index.scss, static/templates/actors/character/sidebar/health.html, static/templates/actors/partials/dying-pips.html
Also replaces the last dying pip for a real pip.
This is a bugfix for an old issue.
=> Adjust dying max based on current doomed value

src/module/item/spellcasting-entry/index.ts
=> Find the best slot to consume when using the cast function

packs/data/vehicles.db/bone-ship.json
First attempt to add the vehicle - still not quite sure what should get added and should should be left out though.
=> Add bone ship vehicle from B3

src/module/apps/ui/chat-log.ts, src/module/chat-message/index.ts
=> Fix assignment of actor to save messages made from from spells cards

src/scripts/config/traits.ts
=> Add all magical traditions to creature traits

packs/data/feat-effects.db/stance-multishot-stance.json, packs/data/feats.db/double-shot.json, packs/data/feats.db/triple-shot.json
=> Refactor Triple Shot and Multishot Stance into modifier adjustments

packs/data/pathfinder-bestiary-3.db/blood-hag.json
=> Add a range to the Blood Hag's Firebolt Strike

src/module/actor/character/sheet.ts, src/module/actor/creature/sheet.ts, src/styles/actor/familiar/_index.scss, static/templates/actors/familiar-sheet.html
=> Add temp hp and dying pips to familiar sheet

packs/data/pathfinder-bestiary-3.db/city-guard-squadron.json, packs/data/pathfinder-bestiary-3.db/cobbleswarm.json, packs/data/pathfinder-bestiary-3.db/consonite-choir.json, packs/data/pathfinder-bestiary-3.db/sturzstromer.json
=> Review B3 - city guard squadron, cobbleswarm, sturzstromer, consonite choir

src/module/rules/rule-element/roll-note.ts
\+ send message for each validation failure
=> Fix validation test in Note RE

packs/data/feats.db/unlimited-ghost-flight.json
Fix the prerequisite in Unlimited ghost flight
=> fix the prerequisite in Unlimited ghost flight

src/module/actor/sheet/base.ts
=> Fix physical items of different types not being reorderable

src/module/apps/ui/compendium-directory.ts, types/foundry/client/game.d.ts, types/foundry/client/ui/context.d.ts
=> Add context menu to compendium search results

src/global.d.ts, src/module/actor/base.ts, src/module/actor/data/base.ts, src/module/scene/token-document/data.ts, src/module/scene/token-document/document.ts, src/module/scene/token-document/sheet.ts, src/scripts/register-module-art.ts
As a necessary component, a new token flag is also added to disable token auto-scaling on an individual basis.
=> Add support for module art setting token scale

src/module/actor/sheet/popups/ability-builder.ts, static/lang/en.json, static/templates/actors/ability-builder.html
=> Fix close button, tooltip, and pair of labels in boost manager

src/module/actor/character/index.ts, src/module/actor/sheet/popups/ability-builder.ts, src/styles/actor/character/_character.scss, static/templates/actors/ability-builder.html, static/templates/actors/character/partials/abilities.html, static/templates/actors/character/partials/traits.html
Several things are broken by the changes that have been made to "improve" it.
Also, improve behavior of key ability score being set manually.
=> Clean up the Ability Score builder, again and by a different person

src/module/item/deity/sheet.ts, src/util/tags.ts, static/templates/items/deity-details.html
Also removes max suggestions from tagify'd deity sheet inputs
=> Make deity sheet's use of Tagify generally available

packs/data/extinction-curse-bestiary.db/bitter-truth-bandit.json, packs/data/extinction-curse-bestiary.db/pin-tingwheely.json, packs/data/extinction-curse-bestiary.db/raving-spirit.json, packs/data/extinction-curse-bestiary.db/swardlands-delinquent.json, packs/data/extinction-curse-bestiary.db/tanessa-fleer.json
Updated Bitter Truth Bandit, Pin Tingwheely, Raving Spirit, Swardlands Delinquent, and Tanessa Fleer.
=> Update Extinction Curse Book 3 Ch1 NPCs

packs/data/extinction-curse-bestiary.db/caustic-dart-trap.json, packs/data/extinction-curse-bestiary.db/xulgath-bomber.json, packs/data/extinction-curse-bestiary.db/xulgath-skirmisher.json
Updated Caustic Dart Trap, Xulgath Bomber, and Xulgath Skirmisher.
=> Update Extinction Curse Book 3 Ch2 NPCs

packs/data/feats.db/foxfire.json
=> Remove errrant prereq from Foxfire

static/lang/re-en.json
stwlam checked that's all right elsewhere. #2718 Closed
=> Delete extra d (poisond1d12 key) in re-en.json

src/module/actor/character/index.ts, src/module/actor/helpers.ts, src/module/actor/npc/index.ts, src/module/rules/rule-element/data.ts, src/module/rules/rule-element/index.ts, src/module/rules/rule-element/multiple-attack-penalty.ts, src/module/system/statistic/data.ts, src/module/system/statistic/index.ts
=> Share MAP calculation between PCs and NPCs

packs/data/pathfinder-bestiary-2.db/megalania.json, packs/data/pathfinder-bestiary-2.db/nuglub.json, packs/data/pathfinder-bestiary-2.db/quickling.json, packs/data/pathfinder-bestiary.db/jinkin.json, packs/data/pathfinder-bestiary.db/pixie.json
Since I can't comment on lines outside of changes anymore, this forwards changes I made to PFS variants back to the book versions of these monsters.
=> Fixes to Bestiary 1 & 2 NPCs found in #2643

packs/data/classfeatures.db/ape-animal-instinct.json, packs/data/classfeatures.db/bear-animal-instinct.json, packs/data/classfeatures.db/bull-animal-instinct.json, packs/data/classfeatures.db/cat-animal-instinct.json, packs/data/classfeatures.db/deer-animal-instinct.json, packs/data/classfeatures.db/frog-animal-instinct.json, packs/data/classfeatures.db/shark-animal-instinct.json, packs/data/classfeatures.db/snake-animal-instinct.json, packs/data/classfeatures.db/wolf-animal-instinct.json
Adding back in the load bearing jank.
=> Fix rage damage of animal instinct barbarians.

packs/data/equipment.db/blast-lance-greater.json
Level 4 -> 8
Price 100 -> 500 gp
fire damage 2d8 -> 3d8
page reference deleted
=> Errata of the Blast lance (greater)

packs/data/pathfinder-bestiary-2.db/cairn-linnorm.json
=> Fix a double info in Cairn linnorm venom

src/styles/_colors.scss, src/styles/actor/character/_character.scss, src/styles/actor/character/_feats.scss, src/styles/actor/character/_index.scss, static/lang/en.json, static/templates/actors/character/tabs/feats.html, static/templates/actors/character/tabs/general.html
=> Standardize Ability Scores Header and use for Feat section

src/global.d.ts, src/module/actor/character/data/types.ts, src/module/actor/character/index.ts, src/module/actor/sheet/popups/ability-builder.ts, src/module/system/settings/variant-rules.ts, static/lang/en.json, static/templates/actors/ability-builder.html, static/templates/system/settings/variant-rules-settings.html
=> Implement Gradual Ability Boosts Variant Rule

src/module/canvas/measured-template.ts
=> Open up grid highlighting for uses other than measured templates

packs/data/equipment.db/blast-lance-greater.json, packs/data/equipment.db/blast-lance.json, packs/data/equipment.db/knight-captains-lance.json, packs/data/equipment.db/lance.json, packs/data/equipment.db/radiant-lance.json, packs/data/pathfinder-bestiary.db/skeletal-champion.json, packs/data/pfs-season-1-bestiary.db/flaming-skull-skeletal-champion.json, packs/data/pfs-season-1-bestiary.db/skeletal-gladiator.json, packs/data/pfs-season-1-bestiary.db/skeleton-captain.json, packs/data/pfs-season-3-bestiary.db/bloody-skeletal-champion.json, packs/data/pfs-season-3-bestiary.db/unstable-skeletal-champion.json
=> Correct deadly die size for lances

packs/data/pathfinder-bestiary-2.db/ember-fox.json
Replaces #2786 to avoid superfluous commits
=> Add Persistent Damage Notes to Ember Fox Jaws

packs/data/agents-of-edgewatch-bestiary.db/poison-eater.json, packs/data/bestiary-effects.db/effect-poison-frenzy.json
=> Audit the Poison Eater (AoE)

src/module/system/rolls.ts, src/module/system/statistic/index.ts, src/styles/ui/sidebar/chat/_chat-roll-details.scss, static/templates/chat/chat-roll-details.html
=> Add domains to roll inspector for statistic rolls

packs/data/iconics.db/korakai-level-1.json, packs/data/iconics.db/korakai-level-5.json, packs/data/spells.db/tempest-touch.json
Adds Cold damage to Tempest Touch base and heightened.
=> Update Tempest Touch with secondary damage

packs/data/adventure-specific-actions.db/communicate-from-beyond.json, packs/data/pathfinder-bestiary-2.db/akizendri.json, packs/data/pfs-season-3-bestiary.db/cooking-catastrophe.json, packs/data/pfs-season-3-bestiary.db/cooking-disaster.json, packs/data/pfs-season-3-bestiary.db/grimple-3-18.json, packs/data/pfs-season-3-bestiary.db/nuglub-3-18.json, packs/data/pfs-season-3-bestiary.db/pelagastr-tail.json, packs/data/pfs-season-3-bestiary.db/thick-pelagastr-tail.json
The Tough Pelgastr Tail does not have a fly speed. This is not an error
The regular one casts cantrips at level 3
The grimple has 16 HP vice 9 (Bestiary 3 version)
=> add NPCs and Hazards from PFS 3-18

packs/data/equipment.db/ring-of-the-ram-greater.json, packs/data/equipment.db/ring-of-the-ram.json
=> Add rollable damage buttons per action to the Ring of the Ram

src/module/actor/sheet/item-summary-renderer.ts
Only find pre-existing summaries among direct children
=> Fix feat double summary rendering

src/styles/actor/character/_character.scss
=> Fix styling of deity on main tab of PC sheet

packs/data/spell-effects.db/spell-effect-pest-form.json
Fixed in description and in the speed field
=> Fix base speed of Pest form spell effect

packs/data/feat-effects.db/effect-blade-ally-anarchic-rune.json, packs/data/feat-effects.db/effect-blade-ally-axiomatic-rune.json, packs/data/feat-effects.db/effect-blade-ally-disrupting-rune-greater.json, packs/data/feat-effects.db/effect-blade-ally-disrupting-rune.json, packs/data/feat-effects.db/effect-blade-ally-fearsome-rune.json, packs/data/feat-effects.db/effect-blade-ally-flaming-rune.json, packs/data/feat-effects.db/effect-blade-ally-ghost-touch-rune.json, packs/data/feat-effects.db/effect-blade-ally-holy-rune.json, packs/data/feat-effects.db/effect-blade-ally-keen-rune.json, packs/data/feat-effects.db/effect-blade-ally-unholy-rune.json
Update `Effect: Blade Ally x` to work with Handwraps
=> Update Effect Blade Ally to work with Handwraps

src/module/actor/hazard/sheet-new.ts, src/module/actor/hazard/types.ts, static/template.json, static/templates/actors/hazard/partials/sidebar.html
And also default hazards to 0 health and 0 ac
=> Show defenses for beta hazard sheet if there is an AC value

packs/data/bestiary-effects.db/effect-adaptive-strike.json, src/module/actor/npc/index.ts, src/module/rules/rule-element/adjust-strike.ts, src/module/system/damage/weapon.ts, static/lang/en.json
=> Extend weapon material strike adjustments to NPC attacks

src/styles/actor/character/_effects.scss, src/styles/mixins/_effects-list.scss, static/templates/actors/character/tabs/effects.html, static/templates/actors/character/tabs/pfs.html
=> Condense effects styling and use non-svg header for PC effects

src/styles/actor/character/_pfs.scss, src/styles/mixins/_effects-list.scss, static/templates/actors/character/tabs/pfs.html
=> Fix PFS boons styling

src/styles/item/_index.scss, static/templates/items/spell-details.html
=> Improve styling of spell variant details in the spell sheet

src/styles/actor/loot/_index.scss, static/templates/actors/loot/sidebar.html
=> Show carried bulk for loot actors

packs/data/pfs-season-1-bestiary.db/barralbus-1-2.json, packs/data/pfs-season-1-bestiary.db/barralbus-3-4.json, packs/data/pfs-season-1-bestiary.db/boggard-swampseer-pfs-1-24.json, packs/data/pfs-season-1-bestiary.db/elite-boggard-swampseer-pfs-1-24-animal-staff.json, packs/data/pfs-season-1-bestiary.db/great-white-shark-pfs-1-12.json, packs/data/pfs-season-1-bestiary.db/hungry-blade-apprentice.json, packs/data/pfs-season-1-bestiary.db/hungry-blade-recruit.json, packs/data/pfs-season-1-bestiary.db/reefclaw-pfs-1-12.json, packs/data/pfs-season-1-bestiary.db/submerged-shard.json
Also fixes order of predicates on extract for boggard swampseers in PFS 1-24
=> Add or update NPCs from PFS 1-12

src/module/actor/character/index.ts, src/module/actor/creature/index.ts, src/module/actor/creature/types.ts, src/module/item/abc/index.ts
[auto-adjust-hp.webm](https://user-images.githubusercontent.com/106829671/178130896-a10e63f0-0c9d-412b-8d51-052f11abef9b.webm)
=> Auto-adjust current hit points when changing PC level or adding ABC item

src/module/actor/hazard/sheet-new.ts, src/module/actor/hazard/types.ts, src/styles/actor/hazard/_actions.scss, static/templates/actors/hazard/sheet-new.html
=> Make actions sortable in new hazard sheet, reactions go first

src/styles/actor/character/_index.scss
=> Use serif font with action category tabs

src/module/item/spell/index.ts
=> Skip damage modifiers on spells that don't have formulas

src/module/actor/base.ts, src/module/actor/character/index.ts, src/module/actor/creature/index.ts, src/module/actor/familiar/index.ts, src/module/actor/hazard/index.ts, src/module/actor/npc/index.ts, src/module/actor/vehicle/index.ts, src/module/item/spell/index.ts, src/module/item/spellcasting-entry/trick.ts, src/module/rules/rule-element/flat-modifier.ts, src/module/rules/util.ts, src/module/system/action-macros/helpers.ts, src/module/system/damage/weapon.ts, src/module/system/statistic/index.ts, src/module/system/text-editor.ts
ActorPF2e#getModifierAdjustments had been getting called inconsistently and with incomplete selectors. This will take care of most of those cases.
=> Have extractModifiers call extractModifierAdjustments

src/module/canvas/token/object.ts
- On-create notification was redundant
- On-delete check is necessary
=> Remove redundant aura notification, add necessary aura check

src/module/rules/rule-element/choice-set/rule-element.ts
=> Don't skip basic unarmed attacks in unarmed attack choicesets

src/module/item/spell/index.ts, src/styles/legacy/_chat.scss
Also a minor CSS fix for buttons with no image
=> Fix spell variant buttons falling back to myster man image with invalid actions

src/styles/settings/_homebrew.scss
=> Fix homebrew input height scaling when multiple lines long

packs/data/spells.db/concordant-choir.json, packs/data/spells.db/elemental-annihilation-wave.json, packs/data/spells.db/horizon-thunder-sphere.json, packs/data/spells.db/inner-radiance-torrent.json, packs/data/spells.db/ki-blast.json, packs/data/spells.db/rip-the-spirit.json, packs/data/spells.db/wronged-monks-wrath.json
Covers the straightforward damage spells with variable cast times that I could find.
=> Add spell variants for damage spells with variable cast times

src/module/item/deity/sheet.ts, src/module/item/feat/sheet.ts, src/module/item/sheet/base.ts, src/module/item/sheet/data-types.ts, src/module/item/sheet/rule-elements.ts, src/scripts/register-templates.ts, src/styles/item/_rules.scss, src/util/tags.ts, static/lang/re-en.json, static/templates/items/rules-panel.html, static/templates/items/rules/default.html, static/templates/items/rules/note.html
Also enable the base item sheet to parse tagify globally
=> Implement Roll Note RE Editor

src/scripts/config/traits.ts
Dark Archive includes Cursed Consumables (Thanks, Paizo!)
=> Add Cursed to Consumable Traits

src/module/actor/character/feats.ts, src/module/actor/character/sheet.ts, src/module/actor/sheet/base.ts, src/styles/actor/character/_feats.scss, static/lang/en.json, static/templates/actors/character/tabs/feats.html
The empty slots no longer interact with mouse drags, and the browse button is gone from the unorganized feats. Resolves #2918
=> Improve feat drag/drop and handle invalid feat drops

src/styles/actor/_index.scss, src/styles/actor/character/_feats.scss, src/styles/actor/npc/_inventory.scss, src/styles/actor/tabs/_actions.scss, static/templates/actors/character/partials/granted-feat.html, static/templates/actors/character/tabs/actions.html, static/templates/actors/character/tabs/feats.html, static/templates/actors/npc/partials/action.html, static/templates/actors/npc/partials/attack.html, static/templates/actors/partials/inventory.html
=> Set FA icons to fixed-width in a few places on PC and NPC sheets

src/scripts/config/traits.ts, static/lang/en.json
Many of the Hazards in DA have the Visual trait.
=> Add Visual trait to Hazard actors and Apocryphal Subdomains

src/styles/actor/_spell-list.scss, src/styles/actor/character/_feats.scss, src/styles/actor/character/_proficiencies.scss, src/styles/actor/character/_spellcasting.scss, static/templates/actors/character/sheet.html, static/templates/actors/character/tabs/actions.html, static/templates/actors/character/tabs/crafting.html, static/templates/actors/character/tabs/effects.html, static/templates/actors/character/tabs/feats.html, static/templates/actors/character/tabs/general.html, static/templates/actors/character/tabs/pfs.html, static/templates/actors/character/tabs/proficiencies.html, static/templates/actors/character/tabs/spellcasting.html, static/templates/actors/spellcasting-spell-list.html
It's doing a good job at making for even and sufficient spacing between and around icons
=> Add fa-fw class to more Font Awesome icons on PC sheet

packs/data/equipment.db/blade-launcher.json
Closes #2963 
Adds the missing Blade Launcher to Equipment
=> Add Blade Launcher from Guns & Gears

packs/data/spell-effects.db/spell-effect-girzanjes-march.json
=> Add field property to RE brackets in Girzanje's March effect

src/module/actor/sheet/spellcasting-dialog.ts, static/lang/en.json, static/templates/actors/spellcasting-dialog.html
Later on we should show the heighten level on the sheet for all actors in the cantrip section, but separate PR.
=> Add configuration for NPC auto heighten

src/module/actor/creature/sheet.ts, src/module/actor/creature/types.ts, src/module/item/action/data.ts, src/module/item/action/index.ts, src/module/item/action/sheet.ts, src/module/item/data/base.ts, src/module/item/feat/data.ts, src/module/item/feat/index.ts, src/module/item/feat/sheet.ts, src/module/item/physical/data.ts, src/module/item/physical/sheet.ts, src/module/item/sheet/data-types.ts, src/scripts/macros/rest-for-the-night.ts, src/styles/actor/character/_actions.scss, src/styles/item/_activations.scss, src/styles/item/_index.scss, static/lang/en.json, static/templates/actors/character/tabs/actions.html, static/templates/items/action-details.html, static/templates/items/activation-panel.html, static/templates/items/feat-details.html
There's a part of me that wants get frequency() to return a special frequency class that can make such comparisons. But I'd like to have eyes on this first.
=> Add frequency and display to actions and feats in the character sheet

packs/data/age-of-ashes-bestiary.db/bloody-blade-mercenary.json, static/lang/re-en.json
Changed RuleElements to use re-en.json entries for localization
=> Review BloodyBladeMercenary

src/module/actor/sheet/popups/ability-builder.ts, src/styles/actor/character/_ability-builder.scss, static/templates/actors/ability-builder.html
Housekeeping before I go in and attempt to handle double flaws.
=> Favor disabled over classname for ability builder

packs/data/equipment.db/potion-of-expeditious-retreat.json
=> Link Fleeing condition in Expeditious Retreat potion

packs/data/feats.db/grippli-weapon-familiarity.json, packs/data/paizo-pregens.db/muruwa.json
Closes https://github.com/foundryvtt/pf2e/issues/3104.
=> Fix a typo in Grippli Weapon Familiarity RE for Scythe

packs/data/age-of-ashes-bestiary.db/bloody-blade-mercenary.json, packs/data/age-of-ashes-bestiary.db/duergar-slave-lord.json, static/lang/re-en.json
Consolidated re-en.json and changed rule elements of Hunt Prey for Bloody Blade Mercenary and Duergar Slave Lord
=> AoA: Localize rule elements

src/module/actor/character/index.ts
=> Include adjustments on bulwark modifier

src/module/migration/migrations/766-wipe-url-sources.ts
there was a ? missing that could sometimes cause undefined.startsWith()
=> fix Migarion 766

src/module/actor/sheet/popups/ability-builder.ts, src/styles/actor/character/_ability-builder.scss, static/templates/actors/ability-builder.html
=> Added applying voluntary flaw to same ability twice

src/module/actor/sheet/popups/ability-builder.ts, src/styles/actor/character/_ability-builder.scss, static/templates/actors/character/ability-builder.html
=> Polish interactivity of ability builder, enlarge buttons

src/module/actor/character/index.ts, src/module/actor/npc/index.ts, src/module/rules/rule-element/aura.ts
Also include hp-remaining for NPCs
=> Add hp-percent roll option to PCs and NPCs

src/module/item/sheet/rule-elements.ts, static/lang/re-en.json, static/templates/items/rules/note.html
=> Clear note RE title if blank, localize placeholders

src/styles/item/_rules.scss
=> Fix styling of rule editor CTRL+F

src/module/migration/migrations/768-add-new-auras.ts
=> Add Enlightened Presence to migration 768

static/templates/actors/character/tabs/actions.html
=> Show that a strike is for a temporary item

src/styles/actor/character/_actions.scss
=> Fix actions tab styling around navigation

static/lang/re-en.json
=> Fix the localization of implements

src/styles/actor/npc/_inventory.scss, static/templates/actors/partials/item-line.html
=> Fix NPC item rarity colors

packs/data/classes.db/thaumaturge.json
=> Add trained skills to Thaumaturge

src/module/actor/sheet/item-summary-renderer.ts
=> Fix spell variant check in item summary renderer

packs/data/classfeatures.db/implements-empowerment.json
=> Add automation to Implement's Empowerment feature

packs/data/age-of-ashes-bestiary.db/xotani-the-firebleeder.json
Changed language "Cannot Speak..." to "Can't Speak..." as in all other NPCs in AoA and Bestiaries.
=> Standardize Language Can't Speak

packs/data/equipment.db/spellguard-blade.json
=> Add abjuration trait to Spellguard Blade

src/module/item/class/index.ts
Hold until after patch release: we'll probably want to audit the classes before letting this run.
=> Train skills from class during data preparation

src/module/actor/base.ts, src/module/actor/creature/index.ts, src/module/actor/modifiers.ts, src/module/actor/npc/data.ts, src/module/actor/npc/index.ts, src/module/actor/npc/sheet.ts, src/module/actor/npc/types.ts, src/module/item/base.ts, src/module/item/melee/index.ts, src/module/item/spell/index.ts, src/scripts/dice.ts, src/styles/actor/npc/_spells.scss, static/templates/actors/npc/tabs/spells.html
=> Adjust modifiers instead of adding new ones for elite/weak adjustments

src/module/actor/character/automatic-bonus-progression.ts, src/module/actor/character/feats.ts, src/module/actor/character/index.ts, src/module/actor/character/sheet.ts, src/module/actor/character/strike-weapon-traits.ts, src/module/actor/creature/index.ts, src/module/actor/creature/sheet.ts, src/module/actor/familiar/index.ts, src/module/actor/familiar/sheet.ts, src/module/actor/inventory/bulk.ts, src/module/actor/inventory/index.ts, src/module/actor/loot/index.ts, src/module/actor/loot/sheet.ts, src/module/actor/npc/index.ts, src/module/actor/npc/sheet.ts, src/module/actor/npc/skills-editor.ts, src/module/actor/npc/strike-attack-traits.ts, src/module/actor/sheet/base.ts, src/module/actor/sheet/item-summary-renderer.ts, src/module/actor/sheet/trick-magic-item-popup.ts, src/module/actor/vehicle/index.ts
=> Convert files in @actor to use `Actor#system`

src/module/actor/hazard/index.ts, src/module/actor/hazard/sheet.ts, src/module/actor/sheet/base.ts, src/styles/actor/hazard/_index.scss, src/styles/ui/_tags.scss, static/templates/actors/hazard/partials/header.html, static/templates/compendium-browser/filters.html, static/templates/items/spell-details.html
=> Use tagify for editing hazard traits

src/styles/ui/_tags.scss
=> Tone down tagify disabled effects for paizo style

src/module/apps/compendium-browser/tabs/action.ts, src/module/apps/compendium-browser/tabs/bestiary.ts, src/module/apps/compendium-browser/tabs/equipment.ts, src/module/apps/compendium-browser/tabs/feat.ts, src/module/apps/compendium-browser/tabs/hazard.ts, src/module/apps/compendium-browser/tabs/spell.ts
=> Convert Compendium Browser tabs `loadData()` method to use the `system` property

src/module/actor/character/sheet.ts, src/module/actor/creature/sheet.ts, src/module/actor/sheet/base.ts, src/module/actor/sheet/spellcasting-dialog.ts, src/module/item/base.ts, src/module/item/physical/index.ts, src/module/item/spell/index.ts, src/module/item/spellcasting-entry/index.ts, src/module/item/spellcasting-entry/sheet.ts, static/templates/actors/spellcasting-prep-sheet.html, static/templates/actors/spellcasting-spell-list.html, types/foundry/client/core/hooks.d.ts
Also fixes moving items between actors and removes various `instance of` checks I found along the way
=> Remove most warnings from character spellcasting and fix character sheet _onDrop

src/module/item/weapon/index.ts
=> Revert strike generation fix

static/templates/actors/character/tabs/actions.html
This is the part where I wonder how it ever worked and how it was never reported until like 2 days ago, privately.
=> Fix bug with updating frequency values

src/styles/actor/_index.scss, src/styles/actor/_reset.scss, src/styles/actor/tabs/_actions.scss, static/lang/en.json, static/templates/actors/character/tabs/actions.html, static/templates/actors/character/tabs/feats.html
=> Update character actions tab to new headers, reset styling for v10

system.json
=> Change `name` property in system.json to `id`

src/module/actor/data/size.ts, src/module/actor/sheet/base.ts, src/module/actor/sheet/data-types.ts, src/styles/actor/_inventory.scss, static/templates/actors/partials/item-line.html
=> Report bulk differences in the inventory

src/module/item/container/sheet.ts, src/module/item/sheet/base.ts, src/scripts/register-sheets.ts, static/lang/en.json, static/templates/items/backpack-details.html
=> Add sheet toggle for container stowability

src/scripts/hooks/ready.ts, types/foundry/common/abstract/document.d.ts
I don't know if this is a v9 bugfix or v10 conversion, but shouldn't really matter either way.
=> Fix data in combat actor re-prep

packs/scripts/extract.ts, src/module/actor/sheet/base.ts, src/scripts/system/dragstart-handler.ts, src/styles/_globals.scss, src/styles/mixins/_tinymce.scss
Also fixes levels of dragged effects
=> Convert entity-link to content-link

src/module/actor/base.ts, src/module/canvas/token/aura/map.ts, src/module/canvas/token/object.ts, src/module/chat-message/document.ts, src/module/rules/rule-element/base.ts, types/foundry/client/pixi/placeable-object/base.d.ts
=> Use v10 getters for token controlled and hover

src/module/actor/base.ts, src/module/scene/token-document/document.ts
Mostly shark's idea to do it like this
=> Fix assigning default token image

src/module/actor/sheet/base.ts, src/styles/actor/character/_character.scss, src/styles/actor/npc/_index.scss, static/templates/actors/character/tabs/general.html, static/templates/actors/npc/partials/sidebar.html
=> Add show image button to npc and characters

src/styles/actor/_inventory.scss, static/templates/actors/partials/carry-type.html, static/templates/actors/partials/item-line.html
=> Use fa-stack for held carry type in item lines

src/module/scene/token-document/document.ts
Temporary until type is updated
=> Assert LightData construction as compatible with V9 type definition

static/lang/re-en.json
These persistent damage notes are fairly silly at this point but I'll keep adding them as needed I guess.
=> Add localizations for persistent force damage

packs/data/feats.db/violent-unleash.json
=> Fix inline damage on Violent Unleash feat

src/module/actor/sheet/base.ts, src/module/item/spellcasting-entry/collection.ts, src/module/item/spellcasting-entry/index.ts, static/lang/en.json
=> Warn if the spell level is moved or prepared to an invalid level

packs/data/actions.db/confident-finisher.json
=> Fix traits of Confident Finisher

packs/data/feats.db/command-corpse.json, packs/data/feats.db/corpse-tender-dedication.json, packs/data/feats.db/corpse-tenders-font.json, packs/data/feats.db/imbue-mindlessness.json, packs/data/feats.db/improved-command-corpse.json
=> Fix feat type of Corpse Tender archetype feats

packs/data/pathfinder-bestiary-2.db/spirit-naga.json
=> Fix the alignment of Spirit Naga

.eslintrc.js, src/module/actor/sheet/loot/loot-npcs-popup.ts, src/module/item/base.ts, src/module/migration/migrations/651-ephemeral-focus-pool.ts, src/module/migration/migrations/656-other-focus-pool-sources.ts, src/module/migration/migrations/702-re-formulas-at-instance-level.ts, src/module/migration/migrations/704-martial-proficiency-re.ts, src/module/system/settings/menu.ts, types/foundry/client/config.d.ts, types/foundry/client/pixi/helpers/ruler.d.ts, types/foundry/client/roll.d.ts, types/foundry/common/utils/helpers.d.ts, types/foundry/common/utils/primitives.d.ts
See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/array-type.md
=> Add ESLint rule to enforce array types

packs/data/backgrounds.db/reborn-soul.json
=> Add Reborn Soul background

packs/data/feats.db/evangelize.json
=> Fix Evangelize prerequisites

packs/data/agents-of-edgewatch-bestiary.db/ofalth-zombie.json, packs/data/outlaws-of-alkenstar-bestiary.db/chemical-zombie.json, packs/data/pathfinder-bestiary-3.db/sulfur-zombie.json, packs/data/pathfinder-bestiary-3.db/zombie-dragon.json, packs/data/pfs-season-1-bestiary.db/unkillable-zombie-brute-pfs-1-13.json, packs/data/pfs-season-1-bestiary.db/zombie-minihulk.json, packs/data/pfs-season-1-bestiary.db/zombie-riding-horse.json, packs/data/pfs-season-1-bestiary.db/zombie-warhorse.json, packs/data/pfs-season-2-bestiary.db/ferocious-zombie-grindylow.json, packs/data/pfs-season-2-bestiary.db/fire-eye-cyclops-zombie-1-2.json, packs/data/pfs-season-2-bestiary.db/fire-eye-cyclops-zombie-3-4.json, packs/data/pfs-season-2-bestiary.db/unkillable-zombie-shambler.json
=> Add Slowed condition to all zombies missing it

.betterer.results, src/module/system/tag-selector/base.ts, src/module/system/tag-selector/basic.ts, src/module/system/tag-selector/resistances.ts, src/module/system/tag-selector/senses.ts, src/module/system/tag-selector/speeds.ts, src/module/system/tag-selector/weaknesses.ts
The resistances and weakness selectors need to be merged: will happen in a followup PR
=> Clean up tag selector classes and make functional in V10

src/module/actor/character/crafting/helpers.ts, src/module/actor/sheet/popups/scroll-wand-popup.ts, src/module/item/consumable/index.ts, src/module/item/consumable/spell-consumables.ts, static/lang/en.json
- Set heightened level when creating a new scroll/wand
- Refrain from destroying the item if the actor can't cast the embedded spell
- Improve messaging in case of above
=> Fix multiple issues and scroll and wand usage

src/module/system/text-editor.ts, types/foundry/client/config.d.ts
=> Fix `@Localize` generating malformed HTML

src/module/actor/creature/sheet.ts, src/module/apps/effects-panel.ts, src/module/item/abstract-effect/data.ts, src/module/item/abstract-effect/document.ts, src/module/item/abstract-effect/index.ts, src/module/item/condition/index.ts, src/module/item/effect/data.ts, src/module/item/effect/index.ts, src/module/item/effect/sheet.ts, src/module/item/index.ts, src/module/system/conditions/manager.ts, src/module/system/conditions/types.ts, src/styles/system/_effects-panel.scss, static/lang/en.json, static/templates/actors/character/tabs/effects.html, static/templates/actors/npc/tabs/effects.html, static/templates/actors/partials/conditions.html, static/templates/items/effect-sidebar.html, static/templates/system/effects-panel.html
The abstract effect right now is really bare. We can move some token image stuff to there, and we can start implementing more at the base level once condition badge data is migrated
=> Start on abstract effect and number sequence effects

static/templates/actors/character/tabs/crafting.html, static/templates/actors/crafting-entry-list.html
Also change instances of @root.owner to @root.options.editable
=> Fix attributes with listeners on crafting entry templates

packs/data/pfs-season-3-bestiary.db/thomil-bolyrius-5-6.json
=> Fix level of Thomil Bolyrius

src/module/actor/character/data/sheet.ts, src/module/actor/character/feats.ts, src/module/actor/character/sheet.ts, src/module/actor/sheet/base.ts, src/module/apps/compendium-browser/index.ts, src/module/apps/compendium-browser/tabs/data.ts, src/module/apps/compendium-browser/tabs/equipment.ts, src/module/apps/compendium-browser/tabs/feat.ts, src/styles/packs/_filter-slider.scss, tsconfig.json
Bonus: Fix compendium browser feat search launched from PC sheet
=> Use tagified traits input for compendium browser feat search

src/module/apps/compendium-browser/index.ts, src/module/apps/compendium-browser/tabs/data.ts, src/styles/actor/_spell-list.scss, static/templates/actors/spellcasting-prep-sheet.html
=> Fix compendium browser level filtering launched from spell prep sheet

src/styles/actor/character/_spellcasting.scss, static/templates/actors/character/tabs/spellcasting.html
=> Make spell preparation a big blue button for characters

src/module/actor/character/index.ts, src/module/rules/rule-element/base.ts, src/module/rules/rule-element/roll-option.ts
=> Use options parameter for testing in `RollOptionRuleElement#beforeRoll`

src/module/actor/sheet/base.ts, src/module/apps/compendium-browser/index.ts, src/module/item/sheet/base.ts, src/styles/item/_tagify.scss, src/util/tags.ts
Also a sneaky alignment fix on the cursor and input size.
=> Fix lingering tagify dropdowns and hazard traits input

src/module/item/base.ts, src/scripts/hooks/render-dialog.ts, static/lang/en.json
We can always add more later, but physical items is the biggest category.
=> Add option groups to the item create dialog

packs/data/equipment.db/armored-coat.json, packs/data/equipment.db/bladed-gauntlet.json, packs/data/equipment.db/hollowed-hilt.json, packs/data/equipment.db/knights-maintenance-kit.json, packs/data/equipment.db/knights-standard.json, packs/data/equipment.db/knights-tabard.json, packs/data/equipment.db/portable-altar.json, packs/data/equipment.db/travelers-cloak.json, packs/data/equipment.db/war-lance.json, packs/data/equipment.db/war-saddle.json, static/lang/en.json
Also alphabetize the armor list in en.json
Closes #3588
=> Add missing equipment from Knights of Lastwall

src/module/actor/modifiers.ts, src/module/rules/rule-element/base.ts, src/module/rules/util.ts, src/module/system/predication.ts
In the near future everything should be working entirely from sets
=> Accept roll-option sets in more functions

src/module/actor/hazard/sheet.ts, src/module/actor/npc/sheet.ts, src/styles/actor/npc/_index.scss, src/styles/item/_header.scss, src/styles/ui/_tags.scss, static/templates/actors/npc/partials/header.html
=> Tagify NPC traits

packs/data/equipment.db/stiletto-pen.json, src/module/item/weapon/index.ts, src/module/item/weapon/sheet.ts, src/module/item/weapon/types.ts, src/module/item/weapon/values.ts, src/module/migration/migrations/691-weapon-range-ability-category-group.ts, src/scripts/config/index.ts
=> Relax melee/ranged coercion of darts

src/module/item/sheet/base.ts, src/module/item/sheet/data-types.ts, src/module/item/sheet/rule-elements.ts, src/scripts/register-templates.ts, src/styles/item/_rules.scss, static/lang/re-en.json, static/templates/items/rules-panel.html, static/templates/items/rules/default.html, static/templates/items/rules/grant-item.html, static/templates/items/rules/note.html
=> Implement Grant Item RE Form

src/module/item/values.ts, src/scripts/hooks/render-dialog.ts, static/lang/en.json
=> Add opt group for PC building items in item-creation dialog

src/module/item/physical/index.ts, src/module/item/weapon/index.ts
Setup work for armor price adjustment as well.
=> Refactor weapon price computation to computeAdjustedPrice()

packs/data/strength-of-thousands-bestiary.db/spellskein-control-weather.json
=> Fix damage roll of Control Weather Spellskein

src/module/item/melee/sheet.ts, src/module/item/sheet/base.ts
I did this before I found it was a core issue, but its still an improvement so here we go.
=> Refactor melee sheet events to melee sheet

packs/data/book-of-the-dead-bestiary.db/vetalarana-manipulator.json
=> Add missing passives to Vetalarana Manipulator

src/module/canvas/status-effects.ts, src/module/encounter/document.ts, src/scripts/hooks/index.ts, src/scripts/hooks/render-token-hud.ts
renderTokenHUD --> hook file
updateEncounter --> `EncounterPF2e#_onUpdate`
=> Move hooks in status-effects.ts to hook file and EncounterPF2e

src/module/canvas/token/object.ts
=> Render temp hp above health bar

src/module/canvas/status-effects.ts, src/module/canvas/token/object.ts, src/module/item/condition/data.ts, src/module/system/conditions/manager.ts, src/scripts/config/index.ts, src/scripts/hooks/canvas-ready.ts, src/scripts/hooks/render-token-hud.ts, src/scripts/hooks/setup.ts, src/styles/legacy/_pf2e.scss, src/styles/ui/_index.scss, src/styles/ui/_token-hud.scss, types/foundry/client/config.d.ts
=> Refactor status-effects.ts for V10 TokenHUD API and personal sanity

src/module/apps/pick-a-thing-prompt.ts, src/module/rules/rule-element/choice-set/rule-element.ts
=> Limit sorting of ChoiceSet options to generated lists

src/module/apps/ui/encounter-tracker.ts, src/styles/ui/_combat.scss
=> Fade out name in encounter if mystified

src/module/system/damage/weapon.ts
=> Restore "str-damage" selector to NPC damage rolls when appropriate

src/module/item/armor/sheet.ts, src/module/item/physical/materials.ts, src/module/item/physical/sheet.ts, src/module/item/sheet/data-types.ts, src/module/item/weapon/index.ts, src/module/item/weapon/sheet.ts, static/templates/items/armor-details.html, static/templates/items/weapon-details.html
You can delay this till after v10. This is here as a starter for specific magic armor as well as partial armor price auto-computation (we can't really do runes for a long time).
=> Add weapon style material selection to armor, restrict armor materials

src/module/canvas/status-effects.ts, src/styles/ui/_token-hud.scss
=> Add icon for overridden conditions in token hud

src/module/apps/ui/compendium-directory.ts
=> Search Contents also matches compendium pack names

packs/data/spells.db/air-bubble.json
=> Add duration to Air Bubble spell

packs/data/classfeatures.db/intensify-vulnerability.json
=> Fix details of Intensify Vulnerability feature

src/module/actor/base.ts, src/module/actor/character/data/types.ts, src/module/actor/character/index.ts, src/module/actor/character/types.ts, src/module/actor/data/base.ts, src/module/actor/npc/data.ts, src/module/actor/npc/index.ts, src/module/rules/rule-element/dexterity-modifier-cap.ts, src/module/rules/synthetics.ts
Also move placement of data from REs to to actor.synthetics
=> Fix application of dexterity modifier cap when AC is zero

src/module/item/sheet/base.ts, src/module/item/sheet/data-types.ts, src/styles/item/_index.scss, src/styles/item/_sidebar.scss, static/templates/items/ancestry-sidebar.html, static/templates/items/armor-sidebar.html, static/templates/items/backpack-sidebar.html, static/templates/items/book-sidebar.html, static/templates/items/condition-sidebar.html, static/templates/items/consumable-sidebar.html, static/templates/items/effect-sidebar.html, static/templates/items/equipment-sidebar.html, static/templates/items/feat-sidebar.html, static/templates/items/formula-sidebar.html, static/templates/items/heritage-sidebar.html, static/templates/items/item-sheet.html, static/templates/items/kit-sidebar.html, static/templates/items/lore-sidebar.html, static/templates/items/spell-sidebar.html, static/templates/items/treasure-sidebar.html, static/templates/items/weapon-sidebar.html
=> Hide sidebar on rules tab

static/templates/compendium-browser/filters.html, static/templates/sidebar/compendium-directory.html
If we can't have #3744 then can we get this instead 😜
=> Set compendium search box to type "search"

src/module/actor/character/helpers.ts, src/module/actor/character/index.ts, static/lang/en.json
Crowbar RE being added with https://github.com/foundryvtt/pf2e/pull/3762
=> Add penalty for attempting to Force Open without crowbar

src/module/item/spell/index.ts, src/module/item/spellcasting-entry/index.ts, src/module/item/spellcasting-entry/trick.ts
This fixes the version that uses the Cast button.
=> Fix heightening spontaneous spells and tricked spells

packs/data/equipment.db/crowbar-levered.json, packs/data/equipment.db/crowbar.json, packs/data/feats.db/forced-entry.json
Added RE to automate crowbar for force open checks
Added RE to automate levered crowbar for force open checks
Added RE to remove crowbar penalty if you have the Forced Entry feat
=> Add Crowbar Rule Elements

static/templates/items/effect-sidebar.html
=> Remove effect badge type selection while counter is the only type

packs/data/pathfinder-bestiary-2.db/icewyrm.json
This should be in line with both AoN and the second Bestiary.
=> Correct icewyrm level value

src/module/actor/base.ts, src/module/scene/token-document/document.ts
Also check for RBV in _prepareDetectionModes override
=> Accommodate recent changes to token post-update workflows

src/styles/item/_index.scss, src/styles/item/_rules.scss, src/styles/item/_tagify.scss, src/util/tags.ts, static/templates/items/rules/grant-item.html, types/foundry/common/utils/helpers.d.ts
=> Show Granted Item on same line in form

src/module/actor/npc/sheet.ts, static/templates/actors/npc/partials/header.html
As a side effect this also makes the adjustment itself easier to click
=> Fix removing Elite/Weak adjustments

src/module/item/sheet/base.ts, src/module/item/sheet/rule-elements/base.ts, src/module/item/sheet/rule-elements/index.ts
Another piece of the ongoing flat modifier re stash that keeps having to be restashed
=> Move RE forms to folder

src/module/actor/character/crafting/entry.ts
=> Clone item source before using it for crafting entry update

packs/data/spells.db/harm.json
=> Remove `applyMod` from Harm spell variant

packs/data/equipment.db/peachwood-talisman.json
=> Add missing traits to Peachwood Talisman

packs/data/classfeatures.db/precise-strike.json, packs/data/feats.db/swashbucklers-speed.json
While we're at it, add slugs to Swashbuckler's Speed FlatModifier REs
=> Add REs to handle Flying Blade feat

src/module/actor/npc/index.ts
=> Fix showing limited NPCs with `actorLink`s in actor directory

src/scripts/hooks/render-chat-message.ts, src/scripts/ui/inline-roll-links.ts
=> Only show repost buttons on chat messages to message owners

src/module/actor/hazard/sheet.ts, src/module/chat-message/listeners/cards.ts, src/module/item/base.ts, src/module/item/melee/index.ts, static/templates/actors/hazard/sheet.html
I tested Hazard, PC, NPC, Familiar attacks, strikes, and damage, and spell attacks and damage.
=> Fix hazard attack and damage rolls

packs/data/strength-of-thousands-bestiary.db/spellskein-consecrate.json, packs/data/strength-of-thousands-bestiary.db/spellskein-control-weather.json, packs/data/strength-of-thousands-bestiary.db/spellskein-heroes-feast.json, packs/data/strength-of-thousands-bestiary.db/spellskein.json
=> Correct perception and missing darkvision on spellskein

CHANGELOG.md, package-lock.json, package.json, system.json
* (stwlam) Fix darkness adjuster rendering on scene view
* (stwlam) Update in-Foundry changelog URL to point to V10 release branch
* (SpartanCPA) Fill in (book) sources on items missing them
* (TMun) Correct perception and missing darkvision on spellskein
=> Release Notes 4.0.3

src/module/actor/sheet/popups/distribute-coins-popup.ts, static/templates/actors/distribute-coins.html
This just popped up in my game. The fix is adding the `value` back in the template and the rest is a bit of clean up.
=> Fix distribute coin popup

packs/data/feats.db/fledgling-flight.json
=> Restore Fledgling Flight feat

src/module/item/sheet/base.ts, src/module/item/sheet/rule-elements/flat-modifier.ts, src/module/item/sheet/rule-elements/index.ts, src/module/rules/rule-element/flat-modifier.ts, src/module/rules/util.ts, src/styles/item/_index.scss, src/styles/item/_rules.scss, src/styles/item/_sidebar.scss, static/lang/re-en.json, static/templates/items/rules/flat-modifier.html
Dev only so I can get more feedback (and so urgency drops a tad if any issues arise). Once data entry has used it enough with incident and its had maybe or two more revisions, we can publish it for real (hopefully for 4.1).
=> Add Flat Modifier Form (dev only)

src/module/actor/base.ts, src/module/canvas/status-effects.ts
=> Fix construction of persistent damage icon path

src/module/actor/npc/index.ts, src/module/notes.ts, src/module/system/action-macros/helpers.ts, src/module/system/rolls.ts, src/styles/_globals.scss
- Ensure cloning creates a perfect copy
- Prevent nested P elements
=> Fix multiple issues with roll notes

src/module/chat-message/document.ts, src/scripts/ui/user-visibility.ts
Bonus: double-click sender name to pan to the token
=> Fix obscuring sender names on chat messages

packs/data/equipment.db/wounding.json
Must've missed this on my errata PR
=> Remove outdated critical text from Wounding rune

src/module/item/feat/sheet.ts, static/lang/en.json
=> Correct "Feat/Feature" in Feat Sheet Header

packs/data/feats.db/automaton-armament.json, packs/data/feats.db/beastbrood.json, packs/data/feats.db/celestial-strikes.json, packs/data/feats.db/ceremony-of-the-evened-hand.json, packs/data/feats.db/fiendish-resistance.json, packs/data/feats.db/fiendish-strikes.json, packs/data/feats.db/fiendish-wings.json, packs/data/feats.db/final-form.json, packs/data/feats.db/form-of-the-fiend.json, packs/data/feats.db/riftmarked.json, packs/data/feats.db/tengu-weapon-familiarity.json, static/lang/re-en.json
Plus a missed tengu feat, an aasimar feat, adding the missed strikes onto a conrasu feat (oops), and adding icons to an automaton strike feat.
=> Automate tiefling feats

src/module/system/damage/weapon.ts
=> Fix damage roll notes getting dropped from chat cards

src/styles/_globals.scss
=> Tweak position of repost buttons

src/module/item/kit/sheet.ts, static/templates/items/kit-details.html, static/templates/items/kit-sidebar.html
Also remove old physical item fields from sidebar. The sidebar totally isn't needed anymore.
=> Fix item-drop handling of kit sheets

packs/data/extinction-curse-bestiary.db/doblagub.json
=> Audit Doblagub (Extinction Curse)

src/module/canvas/perception/modes.ts, src/module/scene/token-document/document.ts, types/foundry/client/pixi/perception/detection-mode.d.ts
=> Add support for tremorsense in RBV

src/module/apps/compendium-browser/index.ts, src/module/apps/compendium-browser/tabs/action.ts, src/module/apps/compendium-browser/tabs/base.ts, src/module/apps/compendium-browser/tabs/bestiary.ts, src/module/apps/compendium-browser/tabs/data.ts, src/module/apps/compendium-browser/tabs/equipment.ts, src/module/apps/compendium-browser/tabs/feat.ts, src/module/apps/compendium-browser/tabs/hazard.ts, src/module/apps/compendium-browser/tabs/spell.ts, static/templates/compendium-browser/partials/action.html, static/templates/compendium-browser/partials/bestiary.html, static/templates/compendium-browser/partials/equipment.html, static/templates/compendium-browser/partials/feat.html, static/templates/compendium-browser/partials/hazard.html, static/templates/compendium-browser/partials/spell.html
[comp-mini-search.webm](https://user-images.githubusercontent.com/41452412/190854899-5423e832-f51a-443c-b3e3-98224ce64bf2.webm)
=> Update Compendium Browser text search to utilize `MiniSearch`

src/module/actor/character/helpers.ts, src/module/actor/character/index.ts
+ move helper to helpers file (probably should be sheet data?)
=> Make several `CharacterPF2e` methods #private

src/module/actor/character/helpers.ts, src/module/actor/character/index.ts
=> Revert "Make several `CharacterPF2e` methods #private"

.betterer.results, src/module/system/text-editor.ts, src/scripts/hooks/render-journal-text-page-sheet.ts, src/scripts/ui/user-visibility.ts
=> Pass `JournalEntryTextPage` to `UserVisibility` processing

packs/data/backgrounds.db/legacy-of-the-hammer.json
=> Rename Legacy of the Hammer background

packs/data/feats.db/dragons-rage-breath.json
=> Add a rollable save to Dragon's Rage Breath

static/templates/actors/character/tabs/proficiencies.html
actor skills raw data still uses short form unfortunately.
=> Fix regression with editing character skill proficiency

packs/data/pathfinder-bestiary.db/uthul.json
=> Fix language known by Uthuls (bestiary 1)

packs/data/outlaws-of-alkenstar-bestiary.db/gold-tank-broker.json
=> Fix token name of Gold Tank Broker

system.json
Flags available everywhere now o_O
=> Run system.json through `System#migrateManifest`

src/styles/actor/character/_inventory.scss, static/templates/actors/partials/item-line.html
Closes #1923
Also spotted a bug with mystified items showing the mystified name in parentheses instead of the original name, will open a separate PR with a fix for that.
=> Add rarity colors to player inventory

CHANGELOG.md, package-lock.json, package.json, system.json
Cherry-picking 6dae643526a0fc781b183a44905be7e69fdc3a32 for a patch release
=> Release Notes 4.1.3

src/module/item/base.ts, src/module/system/statistic/index.ts, src/module/system/text-editor.ts, src/scripts/hooks/render-chat-message.ts, src/scripts/ui/inline-roll-links.ts
Item context is still absent: using the core enrichers API means we're never getting an item in the roll data.
Closes #4162
=> Fix loss of actor context in item card @Checks

src/styles/_fonts.scss, src/styles/ui/_dialog.scss
=> Tweak styling of roll dialog

src/styles/actor/npc/_index.scss, static/templates/actors/npc/partials/sidebar.html
Fixed width icons while I was at breaking everyone's muscle memory 😊
=> Reorder NPC IWR to match convention + lineup icon widths

packs/data/pathfinder-bestiary-3.db/living-graffiti-oil.json
I'll add the other variants as separate creatures once this is in.
=> Review B3 - living graffiti oil

src/module/actor/hazard/sheet.ts, static/templates/actors/hazard/partials/header.html, static/templates/actors/hazard/partials/sidebar.html, static/templates/actors/npc/partials/sidebar.html
=> Show resistance exceptions in hazard IWR

src/module/apps/world-clock/animate-darkness.ts, src/styles/scene/_darkness-adjuster.scss, types/foundry/client/pixi/placeables-layer/lighting-layer.d.ts
Also tweak interactivity of scene darkness adjuster
=> Replace use of deprecated `LightingLayer#animateDarkness`

src/module/item/spellcasting-entry/data/types.ts, src/module/item/spellcasting-entry/index.ts, static/lang/en.json, static/templates/actors/spellcasting-dialog.html
=> Add ability to restrict item spellcasting to scrolls only

src/module/rules/rule-element/flat-modifier.ts, src/module/system/damage/weapon.ts
=> Allow FlatModifier REs to only (or never) apply to critical damage

src/module/rules/rule-element/damage-dice.ts
=> Restore `critical` booleans added from DamageDice REs

packs/data/spells.db/enervation.json
=> Fix enervation damage error

packs/data/classfeatures.db/fourth-doctrine-cloistered-cleric.json, packs/data/classfeatures.db/third-doctrine-warpriest.json
Also update description on warpriest's 3rd doctrine
=> Add REs and update description on cloistered cleric's 4th doctrine

src/module/system/settings/variant-rules.ts
I missed one. :slightly_frowning_face:
=> Remove one more superfluous `for await`

packs/data/equipment.db/thundering-greater.json
=> Fix Greater Thundering Rune description

src/styles/actor/_inventory.scss, src/styles/actor/character/_inventory.scss
=> Match character inventory with npc and put traits at the top

packs/data/equipment.db/staff-of-healing-true.json
Fixes https://github.com/foundryvtt/pf2e/issues/4277
=> List correct bonus value in Staff of Healing (True)

packs/data/pathfinder-bestiary-2.db/adult-crystal-dragon-spellcaster.json, packs/data/pathfinder-bestiary-2.db/adult-crystal-dragon.json, packs/data/pathfinder-bestiary-2.db/ancient-crystal-dragon-spellcaster.json, packs/data/pathfinder-bestiary-2.db/ancient-crystal-dragon.json, packs/data/pathfinder-bestiary-2.db/young-crystal-dragon-spellcaster.json, packs/data/pathfinder-bestiary-2.db/young-crystal-dragon.json
Will fix https://github.com/foundryvtt/pf2e/issues/4266
=> Audit Crystal Dragons (B2)

src/module/actor/creature/data.ts, src/module/actor/creature/index.ts, src/module/rules/rule-element/base-speed.ts, src/module/rules/synthetics.ts
Closes #4275, supersedes #4287
=> Add support for RE-based land speeds

packs/data/menace-under-otari-bestiary.db/skeleton-guard-bb.json
Closes https://github.com/foundryvtt/pf2e/issues/4253
=> Fix weapon descriptions for BB Skeleton Warrior

src/scripts/config/index.ts, src/scripts/config/traits.ts, static/lang/en.json, static/licenses/OpenGameLicense.md
Adds license info for PFS 4-04 to 4-07 and Kingmaker
Adds missing tech trait
=> Update licensing and add missing trait

packs/data/feats.db/game-hunter-dedication.json, packs/data/feats.db/triple-shot.json, src/module/migration/migrations/793-make-predicates-arrays.ts
I'll add a followup migration but would like to get a patch release out
=> Catch one more unmigrated predicate property

src/module/actor/base.ts
=> Toggle defeated state for npcs when healed to above 0 hp when defeated.

static/templates/sidebar/actor-document-partial.html
=> Fix display of level in actor directory for level-zero actors

src/module/item/sheet/rule-elements/flat-modifier.ts, src/styles/item/_rules.scss, static/lang/re-en.json, static/templates/items/rules/flat-modifier.html
=> Add critical field to FlatModifier form

packs/data/feats.db/mountain-quake.json
=> Fix Mountain Quake requirement

src/module/apps/ui/chat-log.ts, src/module/chat-message/listeners/set-as-initiative.ts, src/util/misc.ts, static/templates/actors/npc/partials/sidebar.html
=> Change initiative fa-fist-raised icon to fa-swords

src/styles/ui/sidebar/_compendium-directory.scss
=> Fix distortion of actor portraits in compendium search results

src/styles/item/_heritage-sheet.scss, static/lang/en.json, static/templates/items/heritage-sidebar.html
=> Fix position of delete button on heritage's prerequisite ancestry

src/module/actor/character/index.ts
=> Restore ability-based domains for spellcasting

src/module/canvas/status-effects.ts
=> Restore re-rendering token HUD after mouse interactions

packs/data/pathfinder-bestiary-3.db/ostovite.json
https://2e.aonprd.com/Monsters.aspx?ID=1255
=> Add toggle for Ostovite's bone chariot

packs/data/feat-effects.db/effect-elemental-assault.json
=> Fix rule elements on Elemental Assault effect

src/module/scene/token-document/document.ts
=> Fix bidirectional diff of aura changes

src/module/system/statistic/index.ts
=> Create Statistic check/dc in constructor and full-load check/dc modifiers

src/styles/actor/npc/_spells.scss
Wasn't turning blue (CSS specificity issue)
=> Fix adjusted npc spell dc style

packs/data/pathfinder-bestiary.db/elemental-avalanche.json
=> Correct aura from 5 to 10 feet for elemental avalanche

packs/data/feats.db/virtuosic-performer-acting.json, packs/data/feats.db/virtuosic-performer-comedy.json, packs/data/feats.db/virtuosic-performer-dance.json, packs/data/feats.db/virtuosic-performer-keyboards.json, packs/data/feats.db/virtuosic-performer-oratory.json, packs/data/feats.db/virtuosic-performer-percussion.json, packs/data/feats.db/virtuosic-performer-singing.json, packs/data/feats.db/virtuosic-performer-strings.json, packs/data/feats.db/virtuosic-performer-winds.json
=> Standardize predicates for virtuosic performer

packs/data/equipment-effects.db/effect-earplugs-pfs-guide.json, packs/data/equipment.db/earplugs-pfs-guide.json, packs/data/equipment.db/earplugs.json
=> Add variant effect to PFS earplugs and correct links between effects and items

static/lang/re-en.json
=> Add localization keys for some equipment effects

packs/data/feats.db/sly-striker.json
Corrects predicates
Adds support for rogue dedication
Closes #4466
=> Update sly striker rule elements to function in V10

src/module/canvas/status-effects.ts, src/module/scene/token-document/document.ts
=> Avoid unnecessary redraw on unlinked token updates

packs/data/spells.db/rebounding-barrier.json
https://2e.aonprd.com/Spells.aspx?ID=813
=> Correct Rebounding Barrier Requirement to Trigger

packs/data/classfeatures.db/laughing-shadow.json, packs/data/classfeatures.db/sneak-attack.json, packs/data/feats.db/undead-slayer.json, src/global.d.ts, src/module/actor/creature/index.ts, src/module/rules/rule-element/roll-option.ts, src/module/system/settings/index.ts, static/lang/en.json, static/lang/re-en.json, static/templates/actors/character/tabs/actions.html
Will follow up with a migration
=> Move flat-footed toggle to relevant features, add setting to show

src/module/chat-message/chat-roll-details.ts
=> Put top level roll options at the top in the inspector

packs/data/feats.db/eternal-wings-aasimar.json, packs/data/feats.db/eternal-wings-sylph.json
=> Change Eternal Wings RE from speed.total to speed.base

src/module/actor/character/index.ts, src/module/actor/npc/index.ts, src/module/chat-message/chat-roll-details.ts, static/templates/chat/chat-roll-details.html
=> Include domains in character/npc strike roll inspector

packs/data/equipment.db/sack.json
The most critical PR in the entire history of the project.
=> Fix the quantity of sacks

src/module/item/armor/document.ts
=> Set the ID of a PC's worn armor as a roll option

packs/data/kingmaker-bestiary.db/nok-nok-level-1.json, packs/data/kingmaker-bestiary.db/nok-nok-level-5.json, packs/data/kingmaker-bestiary.db/tristan-level-1.json, packs/data/kingmaker-bestiary.db/tristan-level-10.json, packs/data/kingmaker-bestiary.db/valerie-level-1.json, packs/data/kingmaker-bestiary.db/valerie-level-9.json, packs/data/spells.db/dawnflowers-light.json
Correct Dawnflowers Light spell name and level
=> Add Nok-Nok, Tristan, and Valerie

packs/data/classfeatures.db/laughing-shadow.json, packs/data/classfeatures.db/phlogistonic-regulator.json, packs/data/classfeatures.db/sneak-attack.json
=> Fix formulas in Phlogistonic Regulator

packs/data/spells.db/sea-surge.json
=> Add damage to Sea Surge spell

src/module/chat-message/data.ts, src/module/chat-message/document.ts, src/module/system/damage/roll-dialog.ts, src/module/system/rolls.ts
=> Retrieve strike weapon item from damage as well

src/scripts/config/index.ts
=> Set Psyche trait description

src/module/system/rolls.ts
=> Adjust context.outcome based on result of reroll

src/module/item/consumable/document.ts
=> Adds pf2e flags with sourceId, uuid and type to used item chat message.

packs/data/equipment.db/signifiers-mask.json, packs/data/feats.db/hellknight-signifer-dedication.json
Closes #4447 
Supersedes #4456
=> Fully automate Hellknight Signifier Dedication

packs/data/spells.db/time-beacon.json
=> Correct duration for Time Beacon

packs/data/agents-of-edgewatch-bestiary.db/acidic-poison-cloud-trap.json
=> Fix inline check of Acidic Poison Cloud Trap

packs/data/pfs-introductions-bestiary.db/spiked-pit.json
=> Correct reference and text for spiked pit damage

packs/data/classfeatures.db/staff-nexus.json
Closes [#4638](https://github.com/foundryvtt/pf2e/issues/4638)
=> Fix Staff Nexus source

src/module/scene/token-document/document.ts, types/foundry/client/pixi/perception/vision-mode.d.ts
=> Nullish-coalesce when assigning from vision mode defaults

src/module/system/text-editor.ts
=> Get elite/weak modifier adjustments for inline checks

packs/data/equipment.db/torch.json
=> Fix Torch description

src/module/actor/creature/index.ts, src/module/actor/creature/values.ts, src/module/item/melee/document.ts
=> Adjust default reach of NPC attacks to use lower end of CRB Table 9-1

src/module/actor/character/sheet.ts
=> Fix quick alchemy feat

packs/data/spells.db/inner-radiance-torrent.json
=> Fix Inner Radiance Torrent Heightening

packs/data/extinction-curse-bestiary.db/hooklimb-xulgath.json, packs/data/extinction-curse-bestiary.db/resin-seep-xulgath.json, packs/data/extinction-curse-bestiary.db/thessekka.json
Brushup EC Book 3 NPCs: Hooklimb Xulgath, Resin-seep Xulgath, and Thessekka
=> Brushup EC Book 3 NPCs part 3

src/module/scene/token-document/document.ts, types/foundry/client/pixi/placeable-object/token.d.ts
Fixed based on @ghost91 's suggestion.
Closes #4568
=> Fix shield HP updates not being reflected in token resource bars

src/module/system/rolls.ts
Not just spells (as the old code did)
=> Show incapacitation note for all checks with the trait

packs/data/equipment.db/necklace-of-knives.json
=> Fix rule elements on Necklace of Knives

src/module/canvas/token/aura/renderer.ts
GMs are frequently getting confused when they're testing auras alone in their unlit bedrooms at 3AM, so this will hopefully help.
=> Render auras when GMs are logged in alone

packs/data/actions.db/hunt-prey.json, packs/data/actions.db/mark-for-death.json
Condenses flat modifiers for Hunt Prey and Mark for Death using the new multiple method.
Completes condensing of flat modifiers for action.db
=> Condense Flat Modifiers for Action.db

packs/data/pathfinder-bestiary-3.db/mothman.json, packs/data/pathfinder-bestiary-3.db/munavri-spellblade.json, packs/data/pathfinder-bestiary-3.db/myceloid.json, packs/data/pathfinder-bestiary-3.db/platecarpus.json, packs/data/pathfinder-bestiary-3.db/tylosaurus.json
=> Review Platecarpus, Tylosaurus, Mothman, Munavri Spellblade, Myceloid from Bestiary 3

packs/data/pathfinder-bestiary-3.db/giant-pangolin.json, packs/data/pathfinder-bestiary-3.db/manticore-paaridar.json, packs/data/pathfinder-bestiary-3.db/penanggalan.json, packs/data/pathfinder-bestiary-3.db/peri.json
=> Review Giant Pangolin, Manticore Paaridar, Peri, Penanggalan from Bestiary 3

packs/data/feats.db/no-escape.json
Closes [#4830](https://github.com/foundryvtt/pf2e/issues/4830)
=> Add trigger text to No Escape description.

packs/data/pathfinder-bestiary-3.db/giant-porcupine.json, packs/data/pathfinder-bestiary-3.db/popobawa.json, packs/data/pathfinder-bestiary-3.db/pukwudgie.json, packs/data/pathfinder-bestiary-3.db/quintessivore.json
=> Review Giant Porcupine, Popobawa, Pukwudgie, Quintessivore from Bestiary 3

packs/data/pathfinder-bestiary-3.db/sabosan.json, packs/data/pathfinder-bestiary-3.db/samsaran-anchorite.json, packs/data/pathfinder-bestiary-3.db/sasquatch.json, packs/data/pathfinder-bestiary-3.db/scalescribe.json
=> Review Sabosan, Samsaran Anchorite, Sasquatch, Scalescribe from Bestiary 3

packs/data/extinction-curse-bestiary.db/cu-sith.json, packs/data/extinction-curse-bestiary.db/herecite-of-zevgavizeb.json, packs/data/extinction-curse-bestiary.db/shoony-hierarch.json, packs/data/extinction-curse-bestiary.db/shoony-militia-member.json
=> Brushup EC Book 3 NPCs part 4

packs/data/extinction-curse-bestiary.db/buzzing-latch-rune.json, packs/data/extinction-curse-bestiary.db/explosive-furniture-trap.json, packs/data/extinction-curse-bestiary.db/xulgath-roughrider.json
Brushup: Explosive Furniture Trap, Buzzing Latch Rune, Xulgath Roughrider
=> Brushup EC Book 4 NPCs part 2

packs/data/bestiary-effects.db/effect-despoiler.json, packs/data/bestiary-effects.db/effect-entangling-train.json, packs/data/pathfinder-bestiary-3.db/esipil.json, packs/data/pathfinder-bestiary-3.db/kimenhul.json, packs/data/pathfinder-bestiary-3.db/nucol.json, packs/data/pathfinder-bestiary-3.db/pakalchi.json, packs/data/pathfinder-bestiary-3.db/wihsaak.json, packs/data/pathfinder-bestiary-3.db/ximtal.json
=> Review esipil, nucol, pakalchi, wihsaak, ximtal, kimenhul from Bestiary 3

src/styles/_colors.scss, src/styles/_globals.scss
First without the secret trait, second with
Once again, sorry github user `@Check`
=> Alter icon for secret inline checks

src/module/rules/rule-element/adjust-strike.ts
=> Change AdjustStrike to search item domain

packs/data/extinction-curse-bestiary.db/mukradi-summoning-runes.json, packs/data/extinction-curse-bestiary.db/sodden-sentinel.json, packs/data/extinction-curse-bestiary.db/tallow-ooze.json, packs/data/extinction-curse-bestiary.db/wight-cultist.json
Tallow Ooze, Sodden Sentinel, Wight Cultist, & Mukradi Summoning Runes
=> Brushup EC Book 4 NPCs part 3

src/module/apps/effects-panel.ts, src/module/item/effect/document.ts, src/module/system/effect-tracker.ts
=> Fix implementation of "automation.removeExpiredEffects" setting

packs/data/bestiary-effects.db/effect-remove-face.json, packs/data/extinction-curse-bestiary.db/aukashungi-swarm.json, packs/data/extinction-curse-bestiary.db/giant-aukashungi.json, packs/data/extinction-curse-bestiary.db/the-vanish-man.json, packs/data/extinction-curse-bestiary.db/xilvirek.json
The Vanish Man, Giant Aukashungi, Xilvirek, Aukashungi Swarm
=> Brushup EC Book 4 NPCs part 6

src/module/item/sheet/base.ts, src/module/item/sheet/data-types.ts, src/module/sheet/helpers.ts, src/styles/_tags.scss, static/templates/items/item-sheet.html
need to loop back around and do the same for NPCs; will move things into helpers then
=> Fix automatically-added item traits getting stored

static/templates/items/item-sheet.html
Supercedes #4917. Sorry, I had this done yesterday and forgot to push it up cause I was busy prepping for a sudden tuesday game.
=> Use presence of actionCost for item sheet action icon

packs/data/spells.db/fearful-feast.json, packs/data/spells.db/lift-natures-caul.json
Apparently these spells got errata in the hardcover.
=> Update AV spells to hardcover versions

packs/data/extinction-curse-bestiary.db/lyrt-cozurn.json, packs/data/extinction-curse-bestiary.db/spiked-barricade-trap.json, packs/data/extinction-curse-bestiary.db/war-sauropelta.json, packs/data/extinction-curse-bestiary.db/xulgath-gutrager.json
NPC List: Lyrt Cozurn, Xulgath Gutrager, Spiked Barricade Trap, War Sauropelta
=> Brushup EC Book 4 NPCs part 5

packs/data/equipment-effects.db/effect-cognitive-mutagen-greater.json, packs/data/equipment-effects.db/effect-cognitive-mutagen-lesser.json, packs/data/equipment-effects.db/effect-cognitive-mutagen-major.json, packs/data/equipment-effects.db/effect-cognitive-mutagen-moderate.json
Closes [#4903](https://github.com/foundryvtt/pf2e/issues/4903)
=> Fix cognitive mutagen effect descriptions

packs/data/bestiary-effects.db/effect-pfs-level-bump.json
2 and a half years later this closes #424
=> Add PFS level bump effect for NPCs

packs/data/equipment-effects.db/effect-spined-shield-spines.json, packs/data/equipment.db/spined-shield.json
=> Add effect to track Spined Shield spines

packs/data/feats.db/fearsome-brute.json
Closes #2212
There is only one thing in the system that can bring you to frightened 5 (peryton) and it's likely an oversight, other spells and effects hard cap at 4 and one was erratad to cap it at 4.
=> Automate Fearsome Brute

packs/data/equipment.db/tricky-pick.json
=> Add missing trait to Tricky Pick

packs/data/extinction-curse-bestiary.db/arskuva-the-gnasher.json, packs/data/extinction-curse-bestiary.db/helg-eats-the-eaters.json, packs/data/extinction-curse-bestiary.db/war-sauropelta.json, packs/data/extinction-curse-bestiary.db/xulgath-hardscale.json, packs/data/extinction-curse-bestiary.db/zashathal-head-taker.json
Xulgath Hardscale, Zashathal Head-Taker, Helg Eats-The-Eaters. Arskuva the Gnasher
Minor update to War Sauropelta that was automated by system
I will add TempHP effect to Renewed Vigor on Zashathal once the effect PR is merged into master
=> Brushup EC Book 4 NPCs part 7

packs/data/feats.db/monk-dedication.json
=> Grant Powerful Fist feature with Monk Dedication

packs/data/backgrounds.db/purveyor-of-the-bizarre.json, packs/data/feats.db/bizarre-transformation.json
Closes [#4954](https://github.com/foundryvtt/pf2e/issues/4954)
=> Fix spelling of Bizarre

src/module/actor/character/sheet.ts, src/module/actor/familiar/sheet.ts, src/module/actor/hazard/sheet.ts, src/module/actor/npc/sheet.ts, src/module/actor/sheet/base.ts, src/module/actor/vehicle/sheet.ts, src/styles/actor/loot/_index.scss, static/lang/en.json, static/templates/actors/loot/sheet.html, static/templates/actors/loot/sidebar.html
Fixes the carried bulk above inventory bug for players as well.
=> Touchup loot sheet styling

packs/data/abomination-vaults-bestiary.db/dreshkan.json
=> Update dreshkan needle spray save from Hardcover errata

static/lang/en.json
Fixes https://github.com/foundryvtt/pf2e/issues/4987
=> Update en.json to include missing trait name

src/module/actor/sheet/item-summary-renderer.ts, src/module/item/equipment/document.ts, src/scripts/ui/user-visibility.ts, src/styles/actor/_inventory.scss, static/templates/actors/partials/item-line.html
=> Clean up user visibility in inventory lines and summaries

src/module/actor/creature/sheet.ts, src/module/actor/hazard/index.ts, src/module/actor/hazard/sheet.ts, src/module/actor/helpers.ts, src/module/actor/npc/index.ts, src/module/actor/npc/sheet.ts, src/module/actor/npc/types.ts, src/module/actor/sheet/base.ts, src/module/chat-message/document.ts, src/module/system/check/check.ts, static/templates/actors/hazard/sheet.html, static/templates/actors/npc/partials/attack.html, static/templates/actors/npc/tabs/main.html
=> Have hazards use `StrikeData` objects

packs/data/extinction-curse-bestiary.db/bugul-noz.json
as per https://2e.aonprd.com/Monsters.aspx?ID=516
=> Fix innate spells of Bugul Noz

packs/data/extinction-curse-bestiary.db/bugul-noz.json, packs/data/extinction-curse-bestiary.db/wight-cultist.json
\+ random normalization of Bugul Noz JSON
=> Fix predicate on Wight Cultist ability

src/module/actor/character/index.ts, src/module/actor/character/sheet.ts, src/module/actor/modifiers.ts, src/module/item/spell/document.ts, src/module/system/statistic/index.ts
Bonus: Strikes are Ability Score then Proficiency like everything else is now.
=> Add support for proficiency modifier adjustments

static/templates/items/action-details.html
Something very minor before we start going in with a larger brush.
=> Make action cost in action sheet like the feat one

packs/data/heritages.db/elfbane-hobgoblin.json
=> Fix ancestry record for Elfbane Hobgoblin

packs/data/feats.db/raging-athlete.json
=> Fix description of Raging Athlete feat

static/lang/re-en.json
Closes [#5087](https://github.com/foundryvtt/pf2e/issues/5087)
=> Add Sparkling Targe Defending checkbox label

src/styles/actor/loot/_index.scss
Mostly just uses the squishier font for the title.
=> Add more loot sheet touchups

package-lock.json, package.json
Just getting this in so other dependencies can be updated without breaking my parsing branch :)
=> Add Peggy as a dependency

packs/data/pathfinder-bestiary.db/marid.json, packs/data/pfs-season-2-bestiary.db/perizia-5-6.json, packs/data/pfs-season-2-bestiary.db/perizia-7-8.json
=> Standardize 'Good or Evil Only' parentheticals

packs/data/feats.db/solar-rejuvenation-ghoran.json
=> Fix name of Solar Rejuvenation

packs/data/extinction-curse-bestiary.db/vermlek.json, packs/data/pfs-season-2-bestiary.db/vermlek-centaur-3-4.json, packs/data/pfs-season-2-bestiary.db/vermlek-centaur-5-6.json
Closes https://github.com/foundryvtt/pf2e/issues/5160
=> Change vermlek Unsettling Movement to passive

src/styles/_globals.scss
For Nath, who refuses to delete a few paltry characters.
=> Allow easier styling of gm only text

src/module/chat-message/document.ts, src/module/chat-message/listeners/cards.ts, src/module/item/spell/document.ts
This changes loadVariant() to also perform basic heightening as well. Sometime during next release we should cut the cord on saving spells to the DOM....
=> Fix variant spells for consumable items

packs/data/spells.db/noxious-vapors.json
Closes https://github.com/foundryvtt/pf2e/issues/5170
=> Add emanation to Noxious Vapors

packs/data/bestiary-effects.db/effect-harmonizing-aura-allies.json, packs/data/bestiary-effects.db/effect-harmonizing-aura-enemies.json, packs/data/bestiary-effects.db/effect-nymph-queens-inspiration.json, packs/data/bestiary-effects.db/effect-resonance.json
Condenses flat modifiers using the new multiple method for, Effect: Resonance, Effect: Nymph Queen's Inspiration and Effect: Harmonizing Aura both Enemies and Allies
Completes condensing of flat modifiers for bestiary-effects.db
Importing updated expiry to the new default value, and added the unidentified and badge fields
=> Condense flat modifiers for bestiary-effects.db

src/module/rules/rule-element/mark-token/prompt.ts
=> Localise MarkTarget RE's cancel notification

src/module/apps/sidebar/chat-log.ts, types/foundry/client/application/sidebar/sidebar-tab/chat-log.d.ts
=> Handle damage rolls from chat log input

packs/data/equipment.db/torch.json, src/module/rules/rule-element/strike.ts
Closes #5246, also updates torch item
=> Add support for including "other tags" in Strike REs

src/module/system/damage/damage.ts
=> Don't draw vertical divider after traits if no otherTags

static/lang/en.json, static/templates/dice/damage-roll.hbs
=> Add Shift-Click info to damage-application title text

src/module/actor/sheet/item-summary-renderer.ts, src/module/item/spell/document.ts
This should also catch almost all remaining errors involving heightening, hopefully, that I might not have caught.
=> Remove spell variant button from item summary

src/module/actor/character/index.ts, src/module/item/spell/document.ts, src/module/item/spell/helpers.ts, src/module/system/damage/damage.ts, src/module/system/damage/weapon.ts, src/scripts/dice.ts, src/util/misc.ts
=> Added support for spell damage traits, modifier breakdown, and damage instances

packs/data/classfeatures.db/implements-empowerment.json, packs/data/spell-effects.db/spell-effect-gravity-weapon.json, src/module/actor/character/automatic-bonus-progression.ts, src/module/item/weapon/document.ts, src/module/item/weapon/sheet.ts, src/module/system/damage/weapon.ts, src/module/system/settings/variant-rules.ts, src/styles/item/_index.scss, static/lang/en.json, static/templates/items/weapon-details.html
Closes #4148, #4460 
At level 15 with ABP and gravity weapon:
=> Have striking runes modify weapon damage dice directly

packs/data/feats.db/fang-sharpener.json, packs/data/heritages.db/razortooth-goblin.json
=> Add REs to Fang Sharpener feat

src/module/actor/modifiers.ts, src/module/rules/rule-element/damage-dice.ts, src/module/system/damage/damage.ts, src/module/system/damage/formula.ts, src/module/system/damage/roll.ts, src/module/system/damage/weapon.ts, static/lang/en.json, static/templates/dice/damage-roll.hbs, types/foundry/client/roll.d.ts
=> Display persistent damage in damage-roll messages

src/module/item/spell/document.ts
I'll fix up flavor around when I refactor it for custom damage.
=> Include persistent damage in spell damage messages

src/module/system/damage/roll.ts, src/module/system/damage/terms.ts
This should be used particularly for determining persistent-damage stacking.
=> Add `DamageInstance#expectedValue` getter

src/module/system/settings/automation.ts, src/scripts/config/index.ts, src/styles/settings/_index.scss, static/lang/en.json
For now, it defaults to off unless in dev mode.
=> Add IWR automation setting

packs/data/conditions.db/persistent-damage.json, src/global.d.ts, src/module/canvas/status-effects.ts, src/module/item/abstract-effect/data.ts, src/module/item/condition/data.ts, src/module/item/condition/document.ts, src/module/item/condition/persistent-damage-dialog.ts, src/module/system/conditions/manager.ts, src/scripts/macros/edit-persistent.ts, src/scripts/macros/index.ts, src/scripts/set-game-pf2e.ts, src/styles/item/_index.scss, src/styles/item/_persistent-damage-dialog.scss, static/templates/items/persistent-damage-dialog.hbs
Missing
* Editing the name so it looks nice in the effect panel
* Damage type icons
* End of turn automation
* Macro in compendium
=> Add support for creating persistent damage with values

src/module/item/condition/data.ts, src/module/item/condition/document.ts, src/module/item/condition/persistent-damage-dialog.ts, src/module/system/damage/helpers.ts, src/module/system/text-editor.ts, src/styles/item/_persistent-damage-dialog.scss, src/util/misc.ts, static/lang/en.json, static/templates/items/persistent-damage-dialog.hbs
=> Make polish pass on persistent-damage dialog

packs/data/equipment.db/blade-of-the-black-sovereign.json
=> Fixes spelling of the Blade of the Black Sovereign

src/module/actor/creature/data.ts, src/module/actor/creature/document.ts, src/module/rules/rule-element/base-speed.ts, src/module/rules/synthetics.ts
=> Avoid double application of modifiers to speeds derived from land speed

packs/data/pfs-season-4-bestiary.db/dream-of-doom.json
=> Correct the spell list for Dream of Doom in PFS 4-07

src/module/encounter/combatant.ts, src/module/encounter/document.ts, src/module/item/condition/document.ts, src/module/system/damage/roll.ts
This doesn't have the recovery check stuff, this is just the basic auto-rolling.
=> Autoroll persistent damage on turn end

src/module/actor/base.ts, src/module/scene/token-document/document.ts, src/module/scene/token-document/sheet.ts, static/lang/en.json, static/templates/scene/token/partials/appearance.hbs, types/foundry/client/application/form-application/base.d.ts, types/foundry/client/application/form-application/token-config.d.ts
=> Add ability to disable token autoscaling from `TokenConfig`

packs/data/extinction-curse-bestiary.db/dyzallin-shraen.json, packs/data/extinction-curse-bestiary.db/imperious-darkside-mirror.json, packs/data/extinction-curse-bestiary.db/muurfeli.json, packs/data/extinction-curse-bestiary.db/urdefhan-high-tormentor.json, packs/data/extinction-curse-bestiary.db/xulgath-deepmouth.json
=> Brushup EC Book 5 NPCs part 6

src/module/rules/rule-element/battle-form/rule-element.ts
=> Fix using own modifier for battle form skills

src/module/chat-message/listeners/degree-of-success.ts, src/scripts/hooks/render-chat-message.ts
=> Fix errant natural 1 or 20 highlighting when TMun rolls 2d20

src/module/item/spell/data.ts, src/module/item/spell/document.ts, src/module/item/spell/sheet.ts, src/module/system/damage/types.ts, src/module/system/damage/values.ts, src/module/system/tag-selector/index.ts, src/scripts/config/index.ts, static/templates/items/spell-details.hbs
and fix a typing issue caused by a booboo I did, deleting more salt references. No salt here.
=> Fix spell material damage tags and restrict values

packs/data/age-of-ashes-bestiary.db/ingnovims-assistant.json
=> Correct inventory of Ingnovim's assistant

src/global.d.ts, src/module/actor/base.ts, src/module/actor/data/iwr.ts, src/module/apps/sidebar/chat-log.ts, src/module/chat-message/document.ts, src/module/chat-message/listeners/damage-buttons.ts, src/module/chat-message/listeners/damage-taken.ts, src/module/chat-message/listeners/index.ts, src/module/item/physical/runes.ts, src/module/system/damage/iwr.ts, src/module/system/damage/roll.ts, static/lang/en.json, static/templates/chat/damage/damage-taken.hbs, static/templates/chat/damage/iwr-breakdown.hbs
Following up fill in the tooltip in the new template (currently handlebars-commented out)
=> Add basic IWR

src/module/item/spell/document.ts
Early on DamageRoll used to throw an error on a failed parse, which was a bug, but it was what the original code hinged on. Now DamageRoll crashes when you try to receive the formula of an invalid roll instead.
I checked if the formulas were valid explicitly.
=> Fix sheet crashes caused by invalid spell formulas

src/module/item/spell/document.ts, src/module/system/damage/roll.ts
=> Include spell materials in message header

static/templates/actors/hazard/partials/sidebar.hbs
=> Update Hazard sheet sidebar template to new IWR format

packs/data/feats.db/overwhelming-blow.json, packs/data/feats.db/wolf-drag.json, static/lang/re-en.json
=> Change feats from DamageDice to AdjustStrike

src/module/actor/base.ts, src/module/actor/types.ts, src/module/chat-message/listeners/damage-buttons.ts, src/module/system/damage/iwr.ts
=> Apply IWR after manual multipliers and addends

packs/data/spells.db/wild-morph.json
=> Fix time symbol in Wild morph spell

packs/data/age-of-ashes-bestiary.db/veshumirix.json
Closes https://github.com/foundryvtt/pf2e/issues/5403
=> Fix Veshumirix Breath Weapon recharge

packs/data/spells.db/heal-animal.json
=> Fix time symbol in Heal companion spell

src/module/actor/base.ts, src/module/actor/hazard/document.ts, src/module/actor/helpers.ts, src/module/actor/loot/document.ts, src/module/actor/npc/document.ts, src/module/actor/values.ts, src/module/canvas/token/object.ts, src/module/item/base.ts, src/module/item/condition/document.ts, src/module/system/damage/iwr.ts, static/lang/en.json
=> Add support for condition immunity

src/module/item/condition/document.ts, src/module/system/settings/homebrew/data.ts, src/module/system/settings/homebrew/helpers.ts, src/module/system/settings/homebrew/menu.ts
Not sure if bugfix or enhancement.
=> Add custom damage types to IWR

roll-grammar.peggy, src/module/actor/base.ts, src/module/actor/data/iwr.ts, src/module/chat-message/listeners/damage-buttons.ts, src/module/system/damage/helpers.ts, src/module/system/damage/iwr.ts, src/module/system/damage/roll.ts, src/module/system/damage/terms.ts
=> Add support for critical-hits immunity

packs/data/spell-effects.db/spell-effect-organsight.json
=> Define Organsight damage as Precision Damage

src/module/rules/rule-element/token-image.ts
Closes https://github.com/foundryvtt/pf2e/issues/5438
=> Token image rule element bracketed value

src/module/item/spell/document.ts
=> Apply stacking rules to spell-damage modifiers

src/module/actor/base.ts, src/module/actor/data/iwr.ts, src/module/actor/types.ts, src/module/chat-message/listeners/damage-buttons.ts, src/module/item/spell/document.ts, src/module/item/weapon/document.ts, src/module/system/damage/iwr.ts
=> Add IWR support for ghost-touch runes, (not-)magical attacks, and spell schools

src/module/actor/base.ts, src/module/actor/types.ts, src/module/apps/sidebar/chat-log.ts, src/module/chat-message/helpers.ts, src/module/chat-message/listeners/damage-buttons.ts
Relocated the helpers to @module/chat-message/helpers to be shared by the chatlog context-menu entries
=> Fix healing button and damage application from message context menu

src/module/actor/data/iwr.ts
Maybe need some phrasing flexibility there :grin:
=> Add support for axe and arrow vulnerability

packs/data/agents-of-edgewatch-bestiary.db/lusca.json, packs/data/agents-of-edgewatch-bestiary.db/minchgorm.json
Closes https://github.com/foundryvtt/pf2e/issues/5485
=> Fix Grab on Minchgorm

packs/data/spells.db/gouging-claw.json
Closes https://github.com/foundryvtt/pf2e/issues/5404
=> Add Gouging Claw damage variants

src/module/system/damage/weapon.ts
=> Don't label every damage part of NPC attacks as "Base"

src/module/rules/rule-element/damage-dice.ts, src/module/rules/rule-element/flat-modifier.ts, src/module/system/damage/formula.ts, src/module/system/damage/types.ts, src/module/system/damage/values.ts
=> Fix inclusion and doubling of critical damage

src/module/chat-message/document.ts, src/module/system/damage/roll.ts
=> Hide damage-instance breakdown from private damage rolls

src/styles/system/_effects-panel.scss
=> Fix overflow in effect panel from longer badges

src/module/system/damage/roll.ts, src/scripts/handlebars.ts, src/styles/ui/sidebar/chat/_damage.scss, static/lang/en.json, static/templates/dice/damage-roll.hbs
=> Ensure minimum damage totals of 1

src/module/system/damage/roll.ts, src/module/system/damage/terms.ts, types/foundry/client/roll-term/dice-term/die.d.ts
=> Add minimum- and maximum-value getters to damage roll and term classes

packs/data/extinction-curse-bestiary.db/shraen-graveknight.json
=> Remove non-RE weapons master entry from Shraen Graveknight NPC

packs/data/backgrounds.db/brevic-noble.json
Closes https://github.com/foundryvtt/pf2e/issues/5561
=> Fix Brevic Noble Garess to grant crafting rather than arcana

src/module/actor/sheet/popups/ability-builder.ts, src/module/item/ancestry/data.ts, src/module/item/ancestry/document.ts, src/module/migration/migrations/767-convert-voluntary-flaws.ts, src/styles/actor/character/_ability-builder.scss, static/lang/en.json, static/templates/actors/character/ability-builder.hbs
I'm pretty busy, so feel free to tweak the appearance of this at your leisure. The tooltips don't look as nice as what you had for example.
=> Add support for CRB 4.0 voluntary flaws

src/module/system/action-macros/crafting/craft.ts, src/module/system/action-macros/crafting/repair.ts, src/module/system/action-macros/crafting/select-item.ts, static/lang/en.json, static/templates/system/actions/craft-target-item.hbs, static/templates/system/actions/repair/select-item-dialog.hbs
Closes #5580.
These should really be `PickAThingPrompt`s that pull from formulas or owned items, but they at least work now.
=> Fix craft and repair macros

src/module/chat-message/data.ts, src/module/system/check/check.ts
=> Re-evaluate degree of success adjustments on reroll

packs/data/feats.db/burn-it.json, src/module/item/spell/document.ts, src/module/item/weapon/document.ts, src/module/rules/helpers.ts, src/module/system/damage/weapon.ts
=> Build out support for implementing Burn It!

src/module/item/consumable/document.ts, src/styles/ui/sidebar/chat/_damage.scss
Also snuck in a darkening of positive damage text shadow
=> Make damage rolls from consumables

packs/data/feats.db/conrasu-lore.json
Closes https://github.com/foundryvtt/pf2e/issues/5627
=> Add "Conrasu" trait to Conrasu Lore

src/module/system/damage/helpers.ts, src/module/system/damage/roll.ts, src/module/system/damage/terms.ts, src/styles/ui/sidebar/chat/_damage.scss
=> Show icon for precision damage

packs/data/equipment-effects.db/effect-apricot-of-bestial-might.json, packs/data/feats.db/tusks-half-orc.json, packs/data/feats.db/tusks-orc.json
Closes https://github.com/foundryvtt/pf2e/issues/5613
=> Add representative image to Apricot of Bestial Might strike

packs/data/feat-effects.db/effect-giants-stature.json, packs/data/feat-effects.db/effect-titans-stature.json, packs/data/spell-effects.db/spell-effect-enlarge-heightened-4th.json, packs/data/spell-effects.db/spell-effect-enlarge.json, packs/data/spell-effects.db/spell-effect-evolution-surge-huge.json, packs/data/spell-effects.db/spell-effect-evolution-surge-large.json
I think I got these right, but let me know if there are corrections to be made.
=> Set reach in several CreatureSize REs

packs/data/abomination-vaults-bestiary.db/jafaki.json, packs/data/abomination-vaults-bestiary.db/observation-deck-seugathi-researcher.json, packs/data/abomination-vaults-bestiary.db/seugathi-guard.json, packs/data/abomination-vaults-bestiary.db/seugathi-reality-warper.json, packs/data/abomination-vaults-bestiary.db/seugathi-researcher.json, packs/data/abomination-vaults-bestiary.db/seugathi-servant.json, packs/data/quest-for-the-frozen-flame-bestiary.db/summer-hora-queen.json, static/lang/re-en.json
Closes https://github.com/foundryvtt/pf2e/issues/5635
=> Fix Jakaki's Mindfog Aura to be passive. Add Aura RE to Mindfog Aura.

packs/data/equipment.db/alignment-ampoule-greater.json, packs/data/equipment.db/alignment-ampoule-lesser.json, packs/data/equipment.db/alignment-ampoule-major.json, packs/data/equipment.db/alignment-ampoule-moderate.json
Closes https://github.com/foundryvtt/pf2e/issues/5432
=> Add splash trait to Alignment Ampoule

system.json
In line with https://2e.aonprd.com/Rules.aspx?ID=804
=> Rename Deity Boons and Curses compendium to Divine Intercessions

src/module/item/physical/runes.ts, src/module/system/damage/damage.ts, src/module/system/damage/iwr.ts, src/module/system/damage/roll.ts, src/module/system/damage/types.ts, src/module/system/damage/weapon.ts, static/lang/en.json, static/templates/chat/damage/iwr-breakdown.hbs
Just weapon property runes for now
=> Start adding resistance ignoring

packs/data/kingmaker-bestiary.db/imeckus-stroon.json
=> Add Imeckus Stroon

packs/data/heritages.db/clawed-catfolk.json, packs/data/heritages.db/monstrous-skeleton.json
=> Add weapon base type to claws from two heritages

packs/data/outlaws-of-alkenstar-bestiary.db/rust-ooze.json
Closes https://github.com/foundryvtt/pf2e/issues/5688
=> Add metal resistance to Rust Ooze

packs/data/equipment.db/gun-sword.json
This corrects a singular error discovered over the course of preparation.
=> Corrected gun sword category

src/module/item/physical/runes.ts
=> Revert "Remove notes from greater flaming rune"

system.json
=> Hyphenate phrasal adjective in "Adventure Specific Actions"

packs/scripts/run-migration.ts, src/module/migration/migrations/815-consumable-data-cleanup.ts, src/module/migration/migrations/index.ts, src/module/migration/runner/base.ts
This has gotten bad enough to break stackability-testing, so time to clean up
=> Migrate away cruft from consumables

src/styles/actor/character/_feats.scss
=> Tweak styling of nested feats on PC sheets

packs/data/impossible-lands-bestiary.db/stone-sister.json
Closes https://github.com/foundryvtt/pf2e/issues/5730
=> Added Curse of Stone to Stone Sister's attacks

packs/data/age-of-ashes-bestiary.db/tarrasque-the-armageddon-engine.json
=> Correct will save of Tarrasque

packs/data/actions.db/long-term-rest.json
Closes https://github.com/foundryvtt/pf2e/issues/5733
=> Add hyphen to long-term rest action name

roll-grammar.peggy
=> Have damage-formula parser accept dice with no `number`

src/module/chat-message/document.ts, src/module/chat-message/helpers.ts, static/templates/chat/persistent-damage-recovery.hbs
Bonus: do not require the token to be selected
=> Fix visibility of persistent-damage recovery button

src/module/chat-message/helpers.ts
=> Quote message IDs in query selector strings

src/styles/_colors.scss, src/styles/_globals.scss, src/styles/mixins/_animations.scss, src/styles/mixins/_frames.scss, src/styles/scene/_darkness-adjuster.scss, src/styles/ui/_app-ui.scss, src/styles/ui/_controls.scss, src/styles/ui/_index.scss, src/styles/ui/_navigation.scss
Notably no changes* to Hotbar, Sidebar, Chat Messages, Placeables HUD, Effect Panel in this PR.
(*Slight changes due to global style overwrites)
There's been quite a few eyes on these changes, since they're used as-is in recent version of Dorako UI, and I've gotten no reports of these changes breaking anything. 
Pictures of premium modules not breaking:
=> Update scene navigation, scene controls, and app UI

packs/data/iconics.db/fumbus-level-1.json, packs/data/iconics.db/fumbus-level-3.json, packs/data/iconics.db/fumbus-level-5.json, packs/data/iconics.db/kyra-level-5.json, packs/data/iconics.db/lem-level-1.json, packs/data/iconics.db/lem-level-5.json, packs/data/iconics.db/quinn-level-1.json, packs/data/iconics.db/quinn-level-5.json, packs/data/iconics.db/sajan-level-1.json, packs/data/iconics.db/sajan-level-5.json, packs/data/paizo-pregens.db/ekene.json, packs/data/paizo-pregens.db/jadren-tagar.json, packs/data/paizo-pregens.db/kangir.json, packs/data/paizo-pregens.db/oraka.json, packs/data/paizo-pregens.db/popcorn.json, packs/data/paizo-pregens.db/savshin-starwatcher.json, packs/data/paizo-pregens.db/zane-ikundi.json
Replaced all bombs on iconics/pregens. 
Also checked for resistances but it seemed like those were okay.
=> Iconic/Pregen IWR Bomb Refresh

src/module/item/sheet/base.ts
=> Keep tabs from shifting in item sheet when changing to rules tab

packs/data/actions.db/blood-feast.json, packs/data/actions.db/drain-life.json, packs/data/actions.db/gallop.json, packs/data/actions.db/screaming-skull.json, packs/data/actions.db/take-a-taste.json, packs/data/actions.db/telekinetic-assault.json
Closes https://github.com/foundryvtt/pf2e/issues/5697
=> Add missing AC and Eidolon Actions from BotD

roll-grammar.peggy
=> Add support for dice term modifiers to parser generator

packs/data/conditions.db/unconscious.json
=> Set `allowDuplicate` to `false` for Unconscious condition's grant of Prone

src/module/apps/sidebar/compendium-directory.ts, src/module/migration/runner/index.ts, static/lang/en.json, types/foundry/client/collections/compendium-collection.d.ts, types/foundry/common/abstract/document.d.ts
=> Add support for right click migrate compendium (dev only)

src/module/item/affliction/data.ts, src/module/item/affliction/sheet.ts, src/styles/item/_index.scss, static/templates/items/affliction-details.hbs
=> Add affliction damage and conditions

packs/data/feats.db/slag-may.json, src/module/actor/modifiers.ts, src/module/item/spell/document.ts, src/module/item/spell/helpers.ts, src/module/rules/rule-element/damage-dice.ts
=> Add damage dice support to spells

src/module/actor/creature/sheet.ts
Leftovers from another PR :shrug:
=> Remove a couple uses of jquery from creature sheet

packs/data/iconics.db/feiya-level-1.json, packs/data/iconics.db/feiya-level-5.json, packs/data/iconics.db/fumbus-level-1.json, packs/data/iconics.db/fumbus-level-3.json, packs/data/iconics.db/fumbus-level-5.json, packs/data/iconics.db/jirelle-level-1.json, packs/data/iconics.db/jirelle-level-5.json, packs/data/iconics.db/korakai-level-1.json, packs/data/iconics.db/korakai-level-5.json, packs/data/iconics.db/kyra-level-1.json, packs/data/iconics.db/kyra-level-3.json, packs/data/iconics.db/kyra-level-5.json, packs/data/iconics.db/lem-level-1.json, packs/data/iconics.db/lem-level-5.json, packs/data/iconics.db/lini-level-1.json, packs/data/iconics.db/lini-level-5.json, packs/data/iconics.db/quinn-level-1.json, packs/data/iconics.db/quinn-level-5.json, packs/data/iconics.db/sajan-level-1.json, packs/data/iconics.db/sajan-level-5.json, packs/data/iconics.db/seelah-level-1.json, packs/data/iconics.db/seelah-level-5.json, packs/data/iconics.db/seoni-level-1.json, packs/data/iconics.db/seoni-level-5.json, packs/data/iconics.db/valeros-level-1.json, packs/data/iconics.db/valeros-level-3.json, packs/data/iconics.db/valeros-level-5.json
Refreshed iconic actors to use updated options from compendia for usability and better translation support.
=> Refresh Iconic.db actors from compendia

src/global.d.ts, src/module/item/condition/document.ts, src/module/item/spell/document.ts, src/module/system/damage/damage.ts, src/module/system/damage/formula.ts, src/module/system/damage/iwr.ts, src/module/system/damage/roll.ts, src/module/system/damage/terms.ts, src/module/system/settings/index.ts
=> Restore crit dice doubling

packs/data/age-of-ashes-bestiary.db/accursed-forge-spurned.json, packs/data/age-of-ashes-bestiary.db/aiudara-wraith.json, packs/data/age-of-ashes-bestiary.db/belmazog.json, packs/data/age-of-ashes-bestiary.db/gerhard-pendergrast.json, packs/data/age-of-ashes-bestiary.db/hellcrown.json, packs/data/age-of-ashes-bestiary.db/immortal-ichor.json, packs/data/age-of-ashes-bestiary.db/living-sap.json, packs/data/age-of-ashes-bestiary.db/mud-spider.json, packs/data/age-of-ashes-bestiary.db/renali.json, packs/data/age-of-ashes-bestiary.db/rusty-mae.json, packs/data/age-of-ashes-bestiary.db/seismic-spears-trap.json, packs/data/age-of-ashes-bestiary.db/skeletal-hellknight.json, packs/data/age-of-ashes-bestiary.db/spiritbound-aluum.json, packs/data/age-of-ashes-bestiary.db/tixitog.json, packs/data/age-of-ashes-bestiary.db/trapped-lathe.json, packs/data/age-of-ashes-bestiary.db/tree-of-dreadful-dreams.json, packs/data/age-of-ashes-bestiary.db/vazgorlu.json, packs/data/age-of-ashes-bestiary.db/zephyr-guard.json, packs/data/age-of-ashes-bestiary.db/zuferian.json
=> Add slugs to attack effects for Age of Ashes

src/module/rules/rule-element/damage-dice.ts
=> Fix resolving of brackets in `DamageDiceRuleElement`

packs/data/iconics.db/fumbus-level-1.json, packs/data/iconics.db/fumbus-level-3.json, packs/data/iconics.db/fumbus-level-5.json, packs/data/kingmaker-bestiary.db/jubilost-level-1.json, packs/data/kingmaker-bestiary.db/jubilost-level-8.json, packs/scripts/run-migration.ts, src/module/migration/migrations/816-alchemist-research-fields.ts
Completes https://github.com/foundryvtt/pf2e/pull/5251
=> Complete Migration 816

packs/data/feats.db/ghost-hunter.json, src/module/actor/base.ts, src/module/rules/rule-element/adjust-strike.ts, static/lang/re-en.json
With Ghost Hunter ancestry feat as proof of concept
=> Add support for AdjustStrike adding/removing weapon property runes

packs/data/classfeatures.db/field-discovery-bomber.json, packs/data/classfeatures.db/field-discovery-chirurgeon.json, packs/data/classfeatures.db/field-discovery-mutagenist.json, packs/data/classfeatures.db/field-discovery-toxicologist.json, packs/data/iconics.db/fumbus-level-5.json, packs/data/kingmaker-bestiary.db/jubilost-level-8.json, packs/scripts/run-migration.ts, src/module/actor/character/crafting/entry.ts, src/module/migration/migrations/816-alchemist-research-fields.ts, src/module/migration/migrations/817-field-discovery-predicates.ts, src/module/migration/migrations/index.ts, src/module/migration/runner/base.ts, src/module/rules/rule-element/crafting/entry.ts
Includes fix of the Chirurgeon's field discovery
Closes #5899
=> Convert field discovery REs to predicates

packs/data/feats.db/agile-shield-grip.json
Possible pain points:
* wasn't quite sure about the domain
* localization?
* double shield character?
(Not working properly on current master, because of #5897)
=> Add RollOption and automation for Agile Shield Grip

src/module/actor/character/document.ts, src/module/system/damage/damage.ts, src/module/system/damage/formula.ts, src/module/system/damage/types.ts, src/module/system/damage/weapon.ts, src/util/misc.ts
Part 1 for spells using the same damage pipeline as everything else.
=> Refactor damage breakdown to be part of formula creation

src/module/item/spell/document.ts
=> Fix spell variant levels not being able to heightened downwards

src/module/apps/effects-panel.ts
Also removes blocking of value changes/removals of locked effects, allowing `GrantItem` to handle it.
=> Expunge JQuery usage from EffectsPanel application

packs/data/equipment.db/candle.json, static/lang/re-en.json
Closes https://github.com/foundryvtt/pf2e/issues/5946
=> Add TokenLight rule element and toggle to candle

packs/data/feats.db/goloma-courage.json
=> Add missing automation to Goloma Courage

packs/data/kingmaker-bestiary.db/amiri-level-1-kingmaker.json, packs/data/kingmaker-bestiary.db/amiri-level-11-kingmaker.json, packs/data/kingmaker-bestiary.db/jubilost-level-1.json, packs/data/kingmaker-bestiary.db/jubilost-level-8.json, packs/data/kingmaker-bestiary.db/nok-nok-level-1.json, packs/data/kingmaker-bestiary.db/nok-nok-level-5.json, packs/data/kingmaker-bestiary.db/tristian-level-1.json, packs/data/kingmaker-bestiary.db/tristian-level-10.json
Also fixed a little annoying bug with Amiri's Raging Intimidation grant
=> Make Kingmaker PCs allied with party

packs/data/pfs-season-4-bestiary.db/sounrel-3-4.json, packs/data/pfs-season-4-bestiary.db/sounrel-5-6.json, packs/data/spells.db/horrific-visage.json
Closes https://github.com/foundryvtt/pf2e/issues/5998
=> Add emanation to Horrific Visage

packs/data/feats.db/brilliant-crafter.json
Closes https://github.com/foundryvtt/pf2e/issues/5983
=> Fix Brilliant Crafter giving expert in Inventor class DC at level 15

src/module/system/damage/terms.ts
=> Simplify display formulas with double-dice crit setting

src/module/apps/effects-panel.ts, src/module/chat-message/document.ts, src/module/item/condition/document.ts, src/module/system/conditions/manager.ts, src/module/system/conditions/types.ts, src/styles/system/_effects-panel.scss, static/templates/system/effects-panel.hbs
=> Implement rolling persistent damage recovery from effect panel

packs/data/feats.db/zombie-dedication.json, src/module/item/weapon/document.ts, src/module/rules/rule-element/strike.ts, src/module/system/damage/weapon.ts, src/util/misc.ts, static/template.json
Example implementation with Zombie Dedication fist
=> Add support for shorthand Strike RE data to create standard fist attack

src/module/item/condition/persistent-damage-dialog.ts, src/styles/item/_persistent-damage-dialog.scss, static/lang/en.json, static/templates/items/persistent-damage-dialog.hbs
=> Add manual persistent damage roll to editor dialog

packs/data/classfeatures.db/giant-instinct.json, packs/data/iconics.db/amiri-level-1.json, packs/data/iconics.db/amiri-level-3.json, packs/data/iconics.db/amiri-level-5.json
=> Fix predicates on Giant Instinct resistance.

static/templates/items/weapon-details.hbs
=> Fix display of custom damage types on weapon sheet

src/module/actor/base.ts, src/module/apps/compendium-browser/index.ts, src/module/apps/sidebar/compendium-directory.ts, src/module/system/module-art.ts, src/util/misc.ts, types/foundry/common/abstract/document.d.ts
Also reorganizes preparation of module art, moving most of the heavy lifting to the module art class
=> Add support for setting `randomImg` (token property) in module art

src/module/item/affliction/document.ts
=> Set affliction badge label to Stage X

src/module/actor/base.ts, src/module/chat-message/document.ts, src/module/chat-message/listeners/damage-taken.ts, src/module/system/text-editor.ts, static/lang/en.json, static/templates/chat/damage/damage-taken.hbs
=> Obscure damage recipient names when tokenSetsNameVisibility is enabled

src/module/actor/sheet/base.ts, src/module/item/abstract-effect/data.ts, src/module/item/affliction/data.ts, src/module/item/effect/data.ts, src/scripts/system/dragstart-handler.ts, static/template.json
A bit of a crude solution for now: once we have system-defined indexing from the server we can link spells and their effects
=> Transmit traits from chat card spells/actions to drag & drop effects

packs/data/equipment.db/gluttonous-spear.json, packs/data/the-slithering-bestiary.db/ahvothian.json, packs/data/the-slithering-bestiary.db/angazhani-cultist.json, packs/data/the-slithering-bestiary.db/fiendripping-blast-trap.json, packs/data/the-slithering-bestiary.db/nyamat-mshwe.json, static/lang/re-en.json
Also updates Gluttonous Spear.
=> Update The Slithering NPCs (part 2 of 4)

src/styles/actor/_header.scss, src/styles/actor/_index.scss, src/styles/actor/character/_header.scss, src/styles/actor/npc/_index.scss, src/styles/actor/vehicle/_index.scss, static/templates/actors/character/partials/header.hbs, static/templates/actors/vehicle/tabs/vehicle-details.hbs, static/templates/actors/vehicle/vehicle-header.hbs
=> Move vehicle traits to header, adjust PC hero point placement

src/module/canvas/status-effects.ts, src/module/item/condition/document.ts, src/module/system/settings/index.ts, src/styles/ui/_token-hud.scss, types/foundry/client/config.d.ts
- Ensure all conditions are border-highlighted when active
- Debounce re-renders and call from `ConditionPF2e`
- Make highlight border more visible when hovered
Closes #6101
=> Fix several bugs/display quirks with status effects panel

packs/data/equipment-effects.db/effect-slime-whip.json, packs/data/equipment.db/slime-whip.json, packs/data/the-slithering-bestiary.db/alchemical-golem-slithering.json, packs/data/the-slithering-bestiary.db/fuming-sludge.json, packs/data/the-slithering-bestiary.db/paga-nikohian.json, packs/data/the-slithering-bestiary.db/scroll-shock-trap.json, static/lang/re-en.json
=> Update The Slithering NPCs (part 4 of 4)

packs/data/abomination-vaults-bestiary.db/salaisa-malthulas.json, packs/data/age-of-ashes-bestiary.db/mialari-docur.json, packs/data/agents-of-edgewatch-bestiary.db/bloody-barber-goon.json, packs/data/agents-of-edgewatch-bestiary.db/grunka.json, packs/data/agents-of-edgewatch-bestiary.db/pelmo.json, packs/data/april-fools-bestiary.db/demom.json, packs/data/blood-lords-bestiary.db/shimmernewt.json, packs/data/book-of-the-dead-bestiary.db/relictner-eroder.json, packs/data/fists-of-the-ruby-phoenix-bestiary.db/joon-seo.json, packs/data/gatewalkers-bestiary.db/amelekana.json, packs/data/pathfinder-bestiary-3.db/arboreal-reaper.json, packs/data/pathfinder-bestiary-3.db/baykok.json, packs/data/pathfinder-bestiary-3.db/camel.json, packs/data/pathfinder-bestiary-3.db/gliminal.json
Still more to do after this but most of it is PFS.
=> Fix details of several ranged strikes

src/module/actor/character/data/types.ts, src/module/actor/character/document.ts, src/module/actor/character/sheet.ts, src/module/actor/data/base.ts, src/module/actor/helpers.ts, src/module/actor/npc/data.ts, src/module/actor/npc/index.ts, src/module/actor/sheet/base.ts, src/module/item/melee/data.ts, src/module/item/melee/document.ts, src/module/item/melee/sheet.ts, src/module/item/weapon/document.ts, src/module/migration/migrations/607-melee-item-damage-rolls.ts, src/module/system/damage/weapon.ts, src/scripts/config/damage.ts, src/scripts/config/index.ts, src/styles/item/_index.scss, src/styles/item/_melee-sheet.scss, static/lang/en.json, static/templates/actors/hazard/sheet.hbs, static/templates/actors/npc/partials/attack.hbs, static/templates/items/melee-details.hbs
Has a side effect of fixing NPC damage breakdowns
=> Add support for categorizing NPC damage partials

static/lang/en.json, static/templates/actors/spellcasting-dialog.hbs
=> Show Tradition Spellcasting instead of Magic Tradition when configuring spellcasting

packs/data/abomination-vaults-bestiary.db/volluk-azrinae.json, packs/data/kingmaker-bestiary.db/the-wriggling-man.json, packs/data/pathfinder-bestiary-2.db/worm-that-walks-cultist.json, packs/data/strength-of-thousands-bestiary.db/king-of-biting-ants.json
Closes https://github.com/foundryvtt/pf2e/issues/5893
=> Add persistent damage to worm that walks tendril

src/styles/actor/_header.scss
=> Add more tweaks to PC header alignment

packs/data/agents-of-edgewatch-bestiary.db/needling-stairs.json, packs/data/agents-of-edgewatch-bestiary.db/olansa-terimor.json, packs/data/blood-lords-bestiary.db/umbraex.json, packs/data/book-of-the-dead-bestiary.db/bhuta.json, packs/data/book-of-the-dead-bestiary.db/ghul.json, packs/data/kingmaker-bestiary.db/lesser-jabberwock.json, packs/data/malevolence-bestiary.db/architect-and-hunter.json, packs/data/malevolence-bestiary.db/wrathful-hatchet.json, packs/data/monsters-of-myth-bestiary.db/mosquito-witch-the-hemoprophet.json, packs/data/monsters-of-myth-bestiary.db/mosquito-witch-the-legion-leech.json, packs/data/monsters-of-myth-bestiary.db/mosquito-witch-the-swarm-seer.json, packs/data/monsters-of-myth-bestiary.db/mosquito-witch.json, packs/data/night-of-the-gray-death-bestiary.db/gray-gardener-enforcer.json, packs/data/night-of-the-gray-death-bestiary.db/miss-whisper.json, packs/data/pathfinder-bestiary-2.db/jabberwock.json, packs/data/pathfinder-bestiary.db/deinonychus.json, packs/data/pathfinder-bestiary.db/quetzalcoatlus.json, packs/data/pathfinder-bestiary.db/shining-child.json, packs/data/shadows-at-sundown-bestiary.db/ileosas-shell.json, packs/data/shadows-at-sundown-bestiary.db/scarlet-walker.json
Note: I believe Olansa Terimor had damage incorrectly entered as "acid" instead of "bleed".
=> Add persistent damage to some NPC attacks

packs/data/feats.db/fire-resistance.json
Add missing RE for Fire Resistance feat
https://2e.aonprd.com/Feats.aspx?ID=2973
=> Add resistance rule element to Fire Resistance feat

packs/data/feats.db/advantageous-assault.json, src/module/actor/character/document.ts, src/module/actor/data/base.ts, src/module/actor/helpers.ts, src/module/chat-message/data.ts, src/module/chat-message/listeners/cards.ts, src/module/item/spell/document.ts, src/module/rules/rule-element/adjust-modifier.ts, src/module/system/check/check.ts, src/module/system/check/types.ts, src/module/system/damage/damage.ts, src/module/system/damage/types.ts, src/module/system/damage/weapon.ts, src/module/system/rolls.ts, src/module/system/statistic/index.ts
Includes example implementation with Advantageous Assault
=> Include MAP increases in attack/damage roll contexts and roll options

packs/data/outlaws-of-alkenstar-bestiary.db/clearwater-cleaner.json, packs/data/outlaws-of-alkenstar-bestiary.db/dewey-daystar.json, packs/data/outlaws-of-alkenstar-bestiary.db/follower-of-shumfallow.json
=> add deathNote to Verdant Burst in OoA

packs/data/equipment.db/rowan-rifle.json, packs/data/equipment.db/tigers-claw.json
Closes https://github.com/foundryvtt/pf2e/issues/6173
=> Fix usage and bulk of Rowan Rifle

src/module/item/melee/sheet.ts, src/module/system/damage/formula.ts, static/lang/en.json
=> Allow NPC melee categorized partial without matching base

packs/data/feats.db/asura-magic.json, packs/data/feats.db/dominion-aura.json, packs/data/feats.db/idol-threat.json, packs/data/feats.db/jalmeri-rakshasa-magic.json, packs/data/feats.db/reveal-hidden-self.json
Closes https://github.com/foundryvtt/pf2e/issues/6197
=> Add missing feats from Impossible Lands

packs/data/actions.db/balance.json, packs/data/actions.db/borrow-an-arcane-spell.json, packs/data/actions.db/demoralize.json
Closes #5851
Even though this may not be strictly correct, imho it's better to at least have normalized behaviour.
=> Normalize "skill" actions by adding missing trait

packs/data/spells.db/terminate-bloodline.json
- Delete part of the description 
- Fix the number of secondary casters of the ritual
=> Fix terminate bloodline

src/scripts/ui/inline-roll-links.ts
=> Fix inline roll warning message

src/module/canvas/token/aura/renderer.ts, src/module/scene/document.ts, src/module/scene/helpers.ts, src/module/scene/token-document/aura/index.ts
Closes #6188
Also consolidates all checks for whether a scene is "in focus"
=> Don't render enemy visual/auditory auras to players

packs/data/pathfinder-bestiary.db/fire-mephit.json
Closes https://github.com/foundryvtt/pf2e/issues/6203
=> Change Fire Mephit Breath Weapon to unique id

packs/data/feats.db/master-magus-spellcasting.json
Data Entry: Corrected wrong text of Master Magus Spellcasting feat
=> DataEntry: Corrected Master Magus Spellcasting feat

packs/data/abomination-vaults-bestiary.db/drow-cavern-seer.json, packs/data/abomination-vaults-bestiary.db/galudu.json, packs/data/abomination-vaults-bestiary.db/ladys-whisper.json
Found one more oddball - Galudu from abomination vaults had multiple copies of the same spells in his spellbook
=> Update abomination vaults Galudu

types/foundry/client/collections/world-collection/actors.d.ts, types/foundry/client/collections/world-collection/base.d.ts, types/foundry/client/collections/world-collection/items.d.ts, types/foundry/util.d.ts
The interface was miraculously preserved despite the heavy refactor. :open_mouth:
=> Update `WorldCollection` types for V10

static/template.json
=> Restore traits to heritage template.json defaults

src/module/item/sheet/base.ts, src/module/item/weapon/sheet.ts, src/util/misc.ts, static/templates/items/weapon-details.hbs
Also fixes their localized sorting
=> Restore inclusion of homebrew base weapon types to weapon sheet

src/module/actor/npc/sheet.ts, src/module/actor/npc/types.ts, src/module/item/sheet/base.ts, src/module/item/sheet/data-types.ts, src/module/sheet/helpers.ts, static/templates/actors/npc/partials/header.hbs, static/templates/items/item-sheet.hbs
=> Avoid persisting synthetic npc traits

packs/data/spells.db/searing-light.json
~~Waiting on https://github.com/foundryvtt/pf2e/pull/6263~~
=> Automate Searing Light good damage

packs/data/classfeatures.db/scoundrel.json
=> Add roll notes to the scoundrel for successful feints

src/module/canvas/status-effects.ts
This actually works out quite cleanly:
- If no token is controlled, right-clicking on a token also controls it.
- Right-clicking any token among a set of controlled tokens maintains the controlled status of all tokens.
- If a token isn't among those controlled when right-clicking it, controlled tokens are cleared, and the right-clicked token is then controlled.
=> Have status effects panel operate on all controlled tokens

packs/data/classfeatures.db/animal-order.json, packs/data/classfeatures.db/flame-order.json, packs/data/classfeatures.db/leaf-order.json, packs/data/classfeatures.db/stone-order.json, packs/data/classfeatures.db/storm-order.json, packs/data/classfeatures.db/wave-order.json, packs/data/classfeatures.db/wild-order.json, packs/data/feats.db/order-explorer.json
Fixes https://github.com/foundryvtt/pf2e/issues/5586.
=> Automate Order Explorer Feat

src/util/from-uuids.ts
`fromUuidSync` alawys returns the compendium index entry instead of the document (even if it is cached locally) so the cache check didn't work at all.
```js
...
if ( collection instanceof CompendiumCollection ) {
doc = doc ?? collection.index.get(documentId);
if ( doc ) doc.pack = collection.collection;
} else {
...
````
=> Fix `fromUUIDs` never returning cached compendium documents

src/module/actor/base.ts, src/module/actor/data/index.ts, src/module/actor/index.ts, src/module/actor/party/data.ts, src/module/actor/party/document.ts, src/module/actor/party/index.ts, src/scripts/config/index.ts, static/lang/en.json, static/template.json
Does nothing right now, this is here so people can start working on it.
=> Add blank party actor for dev worlds

packs/data/heritages.db/pixie.json
=> Increase reach in Pixie heritage's CreatureSize RE

src/module/apps/sidebar/encounter-tracker.ts, src/styles/ui/_combat.scss
=> Gussy up drag preview in encounter tracker

src/module/actor/npc/data.ts, src/module/actor/npc/document.ts
For use with critical specialization effects that require it
=> Add a fake class DC (set to level-based) to NPCs

packs/data/heritages.db/pixie.json, src/module/rules/rule-element/creature-size.ts
Also reverts 1027e52cdff71ec2b45ef7610d09c8bc07a7b666
=> Globally fix CreatureSize RE not adjusting reach to minimum for size

packs/data/feats.db/unburdened-iron.json, src/module/actor/character/document.ts, src/module/actor/creature/document.ts, src/module/actor/modifiers.ts, src/module/rules/rule-element/adjust-modifier.ts, src/module/system/check/check.ts, src/util/misc.ts
`ModifierAdjustment` could really benefit from being a class at this point rather than an interface. It'll be worth returning to refactor soon.
=> Expand modifier adjustments to fully support Unburdened Iron

src/module/canvas/helpers.ts, src/module/canvas/token/aura/util.ts, src/module/canvas/token/object.ts, src/module/scene/token-document/aura/index.ts
closes #4824
removed Pythagoras of 3 diagonals in favor of 3d counting of minecraft blocks.
=> Fix token distance measurement in 3D space

src/module/item/consumable/document.ts
Making room for consumable effect spinoffs
=> Have consumables suppress all their REs, tidy `consume` method

src/module/encounter/combatant.ts, src/module/encounter/document.ts, src/module/system/damage/damage.ts, src/scripts/macros/rest-for-the-night.ts, types/foundry/client/core/hooks.d.ts
Also changes all system calls of `Hooks.call` to `Hooks.callAll`
=> Call hook after Rest for the Night completes

src/module/actor/creature/sheet.ts, src/module/actor/sheet/base.ts, src/styles/actor/_spell-list.scss, src/styles/actor/character/_spellcasting.scss
=> Fix UI quirks, improve drop handling of spellcasting entries

packs/data/pathfinder-bestiary-2.db/bralani.json
Closes https://github.com/foundryvtt/pf2e/issues/6328
=> Fix Bralani inventory

src/module/apps/effects-panel.ts, src/styles/system/_effects-panel.scss, static/lang/en.json, static/templates/system/effects-panel.hbs
=> Change left click effect panel functionality for persistent to roll damage

packs/data/feats.db/desiccating-inhalation.json
Sorry for the lonely PR.
It is the last of my read proofing of the archetype in the journals
=> Fix formula of dessicating inhalation save

src/module/actor/character/document.ts
=> Ensure minimum value and max for PC XP

src/module/actor/creature/sheet.ts, src/module/item/spellcasting-entry/collection.ts, static/templates/actors/character/tabs/spellcasting.hbs
\+ minor tidying along the way
=> Make spell browser always available for focus spellcasting entries

src/module/item/melee/document.ts, src/module/item/weapon/document.ts, src/module/rules/rule-element/choice-set/rule-element.ts
=> Extend support for "ownAttacks" choice sets to melee items

src/module/system/action-macros/helpers.ts
=> Show degree-of-success notes first in action macros

packs/data/outlaws-of-alkenstar-bestiary.db/dewey-daystar.json
Closes https://github.com/foundryvtt/pf2e/issues/6422
=> Update Dewey Daystar's Heal, Magic Fang, and Wand of Healing

packs/data/agents-of-edgewatch-bestiary.db/siege-shard.json, packs/data/gatewalkers-bestiary.db/quarry-construct.json, packs/data/menace-under-otari-bestiary.db/animated-armor-bb.json, packs/data/pathfinder-bestiary-2.db/spiral-centurion.json, packs/data/strength-of-thousands-bestiary.db/living-sun-spire.json
Standardizes hardness into hardness field instead of as a HP note.
Closes #6421
=> standardize hardness data entry

packs/data/classfeatures.db/dragon-deviant-classification.json, packs/data/classfeatures.db/wraith-deviant-classification.json
Closes https://github.com/foundryvtt/pf2e/issues/6391
=> Fix dragon deviant storming breath escape and wraith deviant ghostly grab

packs/scripts/extract.ts, src/module/item/sheet/base.ts, src/styles/item/_index.scss, static/lang/en.json, static/templates/items/item-sheet.hbs
=> Improve GM notes UI

packs/data/equipment.db/animal-bed.json, packs/data/equipment.db/cage.json, packs/data/equipment.db/collar.json, packs/data/equipment.db/feed-standard.json, packs/data/equipment.db/feed-unique.json, packs/data/equipment.db/handling-gloves.json, packs/data/equipment.db/harness.json, packs/data/equipment.db/leash.json, packs/data/equipment.db/tank-stationary.json, packs/data/equipment.db/tank-traveling.json, packs/data/equipment.db/treat-standard.json, packs/data/equipment.db/treat-unique.json
=> Add basic pet shop equipment

src/module/actor/character/sheet.ts, src/module/apps/compendium-browser/index.ts, src/module/apps/compendium-browser/tabs/action.ts, src/module/apps/compendium-browser/tabs/base.ts, src/module/apps/compendium-browser/tabs/bestiary.ts, src/module/apps/compendium-browser/tabs/data.ts, src/module/apps/compendium-browser/tabs/equipment.ts, src/module/apps/compendium-browser/tabs/feat.ts, src/module/apps/compendium-browser/tabs/hazard.ts, src/module/apps/compendium-browser/tabs/spell.ts, src/styles/_tags.scss, src/styles/packs/_tab.scss, static/lang/en.json, static/templates/actors/character/tabs/feats.hbs, static/templates/compendium-browser/filters.hbs
=> Add `and`,`or` and `not` conditions to the Compendium Browser trait filter

packs/data/equipment.db/waffle-iron-high-grade-mithral.json, packs/data/equipment.db/waffle-iron-mithral.json
https://2e.aonprd.com/Equipment.aspx?ID=275 Mithral Objects have their bulk reduced by 1 and go to Light bulk from 1 Bulk
=> Fix bulk of Mithral Waffle Iron

packs/data/pathfinder-bestiary-2.db/umonlee.json
Closes https://github.com/foundryvtt/pf2e/issues/6449
=> Fix name of umonlee mental save bonus

packs/data/pathfinder-bestiary-2.db/yamaraj.json
Fixes https://github.com/foundryvtt/pf2e/issues/6452
=> Add correct Lores to Yamaraj

packs/data/spell-effects.db/spell-effect-thermal-stasis.json, packs/data/spells.db/thermal-stasis.json
Closes https://github.com/foundryvtt/pf2e/issues/6457
=> Add spell effect for Thermal Stasis

packs/data/strength-of-thousands-bestiary.db/kurshkin.json
=> Fix Kurshkin's level

roll-grammar.peggy
=> Fix display and processing of halved damage

packs/data/kingmaker-bestiary.db/oleg.json, packs/data/kingmaker-bestiary.db/river-elasmosaurus.json, packs/data/kingmaker-bestiary.db/svetlana.json, packs/data/kingmaker-bestiary.db/volodmyra.json
This is my first data edit for pf2e, please let me know if I've done anything wrong!
=> Fix details of several Kingmaker NPCs

packs/data/feats.db/folk-dowsing.json
https://2e.aonprd.com/Feats.aspx?ID=3774
Marked as 1 in the system
=> Correct folk dowsing level

packs/data/feats.db/verdant-metamorphosis.json
Before application of the RE:
After:
=> Automate Verdant Metamorphosis impact on Actor Traits

packs/data/feats.db/chosen-of-lamashtu.json, packs/data/feats.db/elf-atavism.json, static/lang/re-en.json
Also fix up some mistakes in Elf Atavism
=> Add rule elements to Chosen of Lamashtu feat

packs/data/spells.db/plane-shift.json, packs/data/spells.db/song-of-the-fallen.json
https://2e.aonprd.com/Spells.aspx?ID=222
https://2e.aonprd.com/Spells.aspx?ID=563
=> Add focus component to Plane Shift and Song of the Fallen spells

src/module/system/damage/helpers.ts, src/module/system/damage/values.ts
=> Categorize bleed damage as physical

src/styles/actor/hazard/_actions.scss, src/styles/actor/npc/_index.scss
=> Slightly enlarge damage buttons on NPC & Hazard sheets

packs/data/pathfinder-bestiary.db/slurk.json
Fixes https://github.com/foundryvtt/pf2e/issues/6545
=> Add Value to Clumsy Condition from Slurk's Entangling Slime effect

packs/data/equipment.db/casters-targe.json, packs/data/equipment.db/dart-shield.json, packs/data/equipment.db/fortress-shield.json, packs/data/equipment.db/gauntlet-buckler.json, packs/data/equipment.db/harnessed-shield.json, packs/data/equipment.db/heavy-rondache.json, packs/data/equipment.db/helmsmans-recourse-greater.json, packs/data/equipment.db/helmsmans-recourse-major.json, packs/data/equipment.db/helmsmans-recourse.json, packs/data/equipment.db/hide-shield.json, packs/data/equipment.db/klar.json, packs/data/equipment.db/meteor-shield.json, packs/data/equipment.db/razor-disc.json, packs/data/equipment.db/salvo-shield.json, packs/data/equipment.db/sanguine-klar-greater.json, packs/data/equipment.db/sanguine-klar.json, packs/data/equipment.db/starfall-shield.json, packs/data/equipment.db/swordstealer-shield.json, packs/data/equipment.db/turnabout-shield.json
Closes https://github.com/foundryvtt/pf2e/issues/6538
=> Fix usage of some shields

packs/data/equipment.db/cloister-robe-major.json
Closes https://github.com/foundryvtt/pf2e/issues/6546
=> Fix major cloister robe to be greater resilient

packs/data/equipment.db/contagion-metabolizer-greater.json, packs/data/equipment.db/contagion-metabolizer-lesser.json, packs/data/equipment.db/contagion-metabolizer-moderate.json
Closes https://github.com/foundryvtt/pf2e/issues/6540
=> Fix name of contagion metabolizer

src/module/item/consumable/document.ts
=> Fix localization of unidentified consumable types

packs/data/equipment.db/rite-of-reinforcement-exoskeleton.json
Closes https://github.com/foundryvtt/pf2e/issues/6585
=> Fix strength value of Rite of Reinforcement Exoskeleton

src/module/system/damage/weapon.ts
Also extract modifier adjustments for the strength modifier
=> Treat propulsive weapon damage as strength-based

src/module/actor/sheet/item-summary-renderer.ts
=> Fix expanding summaries for nested feats
