foundryvtt/pf2e

packs/data/feats.db/devoted-guardian.json

Closes https://github.com/foundryvtt/pf2e/issues/6603

Fix Devoted Guardian to be one action rather than passive

---

packs/data/equipment.db/aligned-oil.json
packs/data/equipment.db/antimagic-oil.json
packs/data/equipment.db/obfuscation-oil.json
packs/data/equipment.db/oil-of-animation.json
packs/data/equipment.db/oil-of-keen-edges.json
packs/data/equipment.db/oil-of-mending.json
packs/data/equipment.db/oil-of-potency.json
packs/data/equipment.db/oil-of-repulsion.json
packs/data/equipment.db/oil-of-weightlessness-greater.json
packs/data/equipment.db/oil-of-weightlessness.json
packs/data/equipment.db/salve-of-antiparalysis-greater.json
packs/data/equipment.db/salve-of-antiparalysis.json
packs/data/equipment.db/salve-of-slipperiness.json

Closes https://github.com/foundryvtt/pf2e/issues/6607

Fix usage for some oils

---

src/styles/actor/character/_actions.scss

Show repeating ammo icon again

---

src/module/system/text-editor.ts

Change default label of perception @Checks to "Perception"

---

packs/data/equipment.db/corpsecaller-round.json

Closes https://github.com/foundryvtt/pf2e/issues/6674

Fix the type of Corpsecaller Round

---

src/module/chat-message/listeners/set-as-initiative.ts

Hide "setInitiative" button for blind rolls

---

src/module/item/spellcasting-entry/data/sheet.ts
src/module/item/spellcasting-entry/data/types.ts
src/module/item/spellcasting-entry/document.ts

Reducing file changes in #6636

Add `SpellcastingEntryPF2e#category` getter

---

packs/data/equipment.db/unending-itch.json

Closes https://github.com/foundryvtt/pf2e/issues/6690

Fix level for Unending Itch

---

packs/data/feat-effects.db/effect-blade-ally.json

Closes https://github.com/foundryvtt/pf2e/issues/6698

Add Returning and Shifting to Blade Ally choices

---

src/module/apps/sidebar/encounter-tracker.ts
src/module/encounter/document.ts
src/scripts/sheet-util.ts
types/foundry/client/documents/combat.d.ts

Restore blind/gm initiative rolling

---

static/templates/items/condition-sidebar.hbs

Closes https://github.com/foundryvtt/pf2e/issues/6705

Fix localized string for condition sidebar duration

---

packs/data/feats.db/armor-specialist.json
packs/data/feats.db/energy-beam.json

plus extract normalization along for the ride

Set icon for energy beam, add persistent damage

---

src/module/item/armor/document.ts
src/module/item/container/document.ts
src/module/item/equipment/document.ts
static/templates/chat/armor-card.hbs
static/templates/chat/backpack-card.hbs
static/templates/chat/consumable-card.hbs
static/templates/chat/equipment-card.hbs
static/templates/chat/weapon-card.hbs

Fix display of rarity in armor and equipement chat cards

---

src/module/rules/rule-element/ephemeral-effect.ts
src/module/rules/rule-element/grant-item/rule-element.ts

Fix item alterations being applied multiple times to ephemeral effects

---

src/module/actor/base.ts
src/module/actor/creature/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/item-summary-renderer.ts
src/module/actor/vehicle/sheet.ts
src/module/item/abstract-effect/document.ts
src/module/item/effect/document.ts
src/module/system/conditions/manager.ts
src/module/system/conditions/types.ts
static/templates/actors/partials/conditions.hbs
static/templates/actors/partials/item-summary.hbs
static/templates/system/effects-panel.hbs

Fixes #6785, also refactors effect identification getter to match physical items.

Hide mystified item traits and price

---

src/module/rules/rule-element/grant-item/rule-element.ts
src/module/rules/rule-element/grant-item/schema.ts

Will follow up later with the same for ChoiceSet

Add ability to track items from GrantItem rule element

---

src/module/actor/base.ts
src/module/actor/sheet/base.ts
src/module/item/condition/document.ts

Also caught a few more issues with condition active resolving resolving around locked/unlocked prioritization, it *should* work fine now.

Don't increase existing conditions when dragging new ones

---

src/module/actor/base.ts

Show persistent damage dialog when dragging a condition link

---

src/module/actor/base.ts
src/module/actor/helpers.ts
src/module/actor/sheet/item-summary-renderer.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/hotbar.ts
src/module/apps/sidebar/compendium-directory.ts
src/module/chat-message/listeners/cards.ts
src/module/item/base.ts
src/module/item/heritage/sheet.ts
src/module/item/kit/sheet.ts
src/module/item/sheet/rule-elements/grant-item-form.ts
src/module/migration/migrations/823-heritage-ancestry-slug.ts
src/module/rules/rule-element/ephemeral-effect.ts
src/module/rules/rule-element/grant-item/rule-element.ts
src/module/system/action-macros/crafting/craft.ts
src/module/system/action-macros/crafting/repair.ts
src/module/system/action-macros/crafting/select-item.ts
src/scripts/macros/raise-a-shield.ts
src/util/uuid-utils.ts

Turns out this wasn't needed after all.

Remove `UUIDUtils.fromUuid`

---

src/module/encounter/combatant.ts
src/module/encounter/document.ts

Additional reset events:
- During any round or turn change rather than next round or turn
- Any time an encounter participant's initiative is updated
- When a participant is removed from the encounter

Reset actors more frequently during encounter events

---

src/module/actor/character/crafting/helpers.ts

Create tiny items when crafted by tiny PCs

---

packs/data/feats.db/ghost-dedication.json

Add Ghost Touch rune REs to Ghost Dedication

---

packs/data/equipment.db/wand-of-overflowing-life-3rd-level-spell.json
packs/data/equipment.db/wand-of-overflowing-life-4th-level-spell.json
packs/data/equipment.db/wand-of-overflowing-life-5th-level-spell.json
packs/data/equipment.db/wand-of-overflowing-life-6th-level-spell.json
packs/data/equipment.db/wand-of-overflowing-life-7th-level-spell.json
packs/data/equipment.db/wand-of-overflowing-life-8th-level-spell.json

Closes https://github.com/foundryvtt/pf2e/issues/6865

Fix spell level in Wand of Overflowing Life description

---

packs/data/actions.db/bullet-dancer-stance.json
packs/data/feat-effects.db/stance-bullet-dancer-stance.json

No automation for this one yet, I'll revisit this when I revisit monks. Need to think about how to handle these feats that expand the things that set off other feats.

Add Bullet Dancer Stance effect

---

packs/data/pathfinder-dark-archive.db/constricting-hall.json

Closes https://github.com/foundryvtt/pf2e/issues/6888

Remove extraneous word from Constricting Hall Lose Form description

---

src/module/item/effect/document.ts
src/styles/system/_effects-panel.scss
static/templates/system/effects-panel.hbs

Style effects panel icons originating from auras as glowy circles

---

packs/data/blood-lords-bestiary.db/urbulinex.json
packs/data/blood-lords-bestiary.db/yshula.json
packs/data/pfs-introductions-bestiary.db/rain-in-cloudy-day.json

Corrects Urbulinex and Yshula typos.
Sets rain in cloudy day level to 2.
Closes #6924

Correct minor typographic errors in Blood Lords and PFS Introductions

---

src/module/item/abstract-effect/data.ts
src/module/item/effect/document.ts
static/templates/actors/partials/conditions.hbs

Prefer display of effect badge labels on actor sheets

---

src/styles/actor/_inventory.scss
static/templates/actors/partials/item-line.hbs

Show price per on loot sheet

---

packs/data/equipment.db/big-boom-gun.json

Fixes https://github.com/foundryvtt/pf2e/issues/6941

Correct Big Boom Gun's bulk

---

src/module/actor/character/sheet.ts

Fix trait selection in `CharacterSheetPF2E#onClickBrowseFeats`

---

package-lock.json
package.json

Has a high-level vulnerability

Update webpack NPM dependency

---

packs/data/age-of-ashes-bestiary.db/precentor.json

Add regeneration glossary ability to Precentor

---

src/module/item/action/document.ts
src/module/item/feat/document.ts
src/util/misc.ts
static/lang/en.json

- Refrain from showing "passive" as a tag
- Distinguish between single actions and activities

Improve action-type display in action/feat summaries

---

packs/data/crown-of-the-kobold-king-bestiary.db/lekmek.json

Closes https://github.com/foundryvtt/pf2e/issues/7004

Fix action count of Lekmek's Bark Command

---

packs/data/equipment.db/explosive-ammunition-greater.json
packs/data/equipment.db/explosive-ammunition.json
static/lang/re-en.json

Closes https://github.com/foundryvtt/pf2e/issues/6999

Fix damage type in Explosive Ammunition and add Note RE

---

src/module/canvas/token/object.ts
src/module/item/abstract-effect/document.ts
src/module/item/condition/document.ts
src/module/item/effect/document.ts

Reducing the code for affliction condition automation

Move floaty text handling to abstract effect

---

src/module/item/affliction/data.ts
src/module/item/affliction/document.ts
src/module/item/affliction/sheet.ts
src/styles/item/_affliction-sheet.scss
src/styles/item/_index.scss
static/lang/en.json
static/templates/items/affliction-details.hbs
static/templates/system/effects-panel.hbs

Add ability to define if an affliction's condition is linked

---

packs/data/feats.db/nimble-dodge.json
packs/data/feats.db/trap-finder.json
packs/data/feats.db/youre-next.json

Closes https://github.com/foundryvtt/pf2e/issues/7042

Fix source of Nimble Dodge, Trap Finder, and You're Next feats

---

src/module/actor/data/size.ts
src/module/item/base.ts
src/module/item/kit/document.ts

Inflate kit contents to correspond with its owning actor

---

src/module/actor/creature/document.ts
src/module/actor/sheet/base.ts
src/module/chat-message/listeners/set-as-initiative.ts
static/lang/en.json

Always use `EncounterPF2e` methods to set initiative

---

packs/data/feat-effects.db/effect-dread-marshal-stance.json
packs/data/feat-effects.db/effect-rallying-charge.json
packs/data/feats.db/rallying-charge.json

Add damage bonus to Dread Marshal aura

---

packs/data/strength-of-thousands-bestiary.db/sunburst-corpse.json

Closes https://github.com/foundryvtt/pf2e/issues/7072

Add toggle for Sunburst Corpse Blinding Aura. Remove duplicate Constrict ability.

---

src/module/item/physical/document.ts
src/module/item/physical/helpers.ts
src/module/item/physical/sheet.ts
src/module/item/treasure/document.ts
src/module/migration/migrations/746-standardize-pricing.ts
src/module/migration/migrations/750-fix-corrupted-price.ts
src/styles/item/_index.scss
static/templates/items/armor-sidebar.hbs
static/templates/items/backpack-sidebar.hbs
static/templates/items/consumable-sidebar.hbs
static/templates/items/equipment-sidebar.hbs
static/templates/items/weapon-sidebar.hbs

Adjust derived equipment prices for size

---

src/module/system/action-macros/crafting/repair.ts
src/scripts/macros/encouraging-words.ts

I was individually tweaking some things that the skills statistic refactor was going to affect, but turns out the macro was broken anyways!

Convert repair/encouraging to statistic (also fixes encouraging words macro)

---

src/module/system/damage/iwr.ts

This also enforces a minimum of 0 for each damage instance when processing IWR
Closes #7087, supersedes #7091

Increase 1st damage instance total to 1 if roll total was increased to 1

---

packs/data/spells.db/lashing-rope.json

Closes https://github.com/foundryvtt/pf2e/issues/7108

Fix details of Lashing Rope

---

src/module/actor/base.ts
src/module/item/base.ts

Circumvent upstream data resets of items dropped on actor sheets

---

packs/data/classfeatures.db/fighter-weapon-mastery.json

Closes https://github.com/foundryvtt/pf2e/issues/7110

Update description of Fighter Weapon Mastery

---

src/styles/actor/sidebar/_index.scss

Tweak character sheet sidebar to prevent blurred images

---

packs/data/heritages.db/skilled-heritage.json

Shows how often people pick this one

Add automation to Skilled Heritage

---

packs/data/classfeatures.db/animal-instinct.json

Fix frog instinct's tongue strike

---

src/global.d.ts
src/module/apps/sidebar/encounter-tracker.ts
src/module/doc-helpers.ts
src/module/encounter/combatant.ts
src/scripts/hooks/index.ts
src/scripts/hooks/target-token.ts
src/styles/ui/sidebar/_actor-directory.scss
src/styles/ui/sidebar/_tracker.scss
src/util/dom.ts
src/util/misc.ts
static/lang/en.json
types/foundry/client/core/hooks.d.ts
types/foundry/client/documents/combat.d.ts
types/foundry/client/ui/index.d.ts

Indicate which users are targeting combatants in tracker, add toggle

---

packs/data/abomination-vaults-bestiary.db/dreshkan.json
src/module/rules/rule-element/iwr/base.ts
src/module/rules/rule-element/iwr/immunity.ts
src/module/rules/rule-element/iwr/resistance.ts
src/module/rules/rule-element/iwr/weakness.ts

Example implementation of Dreshkan from the Abomination Vaults bestiary

Add support for "remove" mode in IWR rule elements

---

packs/data/feat-effects.db/effect-ghost-wrangler.json
packs/data/feat-effects.db/effect-giants-stature.json
packs/data/feat-effects.db/effect-rage.json
packs/data/feat-effects.db/effect-reckless-abandon-barbarian.json
packs/data/feat-effects.db/effect-share-rage.json
packs/data/feats.db/acute-scent.json
packs/data/feats.db/adrenaline-rush.json
packs/data/feats.db/animal-rage.json
packs/data/feats.db/bashing-charge.json
packs/data/feats.db/brutal-bully.json
packs/data/feats.db/come-and-get-me.json
packs/data/feats.db/draconic-arrogance.json
packs/data/feats.db/farabellus-flip.json
packs/data/feats.db/fast-movement.json
packs/data/feats.db/follow-up-assault.json
packs/data/feats.db/furious-bully.json
packs/data/feats.db/ghost-wrangler.json
packs/data/feats.db/giants-stature.json
packs/data/feats.db/inured-to-alchemy.json
packs/data/feats.db/nocturnal-sense.json
packs/data/feats.db/pain-tolerance.json
packs/data/feats.db/raging-athlete.json
packs/data/feats.db/scouring-rage.json
packs/data/feats.db/second-wind.json
packs/data/feats.db/shake-it-off.json
packs/data/feats.db/share-rage.json
packs/data/feats.db/sudden-charge.json
packs/data/feats.db/sudden-leap.json
packs/data/feats.db/thrash.json
static/lang/re-en.json

Levels 1-8 feats. I'll do the other half next.

Brushup Barbarian feats part 1

---

packs/data/feats.db/marshal-dedication.json

Automate the skill selection of Marshal Dedication

---

src/module/actor/base.ts
src/module/system/damage/iwr.ts

This is causing more trouble than it's worth.
Closes #6207

Remove check to skip persistent damage that would be resisted away

---

src/module/system/statistic/index.ts

Someone asked me if these could be added for use in modules.

Add `extraRollNotes` and `label` as optional parameters of `StatisticCheck#roll`

---

packs/data/extinction-curse-bestiary.db/ledorick-banyan-possessed.json
packs/data/extinction-curse-bestiary.db/ledorick-banyan.json
packs/data/kingmaker-bestiary.db/aldori-sister.json

Closes https://github.com/foundryvtt/pf2e/issues/7193

Fix NPCs adding damage dice of type "precision"

---

packs/data/classfeatures.db/precise-strike.json

Needed for Combination Finisher to work properly.

Fix the domain of Swashbuckler finishers

---

src/module/item/weapon/document.ts

Fix generation of magic weapon names

---

src/module/actor/base.ts
src/module/scene/token-document/document.ts

Pushing out standalone changes to reduce the final merge size

Link party actor by default

---

src/scripts/config/damage.ts

Closes https://github.com/foundryvtt/pf2e/issues/7281

Include orichalcum in material damage effects

---

packs/data/deities.db/narakaas.json
packs/data/domains.db/introspection-domain.json
packs/data/journals.db/domains.json
static/lang/en.json

I did my best to copy existing structures for other domains. Please let me know if I missed anything.
Fixes: #7188

Add Introspection Domain

---

packs/data/pathfinder-bestiary.db/quelaunt.json

Also refreshed spells on the creature

Fix an erroneous at will spell on Quelaunt

---

packs/data/outlaws-of-alkenstar-bestiary.db/shoma-lyzerius.json

add Lyzerium to Lyzerius

---

packs/data/classfeatures.db/deific-weapon.json
packs/data/classfeatures.db/deity.json
src/module/rules/rule-element/strike.ts

Also adjusted processing of the shorthand to incorporate existing predicate statements in the RE

Use "fist" shorthand for granting deity-favored fist strike

---

src/module/rules/rule-element/creature-size.ts

Have `resizeEquipment` option of CreatureSize RE treat small as medium

---

src/module/actor/sheet/base.ts
src/module/item/physical/document.ts
src/styles/actor/_inventory.scss
static/templates/actors/loot/inventory.hbs
static/templates/actors/partials/item-line.hbs

[sortable-inventory.webm](https://user-images.githubusercontent.com/41452412/229311409-0ae583dc-e78e-4f05-8527-3c0d6271a8ad.webm)

Enhance inventory sorting with `SortableJS`

---

packs/data/feats.db/skill-mastery-investigator.json

copy rules for Skill Mastery (Rogue) into Skill Mastery (Investigator)

---

src/module/system/action-macros/basic/crawl.ts
src/module/system/action-macros/basic/delay.ts
src/module/system/action-macros/basic/drop-prone.ts
src/module/system/action-macros/basic/interact.ts
src/module/system/action-macros/basic/leap.ts
src/module/system/action-macros/basic/ready.ts
src/module/system/action-macros/basic/release.ts
src/module/system/action-macros/basic/stand.ts
src/module/system/action-macros/basic/step.ts
src/module/system/action-macros/basic/stride.ts
src/module/system/action-macros/index.ts
static/lang/action-en.json

Depends on https://github.com/foundryvtt/pf2e/pull/7270 for proper translations in the chat cards.

Add basic actions without checks

---

src/scripts/dice.ts

fix stray Misfortune title

---

src/styles/actor/_limited.scss
static/templates/actors/character/limited.hbs

Allow actor img on limited sheet to expand to fit

---

src/module/system/action-macros/acrobatics/balance.ts
src/module/system/action-macros/acrobatics/maneuver-in-flight.ts
src/module/system/action-macros/acrobatics/squeeze.ts
src/module/system/action-macros/acrobatics/tumble-through.ts
src/module/system/action-macros/index.ts
static/lang/action-en.json

Balance, Tumble Through, Maneuver in Flight, and Squeeze.

Convert Acrobatics skill action functions to action objects

---

packs/data/feats.db/trap-finder.json

Closes https://github.com/foundryvtt/pf2e/issues/7327

Fix Trap Finder perception bonus

---

src/module/actor/creature/document.ts
src/module/system/statistic/index.ts

Fixes Elven Instincts and Battlefield Surveyor

Fix initiative rolls predicated on certain checks

---

src/module/actor/creature/document.ts
src/module/actor/party/data.ts
src/module/actor/party/document.ts

Support adding members to parties

---

packs/data/pathfinder-bestiary-2.db/marrmora.json

Closes #7275.
Verified against bestiary 2 and B2 errata

Correct spell list for Marrmora.

---

packs/data/spells.db/fearful-feast.json

Closes #7353. Verified against AV hardcover.

Correct heightening for Frightful Feast

---

src/module/system/action-macros/index.ts
src/module/system/action-macros/stealth/conceal-an-object.ts
static/lang/action-en.json

Convert remaining Stealth skill action

---

package-lock.json
src/module/actor/npc/data.ts
src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts
src/module/actor/npc/types.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/popups/recall-knowledge-popup.ts
src/module/dc.ts
src/module/recall-knowledge.ts
src/scripts/config/index.ts
src/util/misc.ts
static/lang/en.json
static/templates/actors/npc/tabs/main.hbs
static/templates/actors/recall-knowledge.hbs
tests/module/dc.test.ts
tests/module/recall-knowledge.test.ts

Use CRB language for creature identification info on NPC sheet

---

packs/data/equipment.db/blessed-reformer.json
packs/data/equipment.db/vigilant-eye-major.json
packs/data/equipment.db/wand-of-pernicious-poison-purple-worm-sting.json

Closes https://github.com/foundryvtt/pf2e/issues/7365

Fix name of Blessed Reformer and Wand of Pernicious Poison (Purple Worm Sting). Fix level and price of Vigilant Eye (Major).

---

src/scripts/hooks/ready.ts
types/foundry/client/game.d.ts

Update out-of-date-module check to nag about sub-V10 modules

---

packs/data/spells.db/spiritual-epidemic.json

Closes https://github.com/foundryvtt/pf2e/issues/7401

Fix Enfeebled value for Spiritual Epidemic Critical Failure

---

src/scripts/config/index.ts
src/scripts/hooks/render-dialog.ts
src/scripts/macros/encouraging-words.ts
src/scripts/macros/hotbar.ts
src/scripts/macros/raise-a-shield.ts
src/scripts/macros/rest-for-the-night.ts
src/scripts/macros/steel-your-resolve.ts
src/scripts/register-sheets.ts
src/scripts/system/remigrate.ts
src/util/misc.ts

Beginning with usage in `@scripts`

Start phasing out `LocalizePF2e`

---

src/module/apps/compendium-browser/tabs/equipment.ts

Infer `magical` trait for armor and weapons in the compendium browser

---

src/scripts/hooks/render-dialog.ts

Related to https://github.com/foundryvtt/pf2e/pull/7414

Fix localization of item creation dialog labels

---

packs/data/equipment.db/alchemists-haversack.json

Closes https://github.com/foundryvtt/pf2e/issues/7446

Fix price of Alchemist's Haversack

---

src/module/rules/rule-element/base.ts

Improve message accuracy when failing to resolve rule element formulas

---

src/module/actor/sheet/base.ts

Sortable needs to be initialized before the `this.options.editable` check to allow dragging from actors with limited permissions.
I've also removed the `render: false` option from the normal inventory move action because I noticed that skipping the local render will also skip rendering for all connected clients that have that sheet open so the sorting gets out of sync.

Fix dragging items from loot or merchant actors with limited permissions

---

packs/data/hazards.db/sportlebore.json
src/scripts/config/traits.ts

https://2e.aonprd.com/Hazards.aspx?ID=49

Add "animal" to hazard traits, include in Sportlebore traits

---

src/module/item/weapon/data.ts
src/module/item/weapon/document.ts
src/module/item/weapon/helpers.ts

Will follow up with UI integration if/when approved

Add data handling of toggleable weapon traits

---

src/module/apps/sidebar/chat-log.ts
src/module/system/damage/helpers.ts
src/module/system/text-editor.ts

Tighten fuzzy recognition of damage rolls from inline formulas and chat

---

src/module/actor/character/document.ts
src/module/actor/modifiers.ts
src/module/rules/rule-element/flat-modifier.ts

Add statements to modifier roll options to inform item source

---

src/module/actor/sheet/base.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/collection.ts

Fix heightening for signature spells and when sent to chat

---

src/module/item/spell/document.ts
src/module/system/damage/damage.ts
src/module/system/damage/roll.ts
src/module/system/damage/types.ts

Don't set "failure" outcome in damage contexts of non-attack spells

---

src/scripts/dice.ts

Negative dice, when combined, will now reduce dice, but it will never go below 0 (once it hits 0, the dice are removed from the formula). Removing dice wasn't the goal, but it was a neat side effect.

Support negative modifiers (and dice) in spell combine terms

---

src/module/actor/types.ts
src/module/canvas/token/aura/renderer.ts
src/module/rules/rule-element/aura.ts
src/module/rules/rule-element/data.ts
types/foundry/common/data/fields.d.ts

Add schema definition to Aura rule element

---

src/module/item/melee/document.ts
src/module/item/spell/document.ts
src/module/system/damage/damage.ts
src/module/system/damage/types.ts

The tweaks done to combineTerms() is also relevant for melee.

Simplify melee elite/weak adjustment

---

src/module/system/damage/formula.ts
src/module/system/damage/weapon.ts
src/scripts/dice.ts

The "identify terms from formula" bit is also needed by melee. The "combine partials into unflavored formula" bit is also needed by the main damage code.

Remove some code duplication in combineTerms() and melee

---

packs/data/feat-effects.db/effect-flames-curse.json

Closes https://github.com/foundryvtt/pf2e/issues/7461

Update Flames Curse to grant Concealed and add reminder aura

---

packs/data/spells.db/ashen-wind.json

https://2e.aonprd.com/Spells.aspx?ID=1242

Fix level and description of Ashen Wind

---

src/scripts/hooks/init.ts

Update css filename added to `CONFIG.TinyMCE.content_css`

---

packs/data/pathfinder-bestiary.db/night-hag.json

Closes https://github.com/foundryvtt/pf2e/issues/7587

Fix Night Hag's Nightmare Rider link

---

packs/data/backgrounds.db/eclipseborn.json
packs/data/backgrounds.db/street-preacher.json
packs/data/blog-bestiary.db/prrall.json
packs/data/strength-of-thousands-bestiary.db/graveknight-champion.json

Added a "Swift Sneak" passive to Pr'rall, to bring it in line with others and to avoid a custom Stealth skill name.
https://paizo.com/community/blog/v5748dyo6sham

Clean up some irregular skill names

---

packs/data/feats.db/crane-flutter.json
packs/data/feats.db/dragon-roar.json
packs/data/feats.db/tiger-slash.json
packs/data/feats.db/wolf-drag.json
static/lang/re-en.json

Also fix Tiger Slash disable predicate

Disable toggles for Crane Flutter, Dragon Roar, Wolf Drag if not in appropriate stance

---

src/styles/item/_index.scss

We can sit on this one until after 4.11 patching is done

Fix scrolling through long descriptions when GM notes are present

---

packs/data/equipment-effects.db/effect-soothing-tonic-greater.json
packs/data/equipment-effects.db/effect-soothing-tonic-lesser.json
packs/data/equipment-effects.db/effect-soothing-tonic-major.json
packs/data/equipment-effects.db/effect-soothing-tonic-moderate.json
packs/data/equipment.db/soothing-tonic-greater.json
packs/data/equipment.db/soothing-tonic-lesser.json
packs/data/equipment.db/soothing-tonic-major.json
packs/data/equipment.db/soothing-tonic-moderate.json

Closes https://github.com/foundryvtt/pf2e/issues/7603

Add effects for Soothing Tonic

---

packs/data/feats.db/one-inch-punch.json
static/lang/re-en.json

Also ternaries while we're at it

Update One Inch Punch to use RollOption suboptions

---

src/module/actor/creature/document.ts
src/module/actor/data/base.ts
src/module/actor/data/index.ts
src/module/actor/hazard/document.ts
src/module/actor/initiative.ts
src/module/encounter/document.ts

They outta be using actor.initiative.roll() if they wanna pass params but sure we can be exhaustive.

Add backwards compat for attributes.initiative.roll, and pass along rollInitiative() args

---

src/module/item/effect/document.ts

Prevent early effect expiration when combatants have equal initiative

---

src/module/actor/modifiers.ts

Make `ModifierPF2e#item` not enumerable

---

packs/data/spells.db/acid-splash.json

Closes https://github.com/foundryvtt/pf2e/issues/7639

Clean up description of Acid Splash and add leveled persistent damage link

---

packs/data/equipment.db/polytool.json

This has dealt acid damage since its initial data entry in 2020. :upside_down_face:

Fix polytool damage type

---

src/module/actor/creature/spell-preparation-sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/helpers.ts
src/module/item/base.ts
static/templates/actors/spellcasting-spell-list.hbs

Fix creation of custom spells from actor sheets

---

src/module/item/physical/sheet.ts

Show source value for size on physical-item sheets

---

src/module/item/melee/sheet.ts

Show source values for attack and damage in NPC attack sheets

---

src/module/item/base.ts
src/module/rules/rule-element/base.ts

Include roll options from REs' parent items using "parent" prefix

---

src/module/item/armor/document.ts
src/module/item/armor/sheet.ts
src/module/item/physical/runes.ts
src/module/item/weapon/document.ts
src/module/item/weapon/sheet.ts

(given property runes are allowed)

Expose property rune slots on unowned armor when ABP is enabled

---

packs/data/feats.db/psychic-dedication.json

Fix focus points added by Psychic Dedication

---

packs/data/equipment.db/armory-bracelet-major.json

Thanks to Lyude (french community member)

Fix level and price of Armory bracelet (Major)

---

packs/data/pfs-season-4-bestiary.db/determined-dura-1-2.json
packs/data/pfs-season-4-bestiary.db/determined-dura-3-4.json
packs/data/pfs-season-4-bestiary.db/determined-halran-1-2.json
packs/data/pfs-season-4-bestiary.db/determined-halran-3-4.json
packs/data/pfs-season-4-bestiary.db/determined-rhenei-1-2.json
packs/data/pfs-season-4-bestiary.db/determined-rhenei-3-4.json
packs/data/pfs-season-4-bestiary.db/determined-thisnabel-1-2.json
packs/data/pfs-season-4-bestiary.db/determined-thisnabel-3-4.json
packs/data/pfs-season-4-bestiary.db/dura-1-2.json
packs/data/pfs-season-4-bestiary.db/dura-3-4.json
packs/data/pfs-season-4-bestiary.db/halran-1-2.json
packs/data/pfs-season-4-bestiary.db/halran-3-4.json
packs/data/pfs-season-4-bestiary.db/rhenei-1-2.json
packs/data/pfs-season-4-bestiary.db/rhenei-3-4.json
packs/data/pfs-season-4-bestiary.db/thisnabel-1-2.json
packs/data/pfs-season-4-bestiary.db/thisnabel-3-4.json
static/licenses/OpenGameLicense.md

Also update license file for Q14

Add NPCs from PFS Quest 14

---

src/module/item/weapon/document.ts
src/module/item/weapon/helpers.ts
src/module/rules/rule-element/adjust-strike.ts

Prune duplicate and lesser versions of property runes on each weapon

---

src/module/actor/party/document.ts
src/module/actor/party/sheet.ts
src/module/actor/party/types.ts
src/styles/actor/party/_index.scss
static/lang/en.json
static/templates/actors/party/sheet.hbs

Add tab for orphaned party items

---

src/module/item/spell/document.ts
src/module/system/damage/formula.ts
src/module/system/damage/modifier-dialog.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts

This originally started as a refactor, but I noticed and fixed an existing bug.

Fix stacking modifiers in spell damage

---

packs/data/equipment.db/monkeys-fist.json

Closes https://github.com/foundryvtt/pf2e/issues/7748

Correct traits and bulk of Monkey's Fist

---

src/module/actor/helpers.ts

Ensure NPC self roll options are retrieved for damage rolls from sheets

---

packs/data/feats.db/diverse-lore.json

Adds a toggle to enable to -2 penalty on an Esoteric Lore check with Diverse Lore
Closes #7419

Add functionality to diverse lore feat

---

packs/data/abomination-vaults-bestiary.db/caliddo-haruvex.json
packs/data/abomination-vaults-bestiary.db/jafaki.json
packs/data/abomination-vaults-bestiary.db/nyzuros.json
packs/data/abomination-vaults-bestiary.db/padli.json
packs/data/abomination-vaults-bestiary.db/quara-orshendiel.json
packs/data/abomination-vaults-bestiary.db/salaisa-malthulas.json
packs/data/crown-of-the-kobold-king-bestiary.db/ygrik.json
packs/data/fall-of-plaguestone.db/hallod.json
packs/data/fall-of-plaguestone.db/lord-nar.json
packs/data/fall-of-plaguestone.db/vilree.json
packs/data/pfs-season-2-bestiary.db/mother-forsythe-3-4.json
packs/data/pfs-season-2-bestiary.db/mother-forsythe-5-6.json

Change treasure keys to equipment

---

packs/data/spells.db/lay-on-hands.json
packs/data/spells.db/touch-of-corruption.json

Add variants to Lay on Hands and Touch of Corruption

---

src/module/system/damage/modifier-dialog.ts
static/templates/chat/damage/damage-modifier-dialog.hbs

Show result formula for damage roll dialog

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/creature/data.ts
src/module/actor/creature/document.ts
src/module/actor/familiar/data.ts
src/module/actor/familiar/document.ts
src/module/actor/npc/data.ts
src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts
src/module/rules/rule-element/battle-form/rule-element.ts
src/module/system/statistic/data.ts
src/module/system/statistic/index.ts

This should preserve compatibility even with the silly macros that ignore deprecation messages.

Refactor skills to use Statistic

---

src/module/actor/character/document.ts
src/module/actor/creature/data.ts
src/module/actor/creature/document.ts
src/module/actor/data/base.ts
src/module/actor/familiar/data.ts
src/module/actor/familiar/document.ts
src/module/actor/familiar/sheet.ts
src/module/actor/npc/document.ts
src/module/actor/npc/sheet.ts
src/module/system/statistic/index.ts
static/lang/en.json
static/templates/actors/familiar-sheet.hbs

Also fixes an error that occurs when retrieving a masterless familiar's perception.

Convert perception to statistic

---

src/scripts/handlebars.ts
static/templates/actors/character/tabs/actions.hbs

Remove `selected` handlebars helper

---

src/module/item/physical/document.ts

Skip vehicles when converting item sizes relative to owning actors

---

src/module/apps/hotbar.ts
src/scripts/macros/hotbar.ts

Preserve mystified names of macros generated from physical items

---

packs/data/bestiary-effects.db/effect-field-of-undeath.json
packs/data/book-of-the-dead-bestiary.db/deathless-acolyte-of-urgathoa.json
packs/data/book-of-the-dead-bestiary.db/deathless-hierophant-of-urgathoa.json
packs/data/pfs-season-4-bestiary.db/seldrick-dralston-1-2.json
packs/data/pfs-season-4-bestiary.db/seldrick-dralston-3-4.json

Add Fast Healing effect to Field of Undeath auras

---

src/module/system/action-macros/helpers.ts
src/module/system/action-macros/types.ts
src/module/system/statistic/index.ts

Imagine how much code we'll be able to delete once strikes use statistics.

Fix action macros with skill statistics

---

src/module/actor/sheet/base.ts

Putting all the jquery fish in a single barrel

Move actor-sheet inventory listeners to separate method

---

packs/data/campaign-effects.db/resonant-reflection-reflection-of-water.json
packs/data/equipment-effects.db/effect-arachnid-harness.json
packs/data/feats.db/flamboyant-athlete.json

Closes https://github.com/foundryvtt/pf2e/issues/7829

Fix Flamboyant Athlete to be passive and add base speed REs

---

src/styles/actor/_index.scss
src/styles/actor/_inventory.scss
src/styles/actor/_spell-list.scss
src/styles/actor/character/_actions.scss
src/styles/actor/character/_crafting.scss
src/styles/actor/character/_effects.scss
src/styles/actor/character/_feats.scss
src/styles/actor/character/_index.scss
src/styles/mixins/_effects-list.scss
src/styles/mixins/_frames.scss
static/templates/actors/character/partials/feat-slot.hbs
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/character/tabs/effects.hbs
static/templates/actors/character/tabs/pfs.hbs
static/templates/actors/partials/conditions.hbs
static/templates/actors/partials/item-line.hbs
static/templates/actors/spellcasting-spell-list.hbs

This does change the background color in some places. I can swap it to the secondary color if that's the preferred one.

Make item image styling and HTML more consistent

---

src/scripts/macros/xp/dialog.ts

Update system XP budget macro to exclude minions.

---

packs/data/age-of-ashes-bestiary.db/vazgorlu.json

Closes https://github.com/foundryvtt/pf2e/issues/7848

Fix Vazgorlu level

---

packs/data/feats.db/dragon-disciple-dedication.json

Fix dragon-type restriction on Dragon Disciple Dedication

---

src/module/actor/hazard/sheet.ts
src/module/actor/sheet/base.ts
src/styles/actor/hazard/_header.scss
src/styles/actor/hazard/_index.scss
src/styles/actor/hazard/_sidebar.scss
static/lang/en.json
static/templates/actors/hazard/partials/sidebar.hbs
static/templates/actors/hazard/sheet.hbs

plus a couple localization issues

Fix editability inconsistencies on hazard sheet

---

packs/data/actions.db/pursue-a-lead.json
static/templates/actors/character/tabs/actions.hbs

Add frequency to Pursue a Lead (the only exploration action with frequency).

Show frequency for exploration actions. 

---

src/module/actor/sheet/base.ts
src/module/actor/sheet/loot/move-loot-popup.ts
static/templates/popups/loot/move-loot-popup.hbs

Buy one item (10 for ammunition) from a merchant by default.

---

package-lock.json
package.json
packs/data/classes.db/psychic.json
packs/data/classes.db/rogue.json
packs/data/classfeatures.db/eldritch-trickster.json
packs/data/classfeatures.db/emotional-acceptance.json
packs/data/classfeatures.db/gathered-lore.json
packs/data/classfeatures.db/mastermind.json
packs/data/classfeatures.db/precise-discipline.json
packs/data/classfeatures.db/ruffian.json
packs/data/classfeatures.db/scoundrel.json
packs/data/classfeatures.db/wandering-reverie.json
src/module/item/feat/data.ts
src/module/item/feat/document.ts
src/module/item/feat/helpers.ts
src/module/item/feat/sheet.ts
static/lang/en.json
static/templates/items/feat-details.hbs

This will allow additional key ability options to be specified in class features. The options will be added to the list presented in the ability builder application.

Add "key ability options" property to class features

---

packs/data/equipment.db/dagger-pistol.json
src/module/actor/character/data.ts
src/module/actor/character/document.ts
src/module/actor/character/helpers.ts
src/module/actor/character/sheet.ts
src/module/item/effect/document.ts
src/module/item/weapon/data.ts
src/module/item/weapon/document.ts
src/module/item/weapon/helpers.ts
src/module/migration/migrations/685-fix-melee-usage-traits.ts
src/module/rules/rule-element/strike.ts
src/styles/actor/character/_actions.scss
src/styles/mixins/_typography.scss
static/templates/actors/character/tabs/actions.hbs

Add versatile-damage toggling to strikes

---

src/scripts/config/index.ts
src/scripts/macros/rest-for-the-night.ts
static/lang/en.json

Fixes #4542
Not sure this one is worth doing, but given I've done it, I might as well submit it. :)

Add frequency for round and turn.

---

src/styles/actor/hazard/_sidebar.scss
static/templates/actors/hazard/partials/sidebar.hbs

Make initiative rollable from the hazard sheet

---

src/module/item/spellcasting-entry/trick.ts

No user facing and barely even an API fix.

Fix id acquisition and tradition of trick magic item flag data

---

src/module/actor/base.ts

Fix retrieval of lore skills via `ActorPF2e#getStatistic`

---

static/lang/re-en.json

To Coneal an object -> Conceal

Fix conceal typo in re-en.json

---

src/module/system/statistic/index.ts

Restore passing along of domains while retrieving DC roll options

---

static/lang/re-en.json

Fix a typo in re-en.json

---

static/templates/items/weapon-details.hbs

Show source range value in weapon sheets

---

src/module/system/statistic/index.ts

Fix application of dexterity modifier cap

---

packs/data/feats.db/takedown-expert.json

Also add requirement for weapon to be held in one hand

Fix selector in Takedown Expert rule element

---

packs/data/equipment.db/dragons-crest.json

Remove errant `system.ability` field in Dragon's Crest

---

packs/data/feats.db/stonewall.json
static/licenses/OpenGameLicense.md

Update license file and blog entry

Add stonewall feat from blog

---

src/module/actor/modifiers.ts

Fix macros that now feed raw modifiers into CheckModifier

---

src/util/uuid.ts

Fix handling of `null` values in `UUIDUtils.fromUUIDs`

---

src/module/actor/creature/document.ts

Fix calculation of battle form land speeds

---

packs/data/equipment.db/battle-medics-baton.json

Closes https://github.com/foundryvtt/pf2e/issues/8036

Add rule element to Battle Medic's Baton

---

src/module/actor/sheet/base.ts
src/module/actor/sheet/helpers.ts
static/templates/actors/character/tabs/actions.hbs

Also moves us away from ramming dataset into item source and hoping foundry can figure it out.

Fix item create behavior for exploration and downtime actions

---

src/module/actor/character/helpers.ts
src/module/system/statistic/armor-class.ts

Fix creation of shield AC bonuses on NPCs

---

src/styles/actor/character/_crafting.scss
src/styles/actor/character/_index.scss
src/styles/actor/character/_spellcasting.scss
static/templates/actors/character/tabs/crafting.hbs
static/templates/actors/character/tabs/spellcasting.hbs

Also enlarged some text in places

Consolidate some styling between PC-sheet spellcasting and crafting tabs

---

packs/data/spell-effects.db/spell-effect-protective-ward.json

Remove value bracketing from Protective Ward effect RE

---

src/module/item/action/sheet.ts
src/module/item/feat/sheet.ts

Fix default action and feat frequency value

---

src/styles/actor/_red-action-boxes.scss
static/templates/actors/familiar-sheet.hbs

Familiar Focus sold separately

Add frequency display to familiar sheet

---

src/module/actor/character/feats.ts

It doesn't look like this ultimately made a difference, but good to keep it tidy anyway :blush:

Fix class feat prefilter arrays

---

src/module/actor/sheet/base.ts
static/lang/en.json
static/templates/actors/partials/item-line.hbs

Used to be a Toolbox feature, and then a Workbench feature.

Increase/decrease item quantities by 5 if shift-clicking or 10 by ctrl-clicking.

---

packs/data/equipment.db/tallow-bomb-greater.json
packs/data/equipment.db/tallow-bomb-major.json
packs/data/equipment.db/tallow-bomb-moderate.json
packs/data/equipment.db/twigjack-sack-greater.json
packs/data/equipment.db/twigjack-sack-lesser.json
packs/data/equipment.db/twigjack-sack-major.json
packs/data/equipment.db/twigjack-sack-moderate.json
packs/data/pfs-season-3-bestiary.db/tyrannical-interrogator.json
packs/data/quest-for-the-frozen-flame-bestiary.db/ardissa-prendergant.json
packs/data/quest-for-the-frozen-flame-bestiary.db/pakano.json

Probably some data entry was being done with a dev build

Remove equipment activation data

---

packs/data/strength-of-thousands-bestiary.db/abendego-brute.json
packs/data/strength-of-thousands-bestiary.db/ajbal-kimon.json
packs/data/strength-of-thousands-bestiary.db/bharlen-sajor.json
static/lang/re-en.json

~~Blocked by https://github.com/foundryvtt/pf2e/pull/8082~~

Add rule elements for Brute Strength and Trident Bully

---

src/module/apps/sidebar/compendium-directory.ts
src/module/system/statistic/armor-class.ts

I was doing the change independently, but after rebasing this is what's different.

Minor localization structure change tweaks

---

src/module/apps/effects-panel.ts

Include roll data in effects panel descriptions

---

src/module/actor/sheet/base.ts
src/styles/actor/character/_proficiencies.scss

Fix creation of custom physical items on actor sheets

---

src/module/apps/sidebar/compendium-directory.ts
src/styles/ui/sidebar/_compendium-directory.scss
static/templates/sidebar/compendium-directory.hbs
types/foundry/client/data/collections/compendium-collection.d.ts

Probably needs more adjusments but works for now.

Restore compendium sidebar functionality

---

src/module/actor/party/document.ts
src/module/apps/sidebar/actor-directory.ts
src/module/collection/actors.ts
static/templates/sidebar/party-document-partial.hbs
types/foundry/client/data/abstract/world-collection.d.ts
types/foundry/common/constants.d.ts

And fixes the drag drop error v10 had by introducing an invisible image

Restore party sidebar functionality for v11

---

src/module/apps/effects-panel.ts

Have effects panel use condition items instead of `FlattenedCondition`s

---

packs/spells/burning-blossoms.json

Closes https://github.com/foundryvtt/pf2e/issues/8180

Fix radius of Burning Blossoms

---

src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/base.ts
src/styles/packs/_tab.scss
static/lang/en.json
static/templates/compendium-browser/filters.hbs
types/foundry/client/ui/dialog.d.ts

[roll-table-2.webm](https://github.com/foundryvtt/pf2e/assets/41452412/489aba17-5166-4b68-b1c9-69f7c0737a64)
Closes #4853

Enable creation of Roll Tables from Compendium Browser search results

---

src/module/apps/compendium-browser/tabs/base.ts

Fix `CompendiumBrowserTab#getRollTableResults` range increase

---

packs/outlaws-of-alkenstar-bestiary/kreeth-ni.json

Closes https://github.com/foundryvtt/pf2e/issues/8113

Add link to effect for Kreeth-Ni's Wrath of Spurned Hospitality

---

packs/feats/gadget-specialist.json

Add maxItemLevel to Gadget Specialist

---

static/system.json

(except the actual Bestiaries)

Remove "Bestiary" from bestiary pack names in anticipation of foldering

---

static/templates/user/sheet.hbs

add pronoun field in player config

---

src/scripts/hooks/render-combat-tracker-config.ts
static/templates/sidebar/encounter-tracker/config.hbs

Fix appended CombatConfig settings

---

src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/tabs/base.ts
static/lang/en.json
static/templates/compendium-browser/roll-table-dialog.hbs

Add more options to Compendium Browser roll table dialogs

---

src/styles/actor/character/_proficiencies.scss
src/styles/actor/character/_proficiency-ranks.scss
static/templates/actors/character/tabs/proficiencies.hbs

The one other source of proficiency dropdowns, spells, seems to continue working fine. Let me know if I should test anything else

Minor visual updates to character skills

---

.github/workflows/cd.yml
.gitignore
build/build-packs.ts
build/lib/compendium-pack.ts
package.json

Sample zip file:
https://github.com/In3luki/pf2e/releases/latest/download/packs-json.zip

Add JSON pack files to release artifacts

---

src/module/actor/item-transfer.ts
src/module/actor/loot/sheet.ts
static/lang/en.json

(applicable to party loot transfers)

Prevent error from being thrown from `ItemTransfer##sendMessage`

---

static/templates/scene/token/partials/identity.hbs

Add core Append Number and Prepend Adjective fields to Prototype Token Config

---

.github/workflows/cd.yml
.gitignore
build/lib/compendium-pack.ts

`json-assets.zip` contains a `packs` folder with the pack JSON files and a `lang` folder with the contents of `static/lang`.
Example zip:
https://github.com/In3luki/pf2e/releases/download/5.0.0-beta2/json-assets.zip

[CD] Rename `packs-json.zip` to `json-assets.zip` and add `static/lang` files

---

src/module/actor/party/document.ts
src/module/actor/party/invalid-campaign.ts
src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/data.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/types.ts
src/styles/actor/party/_index.scss
src/styles/actor/party/kingdom/_builder.scss
src/styles/actor/party/kingdom/_index.scss
src/styles/ui/sidebar/_actor-directory.scss
static/lang/en.json
static/lang/kingmaker-en.json
static/system.json
static/templates/actors/party/kingdom/builder.hbs
static/templates/sidebar/party-document-partial.hbs
types/foundry/common/abstract/data.d.ts
types/foundry/common/abstract/document.d.ts

This also updates the kingdom model to update source between data preparation instead of recreating from scratch every time.

Create Kingdom builder sheet and validate kingdom data

---

src/module/apps/sidebar/compendium-directory.ts
src/styles/ui/sidebar/_compendium-directory.scss
static/lang/en.json
static/templates/sidebar/compendium-directory.hbs

Plus update template to latest from core

Fix compendium drag & drop functionality

---

static/system.json

This reverts commit 22ba65056c1cb9cf4ea8f898b2735581f348749e.

Revert "Temporarily remove `packFolders` (#8237)"

---

src/module/actor/npc/sheet.ts
src/module/actor/sheet/item-summary-renderer.ts
static/templates/actors/npc/loot-sheet.hbs

Fixes limited and loot sheets not properly sizing nor positioning themselves when first opened. Also fixes the lack of a scrollbar on the npc loot sheet.

Fix NPC limited and loot sheet

---

build/lib/compendium-pack.ts

Add `JournalEntry`, `Macro` and `RollTable` to `CompendiumPack.LINK_PATTERNS`

---

packs/age-of-ashes-bestiary/carnivorous-crystal.json

Closes https://github.com/foundryvtt/pf2e/issues/8312

Add missing critical hits immunity to Carnivorous Crystal

---

build/lib/level-database.ts
src/module/actor/party/kingdom/data.ts
src/module/actor/party/kingdom/model.ts
src/module/rules/rule-element/adjust-modifier.ts
src/module/rules/rule-element/adjust-strike.ts
src/module/rules/rule-element/ae-like.ts
src/module/rules/rule-element/alter-item/schema.ts
src/module/rules/rule-element/aura.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/choice-set/data.ts
src/module/rules/rule-element/choice-set/rule-element.ts
src/module/rules/rule-element/crit-spec.ts
src/module/rules/rule-element/ephemeral-effect.ts
src/module/rules/rule-element/flat-modifier.ts
src/module/rules/rule-element/grant-item/rule-element.ts
src/module/rules/rule-element/iwr/base.ts
src/module/rules/rule-element/iwr/immunity.ts
src/module/rules/rule-element/iwr/resistance.ts
src/module/rules/rule-element/iwr/weakness.ts
src/module/rules/rule-element/roll-note.ts
src/module/rules/rule-element/roll-option.ts
src/module/rules/rule-element/strike.ts
types/foundry/common/abstract/document.d.ts
types/foundry/common/data/data.d.ts
types/foundry/common/data/fields.d.ts
types/foundry/common/documents/ambient-light.d.ts
types/foundry/common/documents/journal-entry-page.d.ts
types/foundry/common/documents/journal-entry.d.ts
types/foundry/common/documents/module.d.ts

Also add `ModelPropsFromSchema` to global namespace

Add type definition of `JournalEntryPageSchema`

---

src/module/item/ancestry/document.ts

Need to fix Adopted Ancestry rule element

Add missing rarity trait to AncestryRollOptions

---

packs/equipment/basic-ingredient.json
packs/equipment/special-ingredient.json

Fix #8309 
Rules can be read up at https://2e.aonprd.com/Rules.aspx?ID=1885

Add cooking ingredients from kingmaker companion guide

---

packs/classfeatures/leaf-order.json
packs/classfeatures/storm-order.json
packs/feats/order-explorer.json

Prevent Order Explorer (Leaf or Storm) from granting focus points

---

src/module/actor/base.ts
src/module/actor/token-effect.ts
src/module/migration/migrations/620-rename-to-webp.ts
src/module/migration/migrations/653-aes-to-res.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/token-effect-icon.ts
types/foundry/client/data/documents/active-effect.d.ts
types/foundry/client/data/documents/actor.d.ts
types/foundry/common/documents/active-effect.d.ts
types/foundry/common/documents/module.d.ts

Update and expand `TemporaryEffect` coverage of `ActiveEffect` interface

---

packs/feats/reveal-true-name.json

https://2e.aonprd.com/Feats.aspx?ID=3028

Add missing True Name trait to Reveal True Name

---

packs/blood-lords-bestiary/grace-the-rhino-owano.json

Closes https://github.com/foundryvtt/pf2e/issues/8378

Add speed bonus to Grace "The Rhino" Owano's Celestial Rage

---

src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/battle-form/schema.ts
src/module/rules/rule-element/battle-form/types.ts

Tested with all insect form effects (heightened and non-heightenend) and all fey form effects.

Add schema to `BattleFormRuleElement`

---

src/module/actor/base.ts
src/module/actor/data/base.ts
src/module/scene/token-document/document.ts
types/foundry/common/data/data.d.ts
types/foundry/common/documents/actor.d.ts

Set prototype tokens' default images in same way as token documents

---

src/module/item/melee/document.ts

Include roll option on NPC attacks indicating whether they are magical

---

packs/pathfinder-society-boons/hireling-expert.json
packs/pathfinder-society-boons/hireling-master.json
packs/pathfinder-society-boons/hireling-professional.json
packs/pathfinder-society-boons/hireling.json

Closes https://github.com/foundryvtt/pf2e/issues/8414
https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Full-Guide#Hireling

Allow PFS Hireling boons to be taken multiple times

---

src/module/actor/creature/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/styles/ui/_hover.scss

- Fix the "stowed" option never appearing
- Prevent removing an item from its (non-stowing) container if selecting the "worn" option
Maybe supersedes #8415, but the PR author may want to build on the now-fixed bug.

Fix pair of bugs with carry-type menu

---

src/module/system/check/check.ts

No clue whether to mark as a bugfix or enhancement, I'll let you decide.

Always skip dialog for flat checks

---

packs/blood-lords-bestiary/mithral-golem.json

Closes https://github.com/foundryvtt/pf2e/issues/8423

Fix reach on Blood Lords Mithral Golem's Spike

---

packs/equipment/throwing-shield.json

Closes https://github.com/foundryvtt/pf2e/issues/8435

Fix Strike category for Throwing Shield

---

src/module/system/check/check.ts

Reevaluate roll note outcome on check reroll

---

src/module/system/text-editor.ts
src/scripts/ui/inline-roll-links.ts
static/lang/en.json

Fix bugs with roller:self

---

src/module/actor/base.ts
src/styles/ui/sidebar/chat/_damage.scss
static/templates/chat/damage/damage-taken-flavor.hbs
static/templates/chat/damage/damage-taken.hbs

Render damage taken message flavor and content separately

---

src/module/actor/sheet/popups/ability-builder.ts

Fix counting of maximum background boosts in ability builder

---

src/module/item/spell/document.ts

Use `DamageRoll` class to validate spell damage formulas

---

src/module/system/statistic/index.ts

Also simplified down the RE that exposed the bug

Acquire new adjustments for check/dc parent modifiers

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/chat-message/helpers.ts

Create separate chat messages for `healing-received` bonus dice rolls

---

packs/ancestryfeatures/greater-darkvision.json

Remove rule element from greater darkvision

---

src/scripts/ui/inline-roll-links.ts

Limit item retrieval for inline roll links to spells

---

packs/spells/etheric-shards.json

Closes https://github.com/foundryvtt/pf2e/issues/8505

Add base level 5 overlay to Etheric Shards and remove overlay level overrides

---

packs/pfs-season-3-bestiary/lesser-animate-dream.json
packs/pfs-season-4-bestiary/combustive-zombie.json
packs/pfs-season-4-bestiary/elite-clacking-skull-swarm.json
packs/pfs-season-4-bestiary/elite-combustive-zombie.json
packs/pfs-season-4-bestiary/elite-smokesight-deadeye-wight.json
packs/pfs-season-4-bestiary/elite-smokesight-hunter-wight.json
packs/pfs-season-4-bestiary/elite-smokesight-prowler-wight.json
packs/pfs-season-4-bestiary/elite-smokesight-stalker-wight.json
packs/pfs-season-4-bestiary/elite-smokesight-wight-captain.json
packs/pfs-season-4-bestiary/elite-smokesight-wight-commander.json
packs/pfs-season-4-bestiary/elite-sulfur-zombie.json
packs/pfs-season-4-bestiary/smokesight-deadeye-wight.json
packs/pfs-season-4-bestiary/smokesight-hunter-wight.json
packs/pfs-season-4-bestiary/smokesight-prowler-wight.json
packs/pfs-season-4-bestiary/smokesight-stalker-wight.json
packs/pfs-season-4-bestiary/smokesight-wight-captain.json
packs/pfs-season-4-bestiary/smokesight-wight-commander.json
packs/pfs-season-4-bestiary/weak-clacking-skull-swarm.json

Also correct strike value for lesser animate dream from PFS 3-19

Add NPCs from PFS 4-15

---

src/module/canvas/helpers.ts
src/module/canvas/measured-template.ts

Fix dragged-template grid highlighting

---

src/module/system/statistic/index.ts

Use token name when available for `Statistic` checks

---

src/module/actor/party/data.ts
src/module/actor/party/document.ts
src/module/actor/party/sheet.ts
src/scripts/config/index.ts
src/styles/actor/party/_exploration.scss
src/styles/actor/party/_index.scss
src/styles/actor/party/_inventory.scss
static/lang/en.json
static/templates/actors/party/regions/exploration.hbs
static/templates/actors/party/regions/inventory-members.hbs
static/templates/actors/party/sheet.hbs

Start on party exploration tab

---

src/module/system/tag-selector/base.ts
src/module/system/tag-selector/basic.ts
static/templates/system/tag-selector/basic.hbs

Fix basic tag selector search

---

src/module/actor/modifiers.ts

Allows implementing kingmaker vacancy penalties, but also adhoc "custom modifier types" without adding to the global modifier type list.

Prefer highest value of same type when deduping modifiers

---

packs/equipment/shatterstone-greater.json
packs/equipment/shatterstone.json

Closes https://github.com/foundryvtt/pf2e/issues/8538

Add missing traits to Shatterstone

---

src/module/actor/character/data.ts
src/module/actor/character/sheet.ts
src/module/actor/party/sheet.ts
src/module/actor/sheet/base.ts
src/styles/actor/character/_actions.scss
src/styles/actor/party/_exploration.scss
src/styles/actor/party/_index.scss
static/lang/en.json
static/template.json
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/party/regions/exploration.hbs

Rest will need to display a new dialog to possibly advance the clock in future revisions.

Allow setting active exploration activities + show in party sheet

---

src/module/rules/rule-element/base.ts

Include parent items' names and UUIDs in `DataModel` validation warnings

---

src/module/actor/character/document.ts
src/module/item/feat/document.ts
src/util/misc.ts

Add fallback for stale template.json

---

src/styles/actor/party/_exploration.scss
src/styles/actor/party/_index.scss
src/styles/actor/party/_inventory.scss
src/styles/actor/party/_overview.scss
static/templates/actors/party/regions/inventory-members.hbs

This primarily affects the restricted view

Fix whitespace and alignment issues in party inventory

---

packs/equipment/cloister-robe-major.json

Fix price of major cloister robe

---

src/styles/actor/familiar/_index.scss
static/templates/actors/familiar-sheet.hbs

+ remove unused css classes + reorder and organize based on general sheet structure

Add scrollbar to familiar sheet

---

src/module/canvas/status-effects.ts
src/scripts/hooks/init.ts
src/scripts/hooks/setup.ts

Fix incorrect condition theme on initial load

---

packs/feats/mummy-dedication.json
src/module/rules/rule-element/actor-traits.ts

Also check applicability of added traits

Handle RE-added traits that may affect actors' modes of being

---

src/module/canvas/status-effects.ts
src/module/system/settings/index.ts
src/scripts/hooks/setup.ts

Fix refresh of death icon on setting change

---

static/lang/re-en.json

capitalization, punctuation, word choice (prefer "select" over "choose")

Standardize language of some choice set prompts

---

packs/feats/city-scavenger.json
static/lang/re-en.json

Closes https://github.com/foundryvtt/pf2e/issues/8595

Allow City Scavenger's subsist bonus to apply to Society

---

packs/spell-effects/spell-effect-healers-blessing.json
packs/spells/healers-blessing.json

I'll add something soon to satisfy the caveat that it only applies the first iteration of recurring healing

Add Spell Effect: Healer's Blessing

---

src/scripts/config/traits.ts
static/lang/en.json

Needed for Battlezoo but also both of these things are ones I can see Paizo winding up at eventually anyways.

Add 120 foot reach to NPC strike list

---

packs/feat-effects/effect-curse-of-the-perpetual-storm.json

Have perpetual storm item alterations alter self

---

src/module/actor/creature/document.ts
src/module/item/condition/document.ts
src/module/system/statistic/index.ts
src/scripts/ui/inline-roll-links.ts
static/lang/en.json

Collect note and DoS adjustment synthetics for recovery checks

---

src/module/system/statistic/index.ts
static/lang/en.json
static/templates/chat/chat-roll-details.hbs

Fix option acquisition and roll inspector for flat checks

---

packs/equipment/dart.json
src/module/actor/character/document.ts
src/module/actor/data/base.ts
src/module/actor/sheet/trick-magic-item-popup.ts
src/module/item/consumable/document.ts
src/module/item/physical/sheet.ts
src/module/item/weapon/data.ts
src/module/item/weapon/document.ts
src/module/item/weapon/sheet.ts
static/lang/en.json
static/templates/items/armor-details.hbs
static/templates/items/consumable-details.hbs
static/templates/items/weapon-details.hbs

Allow thrown weapons to configured for use as ammunition

---

src/module/system/check/check.ts
src/module/system/check/types.ts
src/module/system/degree-of-success.ts
src/module/system/statistic/index.ts
src/module/system/text-editor.ts
src/scripts/ui/inline-roll-links.ts
src/styles/_globals.scss
static/lang/en.json

Add support for targeted inline checks against specified defenses

---

src/module/item/condition/document.ts
src/module/item/helpers.ts
src/module/rules/rule-element/base.ts
src/module/rules/rule-element/ephemeral-effect.ts
src/module/rules/rule-element/grant-item/rule-element.ts
src/module/rules/rule-element/grant-item/schema.ts
src/module/rules/rule-element/item-alteration/alteration.ts
src/module/rules/rule-element/item-alteration/schemas.ts

Add support for in-memory-only grants of condition items

---

packs/age-of-ashes-bestiary/spiritbound-aluum.json
packs/agents-of-edgewatch-bestiary/ilsetsya-wyrmtouched.json
packs/blog-bestiary/hellknight-centaur.json
packs/crown-of-the-kobold-king-bestiary/dismemberment-table.json
packs/fists-of-the-ruby-phoenix-bestiary/tino-oni-form.json
packs/gatewalkers-bestiary/symbiotic-amoeba.json
packs/kingmaker-bestiary/kressle.json
packs/outlaws-of-alkenstar-bestiary/clockwork-sphinx.json

Hellknight Centaur can be found here:
https://paizo.com/community/blog/v5748dyo6sgz9?The-Usual-Suspects

Add skills to some NPCs that were missing them

---

src/module/rules/rule-element/battle-form/rule-element.ts

Fix creation of battle form strikes from data with no traits

---

src/module/actor/base.ts
src/module/system/tag-selector/index.ts
src/scripts/config/index.ts

No longer in use since hazard actor is fully using `Statistic`s

Remove `ActorPF2e#rollAttribute`

---

src/module/encounter/document.ts
src/module/item/abstract-effect/data.ts
src/module/item/effect/document.ts
src/module/system/effect-tracker.ts
src/styles/item/_effect-sheet.scss
src/styles/item/_index.scss
src/styles/item/_sidebar.scss
static/lang/en.json
static/templates/items/effect-sidebar.hbs
static/templates/items/partials/duration.hbs

Add option to reevaluate formula effect badges every turn

---

src/module/actor/base.ts

Copy what I did for the item create dialog in preparation for contextually hiding the army sheet.

Refactor actor create dialog

---

src/module/actor/character/document.ts
src/module/actor/helpers.ts
src/module/actor/modifiers.ts
src/module/system/check/check.ts
src/util/misc.ts
static/lang/en.json
static/templates/actors/character/tabs/actions.hbs

Show adjusted modifier on strike MAP buttons

---

static/templates/actors/character/limited.hbs
static/templates/actors/character/sheet.hbs

Use fa-person-rays for PC sheet effects tab icon

---

static/lang/re-en.json

Needed for something in the future.

Add localized names for each animal form

---

src/module/migration/migrations/849-delete-broken-threshold.ts

Set version in migration 849

---

src/module/actor/sheet/item-summary-renderer.ts
src/module/apps/effects-panel.ts
src/scripts/ui/inline-roll-links.ts

Attempts to tweak it to a get document and a get actor phase, making it more predictable and also work better with items as parameters.

Enable item option acquisition in item summaries

---

src/module/actor/party/document.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/module/actor/party/kingdom/values.ts
src/module/actor/sheet/item-summary-renderer.ts
src/scripts/register-templates.ts
src/styles/actor/party/kingdom/_activities.scss
src/styles/actor/party/kingdom/_advancement.scss
src/styles/actor/party/kingdom/_index.scss
src/styles/actor/party/kingdom/_main.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/activities.hbs
static/templates/actors/party/kingdom/advancement.hbs
static/templates/actors/party/kingdom/builder.hbs
static/templates/actors/party/kingdom/main.hbs
static/templates/actors/party/kingdom/sheet.hbs

Even if kingmaker is enabled, its not currently accessible with doing a data update to set active to true, I'll start the process towards that happening once the compendium and these are merged.
Sibling to https://github.com/foundryvtt/pf2e/pull/8554

Add initial kingdom sheet

---

packs/equipment/sapling-shield-greater.json
packs/equipment/sapling-shield-lesser.json
packs/equipment/sapling-shield-major.json
packs/equipment/sapling-shield-minor.json
packs/equipment/sapling-shield-moderate.json
packs/equipment/sapling-shield-true.json

Closes https://github.com/foundryvtt/pf2e/issues/7167
Modifying bulk is not currently possible.
~~Blocked by https://github.com/foundryvtt/pf2e/pull/8781~~

Update Sapling Shield rule elements

---

src/module/actor/sheet/popups/add-coins-popup.ts
src/module/actor/sheet/popups/remove-coins-popup.ts
src/module/item/physical/helpers.ts
static/templates/actors/add-coins.hbs
static/templates/actors/remove-coins.hbs

Also update add/remove coins popups to enforce the same

Ensure `CoinsPF2e` objects have positive integer values

---

src/module/item/spell/document.ts
src/module/rules/helpers.ts
src/module/system/damage/weapon.ts

If you want to be careful given we're releasing soon, we can do this after the next release. Little preparation for some inline damage upgrades.

Simplify weapon/spell modifier extraction

---

src/module/actor/sheet/base.ts
src/module/apps/hotbar.ts
static/lang/en.json

Send notification when roll options are toggled from macros

---

src/module/actor/party/sheet.ts
src/styles/actor/party/_index.scss
src/styles/actor/party/_overview.scss
static/templates/actors/party/regions/exploration.hbs
static/templates/actors/party/regions/overview.hbs

Add support for party recall knowledge skills

---

src/module/chat-message/document.ts
src/scripts/ui/user-visibility.ts

Fall back to prototype token for determining name visibility of speaker

---

src/module/canvas/token/aura/util.ts
src/module/scene/token-document/aura/index.ts

Test aura coverage with small cluster of origin points

---

src/module/system/text-editor.ts

Fix elite/weak modifications for inline dcs

---

packs/feat-effects/effect-ancestral-influence.json
src/module/rules/rule-element/ae-like.ts
src/module/rules/rule-element/roll-option.ts

Add data-preparation phase support to roll option

---

packs/equipment/twining-chains.json

Closes https://github.com/foundryvtt/pf2e/issues/8901

Fix usage of Twining Chains

---

packs/blood-lords-bestiary/skeleton-rival-corpsekiller.json
packs/blood-lords-bestiary/skeleton-rival-necromancer.json
packs/blood-lords-bestiary/vampire-rival-necromancer.json
packs/blood-lords-bestiary/zombie-rival-necromancer.json

Closes https://github.com/foundryvtt/pf2e/issues/8858

Fix resistances for Vampire Rival and Skeleton Rivals

---

src/module/actor/loot/sheet.ts
src/module/actor/party/sheet.ts
src/module/actor/sheet/data-types.ts
src/module/actor/sheet/popups/distribute-coins-popup.ts
src/styles/actor/_coinage.scss
static/lang/en.json
static/templates/actors/partials/coinage.hbs

Add Distribute Coins button to party sheet

---

src/module/actor/character/document.ts

Prevent armor speed penalty from being doubly applied to derived speeds

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/item/abstract-effect/data.ts
src/module/item/action/data.ts
src/module/item/action/index.ts
src/module/item/action/types.ts
src/module/item/affliction/sheet.ts
src/module/item/data/base.ts
src/module/item/physical/data.ts
src/module/item/spell/document.ts
src/module/migration/migrations/828-prune-invalid-traits.ts
src/module/rules/rule-element/adjust-strike.ts
src/scripts/ui/inline-roll-links.ts

Also move `ActionTrait` to @item/action/types.ts

Display actual traits as such in roll cards from inline checks

---

src/module/item/base.ts
src/scripts/hooks/load.ts
src/styles/_globals.scss
src/styles/system/_effects-panel.scss
static/templates/system/effects-panel.hbs

Fix several display issues with effects panel

---

src/module/actor/familiar/document.ts

Set label for familiar's attack-roll statistic

---

src/module/system/settings/homebrew/menu.ts
src/scripts/hooks/init.ts
src/scripts/hooks/setup.ts

Initialize apply homebrew elements early enough for utilization by REs

---

packs/spells/focusing-hum.json

Closes https://github.com/foundryvtt/pf2e/issues/8985

Fix action cost and traits of Focusing Hum

---

packs/feat-effects/effect-daydream-trance.json

Closes https://github.com/foundryvtt/pf2e/issues/8995

Brush up effect for Daydream Trance

---

src/module/chat-message/data.ts
src/module/chat-message/helpers.ts
src/module/chat-message/listeners/cards.ts
src/module/item/spell/document.ts
src/module/scene/measured-template-document.ts
src/scripts/hooks/canvas-ready.ts
src/styles/legacy/_chat.scss
static/lang/en.json
static/templates/chat/spell-card.hbs

Add "Clear Placed Templates" button to area-effect spell cards

---

src/module/actor/character/document.ts
src/module/actor/npc/document.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/trick.ts
src/module/item/spellcasting-entry/types.ts
static/templates/actors/npc/tabs/spells.hbs

No underlying data changes yet: just a few getters

Change codebase references to spellcasting "abilities" to "attributes"

---

packs/blood-lords-bestiary/basiri-wellspring-keeper.json
packs/blood-lords-bestiary/drowned-mummy.json

Closes https://github.com/foundryvtt/pf2e/issues/8999

Add swim speed to Drowned Mummy. Add resistances to Basiri.

---

src/module/item/abstract-effect/document.ts

Loosen effect-origin safety check

---

src/module/actor/creature/data.ts
src/module/actor/familiar/document.ts
src/module/actor/vehicle/data.ts
src/module/actor/vehicle/document.ts
src/module/system/action-macros/medicine/administer-first-aid.ts
src/module/system/statistic/data.ts
src/module/system/statistic/hit-points.ts
src/module/system/statistic/index.ts
static/lang/en.json

Testing with familiars and vehicles before extending to PCs, NPCs, and (later) armies

Create a `HitPointsStatistic`

---

packs/fists-of-the-ruby-phoenix-bestiary/bul-gae.json
packs/stolen-fate-bestiary/mighty-bul-gae.json

Update Jaws and Thermal Mastery extra damage to suboptions. Add missing Lunar Burst to Bul-Gae and fix action cost for Mighty Bul-Gae. Fix Mighty Bul-Gae to use Improved Knockdown.

Brush up Bul-Gae

---

src/module/item/affliction/document.ts
static/templates/chat/affliction-card.hbs

Add affliction chat template

---

src/module/item/physical/bulk.ts
src/module/system/statistic/index.ts
src/util/dom.ts
src/util/misc.ts

Identical one exists as `Maybe`

Remove `Optional` utility type

---

packs/equipment/aboutface-figurehead.json
packs/equipment/accompaniment-cloak.json
packs/equipment/achaekeks-kiss.json
packs/equipment/acid-spitter.json
packs/equipment/aeon-stone-cymophane-cabochon.json
packs/equipment/aeon-stone-olivine-pendeloque.json

Updated a few equipment images for items with default images.

Updated equipment images.

---

packs/spell-effects/spell-effect-flame-wisp.json

Improve automation of Flame Wisp

---

src/module/actor/inventory/bulk.ts
src/module/actor/npc/data.ts
src/module/actor/npc/document.ts

Set bonus bulk values for NPCs

---

src/module/canvas/perception/modes.ts

Hide GM-hidden tokens from (GMs controlling tokens with) tremorsense

---

packs/equipment/starsong-nectar.json

Correct the price of Starsong Nectar from Treasure Vault

---

packs/pfs-season-4-bestiary/ambush-assassin.json
packs/pfs-season-4-bestiary/nathatel-3-4.json
packs/pfs-season-4-bestiary/nathatel-5-6.json
packs/pfs-season-4-bestiary/nathatel-7-8.json
packs/pfs-season-4-bestiary/serraleth-7-8.json
packs/pfs-season-4-bestiary/serraleth.json

From Alex and Shay for PFS 4-99

Add PFS 4-99 errata from org play major convensions planning server 

---

packs/equipment/earthbreaker.json
packs/equipment/gakgung.json

following the instructions from Tikael: https://discord.com/channels/880968862240239708/880969304365994034/1133823765072072804
I updated file paths of the weapons earthbreaker and gakgung.

Add images to several weapons missing them

---

src/module/actor/base.ts
src/module/encounter/document.ts
src/module/macro.ts
static/system.json

plus remove or extend workarounds of upstream issues

Indicate compatibility with FVTT 11.307

---

src/module/system/damage/helpers.ts

The if/else wall is starting to intimidate me.

Handle top level math terms and subtraction in @Damage

---

src/module/system/text-editor.ts

Respect `overrideTraits` (and its absence) in @Damage expressions

---

packs/feats/martial-performance.json

Add automation for Martial Performance feat

---

packs/pfs-season-1-bestiary/cinder-wolf-1-2.json
packs/pfs-season-1-bestiary/cinder-wolf-3-4.json

Add knockdown to cinder wolf strikes from PFS 1-14

---

src/module/system/text-editor.ts

Attribute the @Damage roll to the actor that owns it

---

src/module/system/damage/helpers.ts

This should make the whole thing easier to grok.
In general, if a term is deterministic, we don't have to check what it is, we can use DamageInstance.getValue() and simplify it immediately.

Refactor @Damage extraction to use DamageInstance.getValue() more

---

packs/agents-of-edgewatch-bestiary/obrousian.json
packs/book-of-the-dead-bestiary/obrousian.json

Add missing spell DC to Obrousian

---

packs/equipment/eldritch-flare.json

Fix inline damage of Eldritch Flare

---

packs/blood-lords-bestiary/choking-tethers.json

Fix immunities of Choking Tethers hazard

---

packs/spells/grasping-grave.json

Add area to Grasping Grave focus spell

---

src/module/actor/familiar/data.ts
src/module/actor/familiar/document.ts
src/module/actor/familiar/sheet.ts
static/templates/actors/familiar-sheet.hbs

Use `Statistic` for familiar attack-roll statistic

---

src/scripts/config/index.ts
static/lang/en.json

Add Shory Language from Stolen Fate Player's Guide

Add Shory Language from Stolen Fate Player's Guide

---

src/module/chat-message/listeners/cards.ts
src/module/item/affliction/document.ts
static/templates/chat/affliction-card.hbs

Handling save button for affliction

---

packs/classfeatures/way-of-the-spellshot.json

Force attribute modifier of spellshot class DC to be int

---

packs/spells/one-with-stone.json

Add duration and traditions to One with Stone

---

src/module/scene/document.ts
src/module/scene/token-document/document.ts

Closes #8948
Thanks @this-gavagai for investigating

Determine that scene is in focus before checking auras

---

src/module/rules/rule-element/aura.ts

So there aren't a dozen kinetic auras on a single actor: if an existing aura has the same slug as a new one on the actor, setting `mergeExisting` to true will merge the second aura into the first, combining effects and traits.

Add `mergeExisting` property to Aura RE

---

packs/spells/elemental-betrayal.json

Updated Lesson of Element's Focus Spell Elemental Betrayal spellType from attack to utility

Updated Lesson of Element's Focus Spell spellType

---

packs/equipment/witchwyrd-beacon.json

Fix name of Witchwyrd Beacon

---

src/module/item/spell/document.ts

plus itty bitty refactor of spellcasting ability acquisition wrt trick magic item (will do more later).

Allow trick magic item counteract

---

packs/bestiary-effects/effect-bullys-rage.json
packs/bestiary-effects/effect-pulse-of-rage.json
packs/classfeatures/rage.json
packs/feat-effects/effect-rage.json
packs/feat-effects/effect-share-rage.json
packs/iconics/amiri-level-1.json
packs/iconics/amiri-level-3.json
packs/iconics/amiri-level-5.json
packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
packs/paizo-pregens/popcorn-level-4.json
packs/paizo-pregens/popcorn.json

The existing one is under a kilobyte and can stick around indefinitely.

Use core icon for rage effect

---

packs/feats/through-the-gate.json

Fix filter on Through the Gate feat

---

packs/actions/a-quick-glimpse-beyond.json
packs/actions/avoid-dire-fate.json
packs/actions/chaotic-destiny.json
packs/actions/decompose.json
packs/actions/fated-not-to-die.json
packs/actions/harrow-the-fiend.json
packs/actions/lucky-break.json
packs/actions/recall-under-pressure.json
packs/feats/moldersoul.json

Closes #9262 
Also set some action icons that were missing them.

Add missing Decompose action

---

packs/equipment/sawtooth-saber.json
packs/paizo-pregens/eteleon.json
packs/paizo-pregens/yacob.json
packs/paizo-pregens/zeah.json

Closes https://github.com/foundryvtt/pf2e/issues/9286

Fix Sawtooth Saber bulk

---

src/module/actor/character/sheet.ts

(rather than repeatedly accessing the getter)

Retrieve `this.actor` early in `CharacterSheetPF2e#getData`

---

packs/feats/dazing-blow.json
static/lang/re-en.json

Closes https://github.com/foundryvtt/pf2e/issues/9298

Add automation to Dazing Blow

---

packs/equipment-effects/effect-voice-of-oceans.json
packs/equipment/conch-of-otherworldly-seas.json

Supersedes https://github.com/foundryvtt/pf2e/pull/9290

Move Conch of Otherworldly Seas' Voice of Oceans automation to effect

---

src/module/actor/character/sheet.ts
src/module/encounter/document.ts
static/lang/en.json

Also:
- Disable if already rolled initiative
- Kill the jquery

Consolidate PC sheet's roll-initiative toggle methods

---

src/module/actor/modifiers.ts

Prevent doubling of splash damage dice on NPC attacks

---

src/module/actor/item-transfer.ts
src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/module/actor/party/sheet.ts
src/module/actor/party/types.ts
src/module/actor/sheet/base.ts
src/module/item/sheet/base.ts
src/scripts/hooks/close-world-clock-settings.ts
src/scripts/socket.ts

Also brings up the current tab (gm can direct everyone to exploration activities)

Add show sheet button to party, kingdom, and builder

---

src/module/apps/pick-a-thing-prompt.ts
src/module/rules/rule-element/choice-set/prompt.ts
src/util/dom.ts

Kill the jqueries along the way

Fix actor sheet becoming uneditable after choice set RE aborts

---

packs/gatewalkers-bestiary/immolis.json

Closes https://github.com/foundryvtt/pf2e/issues/9328

Fix Immolis' Heat Beam DC

---

src/module/item/ability/data.ts
src/module/item/ability/document.ts
src/module/item/ability/helpers.ts
src/module/item/ability/sheet.ts
src/module/item/campaign-feature/sheet.ts
src/module/item/feat/data.ts
src/module/item/feat/document.ts
src/module/item/feat/helpers.ts
src/module/item/feat/sheet.ts
src/scripts/register-templates.ts
src/styles/item/_ability-sheet.scss
src/styles/item/_feat-sheet.scss
src/styles/item/_index.scss
src/styles/item/_self-applied-effect.scss
static/lang/en.json
static/templates/items/action-details.hbs
static/templates/items/feat-details.hbs
static/templates/items/partials/self-applied-effect.hbs
static/templates/items/sheet.hbs

This is just the data and sheet part: will follow up with inclusion in chat messages.

Add support for including self-applied effects in ability/feat items

---

src/module/item/abc/sheet.ts
static/templates/items/ancestry-details.hbs
static/templates/items/background-details.hbs
static/templates/items/class-details.hbs

Make embedded abc items viewable from item sheet

---

src/module/encounter/combatant.ts
src/module/encounter/document.ts
src/module/item/effect/document.ts
src/module/system/effect-tracker.ts

Check familiars' effects when encounter turns change

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/data-types.ts
src/styles/actor/_inventory.scss
static/templates/actors/partials/item-line.hbs

https://github.com/foundryvtt/pf2e/assets/1286721/aef62417-fa68-44cf-a4c7-2ae99a22134a

Make invest icon glowy when armor is equipped but not invested

---

packs/classfeatures/impulses.json
packs/feats/versatile-blasts.json

Will localize if this is the approach we want to take.

Add elemental blast choices to actor data

---

build/run-migration.ts
packs/classfeatures/greater-weapon-specialization-barbarian.json
packs/classfeatures/greater-weapon-specialization.json
packs/classfeatures/psychic-weapon-specialization.json
packs/classfeatures/weapon-specialization.json
packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
packs/kingmaker-bestiary/valerie-level-9.json
src/module/migration/migrations/850-flat-footed-to-off-guard.ts
src/module/migration/migrations/857-weapon-spec-re.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/rules/rule-element/adjust-modifier.ts
src/module/system/damage/weapon.ts

Also adds weapon specialization to psychic, which wasn't working before.

Convert weapon specialization to rule elements

---

src/module/actor/party/sheet.ts
src/styles/ui/_hover.scss
static/templates/actors/party/regions/exploration.hbs

Show hover item summary in party exploration tab

---

src/module/actor/data/iwr.ts

Include ghost touch in set of non-damage weaknesses

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/item-summary-renderer.ts
src/styles/actor/_red-action-boxes.scss
src/styles/actor/character/_actions.scss
src/styles/actor/npc/_index.scss
src/styles/actor/tabs/_actions.scss
static/lang/action-en.json
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/familiar-sheet.hbs
static/templates/actors/npc/partials/action.hbs
static/templates/actors/npc/partials/attack.hbs
static/templates/chat/action-card.hbs
static/templates/items/partials/ability-activation.hbs

Step 2/3: after this is making it send a message with a collapsed description and "Apply Effects" button.

Add "use" button to sheets for actions with self-applied effects

---

src/styles/ui/sidebar/chat/_chat-inspect-roll.scss

Make domains in roll inspector user-selectable

---

src/module/item/physical/document.ts
src/module/rules/rule-element/choice-set/rule-element.ts

Also add rarity to physical-item roll options

Fix `baseItem` index field in choice set RE, add `potencyRune`

---

src/module/actor/character/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/vehicle/sheet.ts
src/scripts/register-templates.ts
src/styles/_globals.scss
src/styles/actor/tabs/_actions.scss
src/styles/actor/vehicle/_index.scss
src/styles/ui/_icons.scss
static/templates/actors/character/tabs/actions.hbs
static/templates/actors/partials/action.hbs
static/templates/actors/vehicle/tabs/vehicle-actions.hbs

This required a bit of a refactor due to shared styling. The action markup is now in a separate, shared partial template.

Fix regression in display of actions on vehicle sheet

---

packs/pathfinder-bestiary-2/doprillu.json
packs/stolen-fate-bestiary/sickened-doprillu.json

Closes https://github.com/foundryvtt/pf2e/issues/9445

Add automation to Doprillu's Mask of Power

---

src/module/actor/party/kingdom/builder.ts
src/styles/actor/party/kingdom/_builder.scss
static/templates/actors/party/kingdom/builder.hbs

Not perfect, but it should be easier for players to follow along the building process when using "Show Players".

Make kingdom builder look nicer to players

---

src/scripts/ui/user-visibility.ts
src/styles/_globals.scss
static/templates/chat/spell-card.hbs

Conditionally hide some chat buttons using data-visibility

---

src/module/actor/item-transfer.ts
src/scripts/macros/raise-a-shield.ts
static/templates/chat/action/flavor.hbs

Also defer localization of trait descriptions

Pass glyphs directly to chat/action/flavor.hbs

---

packs/spells/force-cage.json
src/module/item/spell/document.ts
src/scripts/ui/inline-roll-links.ts

Closes https://github.com/foundryvtt/pf2e/issues/9475

Fix rectangle templates and fix Force Cage to be cube

---

src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/trick.ts
src/module/system/check/types.ts
src/module/system/statistic/index.ts

Also automatically add domains to attack rolls

Remove "spell-attack-roll" check type

---

src/styles/actor/_red-action-boxes.scss
static/templates/actors/npc/partials/action.hbs
static/templates/actors/npc/partials/attack.hbs

Fix display of melee-item descriptions on NPC sheets

---

src/styles/ui/sidebar/chat/_action.scss

Tweak position of damage-button cue

---

packs/spell-effects/spell-effect-angelic-halo.json
packs/spell-effects/spell-effect-eat-fire.json

Closes https://github.com/foundryvtt/pf2e/issues/9536

Fix Eat Fire resistance formula

---

src/module/actor/familiar/document.ts
static/lang/en.json

Fix creation of familiar `ArmorClass` statistic

---

packs/book-of-the-dead-bestiary/phantom-footsteps.json

Closes https://github.com/foundryvtt/pf2e/issues/9568

Fix level of Phantom Footsteps

---

src/module/system/check/dialog.ts

Strip HTML from check dialog titles

---

packs/classfeatures/impulses.json
packs/feats/versatile-blasts.json
static/lang/re-en.json

This data structure is more suited to how the elemental blast API it turning out

Rewrite elemental blast flag structure for easier data access

---

packs/actions/rage.json
packs/classfeatures/rage.json

Have the Rage class feature grant the Rage action

---

packs/feats/manifold-modifications.json

Automate Manifold Modifications

---

packs/pathfinder-bestiary-2/quoppopak.json
packs/stolen-fate-bestiary/quoppopak-mummy.json

Closes https://github.com/foundryvtt/pf2e/issues/9589

Automate Quoppopak Tentacle Stab damage override

---

src/module/item/weapon/document.ts

Correctly source damage type of weapons for roll options

---

src/module/rules/rule-element/damage-dice.ts

Allow multiple selectors in DamageDice REs

---

src/module/chat-message/listeners/cards.ts
src/styles/ui/sidebar/chat/_action.scss
static/lang/en.json

Clear "Apply Effect" buttons in chat messages after clicking

---

packs/spell-effects/spell-effect-glass-shield.json
packs/spells/glass-shield.json

Closes https://github.com/foundryvtt/pf2e/issues/9382

Fix Glass Shield's spell effect hit points

---

src/module/item/physical/document.ts

Fix worn bulk of container items

---

src/module/item/effect/document.ts

Specifically ones with zero-round, end-of-turn durations
Closes #7983

Prevent some effects from immediately expiring outside combat

---

src/module/actor/party/document.ts
src/module/actor/party/helpers.ts
src/scripts/register-keybindings.ts

I suppose we'll need a migration with this as well

Fix P keybind fetching active party

---

src/global.ts
src/module/actor/party/document.ts
src/module/apps/sidebar/actor-directory.ts
src/module/system/settings/index.ts
src/scripts/hooks/ready.ts
src/styles/ui/sidebar/_actor-directory.scss

And makes the No members display a bit smaller.

Save active party folder state and default to expanded

---

packs/feat-effects/effect-weapon-infusion.json
src/module/actor/character/elemental-blast.ts
static/templates/actors/character/partials/elemental-blast.hbs

Add additional damage types from weapon infusion effect

---

src/module/actor/character/sheet.ts

Fix feat browser pre-filtering on traits with hyphens

---

packs/classes/kineticist.json
packs/feats/kineticist-dedication.json

Add necessary class features to kineticist dedication

---

src/module/actor/character/sheet.ts
src/module/actor/creature/sheet.ts
src/styles/actor/character/_spellcasting.scss
static/templates/actors/character/tabs/spellcasting.hbs

Fix rolling checks for item only spellcasting entries

---

src/module/actor/party/sheet.ts
src/module/system/settings/metagame.ts
static/lang/en.json
static/templates/actors/party/regions/exploration.hbs
static/templates/actors/party/regions/overview.hbs
static/templates/actors/party/sheet.hbs

Also place party-related metagame permissions next to each other

Hide HP bar when stats are hidden

---

src/module/item/spell/document.ts

Internal thing. Introduces arcane-damage or thaumaturge-damage or whatever. I'm going to handle inline damage separately.

Include base spellcasting statistic in spell damage domains

---

src/styles/_colors.scss
src/styles/_tags.scss
src/styles/actor/_coinage.scss
src/styles/actor/_index.scss
src/styles/actor/_inventory.scss
src/styles/actor/_red-action-boxes.scss
src/styles/actor/npc/_index.scss
src/styles/actor/npc/_inventory.scss
src/styles/actor/npc/_spells.scss
src/styles/actor/npc/forms/_npc-skills-editor.scss
src/styles/item/_index.scss
src/styles/legacy/_pf2e.scss
static/templates/items/sheet.hbs

Also reverse course on some white-color replacements but use variables

Add more trait color variables, utilize in NPC sheet

---

src/styles/actor/party/_index.scss
static/templates/actors/party/sheet.hbs

Regression that occurred due to the followup prs after it turned into a grid.

Fix party actor type label alignment

---

src/module/system/text-editor.ts
static/lang/en.json

Restricted to sluggified that ends with -damage.

Allow custom domains for inline damage rolls

---

src/module/system/damage/damage.ts
src/module/system/text-editor.ts

Internal only, I don't think anything was relying on this *yet*.

Fix resolvables for @Damage roll notes

---

src/module/actor/character/data.ts
src/module/actor/creature/data.ts
src/module/actor/data/base.ts
src/module/actor/familiar/data.ts
src/module/actor/hazard/data.ts
src/module/actor/loot/data.ts
src/module/actor/npc/data.ts
src/module/actor/party/data.ts
src/module/actor/party/document.ts
static/template.json

Also remove party level from template.json

Define `system.details.alliance` in all actor-source interfaces

---

packs/equipment-effects/effect-numbing-tonic-greater.json
packs/equipment-effects/effect-numbing-tonic-lesser.json
packs/equipment-effects/effect-numbing-tonic-major.json
packs/equipment-effects/effect-numbing-tonic-minor.json
packs/equipment-effects/effect-numbing-tonic-moderate.json
packs/feat-effects/effect-aura-junction-wood.json
packs/feat-effects/stance-arcane-cascade.json

Set explicit `onCreate` event options in TempHP REs

---

src/module/actor/character/sheet.ts
src/styles/actor/character/_attribute-builder.scss
static/templates/actors/character/attribute-builder.hbs

Restore legacy boost row in attribute builder

---

packs/rage-of-elements-bestiary/capritellix.json

Closes https://github.com/foundryvtt/pf2e/issues/9793

Add Capritellix

---

src/module/actor/sheet/base.ts
src/styles/actor/_coinage.scss
src/styles/actor/_inventory.scss
src/styles/actor/character/_inventory.scss
src/styles/actor/npc/_inventory.scss
src/styles/actor/party/_index.scss
src/styles/actor/party/_inventory.scss
static/lang/en.json
static/templates/actors/character/tabs/inventory.hbs
static/templates/actors/partials/inventory.hbs
static/templates/actors/partials/item-line.hbs
static/templates/actors/party/sheet.hbs

- coin values
- rarity colors (to all actor sheet inventories)
- total bulk

Add UI/UX enhancements to party stash tab

---

src/module/item/base.ts
src/module/item/melee/document.ts
src/module/item/physical/document.ts
src/module/item/spell/document.ts

Conditionally set "item:magical" roll option for all item types

---

packs/spell-effects/spell-effect-phase-familiar.json
packs/spells/phase-familiar.json

(pedrogrullada) Add spell effect for Phase Familiar

---

src/module/system/text-editor.ts
src/scripts/ui/inline-roll-links.ts

Attempt to retrieve roll data for inline links via `dataset.itemUuid`

---

src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_activities.scss
src/styles/actor/party/kingdom/_index.scss
src/styles/actor/party/kingdom/_main.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/main.hbs
static/templates/actors/party/kingdom/sheet.hbs

* Add hover for vacancy penalties
* Add support for effects
* Visual Tweaks to ability scores

Add additional kingdom features and tweaks

---

src/styles/_tags.scss

Widen left/right border of paizo-style trait tags

---

packs/abomination-vaults-bestiary/siora-fallowglade.json
packs/impossible-lands-bestiary/cursed-king.json
packs/monsters-of-myth-bestiary/ulistul.json
packs/night-of-the-gray-death-bestiary/gray-gardener-assassin.json
packs/night-of-the-gray-death-bestiary/zintaya-calbieste.json

Also add fist attack to Cursed King

Brush up NPC automation for Mark for Death and Dismantler. Add automation to Cursed King's Berserk.

---

src/module/actor/party/kingdom/schema.ts

Add module prop to kingdom schema

---

src/module/scene/data.ts
src/module/scene/document.ts
src/module/scene/sheet.ts
src/scripts/config/index.ts
src/styles/scene/_sheet.scss
static/lang/en.json
static/templates/scene/sheet-partials.hbs

Add rules-based vision override for individual scenes

---

src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_activities.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/activities.hbs

Add support for kingdom phase summaries

---

src/module/scene/data.ts
src/module/scene/document.ts
src/module/scene/sheet.ts
src/module/scene/token-document/document.ts
src/styles/scene/_sheet.scss
static/lang/en.json
static/templates/scene/sheet-partials.hbs

Add hearing range to system scene settings

---

src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_activities.scss
src/styles/actor/party/kingdom/_main.scss
static/templates/actors/party/kingdom/main.hbs

Also adds support for opening the leader actor sheet

Visual tweaks to kingdom leaders and control dc

---

src/module/actor/character/data.ts
src/module/actor/character/document.ts
src/module/actor/creature/data.ts
src/module/actor/data/base.ts
src/module/actor/familiar/document.ts
src/module/actor/hazard/data.ts
src/module/actor/hazard/document.ts
src/module/actor/initiative.ts
src/module/actor/modifiers.ts
src/module/actor/npc/document.ts
src/module/actor/sheet/spellcasting-dialog.ts
src/module/actor/values.ts
src/module/item/spell/document.ts
src/module/item/spellcasting-entry/document.ts
src/module/item/spellcasting-entry/trick.ts
src/module/rules/rule-element/special-statistic.ts
src/module/system/statistic/armor-class.ts
src/module/system/statistic/data.ts
src/module/system/statistic/hit-points.ts
src/module/system/statistic/index.ts
src/scripts/config/index.ts

Also:
- `Statistic#data#ability` to `Statistic#data#attribute`
- `createAbilityModifier` to `createAttributeModifier`
- `SKILL_EXPANDED#ability` to `SKILL_EXPANDED#attribute`

Rename `Statistic#ability` to `Statistic#attribute`

---

src/module/system/text-editor.ts

Hopefully should make it a bit more clear what's going on in this function. Moves label acquisition to before the element is built.

Minor refactor to check creation

---

src/scripts/ui/inline-roll-links.ts

Unfortunately supporting full item retrieval is a more involved process than I think we have time for, since we'd need to verify it works from the text editor end as well.

Support campaign features for inline checks

---

src/module/actor/character/sheet.ts
src/module/actor/party/kingdom/sheet.ts
src/module/apps/compendium-browser/data.ts
src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/loader.ts
src/module/apps/compendium-browser/tabs/campaignFeature.ts
src/module/apps/compendium-browser/tabs/data.ts
src/module/apps/compendium-browser/tabs/index.ts
src/styles/actor/party/kingdom/_activities.scss
static/lang/en.json
static/templates/actors/character/partials/feat-slot.hbs
static/templates/actors/character/tabs/effects.hbs
static/templates/actors/character/tabs/feats.hbs
static/templates/actors/party/kingdom/advancement.hbs
static/templates/compendium-browser/compendium-browser.hbs

Plus convert feat-browse css class to browse-feats data-action.

Support kingmaker campaign features in compendium browser

---

src/module/apps/sidebar/encounter-tracker.ts
src/module/encounter/document.ts
src/scripts/macros/xp/index.ts
src/styles/_globals.scss
src/styles/ui/sidebar/_encounter-tracker.scss
static/lang/en.json
static/templates/sidebar/encounter-tracker/threat-xp.hbs

Show basic threat/XP data in encounter tracker

---

src/module/item/sheet/base.ts
src/module/item/sheet/rule-elements/base.ts
src/module/item/sheet/rule-elements/fast-healing-form.ts
src/module/item/sheet/rule-elements/flat-modifier-form.ts
src/module/item/sheet/rule-elements/grant-item-form.ts
src/module/item/sheet/rule-elements/roll-note-form.ts
src/module/rules/rule-element/fast-healing.ts
src/module/rules/rule-element/flat-modifier.ts
src/module/rules/rule-element/roll-note.ts
static/templates/items/rules/flat-modifier.hbs
static/templates/items/rules/grant-item.hbs
types/foundry/common/data/fields.d.ts

This also fixes the allowDuplicates default in the grant item form.

Auto-clean re form props using schema + fix grant item defaults

---

packs/feats/elemental-eyes.json
packs/feats/elemental-lore.json
packs/feats/genie-weapon-expertise.json
packs/feats/genie-weapon-familiarity.json
packs/feats/genie-weapon-flourish.json
packs/feats/miraculous-repair.json
packs/feats/noble-resolve.json
packs/feats/planar-sidestep.json
packs/feats/skillful-tail-geniekin.json

Add Talos and Ardande traits to geniekin feats

---

packs/pfs-season-4-bestiary/grace-of-the-owl.json

Add missing NPC from PFS 4-12

---

src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_main.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/main.hbs

As well as hover over tooltip descriptions.

Add fields for every kingdom commodity structure

---

packs/feat-effects/effect-curse-of-turbulent-moments.json
packs/feats/crimson-shroud.json
src/module/rules/rule-element/item-alteration/rule-element.ts

Include sample application of change

Allow item alteration REs to specify item IDs instead of predicating

---

src/module/item/armor/document.ts
src/module/item/physical/document.ts
src/module/item/weapon/document.ts
src/module/rules/rule-element/item-alteration/alteration.ts

I wanted to get this in but will be moving it all to a helper before expanding it any further.

Change armor name according to precious material

---

src/module/actor/party/kingdom/model.ts
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/collection.hbs

Implement collect button for kingdom resources and commodities

---

packs/equipment-effects/effect-ginger-chew.json
packs/equipment-effects/effect-journeybread-power.json
packs/equipment/ginger-chew.json
packs/equipment/journeybread-power.json
packs/equipment/journeybread.json
packs/equipment/missive-mint.json

Add effects for Journeybread (Power) and Ginger Chew

---

packs/equipment/aerial-cloak.json
packs/equipment/dwarven-dorn-dergar.json
packs/equipment/starfaring-cloak.json

Also fix formatting of Starfaring Cloak description and add icons to Aerial Cloak and Dwarven Dorn-Dergar.

Add token light to Starfaring Cloak and add icon

---

packs/equipment/alchemical-chart-greater.json
packs/equipment/alchemical-chart-lesser.json
packs/equipment/alchemical-chart-moderate.json
packs/equipment/corset-knife.json
packs/equipment/everburning-coal.json
packs/equipment/menders-soup.json
packs/equipment/rhythm-bone-greater.json
packs/equipment/rhythm-bone.json

Also reformat Rhythm Bone description

Add icons to some equipment

---

src/module/rules/helpers.ts

Provision necessary roll options for ephemeral-effect extraction

---

packs/spell-effects/spell-effect-flashy-disappearance.json
packs/spells/flashy-disappearance.json

Also add icon and description.

Update Flashy Disappearance effect to include grant of Invisible

---

src/module/actor/party/document.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/styles/actor/party/kingdom/_main.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/main.hbs

Also implements the unrest penalty and fixes an issue with data preparation.

Display unrest and consumption on the kingdom sheet

---

src/module/actor/party/document.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/types.ts
src/styles/actor/party/kingdom/_world.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/world.hbs

Still awful looking, but its starting to gain a shape. Also has a fix for kingdom data preparation.

Start initial layout for the kingdom world tab

---

src/module/apps/compendium-browser/tabs/feat.ts

When the `Ancestry Feat` category is selcted Ancestry Feats without an ancestry trait are now always shown regardless of the selected traits.
Closes #9803

Fix ancestry feats without an ancestry trait being filtered in the compendium browser feats tab

---

packs/equipment-effects/effect-ooze-ammunition-greater.json
packs/equipment-effects/effect-ooze-ammunition-lesser.json
packs/equipment-effects/effect-ooze-ammunition-major.json
packs/equipment-effects/effect-ooze-ammunition-moderate.json
packs/equipment/ooze-ammunition-greater.json
packs/equipment/ooze-ammunition-lesser.json
packs/equipment/ooze-ammunition-major.json
packs/equipment/ooze-ammunition-moderate.json
packs/equipment/oxygen-ooze.json
static/lang/re-en.json

Also added icon for Oxygen Ooze

Add automation for Ooze Ammunition

---

src/module/actor/party/sheet.ts
src/styles/actor/party/_overview.scss
static/lang/en.json
static/templates/actors/character/limited.hbs
static/templates/actors/party/regions/overview.hbs

- member name
- gender/pronouns
- level ancestry class
Before:
After:

Include fuller blurb for each member in party sheet overview

---

src/module/actor/sheet/base.ts
types/foundry/client/application/form-application/document-sheet/actor-sheet.d.ts

Also remove usage of `ElementDragEvent`
This doesn't fix anything on my end, but a real event should be sent anyway.

Send real `DragEvent` from `ActorSheetPF2e#emulateItemDrop`

---

src/module/actor/character/sheet.ts
src/module/actor/creature/sheet.ts
src/module/actor/creature/spell-preparation-sheet.ts
src/module/actor/loot/sheet.ts
src/module/actor/party/sheet.ts
src/module/actor/sheet/base.ts
src/module/actor/sheet/loot/move-loot-popup.ts
types/foundry/client/application/form-application/document-sheet/actor-sheet.d.ts

Also further reduce usage of `ElementDragEvent`

Kill remaining jquery in base actor sheet

---

src/module/system/check/check.ts

Third time's the charm?
I didn't know that actors expose their armor `StatisticDifficultyClass` which makes the whole thing a lot easier.
Applied AC adjustments are now correctly shown for rerolls and the icon on the damage buttons is rendered correctly for the new outcome.
Supersedes #9640 and #10008

Restore `CheckDC` statistic value from context flag in attack roll rerolls

---

packs/equipment/alicorn-lance.json
packs/equipment/dancers-spear.json
packs/equipment/fulminating-spear.json
static/lang/re-en.json

Also add icons to Dancer's Spear and Fulminating Spear. Reformat descriptions of Alicorn Lance and Fulminating Spear. Add localized label for Alicorn Lance and Fulminating Spear. Add TokenEffectIcon to Alicorn Lance.

Add light automation to Fulminating Spear. Fix action cost of Alicorn Lance activation.

---

src/module/apps/pick-a-thing-prompt.ts
src/module/rules/rule-element/choice-set/prompt.ts
src/styles/system/_choice-set-prompt.scss
static/lang/re-en.json
static/templates/system/rules-elements/choice-set-prompt.hbs

[choice-item-info.webm](https://github.com/foundryvtt/pf2e/assets/41452412/ea879725-effe-4f79-b0cb-552bca9cee92)
Closes #9404

Show a button on the `ChoiceSetPrompt` that opens the item sheet when the choice has a UUID

---

packs/equipment-effects/effect-tacticians-helm-move-it.json
packs/equipment/tacticians-helm.json
packs/journals/gm-screen.json

Add automation to Tactician's Helm

---

src/module/actor/types.ts
src/module/canvas/token/aura/map.ts
src/module/canvas/token/aura/renderer.ts
src/module/canvas/token/object.ts
src/module/rules/rule-element/aura.ts

Also fix some rendering differences between GMs and players

Add aura texture configuration option of whether to loop video

---

src/module/rules/rule-element/choice-set/prompt.ts
src/styles/system/_choice-set-prompt.scss
static/lang/re-en.json
static/templates/system/rules-elements/choice-set-prompt.hbs

Tweak language in tooltips, as well

Fix some quirks with choice set prompt info button styling

---

packs/spell-effects/spell-effect-thermal-remedy.json
packs/spells/thermal-remedy.json
static/lang/re-en.json

~~Blocked by https://github.com/foundryvtt/pf2e/pull/10087~~

Add effect for Thermal Remedy

---

src/module/item/sheet/base.ts
src/module/item/sheet/rule-elements/base.ts
src/module/item/sheet/rule-elements/fast-healing-form.ts
src/module/item/sheet/rule-elements/flat-modifier-form.ts
src/styles/item/_rules.scss
static/templates/items/rules-panel.hbs
static/templates/items/rules/fast-healing.hbs
static/templates/items/rules/flat-modifier.hbs
static/templates/items/rules/outer.hbs
static/templates/items/rules/partials/resolvable-brackets.hbs
static/templates/items/rules/partials/resolvable-value.hbs
types/foundry/client/application/templates.d.ts

Tough call between enhancement or bugfix, but given that the form was clobbering brackets before, its probably a bugfix?

Support brackets in fast healing RE form

---

src/module/item/physical/runes.ts
static/templates/items/weapon-details.hbs

Fix labeling and options presentation of striking runes in weapon sheet

---

src/module/actor/party/document.ts
src/module/apps/sidebar/encounter-tracker.ts
src/module/encounter/document.ts
src/module/system/text-editor.ts
src/scripts/hooks/ready.ts
src/styles/ui/sidebar/_encounter-tracker.scss
static/lang/en.json
static/templates/sidebar/encounter-tracker/threat-award.hbs
static/templates/sidebar/encounter-tracker/threat-xp.hbs

Add tooltips explaining threat and award in encounter tracker

---

packs/feats/additional-circus-trick.json

Add missing feat from EC player's guide

---

packs/familiar-abilities/skilled.json
packs/spells/nudge-fate.json

(dogstarrb) Remove unneeded Will save button from Nudge Fate
(websterguy) Fix reference to master ability in Skilled familiar ability flat modifier

Data Entry World Fixes September 16 2023

---

src/module/item/physical/runes.ts
static/lang/en.json

Closes https://github.com/foundryvtt/pf2e/issues/10160

Handle Grievous rune for picks

---

src/module/item/physical/runes.ts
static/lang/en.json

Reverts foundryvtt/pf2e#10161
Already handled

Revert "Handle Grievous rune for picks"

---

src/styles/actor/_inventory.scss

Remove coloration of common-rarity inventory items

---

packs/spells/runic-weapon.json

Closes https://github.com/foundryvtt/pf2e/issues/10149

Fix effect link name in Runic Weapon spell

---

packs/spell-effects/spell-effect-repel-metal.json
packs/spells/detect-metal.json
packs/spells/repel-metal.json

Also add icon for Repel Metal and Detect Metal.

Add effect for Repel Metal and fix level

---

src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/sheet.ts
src/module/actor/party/kingdom/types.ts
src/module/actor/party/kingdom/values.ts
src/scripts/register-templates.ts
src/styles/actor/party/kingdom/_builder.scss
src/styles/actor/party/kingdom/_features.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/builder.hbs
static/templates/actors/party/kingdom/partials/build-entry-boosts.hbs
static/templates/actors/party/kingdom/tabs/activities.hbs
static/templates/actors/party/kingdom/tabs/features.hbs

Implement government skills and show boosts/flaws/skills in kingdom sheet

---

src/module/canvas/token/aura/renderer.ts
src/module/canvas/token/aura/util.ts
src/module/canvas/token/object.ts
src/module/scene/token-document/aura/index.ts
src/module/scene/token-document/document.ts

Fix aura rendering and detection for tiny tokens

---

src/module/system/damage/modifier-dialog.ts
src/styles/ui/_damage-dialog.scss
static/templates/chat/damage/damage-modifier-dialog.hbs

Fix display of bonus dice in damage roll dialog

---

src/styles/actor/character/_biography.scss
src/styles/actor/character/_character.scss
static/templates/actors/character/tabs/biography.hbs
static/templates/actors/character/tabs/general.hbs

Move character height/weight to biography

---

src/module/actor/base.ts
src/module/actor/inventory/index.ts
src/module/actor/sheet/base.ts
src/module/item/physical/document.ts

This will create conflicts with #10092 but should be merged first.

Move `ActorPF2e#findStackableItem` to `ActorInventory` and use `Remeda.equals` to determine stackability

---

src/module/item/sheet/rule-elements/base.ts
src/module/item/sheet/rule-elements/index.ts
src/module/item/sheet/rule-elements/token-light-form.ts
src/module/rules/rule-element/token-light.ts
src/styles/item/_rules.scss
static/templates/items/rules/token-light.hbs
types/foundry/client/pixi/webgl/shaders/sampler.d.ts

Add form for `TokenLightRuleElement`

---

src/module/rules/rule-element/multiple-attack-penalty.ts
static/lang/re-en.json

Also clean up value validation

Label MultipleAttackPenalty REs as "MAP ({label})"

---

src/module/system/check/dialog.ts
src/module/system/damage/dialog.ts
static/templates/chat/check-modifiers-dialog.hbs
static/templates/chat/damage/damage-modifier-dialog.hbs

Also kill the JQuery.
label instead of li is a bit odd but those tooltipster stylings need some work, and I'd rather not fix those right now :(

Add settings header button to damage dialog as well

---

src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/helpers.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/types.ts
src/module/actor/party/kingdom/values.ts
src/styles/actor/party/kingdom/_builder.scss
static/templates/actors/party/kingdom/builder.hbs
static/templates/actors/party/kingdom/partials/build-entry-boosts.hbs

Skip showing flaws in kingdom heartland and goverment

---

packs/iconics/korakai-level-5.json
packs/npc-gallery/priest-of-pharasma.json
packs/pathfinder-bestiary-3/valkyrie.json
packs/spell-effects/spell-effect-disrupting-weapons.json
packs/spells/disrupting-weapons.json
packs/stolen-fate-bestiary/svaryr-commander.json

Also refresh copies of Disrupting Weapons.

Select better icon for spell Disrupting Weapons

---

packs/ancestryfeatures/claws.json
packs/feats/razor-claws.json
packs/feats/sharp-fangs.json

Needs to be brawling to work with [Iruxi Unarmed Cunning](https://2e.aonprd.com/Feats.aspx?ID=1059).
Removed by 9c794f2242f78960365a0a597f27d5b152187d37.

Restore brawling group to Sharp Fangs

---

src/module/actor/party/document.ts
src/module/actor/party/kingdom/builder.ts
src/module/actor/party/kingdom/helpers.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/types.ts
src/module/actor/party/kingdom/values.ts
src/module/actor/party/types.ts
src/styles/actor/party/kingdom/_builder.scss
src/styles/actor/party/kingdom/_features.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/builder.hbs
static/templates/actors/party/kingdom/partials/build-entry-boosts.hbs
static/templates/actors/party/kingdom/tabs/features.hbs

https://github.com/foundryvtt/pf2e/assets/1286721/f6322960-c82b-4651-a7c7-b6e0ba326484

Grant kingdom government feat

---

packs/paizo-pregens/bottlespeaker-level-4.json
packs/paizo-pregens/fluff-fang-level-4.json
packs/paizo-pregens/popcorn-level-4.json
packs/paizo-pregens/reaching-rings-level-4.json

Update skill proficiencies on all 4 pregens
Add Gnomish and 1 more replacement lockpick to Reaching Rings
Add Halfling, Kelish, to Fluff Fang. Replace leather armor with studded leather.

Fix skills, languages, items in A Few Flowers More pregens

---

src/module/actor/base.ts
src/module/actor/values.ts
src/module/migration/migrations/866-link-to-actor-size-again.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/module/scene/token-document/document.ts
src/module/scene/token-document/sheet.ts

Its a bit odd migrating for this when we usually handle this by updating the form such that it resolves the field, but it be what it be.

Fix parties being token size linked

---

src/module/actor/sheet/base.ts

(and kingdom activities).
This is a bugfix since hovering over the item icons shows the send to chat message but doesn't do anything on click.

Allow players to send loot and party items to chat

---

src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_activities.scss
src/styles/actor/party/kingdom/_index.scss
static/templates/actors/partials/modifiers-tooltip.hbs
static/templates/actors/party/kingdom/tabs/ongoing.hbs

Also players can see modifiers and such

Update styling for players viewing kingdom activities

---

src/module/item/sheet/rule-element-form/base.ts
src/module/item/sheet/rule-element-form/token-light.ts
src/module/rules/rule-element/roll-note.ts

Also fix token light crash for non-embedded items

Fix null title regression in roll notes

---

src/module/apps/compendium-browser/tabs/bestiary.ts
src/module/apps/compendium-browser/tabs/equipment.ts
src/module/apps/compendium-browser/tabs/hazard.ts

Also remove unnecessary source editing in equipment tab class

Reduce block nesting in compendium browser tab classes

---

src/module/actor/party/kingdom/chat.ts
src/module/actor/party/kingdom/helpers.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/module/apps/sidebar/chat-log.ts
src/styles/actor/party/kingdom/_chat.scss
src/styles/actor/party/kingdom/_index.scss
src/styles/actor/party/kingdom/_main.scss
src/styles/actor/party/kingdom/_ongoing.scss
src/styles/actor/party/kingdom/_world.scss
src/styles/ui/_roll-modifiers-dialog.scss
static/lang/kingmaker-en.json
static/templates/actors/party/kingdom/collection.hbs

Collect kingdom resource in chat instead of dialog

---

src/module/apps/compendium-browser/index.ts
src/module/apps/compendium-browser/loader.ts

Fix browsing compendiums with multiple actor/item subtypes

---

src/module/item/sheet/base.ts
src/module/item/sheet/rule-element-form/base.ts
src/styles/item/_index.scss
src/styles/item/_rules.scss
static/templates/items/rules/multiple-attack-penalty.hbs

Also guarantee presence of `object` for actual forms

Standardize prefix for IDs in RE form

---

packs/equipment/ring-of-observation-greater.json
packs/equipment/ring-of-observation-lesser.json
packs/equipment/ring-of-observation-moderate.json

Also update description formatting.
Closes https://github.com/foundryvtt/pf2e/issues/10316

Fix usage and bulk of Ring of Observation

---

src/module/actor/party/kingdom/schema.ts
src/module/actor/party/kingdom/sheet.ts
src/styles/actor/party/kingdom/_index.scss
src/styles/actor/party/kingdom/_world.scss
static/templates/actors/party/kingdom/tabs/world.hbs

I can''t figure out how to make RecordField's type play along, but I don't have time to figure that out, so there's some casting / filtering in here based on what I felt was convenient at the time.

Implement resorting for kingdom settlements

---

static/lang/re-en.json

Fix Dead Faine's toggle label to off-guard

---

src/module/item/sheet/rule-element-form/base.ts
src/module/rules/rule-element/data.ts

With the move also coerce empty strings to zero.

Move resolvable value cleaning to `ResolvableValueField`

---

src/module/item/sheet/rule-element-form/base.ts

To test this bug, take an aura rule element and then delete the border color. It'll reset back to black, but you'll see `"brackets": {}` in the data if you go to edit it. This attempts to handle such cases.
I figured destructuring instead of mergeObject() was fine because the algorithm was recursive anyways.

Fix re form initial value tests for objects with cleaned values

---

src/styles/packs/_index.scss

Fix overflow in Compendium Browser settings tab

---

src/module/rules/rule-element/multiple-attack-penalty.ts

This reverts commit 6b59f26155be8580f829d8501c337e31c008396c.
Closes #10392

Revert "Predicate-test MultipleAttackPenalty REs (#10220)"

---

src/module/item/sheet/rule-element-form/flat-modifier.ts
src/module/rules/rule-element/base.ts
static/templates/items/rules/flat-modifier.hbs

Localize type choices in flat modifier form

---

src/module/chat-message/listeners/cards.ts

Allow all users to expand collapsed action descriptions

---

src/module/rules/rule-element/base-speed.ts

Fix `BaseSpeedRuleElement` selector assignment

---

packs/abomination-vaults-bestiary/shanrigol-behemoth.json
packs/abomination-vaults-bestiary/shanrigol-heap.json
packs/pfs-season-3-bestiary/shanrigol-mound.json

Also Shanrigol Heap's rarity changed in the hardcover.

Unify inline damage links for Shanrigol's Sapping Squeeze

---

static/templates/chat/check/roll.hbs

Closes https://github.com/foundryvtt/pf2e/issues/10468

Fix issue with showing critical damage cue when metagame settings should prevent it

---

packs/feat-effects/effect-lock-on.json
packs/feats/lock-on.json
static/lang/re-en.json

Automate Lock On feat

---

build/lib/extractor.ts

Convert hyphen-like and dash characters to hyphens and HTML entities

---

packs/agents-of-edgewatch-bestiary/chalky.json
packs/extinction-curse-bestiary/darklands-alchemical-golem.json
packs/pathfinder-bestiary/alchemical-golem.json
packs/the-slithering-bestiary/alchemical-golem-slithering.json
static/lang/re-en.json

Also unify bomb damage and fix some formatting.

Add automation for Alchemical Golem's Alchemical Injection

---

src/module/actor/helpers.ts
src/module/item/sheet/rule-element-form/aura.ts
src/module/rules/rule-element/aura.ts
src/module/system/schema-data-fields.ts
src/styles/item/_index.scss
src/styles/item/_rules.scss
static/templates/items/rules/aura.hbs

[Screencast from 10-01-2023 04:33:57 AM.webm](https://github.com/foundryvtt/pf2e/assets/106829671/d799e1dd-18bf-4b8f-aa1c-b748cd6710ea)

Add explicit options to set aura highlight/border color to user color

---

src/module/item/sheet/rule-element-form/base.ts
src/styles/item/_rules.scss
static/lang/re-en.json
static/templates/items/rules/outer.hbs

Include priority in header for rule element forms

---

packs/classfeatures/heavy-construction.json

Also set explicit label for Heavy Construction's defense proficiency

Remove change to dex cap in Heavy Construction modification

---

src/module/actor/character/elemental-blast.ts
src/module/item/spell/document.ts
src/module/system/damage/dialog.ts
src/module/system/damage/formula.ts
src/module/system/damage/types.ts
src/module/system/damage/weapon.ts
src/module/system/text-editor.ts
static/templates/chat/damage/damage-modifier-dialog.hbs

Also wires up the damage dialog into elemental blast.

Rename CreateDamageFormulaParams to DamageFormulaData

---

src/global.ts
src/module/canvas/status-effects.ts
src/scripts/config/index.ts
vite.config.ts

Not sure if this is the best way to handle it but it works.
Before:
After:

Prevent bundling of translation JSON files

---

src/module/actor/inventory/bulk.ts
static/templates/actors/partials/encumbrance.hbs

Add tooltip breakdown to encumbrance and max bulks

---

src/module/actor/character/document.ts

Fix WeaponPotency RE not adding "magical" trait to weapons

---

src/module/actor/base.ts
src/module/actor/creature/helpers.ts
src/module/actor/data/base.ts
src/module/actor/data/iwr.ts
src/module/actor/hazard/document.ts
src/module/actor/sheet/popups/iwr-editor.ts
src/module/rules/rule-element/battle-form/rule-element.ts
src/module/rules/rule-element/iwr/base.ts
src/module/rules/rule-element/iwr/immunity.ts
src/module/rules/rule-element/iwr/resistance.ts
src/module/rules/rule-element/iwr/weakness.ts
src/module/system/damage/iwr.ts
src/scripts/config/iwr.ts

Add support for custom IWR

---

packs/blood-lords-bestiary/harmony-in-agony.json
packs/blood-lords-bestiary/hyrune-loxenna.json
packs/blood-lords-bestiary/kemnebi.json
packs/blood-lords-bestiary/vampire-guardian.json
packs/blood-lords-bestiary/vice-chancellor-vikroti-stroh.json
packs/blood-lords-bestiary/weeping-jack.json
packs/book-of-the-dead-bestiary/minister-of-tumult.json
packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
packs/extinction-curse-bestiary/iffdahsil.json
packs/extinction-curse-bestiary/zinogyvaz.json
packs/kingmaker-bestiary/vordakai.json
packs/pathfinder-bestiary/vampire-count.json
packs/pathfinder-bestiary/vampire-mastermind.json
packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
packs/pfs-season-4-bestiary/evasive-vampire-count.json
packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
static/lang/re-en.json

Can't double-check the PFS NPCs as I don't have the PDFs, but they look similar.
Leverages https://github.com/foundryvtt/pf2e/pull/10579
Closes https://github.com/foundryvtt/pf2e/issues/9709

Update vampire physical exception to magical cold iron, magical darkwood, magical silver

---

src/styles/item/_rules.scss
static/templates/items/rules/grant-item.hbs

Fix regression in styling of checkboxes on GrantItem form

---

src/module/rules/rule-element/grant-item/rule-element.ts
src/module/rules/rule-element/grant-item/schema.ts
src/styles/item/_index.scss
src/styles/item/_rules.scss
static/templates/items/rules/grant-item.hbs

No deprecation period: this feature has been flaky from the start and never maintained since.

Drop support for `replaceSelf` in GrantItem RE

---

packs/blood-lords-bestiary/harmony-in-agony.json
packs/blood-lords-bestiary/hyrune-loxenna.json
packs/blood-lords-bestiary/kemnebi.json
packs/blood-lords-bestiary/vampire-guardian.json
packs/blood-lords-bestiary/vampire-taviah.json
packs/blood-lords-bestiary/vice-chancellor-vikroti-stroh.json
packs/blood-lords-bestiary/weeping-jack.json
packs/book-of-the-dead-bestiary/minister-of-tumult.json
packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
packs/extinction-curse-bestiary/iffdahsil.json
packs/extinction-curse-bestiary/zinogyvaz.json
packs/kingmaker-bestiary/vordakai.json
packs/pathfinder-bestiary/vampire-count.json
packs/pathfinder-bestiary/vampire-mastermind.json
packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
packs/pfs-season-4-bestiary/evasive-vampire-count.json
packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
packs/stolen-fate-bestiary/kannijo.json
static/lang/re-en.json

Add custom cold iron bludgeoning exception to Vampire Taviah. Add Vampire Weaknesses item to Weeping Jack.
Add physical resistance to Kannijo.

Move vampire custom resistances to rule elements

---

src/styles/actor/_index.scss
src/styles/actor/npc/_index.scss
src/styles/legacy/_pf2e.scss
static/templates/actors/limited/npc-sheet.hbs
static/templates/actors/npc/partials/sidebar.hbs
static/templates/actors/npc/simple-sheet.hbs

- Fix sidebar class in limited and simple sheets
- Hide private notes from non-GMs in simple sheet
- Fix positioning of show-image anchor

Normalize some differences among NPC sheets

---

src/styles/actor/npc/_index.scss

Makes private notes easier to edit

Add min height to npc notes editing

---

packs/age-of-ashes-bestiary/charau-ka-dragon-priest.json
packs/age-of-ashes-bestiary/charau-ka.json
packs/age-of-ashes-bestiary/malarunk.json
packs/age-of-ashes-bestiary/racharak.json
packs/mwangi-expanse-bestiary/charau-ka-acolyte-of-angazhan.json
packs/mwangi-expanse-bestiary/charau-ka-butcher.json
packs/mwangi-expanse-bestiary/charau-ka-warrior.json

Also fix duplicate ranged Spear strike for Charau-ka Acolyte of Angazhan (one should be melee)

Add automation for Thrown Weapon Mastery

---

src/module/scene/helpers.ts

Alternatively we could try to figuring out "using" and make the lock a `await using lock = createLock()`. Perhaps if we need to lock often.

Guarantee aura lock is released even if it errors

---

packs/feat-effects/effect-kinetic-aura.json
packs/feat-effects/effect-thermal-nimbus-cold.json
packs/feat-effects/effect-thermal-nimbus-fire.json
packs/feat-effects/stance-thermal-nimbus.json

In turn set thermal nimbus effects to item level, which will be set by the aura.

Set kinetic aura level to actor level

---

build/lib/compendium-pack.ts
build/run-migration.ts
src/module/actor/character/data.ts
src/module/actor/character/document.ts
src/module/actor/character/feats.ts
src/module/actor/character/sheet.ts
src/module/actor/party/kingdom/model.ts
src/module/actor/party/kingdom/sheet.ts
src/module/item/abc/sheet.ts
src/module/item/background/document.ts
src/module/item/base.ts
src/module/item/class/document.ts
src/module/item/feat/data.ts
src/module/item/feat/document.ts
src/module/item/feat/types.ts
src/module/item/feat/values.ts
src/module/migration/migrations/834-feat-categories.ts
src/module/migration/migrations/875-set-innovation-id-early.ts
src/module/migration/migrations/876-feat-level-taken.ts
src/module/migration/migrations/index.ts
src/module/migration/runner/base.ts
src/scripts/config/index.ts
static/templates/actors/character/partials/feat-slot.hbs
static/templates/actors/character/tabs/feats.hbs
static/templates/actors/party/kingdom/tabs/features.hbs

Record level taken on feats

---

src/module/apps/compendium-migration-status.ts
src/module/apps/sidebar/compendium-directory.ts
src/module/migration/runner/base.ts
src/module/migration/runner/index.ts
src/styles/system/_compendium-migration-status.scss
src/styles/system/_index.scss
static/lang/en.json
static/templates/system/compendium-migration-status.hbs
types/foundry/client/data/collections/compendium-collection.d.ts

Also fixes compendium migration but since its not a released feature and the bug only occurred this cycle (?), we don't really need to add the bugfix tag.

Add dialog to perform compendium migrations

---

packs/pathfinder-bestiary-2/yellow-musk-brute.json
packs/pathfinder-bestiary-2/yellow-musk-thrall.json

Automation based on hp not currently possible, as "hp-remaining" is not available early enough.

Add toggle for Limb Extension

---

packs/stolen-fate-bestiary/svaryr-soldier.json

Closes https://github.com/foundryvtt/pf2e/issues/10670

Add missing Zeal for Battle spell to Svaryr Soldier

---

packs/equipment-effects/effect-breastplate-of-the-mountain.json
packs/equipment/amulet-of-the-third-eye.json
packs/equipment/breastplate-of-the-mountain.json

Add icon to Breastplate of the Mountain

---

packs/feat-effects/effect-shattershields.json
packs/feat-effects/stance-shattershields.json
packs/feats/shattershields.json

Add effect for Shattershields

---

packs/equipment/blackaxe.json

Treerazer has no time for toy axes.

Make Blackaxe huge

---

src/module/actor/character/elemental-blast.ts

(instead of looking for effect item)

Check for kinetic gate effect roll option in elemental blast

---

src/styles/actor/_red-action-boxes.scss
static/templates/actors/npc/partials/attack.hbs

Also convert titles into tooltips

Restore pre-expanded NPC attack descriptions

---

packs/extinction-curse-bestiary/gluttondark-babau.json
packs/pathfinder-bestiary-2/babau.json

Remove untyped damage link from Babau's Grievous Strike and add Note

---

src/module/actor/conditions.ts
static/templates/actors/npc/sheet.hbs

Closes https://github.com/foundryvtt/pf2e/issues/10732

Fix NPC Effects tab being dimmed when conditions are applied

---

src/scripts/macros/rest-for-the-night.ts
static/templates/actors/character/partials/sidebar.hbs

Fix stamina max value on character sheet and stamina restoration in rest for the night macro

---

packs/equipment/necrotic-bomb-greater.json
packs/equipment/necrotic-bomb-lesser.json
packs/equipment/necrotic-bomb-major.json
packs/equipment/necrotic-bomb-moderate.json

Also remove unneeded success Note

Remove inline damage links from Necrotic Bomb

---

src/module/system/damage/formula.ts

Don't parenthesis-wrap "doubled" flavor modifier in damage formulas

---

packs/equipment/lancer.json

Add crossbow other-tag to Lancer weapon

---

packs/classfeatures/rune-patron.json
packs/classfeatures/way-of-the-spellshot.json

Closes https://github.com/foundryvtt/pf2e/issues/10760

Add otherTags to Rune Patron and Way of the Spellshot

---

src/module/actor/creature/spell-preparation-sheet.ts
src/styles/actor/_spell-preparation.scss
static/lang/en.json
static/templates/actors/spellcasting-prep-sheet.hbs
types/foundry/client/application/base.d.ts

Add search input on spell preparation sheet

---

packs/classfeatures/gate-junction.json
static/lang/re-en.json

Waiting for the item bonus to attack rolls to be in flags.

Automate Kineticist critical junctions

---

src/module/system/damage/formula.ts

Parenthesis-wrap dice-doubled precision damage

---

packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-20.json

Add missing spells to FotRP actor

---

packs/feat-effects/effect-shattershields.json
packs/feat-effects/stance-shattershields.json

Add icons for shattershields

---

src/module/rules/rule-element/crit-spec.ts

Add support for alternative critical specialization damage

---

packs/abomination-vaults-bestiary/jafaki.json
packs/blood-lords-bestiary/pesgahi-the-poisoner.json
packs/fall-of-plaguestone/the-sculptor.json
packs/fall-of-plaguestone/vilree.json
packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-14.json
packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-16.json
packs/gatewalkers-bestiary/etward-ritalson.json
packs/npc-gallery/grave-robber.json
packs/outlaws-of-alkenstar-bestiary/shoma-lyzerius.json
packs/pathfinder-bestiary/ratfolk-grenadier.json
packs/pfs-season-2-bestiary/strak-5-6.json
packs/pfs-season-2-bestiary/strak-7-8.json
packs/strength-of-thousands-bestiary/fire-pot-ubanu.json

Also fix bomb counts on Ratfolk Grenadier and name Shoma Lyzerius' infused items as such

Add infused trait to several NPC items

---

src/module/rules/rule-element/iwr/immunity.ts
src/module/rules/rule-element/iwr/weakness.ts

Y'know that thing that lets you define custom resistances?    
Yeah, that, but for weaknesses and immunities too, thanks.

Include custom IWR definitions in weaknesses and immunities

---

packs/other-effects/effect-scouting-incredible-scout.json
packs/other-effects/effect-scouting.json

scouting effect icon is now shown and has removeAfterRoll

Brush up effects for scouting

---

src/module/item/physical/sheet.ts
src/module/item/sheet/base.ts
src/styles/_globals.scss
src/styles/item/_index.scss
src/styles/lib/_tooltip.scss
static/templates/chat/damage/damage-card-details.hbs
static/templates/items/ancestry-details.hbs
static/templates/items/armor-details.hbs
static/templates/items/armor-sidebar.hbs
static/templates/items/background-details.hbs
static/templates/items/class-details.hbs
static/templates/items/consumable-details.hbs
static/templates/items/heritage-sidebar.hbs
static/templates/items/kit-details.hbs
static/templates/items/persistent-damage-dialog.hbs
static/templates/items/rules-panel.hbs
static/templates/items/rules/aura.hbs
static/templates/items/sheet.hbs
static/templates/items/spell-overlay.hbs
static/templates/items/weapon-details.hbs
static/templates/items/weapon-sidebar.hbs

Use core tooltip API instead of tooltipster on item sheets

---

static/templates/items/sheet.hbs

Consistent with how they were when using tooltipster

Set tooltip direction to "UP" on item sheets

---

src/module/rules/rule-element/grant-item/rule-element.ts

Set in-memory-only grants in AE-like phase

---

src/styles/_fonts.scss
src/styles/_tags.scss
src/styles/actor/npc/_index.scss
src/styles/packs/_tab.scss

Clean up tag styling; prevent aberrant results with longer tags

---

packs/feat-effects/effect-devise-a-stratagem.json

Closes #10821, depends on #10824

Expire Devise a Stratagem effect at end of current round

---

packs/spell-effects/spell-effect-righteous-might.json

Add size increase for heightened Righteous Might spell effect

---

src/module/actor/character/attribute-builder.ts
src/module/actor/character/sheet.ts
src/styles/actor/character/_attribute-builder.scss
static/templates/actors/character/attribute-builder.hbs
static/templates/actors/character/partials/strike.hbs

Use core tooltip API for pair of tooltips in attribute builder

---

src/styles/_tags.scss
static/templates/actors/partials/item-summary.hbs
static/templates/chat/action-card.hbs
static/templates/chat/affliction-card.hbs
static/templates/chat/armor-card.hbs
static/templates/chat/backpack-card.hbs
static/templates/chat/campaign-feature-card.hbs
static/templates/chat/condition-card.hbs
static/templates/chat/consumable-card.hbs
static/templates/chat/effect-card.hbs
static/templates/chat/equipment-card.hbs
static/templates/chat/feat-card.hbs
static/templates/chat/melee-card.hbs
static/templates/chat/spell-card.hbs
static/templates/chat/strike-card.hbs
static/templates/chat/treasure-card.hbs
static/templates/chat/weapon-card.hbs

Catch up item-message trait tooltips with similar message types

---

src/module/actor/base.ts
src/module/actor/character/document.ts
src/module/actor/familiar/document.ts
src/module/actor/npc/document.ts
src/module/actor/party/document.ts

Ensure level and infused reagents are integer values

---

src/module/scene/token-document/document.ts

Fix stamina token bar attribute

---

src/module/actor/character/feats.ts

Fix dropping feats in campaign feat group

---

src/module/item/abstract-effect/document.ts

Taking a small risk here and will monitor it during the dev cycle, but I _think_ the precautions that were taken before are no longer needed in V11.

Simplify `AbstractEffect#origin` getter

---

packs/kingmaker-bestiary/the-beast.json

Closes https://github.com/foundryvtt/pf2e/issues/10857

Fix size of the Beast

---

packs/kingmaker-bestiary/bloom-of-lamashtu.json

Closes https://github.com/foundryvtt/pf2e/issues/10835

Fix resistances and weaknesses of Bloom of Lamashtu

---

src/module/actor/helpers.ts

Fix setting of attribute domain for strikes using weapons with finesse

---

packs/feats/overdrive-ally.json

Makes Overdrive Ally an action not a passive

---

src/module/canvas/token/aura/map.ts
src/module/canvas/token/aura/renderer.ts
src/module/canvas/token/object.ts
types/foundry/client/pixi/placeable.d.ts
types/foundry/client/pixi/placeables/token.d.ts

[swimmers](https://github.com/foundryvtt/pf2e/assets/106829671/146a0f6c-e390-485e-a656-84a164588041)

Draw aura textures underneath tokens

---

src/module/item/ancestry/document.ts
src/module/system/settings/homebrew/helpers.ts

Also include language removal in homebrew settings migration
Closes #10911

Check validity of languages from ancestry before adding to PC

---

src/module/actor/conditions.ts
src/util/delegated-collection.ts

I tested with Amiri's sword, let me know if I should do a different test.

Use delegated collection for actor conditions

---

packs/feats/predatory-claws.json
src/module/actor/character/document.ts
src/module/actor/data/base.ts
src/module/actor/helpers.ts
src/module/actor/sheet/base.ts
src/module/item/weapon/data.ts
src/module/rules/rule-element/strike.ts
src/scripts/macros/hotbar.ts
src/styles/actor/character/_actions.scss
src/styles/actor/tabs/_actions.scss
static/lang/en.json
static/templates/actors/character/partials/strike.hbs

Make PC attacks that require free hands always visible on sheet

---

packs/fists-of-the-ruby-phoenix-bestiary/spirit-turtle.json

Also add aura for Pacifying Aura, add Constrict ability, and add damage links for Unbalancing Stomp.

Add automation for Spirit Turtle's Environmental Balance

---

src/module/apps/sidebar/actor-directory.ts
src/scripts/hooks/ready.ts

Move initial expanding of active party folder to `ActorDirectoryPF2e#render`

---

src/module/actor/actions/single-check.ts

Allow the use of `options.difficultyClass` in `SingleCheckActionVariant#use`

---

src/module/actor/base.ts
src/module/apps/sidebar/chat-log.ts
src/module/item/spell/document.ts
src/module/system/damage/formula.ts
src/module/system/damage/roll.ts
src/module/system/damage/types.ts
src/styles/ui/sidebar/chat/_damage.scss
static/lang/en.json
static/templates/chat/spell-card.hbs
static/templates/dice/damage-roll.hbs

Just laying some groundwork; not doing much with it yet.

Add support for designating damage instances as being healing

---

src/module/scene/token-document/document.ts

Restore editability of stamina & resolve from token HUD

---

src/module/system/damage/dialog.ts
static/lang/en.json
static/templates/chat/damage/damage-modifier-dialog.hbs

I'm not certain about the labels, but I'm sure people will have ideas as this gets more use.

Include dice overrides in damage dialog

---

src/module/actor/base.ts
src/module/actor/types.ts
src/module/rules/rule-element/aura.ts

Add support for aura effect alterations

---

packs/rage-of-elements-bestiary/ifrit-shuyookh.json

Add Exploit Regret reaction to Ifrit Shuyookh
